### ISSUE TITLE
Problem related to running the app

### ISSUE THREAD

**Issue by Lambrusko** [DIGITALCRIMINAL/OnlyFans#1]
I filled that in the .json file and I don't know how to run the .py file , i used powershell and nothing

**Comment by DIGITALCRIMINAL** [comment]
You figured it out?

**Comment by Lambrusko** [comment]
well yes but when i type an username for example its said that user not found

**Comment by Lambrusko** [comment]
do i have to subscribe to that user on onlyfans?

**Comment by DIGITALCRIMINAL** [comment]
Yes you have to be subscribed to the user
