### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Frangus90** [DIGITALCRIMINAL/OnlyFans#10]
Im quite the beginner with python. 

I have installed all the requirements and have verified that the request module has been downloaded but im still getting this error.

Traceback (most recent call last):
  File "C:\OnlyFans-master\OnlyFans.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by DIGITALCRIMINAL** [comment]
Do you have Python 3.7 installed?

**Comment by Frangus90** [comment]
Yes i have 3.7.3 installed and PIP installed correctly from the requirements.txt

**Comment by DIGITALCRIMINAL** [comment]
Did you manage to fix it?
