### ISSUE TITLE
Auth Attempt and User Not Found 

### ISSUE THREAD

**Issue by Daironman78** [DIGITALCRIMINAL/OnlyFans#1001]
Ok i need an expert to help me badly!!! I am back having issues with this Scraper and/or python. I figured out how to fix my issue a couple weeks back and was getting my content just fine. Then today, I go on and try to scrape and get this mess again. Can someone please help me ASAP . I have tried everything and all the info in the Json file is correct according to the Network. I dont know why this is happening again but can someone please let me know what I need to do: 

Pausing scraper for 0 seconds.
Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan | x = Exit
0
Auth (V1)
Auth Attempt 1/10
User not found
Auth Attempt 2/10
User not found
Auth Attempt 3/10
User not found
Auth Attempt 4/10
User not found
Auth Attempt 5/10
User not found
Auth Attempt 6/10
User not found
Auth Attempt 7/10
User not found
Auth Attempt 8/10
User not found
Auth Attempt 9/10
User not found
Auth Attempt 10/10
User not found
Names: Username = username | 0 = All

**Comment by Themisssingport** [comment]
Which version are you using? it seems like something is broken because others are having issues with auth

**Comment by cryptixcoder** [comment]
I'm having this issue too, I'm using the older version that was still working.

**Comment by DIGITALCRIMINAL** [comment]
Literally no point opening a duplicate issue

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1001
