### ISSUE TITLE
KeyError: 'auth'

### ISSUE THREAD

**Issue by menooneelse** [DIGITALCRIMINAL/OnlyFans#1004]
Hey,
i tried to download some stuff. But i got this error. I got the auth file from the "OnlyFans Cookie Helper" Add-On.
I re-intsalled python and run the pip command.
I run PowerShell as admin but nothing changed

Does somebody know what I did wrong?

**_This it what I get:_**

python.exe .\start_ofd.py

Site: 0 = onlyfans | x = Exit
0
Session IP: XX.XX.XX.XX

Traceback (most recent call last):
  File "C:\Users\ME\Documents\Bilder\OnlyFans-v.6.4.4\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\ME\Documents\Bilder\OnlyFans-v.6.4.4\datascraper\main_datascraper.py", line 60, in start_datascraper
    apis = main_helper.process_profiles(
  File "C:\Users\ME\Documents\Bilder\OnlyFans-v.6.4.4\helpers\main_helper.py", line 602, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'

**Comment by Digigi777** [comment]
Hey, did you manage to find auth_hash and auth_uniq for the profile section? If so can you message me, I need help please

**Comment by jimcrapo** [comment]
Having the same issue

Site: 0 = onlyfans | x = Exit
0
Session IP: X.X.X.X

Traceback (most recent call last):
File "F:\rip\start_ofd.py", line 43, in
apis = main_datascraper.start_datascraper(json_config, site_name_lower)
File "F:\rip\datascraper\main_datascraper.py", line 60, in start_datascraper
apis = main_helper.process_profiles(
File "F:\rip\helpers\main_helper.py", line 600, in process_profiles
temp_json_auth = ujson.load(
ValueError: Trailing data

requirements are installed:

Requirement already satisfied: requests in c:\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (2.25.0)
Requirement already satisfied: beautifulsoup4 in c:\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (4.9.3)
Requirement already satisfied: urllib3 in c:\python\python39\lib\site-packages (from -r requirements.txt (line 3)) (1.26.2)
Requirement already satisfied: win32-setctime in c:\python\python39\lib\site-packages (from -r requirements.txt (line 4)) (1.0.3)
Requirement already satisfied: pysocks in c:\python\python39\lib\site-packages (from -r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: psutil in c:\python\python39\lib\site-packages (from -r requirements.txt (line 6)) (5.7.3)
Requirement already satisfied: python-dateutil in c:\python\python39\lib\site-packages (from -r requirements.txt (line 7)) (2.8.1)
Requirement already satisfied: lxml in c:\python\python39\lib\site-packages (from -r requirements.txt (line 8)) (4.6.1)
Requirement already satisfied: mergedeep in c:\python\python39\lib\site-packages (from -r requirements.txt (line 9)) (1.3.0)
Requirement already satisfied: jsonpickle in c:\python\python39\lib\site-packages (from -r requirements.txt (line 10)) (1.4.1)
Requirement already satisfied: deepdiff[murmur] in c:\python\python39\lib\site-packages (from -r requirements.txt (line 11)) (5.0.2)
Requirement already satisfied: numpy==1.19.3 in c:\python\python39\lib\site-packages (from -r requirements.txt (line 12)) (1.19.3)
Requirement already satisfied: ujson in c:\python\python39\lib\site-packages (from -r requirements.txt (line 13)) (4.0.1)
Requirement already satisfied: sqlalchemy==1.3.23 in c:\python\python39\lib\site-packages (from -r requirements.txt (line 14)) (1.3.23)
Requirement already satisfied: alembic in c:\python\python39\lib\site-packages (from -r requirements.txt (line 15)) (1.5.8)
Requirement already satisfied: tqdm in c:\python\python39\lib\site-packages (from -r requirements.txt (line 16)) (4.60.0)
Requirement already satisfied: selenium in c:\python\python39\lib\site-packages (from -r requirements.txt (line 17)) (3.141.0)
Requirement already satisfied: selenium-wire==2.1.2 in c:\python\python39\lib\site-packages (from -r requirements.txt (line 18)) (2.1.2)
Requirement already satisfied: user_agent in c:\python\python39\lib\site-packages (from -r requirements.txt (line 19)) (0.1.9)
Requirement already satisfied: python-editor>=0.3 in c:\python\python39\lib\site-packages (from alembic->-r requirements.txt (line 15)) (1.0.4)
Requirement already satisfied: Mako in c:\python\python39\lib\site-packages (from alembic->-r requirements.txt (line 15)) (1.1.4)
Requirement already satisfied: soupsieve>1.2 in c:\python\python39\lib\site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: ordered-set>=4.0.1 in c:\python\python39\lib\site-packages (from deepdiff[murmur]->-r requirements.txt (line 11)) (4.0.2)
Requirement already satisfied: mmh3 in c:\python\python39\lib\site-packages (from deepdiff[murmur]->-r requirements.txt (line 11)) (2.5.1)
Requirement already satisfied: importlib-metadata in c:\python\python39\lib\site-packages (from jsonpickle->-r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\python\python39\lib\site-packages (from python-dateutil->-r requirements.txt (line 7)) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python\python39\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\python\python39\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\python39\lib\site-packages (from requests->-r requirements.txt (line 1)) (2020.11.8)
Requirement already satisfied: zipp>=0.5 in c:\python\python39\lib\site-packages (from importlib-metadata->jsonpickle->-r requirements.txt (line 10)) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\python\python39\lib\site-packages (from Mako->alembic->-r requirements.txt (line 15)) (1.1.1)

config and auth have been configured.

**Comment by jimcrapo** [comment]
I fixed this by using a fresh auth.json and NOT using the cookie helper to fill in the settings. May want to remove that suggestion of using it from the first page to avoid any other confusion.

**Comment by GreenMonkey1** [comment]
> I fixed this by using a fresh auth.json and NOT using the cookie helper to fill in the settings. May want to remove that suggestion of using it from the first page to avoid any other confusion.

can you please explain what you did different ,  
did you delete it and create a new auth.json 

or just edit the content ??
