### ISSUE TITLE
Can't find auth_hash and auth_uniq "Please help me I can pay for help"

### ISSUE THREAD

**Issue by Digigi777** [DIGITALCRIMINAL/OnlyFans#1005]
Hey, I can't find auth_hash and auth_uniq anywhere when I inspect the page. I can find anything else but this. I'm on the network debugger and I'm on the request header section and I still can't find it. Please help me.

**Comment by E0911CD45B19686** [comment]
If you don't have 2fa enabled you won't find them, leave them blank.

**Comment by Digigi777** [comment]
> If you don't have 2fa enabled you won't find them, leave them blank.

alright thanks, now when I try to launch the python script it closes itself  right away. Do you what that issue could be? I was using this script about a month ago and everything was fine then I deleted it and re download and now it's not launching.

**Comment by nappyapp** [comment]
Run it from a command prompt/terminal and see why it's crashing

**Comment by Digigi777** [comment]
> Run it from a command prompt/terminal and see why it's crashing

this is what I get

Microsoft Windows [Version 10.0.19042.906]
(c) Microsoft Corporation. All rights reserved.

C:\Users\\Desktop\OnlyFans-master>python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\\Desktop\OnlyFans-master\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "C:\Users\\Desktop\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\\Desktop\OnlyFans-master\helpers\main_helper.py", line 5, in <module>
    from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'

C:\Users\\Desktop\OnlyFans-master>

**Comment by nappyapp** [comment]
Run this:

`python3 -m pip install -r requirements.txt`

or just

`pip3 install -r requirements.txt`

If those don't work take the 3 out and try again
