### ISSUE TITLE
Settings folder not being created

### ISSUE THREAD

**Issue by u5553890** [DIGITALCRIMINAL/OnlyFans#1006]
Ive been using an older version of the downloader successfully for a while now then one day like last week it just stopped as ive seen has happened to plenty of people here. I tried updating to the newest version of the downloader and cant seem to get it to work. i downloaded C++ build tools and installed the new requirements file but this still isnt working. I run the program the python window pops up and says to press enter and when i do it just closes and nothing changes/happens. I assume im missing something obvious and being an idiot but I'm pretty stuck right now

**Comment by nappyapp** [comment]
Try a clean install in a new folder

**Comment by u5553890** [comment]
Ive tried different folder and different drive and get the same results

**Comment by LunarPenguin** [comment]
Can you post a log or screenshot of the (error)message you receive?

**Comment by u5553890** [comment]
![Screenshot 2021-04-12 205826](https://user-images.githubusercontent.com/82281072/114481396-74350000-9bd2-11eb-8181-0423bb3c94ab.png)
![Screenshot 2021-04-12 205856](https://user-images.githubusercontent.com/82281072/114481397-74350000-9bd2-11eb-8ac1-c522b09bcdbd.png)


I dont really have any log nor do i get an error at all. heres the terminal window when i try to run it, I press enter like it says then nothing. I also included a screenshot of the folder after running that. I fully believe im doing something wrong/being an idiot so feel free to call me dumb lol

**Comment by nappyapp** [comment]
Looks like you're using the wrong version of python, see it's telling you
to use python 3.9. update to that and try again

**Comment by u5553890** [comment]
omfg i knew it was something stupid. i downloaded 3.9.4 but never uninstalled 3.7 so it was using that. and i thought that message was saying like "press enter to execute the script with python 3.9" Im an idiot, thanks!

**Comment by nappyapp** [comment]
You can close the issue if you got it working btw
