### ISSUE TITLE
Scraping Issues

### ISSUE THREAD

**Issue by NYfan0122** [DIGITALCRIMINAL/OnlyFans#1007]
Every time I try to scrape content from a profile, it says there's nothing to scrape. This account has 46 posts, so I know it has something, but nothing is downloading.

**Comment by neuri4848** [comment]
When you get to choose profile youre supposed to choose 0 or 1. The program will run then will give you a number for the model. Pick the model you want press enter and it will give you an option for what you want to scrape. Choose whatever you like and there you go.

**Comment by LunarPenguin** [comment]
Make sure your authentication is setup correctly, if done incorrectly the script can not login and cant find anything to scrape
