### ISSUE TITLE
program is scraping deleted messages from an account I didn't select

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINAL/OnlyFans#1008]
![image](https://user-images.githubusercontent.com/22129443/114293232-0d202a00-9ab2-11eb-9983-af0c87cdcd81.png)

![image](https://user-images.githubusercontent.com/22129443/114293210-e7932080-9ab1-11eb-890b-4275d8d4ae68.png)

**Comment by DIGITALCRIMINAL** [comment]
Set paid messages to false.
