### ISSUE TITLE
Scrapping videos to json file

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#101]
OnlyFans have changed their download links and the scrapper is not capturing the filenames for the json file.

**Comment by DIGITALCRIMINAL** [comment]
LMAO I just checked it out. They really messed it up.

**Comment by DIGITALCRIMINAL** [comment]
The good thing is we can now access the scraped links from any ip/computer.

**Comment by DIGITALCRIMINAL** [comment]
The newest commit fixes it if you want to download it now.

**Comment by zoopzorp** [comment]
I'm still seeing an issue on macOS. The `reformat` that sets `file_path` is returning only the directory to store the media in, so the `rsplit('/', 1)[-1]` will return an empty string, then when creating `download_path` it points to the directory only and fails to save.

**Comment by dilemmax** [comment]
> The newest commit fixes it if you want to download it now.

That was quick. Thank you!

**Comment by dilemmax** [comment]
I just tried the new commit on a new account and the filename column is still empty :(

**Comment by DIGITALCRIMINAL** [comment]
@dilemmax Ahh, I fixed it for Windows but not for Linux and Mac users. I've just updated the program with @zoopzorp fix.

I just released it.

**Comment by dilemmax** [comment]
cool. Thanks. I'm using the new version and it works! Thanks All!
