### ISSUE TITLE
"Databases is locked" error when scraping

### ISSUE THREAD

**Issue by salamihawk** [DIGITALCRIMINAL/OnlyFans#1011]
I've updated to the latest version and after choosing a site and a profile, it gets to the following point and then errors out:

Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

Anyone have any clue what's going on? I'm running the script from a Debian VM, but the script is stored on an SMB Server because that's where the downloads are, if that makes any difference.

**Comment by Jarsky** [comment]
I was getting the same issue, i added "nolock" to my /etc/fstab

e.g

`//storage/share /mnt/share cifs vers=3.0,credentials=/home/user/.smbcredentials,uid=nobody,iocharset=utf8,noperm,nolock 0 0`

but I think theres another issue, today im suddenly getting 

> PermissionError: [Errno 13] Permission denied
