### ISSUE TITLE
Unable to create session

### ISSUE THREAD

**Issue by Aer3x** [DIGITALCRIMINAL/OnlyFans#1015]
Unable to scrape, "Unable to create session" message and returns.

even after wiping conf files

```
Site: 0 = onlyfans | x = Exit
0
Proxy Not Set: None

Unable to create session
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit
0
Proxy Not Set: None

Unable to create session
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit
0
Proxy Not Set: None

Unable to create session
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit
```

**Comment by rssfed23** [comment]
I'm also getting this
```Successfully built 6862a5c132e5
Successfully tagged only-fans:latest
Proxy Not Set: None

Unable to create session
Pausing scraper for 0 seconds.
Proxy Not Set: None

Unable to create session
Pausing scraper for 0 seconds.
Proxy Not Set: None

Unable to create session
Pausing scraper for 0 seconds.
Proxy Not Set: None```

**Comment by rssfed23** [comment]
This seems to be an intermittent issue with OF for me. I've been able to create a session and scrape for the past 30 minutes, but now the error is happening again (after previously experiencing it before it started working again).

**Comment by Aer3x** [comment]
i found the issue
everytime i try to start the scraper it blocks a DNS request to `checkip.amazonaws.com` in my pihole.
unblocked it and its working again.
