### ISSUE TITLE
Thank you so much for this! Quick question

### ISSUE THREAD

**Issue by porncritic** [DIGITALCRIMINAL/OnlyFans#1016]
after choosing the profile I want I choose all, it downloads 18.6 GB but only 17.1 GB on disk. Also, I don't seem to get any paywalls. Any help would be nice, if not thats fine too, either way thank you for your work

**Comment by LunarPenguin** [comment]
the software wont download anything you have not paid for

**Comment by ProjektPremium** [comment]
> 
> 
> after choosing the profile I want I choose all, it downloads 18.6 GB but only 17.1 GB on disk. Also, I don't seem to get any paywalls. Any help would be nice, if not thats fine too, either way thank you for your work

Who is the creator you're trying to download?

**Comment by silverglade303** [comment]
I'm with you on this one, the FAQ says it will bypass paywalls but it does not seem to work.
