### ISSUE TITLE
user_agent required for: default?

### ISSUE THREAD

**Issue by uzodinmat** [DIGITALCRIMINAL/OnlyFans#1017]
Everything needed installed, I run the program and get "user_agent required for: default"? ....I'm a noob so please what am I doing wrong?

**Comment by LunarPenguin** [comment]
First of all, please read the `README.MD` file on the homepage of this repo that explains all you need to know.

In your OnlyFans scraper folder you will find a `.profiles` folder inside that folder is a `onlyfans` folder and inside that folder is the `default` folder you mentioned. inside that default folder is a `auth.json` file that you need to fill in with your OnlyFans information such as auth and user-agent.

So the final path is `.profiles/onlyfans/default/auth.json`

There is a example of the `auth.json` in the `README.MD` file i mentioned before on the homepage of this repo. and remember if you dont have something mentioned in the `auth.json` file, leave it as is (blank)

**Comment by Spidersavitch89** [comment]
I am also running into this issue. I'm running the docker image and it runs just fine the first go, but as soon as the container is exited, and I fire up another container I get this error.

I tried running the image both with `docker run -ti only-fans` which starts me off with the .settings and .profile prompts.

I then tried running `docker run -ti only-fans bash` and then `python start-ofd.py` which ended up with the same results. 

I also tried building the docker file again both with and without the volume mounts. no luck either.

looks like the volumes all mounted correctly and the auth and config files don't change between container runs. 

I did also try to run a `docker commit` to see if I could create a new image in a working state and then fire up a container from that image. No luck.

The only way to make it work seems to be to remove the auth and config files and let the start-ofd.py generate the new ones which is a bit of a drag grabbing id's and sess data each time I want to run the .py

**Comment by DIGITALCRIMINAL** [comment]
> First of all, please read the `README.MD` file on the homepage of this repo that explains all you need to know.
> 
> In your OnlyFans scraper folder you will find a `.profiles` folder inside that folder is a `onlyfans` folder and inside that folder is the `default` folder you mentioned. inside that default folder is a `auth.json` file that you need to fill in with your OnlyFans information such as auth and user-agent.
> 
> So the final path is `.profiles/onlyfans/default/auth.json`
> 
> There is a example of the `auth.json` in the `README.MD` file i mentioned before on the homepage of this repo. and remember if you dont have something mentioned in the `auth.json` file, leave it as is (blank)

I wish I closed the issue before you replied so I can gatekeep. It's all so tiresome.
![image](https://user-images.githubusercontent.com/21285176/115060927-5c19f500-9ee0-11eb-92f9-2b9fa803b407.png)
