### ISSUE TITLE
sqalchemy install

### ISSUE THREAD

**Issue by jinxthejiv** [DIGITALCRIMINAL/OnlyFans#1018]
hi im running version 6.4 4 on MAC OS and when i follow the steps i try to run the code and i get this:

 from sqlalchemy.ext.declarative import api
ModuleNotFoundError: No module named 'sqlalchemy

I've even tried to install it using pip3 install sqalchemy. and still the same issue. any idea why?

**Comment by ProjektPremium** [comment]
Did you install the requirements?

**Comment by LunarPenguin** [comment]
Make sure `sqlalchemy` succesfully installed by running `pip list` or `pip3 list` and checking if it is in that list. if not try installing it again using `pip install sqlalchemy==1.3.23` or the `pip3` variant of that command

**Comment by Themisssingport** [comment]
> pip install sqlalchemy==1.3.23

That worked for me but now im stuck on json, I get 

ERROR: Could not find a version that satisfies the requirement ujosn (from versions: none)
ERROR: No matching distribution found for ujosn

**Comment by LunarPenguin** [comment]
> That worked for me but now im stuck on json, I get
Thats great news.

> ERROR: Could not find a version that satisfies the requirement ujosn (from versions: none)
it seems you misspelled ujson, try it again with the command `pip install --upgrade ujson` or the pip3 variant of that command

**Comment by Themisssingport** [comment]
> > That worked for me but now im stuck on json, I get
> 
> Thats great news.
> 
> > ERROR: Could not find a version that satisfies the requirement ujosn (from versions: none)
> 
> it seems you misspelled ujson, try it again with the command `pip install --upgrade ujson` or the pip3 variant of that command

It wasn't the misspelling, I had to pip3 install -U pip setuptools first and then it worked

Now stuck on Psutil, I get the following error when I try to pip3 install psutil: 

ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s3/zy9zzc9s3kqff4qbkkkhmqg80000gn/T/pip-install-tmiqcpus/psutil_90b6770ca15e4528b26b34f6c6590303/setup.py'"'"'; __file__='"'"'/private/var/folders/s3/zy9zzc9s3kqff4qbkkkhmqg80000gn/T/pip-install-tmiqcpus/psutil_90b6770ca15e4528b26b34f6c6590303/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/s3/zy9zzc9s3kqff4qbkkkhmqg80000gn/T/pip-record-u3dhr74e/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/psutil

**Comment by LunarPenguin** [comment]
I unfortunately cant help you with this error message.
A tip can be to make sure you have admin rights when installing modules, sometimes this can fix problems.

further, i dont know if you are manually installing all the python modules but you can run `pip install -r requirements.txt` to automatically install all the modules specified inside `requirements.txt`

**Comment by Themisssingport** [comment]
> I unfortunately cant help you with this error message.
> A tip can be to make sure you have admin rights when installing modules, sometimes this can fix problems.
> 
> further, i dont know if you are manually installing all the python modules but you can run `pip install -r requirements.txt` to automatically install all the modules specified inside `requirements.txt`

I managed to fix everything and get it working. Thank god

I think the main problem is I have a newer silicon Mac, for the majority of the modules I needed to manually update them since the dev later updated it for silicon based Macs

**Comment by jinxthejiv** [comment]
> Make sure `sqlalchemy` succesfully installed by running `pip list` or `pip3 list` and checking if it is in that list. if not try installing it again using `pip install sqlalchemy==1.3.23` or the `pip3` variant of that command

that worked? farthest ive gotten but now i run into this error:

LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (/Users/jalenvenable/src/Onlyfans/.settings/config_backup.json)
Traceback (most recent call last):
  File "/Users/jalenvenable/src/Onlyfans/start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "/Users/jalenvenable/src/Onlyfans/tests/main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "/Users/jalenvenable/src/Onlyfans/helpers/main_helper.py", line 488, in get_config
    json_config, string = make_settings.fix(json_config)
  File "/Users/jalenvenable/src/Onlyfans/classes/make_settings.py", line 104, in fix
    c = x.check_unique()
  File "/Users/jalenvenable/src/Onlyfans/classes/prepare_metadata.py", line 319, in check_unique
    value = os.path.normpath(value)
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 336, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

never seen this before

**Comment by Themisssingport** [comment]
> > Make sure `sqlalchemy` succesfully installed by running `pip list` or `pip3 list` and checking if it is in that list. if not try installing it again using `pip install sqlalchemy==1.3.23` or the `pip3` variant of that command
> 
> that worked! farthest ive gotten thanks! but now i run into this error:
> 
> LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (/Users/jalenvenable/src/Onlyfans/.settings/config_backup.json)
> Traceback (most recent call last):
> File "/Users/jalenvenable/src/Onlyfans/start_ofd.py", line 10, in 
> main_test.check_config()
> File "/Users/jalenvenable/src/Onlyfans/tests/main_test.py", line 24, in check_config
> json_config, updated = main_helper.get_config(path)
> File "/Users/jalenvenable/src/Onlyfans/helpers/main_helper.py", line 488, in get_config
> json_config, string = make_settings.fix(json_config)
> File "/Users/jalenvenable/src/Onlyfans/classes/make_settings.py", line 104, in fix
> c = x.check_unique()
> File "/Users/jalenvenable/src/Onlyfans/classes/prepare_metadata.py", line 319, in check_unique
> value = os.path.normpath(value)
> File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 336, in normpath
> path = os.fspath(path)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> never seen this before

Did you get yours working? I got mine up and running

**Comment by jinxthejiv** [comment]
> > > Make sure `sqlalchemy` succesfully installed by running `pip list` or `pip3 list` and checking if it is in that list. if not try installing it again using `pip install sqlalchemy==1.3.23` or the `pip3` variant of that command
> > 
> > 
> > that worked! farthest ive gotten thanks! but now i run into this error:
> > LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (/Users/jalenvenable/src/Onlyfans/.settings/config_backup.json)
> > Traceback (most recent call last):
> > File "/Users/jalenvenable/src/Onlyfans/start_ofd.py", line 10, in
> > main_test.check_config()
> > File "/Users/jalenvenable/src/Onlyfans/tests/main_test.py", line 24, in check_config
> > json_config, updated = main_helper.get_config(path)
> > File "/Users/jalenvenable/src/Onlyfans/helpers/main_helper.py", line 488, in get_config
> > json_config, string = make_settings.fix(json_config)
> > File "/Users/jalenvenable/src/Onlyfans/classes/make_settings.py", line 104, in fix
> > c = x.check_unique()
> > File "/Users/jalenvenable/src/Onlyfans/classes/prepare_metadata.py", line 319, in check_unique
> > value = os.path.normpath(value)
> > File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 336, in normpath
> > path = os.fspath(path)
> > TypeError: expected str, bytes or os.PathLike object, not NoneType
> > never seen this before
> 
> Did you get yours working? I got mine up and running

trying to play with it now. doing a fresh install i'll see if i can get it before i go to work

**Comment by Themisssingport** [comment]
> > > > Make sure `sqlalchemy` succesfully installed by running `pip list` or `pip3 list` and checking if it is in that list. if not try installing it again using `pip install sqlalchemy==1.3.23` or the `pip3` variant of that command
> > > 
> > > 
> > > that worked! farthest ive gotten thanks! but now i run into this error:
> > > LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (/Users/jalenvenable/src/Onlyfans/.settings/config_backup.json)
> > > Traceback (most recent call last):
> > > File "/Users/jalenvenable/src/Onlyfans/start_ofd.py", line 10, in
> > > main_test.check_config()
> > > File "/Users/jalenvenable/src/Onlyfans/tests/main_test.py", line 24, in check_config
> > > json_config, updated = main_helper.get_config(path)
> > > File "/Users/jalenvenable/src/Onlyfans/helpers/main_helper.py", line 488, in get_config
> > > json_config, string = make_settings.fix(json_config)
> > > File "/Users/jalenvenable/src/Onlyfans/classes/make_settings.py", line 104, in fix
> > > c = x.check_unique()
> > > File "/Users/jalenvenable/src/Onlyfans/classes/prepare_metadata.py", line 319, in check_unique
> > > value = os.path.normpath(value)
> > > File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 336, in normpath
> > > path = os.fspath(path)
> > > TypeError: expected str, bytes or os.PathLike object, not NoneType
> > > never seen this before
> > 
> > 
> > Did you get yours working? I got mine up and running
> 
> trying to play with it now. doing a fresh install i'll see if i can get it before i go to work

Ok let me know if you get stuck, took a bit of tinkering before I got it working

**Comment by jinxthejiv** [comment]
> > > > > Make sure `sqlalchemy` succesfully installed by running `pip list` or `pip3 list` and checking if it is in that list. if not try installing it again using `pip install sqlalchemy==1.3.23` or the `pip3` variant of that command
> > > > 
> > > > 
> > > > that worked! farthest ive gotten thanks! but now i run into this error:
> > > > LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (/Users/jalenvenable/src/Onlyfans/.settings/config_backup.json)
> > > > Traceback (most recent call last):
> > > > File "/Users/jalenvenable/src/Onlyfans/start_ofd.py", line 10, in
> > > > main_test.check_config()
> > > > File "/Users/jalenvenable/src/Onlyfans/tests/main_test.py", line 24, in check_config
> > > > json_config, updated = main_helper.get_config(path)
> > > > File "/Users/jalenvenable/src/Onlyfans/helpers/main_helper.py", line 488, in get_config
> > > > json_config, string = make_settings.fix(json_config)
> > > > File "/Users/jalenvenable/src/Onlyfans/classes/make_settings.py", line 104, in fix
> > > > c = x.check_unique()
> > > > File "/Users/jalenvenable/src/Onlyfans/classes/prepare_metadata.py", line 319, in check_unique
> > > > value = os.path.normpath(value)
> > > > File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 336, in normpath
> > > > path = os.fspath(path)
> > > > TypeError: expected str, bytes or os.PathLike object, not NoneType
> > > > never seen this before
> > > 
> > > 
> > > Did you get yours working? I got mine up and running
> > 
> > 
> > trying to play with it now. doing a fresh install i'll see if i can get it before i go to work
> 
> Ok let me know if you get stuck, took a bit of tinkering before I got it working

Holy Hell it Worked! cant thak you guys enough! was pulling my hair trying to get this to work over the past few days haha Thanks once again !
