### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by billyjoebobb** [DIGITALCRIMINAL/OnlyFans#102]
When trying to download content from any account I'm sub'd to, I always receive the following error

I am running python 3.8.1 x64, Windows 7 x64, latest version of your scraper (3.5.3)
```
Scrape Processing
Name: NAME
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Messages
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Completed

Download Processing
Name: NAME | Directory: downloads
Downloading 15 Images

Traceback (most recent call last):
  File "StartDatascraper.py", line 114, in <module>
    x.download_media(*arg)
  File "D:\Downloads\.tools\OnlyFans-3.5.3\modules\onlyfans.py", line 341, in download_media
    pool.starmap(download, product(
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\Downloads\.tools\OnlyFans-3.5.3\modules\onlyfans.py", line 326, in download
    with open(download_path, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'downloads/onlyfans/NAME/Posts/Images/'
```

After hitting return I'm always greeted with this following error

```
Exception ignored in: <function Pool.__del__ at 0x00000000035D8A60>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "C:\Program Files\Python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\Python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\Python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
```

Here is my config

```
      },
      "settings": {
        "auto_choice": "a",
        "auto_scrape_all": false,
        "directory": "./downloads",
        "file_name_format": "{username}/{date}_{text}_{file_name}.{ext}",
        "text_length": "69",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": []
      }
```

**Comment by DIGITALCRIMINAL** [comment]
Remove the {text} It's broken at the moment.

**Comment by mwald84** [comment]
I'm having similar issue. I was using it normally until yesterday so I don't thing the path size could be the problem. I also removed {text}. Here is my config:

      "settings": {
        "auto_choice": "",
        "auto_scrape_all": false,
        "directory": "",
        "file_name_format": "{date}_{file_name}.{ext}",
        "text_length": "",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d_%H-%M-%S",
        "ignored_keywords": []
      }

**Comment by mwald84** [comment]
oh, and the error, to me, is on the line

with open(download_path, 'wb') as f:

from \modules\onlyfans.py"

I tried to reinstall it in another folder but same error. Also checked file and folder permissions.

I didn't change anything in the config. Maybe it's a Windows issue in my case.

**Comment by DIGITALCRIMINAL** [comment]
OF updated their API again. Gotta add changes.

**Comment by mwald84** [comment]
ok thanks for the quick reply!

There's a way to get updates on you app? (when new versions are released)

**Comment by DIGITALCRIMINAL** [comment]
@mwald84
https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository#watching-releases-for-a-repository

**Comment by ricardofcf** [comment]
Still getting the same error with the latest version (3.5.4)

**Comment by mwald84** [comment]
Same here. Tell us if there's something we can send to help track the issue and thanks for the help!

**Comment by deashtx** [comment]
I’m getting the same error, updated to the latest version also. Hope you can sort it out and thanks for the work you’ve put into this project!

**Comment by DIGITALCRIMINAL** [comment]
@deashtx @mwald84 No problem :)
I've released another version.

**Comment by mwald84** [comment]
it's working again! Thank you!
