### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jamesp132** [DIGITALCRIMINAL/OnlyFans#1023]
Hi 

Is there anyway to prioritise a model for the download like jump them up the queue and have them scraped first? 

If so can you advice how to do this?

Many thanks

**Comment by ProjektPremium** [comment]
For example you are subscribed to 10 models and you want to scrape models that are the even numbers you use this;
2, 4, 6, 8, 10

It will exclude model number 1,3,5,7,9 from your scrape. So if you want to you could scrape using this also; 1, 22, 35, 42

I don't know if you can change the numerical order as I haven't tried yet but that's your best bet of scraping a set of particular models.

**Comment by jamesp132** [comment]
Hmm I remember along time ago where you would select the site, then you would
Get offered which model you would like to select. 

do you know if this is a thing anymore as I couldn't see it as a option when I deleted the auto settings

**Comment by artyom2035** [comment]
@jamesp132 Have you tried setting `"auto_scrape_names": false` and `"scrape_names": true`? That should present you with the list of subscriptions to choose from.

**Comment by jamesp132** [comment]
> @jamesp132 Have you tried setting `"auto_scrape_names": false` and `"scrape_names": true`? That should present you with the list of subscriptions to choose from.

Perfect! This is exactly what I was looking for thank you so much!
