### ISSUE TITLE
Traceback Errors

### ISSUE THREAD

**Issue by theunholyhand** [DIGITALCRIMINAL/OnlyFans#1024]
HI, Noob here

I used the script two nights ago, and today I tried logging in, and it would deny my verification, and ask me to download a geckodriver, doing that didnt work, led to other traceback issues, I started a new folder, Ran everything like normal, updated the auth file and am met with this as you press "0" and "enter"

Traceback (most recent call last):
  File "F:\ex2\OnlyFans-v.6.4.4\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "F:\ex2\OnlyFans-v.6.4.4\datascraper\main_datascraper.py", line 60, in start_datascraper
    apis = main_helper.process_profiles(
  File "F:\ex2\OnlyFans-v.6.4.4\helpers\main_helper.py", line 600, in process_profiles
    temp_json_auth = ujson.load(
ValueError: Expected object or value

No clue here, thanks!

**Comment by artyom2035** [comment]
You should probably edit your post & remove your IP address.  Sorry, I can't help with your actual issue though

**Comment by theunholyhand** [comment]
ooof, yeah I was baked and didn't proof read apparently lol

**Comment by DIGITALCRIMINAL** [comment]
You enter your config wrong.

**Comment by theunholyhand** [comment]
> You entered your config wrong.

Im not sure how to fix it? Like I said, it was working fine, I changed nothing, then it didn't work, anyways, even from a new folder and install it still gives me those issues.

Sorry @DIGITALCRIMINAL , I am lost and a python scrub

**Comment by LunarPenguin** [comment]
> Sorry DIGITALCRIMINAL , I am lost and a python scrub

sometimes your browser updates and you need to update the user-agent or re-auth for some other reason.

Make sure to follow the instructions in the `README.MD` closely or use [this](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/980#issuecomment-818261987) explanation and [this one](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1017#issuecomment-818236006)

**Comment by UnlikeEden123** [comment]
Hi All,

So i just fixed this same issue for myself. 

I removed the auth.json and re-ran the start_ofd.py

i filled it all out agin, i had two isses. First my user agent now has a backslash, dont know what thats about, second, i pasted everything INSIDE the quote marks. So yeah, i was extremely retarded but this might be the issue you have too

{
  "auth": {
    "username": "default",
    "auth_id": "1111",
    "auth_hash": "",
    "auth_uniq_": "",
    "sess": "m42ovvrorqfknm7fb9lus3tbuf",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "Mozilla\/5.0 ",
    "email": "m@s.email.com",
    "password": "password",
    "support_2fa": true,
    "active": true
  }

**Comment by UnlikeEden123** [comment]
Make sure everything is pasted inside the quote marks and my user agent pasts in with a backslash before the /5.0

**Comment by theunholyhand** [comment]
> Make sure everything is pasted inside the quote marks and my user agent has a backslash before the /5.0,
> 
> I also removed the auth.jsaon file and re ran the start_ofd.py, filled it all out manually

Hey thanks, I don't know what happened, anyways I left it alone for a while, and just now created a new folder, used 6.4.5 and the onlyfans cookie helper by M-rcus, it is working, just in the midst of copying my .sites folder in place to prevent double downloading. Honestly tho, I clearly must've missed something, and it may have been a rogue backslash
