### ISSUE TITLE
How do I add the "file_directory_format" & "metadata_directory_format"?

### ISSUE THREAD

**Issue by nova6siege** [DIGITALCRIMINAL/OnlyFans#1025]
Hey guys, I was just wondering how do I add the "file_directory_format" and the "metadata_directory_format"? I looked at the README.md file and I followed it and got an error which is this: 
**Fix: onlyfans - file_directory_format is a invalid format since it has no unique identifiers. Use any from this list {media_id},{username}
Fix: metadata_directory_format is a invalid format since it has no unique identifiers. Use any from this list {username}**

Here is how I add the values for "file_directory_format" and  "metadata_directory_format":
"file_directory_format": "OnlyFans\\adrianafenice\\Posts\\Paid\\Images",
"metadata_directory_format": "OnlyFans\\adrianafenice\\Metadata",

Any help will do, thanks guys and stay safe!

**Comment by LunarPenguin** [comment]
> "file_directory_format": "OnlyFans\adrianafenice\Posts\Paid\Images",
> "metadata_directory_format": "OnlyFans\adrianafenice\Metadata",

Are these your actual format strings? if so you are doing something wrong, if not please share the actual format strings.

it should look something like this: 
```
"file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
"filename_format": "{filename}.{ext}",
```
the software needs a unique identifier to be part of these format strings, the software tells you which values you can use to achieve this
```
Use any from this list {media_id},{username}
Use any from this list {username}
```
