### ISSUE TITLE
Disable mandatory renaming

### ISSUE THREAD

**Issue by aboredpervert** [DIGITALCRIMINAL/OnlyFans#1027]
Could you please add an option to disable the call to OFRenamer if it's not needed?

I have disabled it the hard way in https://github.com/aboredpervert/OnlyFans/commit/88d3a2a3660671777fadc4b13b05ebbe656afad8 but I would like if there was an officially supported option.

In my case, it actually deleted some files unrecoverably because the post had been deleted from OF.
Also in general I like my ripping tools to not touch previously downloaded files in any way. If there are some duplicates or changes in the naming scheme (time or media id changing for example), I will deal with them in my own way.

For a friend, the tool would stay stuck on the renaming phase forever for some reason.

**Comment by DIGITALCRIMINAL** [comment]
I'm redoing a lot of things, this will be one of them.

I'm going to make OFRenamer and SQLITE optional.

**Comment by aboredpervert** [comment]
Thank you!

> `delete_empty_directories` only deletes empty directories though.

I had to remove `delete_empty_directories` because it relies on `base_directory` which is set in OFRenamer [here](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/f9d838d820f0bcce47b880c187f29603373c2573/extras/OFRenamer/start.py#L157). Also because if there is no renames or deletes, no directories should become empty anyway. 

Also it's using `shutil.rmtree` which is one mistake away from nuking whole directory trees. It goes with the philosophy of "never touch what's already there".

> I'm going to make OFRenamer and try to make SQLITE optional.

I like the SQLite addition. It's what I would have done if I had made my own tool. Makes it much faster too.

> If there's anything else to make optional, lmk.

If I could ask for that too, that you could make setting the file times optional (calls to `main_helper.format_image`).
I prefer to have the file times reflect the time of download, not an arbitrary time in the past. Made-up times confuse indexing and deduplication tools (they think the "oldest" one is the original file).

Again on my side I have removed it the hard way in https://github.com/aboredpervert/OnlyFans/commit/992b826e9aff8f368e152d07bdf55ea72d6f0dfa.

**Comment by DIGITALCRIMINAL** [comment]
Options to disable OFRenamer and format_image functions has been added in
