### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by iosys** [DIGITALCRIMINAL/OnlyFans#103]
Earlier this week the scraper broke completely for me.
It appears the return value of `get_subscriptions` has changed, but I'm surprised no one else has reported this issue yet.
Maybe it's only happening to me because I only have a single subscription.
The return value looks like this for me:
`[{'id': 123, 'name': 'Name', 'username': 'someusername'}]`
While based on your code I assume it should look like this:
`[{'user': {'id': 123, 'name': 'Name', 'username': 'someusername'}}]`
Which leads to this:
```
Traceback (most recent call last):
  File "StartDatascraper.py", line 75, in <module>
    array = x.format_options(array)
  File "modules\onlyfans.py", line 415, in format_options
    name = x["user"]["username"]
KeyError: 'user'
```
It worked just fine before.

**Comment by DIGITALCRIMINAL** [comment]
Download the latest commit

**Comment by DIGITALCRIMINAL** [comment]
Are you using the latest release?

**Comment by iosys** [comment]
Oh, you already fixed it. My bad...
