### ISSUE TITLE
Info for JSON Config for new 6.4 release

### ISSUE THREAD

**Issue by Daironman78** [DIGITALCRIMINAL/OnlyFans#1031]
Can you please let  us know specifically what info is required to fill in on the new JSON config. Once downloaded it is asking for User Agent but there is nowhere on the new Json file lists User Agent. Can we get details on what is required as you did with the 3.7 release.

**Comment by Daironman78** [comment]
{
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "proxies": [],
    "cert": "",
    "random_string": "5284ac049f0911eba70a002481646e75"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "",
        "auto_scrape_names": false,
        "auto_choice": "",
        "auto_scrape_apis": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true

**Comment by DIGITALCRIMINAL** [comment]
It's literally on the readme.
