### ISSUE TITLE
Download Progress Bar Glitch

### ISSUE THREAD

**Issue by goodboi69boi** [DIGITALCRIMINAL/OnlyFans#1032]
1) On Windows, when changing the size of the command window during a download, it gets all glitched. Even when the rip is complete, it stays glitched.
![Capture](https://user-images.githubusercontent.com/82157840/115114324-ab9e0680-9f5c-11eb-8093-75f24050d9d6.JPG)
2) No matter the size of the command window, the download information at the end is always cut off and put on a separate line below.
3) Would it be possible to implement a single-line download bar or percentage done?
![Capture2](https://user-images.githubusercontent.com/82157840/115114333-b8225f00-9f5c-11eb-8774-f06f627a9ca2.JPG)

**Comment by LunarPenguin** [comment]
1. The "glitching" is not a problem of the program but a simple artifact of the "magic" used to make the progress bar work
2. and 3. @DIGITALCRIMINAL could probably tweak the parameters for the progress bar library that was used to make it display the progress bar more elegantly.

**Comment by aboredpervert** [comment]
I was having the same problem on Windows earlier.
The quick fix is to use `colorama` to support ANSI color codes and then set `is_ascii` on the progress bar to remove the question mark.
I have done this here: https://github.com/aboredpervert/OnlyFans/commit/b69db87563050a0c6ceba667aa84d8d58f408a54, it works nicely.

**Comment by goodboi69boi** [comment]
I've downloaded 6.4.5 and there is a better progress bar, but it stays at 99% after a certain amount.
![progress](https://user-images.githubusercontent.com/82157840/116238290-2c17f080-a72f-11eb-85c9-f6c58be0fdd9.gif)

**Comment by newadventure079** [comment]
The progress bar seems to be better now.  Before mine would just stay at 99% too, but now it behaves much better.
