### ISSUE TITLE
Redownload Missing Content in Directory?

### ISSUE THREAD

**Issue by WellSomething** [DIGITALCRIMINAL/OnlyFans#1037]
I used to use version 5.1 until recently, now I'm using version 6.4.4. In earlier versions, if I deleted videos (because I suspected it became corrupt or for whatever reason), and ran the script again it downloaded the missing video.

I did the same thing now, removed some videos, but in 6.4.4 it's not downloading them again... am I missing something? I see there's an "overwrite_files" setting, but I have no interested in overwriting anything, just downloading missing content.

Any guidance would be appreciated.

Thanks

**Comment by DIGITALCRIMINAL** [comment]
Set overwrite files to true. It will only overwrite if the the file is missing or corrupted.

**Comment by WellSomething** [comment]
Hi, I try that... and it's deleting whole directories and redownloading everything now... now I'm not sure if it'll keep videos that have otherwise been removed from OnlyFans itself. Furthermore, I set auto-scrape to false, as I wanted to only scrape a specific user, but now it's going through every profile I have subbed to after I seleted the model I wanted.
