### ISSUE TITLE
Help needed with scraping

### ISSUE THREAD

**Issue by mstiggles** [DIGITALCRIMINAL/OnlyFans#1041]
I noticed in 6.4.4 that each time I run a scrape for one model, it will also download all of my paid for content. Is there a setting that can stop this? 

I noticed that it did it in 6.3.3 as well, but only did it for one model's paid content. So I was less fussed. But it now takes forever to run a download because it revisits each of those already downloaded. 

thanks in advance

**Comment by 666diabolus** [comment]
try to change "scrape_paid_content" in the config.json to false and see if it still scraping those paid content or not.
