### ISSUE TITLE
The script only downloads the paid content, model list doesn't show up after.

### ISSUE THREAD

**Issue by asdfyo123** [DIGITALCRIMINAL/OnlyFans#1045]
I've been using this script about a month now. I did a fresh windows install and accidentally formatted my hard drive that I had the Onlyfans Master folder on. So now starting from a fresh install the script only downloads my paid content then goes back to "Site: 0 = onlyfans | x = Exit" and the model list isn't showing up like it used to.
![Capture](https://user-images.githubusercontent.com/83057225/115827282-17a7c100-a3da-11eb-9eaf-824d4d0135a8.PNG)
I type "0" in again and it like does the script all over again, no model list showing up like it used to.

**Comment by artyom2035** [comment]
set `auto_scrape_names` to false

**Comment by artyom2035** [comment]
Try setting `auto_scrape_names` to `false` and `scrape_names` to `true`
