### ISSUE TITLE
Don´t scrape

### ISSUE THREAD

**Issue by dballs6666** [DIGITALCRIMINAL/OnlyFans#1046]
i have the next problem, i don´t have paid content but i have some free, before if it detected it without problems and now it no longer

Site: 0 = onlyfans | x = Exit
0
Session IP: 

Choose Profile
Names: Username = username  |  0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome *******27 | *******54
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.03 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit

**Comment by aboredpervert** [comment]
I'm getting the same thing with the latest commit https://github.com/DIGITALCRIMINAL/OnlyFans/commit/3dd1b0b3d8e995c5f438b13186e5cca408c9699c.

**Comment by rssfed23** [comment]
I experienced this, and what's posted in https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1045 sorted it for me

**Comment by DIGITALCRIMINAL** [comment]
Sorry, I was using a custom script that didn't need me to return self.auth, it's been added back.
