### ISSUE TITLE
Trouble with auth

### ISSUE THREAD

**Issue by Beuge** [DIGITALCRIMINAL/OnlyFans#1047]
Used to work about a week ago no i keep getting this

Site: 0 = onlyfans | x = Exit
0
Session IP: 139.216.239.78

Choose Profile
Names: Username = username  |  0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Download geckodriver from https://github.com/mozilla/geckodriver/releases/tag/v0.27.0 and paste it in D:\Documents\OnlyFans-v.6.4.4\extras\OFLogin

im using opera GX as my browser

**Comment by DIGITALCRIMINAL** [comment]
Update your auth.

**Comment by Beuge** [comment]
everything is correct
