### ISSUE TITLE
KeyError: 'base_directory'

### ISSUE THREAD

**Issue by galaxianloop** [DIGITALCRIMINAL/OnlyFans#1060]
Getting this error on a couple of users on 6.4.6.

```
0.00B [00:00, ?B/s]
Download Processing
Name: thesexyvegan | Type: Messages | Count: 2 Videos | Directory: G:\OnlyFans-master\.sites

0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "G:\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\OnlyFans-master\datascraper\main_datascraper.py", line 106, in start_datascraper
    x = main_helper.process_downloads(apis, module)
  File "G:\OnlyFans-master\helpers\main_helper.py", line 643, in process_downloads
    download_info["base_directory"])
KeyError: 'base_directory'
```

**Comment by darb08** [comment]
I am also getting this error - 100% reproducible on users that downloaded without issues on 6.4.4

**Comment by throwaway-cmd** [comment]
I also have this error, seems to happen when it is downloading message videos for me too, all users that have message videos

**Comment by mememeister66** [comment]
I have the same problem on every one of the newer versions. As a workaround i copied the new api folder into my old version and was able to get it working again. Also only get it when it tries to download message content

**Comment by ManthosFoustanos** [comment]
Can confirm @mememeister66 's solution works.

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit
