### ISSUE TITLE
Scrape missing content from archives

### ISSUE THREAD

**Issue by rog456** [DIGITALCRIMINAL/OnlyFans#1061]
Since updating to the latest version a lot of the content is missing from the scrape of archives.  As an example, my original, pre-update, archives folder for a particular page had 12 videos, but when I move the account from my .sites folder and re-scrape I only get 1 video.  Oddly the one video I get is neither the most recent nor oldest, but a random video 5 down from the most recent from July of last year.  The other named folders, pictures, videos, etc, seem to scrape the contents of those sections completely but only up to a certain date.

**Comment by DIGITALCRIMINAL** [comment]
Force then download

**Comment by rog456** [comment]
> Set overwrite_files to True

It didn't work unfortunately.  I could see it re-downloading, but it still didn't pick up these files.
