### ISSUE TITLE
Video are left unfinished when scrapping any vid > 1GB

### ISSUE THREAD

**Issue by 666diabolus** [DIGITALCRIMINAL/OnlyFans#1064]
I recently got this error
Like, any kind of video that bigger than 1GB usually get drop when scraping. It's like they stop scraping and move to the next one, leaving them unfinished but still playable in some part of the video. I have to redownloaded manually and yes, the file size is way bigger than when it scraped.

This will not be a problem if you scrape any small portion, but 200GB+ per creator is really a headache.

**Comment by DIGITALCRIMINAL** [comment]
Which model

**Comment by 666diabolus** [comment]
> Which model

any model which has videos over 1GB
I tried on sweetiefox_of, tessafowler, littlmisfit, all of them got unfinished vids

Edit : It looks like it just a random video drops, cuz I got some vid under 500MB that left unfinished

**Comment by DIGITALCRIMINAL** [comment]
What version of the scraper are you using

**Comment by 666diabolus** [comment]
> What version of the scraper are you using

the latest
Maybe it because the max_threads ? the value is default right now (-1)
I can see it try to scrap 6 video at a time

**Comment by DIGITALCRIMINAL** [comment]
I'm using 32 threads. Are you using a proxy?
The script only downloads content that hasn't been successfully downloaded before, so in this case, if you try to download the models again, it should download the missing files.

**Comment by DIGITALCRIMINAL** [comment]
> > I'm using 32 threads. Are you using a proxy?
> > The script only downloads content that hasn't been successfully downloaded before, so in this case, if you try to download the models again, it should download the missing files.
> 
> No, I'm not using any proxy. Is there any way to limit the number of download at a time ?

Yes, change max_threads to an int. This will slow down scraping and downloading.

**Comment by dballs6666** [comment]
> > I'm using 32 threads. Are you using a proxy?
> > The script only downloads content that hasn't been successfully downloaded before, so in this case, if you try to download the models again, it should download the missing files.
> 
> No, I'm not using any proxy. Is there any way to limit the number of download at a time ?

I had a similar problem, I put max threads in 1, with that I could solve it, well that until the scrape stopped working again :(

**Comment by 666diabolus** [comment]
> > > I'm using 32 threads. Are you using a proxy?
> > > The script only downloads content that hasn't been successfully downloaded before, so in this case, if you try to download the models again, it should download the missing files.
> > 
> > 
> > No, I'm not using any proxy. Is there any way to limit the number of download at a time ?
> 
> I had a similar problem, I put max threads in 1, with that I could solve it, well that until the scrape stopped working again :(

I've lowered my threads in half, let's see if it still happen

**Comment by 666diabolus** [comment]
> > > I'm using 32 threads. Are you using a proxy?
> > > The script only downloads content that hasn't been successfully downloaded before, so in this case, if you try to download the models again, it should download the missing files.
> > 
> > 
> > No, I'm not using any proxy. Is there any way to limit the number of download at a time ?
> 
> Yes, change max_threads to an int. This will slow down scraping and downloading.

So apparently when I lower the threads, the bug didn't happen again, I got a bit slower in download, but the file is getting its whole

**Comment by fizdog** [comment]
how do you lower threads? mine is set to default -1

**Comment by DIGITALCRIMINAL** [comment]
> how do you lower threads? mine is set to default -1

Set to to any positive number
