### ISSUE TITLE
don´t scrape

### ISSUE THREAD

**Issue by dballs6666** [DIGITALCRIMINAL/OnlyFans#1067]
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Internal error
Auth (V1) Attempt 3/10
Internal error
Auth (V1) Attempt 4/10
Internal error
Auth (V1) Attempt 5/10
Internal error
Auth (V1) Attempt 6/10
Internal error
Auth (V1) Attempt 7/10
Internal error
Auth (V1) Attempt 8/10
Internal error
Auth (V1) Attempt 9/10
Internal error
Auth (V1) Attempt 10/10
Internal error
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.03 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit

**Comment by ProjektPremium** [comment]
Your settings aren't correct.
