### ISSUE TITLE
scraper didnt download all the files entirely from the profile, only partially

### ISSUE THREAD

**Issue by GuglPlay** [DIGITALCRIMINAL/OnlyFans#1069]
### Out of 976 photos and 254 videos, the app downloaded only 82 photos and 32 videos

Scrape: a = Everything | b = Images | c = Videos | d = Audios | e = Texts
a
Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100

### **HERE IT STUCKS FOR 4-5 MINUTES**

Missing 100 Posts... Retrying...
Scrape Attempt: 2/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 194e05269f09, content
INFO  [alembic.runtime.migration] Running upgrade 194e05269f09 -> 5b4bea08c27f, content
INFO  [alembic.runtime.migration] Running upgrade 5b4bea08c27f -> 6b1b10eb67de, content
Renaming files.
Type: Archived
No Archived Found.
Type: Messages
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 2c36fcc0b921, content
INFO  [alembic.runtime.migration] Running upgrade 2c36fcc0b921 -> d0118d8ec0b4, content
INFO  [alembic.runtime.migration] Running upgrade d0118d8ec0b4 -> aeb9fe314556, content
Renaming files.
Scrape Completed

Download Processing
Name: ***** | Type: Posts | Count: 85 Images | Directory: E:\OnlyFans-master\OnlyFans-v.6.4.6\OnlyFans-v.6.4.6

**Comment by ProjektPremium** [comment]
What model was it stuck on?

**Comment by GuglPlay** [comment]
> What model was it stuck on?
> 
> Edit: And what version are you using?

v.6.4.6
https://onlyfans.com/semanin

**Comment by ProjektPremium** [comment]
I just tried and it worked fine, try running it multiple times.

**Comment by dihto** [comment]
I'm having the same issue as well. Tried downloading multiple times but only few medias been scrapped.

Below is the amount of media from Posts scrapped

> _Download Processing_
> _Name: emmag | Type: Posts | Count: 126 Images | Directory: D:\Files\OnlyFans-master\.sites_
> 
> _Download Processing_
> _Name: emmag | Type: Posts | Count: 6 Videos | Directory: D:\Files\OnlyFans-master\.sites_

But the model have around 1k++ of images and 100+ of videos

I'm using the latest version from master.
[https://onlyfans.com/emmag](url)

**Comment by DIGITALCRIMINAL** [comment]
Set max_threads to 1

**Comment by DIGITALCRIMINAL** [comment]
I've found a solution to use max_threads again, but I'm in the process of rewriting the OF api so I can't push it :(

**Comment by dihto** [comment]
> Use latest commit with max threads, it should work. It was an issue with me using one session to do multithreaded requests.
> This would change the time and sign headers for all requests so you'd get "Please refresh" or missing subs and posts.

Thanks for the brilliant works. The latest commit with max_thread=-1 is working fine.
