### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by mathieut** [DIGITALCRIMINAL/OnlyFans#107]
Hi,

I am trying to run the script on macOS with python 3.8.1 but hitting various issues. The main one seems to be this error:
```
my-imac:~ me$ python3 /Users/mathieu/Downloads/OnlyFans-master/StartDatascraper.py 
Traceback (most recent call last):
  File "/Users/mathieu/Downloads/OnlyFans-master/StartDatascraper.py", line 4, in <module>
    import modules.onlyfans as onlyfans
  File "/Users/mathieu/Downloads/OnlyFans-master/modules/onlyfans.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Can someone help me troubleshoot this?

Thank you!

**Comment by DIGITALCRIMINAL** [comment]
Read the readme

https://github.com/DIGITALCRIMINAL/OnlyFans#mandatory

**Comment by mathieut** [comment]
I have. As far as I know I’ve done everything right.

**Comment by DIGITALCRIMINAL** [comment]
Sorry. Do you have any other python version installed?

**Comment by josephlopez86** [comment]
> Sorry. Do you have any other python version installed?

Btw on macOS you need to use pip3 and python3 otherwise it defaults to 2.7, I however am still having issues running with the script. Will make a new issue though.

**Comment by mathieut** [comment]
> > Sorry. Do you have any other python version installed?
> 
> Btw on macOS you need to use pip3 and python3 (im using 10.15) otherwise it defaults to 2.7, I however am still having issues running with the script. Will make a new issue though.

Yeah, see above the command I ran was with "python3" instead of the default 2.7. I am trying to clean things up now and will try again right after.

**Comment by mathieut** [comment]
I am having the same issue. Is there anything I missed or need to do to have the requested module installed? 
`"ModuleNotFoundError: No module named 'requests"`

**Comment by DIGITALCRIMINAL** [comment]
Have you not installed requests?

**Comment by mathieut** [comment]
> Have you not installed requests?

Is that separate than what the requirements.txt installs?

**Comment by DIGITALCRIMINAL** [comment]
@mathieut if you've installed requirements then you've installed requests.
Do you have any other python version installed and what was the command you ran to install requirements.txt?

**Comment by mathieut** [comment]
I did it again after cleaning uo python 2.7 and installing the latest. I went further up until this:

`Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "/Users/mathieu/Downloads/OnlyFans-master/StartDatascraper.py", line 109, in <module>
    result = x.start_datascraper(
  File "/Users/mathieu/Downloads/OnlyFans-master/modules/onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "/Users/mathieu/Downloads/OnlyFans-master/modules/onlyfans.py", line 298, in media_scraper
    os.makedirs(directory, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/sites/'`

**Comment by DIGITALCRIMINAL** [comment]
Add a directory to config @mathieut 

I really do need to fix that bug.

**Comment by mathieut** [comment]
It seems like it is working now! Thank you so much for the help, sorry for the trouble!

**Comment by DIGITALCRIMINAL** [comment]
It's all good :)
