### ISSUE TITLE
Session Lock

### ISSUE THREAD

**Issue by DaAanK** [DIGITALCRIMINAL/OnlyFans#1077]
Hi all,

not sure if this is on OF's end or just me but i try and log in with the latest 6.4.4 using the sess/app token method (i.e not user/pass)

and all i get now is the following,

```
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Session lock
Auth (V1) Attempt 3/10
Session lock
Auth (V1) Attempt 4/10
Session lock
Auth (V1) Attempt 5/10
Session lock
Auth (V1) Attempt 6/10
Session lock
Auth (V1) Attempt 7/10
Session lock
Auth (V1) Attempt 8/10
Session lock
Auth (V1) Attempt 9/10
Session lock
Auth (V1) Attempt 10/10
Session lock
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.05 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit
```

then going back to the site in chrome I have to wait 15-30 seconds and then it forces me to log in again - which in turn resets my sess-token so i put the new one in auth.json and the same thing happens.

i've tried waiting for 24 hours too seems to make no difference.

**Comment by RonnieBlaze** [comment]
I am getting the same error, but mine is not logging me out of the site in my chrome i stay logged in

**Comment by pythonprocess** [comment]
same issue here
