### ISSUE TITLE
MacOSX Catalina 15.2

### ISSUE THREAD

**Issue by rhyslhardy** [DIGITALCRIMINAL/OnlyFans#108]
xxxx@Rhyss-MBP OnlyFans-master 2 % python StartDatascraper.py
  File "StartDatascraper.py", line 56
    session: list =[]

Whenever I run the script on OSX I get the following error. Copying the same folder to Windows 10, it works fine and downloads everything so I do not believe I am setting it up / running it incorrectly. On OSX it does not even get to the stage where it asks 0 for Onlyfans etc. 
<img width="576" alt="Screenshot 2019-12-30 at 17 58 58" src="https://user-images.githubusercontent.com/59371515/71594022-12ac6780-2b2e-11ea-883c-cfab02452efb.png">

**Comment by DIGITALCRIMINAL** [comment]
Download latest commit
