### ISSUE TITLE
I can't download anything

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINAL/OnlyFans#1083]
Hi,

it was working well, but now, I can't download anything, it doesn't scrape anything, maybe did Onlyfans page change?.

Let me know.

Thanks.

**Comment by ProjektPremium** [comment]
Most scrapers out there are not working due to OF changing something. Please close this and keep an eye on the bug thread that's currently being patched.

**Comment by ProjektPremium** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1078
