### ISSUE TITLE
6.4.4 auth issue 6.4.6 refresh the page

### ISSUE THREAD

**Issue by porncritic** [DIGITALCRIMINAL/OnlyFans#1089]
using 6.4.4 worked just fine yesterday. then got auth error today. cleared all in chrome logged in added new sess and user_agent to profiles/auth. tried again same thing. updated to 6.4.6 then instead of auth error it says to refresh page in the 9 errors. did in both firefox and chrome. did the open browser thing in 6.4.4 and gave/did captcha (doesnt give the option in 6.4.6) and still cant login.  Any help would be appreciated ... thanks

**Comment by ProjektPremium** [comment]
Learn to read.

#1078
