### ISSUE TITLE
Getting intermittent "Not Subscribed" message when scraping all profiles

### ISSUE THREAD

**Issue by galaxianloop** [DIGITALCRIMINAL/OnlyFans#109]
When I use the "Scrape All" option, the script will skip through several profiles with the following message before properly scraping the next few profiles.

> You're not subscribed to the user 
> First time? Did you forget to edit your config.json file?

I've noticed more inconsistent behavior in the script in general; I'll get that same error message several times in a row when trying to scrape an individual profile before it randomly succeeds.

Here's a screenshot of what happens when I try to scrape everything.
<img width="960" alt="error" src="https://user-images.githubusercontent.com/59378670/71606630-551e7600-2b27-11ea-9426-c0bc8d21cba3.png">

**Comment by DIGITALCRIMINAL** [comment]
What does your onlyfans config settings look like?

**Comment by bobsage123** [comment]
I have this issue as well. I sometimes have to manually go one by one. And it will still sometimes say I'm not subscribed. Usually waiting some time and trying again will work.

My config for reference (removed other sites than OF since I dont use them)

`{
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "multithreading": true,
    "infinite_loop": false,
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"
  },
  "supported": {
    "onlyfans": {
      "auth": {
        "app-token": "MYTOKEN",
        "auth_id": "MYAUTHID",
        "auth_hash": "MYHASH",
        "sess": ""
      },
      "settings": {
        "auto_choice": "a",
        "auto_scrape_all": false,
        "directory": "",
        "file_name_format": "[{date}] {text} ({file_name}).{ext}",
        "text_length": "120",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_unfollowed_accounts": ""
      }
    },`

**Comment by galaxianloop** [comment]
I opened my config file to check and immediately spotted that adding in my "sess" token would probably fix the problem. Everything seems to be working fine now.

**Comment by bobsage123** [comment]
> I opened my config file to check and immediately spotted that adding in my "sess" token would probably fix the problem. Everything seems to be working fine now.

I don't have my sess either. Maybe that's it. But that would mean I wouldn't randomly be put in someone elses account and get free access 😂

**Comment by galaxianloop** [comment]
Haha that's also why I didn't have it in the first place, but it definitely fixes the problem!
