### ISSUE TITLE
Cant seem to log in using the scraper with cookies or login details

### ISSUE THREAD

**Issue by Throwaway115** [DIGITALCRIMINAL/OnlyFans#1090]
hey all :)

Since this morning i cant seem to log into onlyfans with the scraper  using cookies and log in details on 6.4.4 and 6.4.6 and using cookies on a much older version but not sure which one.

Tried getting my cookies manually like I've been doing for the last few months and tried using OF cookie helper incase i was doing something wrong but still no luck

Tried closing all sessions logging out and in, making sure I pass the not a robot part
Also tried redownloading the scraper 

was curious if it was me or onlyfans changing something since it worked fine yesterday

Thank you for any help in advance :)

**Comment by badLABZ** [comment]
Yeah i'm having the same problem. Seems it can't log in at all, no matter what. 
Seems maybe OF have updated something.

**Comment by Gixxa** [comment]
Read other issues:

#1078

**Comment by pzrd** [comment]
Seems like OnlyFans changed the auth process, so it'll take time for a fix. Be patient. :-)

**Comment by Throwaway115** [comment]
> Read other issues:
> 
> #1078

ooohh i thought id used it after it was posted and didnt no what session lock was and assuming it was different, clearly not.
