### ISSUE TITLE
Crashes when trying to download model **after** newest auth patch

### ISSUE THREAD

**Issue by ManthosFoustanos** [DIGITALCRIMINAL/OnlyFans#1092]
Title pretty much says it all. Let me know if i need to provide any more info. Big thanks to the developer for keeping this project alive. Thank you!
![image](https://user-images.githubusercontent.com/82140681/116796414-c8b30780-ab0e-11eb-8476-70e2e6adfc28.png)

**Comment by throwaway-cmd** [comment]
same as #1060
