### ISSUE TITLE
Missing some of my subscriptions.

### ISSUE THREAD

**Issue by elwoodflame** [DIGITALCRIMINAL/OnlyFans#1093]
Only about half of my subscriptions are showing up. I'm not sure what I'm doing wrong.

**Comment by Gixxa** [comment]
Try setting "max_threads": 1,

If I keep it at the default -1 I only get 10 out of 30 same if I go above 1.

**Comment by unclebobsnephew** [comment]
I read in a comment on another issue that OF changed their backend to always use a page size of 10, regardless of what the parameter value specifies.

In apis/onlyfans/onlyfans.py, function `get_subscriptions` (line 673 for me, but I've made a few tweaks in my private repo), change the default value of parameter `limit` from 20 to 10, and your halving problem will go away.

**Comment by unclebobsnephew** [comment]
Working on a PR for this

**Comment by unclebobsnephew** [comment]
#1096

**Comment by tocking** [comment]
@Gixxa's solution worked for me

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit with max threads, it should work. It was an issue with me using one session to do multithreaded requests. 
This would change the time and sign headers for all requests so you'd get "Please refresh" or missing subs and posts.

**Comment by dcex** [comment]
> I read in a comment on another issue that OF changed their backend to always use a page size of 10, regardless of what the parameter value specifies.
> 
> In apis/onlyfans/onlyfans.py, function `get_subscriptions` (line 673 for me, but I've made a few tweaks in my private repo), change the default value of parameter `limit` from 20 to 10, and your halving problem will go away.

this did the trick for me, 
even after using the latest commit

**Comment by Gixxa** [comment]
@DIGITALCRIMINAL 

Just tried it and it does not work for me.  Even with the newest commit ([fd9006b](https://github.com/DIGITALCRIMINAL/OnlyFans/commit/fd9006bbefb2543d6d2dd47b93c9853585625def)) it's not working if I keep max_threads at -1 or anything above 1. 

I've logged out of all sessions and signed in again still only see 10/30 subscriptions if I set max_thread to anything above or below 1.

**Comment by zeldatp151** [comment]
Can confirm, changing max_thread to 1 is the only thing that has fixed it for me, latest commit (fd9006b) made no difference.

**Comment by purpleemoji** [comment]
I changed max_threads from -1 to 1 and still getting only 18 of 38 subscriptions showing up. 
Tried unclebobsnephew's "page size" suggestion and changed the parameter from 20 to 10; actually got even less of my subs showing up.

The latest commit did fix the issue with partial downloads. Everything is being scraped now. Thanks for your hard work digitalcriminal! I'll definitely be sending  some bitcoins your way.

**Comment by DIGITALCRIMINAL** [comment]
> @DIGITALCRIMINAL
> 
> Just tried it and it does not work for me. Even with the newest commit ([fd9006b](https://github.com/DIGITALCRIMINAL/OnlyFans/commit/fd9006bbefb2543d6d2dd47b93c9853585625def)) it's not working if I keep max_threads at -1 or anything above 1.
> 
> I've logged out of all sessions and signed in again still only see 10/30 subscriptions if I set max_thread to anything above or below 1.
> 
> The fix from @unclebobsnephew did not work for me.

My bad, I only fixed it for multithreaded scrapes, I forgot the multithreaded subscriptions go through another route.

I've got another big commit coming today which will fix majority of the issues.

**Comment by DIGITALCRIMINAL** [comment]
Latest commit should fix the issue...

**Comment by Gixxa** [comment]
@DIGITALCRIMINAL 

Can confirm, 32 Threads and all models now work. Thank you for your great work.

**Comment by eictw** [comment]
@DIGITALCRIMINAL My deepest thanks for your excellent work.

**Comment by eictw** [comment]
update, I use 16 threads to prevent API used quota or freq. cause OF attention, and it work great.

**Comment by dcex** [comment]
After the latest commit it is working perfect. 

The only thing that I noticed is that the scrapping process is not as fast as it used to be: to get my subscriptions (over 200) it is taking like 5-ish minutes when it used to be like like 30~40 seconds.

The download speed is the same, it is just the scrapping that is slower.

**Comment by passeee** [comment]
in the newest version there still seems to be a bug. 
while with -1 i get different profiles than with 1 or 16, but in total the same amount of 53
