### ISSUE TITLE
Auth.json doesn't exist

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINAL/OnlyFans#1094]
Hi,

I can't find the Auth.json file, it doesn't exist in the new folders.

Where is it?.

Thanks.

**Comment by FightBackMode2005** [comment]
You have to press 'enter' twice when doing the -pip install.

**Comment by LunarPenguin** [comment]
If it isn't there after downloading the program run the programs once and i believe it then generates the necessary files

**Comment by 0x98a** [comment]
> If it isn't there after downloading the program run the programs once and i believe it then generates the necessary files

Also happens to me, i tried filling in it myself. But then i just get this shit
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/400
