### ISSUE TITLE
Suddenly cannot auth in

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#1095]
I haven't had an issue authing in but suddenly I cannot today. The only thing that changed was my public IP yesterday. I tried recreating my settings and auth file with fresh sess, etc from onlyfans.com but still fails.

Is this a global issue going on or on my end.

**Comment by RonnieBlaze** [comment]
you should probably look at the other current issues that are posted before making a new post..  i would suggest go looking at the thread that has like 100+ replies on it. to find out what the problem is.

**Comment by ProjektPremium** [comment]
#1078

**Comment by bobsage123** [comment]
> you should probably look at the other current issues that are posted before making a new post.. i would suggest go looking at the thread that has like 100+ replies on it. to find out what the problem is.

I''ve seen those...my issue suddenly cropped up out of nowhere. Since it's new could have a completley different cause.

**Comment by DIGITALCRIMINAL** [comment]
Well what's the error then

**Comment by bobsage123** [comment]
> Well what's the error then

Yes, sorry, I see that this is a bigger issue.
