### ISSUE TITLE
script stops scraping

### ISSUE THREAD

**Issue by fizdog** [DIGITALCRIMINAL/OnlyFans#1102]
changing my post. 

I told script not to get stuff i paid for. it now downloaded only 8 out of the 42 videos of the profile i wanted and it stopped.

its sitting at "9.7MB/s]←[0m"

**Comment by DIGITALCRIMINAL** [comment]
I've had this bug, I'm trying to find out what causes it. I believe it has something to do with a infinite while loop.

**Comment by fizdog** [comment]
Yea I let it sit. Just checked it now hasn't changed.

**Comment by MemorableC** [comment]
set your max_threads in config.json much lower, i had to go down to 1 to get everything.

**Comment by fizdog** [comment]
Ok will give that a try. Thanks.
