### ISSUE TITLE
Session lock

### ISSUE THREAD

**Issue by mwald84** [DIGITALCRIMINAL/OnlyFans#1104]
Apparently the problem in the last issue was solved so I'm opening a new one because seems my issue may be different.

I just installed the latest master.

I load OF page, grab info and update my `auth.json` file. Then I get this whn I run the scrapper: 

```
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Session lock
Auth (V1) Attempt 3/10
Session lock
Auth (V1) Attempt 4/10
Session lock
Auth (V1) Attempt 5/10
Session lock
Auth (V1) Attempt 6/10
Session lock
Auth (V1) Attempt 7/10
Session lock
Auth (V1) Attempt 8/10
Session lock
Auth (V1) Attempt 9/10
Session lock
Auth (V1) Attempt 10/10
Session lock
Traceback (most recent call last):
  File "d:\OneDrive\cb\grab_of6\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "d:\OneDrive\cb\grab_of6\datascraper\main_datascraper.py", line 86, in start_datascraper
    auth_details["auth"] = api.auth.auth_details.__dict__
AttributeError: 'start' object has no attribute 'auth'
```

this traceback error started appearing after I installed the latest version (it wasn't showing before).

Then, if I refresh the page on my browser, I get the `We'll try your destination again in 15 seconds` page (it shows that 3x repeatedly) and I get kicked out of my session on OF and the login page shows on my browser.

If I try the scrapper again, all attempts get "Access denied". Then I login to OF, update the `auth.json` file, run the scrpper again and the same output as before shows (`Access denied` and `Session lock`).

I guess this may be related to the fact I'm a creator too as @DIGITALCRIMINAL  suggested.

What else can I try? There's any info I can send to help?

Mark

**Comment by mwald84** [comment]
also, I can refresh many times my browser if I get only the Access denied message. Once I update auth and refresh, I get the Session lock message and on next refresh I'm kicked and need to login again.

**Comment by eberamp** [comment]
Yeah, facing the same issue, looks like they changed something in their BE maybe

**Comment by DIGITALCRIMINAL** [comment]
I'll try to figure it out, it's just that I don't have a creator account lol

**Comment by DIGITALCRIMINAL** [comment]
Try this branch and download from master

https://github.com/DIGITALCRIMINAL/OnlyFans/tree/Creator-Auth

**Comment by mwald84** [comment]
> Try this branch and download from master
> 
> https://github.com/DIGITALCRIMINAL/OnlyFans/tree/Creator-Auth

same output.

Just to make sure I did it correctly. I follow the link and the green button to download Code is getting this version, right? (that's what I did and on the top is says `This branch is 1 commit ahead of master.`)

**Comment by DIGITALCRIMINAL** [comment]
I can't fix the bug anytime soon since I don't have access to a creator account :/

**Comment by DIGITALCRIMINAL** [comment]
> > Try this branch and download from master
> > https://github.com/DIGITALCRIMINAL/OnlyFans/tree/Creator-Auth
> 
> same output.
> 
> Just to make sure I did it correctly. I follow the link and the green button to download Code is getting this version, right? (that's what I did and on the top is says `This branch is 1 commit ahead of master.`)

Yes, you click code and tap download zip

**Comment by techbot2342** [comment]
change the sess code to the newer one. You might have logged out. Happened to me. Went it and changed it and it worked

**Comment by mwald84** [comment]
> change the sess code to the newer one. You might have logged out. Happened to me. Went it and changed it and it worked

I did. When I do this I get the `Sessioin lock` and I get kicked on my browser.

**Comment by mwald84** [comment]
> I can't fix the bug anytime soon since I don't have access to a creator account :/

I'll try to dig more into it and try to post something that may help. Thanks for now!

Also, I think OF my've changed the process, but when I did mine, it was only send an ID to verify and get your creator account. I think they are asking for more now. Not sure tho

**Comment by DIGITALCRIMINAL** [comment]
I was able to auth into a creator account

**Comment by mwald84** [comment]
> I was able to auth into a creator account

with this code? so it must be something else on my end.

**Comment by DIGITALCRIMINAL** [comment]
I authed with the main branch master commit.

**Comment by mwald84** [comment]
> I authed with the main branch master commit.

same output here and got kicked out from browser. 😔

I'll see if I can find more useful info to help you.

**Comment by mwald84** [comment]
I tried a fresh install but same error.

**Comment by ProjektPremium** [comment]
Create a new account that isn't a creator account, subscribe to somebody free and see if you are able to scrape them or if you run into the same error.

**Comment by mwald84** [comment]
I tried it again today and it worked. Maybe I was at some kind of "timeout" from OF lol

Thanks for the help!
