### ISSUE TITLE
Incorrect models being scraped when specifying certain one

### ISSUE THREAD

**Issue by milktruckk** [DIGITALCRIMINAL/OnlyFans#1106]
I don't know how or why this is happening, but when I try and scrape a certain model from my list, I put the correct number in, scrape everything, and after it starts its process it scrapes things from other models for some reason and I don't know why. I tried using the previous version, and also the latest version 7, am I doing something wrong? I don't know why this is doing this. I included a small video of what I mean is happening

https://user-images.githubusercontent.com/10473990/116831013-02b9f300-ab7b-11eb-946e-4be0b459c370.mp4

**Comment by DIGITALCRIMINAL** [comment]
Set scrape paid content to False, and thanks for the visual.

Scraping paid content downloads every model's paid content.
