### ISSUE TITLE
extremely poor speed

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINAL/OnlyFans#1107]
![Screenshot (378)](https://user-images.githubusercontent.com/22129443/116842685-01300f80-abfb-11eb-9e69-e42bf820dbb7.png)
see screenshot above

**Comment by DIGITALCRIMINAL** [comment]
Did you set max_threads to 1?

**Comment by alectprasad** [comment]
nvm my ISP throttles OF

**Comment by DIGITALCRIMINAL** [comment]
Unlucky. If you want full speed, use a proxy with the script.
