### ISSUE TITLE
"There is nothing to scrape"

### ISSUE THREAD

**Issue by martin123ist** [DIGITALCRIMINAL/OnlyFans#1108]
![Untitled](https://user-images.githubusercontent.com/83578996/116859178-dac0a300-abff-11eb-84b4-2a964e5a45b4.png)

Trying to scrape siswet19 and Malann. but it returns "There is nothing to scrape" I've entered in all the info from the guide. Anyone having this issue and know of a fix?

**Comment by DIGITALCRIMINAL** [comment]
Are you subscribed to them

**Comment by martin123ist** [comment]
yes

**Comment by DIGITALCRIMINAL** [comment]
......... press 1 instead of putting her name

**Comment by martin123ist** [comment]
Would you look at that! It works, many thanks :D
