### ISSUE TITLE
v7 auth - x_bc?

### ISSUE THREAD

**Issue by j-ktz** [DIGITALCRIMINAL/OnlyFans#1109]
Using the newest version. Trying to fill out my auth but not sure where to find x_bc or auth_hash? There wasn't anything in the Readme about x_bc. Don't see it in the Network Debugger and the Cookie Helper doesn't pull in either. If I leave those two fields blank I get this error:

```
Auth (V1) Attempt 1/10
Access denied.

Traceback (most recent call last):
  File "/Users/USERNAME/OnlyFans-7/start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Users/USERNAME/OnlyFans-7/datascraper/main_datascraper.py", line 86, in start_datascraper
    auth_details["auth"] = api.auth.auth_details.__dict__
AttributeError: 'start' object has no attribute 'auth'
```

Also, if there's a better way to ask for help, please let me know. Don't wanna annoy or bug, but I've had issues with the last 3 releases, following the Readme and using the Cookie helper. Just trying to get mine working again. Have we thought about a Discord? Maybe that's adding too much. Just thinking of people that struggle with issues, like me. Sorry in advance!

**Comment by DIGITALCRIMINAL** [comment]
Latest commit will fix the attribute error. If we open a Discord, "investigators" will start to spy on us lol :/

You don't really need the x-bc token, but it's located in the same place as sess.

**Comment by j-ktz** [comment]
Gotcha. That makes sense. I’m on v7 this morning. If I’m still getting these errors. Any idea?

**Comment by DIGITALCRIMINAL** [comment]
Are you a creator on OnlyFans?

**Comment by j-ktz** [comment]
No.

**Comment by mstiggles** [comment]
sorry, am having the same issue. when you say "latest commit" what do you mean?
