### ISSUE TITLE
config not found

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINAL/OnlyFans#111]
I updated to the latest version available here on GitHub and now it's telling me it can't find my config.json file, despite it still living in the same directory as the script. 

`python OnlyFans/StartDatascraper.py`
`Traceback (most recent call last):`
`  File "OnlyFans/StartDatascraper.py", line 6, in <module>`
`    import modules.helpers as helpers`
`  File "/media/sdw1/holonet81/OnlyFans/modules/helpers.py", line 11, in <module>`
`    json_config = json.load(open('config.json'))`
`FileNotFoundError: [Errno 2] No such file or directory: 'config.json'`

**Comment by ElusiveZatchmo** [comment]
It only seems to find the config file if I run the script directly from the script directory

**Comment by DIGITALCRIMINAL** [comment]
Yeah, it's because of how I set up the script. Before you can start the script from anywhere.
The latest commit should fix it.
