### ISSUE TITLE
Auth (V1) Attempt 1/10 Please refresh the page

### ISSUE THREAD

**Issue by idiotabroad** [DIGITALCRIMINAL/OnlyFans#1113]
Hey

I know this has been reported before, but apparently it was fixed - yet I received it today.

1. I cloned the repo today.
2. I successfully scraped two models
3. It stopped working and gave me

```sh
Auth (V1) Attempt 1/10
Please refresh the page
Auth (V1) Attempt 2/10
Please refresh the page
Auth (V1) Attempt 3/10
Please refresh the page
Auth (V1) Attempt 4/10
Please refresh the page
Auth (V1) Attempt 5/10
Please refresh the page
Auth (V1) Attempt 6/10
Please refresh the page
Auth (V1) Attempt 7/10
Please refresh the page
Auth (V1) Attempt 8/10
Please refresh the page
Auth (V1) Attempt 9/10
Please refresh the page
Auth (V1) Attempt 10/10
Please refresh the page
```

Exact same code, exact same everything, two minutes apart it was working until it wasn't

Have logged out of OF and back in again then updated the credentials in .profiles but there is no fix

Is there a fix? What am I doing wrong? Is this bug back?

Thanks

**Comment by Kurosaki22** [comment]
running into the same issue.
Worked few hours ago.
Seems like they already changed something again

**Comment by sintaxx** [comment]
I am also getting this issue, I updated yesterday and it resolved it, and i was able to scrape a bit this morning and now i'm getting that error message again.

**Comment by nezrok** [comment]
Jup, same here

**Comment by dilemmax** [comment]
Same here

**Comment by LunarPenguin** [comment]
yes, the `sign` value as been changed, the scraper does not work until the `sign` creation code gets updated 

see: #1078

**Comment by idiotabroad** [comment]
Thanks @LunarPenguin but that's a really long thread!

Can you summarise what the sign needs to change to and where we can change it?

**Comment by pzrd** [comment]
Oof. Same happening here now, worked fine for me just two hours ago. Onlyfans desperately trying to nerf this script it seems.

**Comment by dilemmax** [comment]
Hahaha. yes. It seems everything stops working whenever I'm on the last day of a subscription.

**Comment by trevdilley** [comment]
yeah looks like **608c48da** has been changed to **608fcf2c**

and **BcsLYSyemJCNrob8u6QWziudT5Xx4LlO** needs to be something else

**Comment by dukedward** [comment]
I also noticed the sign begins with a 4 instead of 3 like previously

**Comment by Gixxa** [comment]
Can confirm, it has also stopped for me. I was still logged in but as soon as I pressed the "0" I only got scrape attempts. Closed the window and tried again - same result as OP.

**Comment by idiotabroad** [comment]
So we can expect fixes to last about ~1 day.

I wonder if it's automatically changing the sign periodically? 🤔

**Comment by trevdilley** [comment]
@DIGITALCRIMINAL how did you come up with **BcsLYSyemJCNrob8u6QWziudT5Xx4LlO** was that value in the vendor.js file?

**Comment by misterscraper** [comment]
can also confirm not working for me

**Comment by Macmasteri** [comment]
Same here. Now we waiting for DC to do the hard work over again.

Wonder if OF staff reads this too?

**Comment by estif2127** [comment]
they changed the code again :(

**Comment by misterscraper** [comment]
> Same here. Now we waiting for DC to do the hard work over again.
> 
> Wonder if OF staff reads this too?

would not surprise me when this tool is being used by the masses

**Comment by NytroDev** [comment]
yea, seems they made a decent amount of changes to the **869c** function 

https://www.diffchecker.com/ZxzDPtiS

little comparison of yesterdays vendor.js to now

**Comment by 666diabolus** [comment]
> Same here. Now we waiting for DC to do the hard work over again.
> 
> Wonder if OF staff reads this too?

I think some of them got triggered when they saw the last topic, so they change the code again lol

**Comment by misterscraper** [comment]
I wonder how many leakers are lurking at this topic right now...ready with their guns loader lol

**Comment by AshSha1** [comment]
can this be moved to non public channel ?

**Comment by Macmasteri** [comment]
This tool should be able for the world for sure, but maybe tone down the bugs :D

**Comment by 666diabolus** [comment]
so base on my acknowledgement, the "BcsLYSyemJCNrob8u6QWziudT5Xx4LlO" are meant to never change, has changed, so it may not be static as we thought

**Comment by DIGITALCRIMINAL** [comment]
> @DIGITALCRIMINAL how did you come up with **BcsLYSyemJCNrob8u6QWziudT5Xx4LlO** was that value in the vendor.js file?

Breakpoint on this return (vendor.js)

![image](https://user-images.githubusercontent.com/21285176/116922062-b939d880-ac4c-11eb-915e-e0ea6ce5d739.png)

For me it starts with "yo"

**Comment by trevdilley** [comment]
@DIGITALCRIMINAL  thanks yeah mine start with "yo" also

**Comment by DIGITALCRIMINAL** [comment]
So it's yoCCrPVmrN27vlUEQLZcW3DZH97KRVoy?

**Comment by trevdilley** [comment]
@DIGITALCRIMINAL  yep

**Comment by NytroDev** [comment]
> So it's yoCCrPVmrN27vlUEQLZcW3DZH97KRVoy?

just replaced the old value with that one, still giving off the same error. i dont believe thats all they did.

**Comment by trevdilley** [comment]
@NytroDev yep agree

**Comment by smmsnab** [comment]
But they've changed checksum algorithm also, and don't forget about 4: in the start and :608fcf2c in the end (as opposed to previous parameters 3: and :608c48da)

**Comment by dearcoding** [comment]
Well, if they change this algorithm every day it will be very hard for us to update id :(. Hope they won't change it quickly.

**Comment by smmsnab** [comment]
@dearcoding the only viable option in this case would be to move to headless browsers mode

**Comment by throwaway-cmd** [comment]
@DIGITALCRIMINAL please move this git to your own git site, that will be their next step they do it with many other projects. The devs of sites can't beat them so they just get GH to nuke the repos of these sorts of projects..

**Comment by Gixxa** [comment]
@throwaway-cmd 

inal (I'm not a lawyer) but I would say there is nothing the devs could do. Even youtube-dl is back so if youtube-dl is fine then this repo will be fine. Youtube at least does some sort of "DRM" so you can't just look at the source code and download the videos. With OF it's just a simple html5 video tag if you press F12 so their chance in court would be essentially 0.

The only real problem I could se is with the name but then again youtube-dl also has youtube in it.

**Comment by aboredpervert** [comment]
I have a feeling that this will just escalate from now on.
Fix it now, they will change it again in a few days...

**Comment by throwaway-cmd** [comment]
> @throwaway-cmd
> 
> inal (I'm not a lawyer) but I would say there is nothing the devs could do. Even youtube-dl is back so if youtube-dl is fine then this repo will be fine. Youtube at least does some sort of "DRM" so you can't just look at the source code and download the videos. With OF it's just a simple html5 video tag if you press F12 so their chance in court would be essentially 0.
> 
> The only real problem I could se is with the name but then again youtube-dl also has youtube in it.

Take Deezloadr for example. does exactly the same as this by scraping the Deezer API and Deezer got GH to take the repo down on github. they now host it elsewhere. and have not had an issue with it stopping working since. I know this might be slightly different because that is copyrighted music. but technically these models content is copyrighted too. but I am not a lawyer either. lol



> I have a feeling that this will just escalate from now on.
> Fix it now, they will change it again in a few days...

I agree, why I think it should do some sort of closed source, or some sort of obviscation himself to make it hard to see what he is doing in the code. (though that is pointless as if it's working they know that he has just reverse engineered the api so they know what has been done) But at least if it is another repo they don't know that it's been done so the patches might last longer.

**Comment by idiotabroad** [comment]
I expect they can detect it from download patterns, tbh

**Comment by nappyapp** [comment]
> yea, seems they made a decent amount of changes to the **869c** function
> 
> https://www.diffchecker.com/ZxzDPtiS
> 
> little comparison of yesterdays vendor.js to now

@DIGITALCRIMINAL 

I don't understand the algorithm but it looks like all the array indices rotated alphabetically one forward, like t->u, E->F, etc. Maybe it automatically rolls forward each day or something?

**Comment by dcex** [comment]
Can't we use something like `pyv8` to call the function from the `vendor.js` file instead of reverse engineering it?

**Comment by trevdilley** [comment]
anyone having any better luck than me getting the sha1 and the checksum?

**Comment by nappyapp** [comment]
> Can't we use something like `pyv8` to call the function from the `vendor.js` file instead of reverse engineering it?

I don't know enough about JS and Python but yes shouldn't this be possible?

**Comment by LunarPenguin** [comment]
> I agree, why I think it should do some sort of closed source, or some sort of obviscation himself to make it hard to see what he is doing in the code. (though that is pointless as if it's working they know that he has just reverse engineered the api so they know what has been done) But at least if it is another repo they don't know that it's been done so the patches might last longer.

I disagree. going closed source is not doing anyone any favors, it might buy us some time initially but in the end we're still reliant on the `API` of OF which they could sabotage at any moment. Going closed source also means that no "auditing" can be done and that fixes for `API` changes will probably take more time because only the maintainers are able to contribute to the source code.

i do think that we should be a bit less cocky from time to time

**Comment by ofext** [comment]
We already know how to create the sha1 hash, the new constants for the hash are:

```
var t = Date.now();
var str1 = "yoCCrPVmrN27vlUEQLZcW3DZH97KRVoy";
var str2 = "608fcf2c";
var text = str1 + "\n" + t + "\n" + path + "\n" + userId;
var hash = sha1(text);

```

Given the hash, I've isolated the function to get the new sign. If anyone is able to reduce it even further until it's as small as the last one, be my guest:

[https://jsfiddle.net/drL4t7oz/](https://jsfiddle.net/drL4t7oz/)

**Comment by hippothon** [comment]
```
hash.charCodeAt(14) +
hash.charCodeAt(21) +
hash.charCodeAt(2) +
hash.charCodeAt(39) +
hash.charCodeAt(25) +
hash.charCodeAt(33) +
hash.charCodeAt(17) +
hash.charCodeAt(24) +
hash.charCodeAt(17) +
hash.charCodeAt(28) +
hash.charCodeAt(23) +
hash.charCodeAt(16) +
hash.charCodeAt(28) +
hash.charCodeAt(5) +
hash.charCodeAt(5) +
hash.charCodeAt(20) +
hash.charCodeAt(22) +
hash.charCodeAt(25) +
hash.charCodeAt(36) +
hash.charCodeAt(17) +
hash.charCodeAt(39) +
hash.charCodeAt(14) +
hash.charCodeAt(11) +
hash.charCodeAt(11) +
hash.charCodeAt(7) +
hash.charCodeAt(32) +
hash.charCodeAt(19) +
hash.charCodeAt(18) +
hash.charCodeAt(30) +
hash.charCodeAt(31) +
hash.charCodeAt(38) +
hash.charCodeAt(4) +
-148

```

**Comment by singularitysky** [comment]
Can we not just use [Js2Py](https://github.com/PiotrDabkowski/Js2Py)  to translate the offending module to python?

**Comment by DIGITALCRIMINAL** [comment]
> ```
> hash.charCodeAt(14) +
> hash.charCodeAt(21) +
> hash.charCodeAt(2) +
> hash.charCodeAt(39) +
> hash.charCodeAt(25) +
> hash.charCodeAt(33) +
> hash.charCodeAt(17) +
> hash.charCodeAt(24) +
> hash.charCodeAt(17) +
> hash.charCodeAt(28) +
> hash.charCodeAt(23) +
> hash.charCodeAt(16) +
> hash.charCodeAt(28) +
> hash.charCodeAt(5) +
> hash.charCodeAt(5) +
> hash.charCodeAt(20) +
> hash.charCodeAt(22) +
> hash.charCodeAt(25) +
> hash.charCodeAt(36) +
> hash.charCodeAt(17) +
> hash.charCodeAt(39) +
> hash.charCodeAt(14) +
> hash.charCodeAt(11) +
> hash.charCodeAt(11) +
> hash.charCodeAt(7) +
> hash.charCodeAt(32) +
> hash.charCodeAt(19) +
> hash.charCodeAt(18) +
> hash.charCodeAt(30) +
> hash.charCodeAt(31) +
> hash.charCodeAt(38) +
> hash.charCodeAt(4) +
> -148
> ```

Thanks, it works.

Latest commit includes the function.
https://github.com/DIGITALCRIMINAL/OnlyFans/blob/cfcf04b3168ca0e25ea614cbd16edb6662ba91fa/apis/onlyfans/onlyfans.py#L33

**Comment by AshSha1** [comment]
After this change , got below error:

I:\NN\NN\OnlyFans-6.4.6\OnlyFans-6.4.6>python start_ofd.py
Site: 0 = onlyfans | x = Exit
0
Session IP:

Traceback (most recent call last):

  File "I:\NN\NN\OnlyFans-6.4.6\OnlyFans-6.4.6\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "I:\NN\NN\OnlyFans-6.4.6\OnlyFans-6.4.6\datascraper\main_datascraper.py", line 60, in start_datascraper
    api = main_helper.process_profiles(
  File "I:\NN\NN\OnlyFans-6.4.6\OnlyFans-6.4.6\helpers\main_helper.py", line 604, in process_profiles
    auth = api.set_auth_details(
  File "I:\NN\NN\OnlyFans-6.4.6\OnlyFans-6.4.6\apis\onlyfans\onlyfans.py", line 488, in set_auth_details
    auth = create_auth()
  File "I:\NN\NN\OnlyFans-6.4.6\OnlyFans-6.4.6\apis\onlyfans\onlyfans.py", line 514, in __init__
    self.session_manager = api_helper.session_manager(
TypeError: __init__() got an unexpected keyword argument 'session_rules'

**Comment by singularitysky** [comment]
Odd. Prior to update was running at maxthreads -1 with no problems. After the update ran into the same problem of not all the models showing up. Changed back to single thread and it worked again.

**Comment by sintaxx** [comment]
Latest pull works for me! she's back in action !

**Comment by neuri4848** [comment]
> Odd. Prior to update was running at maxthreads -1 with no problems. After the update ran into the same problem of not all the models showing up. Changed back to single thread and it worked again.

i changed it to 1 in the settings (not the api) works for me

**Comment by TheNytangel** [comment]
The fourth part of the sign that's changing - previously 608c48da and now 608fcf2c - this looks like a hexidecimal version of an epoch timestamp in seconds. I don't have the previous vendor.js to look back at, but this is what I've observed from the new file:

1. 608fcf2c converted to decimal and then analyzed as a timestamp is **2021-05-03 10:23**:40 UTC
2. The vendor.js full file name from Chrome developer tools is vendor.js?rev=**202105031022**-6ba1f1c47b

It looks like the revision number and the hex code that is being used are similar but off by a minute, so maybe this is just a coincidence. Just an observation.

**Comment by DIGITALCRIMINAL** [comment]
> The fourth part of the sign that's changing - previously 608c48da and now 608fcf2c - this looks like a hexidecimal version of an epoch timestamp in seconds. I don't have the previous vendor.js to look back at, but this is what I've observed from the new file:
> 
> 1. 608fcf2c converted to decimal and then analyzed as a timestamp is **2021-05-03 10:23**:40 UTC
> 2. The vendor.js full file name from Chrome developer tools is vendor.js?rev=**202105031022**-6ba1f1c47b
> 
> It looks like the revision number and the hex code that is being used are similar but off by a minute, so maybe this is just a coincidence. Just an observation.

I was going to say if 4: is the day and :608 is the revision then it might be dynamically generated?

**Comment by TheNytangel** [comment]
> > The fourth part of the sign that's changing - previously 608c48da and now 608fcf2c - this looks like a hexidecimal version of an epoch timestamp in seconds. I don't have the previous vendor.js to look back at, but this is what I've observed from the new file:
> > 
> > 1. 608fcf2c converted to decimal and then analyzed as a timestamp is **2021-05-03 10:23**:40 UTC
> > 2. The vendor.js full file name from Chrome developer tools is vendor.js?rev=**202105031022**-6ba1f1c47b
> > 
> > It looks like the revision number and the hex code that is being used are similar but off by a minute, so maybe this is just a coincidence. Just an observation.
> 
> I was going to say if 4: is the day and :608 is the revision then it might be dynamically generated?

The first number so far does seem to be incrementing, but is it by day? It seems the 3: lasted both Saturday and Sunday.

**Comment by DIGITALCRIMINAL** [comment]
> > > The fourth part of the sign that's changing - previously 608c48da and now 608fcf2c - this looks like a hexidecimal version of an epoch timestamp in seconds. I don't have the previous vendor.js to look back at, but this is what I've observed from the new file:
> > > 
> > > 1. 608fcf2c converted to decimal and then analyzed as a timestamp is **2021-05-03 10:23**:40 UTC
> > > 2. The vendor.js full file name from Chrome developer tools is vendor.js?rev=**202105031022**-6ba1f1c47b
> > > 
> > > It looks like the revision number and the hex code that is being used are similar but off by a minute, so maybe this is just a coincidence. Just an observation.
> > 
> > 
> > I was going to say if 4: is the day and :608 is the revision then it might be dynamically generated?
> 
> The first number so far does seem to be incrementing, but is it by day? It seems the 3: lasted both Saturday and Sunday.

Yeah, but on the 3rd they changed the number to 4th - maybe today they'll change it to 5.

**Comment by Comfy-Mittens** [comment]
Here is a [link](https://static.cdn.onlyfans.com/theme/onlyfans/spa/vendor.js?rev=202104301813-271ad07a42) to the old vendor.js.
```
https://static.cdn.onlyfans.com/theme/onlyfans/spa/vendor.js?rev=202104301813-271ad07a42
60 8C 48 DA = 04/30/2021 18:13:46
```

**Comment by Luke-L** [comment]
any updates? still getting the same errors lol 

> Auth (V1) Attempt 10/10

>Please refresh the page
Traceback (most recent call last):
  File "B:\OnlyFans-6.4.3\OF-Extract\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "B:\OnlyFans-6.4.3\OF-Extract\datascraper\main_datascraper.py", line 79, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "B:\OnlyFans-6.4.3\OF-Extract\modules\onlyfans.py", line 118, in account_setup
    cookies = oflogin.login(auth, domain, proxy)
  File "B:\OnlyFans-6.4.3\OF-Extract\extras\OFLogin\start_ofl.py", line 67, in login
    auth_details = api.auth.auth_details
AttributeError: 'create_auth' object has no attribute 'auth'

**Comment by DIGITALCRIMINAL** [comment]
> any updates? still getting the same errors lol
> 
> > Auth (V1) Attempt 10/10
> 
> > Please refresh the page
> > Traceback (most recent call last):
> > File "B:\OnlyFans-6.4.3\OF-Extract\start_ofd.py", line 43, in 
> > apis = main_datascraper.start_datascraper(json_config, site_name_lower)
> > File "B:\OnlyFans-6.4.3\OF-Extract\datascraper\main_datascraper.py", line 79, in start_datascraper
> > setup, subscriptions = module.account_setup(
> > File "B:\OnlyFans-6.4.3\OF-Extract\modules\onlyfans.py", line 118, in account_setup
> > cookies = oflogin.login(auth, domain, proxy)
> > File "B:\OnlyFans-6.4.3\OF-Extract\extras\OFLogin\start_ofl.py", line 67, in login
> > auth_details = api.auth.auth_details
> > AttributeError: 'create_auth' object has no attribute 'auth'

Logging in via browser is broken atm lol :/

**Comment by edmundackah** [comment]
For the key components can't we implement a webview login and intercept the initial API calls and read the response headers to get the front and last part of the signature?

**Comment by alectprasad** [comment]
use [this extension](https://chrome.google.com/webstore/detail/downloader-for-onlyfansco/pdbbabjcnanbkimdgcdfbnghhmchomnh) instead. it works inside the browser so they can't block it.

**Comment by idiotabroad** [comment]
It's working. Happy for me to close?

**Comment by DIGITALCRIMINAL** [comment]
The script would then just be converted into selenium.

**Comment by trevdilley** [comment]
See you guys in a few days :)

**Comment by ProjektPremium** [comment]
> Odd. Prior to update was running at maxthreads -1 with no problems. After the update ran into the same problem of not all the models showing up. Changed back to single thread and it worked again.

Same, can't get it working with more than 1 thread.

**Comment by neuri4848** [comment]
> > Odd. Prior to update was running at maxthreads -1 with no problems. After the update ran into the same problem of not all the models showing up. Changed back to single thread and it worked again.
> 
> Same, can't get it working with more than 1 thread.
> 
> I'm also getting stuck on random models.

Change max thread to 1 in the settings

**Comment by ProjektPremium** [comment]
> > > Odd. Prior to update was running at maxthreads -1 with no problems. After the update ran into the same problem of not all the models showing up. Changed back to single thread and it worked again.
> > 
> > 
> > Same, can't get it working with more than 1 thread.
> > I'm also getting stuck on random models.
> 
> Change max thread to 1 in the settings

I am using 1 thread. Been testing it with other variables but 1 only works for now. But still get stuck on particular models. It's fine though, I can wait it out until there is a fix.

**Comment by nappyapp** [comment]
Write a bash wrapper script to run multiple instances of the scraper with
different models each lol

**Comment by ProjektPremium** [comment]
> Write a bash wrapper script to run multiple instances of the scraper with different models each lol

Usually I run it remotely via remote machines but only use them locally to test them and once they are working again I move them to my remote devices.

As I said, all good. I will deal with it while it's slow like this until the next episode.

**Comment by dilemmax** [comment]
Mine's still not working :/

Site: 0 = onlyfans | x = Exit
0
Session IP: 1*3

Choose Profile
Names: Username = username  |  0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Please refresh the page
Auth (V1) Attempt 2/10
Please refresh the page
Auth (V1) Attempt 3/10
Please refresh the page
Auth (V1) Attempt 4/10
Please refresh the page
Auth (V1) Attempt 5/10
Please refresh the page
Auth (V1) Attempt 6/10
Please refresh the page
Auth (V1) Attempt 7/10
Please refresh the page
Auth (V1) Attempt 8/10
Please refresh the page
Auth (V1) Attempt 9/10
Please refresh the page
Auth (V1) Attempt 10/10
Please refresh the page
Traceback (most recent call last):
  File "C:\OLF 7\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\OLF 7\datascraper\main_datascraper.py", line 79, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "C:\OLF 7\modules\onlyfans.py", line 118, in account_setup
    cookies = oflogin.login(auth, domain, proxy)
  File "C:\OLF 7\extras\OFLogin\start_ofl.py", line 67, in login
    auth_details = api.auth.auth_details
AttributeError: 'create_auth' object has no attribute 'auth'

**Comment by dilemmax** [comment]
Changing the thread from -1 to 1 in config.json doesn't make a difference.

**Comment by bobsage123** [comment]
7.01 still cant auth

**Comment by mwald84** [comment]
> 7.01 still cant auth

use the code in master instead of the release. It works for me.
