### ISSUE TITLE
Stuck at Download Processing

### ISSUE THREAD

**Issue by dcex** [DIGITALCRIMINAL/OnlyFans#1117]
Not sure if it is related to the last issue or not, but sometimes I'm getting stuck on the download processing.

Download Processing           
Name: _____ | Type: Posts | Count: 4204 Images | Directory: xxxxxx

0it [00:00, ?it/s]

Oddly enough, when I check the process on NetLimiter I see that something is being downloaded.
![imagem_2021-05-04_002223](https://user-images.githubusercontent.com/31260082/116957664-cbc50980-ac6e-11eb-9ac6-d6c0d82ee4ce.png)

**Comment by dcex** [comment]
It always happens at the same 'place'. Same models with the same kind of download -- like in one case it got stuck trying to download posted pictures and with another model it was stuck while trying to download posted videos.

In one case it downloaded a couple of pictures and suddenly stopped downloading anything, I restarted the program and got the same behavior as the one from my first post. (0it [00:00, ?it/s])

**Comment by lEtranger1942** [comment]
For me I selected what I want to scrape, and it remains stuck. max_threads is 1 and paid content is false
![Screenshot from 2021-05-04 10-23-07](https://user-images.githubusercontent.com/33520766/116972153-46b80f80-acc3-11eb-97a8-f3911ccac6ff.png)

Anybody has posibile solution ?

**Comment by salamihawk** [comment]
I'm having the same issue. A model posted a mixed post with pictures and videos (3x videos) and the pictures downloaded fine on the first run, but now it sticks at the videos and just dies. I've disabled paid content scraping. let's see how it works

**Comment by salamihawk** [comment]
No, doesn't seem to have helped. it still hangs at:
Name: <name>| Type: Posts | Count: _69_ Videos | Directory: <path>

0it [00:00, ?it/s]

**Comment by salamihawk** [comment]
I just cloned the latest repository and it downloaded the missing videos!

**Comment by dcex** [comment]
Yep, I think it is solved. Been using for a while with the latest commit and that issue didn't happen again.
