### ISSUE TITLE
Missing posts

### ISSUE THREAD

**Issue by dpsbrdi** [DIGITALCRIMINAL/OnlyFans#1118]
Started with any commit after https://github.com/DIGITALCRIMINAL/OnlyFans/commit/b25deb6221715b60e829524eb112ae06036db304 and is still persisting up to the latest commit with the new signed headers

**Comment by ProjektPremium** [comment]
Change your max_threads to 1 not -1

**Comment by misterscraper** [comment]
> Change your max_threads to 1 not -1

on which file do we adjust this? I'm getting a ton of missing posts while scraping

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit
