### ISSUE TITLE
Not sure if this is a bug or issue on my end...

### ISSUE THREAD

**Issue by Mitchwtn** [DIGITALCRIMINAL/OnlyFans#112]
Traceback (most recent call last):
  File "StartDatascraper.py", line 68, in <module>
    array = x.get_subscriptions(session[0], app_token, session[2])
  File "/home/../Downloads/OnlyFans-master/modules/onlyfans.py", line 417, in get_subscriptions
    result_date = datetime.fromisoformat(
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

**Comment by DIGITALCRIMINAL** [comment]
What is your Python version

**Comment by Mitchwtn** [comment]
Python 3.8.0

**Comment by DIGITALCRIMINAL** [comment]
Do you have any other Python version installed?

**Comment by Mitchwtn** [comment]
Yes, I was trying to use pyenv, as it's "preferred" but could not make it work, so I scrapped it compiled 3.8 and the problem was definitely on my end because now it's working, except only if I run it as root which I don't want to do so I messed something up again.  Anyway, problem was and is on my end.  Thanks.
