### ISSUE TITLE
Please refresh the page & Traceback error

### ISSUE THREAD

**Issue by Scontoni** [DIGITALCRIMINAL/OnlyFans#1120]
Slightly different to the other issue occurring at the moment:
Brand new download of the master branch and fresh setup of auth.json

```
Auth (V1) Attempt 10/10
Please refresh the page
Traceback (most recent call last):
  File "...\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "...\OnlyFans-master\datascraper\main_datascraper.py", line 79, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "...\OnlyFans-master\modules\onlyfans.py", line 118, in account_setup
    cookies = oflogin.login(auth, domain, proxy)
  File "...\OnlyFans-master\extras\OFLogin\start_ofl.py", line 67, in login
    auth_details = api.auth.auth_details
AttributeError: 'create_auth' object has no attribute 'auth'
```

**Comment by ProjektPremium** [comment]
#1119 Problem already reported.

**Comment by Scontoni** [comment]
> 
> 
> #1119 Problem already reported.

Is 'AttributeError: 'create_auth' object has no attribute 'auth'' the same?

**Comment by ProjektPremium** [comment]
Not sure. You'll have to wait it out.

**Comment by ThisWickedGame** [comment]
I had that AttributeError on mine, fix is to change lines 66 & 67 of OnlyFans-master\extras\OFLogin\start_ofl.py to the following:

def login(auth, domain, proxy=None):
    auth_details = auth.auth_details

**Comment by Scontoni** [comment]
Cheers @ThisWickedGame ! Below fix works:

> Change lines 66 & 67 of OnlyFans-master\extras\OFLogin\start_ofl.py to the following:
> 
```
def login(auth, domain, proxy=None):
auth_details = auth.auth_details
```
