### ISSUE TITLE
OF Creator = Session Lock

### ISSUE THREAD

**Issue by ofcreator00** [DIGITALCRIMINAL/OnlyFans#1126]
Updated to the latest release of the code and still getting this error below.

I am a creator so has that got something to do with it?

> Choose Profile
Names: Username = username  |  0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Session lock
Auth (V1) Attempt 3/10
Session lock
Auth (V1) Attempt 4/10
Session lock
Auth (V1) Attempt 5/10
Session lock
Auth (V1) Attempt 6/10
Session lock
Auth (V1) Attempt 7/10
Session lock
Auth (V1) Attempt 8/10
Session lock
Auth (V1) Attempt 9/10
Session lock
Auth (V1) Attempt 10/10
Session lock
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.08 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit

**Comment by stran0s** [comment]
same problem here

**Comment by DIGITALCRIMINAL** [comment]
Can't do anything unless I've got access.
