### ISSUE TITLE
Not actually downloading content

### ISSUE THREAD

**Issue by evilalmus** [DIGITALCRIMINAL/OnlyFans#1128]
As of the most recent update, it seems to be working again! (Thank you!)

The problem is that while it is not producing any errors, and it is creating the directory structures for the downloads it is not actually downloading any content. If I'm doing something wrong I can't figure out what it could be.

**Comment by dwill112** [comment]
Mines isn't downloading content even tho it does the progress bar, but doesn't save to directory selected (Downloads folder).
<img width="1306" alt="Screen Shot 2021-05-04 at 10 02 16 PM" src="https://user-images.githubusercontent.com/83682694/117089784-84995000-ad24-11eb-965d-44564e3f4b74.png">

**Comment by evilalmus** [comment]
Nevermind my report. I didn't realize that it scrapes all of the metadata before it starts downloading. It is working fine for me.
