### ISSUE TITLE
Thread closed, and ready for deletion.

### ISSUE THREAD

**Issue by ApacheTech** [DIGITALCRIMINAL/OnlyFans#1129]
Thread closed, and ready for deletion.

**Comment by kevinsheeks** [comment]
same is happening to me on chrome

**Comment by DIGITALCRIMINAL** [comment]
Login via the browser with the script

**Comment by ApacheTech** [comment]
Tried with geckodriver:

Auth (V1) Attempt 1/10
Please refresh the page
Auth (V1) Attempt 2/10
Please refresh the page
Auth (V1) Attempt 3/10
Please refresh the page
Auth (V1) Attempt 4/10
Please refresh the page
Auth (V1) Attempt 5/10
Please refresh the page
Auth (V1) Attempt 6/10
Please refresh the page
Auth (V1) Attempt 7/10
Please refresh the page
Auth (V1) Attempt 8/10
Please refresh the page
Auth (V1) Attempt 9/10
Please refresh the page
Auth (V1) Attempt 10/10
Please refresh the page
Opening Browser
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 2.06 Minutes
Now exiting.

**Comment by ApacheTech** [comment]
Got the x_bc and other info needed by refreshing and loading the web dev window quickly. Now get:

Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Session lock
Auth (V1) Attempt 3/10
Session lock
Auth (V1) Attempt 4/10
Session lock
Auth (V1) Attempt 5/10
Session lock
Auth (V1) Attempt 6/10
Session lock
Auth (V1) Attempt 7/10
Session lock
Auth (V1) Attempt 8/10
Session lock
Auth (V1) Attempt 9/10
Session lock
Auth (V1) Attempt 10/10
Session lock
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.08 Minutes
Now exiting.

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit

**Comment by ApacheTech** [comment]
That solved it. It's a real pain that they're abusing the debugger like that. Gotta look for a way to strip that function out of Firefox entirely. Get it to completely ignore the debugger keyword.

**Comment by dcex** [comment]
On Chromium browsers you can click on the blue icon to disable breakpoints (it will turn blue once you click)
![imagem_2021-05-04_214058](https://user-images.githubusercontent.com/31260082/117085879-6aaa3e00-ad21-11eb-8489-25456f02474d.png)

**Comment by sintaxx** [comment]
I typically use Ctrl+Shift+E to access the network debugger

**Comment by ApacheTech** [comment]
> 
> 
> On Chromium browsers you can click on the blue icon to disable breakpoints (it will turn blue once you click)
> ![imagem_2021-05-04_214058](https://user-images.githubusercontent.com/31260082/117085879-6aaa3e00-ad21-11eb-8489-25456f02474d.png)

Even with breakpoints deactivated, Firefox crashes to desktop. Even with all debugger options disabled within about:config, Firefox still becomes totally unresponsive, as soon as you press F12, or right-click -> Inspect, or Ctrl-Shift-I.

**Comment by ofext** [comment]
> > On Chromium browsers you can click on the blue icon to disable breakpoints (it will turn blue once you click)
> > ![imagem_2021-05-04_214058](https://user-images.githubusercontent.com/31260082/117085879-6aaa3e00-ad21-11eb-8489-25456f02474d.png)
> 
> Even with breakpoints deactivated, Firefox crashes to desktop. Even with all debugger options disabled within about:config, Firefox still becomes totally unresponsive, as soon as you press F12, or right-click -> Inspect, or Ctrl-Shift-I.

That’s because the function that has the debugger instruction is called from an Infinite loop somewhere in the obfuscated code. So when you tell the browser to ignore the debugger, the Infinite loop kicks in and it consumes all the cpu. You can check it in task manager

**Comment by SafadezaSemLimites** [comment]
![Sem título](https://user-images.githubusercontent.com/78769969/117096218-a47d4380-ad25-11eb-9725-08b6aa76c2b0.png)
How does a noob like me bypass this shit?

**Comment by TheTrueColonel** [comment]
> 
> 
> ![Sem título](https://user-images.githubusercontent.com/78769969/117096218-a47d4380-ad25-11eb-9725-08b6aa76c2b0.png)
> How does a noob like me bypass this shit?

That looks to be something to do with an installed antivirus or network configuration.

**Comment by Macmasteri** [comment]
This debugger thing is it something OF has enables or what?

**Comment by ApacheTech** [comment]
> 
> 
> This debugger thing is it something OF has enables or what?

Yes. They're abusing browser debugging capabilities; making browsers crash to desktop whenever you open the development console. It's a trick born from blackhat development. I think their Red Team might have started running the show. :p

**Comment by Macmasteri** [comment]
> > This debugger thing is it something OF has enables or what?
> 
> Yes. They're abusing browser debugging capabilities; making browsers crash to desktop whenever you open the development console. It's a trick born from blackhat development. I think their Red Team might have started running the show. :p

Ok. My browser does not crash but getting logged out afterwards.

When using geckodriver. Do I need to start it from the folder OFLogin?
I filled in the user:pass in auth file. But does not coming to a browser when running the script?
I feel like a total n00b here.

**Comment by ApacheTech** [comment]
This isn't the right place to ask. Your questions are about Geckodriver, not about the Web Dev console. You're best off starting a new issue, or responding to one that deals with the relevant topic.

**Comment by SafadezaSemLimites** [comment]
> 
> 
> > ![Sem título](https://user-images.githubusercontent.com/78769969/117096218-a47d4380-ad25-11eb-9725-08b6aa76c2b0.png)
> > How does a noob like me bypass this shit?
> 
> That looks to be something to do with an installed antivirus or network configuration.

That's exactly what it is. I just don't know how to bypass it. It blocks any connections the script tries to make when I refresh OF's home page.

**Comment by ofext** [comment]
> > That looks to be something to do with an installed antivirus or network configuration.
> 
> That's exactly what it is. I just don't know how to bypass it. It blocks any connections the script tries to make when I refresh OF's home page.

According to the text, it's Kaspersky blocking it, so check the following two links explaining how to add an exception so it doesn't block a specific website:

https://support.kaspersky.com/common/error/other/15335
https://support.kaspersky.com/common/safemoney/12489
