### ISSUE TITLE
"Nothing to scrape" when attempting to authorize via browser

### ISSUE THREAD

**Issue by metalmau5** [DIGITALCRIMINAL/OnlyFans#1131]
I was getting the "refresh the page" error so I'm trying to authorize via browser, but I'm not sure if I'm doing this method correctly. It will open a browser window, ask me to login and do the captcha stuff, then the window closes and I get this. 
![Screenshot 2021-05-04 18 26 43](https://user-images.githubusercontent.com/83531164/117088092-51e05f00-ad06-11eb-95c2-b9276527c509.png)

**Comment by dhanjaar** [comment]
I get 
Auth (V1) Attempt 1/10
Welcome XXXX XXXXX | XXXXXXXX
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.08 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit

**Comment by bluebower** [comment]
I had the same issue, and came across an instruction to download geckodriver.exe into \OnlyFans-7.01\extras\OFLogin
Chrome is my default browser, and as I came up to 'Opening Browser' it opened up Firefox instead :-/

**Comment by Ferroith** [comment]
I updated the "sess" part in "profiles/default/auth.json". Now it works again

**Comment by ofcreator00** [comment]
Same problem here. Are you an OF creator? This may be the root of the issue.

**Comment by metalmau5** [comment]
> I had the same issue, and came across an instruction to download geckodriver.exe into \OnlyFans-7.01\extras\OFLogin
> Chrome is my default browser, and as I came up to 'Opening Browser' it opened up Firefox instead :-/

I believe that’s because geckodriver is Firefox based. 



> Same problem here. Are you an OF creator? This may be the root of the issue.

I am not.

**Comment by justathrowey** [comment]
Confirming with @metalmau5 that I am also experiencing this problem. Not a creator myself, either.

**Comment by Ferroith** [comment]
Downloaded the latest commit. Now it works again.

**Comment by justathrowey** [comment]
just tried it myself with the latest commit - no luck. same issue.

questions

- what is your useragent? mine is ` "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/90.0.4430.93 Safari\/537.36",`
- what is normally your default browser where you got your initial creds for `auth.json` from OF? i usually have to get it through Chrome

**Comment by Ferroith** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.51

I just use the new Edge which is chromium

**Comment by bluebower** [comment]
I've just downloaded the latest commit and it works again.

`Are you an OF creator?`
No; just for subscribing to content.

`What is your user agent?`
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

**Comment by justathrowey** [comment]
Just did it again - no dice on my end

```
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Opening Browser
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 1.4 Minutes
Now exiting.
```
Here's my auth...
```
{
  "auth": {
    "username": "default",
    "auth_id": "xxx0973",
    "auth_hash": "",
    "auth_uniq_": "",
    "sess": "xxxx",
    "app_token": "xxx57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/90.0.4430.93 Safari\/537.36",
    "email": "xxx@gmail.com",
    "password": "xxx",
    "support_2fa": true,
    "active": true
  }
}

```

**Comment by metalmau5** [comment]
Never got the browser method working, but the latest build is working the normal way.
