### ISSUE TITLE
Cannot get auth config because network debugger automatically stop.

### ISSUE THREAD

**Issue by 666diabolus** [DIGITALCRIMINAL/OnlyFans#1134]
I'm on the latest release and I cannot get those auth config information because when I go to the network debugger, it said paused in debugger and puts me back in the sources tab.
I tried on other website and everything is fine, may be this is another act of them ? 
![InkedDebug_LI](https://user-images.githubusercontent.com/57742957/117117609-f1aaf500-adb9-11eb-9921-0ed772a5e159.jpg)

**Comment by misterscraper** [comment]
i imagine this is why the latest commit isn't working anymore?

**Comment by Gixxa** [comment]
You need to disable Breakpoints. 

Take a look at the right top side there is a "stop sign" icon with a "pause" icon in it. Click on the icon to the left of that.  It will work then. 

![icon](https://user-images.githubusercontent.com/6295802/117120707-f65cb280-ad93-11eb-913f-581abe8c34ec.JPG)

**Comment by misterscraper** [comment]
<img width="254" alt="Screenshot 2021-05-05 at 10 25 22" src="https://user-images.githubusercontent.com/33800433/117121262-446db800-ad8c-11eb-80a6-8f29c617a43a.png">

anyone else getting this issue?

**Comment by ZOMGsheikh** [comment]
> <img alt="Screenshot 2021-05-05 at 10 25 22" width="254" src="https://user-images.githubusercontent.com/33800433/117121262-446db800-ad8c-11eb-80a6-8f29c617a43a.png">
> 
> anyone else getting this issue?

Yep, I am getting that.

**Comment by Gixxa** [comment]
Then you are not on the last commit. 

I just started it again and it works fine.

**Comment by Macmasteri** [comment]
> You need to disable Breakpoints.
> 
> Take a look at the right top side there is a "stop sign" icon with a "pause" icon in it. Click on the icon to the left of that. It will work then.
> 
> ![icon](https://user-images.githubusercontent.com/6295802/117120707-f65cb280-ad93-11eb-913f-581abe8c34ec.JPG)
> 
> edit:
> 
> @misterscraper
> 
> Last commit (still) works fine as of now.

Tried this but still getting "session locked" and getting kicked out from the account.
Do you need to this procedure every time for each account?

**Comment by ApacheTech** [comment]
> 
> 
> You need to disable Breakpoints.
> 
> Take a look at the right top side there is a "stop sign" icon with a "pause" icon in it. Click on the icon to the left of that. It will work then.
> 
> ![icon](https://user-images.githubusercontent.com/6295802/117120707-f65cb280-ad93-11eb-913f-581abe8c34ec.JPG)
> 
> edit:
> 
> @misterscraper
> 
> Last commit (still) works fine as of now.

Doing this will cause your whole browser to crash to desktop. It might ignore the debugger keyword, but it then runs the empty infinite loop, indefinitely. Causes Firefox to become completely unresponsive, and it eventually conks out.

**Comment by Gixxa** [comment]
@Macmasteri 

Are you using a creator account? This is a scrape I just started like 10 sec. before typing this:

![scrape](https://user-images.githubusercontent.com/6295802/117138686-a689e580-adab-11eb-94ea-d1e4cc3b4d75.jpg)

@ApacheTech 

Sounds like a Firefox bug. On Vivaldi 3.8.2259.37 (Stable channel) (32-Bit) it works without a problem.

**Comment by Macmasteri** [comment]
@Gixxa 

No :)

**Comment by simonrule** [comment]
im still getting refresh page, im doing everything right

**Comment by Gamma-Velorum** [comment]
Since when was this a requirement? Where is the tutorial/instructions? The int no longer contains auth_hash and auth_uniq. I was able to find x_bc. What's this other shit now?
