### ISSUE TITLE
Scrapped recently expired accounts

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#114]
I'm not sure if it's the timezone difference but whenever an account is moved to [Expired](https://onlyfans.com/my/subscribes/expired), I can still access the account and they still show up in my feed but I can't scrap them. I usually end up using IDM to download the videos but still want scrap the posts to give it meaningful filenames.

Is there a way to scrap these accounts? I usually scrap an account on the last day just to avoid having to check every other days for new contents.

**Comment by DIGITALCRIMINAL** [comment]
@dilemmax latest commit/next release will allow this c:

**Comment by dilemmax** [comment]
You're champ. Thank you for fixing this for me :)

**Comment by dilemmax** [comment]
Hey there.

I just tried that scrap an account that expired today but it's not showing up the name :(

**Comment by DIGITALCRIMINAL** [comment]
The name disappears at midnight UTC timezone. Is the content still available on OF?

**Comment by dilemmax** [comment]
Yes it is. I'm using a chrome extension to scrap the links for the videos. I figured I test this out to let you know if it works or not.

I'm from Perth, Western Australia if that helps.

**Comment by dilemmax** [comment]
Interestingly, I have two accounts that are supposed to expire today but it's still in the active section, whereas the third one has already been moved to the expired section. All three with 17/01/2020 as the expiry date.

**Comment by DIGITALCRIMINAL** [comment]
Oh so the ones that don't show up on the script, are they in the active tab or expired?

**Comment by dilemmax** [comment]
Hey sorry for the late reply, I somehow missed the latest reply notification.

The one that aren't showing up is in the expired tab.

**Comment by DIGITALCRIMINAL** [comment]
> Hey sorry for the late reply, I somehow missed the latest reply notification.
> 
> The one that aren't showing up is in the expired tab.

But you can still see their content?

**Comment by dilemmax** [comment]
yes I can. I was able to use a chrome extension to scrap the video links to download with IDM.

I have another account that is expiry on the 24th if you can get something for me to test it out?
