### ISSUE TITLE
incorrect download size

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINAL/OnlyFans#1140]
![image](https://user-images.githubusercontent.com/22129443/117236472-60359480-ae46-11eb-813c-0e16f23045ad.png)
why does the program say 45.7 gb downloaded when the folder size is 33.4 gb?

**Comment by adamwinn** [comment]
Could be a GiB vs GB issue.  Or maybe there's misc files.

**Comment by Gixxa** [comment]
Or duplicates that get reported but not downloaded.

**Comment by alectprasad** [comment]
I think I figured out what is happening. the program keeps partial downloads cached somewhere and copies them to that folder when the whole thing is downloaded. this cache gets deleted when the program exits and have to be downloaded again.
