### ISSUE TITLE
python2: can't open file 'brutescrape.py': [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Siyamitcenter** [DIGITALCRIMINAL/OnlyFans#1144]
python2 brutescrape.py
python2: can't open file 'brutescrape.py': [Errno 13] Permission denied

**Comment by ProjektPremium** [comment]
Maybe your version of Python might just be out of date.

**Comment by Siyamitcenter** [comment]
What can I do now, please help me

**Comment by lEtranger1942** [comment]
Update tip python3 and read the documentation. Everything is explained there

**Comment by Siyamitcenter** [comment]
please  help my problem solved, team viewer /anydesk support
