### ISSUE TITLE
Script not scraping anything?

### ISSUE THREAD

**Issue by MysteriousFigure** [DIGITALCRIMINAL/OnlyFans#1147]
I tried running the script for the first time today, and while it logs in properly (the username shows as mine and the user list is correct etc.), whenever I try and scrape a profile, it only seems to download the "profile" section, after which it gets stuck on "Type: Posts Scrape Attempt: 1/100" - it eventually continues and seems to download stuff, however when I look in the .sites folder, no files are there is an empty "free" folder in the posts section - have I setup something incorrectly, or has OF changed something about the cookies again?

**Comment by singularitysky** [comment]
I'm getting this as well.

**Comment by DIGITALCRIMINAL** [comment]
Scrape a paid profile instead and if it's not working, open another issue.
