### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by P0rr** [DIGITALCRIMINAL/OnlyFans#115]
C:\temp\OnlyFans-master>StartDatascraper.py
Traceback (most recent call last):
  File "C:\temp\OnlyFans-master\StartDatascraper.py", line 7, in <module>
    import modules.bbwchan as bbwchan
  File "C:\temp\OnlyFans-master\modules\bbwchan.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

all requirements is installed and done like FAQ tell me.. I get this error 

win 10 64bit python-3.8.1-amd64

Hope some one can tell me what i have done wrong..

**Comment by DIGITALCRIMINAL** [comment]
You've ran this command, right?
pip install -r requirements.txt

**Comment by P0rr** [comment]
yes and when i do that. I get the error i did post.

**Comment by DIGITALCRIMINAL** [comment]
You've only got one Python version right?
