### ISSUE TITLE
Session Lock

### ISSUE THREAD

**Issue by stran0s** [DIGITALCRIMINAL/OnlyFans#1153]
Cant scrape, the access gets denied AND YES IVE USED THE COOKIE TOOL AND I TRIED MANUALLY!

Its not working for me some please some serious help!

**Comment by NumNuts101** [comment]
Check to see if your User Agent changed! That is what caused the error for me!

**Comment by LunarPenguin** [comment]
> Check to see if your User Agent changed!

indeed, make sure the user-agent is updated and make sure you're running version 7.1 or it will not work at all.
