### ISSUE TITLE
JustForFans Support

### ISSUE THREAD

**Issue by mwight4** [DIGITALCRIMINAL/OnlyFans#1164]
Not so much an issue as a suggestion. I found on here the other day a script that works so so and all you provide it is your userid and a hash and it downloads (or attempts to lol) everything you are subscribed to. I have made some adjustments to the script so it works a little better but python not being my thing I'm struggling with it would someone here be willing to work with me on this and possibly get it into this script so we can have it all tied into one place

**Comment by DIGITALCRIMINAL** [comment]
When JFF has an API, then maybe.
