### ISSUE TITLE
Question for the people who's scrapers are successful 

### ISSUE THREAD

**Issue by giggawat** [DIGITALCRIMINAL/OnlyFans#1171]
For the people who’s scrapers are working, what info did you put in, was it more than the userid, sess, and user agent, and did you have to download something extra? I’m using the latest commit and it still doesn’t work.

**Comment by ProjektPremium** [comment]
{
  "auth": {
    "username": "default",
    "auth_id": "THIS",
    "sess": "THIS",
    "user_agent": "THIS",
    "auth_hash": "",
    "auth_uniq_": "",
    "x_bc": "THIS",
    "email": "THIS",
    "password": "THIS",
    "hashed": false,
    "support_2fa": false,
    "active": true
  }
}

The lines that say "THIS" are what I have set individual to myself, which I run remotely and it works fine.

**Comment by M-rcus** [comment]
Here's an example from my [cookie helper browser extension](https://github.com/M-rcus/OnlyFans-Cookie-Helper).

A few differences to note:
- A few fields are missing in comparison to the previous reply (such as `x_bc`). These usually get filled in by the ripping software if they're missing anyways.
- A lot of the fields are intentionally left blank. As I'm writing this comment, the only fields that I know are necessary are the following:
	- `app_token` - this one is the same for everyone: `33d57ade8c02dbc5a333db99ff9ae26a`
	- `sess` - unique to the current login "session"
	- `auth_id` - unique to the OnlyFans account
	- `user_agent` - The "user agent" of the browser used to log in. Directly related to `sess`. Log in usually breaks if there's a mismatch between user agent and sess.
	- `username` - by default set _by the browser extension_ as "u" plus the `auth_id`, but can be anything.
		- `username` will be overwritten with the name of the folder in `.profiles/OnlyFans`.
		- If you named your folder `.profiles/OnlyFans/my-personal-account`, then the username value will be replaced with `my-personal-account`

```json
{
  "auth": {
    "auth_hash": "",
    "auth_id": "123456789",
    "auth_uniq_": "",
    "sess": "<removed>",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "support_2fa": true,
    "username": "u123456789",
    "active": true,
    "email": "",
    "password": ""
  }
}
```

**Comment by olivechicago** [comment]
"username": "default",
    "auth_id": "########",
    "auth_hash": "",
    "auth_uniq_": "",
    "sess": "xx##x#xxx##x#xx##xxxx#xxxx",
    "x_bc": "",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/90.0.4430.93 Safari\/537.36",
    "email": "",
    "password": "",
    "support_2fa": false,
    "active": true
