### ISSUE TITLE
File "/home/ofd/src/OnlyFans/start_ofd.py", line 40, in <module>

### ISSUE THREAD

**Issue by ofdplz** [DIGITALCRIMINAL/OnlyFans#1173]
Getting the below error when trying to run:

Traceback (most recent call last):
  File "/home/ofd/src/OnlyFans/start_ofd.py", line 40, in <module>
    x = int(x)
ValueError: invalid literal for int() with base 10: ''

x
Site: 0 = onlyfans | x = Exit

**Comment by lostGamer54** [comment]
You have to enter 0 after "Site: 0 = onlyfans | x = Exit"
