### ISSUE TITLE
"Please refresh the page"

### ISSUE THREAD

**Issue by digitalleek** [DIGITALCRIMINAL/OnlyFans#1175]
When attempting to scrape and login, each auth attempt outputs the message "Please refresh the page." I assume this means to refresh the webpage with the OF account. Refreshing that page has still resulted in the same message from the auth attempts. I have also ensured that the info in the auth.json info is correct. Anyone else encountering this?

![Please_refresh](https://user-images.githubusercontent.com/83995577/117748250-ab9cc980-b1dd-11eb-8fd9-4550dcb9f02d.PNG)

**Comment by headphonia** [comment]
are you using the latest commit?
