### ISSUE TITLE
cant download contents from a Trial Profile

### ISSUE THREAD

**Issue by kariim4dz** [DIGITALCRIMINAL/OnlyFans#1177]
hi, with a Trial Subscription I have a full access for 1 month, but there is no possibility to download the contents from this profile. thank you

**Comment by M-rcus** [comment]
Any errors? Are you on the latest version?

I've tried with a 3-month trial subscription right now and it seems to work fine for me on the latest version (v7.1).

**Comment by ProjektPremium** [comment]
If you have a trial subscription and content is behind a pay wall, it will not download anything you have to pay for. Just in case you were unsure about that.

**Comment by kariim4dz** [comment]
> Any errors? Are you on the latest version?
 no errors at all
> I've tried with a 3-month trial subscription right now and it seems to work fine for me on the latest version (v7.1).
I tired with 2 profiles with 1 month trial and its not working, try this one https://onlyfans . com / bigbodybenz01

**Comment by M-rcus** [comment]
> If you have a trial subscription and content is behind a pay wall, it will not download anything you have to pay for. Just in case you were unsure about that.

I mean, that goes for _any_ subscription. Any pay-per-view content is not available unless you've purchased it.


> I tired with 2 profiles with 1 month trial and its not working, try this one [onlyfans](https://onlyfans) . com / bigbodybenz01

I tried with `bigbodybenz01`'s 30 day trial and it seems to work just fine for me.  
Does it give you any errors or is the profile just not listed. I assume you can scrape other profiles without issues?
