### ISSUE TITLE
There's nothing to scrape message

### ISSUE THREAD

**Issue by megadoll** [DIGITALCRIMINAL/OnlyFans#1178]
hi, when i log, 
• i press 0 so it takes me to onlyfans
• then i paste or type the username of the account i want to get to (tried with my own too)

it does everything in 0.6 seconds and says there's nothing in that profile

this my auth.json:

`{
  "auth": {
    "username": "default",
    "auth_id": "17529144",
    "sess": "0nmlkleb4n9tg3s6ue4pbtvmd8",
    "user_agent": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:88.0) Gecko\/20100101 Firefox\/88.0",
    "auth_hash": "",
    "auth_uniq_": "",
    "x_bc": "",
    "email": "",
    "password": "&i=X=e33w%bQUE3D;",
    "hashed": false,
    "support_2fa": true,
    "active": true
  }
}`

i've left it with everything so that if someone can check wether im making something wrong in detail it can be done easily

i tried with my mac address spoofed to a different vendor, with my ip address on a VPN, with my natural mac address and with my normal ip address, with python 3.9.4 and python 3.9.5, im on a macOS 10.13.6...

i'm...
sad...

:[

![Captura de pantalla 2021-05-11 a la(s) 07 46 28](https://user-images.githubusercontent.com/54786201/117810528-8637ac00-b22d-11eb-88f5-2e53c5a3f657.png)

**Comment by JohnnyTowns94** [comment]
Type one instead. Your profile is named "default".

**Comment by megadoll** [comment]
> Type 1 instead. Your profile is named "default".

well i have tried to edit the username taking my cookie from the onlyfans cookie helper mozilla extension and it saves it, i edited with xcode with visual code studio with text editor, with text mate and in all cases it reverts to a default non configured auth.json

what can be happening there, why should it revert it to default with no configuration?

i checked all permission to edit but it never works

:/

**Comment by megadoll** [comment]
> > > Type 1 instead. Your profile is named "default".
> > 
> > 
> > well i have tried to edit the username taking my cookie from the onlyfans cookie helper mozilla extension and it saves it, i edited with xcode with visual code studio with text editor, with text mate and in all cases it reverts to a default non configured auth.json
> > what can be happening there, why should it revert it to default with no configuration?
> > i checked all permission to edit but it never works
> > :/
> 
> The `username` is automatically changed to the name of the folder by the script and that's the name of the profile. If you want that to be different, rename the `default` folder to something else.
> 
> JohnnyTowns94 is right though. At the moment you have the default name.
> You have to either put the number 1 (which is the easiest), type `default` so it _selects the right profile by name_ or _rename the folder_ to `andrewiii`
> 
> The "Nothing to scrape" error comes from the fact that you're trying to type "andrewiii" and there's no profile matching that. You have `1 = default`
> 
> Also, if the `auth.json` you posted isn't changed to "censor" your real credentials, you basically just leaked your own credentials and people can scrape on behalf of your profile. **I highly suggest going to [OnlyFans -> Settings -> Account -> Login sessions](https://onlyfans.com/my/settings/account/sessions) and "Close all sessions", then logging out** to invalidate your leaked auth.json, then use the cookie helper to make a new one **for yourself only**.

ok i understand and it now works correctly, i can log into my account and check the options for all the profiles i'm susbcribed to, lik 12 or so but

i have a question... for example when i get in and instead of pressing 1 to go to my profile or 0 to see everything available to my account can i where it says username specify a username im not subscribed to?

do i need something else?

i tried but it again says nothing to scrape the same message and... well i will close this issue as resolved, but if you have any info on how to get a profile im not subscribed to then yeah please, tell me what im doing wrong and then i can close this thread


thank you

**Comment by DIGITALCRIMINAL** [comment]
Script only works on people you're subscribed to or have bought content off of

**Comment by megadoll** [comment]
> Script only works on people you're subscribed to or have bought content off of

great, awesome, thank you so much
