### ISSUE TITLE
did just get this error

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#118]
all did work fine one day back. Have not update / change any  thing.

C:\temp\OnlyFans-master>StartDatascraper.py
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
o
Traceback (most recent call last):
  File "C:\temp\OnlyFans-master\StartDatascraper.py", line 50, in <module>
    x = int(input())
ValueError: invalid literal for int() with base 10: 'o'

Hope some one can help me

**Comment by M-rcus** [comment]
Seems to me that you typed the letter `o` instead of the number `0` (zero).

Just `CTRL+C` to quit the process and start it again.

**Comment by DIGITALCRIMINAL** [comment]
^
