### ISSUE TITLE
KeyError: 'static_param'

### ISSUE THREAD

**Issue by hrnne** [DIGITALCRIMINAL/OnlyFans#1180]
![4F2_Z%I@HY@ H3 {1K{1DWF](https://user-images.githubusercontent.com/50048440/117975024-d3686a80-b360-11eb-9fd0-7f8d922f8916.png)
![HC~~KBGLEQS}BNR~4Q{8VLO](https://user-images.githubusercontent.com/50048440/117975617-6ef9db00-b361-11eb-99a7-142a8b804d35.png)

fill the x_bc can not solve this problem.There is no information about the hash and uniq on the net debugger.I am a bit stupid with code.I swear i follow the tutorial.plz help me!!!!

**Comment by DIGITALCRIMINAL** [comment]
Download latest commit

**Comment by hrnne** [comment]
![ZPH@I(ECA155N_WOYU$WASA](https://user-images.githubusercontent.com/50048440/118007382-acb92c80-b37e-11eb-93cc-5870dc420f5c.png)
![B%ZRTQG}PGQ891I){UWCU3F](https://user-images.githubusercontent.com/50048440/118007728-fa359980-b37e-11eb-95ec-f23ac2549a47.png)
it still does not work.

**Comment by DIGITALCRIMINAL** [comment]
That's on your end, I dunno how to fix that.
