### ISSUE TITLE
ModuleNotFoundError: No module name 'tqdm'

### ISSUE THREAD

**Issue by DaddysComin** [DIGITALCRIMINAL/OnlyFans#1182]
![Screenshot_9](https://user-images.githubusercontent.com/84118924/118084882-73d58380-b38f-11eb-9be2-e3aa0726e676.png)

**Comment by DaddysComin** [comment]
If I try 'pip install tqdm' it says I already have it. If I delete the tqdm folder and reinstall it I'm right back where I started with the error.

**Comment by LunarPenguin** [comment]
Strange, do you perhaps have multiple python installations and you have accidentally installed it for a different version? you could also run `pip list` or `pip freeze` to list the installed packages
