### ISSUE TITLE
Download not work - current GIT pull

### ISSUE THREAD

**Issue by jerryhard** [DIGITALCRIMINAL/OnlyFans#1183]
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Traceback (most recent call last):
  File "/ontap/Pic/OnlyFans/./start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/ontap/Pic/OnlyFans/datascraper/main_datascraper.py", line 104, in start_datascraper
    names = main_helper.process_names(
  File "/ontap/Pic/OnlyFans/helpers/main_helper.py", line 634, in process_names
    result = module.start_datascraper(
  File "/ontap/Pic/OnlyFans/modules/onlyfans.py", line 137, in start_datascraper
    if not json_settings["auto_scrape_apis"]:
KeyError: 'auto_scrape_apis'

**Comment by HtomSirveaux** [comment]
For now, I can get it to work by updating the line it references (modules/onlyfans.py, line 137) to replace auto_scrape_apis with auto_api_choice (I assume recently changed in the config).

**Comment by Onizuka89** [comment]
> For now, I can get it to work by updating the line it references (modules/onlyfans.py, line 137) to replace auto_scrape_apis with auto_api_choice (I assume recently changed in the config).

Most likely, as in config.json, the starsavn site have the "auto_scrape_api", but not the "auto_api_choice", and vice versa for onlyfans. And your solution was better than mine, I just set it to "if True:" which also works but not flexible as having it in a config file.  Tried to edit the config.json file to include "auto_scrape_api" in onlyfans' settings but it just get destroyed next time you fire up the software.

**Comment by LunarPenguin** [comment]
This behavior changed an hour or so before you opened this issue so i suggest you pull the most recent changes and try again. if it doesn't work it may be necessary to change the old `auto_` names in the config file to the new `auto_` names

**Comment by HtomSirveaux** [comment]
> This behavior changed an hour or so before you opened this issue so i suggest you pull the most recent changes and try again. if it doesn't work it may be necessary to change the old `auto_` names in the config file to the new `auto_` names

Not sure if you were referring to me or OP, but when I run mine I have it set to do a git pull origin master each time.  On current, onlyfans.py looks for auto_scrape_apis in config.json, but the script also deleted auto_scrape_apis if it is in there.  Only changing onlyfans.py to look instead for auto_api_choice lets it run.  

The old config I had before today's updates had "auto_choice": "a"
The new config has auto_media_choice, but setting to "a" does not download.  Setting to "0" does.

**Comment by Onizuka89** [comment]
seems like the json_setting["auto_scrape_api"]  should have been json_setting["auto_model_choice"] on that line judging by this code snippet from most recent commit:

```
        def update_site_settings(options) -> dict:
            new_options = copy.copy(options)
            for key, value in options.items():
                if "auto_scrape_names" == key:
                    new_options["auto_model_choice"] = value
```

**Comment by LunarPenguin** [comment]
> Not sure if you were referring to me or OP

to be fair i did not see you were two distinct users so my bad, 

It seems to be an oversight from the commit @DIGITALCRIMINAL made removing backwards compatibility and reformatting the `auto_` fields. it seems that DC forgot te refactor that piece of code and is something DC needs to fix.

**Comment by DIGITALCRIMINAL** [comment]
Sorry, latest commit should fix it
