### ISSUE TITLE
Scrape, but doesn't download

### ISSUE THREAD

**Issue by dcex** [DIGITALCRIMINAL/OnlyFans#1184]
After updating to the last commit I noticed that the program is not downloading.

The program scrapes and seems to find all the content, but nothing is downloaded.  

I used the program with 20~ish models and had 0 things downloaded, and I know that some of them have new content. For instance, a model has 229 videos, the program scrapes 229 videos, but the download folder has only 202 videos and exits without downloading the 27 that I'm missing.

**Comment by dcex** [comment]
Tested it with a new subscription: the only thing that the program was able to download was the profile picture.

**Comment by newadventure079** [comment]
I'm seeing the same thing.  I just get the 2 avatar pics and that's it.

**Comment by rs516a1** [comment]
In a recent [commit](https://github.com/DIGITALCRIMINAL/OnlyFans/commit/35640c73a540178801e4b86221b0424faf941d8b), the options for auto_media_choice changed in the config file. If you want to download everything, set auto_media_choice to '0' instead of 'a'.

**Comment by dcex** [comment]
I feel so dumb, but yep, that was it!

I knew about the int change but never connected the dots (and I looked at the config.json for a while lol)
