### ISSUE TITLE
Model not getting scrape

### ISSUE THREAD

**Issue by 666diabolus** [DIGITALCRIMINAL/OnlyFans#1186]
After I got the message "Session Lock" from the last version, I downloaded your latest code, got into the account but it stopped scraping after getting Metadata and Profile 

`Scrape Processing
Name: primetimepenny
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
a
Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Type: Archived
No Archived Found.
Type: Messages
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Scrape Completed

Archive Completed in 0.63 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |`

**Comment by mwald84** [comment]
I have a similar problem but in my case it also shows the "download processing" messages but it's not downloading anything like there's nothing new to download.

**Comment by DIGITALCRIMINAL** [comment]
Look at the choices.
![image](https://user-images.githubusercontent.com/21285176/118231664-52f05980-b487-11eb-8ee4-54e0c8801630.png)

**Comment by mwald84** [comment]
In my case I'm using the auto choice in the config file. Haven't changed that option from the time it was working to now.

**Comment by DIGITALCRIMINAL** [comment]
> In my case I'm using the auto choice in the config file. So i didn't notice the option has changed. Thanks!

Oh yeah, my bad. I should have reset the choice for everyone when they downloaded the new commit.
