### ISSUE TITLE
Script authenticating but no longer downloading after OF outage this morning

### ISSUE THREAD

**Issue by mediaburnwayne** [DIGITALCRIMINAL/OnlyFans#1189]
Tried doing individual scrapes for a few models and have set threads to 1. These models have content from yesterday that is not being scraped and downloaded.

**Comment by mediaburnwayne** [comment]
Here is my config

{
  "info": {
    "version": 7.1
  },
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": 1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "proxies": [],
    "cert": "",
    "random_string": "f0b53965b42211eb9498000acd3af47c"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "1",
        "auto_model_choice": false,
        "auto_media_choice": "a",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": false
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{date}-{media_id}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": "",
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{date}-{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    }
  }
}

**Comment by valdearg** [comment]
I seem to be getting the same issue today and yesterday, it will go through the models and the renaming of files, then scraping etc.

It then gets to the Download Processing parts and just flies through them all, not actually downloading anything.

It doesn't give any specific errors that I can see, very strange.

Going to subscribe to this issue to see if anyone else is having the issue also.

**Comment by DIGITALCRIMINAL** [comment]
Try using the latest commit

**Comment by valdearg** [comment]
No change for me with the latest commit.

**Comment by mediaburnwayne** [comment]
Same

Still not pulling from known updated models

**Comment by DIGITALCRIMINAL** [comment]
Changed "auto_media_choice": "a"
to
"auto_media_choice": "0",

**Comment by mediaburnwayne** [comment]
That did it, thanks

**Comment by ambersydney333** [comment]
hey im getting auth error i was inactive for a while so idk but i have latest version and still i am getting the auth issue

**Comment by mwight4** [comment]
> Changed "auto_media_choice": "a"
> to
> "auto_media_choice": "0",

I have tried pulling down the latest and doing this and it seems to still be acting like the original poster is discussing I can share my config if that helps

**Comment by DIGITALCRIMINAL** [comment]
Let's see

**Comment by CountParadox** [comment]
Im having this also, its pulled the avatar and header images, but no messages / posts
`{
  "info": {
    "version": 7.1
  },
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "proxies": [],
    "cert": "",
    "random_string": "12345"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "0",
        "auto_model_choice": true,
        "auto_media_choice": "0",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          "\/mnt\/truenas\/OnlyFans\/"
        ],
        "file_directory_format": "{site_name}\/{username}\/{api_type}\/{value}\/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\/{username}\/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": "",
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\/{username}\/{api_type}\/{value}\/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\/{username}\/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    }
  }
}
`

**Comment by euglv** [comment]
For me browser generates `sign` header this way: `14:c737be44905714c438c0c051e29a858174861e85:9bf:609ebeb2`
But in dynamic config file https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json
`format` is `"13:{}:{:x}:609e7984"`

**Comment by bobsage123** [comment]
On v7.2. I noticed I was getting zero things downloading as well so I noticed above to change "auto_media_choice" from a to 0.

After I did that, I now get this.

`Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "I:\OnlyFans-7.2\start_ofd.py", line 43, in <module>
    api = main_datascraper.start_datascraper(
  File "I:\OnlyFans-7.2\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = main_helper.process_names(
  File "I:\OnlyFans-7.2\helpers\main_helper.py", line 631, in process_names
    result = module.start_datascraper(
  File "I:\OnlyFans-7.2\modules\onlyfans.py", line 144, in start_datascraper
    results = prepare_scraper(
  File "I:\OnlyFans-7.2\modules\onlyfans.py", line 683, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "I:\OnlyFans-7.2\modules\onlyfans.py", line 947, in media_scraper
    for media in media_api["media"]:
KeyError: 'media'`

**Comment by CountParadox** [comment]
> On v7.2. I noticed I was getting zero things downloading as well so I noticed above to change "auto_media_choice" from a to 0.
> 
> After I did that, I now get this.

Mine is already set t 0 and I dont get any errors... hmm

**Comment by bobsage123** [comment]
> > On v7.2. I noticed I was getting zero things downloading as well so I noticed above to change "auto_media_choice" from a to 0.
> > After I did that, I now get this.
> 
> Mine is already set t 0 and I dont get any errors... hmm

How did you see this post lol I deleted it. Turned out to be an auth issue and works now.

**Comment by Eviepayne** [comment]
I just pulled to latest today and this happens. doesn't seem to matter what is put it happens. If I unset it, it works as normal.
