### ISSUE TITLE
Authentication loop

### ISSUE THREAD

**Issue by Oznerol88** [DIGITALCRIMINAL/OnlyFans#119]
Hi,

I ran the program a week ago and it worked but now it keeps printing Auth (V1) Attempt 1/10 up to 10/10.

**Comment by tenaka18** [comment]
i had the same problem, but after following the faq and adding sess: i have resolved my auth issues.

**Comment by Oznerol88** [comment]
i have the same number on the sess as on the app-token. I re-downloaded the program and I did it all over again and it still doesn't work.

**Comment by DIGITALCRIMINAL** [comment]
I had the same thing as well. I had to turn 2FA off. I don't know if you guys have 2FA on.

**Comment by tenaka18** [comment]
i never had 2FA on.

i tried to run the scraper one minute ago and the autentication has worked.

**Comment by pcjamesy** [comment]
Oznerol88 have you checked if you config file is still valid for your account. Today i had to update me auth_hash and sess codes.

**Comment by inadquatecoding** [comment]
I am having the same issue running Python 3.8.1, with onlyfans, Confirmed my information is under the "onlyfans" section of the config file, ass cookie values are current. Have never used this script before.

**Comment by DIGITALCRIMINAL** [comment]
@inadquatecoding user-agent?

**Comment by inadquatecoding** [comment]
> @inadquatecoding user-agent?

Chrome or Firefox, session data taken from chrome.

**Comment by DIGITALCRIMINAL** [comment]
@inadquatecoding did you add the user agent into the config

**Comment by inadquatecoding** [comment]
No I didn't, will try

On Jan. 12, 2020 10:57 p.m., CRIMINAL <notifications@github.com> wrote:

@inadquatecoding<https://github.com/inadquatecoding> did you add the user agent into the config

**Comment by inadquatecoding** [comment]
@DIGITALCRIMINAL, how should I specify my user agent? 

Google Chrome, or just Chrome?

**Comment by DIGITALCRIMINAL** [comment]
https://www.whatismybrowser.com/detect/what-is-my-user-agent

**Comment by inadquatecoding** [comment]
Working now, thank you!
