### ISSUE TITLE
404 error using VPN

### ISSUE THREAD

**Issue by j-ktz** [DIGITALCRIMINAL/OnlyFans#1190]
Seems like this is new. It works fine if I turn off my VPN. I can't even load the website in the browser on my VPN. Did OF ban using VPNs?

**Comment by DIGITALCRIMINAL** [comment]
Which VPN provider do you use?

**Comment by j-ktz** [comment]
ExpressVPN. With VPN on get 404 in a browser and the 404'ed error using the latest commit but with VPN off, both work. Never had this issue before with the browser. Maybe they changed something?

**Comment by DIGITALCRIMINAL** [comment]
Nordvpn works

**Comment by j-ktz** [comment]
Yeah so weird. ExpressVPN always worked and after this latest OF update it doesn't.
