### ISSUE TITLE
"download_directories" format on config update

### ISSUE THREAD

**Issue by WellSomething** [DIGITALCRIMINAL/OnlyFans#1191]
On my original config I had it as:
`Z:/OF/OnlyFans`

I downloaded the current master, and did the automatic config update and it changed that value to:

`Z:\/OF\/OnlyFans`

Just thought I'd point it out, since the Readme says to use forward slashes only.

**Comment by DIGITALCRIMINAL** [comment]
Double backslash if you don't want that format.

C:\\Directory\\Folder

**Comment by DIGITALCRIMINAL** [comment]
Yes
