### ISSUE TITLE
Site: 0 = onlyfans |

### ISSUE THREAD

**Issue by spydafx** [DIGITALCRIMINAL/OnlyFans#1194]
i copied using the browser extention u provided the auth and pasted the whole thing into the auth file, and added in email and password my acc's email and password (the of account is linked to my google so i put the google email + a password which i changed afterwards for the onlyfans account) and saved and run the script and it just says "Site: 0 = onlyfans |" and stuck like this.. help?

**Comment by m4exxx** [comment]
You have to type 0 and press enter

**Comment by luciferhasfallen** [comment]
Having the same issue

```
Site: 0 = onlyfans | x = Exit
0
Proxy Not Set: None

Unable to create session
```
