### ISSUE TITLE
Downloading wrong onlyfans?

### ISSUE THREAD

**Issue by g0dzcsgo** [DIGITALCRIMINAL/OnlyFans#1199]
Whenever i do default login, then pick a onlyfans user by number click 0 for all it starts downloading other random onlyfans profiles im subscribed to and not the 1 i wanted?

Edit: I installed newest version of the scraper and got this error when trying to run it:

Traceback (most recent call last):
  File "/root/of/start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "/root/of/tests/main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "/root/of/helpers/main_helper.py", line 8, in <module>
    from sqlalchemy.orm import declarative_base
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/__init__.py)

**Comment by neuri4848** [comment]
install the new requirements

**Comment by DIGITALCRIMINAL** [comment]
Paid subscriptions, false

**Comment by TheMissingPort** [comment]
Im getting the same error. Silicon Mac

**Comment by DIGITALCRIMINAL** [comment]
> Im getting the same error. Silicon Mac

Did you set paid subscriptions to false

**Comment by TheMissingPort** [comment]
> > Im getting the same error. Silicon Mac
> 
> Did you set paid subscriptions to false

In which file? I haven't gotten far enough for it to give me the .settings

**Comment by DIGITALCRIMINAL** [comment]
Install latest requirements

**Comment by g0dzcsgo** [comment]
Installed latest version, still getting the issue of it downloading other people instead of the one i picked.

**Comment by TheMissingPort** [comment]
> Install latest requirements

All are satisfied, still same error 

ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/__init__.py)
