### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'select'

### ISSUE THREAD

**Issue by markt38** [DIGITALCRIMINAL/OnlyFans#12]
Traceback (most recent call last):
  File "OnlyFans.py", line 142, in <module>
    user_id = link_check(input_link)
  File "OnlyFans.py", line 38, in link_check
    temp_user_id = user_list.select('a[data-user]')
AttributeError: 'NoneType' object has no attribute 'select'

**Comment by avekifes** [comment]
Same issue here.

**Comment by DIGITALCRIMINAL** [comment]
Fixed

**Comment by bpo5r5** [comment]
Hey @DIGITALCRIMINAL, when trying the latest commit I'm getting the following error:

```
$ python OnlyFans.py
Input a username or profile link
https://onlyfans.com/yung_angel66
Traceback (most recent call last):
  File "OnlyFans.py", line 145, in <module>
    user_id = link_check()
  File "OnlyFans.py", line 43, in link_check
    y = y[0]["user"]
KeyError: 0
```

**Comment by DIGITALCRIMINAL** [comment]
> Hey @DIGITALCRIMINAL, when trying the latest commit I'm getting the following error:
> 
> ```
> $ python OnlyFans.py
> Input a username or profile link
> https://onlyfans.com/yung_angel66
> Traceback (most recent call last):
>   File "OnlyFans.py", line 145, in <module>
>     user_id = link_check()
>   File "OnlyFans.py", line 43, in link_check
>     y = y[0]["user"]
> KeyError: 0
> ```

That's because you don't have the correct application token. I have updated the script to handle that error ;D
