### ISSUE TITLE
VIdeos sent via message not scraped

### ISSUE THREAD

**Issue by fungastorba** [DIGITALCRIMINAL/OnlyFans#120]
As the title says. I can confirm that scraping images from chat works.

**Comment by DIGITALCRIMINAL** [comment]
Which person are you trying to scrape?

**Comment by fungastorba** [comment]
0ct0kur0 but with an "o"

**Comment by fungastorba** [comment]
mhm

**Comment by DIGITALCRIMINAL** [comment]
Hmm, is it all videos in messages or is it just one?

**Comment by fungastorba** [comment]
Just one

**Comment by fungastorba** [comment]
One out of one ;)

**Comment by DIGITALCRIMINAL** [comment]
Does the video appear in the message metadata?

**Comment by fungastorba** [comment]
Close this shit. I tried it in a new directory + a new file naming rule and it worked this time. 
Old file naming was {date}/{text}-{file_name}.{ext} but because of the backslash it didn't write the date, only text + file_name. Now I used this {date} {text}-{file_name}.{ext} naming convention + a fresh directory and it got scraped. Sorry for wasting your time.

**Comment by fungastorba** [comment]
And yes, it did appear in the old directory metadata. I guess somehow the option to not scrape videos that are already scraped + the bad naming fucked things up.

**Comment by DIGITALCRIMINAL** [comment]
> Close this shit. I tried it in a new directory + a new file naming rule and it worked this time.
> Old file naming was {date}/{text}-{file_name}.{ext} but because of the backslash it didn't write the date, only text + file_name. Now I used this {date} {text}-{file_name}.{ext} naming convention + a fresh directory and it got scraped. Sorry for wasting your time.

LMAO. It's all good bruh. Yeah if it's the same name it won't be downloaded again once the file has been created.
