### ISSUE TITLE
On latest version

### ISSUE THREAD

**Issue by g0dzcsgo** [DIGITALCRIMINAL/OnlyFans#1205]
Basically when i try to download a specific onlyfans user by typing in the ID of the profile i wanna download instead of just scraping and downloading all of that content it goes thru all my other subscriptions and downloads those instead? Happened on my previous version too, so that's why i updated installed the new requirements but still the same issue.

**Comment by DIGITALCRIMINAL** [comment]
SRT PAOD SUBSCRIPTIONS TO FALSE

**Comment by g0dzcsgo** [comment]
> SRT PAOD SUBSCRIPTIONS TO FALSE

Set paid subscriptions to false where? I've looked in config for that THERE IS NOTHING. Maybe instead of saying 5 words explain where it's located???????????
