### ISSUE TITLE
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' 

### ISSUE THREAD

**Issue by TheMissingPort** [DIGITALCRIMINAL/OnlyFans#1211]
Even with latest update, I still get error. Happens after python3 start_ofd.py

ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/__init__.py)

I've already reinstalled requirements as well, and updated SQLalchemy

Using Silicon Mac 

Edit: apparently its something specific to my Mac mini, not sure. I just tried running it on my MacBook Air (also silicon) and it works fine

Any suggestions? Thanks

**Comment by DIGITALCRIMINAL** [comment]
Check the version of sqlalchemy

**Comment by TheMissingPort** [comment]
> Check the version of sqlalchemy

I have checked the version, uninstalled/installed multiple times, even to the latest version from the actual SQLalchemy project with no luck.

**Comment by DIGITALCRIMINAL** [comment]
> > Check the version of sqlalchemy
> 
> I have checked the version, uninstalled/installed multiple times, even to the latest version from the actual SQLalchemy project with no luck. 

What is the version

**Comment by TheMissingPort** [comment]
> > > Check the version of sqlalchemy
> > 
> > 
> > I have checked the version, uninstalled/installed multiple times, even to the latest version from the actual SQLalchemy project with no luck.
> 
> What is the version

SQLAlchemy                         1.4.16.dev0

**Comment by TheMissingPort** [comment]
> > > Check the version of sqlalchemy
> > 
> > 
> > I have checked the version, uninstalled/installed multiple times, even to the latest version from the actual SQLalchemy project with no luck.
> 
> What is the version

**Comment by TheMissingPort** [comment]
> > > Check the version of sqlalchemy
> > 
> > 
> > I have checked the version, uninstalled/installed multiple times, even to the latest version from the actual SQLalchemy project with no luck.
> 
> What is the version

Nevermind, I got it working, had to python3.9 setup.py install the latest SQLalchemy, then it worked

**Comment by DIGITALCRIMINAL** [comment]
The script is supposed to be using 1.4.15 btw

**Comment by zavnish** [comment]
This was not working with version 1.2.7 . I have uninstalled it and updated to 1.4 and then declarative_base is working.

**Comment by Zarar-Azwar** [comment]
USE **from sqlalchemy.ext.declarative import declarative_base**

**Comment by Invidia19** [comment]
> USE **from sqlalchemy.ext.declarative import declarative_base**

use this if you don't want to disturb flask_sqlalchemy functions that still uses older version ( for me it was 1.3.8 )

**Comment by lafftar** [comment]
> USE **from sqlalchemy.ext.declarative import declarative_base**

Worked for me with FastAPI.

My structure is:
```
db/
   base.py
   tables.py
```

I also had to import `base.metadata` from `tables.py` instead of `base.py`. `alembic` requires all the tables to be loaded before it can do its work.

**Comment by Dhamu785** [comment]
> > USE **from sqlalchemy.ext.declarative import declarative_base**
> 
> Worked for me with FastAPI.
> 
> My structure is:
> 
> ```
> db/
>    base.py
>    tables.py
> ```
> 
> I also had to import `base.metadata` from `tables.py` instead of `base.py`. `alembic` requires all the tables to be loaded before it can do its work.

## Thank you. It worked for me
