### ISSUE TITLE
How do i set paid subscriptions to false?

### ISSUE THREAD

**Issue by g0dzcsgo** [DIGITALCRIMINAL/OnlyFans#1212]
I don't know where it's located but people told me to set it to false so random onlyfans profiles doesnt get downloaded of, of my account...?

Like where is it located, cause i've scoured thru config.json and there's nothing there. I even wrote "Paid Subscriptions" search on this github. Nothing.

**Comment by DIGITALCRIMINAL** [comment]
Paid content to false in config.

**Comment by g0dzcsgo** [comment]
It doesnt say that anywhere in the config dear sir @DIGITALCRIMINAL

**Comment by DIGITALCRIMINAL** [comment]
Just copy and paste your config here
