### ISSUE TITLE
Strange Finding

### ISSUE THREAD

**Issue by ProjektPremium** [DIGITALCRIMINAL/OnlyFans#1213]
Never seen this before, could you please explain it @DIGITALCRIMINAL ?

Download Failed: https://of2transcoder.s3-accelerate.amazonaws.com/files/2020_02_13/5e/5e4/5e456ef0f3bb4a502fc49.mp4

**Comment by DIGITALCRIMINAL** [comment]
OF migrated their videos to a new cdn, or something like that. Some links aren't updated. If you can find the post in the metadata, the post's media won't render on the website.
