### ISSUE TITLE
ModuleNotFoundError starting start_ofd.py

### ISSUE THREAD

**Issue by Splitfox** [DIGITALCRIMINAL/OnlyFans#1214]
I downloaded the latest release, installed all requirements with `pip install -r requirements.txt` 
But if i want to start the script i'm getting these error:

![image](https://user-images.githubusercontent.com/12877029/118511208-f82e5a80-b731-11eb-92b5-6d7e0d04b5d6.png)

This is how my folder looks like, i can't see a settings folder even if i can see hidden folders

![image](https://user-images.githubusercontent.com/12877029/118511414-29a72600-b732-11eb-844b-f2355b9ff478.png)

**Comment by TheMissingPort** [comment]
Have you tried pip3 install dateutil? or sometimes you have to go to the actual project on GitHub, download the latest code, and python start.py install

**Comment by Splitfox** [comment]
reinstalled all requirements correctly and now it works just fine. Thanks!
