### ISSUE TITLE
scraping isn't working

### ISSUE THREAD

**Issue by rayturk1** [DIGITALCRIMINAL/OnlyFans#1226]
Auth (V1) Attempt 1/10
Please refresh the page
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.05 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |
every time i do it this shows up ....

**Comment by DIGITALCRIMINAL** [comment]
I will ban you if you open another duplicate issue.

**Comment by rayturk1** [comment]
> I will ban you if you open another duplicate issue.

is it open already?!

**Comment by DIGITALCRIMINAL** [comment]
Yes, and I'm aware of the issue

**Comment by rayturk1** [comment]
> Yes, and I'm aware of the issue

ok i'm sorry didn't know that
