### ISSUE TITLE
Please refresh the page v7.2 on ubuntu 20.04

### ISSUE THREAD

**Issue by atlas-mugged** [DIGITALCRIMINAL/OnlyFans#1229]
Hey Guys,

I have done a git pull and updated the repo, reinstalled requirements, verified "sess" in my auth.json. Strangely it was working just fine earlier today and then just stopped and gave this message when running to application:

"
Auth (V1) Attempt 1/10
Please refresh the page
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Now exiting.
"

Just wondering if anyone else is getting this, or if this another 'OnlyFans' fighting back situation? lol

**Comment by lEtranger1942** [comment]
Check existing issues before posting a new one https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1202

**Comment by atlas-mugged** [comment]
Apologies, my mistake (serious newbie lol).
