### ISSUE TITLE
Stalls after startup

### ISSUE THREAD

**Issue by AJdope** [DIGITALCRIMINAL/OnlyFans#1230]
Tried running Natively through Python 3.9, Windows 10 and through Docker on separate Windows 10 machine
Noticed I'm unable to get an auth hash from Cookies, even with assistance from the browser extentsion across 3 different OS's and browsers (Chrome and Firefox on WIndows 10, 7, and Linux
Account is linked to Twitter, not sure if that makes a difference

Script starts up and then sits on Site: 0 = onlyfans |
File "C:\Users\proxi\Downloads\OnlyFans-master\start_ofd.py", line 40, in <module>     x = int(x) is returned if any input is typedf

**Comment by DIGITALCRIMINAL** [comment]
Use a different script lul
