### ISSUE TITLE
Scrape messages from models you are no longer subscribed to

### ISSUE THREAD

**Issue by dunngitter** [DIGITALCRIMINAL/OnlyFans#1234]
Just noticed that it doesn't seem to be doing this currently. Is this possible? Many models send content over messages even when you are no longer subscribed, mostly for purchase.

**Comment by artyom2035** [comment]
The scrape paid content setting will download the messages that you purchase from creators you no longer subscribe to. Well, it does for me.

 Unfortunately, you can't scrape paid content on a per creator basis - it's either just on (automatically scrapes all paid) or off

**Comment by ProjektPremium** [comment]
Hold shift and right click and you will be able to save the content. Surely you're not receiving that much content you'd need the scraper to do that.

**Comment by dunngitter** [comment]
Right, but what about free content from creators you no longer subscribe to?

**Comment by E0911CD45B19686** [comment]
This issue already exists https://github.com/DIGITALCRIMINAL/OnlyFans/issues/726

**Comment by dunngitter** [comment]
Ahh, nice! Closing this out, then.
