### ISSUE TITLE
OnlyFans Media Version/Type Selection

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINAL/OnlyFans#1235]
Apologies if this is addressed elsewhere but is there a way to select the "version" of media being downloaded? Specifically video.

On the site, one generally has the option of 720p or "Original" and sometimes other compressed versions. I'd like to make sure I'm selecting "original" every time (some other users with space constraints might also like the ability to choose compressed versions).

**Comment by DIGITALCRIMINAL** [comment]
Readme
