### ISSUE TITLE
Very confused and feeling dumb, but where is the .profiles/default/auth.json file ?

### ISSUE THREAD

**Issue by AeroSouls** [DIGITALCRIMINAL/OnlyFans#1238]
I have followed the steps for run local twice now and I never get a file .profiles/default/auth.json

Where can I find this file?

I have show hidden files on
On windows 10 pro
latest python version

**Comment by lEtranger1942** [comment]
Start the script first python startofd.py after this the files will appear

**Comment by AeroSouls** [comment]
> Start the script first python startofd.py after this the files will appear

I've done that many times they never show up :(

this is what my output is after running install req.txtx and the starting the file
![image](https://user-images.githubusercontent.com/49828953/119238910-80867400-bb13-11eb-94a1-f713c320390a.png)

**Comment by lEtranger1942** [comment]
It says in your logs execute script with putin 3.9 from what I gather you are on python 3.8.

Install python 3.9 and try again

**Comment by DIGITALCRIMINAL** [comment]
Gatekept
