### ISSUE TITLE
Content Not Downloading

### ISSUE THREAD

**Issue by goodboi69boi** [DIGITALCRIMINAL/OnlyFans#1239]
I just subscribed to some new users and using version 7.2 of the ripper, it only downloads the `metadata` and `profile` folder.
I tried using my actual IP and my VPN (PIA).

**Comment by root3d1** [comment]
I am getting the same issue on 7.2!

**Comment by jeff-geoff** [comment]
Same. It even creates all the directories (e.g. if there are old subscriptions that are no longer subscribed but have paid messages, it will create the Paid folder in those accounts and then not download anything to it).

No VPN, no changes to the stock config except adding the date to the filenames...

**Comment by lEtranger1942** [comment]
Git clone the latest commit. Works for me on arch

**Comment by TheDudeAbides42** [comment]
I am having the exact same issue (downloads metadata and profiles, but is unable to scrape other media), I attempted to rollback to an earlier commit on master but to no avail. I re-cloned the repo, attempted to scrape with no existing media, same problem. When I attempted with no existing media downloaded for a given creator, it didn't even show them as having any images or videos, let alone download them. I'm thinking it might not be an issue with actually downloading the content, but rather that the program is unable to find any content to download.

**Comment by jeff-geoff** [comment]
Removing the {text} part of the filename solved the problem for me. Maybe it can be added back from the metadata at some point in the future without re-scrape.

**Comment by gazebo-guy** [comment]
Could you give a bit more detail on what you mean by "removing the {text} part of the filename"? In config.json, I'm not seeing {text} but I am seeing {ext}, though I imagine that's needed for the file extension. Is there something else that I'm missing?

**Comment by jeff-geoff** [comment]
I had added both {text} and {date} to the components of my filename, and that caused basically nothing to work. I removed {text} and it made the directories but didn't fill them. Leaving the filename in its default state worked just fine. So it seems to be something to do with file naming? That's all the info I have, and I don't have any specific errors or logs to troubleshoot from...

**Comment by gazebo-guy** [comment]
Well, I pulled down the 7.2 release code instead of cloning the repo, I left the config file completely unmodified (normally, I only set a few defaults [such as `auto_site_choice`, `auto_profile_choice`, `auto_media_choice`] and turn off the infinite loop) and now it is able to scrape content. I tried just having auto_media_choice set, and it still failed to scrape. So for now, I'll leave my config untouched.

**Comment by gazebo-guy** [comment]
I just realized what my issue was. `auto_media_choice` used to use letters. Now it uses numbers. That's why it was failing to scrape. The mystery has been solved, at least for me.

**Comment by jeff-geoff** [comment]
My first config had the same modifications as yours... I forgot about that. Plus I used {date}_{text}_{filename}.{ext}

**Comment by jeff-geoff** [comment]
Well, I don't have any way to check this now, but it's possible that this was related to my config file being old. If you told me I was using letters instead of numbers I wouldn't be surprised... but I have no way to check now. It's likely to probable that that is the case.
