### ISSUE TITLE
Is adding sess token required for authentication now?

### ISSUE THREAD

**Issue by GoldsteinGold** [DIGITALCRIMINAL/OnlyFans#124]
Before, I never added in sess token unless I wanted to guarantee I was authed into the right account. It was nice being authed into other accounts sometimes when the sess token wasn't in the config. Free content.

Now I can't get the scraper to run unless I add in my sess token, which also makes it so I am always authed into my account instead of sometimes getting lucky and being able to scrape other accounts. Without the sess token I get endless auth loops. Anyone else experiencing this?

**Comment by DIGITALCRIMINAL** [comment]
Yeah they fixed their bug 3-4 days ago. GGs c:
