### ISSUE TITLE
Heard it was fixed, but still getting the same problem

### ISSUE THREAD

**Issue by iansquenet** [DIGITALCRIMINAL/OnlyFans#1240]
```
Traceback (most recent call last):
  File "D:\OnlyFans\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "D:\OnlyFans\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "D:\OnlyFans\helpers\main_helper.py", line 8, in <module>
    from sqlalchemy.orm import declarative_base
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (C:\Python39\lib\site-packages\sqlalchemy\orm\__init__.py)
```

**Comment by expl0sivesku11** [comment]
yes i have same but different issue. dont know what is wrong, dont know how to fix.

Traceback (most recent call last):
  File "C:\Users\paulf\OneDrive\Documents\GitHub\OnlyFans\start_ofd.py", line 43, in <module>
    api = main_datascraper.start_datascraper(
  File "C:\Users\paulf\OneDrive\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 69, in start_datascraper
    auths = choose_option(
  File "C:\Users\paulf\OneDrive\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 584, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

**Comment by DIGITALCRIMINAL** [comment]
> yes i have same but different issue. dont know what is wrong, dont know how to fix.
> 
> Traceback (most recent call last):
> File "C:\Users\paulf\OneDrive\Documents\GitHub\OnlyFans\start_ofd.py", line 43, in
> api = main_datascraper.start_datascraper(
> File "C:\Users\paulf\OneDrive\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 69, in start_datascraper
> auths = choose_option(
> File "C:\Users\paulf\OneDrive\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 584, in choose_option
> if value.isdigit():
> AttributeError: 'int' object has no attribute 'isdigit'

Gatekept.



> ```
> Traceback (most recent call last):
>   File "D:\OnlyFans\start_ofd.py", line 10, in <module>
>     main_test.check_config()
>   File "D:\OnlyFans\tests\main_test.py", line 23, in check_config
>     import helpers.main_helper as main_helper
>   File "D:\OnlyFans\helpers\main_helper.py", line 8, in <module>
>     from sqlalchemy.orm import declarative_base
> ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (C:\Python39\lib\site-packages\sqlalchemy\orm\__init__.py)
> ```

Pip install requirements again.

**Comment by iansquenet** [comment]
Still having problems.
