### ISSUE TITLE
Where to find the sess token

### ISSUE THREAD

**Issue by bikinikill9** [DIGITALCRIMINAL/OnlyFans#125]
Hi, I'm struggling a bit to find the sess token, I found this but I'm not sure it's that, since with this sess token the script doesn't seem to bable to autenthicate 

![image](https://user-images.githubusercontent.com/60100603/72728827-86222180-3b8e-11ea-8967-6c05ccbb70bf.png)

Also is this the right place to ask this question? I've used GitHub but never asked a question before

**Comment by DIGITALCRIMINAL** [comment]
Are you using google chrome?

**Comment by bikinikill9** [comment]
> Are you using google chrome?

Yes!

**Comment by DIGITALCRIMINAL** [comment]
Did you search "?app" in the network tab to get the correct sess?

**Comment by bikinikill9** [comment]
> Did you search "?app" in the network tab to get the correct sess?

Yeah, I was able to fill all the other fields (app-token, auth_id and auth_hash), but I didn't see anything called "sess" or "sess-token"...

**Comment by DIGITALCRIMINAL** [comment]
Request Header
![image](https://user-images.githubusercontent.com/21285176/72855943-0f317980-3cb1-11ea-9d60-10d324018e90.png)

**Comment by bikinikill9** [comment]
> Request Header, it's inside cookies
> ![image](https://user-images.githubusercontent.com/21285176/72855943-0f317980-3cb1-11ea-9d60-10d324018e90.png)

Oh, I completely missed that, thanks!

**Comment by DIGITALCRIMINAL** [comment]
I believe they changed it, that's why. I also updated the app.
