### ISSUE TITLE
Only a handful of subs are listed

### ISSUE THREAD

**Issue by monkjew** [DIGITALCRIMINAL/OnlyFans#1251]
Once it logs me in, it only lists a few of my subs. Anything I need to do to populate the rest of them? I'm running the latest version

**Comment by ProjektPremium** [comment]
I'm having the same problem. Try setting your threads to 1 and not -1

Even though mine is set to "1" it still takes forever to even auth and then even list the names.

**Comment by Eviepayne** [comment]
Onlyfans is being really slow in general. It's all the API requests as well that are taking the longest.
Give it a bit.
