### ISSUE TITLE
Site: 0 = onlyfans

### ISSUE THREAD

**Issue by skeliceagesjh-dev** [DIGITALCRIMINAL/OnlyFans#1252]
I have edited auth.json and this is the error i saw on my program, anyway to fix it?
![Capture](https://user-images.githubusercontent.com/84840895/119635107-efcad380-be45-11eb-85fa-d03fb0c05792.PNG)

**Comment by LunarPenguin** [comment]
it seems to have failed to start the program properly. You should check that `auth.config` is filled in correctly and that no commas or brackets are misplaced. also could you provide the command you used to start the program?

**Comment by skeliceagesjh-dev** [comment]
> it seems to have failed to start the program properly. You should check that `auth.config` is filled in correctly and that no commas or brackets are misplaced. also could you provide the command you used to start the program?

I double clicked the start_ofd.py, where can i find 'auth.config'?

**Comment by skeliceagesjh-dev** [comment]
> No, he means the auth.json that is located under:
> 
> OnlyFans-master \ .profiles \ OnlyFans \ default\ auth.json
> 
> Also check your:
> 
> OnlyFans-master \ .settings \ config.json
> 
> if everything is correct there.
> 
> In the worst case delete the .profiles and .settings folder and relaunch the app with start_ofd.py

yes regarding that, i actually opened auth.json and config.json using notepad, is it correct?

**Comment by scopion1745** [comment]
I had the same "problem" and just noticed that the Line " 0 = Onlyfans |" is a question.
It asks you to choose your Website you want to scrape.
Previously i just hit enter, till it errors out with your shown error. Than i got it.


Have you tried enterein "0"?

**Comment by skeliceagesjh-dev** [comment]
> Yes you can use notepad.
> 
> I've also just looked at the code and line 40 is if statement. It looks like you did not press the "0" for onlyfans. If you go into your config.json you can set this in "settings":
> 
> "auto_site_choice": "onlyfans",
> 
> That way you don't have to select 0 everytime you start the app.

oh i just realised that i need to press 0, but now i can only see account that i subscribed for free and also where are the media stored?

**Comment by Gixxa** [comment]
OnlyFans-master \ .sites \ OnlyFans \ model-username

**Comment by skeliceagesjh-dev** [comment]
> OnlyFans-master \ .sites \ OnlyFans \ model-username

do i need to subscribe to scrape content?

**Comment by Gixxa** [comment]
No, you can even bypass the paywall, just take a look at the FAQ:

https://github.com/DIGITALCRIMINAL/OnlyFans#faq

**Comment by Gixxa** [comment]
Yes and now think about the question and answer with the right head and you will get the answer.

**Comment by skeliceagesjh-dev** [comment]
So no?

**Comment by Gixxa** [comment]
![right](https://user-images.githubusercontent.com/6295802/119695586-9ca94e80-be4e-11eb-8ad2-1d0cd0a38183.gif)

**Comment by DIGITALCRIMINAL** [comment]
I just woke up and this is the first thing I saw, lmao
