### ISSUE TITLE
Weird quirk in current master.

### ISSUE THREAD

**Issue by left1000** [DIGITALCRIMINAL/OnlyFans#1256]
Couldn't get 7.2 to work.
So I switched from 7.2 to master commit and instead got everything working perfectly EXCEPT the list of models I follow on onlyfans has each model appear three times in a row, rather than once in a row, making the list of models three times as long for no reason. I downloaded from this link https://github.com/DIGITALCRIMINAL/OnlyFans/archive/refs/heads/master.zip maybe 20 minutes ago.

If this is a purely cosmetic issue it's not a big deal, but what I fear is that selecting one of the three different numbers with the same username will lead to different results. I'm not sure how they'd be different, perhaps rechecking or redownloading more than was needed?

edit: totally unrelated sidenote that doesn't belong here, what does the program do when a disk is full? I think my disk was full for like 1minute before I moved some files around during a rip... did it pause? or just write a bunch of half full video files to disk that it won't replaces on rescrape because the files exist (in an incomplete form)... my GUESS is that it doesn't cause any harm because it looks like only fully complete files can be written to the disk? (files seem to go from 0 filesize to full filesize without stopping anywhere in between during download)...

**Comment by E0911CD45B19686** [comment]
Answered in #1258

**Comment by DIGITALCRIMINAL** [comment]
When disk is full, it goes into an infinite loop until you delete files. Even if the files don't download completely, the script will recognize it and download them again.
