### ISSUE TITLE
Every model is listed twice

### ISSUE THREAD

**Issue by newadventure079** [DIGITALCRIMINAL/OnlyFans#1258]
I'm on the latest master pull.  I run the script and below is what I get

```
Scraping Paid Content
Scraping - sexbydesign | 1 / 56
Scraping - sexbydesign | 2 / 56
Scraping - melody_katt | 3 / 56
Scraping - melody_katt | 4 / 56
Scraping - angela_ride | 5 / 56
Scraping - angela_ride | 6 / 56
Scraping - yummycouple | 7 / 56
Scraping - yummycouple | 8 / 56
Scraping - officialkmbooty | 9 / 56
Scraping - officialkmbooty | 10 / 56
Scraping - jessiebuns | 11 / 56
Scraping - jessiebuns | 12 / 56
Scraping - moodyfeet | 13 / 56
Scraping - moodyfeet | 14 / 56
Scraping - jessikagotti | 15 / 56
Scraping - jessikagotti | 16 / 56
Scraping - aaliyahlove | 17 / 56
Scraping - aaliyahlove | 18 / 56
Scraping - xtaylorjayx | 19 / 56
Scraping - xtaylorjayx | 20 / 56
Scraping - allipark22 | 21 / 56
Scraping - allipark22 | 22 / 56
Scraping - sheisatang | 23 / 56
Scraping - sheisatang | 24 / 56
Scraping - annablossom | 25 / 56
Scraping - annablossom | 26 / 56
Scraping - youlovemads | 27 / 56
Scraping - youlovemads | 28 / 56
Scraping - pixei | 29 / 56
Scraping - pixei | 30 / 56
Scraping - juliecb | 31 / 56
Scraping - juliecb | 32 / 56
Scraping - jewlsmarciano | 33 / 56
Scraping - jewlsmarciano | 34 / 56
Scraping - kikimarie | 35 / 56
Scraping - kikimarie | 36 / 56
Scraping - sashawonderr | 37 / 56
Scraping - sashawonderr | 38 / 56
Scraping - kyliecupcake | 39 / 56
Scraping - kyliecupcake | 40 / 56
Scraping - tiffanyhouston_of | 41 / 56
Scraping - tiffanyhouston_of | 42 / 56
Scraping - saffronbacchus | 43 / 56
Scraping - saffronbacchus | 44 / 56
Scraping - hollybabyxoxo | 45 / 56
Scraping - hollybabyxoxo | 46 / 56
Scraping - jessnjamez | 47 / 56
Scraping - jessnjamez | 48 / 56
Scraping - brandibraids | 49 / 56
Scraping - brandibraids | 50 / 56
Scraping - lemon__cakes | 51 / 56
Scraping - lemon__cakes | 52 / 56
Scraping - fit_american_girl | 53 / 56
Scraping - fit_american_girl | 54 / 56
Scraping - surfergirl121 | 55 / 56
Scraping - surfergirl121 | 56 / 56
Scraping Subscriptions
Names: Username = username  | 0 = All | 1 = sexbydesign | 2 = sexbydesign | 3 = melody_katt | 4 = melody_katt | 5 = angela_ride | 6 = angela_ride | 7 = yummycouple | 8 = yummycouple | 9 = officialkmbooty | 10 = officialkmbooty | 11 = jessiebuns | 12 = jessiebuns | 13 = moodyfeet | 14 = moodyfeet | 15 = jessikagotti | 16 = jessikagotti | 17 = aaliyahlove | 18 = aaliyahlove | 19 = xtaylorjayx | 20 = xtaylorjayx | 21 = allipark22 | 22 = allipark22 | 23 = sheisatang | 24 = sheisatang | 25 = annablossom | 26 = annablossom | 27 = youlovemads | 28 = youlovemads | 29 = pixei | 30 = pixei | 31 = juliecb | 32 = juliecb | 33 = jewlsmarciano | 34 = jewlsmarciano | 35 = kikimarie | 36 = kikimarie | 37 = sashawonderr | 38 = sashawonderr | 39 = kyliecupcake | 40 = kyliecupcake | 41 = tiffanyhouston_of | 42 = tiffanyhouston_of | 43 = saffronbacchus | 44 = saffronbacchus | 45 = hollybabyxoxo | 46 = hollybabyxoxo | 47 = jessnjamez | 48 = jessnjamez | 49 = brandibraids | 50 = brandibraids | 51 = lemon__cakes | 52 = lemon__cakes | 53 = fit_american_girl | 54 = fit_american_girl | 55 = surfergirl121 | 56 = surfergirl121
```

**Comment by newadventure079** [comment]
I entered `0` to process all of them and it's processing each one twice

**Comment by HaseoKite** [comment]
The error comes directly from the OF API.

**Comment by hammerheaddf** [comment]
Yours are under control. My 800+ subs became almost 4000 entries. Things are out of control!

**Comment by DIGITALCRIMINAL** [comment]
Im redoing the script. It's gonna take some time. I suggest using an earlier commit for now.

**Comment by wanyek43** [comment]
Which commit is working properly? I updated on Tuesday and am now getting this. Mine is now showing them 6 or 7 times, making the list up to 702. I'm not exactly sure which version I was running before but it was ≥7 for sure. It worked but got slower.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit

**Comment by wanyek43** [comment]
I just pulled the latest almost 10 minutes ago and it just finished listing the names. It got stuck at "Welcome" for about most of that time and still ended up listing everything 6 or 7 times.

**Comment by DIGITALCRIMINAL** [comment]
Ah, I've now encountered the bug, so I'll fix it.

**Comment by wanyek43** [comment]
No, just the one.

Side note: I know it's been posted in a thread here before, but what is the link to donate to you and the project?

**Comment by DIGITALCRIMINAL** [comment]
Alright, I've pushed the commit.

**Comment by DIGITALCRIMINAL** [comment]
I've only got Crypto .-.

**Comment by wanyek43** [comment]
Now getting this after processing my blacklist on the latest commit:

> Traceback (most recent call last):
  File "/Users/artsevilla/Developer/Python/OnlyFans/start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Users/artsevilla/Developer/Python/OnlyFans/datascraper/main_datascraper.py", line 99, in start_datascraper
    subscription_list = module.format_options(subscription_array, "usernames", api.auths)
  File "/Users/artsevilla/Developer/Python/OnlyFans/modules/onlyfans.py", line 1482, in format_options
    subscriber = x.get_subscriber(match_list)
  File "/Users/artsevilla/Developer/Python/OnlyFans/apis/onlyfans/classes/create_user.py", line 218, in get_subscriber
    subscribes = self.subscribedByData["subscribes"][-1]
IndexError: list index out of range

**Comment by wanyek43** [comment]
I don't have any crypto. Would you take an e-gift card to a spot of your choice or something? I want to give you $50 USD.

**Comment by DIGITALCRIMINAL** [comment]
> Now getting this after processing my blacklist on the latest commit:
> 
> > Traceback (most recent call last):
> > File "/Users/artsevilla/Developer/Python/OnlyFans/start_ofd.py", line 44, in 
> > api = main_datascraper.start_datascraper(json_config, site_name_lower)
> > File "/Users/artsevilla/Developer/Python/OnlyFans/datascraper/main_datascraper.py", line 99, in start_datascraper
> > subscription_list = module.format_options(subscription_array, "usernames", api.auths)
> > File "/Users/artsevilla/Developer/Python/OnlyFans/modules/onlyfans.py", line 1482, in format_options
> > subscriber = x.get_subscriber(match_list)
> > File "/Users/artsevilla/Developer/Python/OnlyFans/apis/onlyfans/classes/create_user.py", line 218, in get_subscriber
> > subscribes = self.subscribedByData["subscribes"][-1]
> > IndexError: list index out of range
> 
> Edit: I tried turning off the Paid Content job, but same result.

Will work now

**Comment by HaseoKite** [comment]
While we wait for DigitalCriminal to solve the last issues.
You can download or checkout to commit "9e97a45fb2260cb3c2561e7820a4acb6472849ee"

Replace /modules/onlyfans.py with this file:  [https://pastebin.com/jFP7AEDE](https://pastebin.com/jFP7AEDE)

**Comment by wanyek43** [comment]
Thanks for the quick updates. It's now listing the models once and getting past the blacklist, but it doesn't seem to be downloading anything. I tried to manually update one of my newest subs, and it didn't download anything. It created the model, metadata and profile folders, but it didn't actually download any of the content. It also didn't update one of my other subs. They've been posting and messaging through today, but the last downloads I have are from 4/25. The sub is still good. I'm still testing with all of the other subs.

**Comment by HaseoKite** [comment]
> 
> 
> Thanks for the quick updates. It's now listing the models once and getting past the blacklist, but it doesn't seem to be downloading anything. I tried to manually update one of my newest subs, and it didn't download anything. It created the model, metadata and profile folders, but it didn't actually download any of the content. It also didn't update one of my other subs. They've been posting and messaging through today, but the last downloads I have are from 4/25. The sub is still good. I'm still testing with all of the other subs.


The last commit fixed it, it's working now!! Try to download the last version.

**Comment by wanyek43** [comment]
Still not downloading anything...
