### ISSUE TITLE
I can't use the program

### ISSUE THREAD

**Issue by FuriaseFTW** [DIGITALCRIMINAL/OnlyFans#126]
When i run "StartDatascraper.py", it asks me the number if the site. I write "0" for onlyfans and it prints:

Auth (V1) Attempt 01/10
Auth (V1) Attempt 02/10
....
....
Auth (V1) Attempt 10/10

After this it asks me again the number. I can't use the program.. help me please

**Comment by DIGITALCRIMINAL** [comment]
Are you using the latest commit?

**Comment by FuriaseFTW** [comment]
Yes, but maybe if filling "config.json" wrong.

**Comment by DIGITALCRIMINAL** [comment]
You need to fill in the sess token and useragent, that's pretty much it

**Comment by FuriaseFTW** [comment]
When i write "?app" on the bar of the network debugger i get  choices:
1. https://onlyfans.com/api2/v2/init?app-token=33d57ade8c02dbc5a333db99ff9ae26a
2. https://onlyfans.com/api2/v2/users/me?app-token=33d57ade8c02dbc5a333db99ff9ae26a

Which one should i open for the token and useragent?

**Comment by FuriaseFTW** [comment]
I did it! Now it tells me:
You're not subscribed to any users.

**Comment by DIGITALCRIMINAL** [comment]
Are you subscribed to any?

**Comment by FuriaseFTW** [comment]
Nope ahahah
I think i misunderstood what this program does ahahah

**Comment by DIGITALCRIMINAL** [comment]
Go follow a free account and download their stuff if you wish.

**Comment by FuriaseFTW** [comment]
I thought i could download premium accounts without paying... ahahahha
