### ISSUE TITLE
Stuck when scraper gets to messages

### ISSUE THREAD

**Issue by BadgersDozen** [DIGITALCRIMINAL/OnlyFans#1260]
Hiya,

I pulled the latest commit but whenever I select the model, it goes through the motions until it gets to messages, where it just hangs indefintely

I've left it for a couple of hours just to see if it will eventually go through but I'm not too hopeful

Anyone else seeing this?

<img width="674" alt="OF DC" src="https://user-images.githubusercontent.com/84915899/119832792-6cb58600-bef6-11eb-8f68-cc8fd0047c94.png">

**Comment by headphonia** [comment]
Same issue here.

**Comment by ChillyP** [comment]
Similar issue although mine is getting stuck right at the start when scraping paid content

**Comment by drobb0690** [comment]
im having the exact same issue

**Comment by CannotTouch** [comment]
it's not stuck it take a LOT of time, leave it open and it will pass that point (for me 51mins).

**Comment by headphonia** [comment]
Seems like whatever changes they did to their API has slowed things down... but yes, can confirm if you left the script run, it'll eventually move onto the next model... only to get stuck on messages again... LOL

**Comment by drobb0690** [comment]
i left it for at least 6 hrs or so and it never moved

**Comment by headphonia** [comment]
I reverted back to the May 25 commit, seems to work for me, did a full scrape.

**Comment by drobb0690** [comment]
how does one find an old commit?

**Comment by headphonia** [comment]
Here you go: https://github.com/DIGITALCRIMINAL/OnlyFans/archive/d1f45e6669d2ae96df7bea725789f4b24837c669.zip

**Comment by drobb0690** [comment]
> Here you go: https://github.com/DIGITALCRIMINAL/OnlyFans/archive/d1f45e6669d2ae96df7bea725789f4b24837c669.zip

Thanks for the link

**Comment by DIGITALCRIMINAL** [comment]
You can try the latest commit. It's able to download message content. 

It also took me around 20 seconds to grab 1.7k messages with 32 threads.

**Comment by kallenkozuki** [comment]
> You can try the latest commit. It's able to download message content.
> 
> It also took me around 20 seconds to grab 1.7k messages with 32 threads.

See if you can find a way to bypass the 3 free trials per 24 hours limit ;)

**Comment by Gixxa** [comment]
@DIGITALCRIMINAL 

Is there a difference if I were to use 32 threads (max for me as I have a 1950X) vs. -1? I currently have it set to 32.

**Comment by BadgersDozen** [comment]
> You can try the latest commit. It's able to download message content.
> 
> It also took me around 20 seconds to grab 1.7k messages with 32 threads.

King

**Comment by DIGITALCRIMINAL** [comment]
> @DIGITALCRIMINAL 
> 
> Is there a difference if I were to use 32 threads (max for me as I have a 1950X) vs. -1? I currently have it set to 32.

No difference as -1 will use all threads your cpu has. Mines set to -1.
