### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by winsherter** [DIGITALCRIMINAL/OnlyFans#1265]
when I execute   python start_ofd.py  that's the error I get.......what can I do?

Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/home/winsherter/Downloads/OnlyFans-7.2/tests/main_test.py", line 10
    python_version = f"{version_info.major}.{version_info.minor}"
                                                                ^
SyntaxError: invalid syntax

**Comment by DIGITALCRIMINAL** [comment]
You're not using Python 3.9
