### ISSUE TITLE
Not going past "Scraping Paid Content"

### ISSUE THREAD

**Issue by Bearded-Beard** [DIGITALCRIMINAL/OnlyFans#1267]
This has been happening to me since I updated the other day (I think there has been like 4 updates that I've tried since), but it sits on this for hours (the time before now, I came here and saw a new update) I just wish I knew why its sitting on this, I've made sure the only details I've changed in Config was 

"auto_media_choice": "0" 
Even deleted that 0 just to see if that was doing it.

"filename_format": "{username} - {date} - {filename}.{ext}"

I wonder if its cause I'm subbed to alot of people, but I've never had an issue till the other day (I was subbed to like 50 people)

**Comment by DIGITALCRIMINAL** [comment]
Do you have alot of paid content?

**Comment by artyom2035** [comment]
Same here.  Hangs indefinitely (many hours at least) at the start of scraping paid content. Give this commit https://github.com/DIGITALCRIMINAL/OnlyFans/commit/d1f45e6669d2ae96df7bea725789f4b24837c669 from 3 days ago a try, it's the last that works for me.  I've  got a lot of already downloaded paid content - nothing new for it to grab...

**Comment by Kurosaki22** [comment]
Same issue for me. Last working commit is from the 25th May for me.
It looks like that it just does nothing at all but I can see that every few minutes the RAM usage increases a little bit.

![image](https://user-images.githubusercontent.com/69061840/120069529-a9b08280-c086-11eb-87dd-9bd9717d58da.png)

I have a decent amount of paid content so we just have to keep the script running for few hours?
Because if I use the commit from the 25th the whole process takes about 10 minutes

**Comment by DIGITALCRIMINAL** [comment]
Do you have more than 100 paid content

**Comment by Kurosaki22** [comment]
Is there a way to find the correct number for that?
Because from a quick overlook I would say yes

**Comment by Kurosaki22** [comment]
After 5 hours stuck on the Scraping Paid Content Message I received the following error:
![image](https://user-images.githubusercontent.com/69061840/120078742-3cfead80-c0b1-11eb-9567-f07f30a5aa07.png)

**Comment by DIGITALCRIMINAL** [comment]
Latest commit should fix it

**Comment by Kurosaki22** [comment]
Tried the latest commit and its fixed for me.
Thanks again for your hard work :)

**Comment by Bearded-Beard** [comment]
Sorry, yeah I have tons of paid content, but as Kurosaki22 said, the latest one, almost instantly went past the pause of paid scrape, thanks.
