### ISSUE TITLE
Comma separated creators

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINAL/OnlyFans#1271]
Hi,
I have try to insert more thatn one username to scrape 
ie: xxx, yyy, zzz
but it scrape only the first one.

Thanks for support

**Comment by DIGITALCRIMINAL** [comment]
Do it with a list instead
[Username, username]

**Comment by CannotTouch** [comment]
I have try with square brackets and doesn't scrape neither the first. without brackets it's scrape only the first username

**Comment by CannotTouch** [comment]
I still don't have understand what you suggest 🙈

**Comment by DIGITALCRIMINAL** [comment]
["username", "username2"]
