### ISSUE TITLE
Blacklist loop

### ISSUE THREAD

**Issue by RakSrinaNa** [DIGITALCRIMINAL/OnlyFans#1272]
If you have more than 100 users blacklisted, it'll loop forever trying to fetch the full list.

This seems to be because the link to the listing api isn't parameterized anymore:
https://github.com/DIGITALCRIMINAL/OnlyFans/blob/afe026969f11aa7dd5fdaabb261f39c5baa99d29/apis/onlyfans/classes/extras.py#L55

It should probably contain parameters `global_limit` and `global_offset` to match the call

https://github.com/DIGITALCRIMINAL/OnlyFans/blob/afe026969f11aa7dd5fdaabb261f39c5baa99d29/apis/onlyfans/classes/create_auth.py#L200-L202

**Comment by DIGITALCRIMINAL** [comment]
Thanks, you can try the latest commit

**Comment by RakSrinaNa** [comment]
Works good now 👌
