### ISSUE TITLE
Another Traceback error

### ISSUE THREAD

**Issue by expl0sivesku11** [DIGITALCRIMINAL/OnlyFans#1273]
i still get a traceback error. i dont know what i am doing wrong. i am not a genius with these things. i just listen to what the other geniuses say. please help.

Traceback (most recent call last):
  File "C:\Users\paulf\Downloads\Github Onlyfans DIGITALCRIMINAL\OnlyFans\start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\paulf\Downloads\Github Onlyfans DIGITALCRIMINAL\OnlyFans\datascraper\main_datascraper.py", line 72, in start_datascraper
    auths = choose_option(subscription_list, auto_profile_choice, True)
  File "C:\Users\paulf\Downloads\Github Onlyfans DIGITALCRIMINAL\OnlyFans\helpers\main_helper.py", line 578, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

**Comment by myotheraccount420** [comment]
You need to wrap your choice for `auto_profile_choice` with quotes as it is expecting a string, not a digit.

e.g. 

`auto_profile_choice: "1"`

**Comment by expl0sivesku11** [comment]
awesome that fixed it, but now it wont download stuff properly. it only scrapes the "count" of items, then pauses scraper and back to my subscriptions.

**Comment by expl0sivesku11** [comment]
here is what my config looks like, maybe an error in it....


{
  "info": {
    "version": 7.1
  },
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "41cc92e1c0b811eb9f4d14abc56b01c9"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "1",
        "auto_model_choice": false,
        "auto_media_choice": "0",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": false
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{date}_{filename}.{ext}",
        "metadata_directories": [
          ".metadatas"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%m-%d-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": "",
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    }
  }
}

**Comment by nappyapp** [comment]
Change this section to look like this:

```"onlyfans": {
"settings": {
"auto_profile_choice": "0",
"auto_model_choice": true,
"auto_media_choice": "0",
"auto_api_choice": true,
```

**Comment by nappyapp** [comment]
Also you can set scrape_paid_content to true

**Comment by expl0sivesku11** [comment]
yes that fixed it. i'm glad the script is completely fixed now. wonder what the issue was with it or onlyfans that gave it so many problems lately....lol thank you for the fast support.
