### ISSUE TITLE
Latest commit not downloading content

### ISSUE THREAD

**Issue by wanyek43** [DIGITALCRIMINAL/OnlyFans#1274]
I have the latest commit, and it won't download anything. I have a lot of new trial subs from the last week and a couple of paid ones, but none of the content is being downloaded. It created the model, profile, and metadata folders, but skipped the downloads.

**Comment by nappyapp** [comment]
Strange, the latest commit is downloading correctly for me

**Comment by xImJakeyy** [comment]
Had the same issue, gone back down to release 7.1 to download content.

Not noticed I've had zero content downloading since the 18th.

**Comment by wanyek43** [comment]
I can confirm nothing is downloading. I ran the scraper multiple times with the same result. I am on the latest commit.

**Comment by Gamma-Velorum** [comment]
I'm having the same problem. Even when I set `"auto_model_choice": false` and manually select the new model I've subscribed to, the content won't download.

This is on v7.2 not the latest commit.  I might try @xImJakeyy's suggestion.

**Comment by xImJakeyy** [comment]
@Gamma-Velorum Only thing I had to-do to get it to work, was recreate the Config file. I think its layout changed after the 7.1 release so newer ones didn't work.

**Comment by BadgersDozen** [comment]
I've found that if I select to download from all models, it will only scrape but not download. If I select each model individually, it will download from that model.

**Comment by wanyek43** [comment]
@BadgersDozen I've tried that and it still doesn't work for me.

**Comment by Sutogai** [comment]
`auto_media_choice` has seemingly been changed. Used to have a value of `a`, but now needs `0`. [Gazebo-guy found it.](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1239#issuecomment-847499203) Might be worth a shot.

**Comment by lEtranger1942** [comment]
Git clone the repo. Don't download releases. When you git clone you get the latest modifications. 

Also read the commit comments if something is not working. DC explains with each commit what has changed

**Comment by Jakeyy22** [comment]
> `auto_media_choice` has seemingly been changed. Used to have a value of `a`, but now needs `0`. [Gazebo-guy found it.](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1239#issuecomment-847499203) Might be worth a shot.

Yup that looks to be the fix here.
Tried again on the latest code pull with '0' instead of 'a'.

Thanks for pointing out the other thread

**Comment by wanyek43** [comment]
@Sutogai thanks for pointing that out. I didn't see that change noted anywhere, but probably missed it. It's going through the scrape again, but sounds like that is the fix.

@lEtranger1942 I don't use the releases. I update the repo.

**Comment by Gamma-Velorum** [comment]
`auto_profile_choice": [],`

has changed as well. no idea what value to put there. tried default without the [], tried it within the [], tried 1 without and 1 within []
