### ISSUE TITLE
Feature request: can the script check for sales?

### ISSUE THREAD

**Issue by nappyapp** [DIGITALCRIMINAL/OnlyFans#1276]
Would it be possible to have the script check if any previously expired models are currently on sale? Maybe even report how many new posts since the expiration? That would be helpful

**Comment by DIGITALCRIMINAL** [comment]
I don't want to turn the script into something that it's not, but you or someone can build it easily using the API.

**Comment by nappyapp** [comment]
I know some coding but not enough for that unfortunately. Maybe a plugin
like the renamer etc?

**Comment by nappyapp** [comment]
Initiating by a command line argument maybe?

But ya I get you on the scope creep. I just figured it would be nice to have all the tools in one place

**Comment by nappyapp** [comment]
Moved to discussion
