### ISSUE TITLE
AutoLiker

### ISSUE THREAD

**Issue by SafadezaSemLimites** [DIGITALCRIMINAL/OnlyFans#1281]
Could you implement a tool/feature to automatically like all of a user's posts on OF? Thanks and keep up the good work!

**Comment by wanyek43** [comment]
Looks like he has been working on that since I saw some code seeming to reference that, but there doesn't seem to be an option to enable it. It's probably not done yet.

**Comment by DIGITALCRIMINAL** [comment]
Someone can easily build it via the API, but the API isn't ready yet.
