### ISSUE TITLE
Renamer not working during metadata upgrade

### ISSUE THREAD

**Issue by PJD94** [DIGITALCRIMINAL/OnlyFans#1283]
Hi when I run the script against a folder that was created with the old version (python 3.8) the metadata successfully upgrades to the dB file but all content is then re downloaded, existing images are not detected/renamed anymore, this worked around 3 weeks ago. Bug or am I doing it wrong now?

**Comment by artyom2035** [comment]
The ability to enable/disable the renamer was added back on 2 May https://github.com/DIGITALCRIMINAL/OnlyFans/commit/1d212a837e322e2f200d21ba2a6313e610121a68. Have you made sure `renamer` is `true` in the config?

**Comment by PJD94** [comment]
The renamer is indeed set to true in the config, during script execution "renaming files" appears for a brief moment but moves on to the next action far to quickly for it to have processed any files.

**Comment by DIGITALCRIMINAL** [comment]
OFRenamer still works. You've probably deleted old metadata files and the model has deleted posts.
