### ISSUE TITLE
No content is added to directory after scraping is done.

### ISSUE THREAD

**Issue by som00s** [DIGITALCRIMINAL/OnlyFans#129]
I'm running the script on macOS catalina and whenever it says "Scrape completed" I don't see the content in my directory. Steps to reproduce:

1. Clone repository.
2. Install requirements with `pip3 install -r requirements.txt`
3. Open safari, open network tracker, login.
4. Update `config.json` with:

"sess": "XXXXXXXXXXXX"
"user-agent": "XXXX"
"directory": "/Users/random",

5. Run script: `python3 StartDatascraper.py`

6. The script will ask me which domain I would like to scrape and then ask for the user I want to scrape. The script shows the following:

Scrape Processing
Name: XXXXXXXXXXXXXXXXX
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Messages
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Completed

When I open my directory I do see the correct folder tree: onlyfans > user > posts > images | metadata | videos 

But these folders are all empty? 

(The reason I'm specifying a directory is to prevent the read-only access error on macOS)

**Comment by DIGITALCRIMINAL** [comment]
Do you change the filename_format

**Comment by som00s** [comment]
@DIGITALCRIMINAL I haven't changed anything besides the sess, user-agent and directory keys. Should the filename-format be updated too?

**Comment by DIGITALCRIMINAL** [comment]
Try double clicking on start datascraper instead

**Comment by som00s** [comment]
That didn't work either, the strange thing is that the `Metadata` folder is not empty and contains a `Images.json` and `Videos.json`

**Comment by DIGITALCRIMINAL** [comment]
It's hard because I don't have a mac to work with so I don't know their directory structure

**Comment by som00s** [comment]
I got it working for macOS catalina. I don't know which steps below solved the problem but in the end these are the things I did to make it work:

1. Install python3 using homebrew for example: `brew install python3`. (pip3 should come together with this install, if not, google is your friend on how to install this).
2. Update your `.bash_profile` with an alias for python:
`alias python='/usr/local/bin/python3` and restart your terminal to update the changes.
3. In terminal navigate to the OnlyFans project, install the requirements with `pip3`:
`pip3 install -r requirements.txt`
4.  Update the `config.json` with the `session`, `app-token`, `user-client` **AND** update the `directory` path. I made a folder in the root of the project called `test`: 

        "directory": "/Users/som00s/Desktop/OnlyFans-master/test"

The reason why is because the script keeps failing to write to the default folder due to permissions.

5. In terminal make the script executable: `chmod 755 StartDatascraper.py`
6. Right click `StartDatascraper.py` in finder and ensure it `always opens with Terminal`.
7. In terminal type: `which python3`, this will print out the path of python3. In my case it returned the following path: `/usr/local/bin/python3`. Copy this path, you'll need to paste it in the next step.
8. Edit the `StartDatascraper.py` using a text editor and put the path on top of the script:
`#!/usr/local/bin/python3` (Make sure you really pasted your own path and not mine, there can be minor differences)
9. Now open finder, navigate to your project, double click the `StartDatascraper.py` and it should automatically start the script. 
10. You're done.

Extra:

- I have 0 knowledge about python and the macOS file handling but these steps really were important:

1. You don't need an init.py file somewhere like stackoverflow suggests.
2. You only need to update the `StartDatascraper.py` which points to python3.
3. You need to update the directory path to a custom path due to folder restrictions.
4. You need to use `python3` and `pip3`.

**Comment by som00s** [comment]
I noticed that when the script asks for the names to select:

Names: 0 = All,  1 = DIGITALCRIMINAL, 2 = som00s ...

And I select 0, the script won't download the content. If I select individual users, all is good. I don't know if only occurs on macOS or due to my changes as explained in https://github.com/DIGITALCRIMINAL/OnlyFans/issues/129#issuecomment-581167697 ..  but I can only make the script work by selecting individual users.

**Comment by DIGITALCRIMINAL** [comment]
@som00s The script scrapes all users first before downloading their content.

**Comment by Guilleack** [comment]
I have the same problem, it access to my account succesfully and when i select an option, it dosen't matter which one it is i get an empty folder except for the Metadata.

I'm on Windows 10. I'm not sure if i should a make a new Issue, thanks for your time.

**Comment by DIGITALCRIMINAL** [comment]
> I have the same problem, it access to my account succesfully and when i select an option, it dosen't matter which one it is i get an empty folder except for the Metadata.
> 
> I'm on Windows 10. I'm not sure if i should a make a new Issue, thanks for your time.

Did you let the script run fully?

**Comment by Guilleack** [comment]
Sorry for the delay, yes it ran fully. It ends almost instalty and asks me again to select an option.

**Comment by DIGITALCRIMINAL** [comment]
Who are you trying to rip?
