### ISSUE TITLE
{date} filename_format is broken

### ISSUE THREAD

**Issue by J4k-The-Reaper** [DIGITALCRIMINAL/OnlyFans#1299]
after i updated requirements with latest commit, it will not download any content. it only tells me the number of posts/photos/videos, then it "pauses scraper" and scrapes my subscriptions. below is what my config looks like, maybe something is wrong in it.

**Comment by DIGITALCRIMINAL** [comment]
I need to see what the script looks like

**Comment by DIGITALCRIMINAL** [comment]
Screenshot the script at the point you think it's stopped working

**Comment by J4k-The-Reaper** [comment]
![Screenshot 2021-06-08 042435](https://user-images.githubusercontent.com/35021417/121177175-f0824300-c811-11eb-87f1-1dba9c846ad5.png)

**Comment by DIGITALCRIMINAL** [comment]
Try removing {date} from filename

**Comment by J4k-The-Reaper** [comment]
it was working perfect, even with the {date} before i updated requirements. i only updated requirements cuz i saw you added the new commit for Asyncio

**Comment by J4k-The-Reaper** [comment]
okay. removing the {date} worked. i only added  that because i was told to add it by someone on some chat forum, cuz it organizes it or something better. guess i dont really need it tho.

**Comment by the-truthBE** [comment]
Hello, I have the same problem, it works when we remove the date from the name, but I have all my files with the date, do you know how tofix the problem please

**Comment by J4k-The-Reaper** [comment]
deleting {date}_ fixed the issue for me. but would like to be able to use it again. makes it easier to find newer/older posts.

**Comment by Macmasteri** [comment]
> deleting {date}_ fixed the issue for me. but would like to be able to use it again. makes it easier to find newer/older content.

Yes I agree on that. I rather go with the date file name. Will wait and see if DC find any solution for this or someone else?

**Comment by J4k-The-Reaper** [comment]
> 
> 
> > deleting {date}_ fixed the issue for me. but would like to be able to use it again. makes it easier to find newer/older content.
> 
> Yes I agree on that. I rather go with the date file name. Will wait and see if DC find any solution for this or someone else?

i am pretty sure DC will fix it soon. but i love that the latest commit makes the script give full download size now. it helps me gauge my storage left on harddrive when downloading.

**Comment by Macmasteri** [comment]
With the latest commit that was up for 10 minutes ago:

When press 0 for everything it only scrapes images, profile, metadata. Video is not scraping.

**Comment by Macmasteri** [comment]
Date does not work with the latest commit for me.

**Comment by PsychoSid** [comment]
I had this also and I used date with `+%Y%m%d` to sort mine. Although I run a post-process `find` to copy new content to a separate directory so not "that" important to me.

Also I had `filename_format` as `{text}-{filename}.{ext}` and I had to remove `{text}-` as well as that was blocking new content downloads.

**Comment by the-truthBE** [comment]
Still the same issue

**Comment by malonecries** [comment]
> I had this also and I used date with `+%Y%m%d` to sort mine. Although I run a post-process `find` to copy new content to a separate directory so not "that" important to me.
> 
> Also I had `filename_format` as `{text}-{filename}.{ext}` and I had to remove `{text}-` as well as that was blocking new content downloads.

I've played with it and it would appear that it's only failing to download when you combine {filename} with anything else. Having the date format as you've stated without {filename} being paired with anything allows downloads.

**Comment by PsychoSid** [comment]
> I've played with it and it would appear that it's only failing to download when you combine {filename} with anything else. Having the date format as you've stated without {filename} being paired with anything allows downloads.

Ah nice. Confirmed I changed mine to `{date}-{text}.{ext}` and it went OK. Seems as @malonecries states that if you use `{filename}` it has to be alone.

Sadly if you want to sanitise the filenames generated to get rid of emoji's from the `{text}` sometimes you end up with nothing and renamer issues and overwrites :)

**Comment by Macmasteri** [comment]
Intresting results.

I run `"filename_format": "{date}-{text}.{ext}",` and `"date_format": "%d-%m-%Y",`
With no luck at all. 

Something I need to change more perhaps?

**Comment by lEtranger1942** [comment]
Same issue here. Would love for the date option to work.

**Comment by DIGITALCRIMINAL** [comment]
I'll fix Date and OFRenamer today. You can continue using the script without date and then rerun the script and it will automatically rename everything to the correct format.

**Comment by J4k-The-Reaper** [comment]
> 
> 
> I'll fix Date and OFRenamer today. You can continue using the script without date and then rerun the script and it will automatically rename everything to the correct format.

cant wait.... you are a godsend, @DIGITALCRIMINAL. you take time outta your life to fix/updat/create this script for us, and dont really expect anything in return. i love you.....(like a god)

**Comment by Macmasteri** [comment]
Is the date working again now?

**Comment by J4k-The-Reaper** [comment]
> Is the date working again now? 

I do not think so just yet. I dont see any new commit from DC. Hopefully soon.

**Comment by J4k-The-Reaper** [comment]
> > Is the date working again now? 
> 
> I do not think so just yet. I dont see any new commit from DC. Hopefully soon.

I don't even know what the "creator fix" is, or what it does/ is for? Anyone know?

**Comment by J4k-The-Reaper** [comment]
Welp....seems like we are still waiting for "{date}_" to be fixed....While subscriptions are expiring. Lol. Hopefully soon though.

**Comment by 666diabolus** [comment]
> Welp....seems like we are still waiting for "{date}_" to be fixed....While subscriptions are expiring. Lol. Hopefully soon though.

If you wanna rush him, put the money on him first, if not, stop complaining. The old commmit before Asyncio still working fine with {date}, try it.

**Comment by direttc** [comment]
> Welp....seems like we are still waiting for "{date}_" to be fixed....While subscriptions are expiring. Lol. Hopefully soon though.

If you want to use {date} renamer, you can just use previous commit [1b14740](https://github.com/DIGITALCRIMINAL/OnlyFans/tree/1b147406de044e32a30713fc3dd182dddfb963e1). It working just fine.

Just don't rush the dev, because this is free.
