### ISSUE TITLE
Getting Access denied

### ISSUE THREAD

**Issue by bpo5r5** [DIGITALCRIMINAL/OnlyFans#13]
I have filled out the requirements inside settings.json, and I am still currently subscribed to the user in question. I'm also using the latest commit fa94513.
```
$ python OnlyFans.py
Input a username or profile link
https://onlyfans.com/yung_angel66
Access denied.
First time? Did you forget to edit your settings.json file?
Input a username or profile link
```

let me know how I can help you troubleshoot!

**Comment by DIGITALCRIMINAL** [comment]
You need to update your sess or user_agent

**Comment by bpo5r5** [comment]
I'm entering the correct `app-token` and `sess` as shown under the posts request. 
Could it be that it's not allowing me due to a different IP address? I'm trying to scrape off my currently logged-in network due to it being slower than the VPS.

**Comment by DIGITALCRIMINAL** [comment]
Ohh yes, it's the IP address. Has to be the same. At least you encountered this issue so we help others solve this. Thanks!

**Comment by DIGITALCRIMINAL** [comment]
You don't have to use the same ip address anymore if you get the recent script
