### ISSUE TITLE
Media creation/modification timestamps not correct

### ISSUE THREAD

**Issue by E0911CD45B19686** [DIGITALCRIMINAL/OnlyFans#1304]
Running commit f49a5d6e9a9633148736db3e19f037d26a829a49 (Implement Asyncio) on Synology DSM 6.

I noticed all the "Date Modified" (as shown in Mac OS) dates for newly downloaded content was set for the time it was downloaded. This includes older content from models I recently subscribed to.

I haven't gone through the full diff yet but I noticed all usages of [`format_image`](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/7d0b729c70d10c45aa8c09ea473ac2378ab59e8b/helpers/main_helper.py#L110) in [`modules/onlyfans.py`](https://github.com/DIGITALCRIMINAL/OnlyFans/commit/f49a5d6e9a9633148736db3e19f037d26a829a49#diff-123d2d6513200c586685266cc260fb736a143bd0bb9863bf70128433fdb7d1a9) have been removed so I think that's the cause.

**Comment by E0911CD45B19686** [comment]
Looks like [`process_download`](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/apis/api_helper.py#L286) is the new function that writes files to disk and it doesn't appear to explicitly set any times

```python
with open(download_path, "wb") as f:
    f.write(data)
```

**Comment by johndoenotavailable** [comment]
Any ETA for this patch yet?

**Comment by DIGITALCRIMINAL** [comment]
Added it for new downloads and I'll add it to OFRenamer at a later date.
