### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Alexcx6** [DIGITALCRIMINAL/OnlyFans#1305]
Hi, i'm having this issue when trying to start the scraper in the new commit😪
![image](https://user-images.githubusercontent.com/59067553/121236725-dec58d80-c85b-11eb-9716-98b50a796582.png)

**Comment by DIGITALCRIMINAL** [comment]
Ahh okay, fix your auth and the error will go away

**Comment by Alexcx6** [comment]
Thx! solved, now I got this one, it isn't scraping nothing😭I will check the other issues in case someone had the same problem
![image](https://user-images.githubusercontent.com/59067553/121248552-2dc5ef80-c869-11eb-9805-f98f08bc67f4.png)

**Comment by DIGITALCRIMINAL** [comment]
What's your filename format?

**Comment by Alexcx6** [comment]
Same as usual, I don't touch the config.json file
![image](https://user-images.githubusercontent.com/59067553/121265753-eba7a880-c87e-11eb-858c-479355eb27af.png)

**Comment by DIGITALCRIMINAL** [comment]
Hmm, strange. Are you sure the files aren't already downloaded?

**Comment by Alexcx6** [comment]
Sure, it just download the avatar pic

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit
