### ISSUE TITLE
[Request] Download from multiple OF accounts at once

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#131]
Would it be possible to add (or is it already possible) to add multiple accounts to the config?

**Comment by DIGITALCRIMINAL** [comment]
Do you mean to store accounts in the config? I could add in that feature

**Comment by bobsage123** [comment]
> Do you mean to store accounts in the config? I could add in that feature

That is correct. To be able to rip from multiple logins. Thanks

**Comment by DIGITALCRIMINAL** [comment]
@bobsage123 with the extra auth, would you like me to merge all of the subscriptions together?

**Comment by DIGITALCRIMINAL** [comment]
Download the latest commit and lemme know if it works please

**Comment by bobsage123** [comment]
Will do, thank you

**Comment by bobsage123** [comment]
> Download the latest commit and lemme know if it works, please

The latest commit I see is the text removal one from 8 days ago. Is there supposed to be another after that?

**Comment by bobsage123** [comment]
> @bobsage123
> I can give you the option to choose accounts you'd like to login to, and I give you an option to merge all account's subscriptions together.
> 
> I'll do the first option first.

Okay great. I was able to get it working, but it merged all accounts together automatically per the second option. Did not see a setting to be able to choose which account to use.

Is it also possible to add more then one account in extra_auth? Was not sure how to do that.

Thanks

**Comment by DIGITALCRIMINAL** [comment]
You gotta copy and paste this

![image](https://user-images.githubusercontent.com/21285176/74300351-6b833880-4d47-11ea-9365-9f429befeafd.png)

Don't forget to add the comma before the ```{```

**Comment by bobsage123** [comment]
Okay, thanks. 

Is the option to choose which account to login to available yet? Was not sure based on above comment.

**Comment by DIGITALCRIMINAL** [comment]
I'm working on it now

**Comment by DIGITALCRIMINAL** [comment]
Added, set choose_auth to true in the config

**Comment by bobsage123** [comment]
It worked great at first, but now I can no longer auth into any account. Switched out the sess tokens.
Also tried older versions of the app same thing... So I think something might be going on on their site, going to give it a while and try again.

**Comment by DIGITALCRIMINAL** [comment]
It's on their side. They changed their API again. Tryna fix it.

**Comment by bobsage123** [comment]
Ahh crap. Okay thanks

**Comment by DIGITALCRIMINAL** [comment]
The latest commit should have fixed it

**Comment by DIGITALCRIMINAL** [comment]
You can copy and paste your config over. Nothing has changed except for one file.

**Comment by bobsage123** [comment]
Looks good so far! Thanks for the quick fix
