### ISSUE TITLE
don't know if this is an auth error 

### ISSUE THREAD

**Issue by rafaelsousa221** [DIGITALCRIMINAL/OnlyFans#1310]
![image](https://user-images.githubusercontent.com/20792719/121349453-6e813f80-c921-11eb-89f6-a7d64486d1cc.png)

**Comment by LunarPenguin** [comment]
seems normal to me up to this point. have you tried typing `0` and hitting <kbd>enter</kbd>? you could also set `auto_site_choice` to `onlyfans` in `config.json`

**Comment by rafaelsousa221** [comment]
![image](https://user-images.githubusercontent.com/20792719/121356007-5eb92980-c928-11eb-8bf1-9ba03fa6cda9.png)
iit dosent show the names of the models that i follow
