### ISSUE TITLE
Infinite "Auth 404'ed" when trying to start scraper after latest commits - macOS 11

### ISSUE THREAD

**Issue by rsmithjfy13** [DIGITALCRIMINAL/OnlyFans#1316]
I've double and triple checked auth info and even tried generating new sessions and updating auth.json to no avail. Everything was working fine until I pulled the most recent commits, starting from commit https://github.com/DIGITALCRIMINAL/OnlyFans/commit/5be27adf7f8b8f93fe9c59bc3335ead023f3026e on 6/7/21.

**Sample terminal output:**

Auth (V1) Attempt 1/10
Auth 404'ed
Auth (V1) Attempt 2/10
Auth 404'ed
Auth (V1) Attempt 3/10
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcda9f12490>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcda9ea05b0>
Auth 404'ed
Auth (V1) Attempt 4/10
Auth 404'ed
Auth (V1) Attempt 5/10
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcd9801b280>
Auth 404'ed

**Comment by DIGITALCRIMINAL** [comment]
Are you using proxy?

**Comment by rsmithjfy13** [comment]
> Are you using proxy?

I'm using a VPN, but I'm also seeing the same issue when I disconnect from the VPN.

**Comment by dominikfigueroa** [comment]
I'n seeing this right now also.

**Comment by dominikfigueroa** [comment]
Update: Commit `1b147406de044e32a30713fc3dd182dddfb963e1` works for me.

**Comment by rsmithjfy13** [comment]
> Update: Commit `1b147406de044e32a30713fc3dd182dddfb963e1` works for me.

Yeah, that's the last commit that worked for me too.

**Comment by DIGITALCRIMINAL** [comment]
I made changes to network requests, maybe it will work.

**Comment by rsmithjfy13** [comment]
> I made changes to network requests, maybe it will work.

I'm still seeing the same behavior after pulling the latest commit unfortunately.

**Comment by DIGITALCRIMINAL** [comment]
Do you have 2FA enabled?

**Comment by rsmithjfy13** [comment]
> Do you have 2FA enabled?

I do not have 2FA enabled, no.

**Comment by aloysiusantioch** [comment]
I am also having the issue. In case this is useful:

`Traceback (most recent call last):
  File "/Users/username/onlyfans/start_ofd.py", line 45, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/username/onlyfans/datascraper/main_datascraper.py", line 80, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Users/username/onlyfans/modules/onlyfans.py", line 119, in account_setup
    cookies = oflogin.login(auth, domain, auth.session_manager.proxies[0])
IndexError: list index out of range

^CTraceback (most recent call last):
  File "/Users/username/onlyfans/start_ofd.py", line 45, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/username/onlyfans/datascraper/main_datascraper.py", line 80, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Users/username/onlyfans/modules/onlyfans.py", line 119, in account_setup
    cookies = oflogin.login(auth, domain, auth.session_manager.proxies[0])
IndexError: list index out of range`

No proxies/vpns, no 2FA.

**Comment by DIGITALCRIMINAL** [comment]
> I am also having the issue. In case this is useful:
> 
> `Traceback (most recent call last):
>   File "/Users/username/onlyfans/start_ofd.py", line 45, in main
>     api = await main_datascraper.start_datascraper(
>   File "/Users/username/onlyfans/datascraper/main_datascraper.py", line 80, in start_datascraper
>     setup, subscriptions = await module.account_setup(
>   File "/Users/username/onlyfans/modules/onlyfans.py", line 119, in account_setup
>     cookies = oflogin.login(auth, domain, auth.session_manager.proxies[0])
> IndexError: list index out of range
> 
> ^CTraceback (most recent call last):
>   File "/Users/username/onlyfans/start_ofd.py", line 45, in main
>     api = await main_datascraper.start_datascraper(
>   File "/Users/username/onlyfans/datascraper/main_datascraper.py", line 80, in start_datascraper
>     setup, subscriptions = await module.account_setup(
>   File "/Users/username/onlyfans/modules/onlyfans.py", line 119, in account_setup
>     cookies = oflogin.login(auth, domain, auth.session_manager.proxies[0])
> IndexError: list index out of range`
> 
> No proxies/vpns, no 2FA.

It's a different thing, but I've fixed it in latest commit.

**Comment by dralfs513** [comment]
The 404 issue comes up if your python install doesn't have certificates installed.

Run the following then try again and it should work:

`sudo /Applications/Python\ 3.9/Install\ Certificates.command`

**Comment by rsmithjfy13** [comment]
> The 404 issue comes up if your python install doesn't have certificates installed.
> 
> Run the following then try again and it should work:
> 
> `sudo /Applications/Python\ 3.9/Install\ Certificates.command`

This has solved the issue for me, thank you!
