### ISSUE TITLE
4b72a69 not working

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#1317]
Processing metadata.
Merging new metadata with old metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade aeb9fe314556 -> 7c1c6e101059, content
Traceback (most recent call last):
  File "X:\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "X:\OnlyFans\datascraper\main_datascraper.py", line 101, in start_datascraper
    paid_content = await module.paid_content_scraper(api, identifiers)
  File "X:\OnlyFans\modules\onlyfans.py", line 421, in paid_content_scraper
    w = process_metadata(
  File "X:\OnlyFans\modules\onlyfans.py", line 670, in process_metadata
    Session, api_type, folder = main_helper.export_sqlite(
  File "X:\OnlyFans\helpers\main_helper.py", line 297, in export_sqlite
    x = legacy_database_fixer(
  File "X:\OnlyFans\helpers\main_helper.py", line 205, in legacy_database_fixer
    x = export_sqlite(old_database_path, datas, database_name, legacy_fixer=True)
  File "X:\OnlyFans\helpers\main_helper.py", line 326, in export_sqlite
    post_db.archived = post["archived"]
KeyError: 'archived'

it crashed while scraping: sweet_redhead

edit: putting "scrape paid" to false temporarily avoids that issue but now I just noticed I don't see my most recent free subscription in the list.

**Comment by DIGITALCRIMINAL** [comment]
Do you have json files in the metadata? Rename them to something else.

**Comment by fl4shback** [comment]
Having the same issue since yesterday.
I'm on the latest commit and renamed every json file in Metadata folders.

**Comment by jp1151419** [comment]
> 
> 
> Do you have json files in the metadata? Rename them to something else.

Any reason I should keep those files? I know they let me look into the info of posts based on their filename but isn't that accessible in the .db files as well?

**Comment by DIGITALCRIMINAL** [comment]
If a model deletes a file, you can't rename it anymore. I've made sure to merge all json files though, but it seems like one of your json files uses an older format that I haven't been able to get an example of.

**Comment by fl4shback** [comment]
Shouldn’t it work after renaming the json files though ? Because it’s not the case.

I could always try to delete them if they’re not used anymore

**Comment by DIGITALCRIMINAL** [comment]
Duplicate issue.

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1309
