### ISSUE TITLE
Unable to get past auth.

### ISSUE THREAD

**Issue by direttc** [DIGITALCRIMINAL/OnlyFans#1319]
I've been using `1b147406de044e32a30713fc3dd182dddfb963e1` for the past 10 days, it was working fine. But encounter the following error today.

```
Site: 0 = onlyfans |
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Please refresh the page
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.03 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |
```

Seems like it can't get pass the authentication process. I've updated to the latest commit `4b72a69c3fe28b47c86566006b6542f6cd7f2530` but it still give out same output.

I've also tried to connect with and without VPN, and still got same result. I'm not sure where did I do wrong.

**Comment by Gixxa** [comment]
Just wait the dynamic-rules have to be updated.

**Comment by Macmasteri** [comment]
Same here.

**Comment by DIGITALCRIMINAL** [comment]
Done
