### ISSUE TITLE
Download from certain date

### ISSUE THREAD

**Issue by GreyBeardy** [DIGITALCRIMINAL/OnlyFans#132]
Hi.

Just want to ask if its possible or maybe will be possible in the future to set a certain date to scrape from ?

I ask because if I scraped 1 accounts content and then in 2 months I want to get everything new since last scrape but as it is now I think everything will be re-downloaded once again.

**Comment by DIGITALCRIMINAL** [comment]
In the config there's an option to stop redownloading media you've already downloaded.

**Comment by GreyBeardy** [comment]
For me that dont work if I already moved the downloaded files to another location, then everything is being downloaded again.

I assume you mean the "overwrite_files": should be set to false.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, overwrite_files. Set it to false. When did you last try? I removed the text format because it's broken.

**Comment by GreyBeardy** [comment]
I tried today but havent upgraded to 3.62 yet.

I download to a temp folder on first scrape and then archive the content.
Next scrape then downloads everything again but if I move the first scrape back to original download folder then it will only download the content thats not there when overwrite set to false.

**Comment by DIGITALCRIMINAL** [comment]
Where do you archive the content?

**Comment by GreyBeardy** [comment]
Normally I download on my RDP then download to my own pc and archive it there.
Sometimes I archive to a different folder on the RDP also ... it varies a bit.

**Comment by DIGITALCRIMINAL** [comment]
> Normally I download on my RDP then download to my own pc and archive it there.
> Sometimes I archive to a different folder on the RDP also ... it varies a bit.

Ahh, I know what you're asking for. I would need to locally store the id of the last post and resume the script from there regardless if you haven't downloaded the content.

**Comment by Morticioner87** [comment]
Is it possible to somehow save the local date/time the script last run? And then have an option to only download content posted after this date/time from that user?

**Comment by DIGITALCRIMINAL** [comment]
I mean, yes, but you need to understand that it will still resume from the last scraped image. The last scraped image doesn't even have to be downloaded, so potentially you'll end not downloading all of their content.

**Comment by 180ml** [comment]
A solution: My script that uploads contents from the `sites` directory to my NAS replaces each one with a new file of the same name but `0kb` size. This way the script sees that the file has already been downloaded, but I don't waste space on my main box.
