### ISSUE TITLE
Auth problems?

### ISSUE THREAD

**Issue by kee65** [DIGITALCRIMINAL/OnlyFans#1320]
I filled my auth file using the chrome plugin but am getting this output
`Auth (V1) Attempt 1/10
Please refresh the page
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.03 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |
`

**Comment by Gixxa** [comment]
Just wait the dynamic-rules have to be updated.

**Comment by kee65** [comment]
I was doing it via AnyDesk, just got on my computer, it's working now. (It worked last night too, so it was weird that it stopped)
 Thanks

**Comment by DIGITALCRIMINAL** [comment]
OF updates their rules which breaks the script
