### ISSUE TITLE
I can't login since today

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINAL/OnlyFans#1321]
Hi,

**today, June 11th, I can't login,** and I think I've got the Auth.json file correct, I've checked the cookies, the message is this: Auth(V1) Please refresh the page.. for 10 times.. :

![2021-06-11 16_41_13-TIH0388600A (C_)](https://user-images.githubusercontent.com/81478245/121704363-fe66eb00-cad3-11eb-903c-766eaa19c830.png)

Could you fix this issue?.
Thanks.

**Comment by luckybear992** [comment]
Wait for an update

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit.
