### ISSUE TITLE
MemoryError during download

### ISSUE THREAD

**Issue by skinnedknees** [DIGITALCRIMINAL/OnlyFans#1323]
Traceback (most recent call last):
  File "Z:\OF\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "Z:\OF\datascraper\main_datascraper.py", line 113, in start_datascraper
    x = await main_helper.process_downloads(api, module)
  File "Z:\OF\helpers\main_helper.py", line 692, in process_downloads
    await module.prepare_downloads(subscription)
  File "Z:\OF\modules\onlyfans.py", line 1266, in prepare_downloads
    a = await subscription.session_manager.async_downloads(
  File "Z:\OF\apis\api_helper.py", line 318, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "Z:\OF\apis\api_helper.py", line 313, in run
    result = await asyncio.gather(*tasks)
  File "Z:\OF\apis\api_helper.py", line 290, in process_download
    response = await self.download_content(
  File "Z:\OF\apis\api_helper.py", line 335, in download_content
    response, task = await asyncio.ensure_future(
  File "Z:\OF\apis\api_helper.py", line 195, in json_request
    final_buffer = b"".join(buffer)
MemoryError

I get this error during the download after about 1gb or so has downloaded. Seems to only be on certain pages. I got this error scraping a specific, single model but it was running through the posts at the time which had a count of 1700+. Not sure if the amount plays a roll, but if I scrape others it runs just fine.

Win10x64 32gb RAM
Python 3.9.2
All current requirements.txt satisfied

**Comment by DIGITALCRIMINAL** [comment]
Does your ram fill up? If so lower your max threads.

**Comment by skinnedknees** [comment]
I just checked, at idle its around 50mb, when it starts scraping and downloading it got to 1.5gb and then threw the error. And that was with my thread count at 1(I previously had it left at the default -1). So my system memory is still under 10gb used and isn't really taxed, but maybe there's a process or python mem cap of ~1.5gb? Been using for months and usually stick with default settings(only thing I add is default site and default profile). Not sure how I'm butting up against a ceiling all of a sudden

**Comment by DIGITALCRIMINAL** [comment]
Btw, thyou might have downloaded the 32bit since that's limited to 4GBs,other than that, I dunno lol
