### ISSUE TITLE
Error downloading (seems to be mixing models)

### ISSUE THREAD

**Issue by mwald84** [DIGITALCRIMINAL/OnlyFans#1324]
I'm running the current master (I just synced to be sure) and I am having this error:

It goes through all profiles and download the profile pic (again since it has done that before) then (after a long time renaming files) the script seems to end, with this message:

```
Archive Completed in 7.13 Minutes
Now exiting.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A29FB7D430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

and it repeats the exception many times (all after the "exiting" message).

Then I changed `max_threads` to 1 and got the same error. And it keeps downloading again the profile pics on each run.

I also tried to change `auto_model_choice` to false and run each model separately. Then I get this error:

```
Archive Completed in 7.16 Minutes
Now exiting.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F5D2B3D430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

but interesting is that, before the error, it shows this: 

```
Download Processing
Name: MODEL | Type: Posts | Count: 13 | Directory: XXX

Download Processing
Name: MODELfree | Type: Posts | Count: 1 | Directory: XXX
```

where `MODEL` is the name of one of the models. It's weird that it seems to be trying to download from her free page too (second part) even if I only chose her paid account. I'm subbed to both accounts but I did the scratch only on the paid account.

Then I tried to scrape her free account and I got the error and it shows like it tried to scrape her paid account too (like when I tried to scrape her paid account and it showed the free also)

Then I tried a different model, and the first model free and paid account showed in the download attempts before the error.

This model has over 4k media in over 2k posts (which doens't match the numbers shown in the output I posted above) so it seems it's mixing the models somehow. Could this be the reason?

What am I missing here?

I tried to add as much info as possible to help but let me know if you want me to try something else.

**Comment by Bearded-Beard** [comment]
> It goes through all profiles and download the profile pic (again since it has done that before) then (after a long time renaming files) the script seems to end, with this message:

Mines been doing this part, 59 profiles, only does the profile picture, I hadn't done a update to collection in a week, had to redownload the script and since then it does only the picture, I tried to just run the config in default mode (usually change the filename format) and still will only do the profile, but when I select 1 model, after the scan it shows download (nothing downloaded) other models.

I don't get the error's popping up but the scraping seems to be the same problem.

**Comment by DIGITALCRIMINAL** [comment]
Fixed in latest commit.
