### ISSUE TITLE
Media is not downloaded when rename.

### ISSUE THREAD

**Issue by direttc** [DIGITALCRIMINAL/OnlyFans#1325]
I just updated to the latest commit `4b72a69`

On previous commit `b6aaaa9` I've always rename my files with the following format `"filename_format": "{username}_{date}_{filename}.{ext}"`  and `"date_format": "%Y-%m-%d"`.

I noticed that the media is being scrapped in the latest commit and it shows in the metadata db that the renamer works fine.

![image](https://i.imgur.com/z5uOP1A.png)

But apparently the media is not being downloaded
```
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 2c36fcc0b921, content
INFO  [alembic.runtime.migration] Running upgrade 2c36fcc0b921 -> d0118d8ec0b4, content
INFO  [alembic.runtime.migration] Running upgrade d0118d8ec0b4 -> aeb9fe314556, content
INFO  [alembic.runtime.migration] Running upgrade aeb9fe314556 -> 7c1c6e101059, content
Renaming files.
Scrape Completed

Download Processing
Name: indiefoxxx | Type: Posts | Count: 17 | Directory: E:\Files\OnlyFans-master\.sites

Archive Completed in 1.51 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |

```
I noticed that the script will download medias only if I set `"{filename}.{ext}"`. Other than that it will not download anything. Have anyone facing the same issue?

**Comment by DIGITALCRIMINAL** [comment]
Duplicate issue
