### ISSUE TITLE
Trying to run just doesn't work

### ISSUE THREAD

**Issue by namelessgithub** [DIGITALCRIMINAL/OnlyFans#1335]
What am I missing? Running on python 3.9.5, double pressing start_ofd.py, or starting it from terminal, it will open console, and instantly close. Am I doing something wrong?

**Comment by WellSomething** [comment]
You probably need to do this:

From the project folder open CMD/Terminal and run the command below:

`pip install -r requirements.txt`

**Comment by namelessgithub** [comment]
That was first thing I did. Tried again and just says everything is downloaded and on the latest version.

**Comment by DIGITALCRIMINAL** [comment]
You'd have to debug it in vscode to find out why it's closing
