### ISSUE TITLE
Getting a different sign, refresh page

### ISSUE THREAD

**Issue by JonathanJumper** [DIGITALCRIMINAL/OnlyFans#1353]
firstly, thanks for you work, very appreciated

I cannot get the right `sign`, 🤕  I tried so many different things, 

I literally copied and pasted the code from this repo in a script, and just hardcoded the variables from the request (`final_time, auth_id, Dict`) expecting to get the same sign, 

so, for this same call (you could verify it's working in any terminal easily)

```js
curl 'https://onlyfans.com/api2/v2/users/me' \
  -H 'authority: onlyfans.com' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'time: 1623776851607' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36' \
  -H 'app-token: 33d57ade8c02dbc5a333db99ff9ae26a' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'x-bc: e96475aa223a99904cd21a174e6dc9213a2efe1c' \
  -H 'sign: 57:4ff521a9b87ddd0dea00a842f8f5d72819f9df0a:868:60c862d1' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://onlyfans.com/jonathanjumper' \
  -H 'accept-language: en-US,en;q=0.9,es-CO;q=0.8,es;q=0.7' \
  -H 'cookie: fp=1a9f3a463fe4afdf2f0d9294795d3a35; csrf=FnmJ2wyNb3ea31ae19e9c62ee7e6d3d0f4719d5f; cookiesAccepted=true; sess=1q9bb9gafm5ree64torghr775n; auth_id=114241418; ref_src=https%3A%2F%2Fapi.twitter.com%2F; st=e0e3e5c81f2b1aa13b3038e0cda3b98014695c7e150f88a6271654c11cfa9e6a' \
  --compressed
```

I hardcoded the variables in this script 

```python
from urllib.parse import urlparse
import hashlib

def create_signed_headers(link: str, auth_id: int, dynamic_rules: dict):
    # Users: 300000 | Creators: 301000
    final_time = "1623776851607" # str(int(round(time.time())))
    path = urlparse(link).path
    query = urlparse(link).query
    path = path if not query else f"{path}?{query}"
    a = [dynamic_rules["static_param"], final_time, path, str(auth_id)]
    msg = "\n".join(a)
    message = msg.encode("utf-8")
    hash_object = hashlib.sha1(message)
    sha_1_sign = hash_object.hexdigest()
    sha_1_b = sha_1_sign.encode("ascii")
    checksum = (
        sum([sha_1_b[number] for number in dynamic_rules["checksum_indexes"]])
        + dynamic_rules["checksum_constant"]
    )
    headers = {}
    headers["sign"] = dynamic_rules["format"].format(sha_1_sign, abs(checksum))
    headers["time"] = final_time
    return headers

Dict = {
    "static_param": "6NmByERB9ZDJX9OKDtIzpGl8ei7KBiYI",
    "format": "57:{}:{:x}:60c862d1",
    "checksum_indexes": [13,4,24,33,18,5,17,25,31,28,0,4,19,23,33,1,10,6,12,6,31,25,10,23,0,22,28,35,26,25,7,30],
    "checksum_constant": -14,
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "remove_headers": ["user-id"],
    "error_code": 0,
    "message": ""
}

print(create_signed_headers(
    'https://onlyfans.com/api2/v2/users/me',
    114241418,
    Dict
))
```

I am getting this from that script:
`{'sign': '57:532940ea16d67a434531f5a376be0cbdcfac3b74:906:60c862d1', 'time': '1623776851607'}`
but I am expecting this, same from curl:
`57:4ff521a9b87ddd0dea00a842f8f5d72819f9df0a:868:60c862d1`

am I missing something?
maybe that comment at the beginning `Users: 300000 | Creators: 301000` ?

thanks again, sorry for the inconvenience
I really need to solve this

**Comment by DIGITALCRIMINAL** [comment]
Hmm, you can't use the same sign for any url, maybe it's because of that?

**Comment by JonathanJumper** [comment]
I don't understand, you're saying that I shouldn't expect to get the same sign from `curl` with the same params? 
(a pure function)

I'm just trying to replicate it, with this same `url` and this same `params` and getting that same `sign`
I got that from a request from browser, and that call it's still working

**Comment by OFfriend** [comment]
`https://onlyfans.com/api2/v2/users/me` use the user ID `0` not your real ID. After that every request use your real User ID

**Comment by JonathanJumper** [comment]
Thank you sooo much @OFfriend , that was it for that `/api2/v2/users/me` endpoint, got it working

BUT, I also tried different endpoints different from `/api2/v2/users/me` before opening this thread,
for instance this endpoint, which I'm more **interested**, `/api2/v2/subscriptions/subscribers?limit=10&offset=0&sort=desc&field=last_activity&type=expired` is giving me a different sign from what I expected in `curl`

do you know if that has also some kind of rule?

very appreciated

**Comment by OFfriend** [comment]
**User ID 0:**

- /api2/v2/users/init
- /api2/v2/users/me

**Everything else: 114241418 (your ID)**

But OF already using Version `58`

**Comment by JonathanJumper** [comment]
What do you mean by the last comment?
Do you mean OF updated the sign protocol again in this version?

**Comment by OFfriend** [comment]
yes here https://github.com/DATAHOARDERS/dynamic-rules/commit/4f51381c2d98690c25497079a1db5067feebe2df but 57 should still working

**Comment by JonathanJumper** [comment]
Bro, thank you sooo much, you gave me a looooot of light, I could resolve :respect:
I might contact you by email for futures inquiries if that's ok with you.

**Comment by ygetarts** [comment]
> yes here [DATAHOARDERS/dynamic-rules@4f51381](https://github.com/DATAHOARDERS/dynamic-rules/commit/4f51381c2d98690c25497079a1db5067feebe2df) but 57 should still working

hey on the off chance you'll see this, where do you get the values from? specifically, the static_param and the checksum_indexes?
