### ISSUE TITLE
It's supposed to look this this

### ISSUE THREAD

**Issue by s4b3rt0oth** [DIGITALCRIMINAL/OnlyFans#136]
It's supposed to look this this
![image](https://user-images.githubusercontent.com/21285176/71743522-ae0a4900-2e5c-11ea-8a1a-f20a56742daa.png)

_Originally posted by @DIGITALCRIMINAL in https://github.com/DIGITALCRIMINAL/OnlyFans/issues/116#issuecomment-570668412_

**Comment by s4b3rt0oth** [comment]
These values are missing from the master config.json. (auth_id and auth_hash)

**Comment by DIGITALCRIMINAL** [comment]
You need to update the program. I took auth_id and the hash out months ago

**Comment by s4b3rt0oth** [comment]
I pulled the latest program. The values are required to login but there is no information about them in the readme and they were taken out. This made it a bit confusing to use at first.

**Comment by DIGITALCRIMINAL** [comment]
The script doesn't even use auth_id or auth_hash. Just the sess token now.
