### ISSUE TITLE
Path to config files 

### ISSUE THREAD

**Issue by kevkov202** [DIGITALCRIMINAL/OnlyFans#137]
Due to the changes in the config path the script does not work under linux distributions anymore. Manually changing the line

`json_config = json.load(open('settings\\config.json'))`

to 

`json_config = json.load(open('settings/config.json'))`

in all modules/*.py files and StartDatascraper.py fixes the issue.

Using `os.path.join('settings', 'config.json')` instead of `'settings\\config.json'` might solve that problem

**Comment by DIGITALCRIMINAL** [comment]
What's your OS

**Comment by DIGITALCRIMINAL** [comment]
nvm, you said linux. thanks

**Comment by kevkov202** [comment]
I'm using Debian 10.3

**Comment by DIGITALCRIMINAL** [comment]
Added the commit, hopefully it works.
