### ISSUE TITLE
get this error on 7.4 when i run start_ofd.py

### ISSUE THREAD

**Issue by Fall0n** [DIGITALCRIMINAL/OnlyFans#1379]
Traceback (most recent call last):
  File "C:\Temp\OnlyFans DataScraper v7.4\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Chrille NUC\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Temp\OnlyFans DataScraper v7.4\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Temp\OnlyFans DataScraper v7.4\datascraper\main_datascraper.py", line 79, in start_datascraper
    main_helper.export_data(auth_details, user_auth_filepath)
  File "C:\Temp\OnlyFans DataScraper v7.4\helpers\main_helper.py", line 771, in export_data
    ujson.dump(metadata, outfile, indent=2, escape_forward_slashes=False)
TypeError: <apis.onlyfans.classes.extras.cookie_parser object at 0x000002BF03B55BE0> is not JSON serializable

**Comment by OFfriend** [comment]
your auth.json is broken. You can use https://jsonlint.com/ to test if auth.json is valid json.

**Comment by marinefl74** [comment]
FWIW, I have the same issue- or at least, very similar. To be clear it starts with an access error but this is the tail of it. And I've triple checked my auth.json and it appears accurate, far as I can tell. 

Traceback (most recent call last):
  File "C:\Users\scott\Downloads\OnlyFans-MASTER\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\scott\Downloads\OnlyFans-MASTER\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\scott\Downloads\OnlyFans-MASTER\datascraper\main_datascraper.py", line 79, in start_datascraper
    main_helper.export_data(auth_details, user_auth_filepath)
  File "C:\Users\scott\Downloads\OnlyFans-MASTER\helpers\main_helper.py", line 771, in export_data
    ujson.dump(metadata, outfile, indent=2, escape_forward_slashes=False)
TypeError: <apis.onlyfans.classes.extras.cookie_parser object at 0x0000021E49DA47F0> is not JSON serializable

**Comment by OFfriend** [comment]
you upgraded from 7.3 to 7.4?

**Comment by marinefl74** [comment]
I did a clean install actually. I still have the old version but if i shouldve upgraded that is on me. Due to issues in the past, I typically just pull down the new build, unzip it in a fresh directory, and configure accordingly(the auth.json). If there is a better way to do it i am happy to though.

**Comment by J4k-The-Reaper** [comment]
do you use the github app? i do and it makes it so much easier to stay up to date, it lets me know when to pull new commits. although i do not know if i still need to use the updater script or not when using the app.

**Comment by marinefl74** [comment]
I do not. Probably should. Tbh while I work in tech I'm not a dev so typically when I can get it to work I typically consider that a victory. Course that is also why I suck at troubleshooting my own issues. In this case, I'm not sure whether its my json file or that is just a red herring from the access denied I get prior to that snippet. I mean I pull the info right from the browser so I cant imagine its incorrect, unless, as I suspect, its something w my formatting.. but then I wouldnt think it would pass the muster with the json validator, haha, soooooo.

**Comment by OFfriend** [comment]
I think there is bug if you don't use 2FA.

**Comment by marinefl74** [comment]
I do use 2FA. I'm happy to post it here, maybe you'll see something I missed. I dont know the protocol since I just signed up for git so if for some reason I'm not supposed to or this is the wrong place to discuss my apologies. 

{
  "auth": {
    "username": "147****",
    "cookie": "auth_id=147****; sess=dn2ldnki253********; auth_hash=; auth_uniq_mQ6SLb4S5piiB0Le*********=; auth_uid_mQ6SLb4S5piiB0Le**********=;",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
    "email": "",
    "password": "",
    "hashed": false,
    "support_2fa": true,
    "active": true
  }
}

I just threw the asterisks on the end so I'm not broadcasting the info, not that I'm guessing it would do much. And prior to that trace I pasted above the only other output is the auth attempts x 10.

**Comment by OFfriend** [comment]
auth_uniq_mQ6SLb4S5piiB0Le looks wrong this should work:

``` JSON
{
	"auth": {
		"username": "147****",
		"cookie": "auth_id=147****; sess=dn2ldnki253********; auth_hash=; auth_uniq_147****=; auth_uid_147****=;",
		"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
		"email": "",
		"password": "",
		"hashed": false,
		"support_2fa": true,
		"active": true
	}
}
```

**Comment by Daironman78** [comment]
> I do use 2FA. I'm happy to post it here, maybe you'll see something I missed. I dont know the protocol since I just signed up for git so if for some reason I'm not supposed to or this is the wrong place to discuss my apologies.
> 
> {
> "auth": {
> "username": "147****",
> "cookie": "auth_id=147****; sess=dn2ldnki253********; auth_hash=; auth_uniq_mQ6SLb4S5piiB0Le*********=; auth_uid_mQ6SLb4S5piiB0Le**********=;",
> "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
> "email": "",
> "password": "",
> "hashed": false,
> "support_2fa": true,
> "active": true
> }
> }
> 
> I just threw the asterisks on the end so I'm not broadcasting the info, not that I'm guessing it would do much. And prior to that trace I pasted above the only other output is the auth attempts x 10.

Where do you locate your Auth Hash and Auth Uniq iD? I dont see anything like that in the cookies when you F12 in messages.

**Comment by Daironman78** [comment]
> I do use 2FA. I'm happy to post it here, maybe you'll see something I missed. I dont know the protocol since I just signed up for git so if for some reason I'm not supposed to or this is the wrong place to discuss my apologies.
> 
> {
> "auth": {
> "username": "147****",
> "cookie": "auth_id=147****; sess=dn2ldnki253********; auth_hash=; auth_uniq_mQ6SLb4S5piiB0Le*********=; auth_uid_mQ6SLb4S5piiB0Le**********=;",
> "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
> "email": "",
> "password": "",
> "hashed": false,
> "support_2fa": true,
> "active": true
> }
> }
> 
> I just threw the asterisks on the end so I'm not broadcasting the info, not that I'm guessing it would do much. And prior to that trace I pasted above the only other output is the auth attempts x 10.

Where do you locate your Auth Hash and Auth Uniq iD? I dont see anything like that in the cookies when you F12 in messages.

**Comment by marinefl74** [comment]
Apologies- I'm not sure where I got that from, frankly. I think i was somewhere else in the dev tools and just grabbed the wrong thing- I was kind of racing as I have family in the hospital so I was trying to get up and visit while I could. Now that I'm looking at it, I believe (key word- believe) I have the right info but its still blowing up so I'm at a loss, but I'll keep looking. And THANK YOU for trying to assist me I greatly appreciate it. 

At the risk of sounding ignorant- is there a way to debug this other than what I'm seeing it report back in console? If its too deep dont worry about it, as I said, I'm kind of learning as I go. This is what it looks like now but still doesnt want to work. I'm positive its just something i'm doing wrong(obviously) but cant seem to narrow down what:


{
	"auth": {
		"username": "1470***",
		"cookie": "auth_id=1470***; sess=dn2ldnki253iehmjg*******; auth_hash=7e82ddbc48372f0610306f969******; auth_uniq_1470***=; auth_uid_1470***=;",
		"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
		"email": "",
		"password": "",
		"hashed": false,
		"support_2fa": true,
		"active": true
	}
}

And again it passes the json validator so I'm thinking the traceback may be a red herring..

Traceback (most recent call last):
  File "C:\Users\scott\Downloads\OnlyFans-MASTER\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\scott\Downloads\OnlyFans-MASTER\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\scott\Downloads\OnlyFans-MASTER\datascraper\main_datascraper.py", line 79, in start_datascraper
    main_helper.export_data(auth_details, user_auth_filepath)
  File "C:\Users\scott\Downloads\OnlyFans-MASTER\helpers\main_helper.py", line 771, in export_data
    ujson.dump(metadata, outfile, indent=2, escape_forward_slashes=False)
TypeError: <apis.onlyfans.classes.extras.cookie_parser object at 0x00000234D4064640> is not JSON serializable

**Comment by DIGITALCRIMINAL** [comment]
I've fixed the traceback error in the latest commit. I think 2fa is broken, I need to fix it.

**Comment by marinefl74** [comment]
Clutch..latest commit works for me. Part of my issue also was the auth_hash. I've no idea its purpose, and i did see in the example its left blank, but since i saw it was present when perusing the contents of the cookie info, I dropped it in there. Apparently that not only isnt necessary but in my case, broke it. Works like a champ now. Much appreciated
