### ISSUE TITLE
auth_count error

### ISSUE THREAD

**Issue by mwald84** [DIGITALCRIMINAL/OnlyFans#138]
I'm getting this error after the update. Maybe a misconfiguration on my side but I can't find where.

File "c:\of\modules\onlyfans.py", line 468, in format_options
    names.append([x["auth_count"], name])
KeyError: 'auth_count'

Thanks in advance!

Mark

**Comment by mwald84** [comment]
The complete screen log in case it helps:

Auth (V1) Attempt 1/10
Welcome {my_username}
Traceback (most recent call last):
  File "StartDatascraper.py", line 95, in <module>
    subscription_array = x.format_options(subscription_array)
  File "c:\of\cb\grab_of2\modules\onlyfans.py", line 468, in format_options
    names.append([x["auth_count"], name])
KeyError: 'auth_count'

**Comment by mwald84** [comment]
The complete screen log in case it helps:

Auth (V1) Attempt 1/10
Welcome {my_username}
Traceback (most recent call last):
File "StartDatascraper.py", line 95, in
subscription_array = x.format_options(subscription_array)
File "c:\of\modules\onlyfans.py", line 468, in format_options
names.append([x["auth_count"], name])
KeyError: 'auth_count'

**Comment by DIGITALCRIMINAL** [comment]
Download latest commit

**Comment by mwald84** [comment]
the problem seems to be on array[0] which contains only {'username':'****'}

where **** is the first username on the list. That element of the array doesn't have auth_count as one of it's keys.

**Comment by mwald84** [comment]
This workaround seems to work for me (added after the 'for x in array' on line 465)

            if 'auth_count' not in x:
                x['auth_count'] = -1

**Comment by DIGITALCRIMINAL** [comment]
Do you have any subscriptions on your account

**Comment by mwald84** [comment]
I do. 2 subs.

**Comment by DIGITALCRIMINAL** [comment]
Oh, are you yourself a "performer"?

**Comment by DIGITALCRIMINAL** [comment]
I recreated the problem on my side. Going to fix it.

**Comment by DIGITALCRIMINAL** [comment]
I pushed a commit

**Comment by mwald84** [comment]
yes. I have content posted too. I just waw your commit mentioning it and that was the problem. It always likst my name with the ones I'm subbed to I now I understand why haha

Thank you!

**Comment by mwald84** [comment]
saw*
