### ISSUE TITLE
auth loop

### ISSUE THREAD

**Issue by stuffnstuffx** [DIGITALCRIMINAL/OnlyFans#139]
i have been using it without any issues and had actually used it about 2 hours ago, tried to use it now and it just keeps on looping on auth. looked over my cookies and they havent changed so im a bit lost. i deleted my cookies and restarted from scratch but still in loop

**Comment by DIGITALCRIMINAL** [comment]
Use latest release

**Comment by tychusfindlay** [comment]
im having the same exact issue
