### ISSUE TITLE
AttributeError: type object 'tqdm_asyncio' has no attribute 'gather'

### ISSUE THREAD

**Issue by jaysomm** [DIGITALCRIMINAL/OnlyFans#1391]
Hitting an error after successful authentication once the app goes to pull paid content or download posts.  Python, PIP, Homebrew, and all dependencies in requirements.txt are up to date. I've not encountered this issue before, and have spent a couple of hours trying to trace through and debug with no luck.

Any help is greatly appreciated!

Traceback (most recent call last):
  File "/Users/USERNAME/Desktop/OnlyFans/start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/USERNAME/Desktop/OnlyFans/start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/USERNAME/Desktop/OnlyFans/datascraper/main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/Users/USERNAME/Desktop/OnlyFans/modules/onlyfans.py", line 391, in paid_content_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
AttributeError: type object 'tqdm_asyncio' has no attribute 'gather'USERNAME

**Comment by DIGITALCRIMINAL** [comment]
Updated requirements? No you haven't.

**Comment by jaysomm** [comment]
I really think i have -- if there's something you think Im missing, i'd definitely appreciate the insight

thanks again!

UNAME@NAMEs-MBP-2 OnlyFans % pip3 install -r requirements.txt 
Requirement already satisfied: requests in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.25.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (4.9.3)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.26.2)
Requirement already satisfied: win32-setctime in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.0.3)
Requirement already satisfied: pysocks in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (5.8.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.8.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (4.6.2)
Requirement already satisfied: mergedeep in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (1.3.0)
Requirement already satisfied: jsonpickle in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (1.4.2)
Requirement already satisfied: ujson in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (4.0.1)
Requirement already satisfied: sqlalchemy==1.4.18 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (1.4.18)
Requirement already satisfied: alembic in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (1.5.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 14)) (4.55.1)
Requirement already satisfied: selenium in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (3.141.0)
Requirement already satisfied: selenium-wire==2.1.2 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 16)) (2.1.2)
Requirement already satisfied: user_agent in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 17)) (0.1.9)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 18)) (3.7.4.post0)
Requirement already satisfied: aiohttp_socks in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 19)) (0.6.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.9/site-packages (from sqlalchemy==1.4.18->-r requirements.txt (line 12)) (1.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests->-r requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/site-packages (from requests->-r requirements.txt (line 1)) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.1)
Requirement already satisfied: six>=1.5 in /Users/UNAME/Library/Python/3.9/lib/python/site-packages (from python-dateutil->-r requirements.txt (line 7)) (1.15.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.9/site-packages (from alembic->-r requirements.txt (line 13)) (1.1.4)
Requirement already satisfied: python-editor>=0.3 in /usr/local/lib/python3.9/site-packages (from alembic->-r requirements.txt (line 13)) (1.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/site-packages (from aiohttp->-r requirements.txt (line 18)) (1.6.3)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/site-packages (from aiohttp->-r requirements.txt (line 18)) (5.1.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.9/site-packages (from aiohttp->-r requirements.txt (line 18)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.9/site-packages (from aiohttp->-r requirements.txt (line 18)) (3.10.0.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/site-packages (from aiohttp->-r requirements.txt (line 18)) (21.2.0)
Requirement already satisfied: python-socks[asyncio]>=1.2.2 in /usr/local/lib/python3.9/site-packages (from aiohttp_socks->-r requirements.txt (line 19)) (1.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.9/site-packages (from Mako->alembic->-r requirements.txt (line 13)) (1.1.1)

@-MBP-2 OnlyFans % brew update && brew upgrade
Already up-to-date.@-MBP-2 OnlyFans % 

brew upgrade python3            
Warning: python3 3.9.5 already installed

**Comment by DIGITALCRIMINAL** [comment]
Read the read me
