### ISSUE TITLE
import tests.main_test as main_test

### ISSUE THREAD

**Issue by carcinojeneticist** [DIGITALCRIMINAL/OnlyFans#1392]
Not a coder so very sorry if this is an obvious thing.
I downloaded all of the requirements but whenever I try to run i get the error

'File "/Users/****/bin/start_ofd.py", line 7, in <module>
    import tests.main_test as main_test
ModuleNotFoundError: No module named 'tests''

Did I miss something?

**Comment by jp1151419** [comment]
Did you try a clean install?
Did you run requirements?

Looks like your install is incomplete for some reason.
