### ISSUE TITLE
Having trouble getting script to even work

### ISSUE THREAD

**Issue by vxbinaca** [DIGITALCRIMINAL/OnlyFans#1394]
Following the directions on your README, I run into a problem in two places:

1. The file to put the authentication data - where is that?
2. I've gotten the cookie output but when I paste it into VS code - which I think you're using (I'm more used to NVIM) it's not indented like in the example.

Help!

**Comment by newadventure079** [comment]
It's in the readme:

```
Open and edit:

.profiles/default/auth.json

[auth]

You have to fill in the following:

{"cookie":"your_cookie"}
{"user-agent":"your_user-agent"}
```

`.profiles` is a hidden folder.  Enable viewing hidden folders for your OS and you'll see the dir and files
