### ISSUE TITLE
[REQUEST] Exporting API's abilities

### ISSUE THREAD

**Issue by viperscode** [DIGITALCRIMINAL/OnlyFans#1399]
Hi there,

Absolute excellent work done on this, and thank you so much for making it open-source.

I want to use your project's API capabilities in a project of mine that scrapes OnlyFans creator profiles. I just need their bio, profile picture and other vital data. I tried using BS4 to scrape this but kept running into "We'll try your destination again in 15 seconds". I discovered in your closed issue here: #1078 that the headers must be specific and dived into your code but couldn't really figure out how to bypass their scraper detection. 

Could you point me towards which files I would need to reference in order to successfully start up a tool like BS4, and scrape profile info based on a link provided?

**Comment by LunarPenguin** [comment]
If you use the build-in API then there is no need to do the header signing yourself as this is already done by the script. It then is also not necessary to use something like BS4 because all user data can be retrieved via the API.

The only hurdle is that the API currently is experimental, largely undocumented and requires asyncio. but it is possible to use the API, i've done it myself for a couple scripts.

**Comment by viperscode** [comment]
> If you use the build-in API then there is no need to do the header signing yourself as this is already done by the script. It then is also not necessary to use something like BS4 because all user data can be retrieved via the API.
> 
> The only hurdle is that the API currently is experimental, largely undocumented and requires asyncio. but it is possible to use the API, i've done it myself for a couple scripts.

Thanks for your reply, it's a great note. I actually discovered last night that I could just use OF's profile API call. Thanks to Digital's work, I was able to take out the create headers function to generate the time stamp + SH1 sign required to grab data. Now I can just use the requests library and make a call. 

For the record, I doubt OF would ever document their API. They don't seem very open-source minded.

**Comment by DIGITALCRIMINAL** [comment]
> For the record, I doubt OF would ever document their API. They don't seem very open-source minded. 


They were talking about my OF API Wrapper
