### ISSUE TITLE
Script is not running anymore

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#14]
Hi, I'm getting this error

Traceback (most recent call last):
  File "OnlyFans.py", line 142, in <module>
    user_id = link_check(input_link)
  File "OnlyFans.py", line 38, in link_check
    temp_user_id = user_list.select('a[data-user]')
AttributeError: 'NoneType' object has no attribute 'select'

**Comment by DIGITALCRIMINAL** [comment]
Update to the latest version, it's been fixed c:

**Comment by dilemmax** [comment]
Sorry about that. I thought I have done that already. Thank you! It's working now
