### ISSUE TITLE
You're not subscribed to any users "im subscribed 7 users"

### ISSUE THREAD

**Issue by P0rr** [DIGITALCRIMINAL/OnlyFans#140]
C:\temp\OnlyFans DataScraper v3.7.1>StartDatascraper.py
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
You're not subscribed to any users.  "im subscribed 7 users"

Latest OnlyFans DataScraper  add all info that need in .json file

what have i done wrong this time..?

**Comment by DIGITALCRIMINAL** [comment]
Do you have 2FA on?

**Comment by P0rr** [comment]
I don't think it's on. And don't really understand where you mean by 2FA

**Comment by DIGITALCRIMINAL** [comment]
In your OF settings, there's a 2FA option.

When you run the program again, does it do another auth loop?

**Comment by P0rr** [comment]
It give me same error try 4 times.

**Comment by DIGITALCRIMINAL** [comment]
Have you updated your cookies?

**Comment by P0rr** [comment]
yes i have done that

**Comment by P0rr** [comment]
One thing I just noticed is that my sess changes frequently. Add it too the file run the program and ye i run debug get sess its new sess

**Comment by DIGITALCRIMINAL** [comment]
Hmm, so your user_agent is correct as well?

**Comment by P0rr** [comment]
yes user_agent is correct

**Comment by DIGITALCRIMINAL** [comment]
I was able to recreate the problem on my side, I'm going to fix it in a bit.

**Comment by DIGITALCRIMINAL** [comment]
I pushed a new commit

**Comment by lanzjose** [comment]
I have a similar problem :S
I entered my sess, app token, and user agent
i have no 2fa
After i click the option to scrape only fans it says
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
You're not subscribed to any users.

**Comment by DIGITALCRIMINAL** [comment]
Have you downloaded the latest commit?

**Comment by lanzjose** [comment]
oh! i don't know how to do that...
I'll do some research :) but thanks! maybe that's the reason

**Comment by DIGITALCRIMINAL** [comment]
You have to download the script again

**Comment by lanzjose** [comment]
ok, so i downloaded the script and configured the config.json 
it gave me this error... I tried filling the extra_auth with the proper information and didn't work...
I alsco copied those two files in the main directory where the datascraper is (i saw that recommendation) and didn't work

Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Traceback (most recent call last):
  File "C:\Users\Jose\Documents\GitHub\Onlyfans\OnlyFans\StartDatascraper.py", line 93, in <module>
    session = x.create_session(
  File "C:\Users\Jose\Documents\GitHub\Onlyfans\OnlyFans\modules\onlyfans.py", line 384, in create_session
    session.head("https://onlyfans.com")
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 568, in head
    return self.request('HEAD', url, **kwargs)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 452, in prepare_request
    p.prepare(
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 315, in prepare
    self.prepare_cookies(cookies)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 572, in prepare_cookies
    cookie_header = get_cookie_header(self._cookies, self)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\cookies.py", line 142, in get_cookie_header
    jar.add_cookie_header(r)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\http\cookiejar.py", line 1367, in add_cookie_header
    attrs = self._cookie_attrs(cookies)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\http\cookiejar.py", line 1326, in _cookie_attrs
    self.non_word_re.search(cookie.value) and version > 0):
TypeError: expected string or bytes-like object

**Comment by DIGITALCRIMINAL** [comment]
It's hard to find out what's happening because I'd need to see what it's trying to input

**Comment by lanzjose** [comment]
Well... What would you need? I think there's a similar report  on the issues tab btw...

**Comment by DIGITALCRIMINAL** [comment]
nvm, I installed linux and recreated the issue on my side

![image](https://user-images.githubusercontent.com/21285176/74475406-4acdf680-4e9f-11ea-9588-a0942e36b322.png)

**Comment by DIGITALCRIMINAL** [comment]
I fixed the issue hours ago, I just forgot to push the latest commit smh.

@P0rr lemme know if you can get messages

**Comment by P0rr** [comment]
I’m on a flight now. Can check when i in the hotel room. Hope that it works fine. Give replay when I have try

**Comment by MrKriegsmarine** [comment]
I'm getting this issue on Windows 10 using 3.7.2.
