### ISSUE TITLE
no media from messages is being downloaded

### ISSUE THREAD

**Issue by LootScooper** [DIGITALCRIMINAL/OnlyFans#141]
About a few days ago i downloaded a new version of your program when the login process was changed and i was no longer able to login. (cheers for updating your program so quick) But now i am unable to download media from messages. I am unsure if the media does not get scraped or if it has a problem downloading it. But it seems like it's not getting scraped.

**Comment by DIGITALCRIMINAL** [comment]
You downloaded the latest commit?

**Comment by LootScooper** [comment]
I redownloaded it about 6 hours ago

**Comment by DIGITALCRIMINAL** [comment]
I pushed 2 commits in the last two hours

**Comment by LootScooper** [comment]
alright i will give it a try and report back

**Comment by LootScooper** [comment]
I get this error:
```
Traceback (most recent call last):
  File "StartDatascraper.py", line 93, in <module>
    session = x.create_session(
  File "/home/philip/devel/OnlyFans/modules/onlyfans.py", line 385, in create_session
    session.head("https://onlyfans.com")
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 568, in head
    return self.request('HEAD', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 315, in prepare
    self.prepare_cookies(cookies)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 572, in prepare_cookies
    cookie_header = get_cookie_header(self._cookies, self)
  File "/usr/lib/python3.8/site-packages/requests/cookies.py", line 142, in get_cookie_header
    jar.add_cookie_header(r)
  File "/usr/lib/python3.8/http/cookiejar.py", line 1367, in add_cookie_header
    attrs = self._cookie_attrs(cookies)
  File "/usr/lib/python3.8/http/cookiejar.py", line 1326, in _cookie_attrs
    self.non_word_re.search(cookie.value) and version > 0):
TypeError: expected string or bytes-like object


^CTraceback (most recent call last):
  File "StartDatascraper.py", line 93, in <module>
    session = x.create_session(
  File "/home/philip/devel/OnlyFans/modules/onlyfans.py", line 385, in create_session
    session.head("https://onlyfans.com")
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 568, in head
    return self.request('HEAD', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 315, in prepare
    self.prepare_cookies(cookies)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 572, in prepare_cookies
    cookie_header = get_cookie_header(self._cookies, self)
  File "/usr/lib/python3.8/site-packages/requests/cookies.py", line 142, in get_cookie_header
    jar.add_cookie_header(r)
  File "/usr/lib/python3.8/http/cookiejar.py", line 1367, in add_cookie_header
    attrs = self._cookie_attrs(cookies)
  File "/usr/lib/python3.8/http/cookiejar.py", line 1326, in _cookie_attrs
    self.non_word_re.search(cookie.value) and version > 0):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "StartDatascraper.py", line 168, in <module>
    input()
KeyboardInterrupt
```
I think its because at line 382 you unpack the cookie dict in 'session.cookies.set'
```python
for auth_cookie in auth_cookies:
    session.cookies.set(**auth_cookie)
```
and if auth_cookie is {'name': 'sess', 'value': {'auth_id': 'my-id', 'auth_hash': 'my-auth-hash', 'sess': 'my sess'}}.  {'auth_id': 'my-id', 'auth_hash': 'my-auth-hash', 'sess': 'my sess'} will be passed to cookie.set which is a dict

**Comment by DIGITALCRIMINAL** [comment]
Oh are you using multiple auths?

**Comment by LootScooper** [comment]
nope

**Comment by DIGITALCRIMINAL** [comment]
Are you using the auth_id,_auth_hash and sess token to login?

**Comment by LootScooper** [comment]
yes and username

**Comment by LootScooper** [comment]
I am running it in Python 3.8.1 on Linux system.

**Comment by DIGITALCRIMINAL** [comment]
Going to try to install Ubuntu again on my VM...

**Comment by mwald84** [comment]
Since it's a similar problem, I'm posting this here. Let me know if you prefer I open a new topic.

To me, for a long time, it downloads only images from DMs. The videos only up to a specific one and it stops.

Today I tried a fresh install and redownloaded and it stops at the same video (no video after that one is downloaded).

One thing I noticed is that I have a tip message after that video. But I had tipped many times before and it didn't stop the media from being downloaded. All images download tho. The difference this time is that I tipped twice between the last video downloaded and the first that doesn't. There's only text and images between the 2 tip messages and the next video is after the second tip.

The video won't show even in the Videos.json file in the Metadata folder

I'm on Windows 10.

Since I get no error (the videos won't download silently) I can't track the problem,

I don't know if this info helps to track it.

**Comment by DIGITALCRIMINAL** [comment]
@mwald84 strange because it works for me. Hmm, I'll check if OF changed their message api again.

I also released a new commit.

**Comment by LootScooper** [comment]
With your new commit i am able to run the program now. But it still won't download media from messages. The new paid photos and videos send in messages won't show up while downloading. The program example reports "Downloading 4 Videos"  when in fact there are more videos.

**Comment by DIGITALCRIMINAL** [comment]
Do all of the message files appear in the metadata folder?

**Comment by LootScooper** [comment]
No it says there are only 4 posts present when there should be more.
And metadata is still being written when i have set it in the config to false. But i am glad that happened this time :)

**Comment by DIGITALCRIMINAL** [comment]
Oh ye, the metadata thing isn't active yet lmao. I put it there as a placeholder haha.

What's the username you're trying to scrape?

**Comment by LootScooper** [comment]
avadevine

**Comment by mwald84** [comment]
> With your new commit i am able to run the program now. But it still won't download media from messages. The new paid photos and videos send in messages won't show up while downloading. The program example reports "Downloading 4 Videos" when in fact there are more videos.

exactly what's happening here. Also the Image couter in regular posts is wrong for me (video is OK) On DMs is the opposite (images ok, videos less than the real number)

**Comment by DIGITALCRIMINAL** [comment]
dang, the only way to pretty much fix this is to use your auth creds to figure it out :/

**Comment by LootScooper** [comment]
I will see if i can take a look at the media_scraper() function tomorrow. Any pointers on where i should start looking?

**Comment by DIGITALCRIMINAL** [comment]
In onlyfans.py put "continue" on line 58

![image](https://user-images.githubusercontent.com/21285176/74510549-e68d5000-4efb-11ea-8b45-c1b2af6eabcd.png)


In onlyfans.py, put ```logger.info("Debug: {}".format(y["list"]))``` on line 289

![image](https://user-images.githubusercontent.com/21285176/74510281-5bac5580-4efb-11ea-8d0c-28c36d1b3efb.png)

After you've done this, run the script and when it's completed it's run send me the application.log via email

datahoarders@protonmail.com

![image](https://user-images.githubusercontent.com/21285176/74510661-28b69180-4efc-11ea-83c5-31a57ae099f4.png)

**Comment by LootScooper** [comment]
Hi i got the logs but my mail provider only allows attachments smaller then 2 mb and the log is 2.6. So i have to create a new mail

**Comment by DIGITALCRIMINAL** [comment]
I don't mind if you upload the text somewhere and email me the link

**Comment by LootScooper** [comment]
i used another mail account you should have it now.

**Comment by DIGITALCRIMINAL** [comment]
Thanks. Do you have a way of identifying the video that is missing? Like did the message come with a text

**Comment by LootScooper** [comment]
Not really i already looked in the page sources but it looked like they got there site pretty locked down. And i couldn't make any sense of the api. I was meaning to ask you how you enumerated their api because i am working on a scraper for a site which also have a 'secret' api.

**Comment by DIGITALCRIMINAL** [comment]
Could you send a screenshot of the video that's missing then?

**Comment by LootScooper** [comment]
Yeah but i will do it later today because i am at work and the video is nsfw.

**Comment by LootScooper** [comment]
Hi, I send you a mail with a screenshot but i also found out that the first time i looked over the page source i was a  bit to quick and didnt see the div's containing the messages. So i included those aswell.
If you need me to provide additional info lemme know.

**Comment by DIGITALCRIMINAL** [comment]
Did the email contain the exact missing video?

**Comment by DIGITALCRIMINAL** [comment]
Ye, I can't recreate it on my side. You're using the default filename format, right?

**Comment by LootScooper** [comment]
Yes

**Comment by DIGITALCRIMINAL** [comment]
Yeah, I have no idea then. The only way for me to figure it out is if you send me the auth cookies, you can debug the media_scraper and scrape_array functions to see why it isn't adding it in. Main one you should be looking in is scrape_array though.
