### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by headphonia** [DIGITALCRIMINAL/OnlyFans#1410]
I'm getting a traceback error in the latest commit

> Traceback (most recent call last):
>   File "/start_ofd.py", line 62, in <module>
>     loop.run_until_complete(main())
>   File "/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/start_ofd.py", line 46, in main
>     api = await main_datascraper.start_datascraper(
>   File "/datascraper/main_datascraper.py", line 90, in start_datascraper
>     await module.paid_content_scraper(api, identifiers)
>   File "/modules/onlyfans.py", line 394, in paid_content_scraper
>     unrefined_set = await tqdm.gather(tasks, **settings)
> AttributeError: type object 'tqdm_asyncio' has no attribute 'gather'

**Comment by DIGITALCRIMINAL** [comment]
Update requirements.

**Comment by headphonia** [comment]
upgraded requirements, still getting the error.
