### ISSUE TITLE
Auth 404'd

### ISSUE THREAD

**Issue by nappyapp** [DIGITALCRIMINAL/OnlyFans#1413]
When I try to login I'm getting an error "Auth 404'd". I haven't seen this one before, it has a different error normally when I have the credentials wrong. What's this 404 about?

![image](https://user-images.githubusercontent.com/79231864/123710452-ac3bfe80-d823-11eb-8be7-c2af7d5439bc.png)

**Comment by DIGITALCRIMINAL** [comment]
Try the website

**Comment by nappyapp** [comment]
I’m able to login on the website. I’m using the correct auth_id and sess cookie parameters and user agent string. The auth_hash, auth_uniq_37776674, and auth_uid_37776674 parameters are unset, as are the email and password.

I’ve never set the email and password before and it hasn’t been an issue. I just tried setting them and I’m still getting “auth 404’d” as in the pic above

**Comment by nappyapp** [comment]
I found the issue: for some reason when the script changed the format of the cookie parameters, it appended 37776674 to those couple parameter names, I did not do that myself. I started a fresh copy of the script and the parameters do not have the number in the names, and it is now working.

**Comment by DIGITALCRIMINAL** [comment]
The number is your account id

**Comment by nappyapp** [comment]
Thanks, do you know why the script modified the profile file and appended
the number to those parameters? I did not make that change myself, so I
suspect there's a bug in the profile auth json file upgrade code

**Comment by DIGITALCRIMINAL** [comment]
There's no bug.
