### ISSUE TITLE
enhancement: add setting for default scrape option

### ISSUE THREAD

**Issue by LootScooper** [DIGITALCRIMINAL/OnlyFans#142]
I know there is a setting for automatically scraping all accounts. But then you still have to press 'a' every time to select all media types to be scraped. It would be nice if there was a setting so i where i can put "Everything" ,"Images", "videos" or "audios". So i don't have to press a 50 times if i want to make a "backup"

**Comment by DIGITALCRIMINAL** [comment]
Search "auto_choice" on the readme

**Comment by LootScooper** [comment]
ah i was putting true or false in there

**Comment by Eviepayne** [comment]
I feel like I might be retarded. I'm putting in 0 for all, I've also tried all but keep getting invalid choice.
Am I doing something wrong?
![image](https://user-images.githubusercontent.com/59463208/118566612-3469b700-b742-11eb-8423-6a60b16de147.png)

**Comment by Eviepayne** [comment]
nvm figured it. am retarded. string is not an int.
