### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by betoalanis** [DIGITALCRIMINAL/OnlyFans#1420]
I was scraping without problem yesterday, today I started to scrape TWO profiles, one downloaded correctly and the second one showed an error (can't remember the error), but as any other time an error happens I update the script and try again, well after updating and running the requirements, I get this error:

```

Traceback (most recent call last):
  File "/Users/beto/Application Tools/OnlyFans-master/start_ofd.py", line 9, in <module>
    main_test.check_config()
  File "/Users/beto/Application Tools/OnlyFans-master/tests/main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "/Users/beto/Application Tools/OnlyFans-master/helpers/main_helper.py", line 1, in <module>
    from database.models.media_table import media_table
  File "/Users/beto/Application Tools/OnlyFans-master/database/models/media_table.py", line 5, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'
```

Tried reverting the update, running it again, deleting config, double checking auth (I know it has nothing to do with auth) but I've tried everything I can think of, and can't get past this error, I was on Python 3.9.2 and saw some other issues where they recommend updating to 3.9.5 and that's where I'm at

**Comment by falbuixech** [comment]
I'm getting the same error

**Comment by PsychoSid** [comment]
You might to run:-

```
pip install --upgrade --user -r requirements.txt
```

After a code update.

**Comment by betoalanis** [comment]
> You might to run:-
> 
> ```
> pip install --upgrade --user -r requirements.txt
> ```
> 
> After a code update. Keep an eye out if that file changes it's a good indicator.

It's been done, the error is still present.

**Comment by MyPersonalKov** [comment]
I had this issue (#1422) , but then I ran the upgrade command for pip and it resolved it.  Now, it can't import from sqlalchemy.

**Comment by betoalanis** [comment]
BUMP

Still happening, I have updated the script and requirements several times during last month, nothing changes.

**Comment by Eviepayne** [comment]
run the following in order:
```
pip uninstall -r requirements.txt
pip uninstall --user -r requirements.txt
pip install --user -r requirements.txt
```

**Comment by betoalanis** [comment]
> run the following in order:
> 
> ```
> pip uninstall -r requirements.txt
> pip uninstall --user -r requirements.txt
> pip install --user -r requirements.txt
> ```

This showed me a bunch of errors when trying to uninstall on the first command, and said "no command --user" on the second. But instead of pip, I used "pip3" on all  (second one still shows no "--user") and now the script is working again, thanks!!! 

`pip3 uninstall -r requirements.txt
pip3 uninstall --user -r requirements.txt
pip3 install --user -r requirements.txt`
