### ISSUE TITLE
Download avatar/header for user you don't follow.

### ISSUE THREAD

**Issue by Zachary24** [DIGITALCRIMINAL/OnlyFans#1421]
Is there any way it can be implemented so that you can download the high res avatar + header without following someone? Theres a user who never posted anything but has profile pictures set that i'd like to get. try'd looking at the source code but couldn't find out how it retrieves the high res copies.

edit: saw https://github.com/DIGITALCRIMINAL/OnlyFans/issues/339 but assumed the api returned a json file not response I did find the url scheme, would still be a nice implementation.

**Comment by DIGITALCRIMINAL** [comment]
You need to follow them
