### ISSUE TITLE
progress bar is broken

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINAL/OnlyFans#1425]
![Screenshot (1)](https://user-images.githubusercontent.com/22129443/123908426-1b853000-d995-11eb-8090-eaf857a74fd8.png)
looks like a new line is being added every time the progress bar refreshes

**Comment by DIGITALCRIMINAL** [comment]
Are you using a proxy?

**Comment by alectprasad** [comment]
no

why would that affect this

**Comment by nappyapp** [comment]
Try running it in PowerShell?
