### ISSUE TITLE
Traceback error: Bad Magic Number

### ISSUE THREAD

**Issue by ricguy91** [DIGITALCRIMINAL/OnlyFans#1435]
Just pulled the latest, did both "pip install -r requirements.txt" and "pip install --upgrade --user -r requirements.txt" and I'm still getting the following error:

```
Traceback (most recent call last):
  File "Z:\OnlyFans\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "Z:\OnlyFans\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
ImportError: bad magic number in 'helpers': b'\x03\xf3\r\n'
```

**Comment by DIGITALCRIMINAL** [comment]
https://stackoverflow.com/questions/514371/whats-the-bad-magic-number-error

**Comment by ricguy91** [comment]
Blowing away the .pyc files dealt with the issue.  Thanks!
