### ISSUE TITLE
ValueError: Trailing data

### ISSUE THREAD

**Issue by Abhi-9758** [DIGITALCRIMINAL/OnlyFans#1442]
I am getting this error:

Traceback (most recent call last):
  File "/home/linuxuser/OnlyFans/start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/home/linuxuser/OnlyFans/datascraper/main_datascraper.py", line 60, in start_datascraper
    api = main_helper.process_profiles(
  File "/home/linuxuser/OnlyFans/helpers/main_helper.py", line 598, in process_profiles
    temp_json_auth = ujson.load(
ValueError: Trailing data

how do i fix this?

**Comment by DIGITALCRIMINAL** [comment]
delete config.

**Comment by Abhi-9758** [comment]
Are you talking about config.json from .setting foler? If so, I deleted config file. But when i started the program, it created config file again and i got the same error.
Do i need to edit something in config.json?

**Comment by Abhi-9758** [comment]
> delete config.
Are you talking about config.json from .setting foler? If so, I deleted config file. But when i started the program, it created config file again and i got the same error.
Do i need to edit something in config.json?

**Comment by Abhi-9758** [comment]
> delete config.

Are you talking about config.json from .setting foler? If so, I deleted config file. But when i started the program, it created config file again and i got the same error.
Do i need to edit something in config.json?

**Comment by DIGITALCRIMINAL** [comment]
You didn't change anything in the config?

**Comment by DIGITALCRIMINAL** [comment]
Which OS are you using?

**Comment by Abhi-9758** [comment]
> You didn't change anything in the config?
> Which OS are you using?

I am using Kali Linux. I am new so I don't know much.

**Comment by Abhi-9758** [comment]
> You didn't change anything in the config?

I didn't change anything.
