### ISSUE TITLE
Resource Exhaustion Diagnosis Events

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#1458]
Would it be possible to limit the amount of RAM the process wants to use? 

I've never used the Max Threads setting since I run it in a VM that pretty much only does that but the last couple runs I did of 100+ accounts led to the system crashing while I was gone. The last event registers that it was using 32GB of system memory and that led to a full crash&reboot.

edit: having it as a "low priority task" would also work, all I'd like is for it to not lock the system due to memory consumption

**Comment by DIGITALCRIMINAL** [comment]
Latest version of the script doesn't use any RAM. It downloads content and removes the T from the RAM.

**Comment by jp1151419** [comment]
So would that just mean that the download batch it was attempting when Windows crashed was too big for the available virtual memory? What determines the batches that gets moved to and from RAM? Is it on a account base or ?

**Comment by DIGITALCRIMINAL** [comment]
The script might have gone into an infinite loop whilst downloading

**Comment by jp1151419** [comment]
Ok, I'll see if it happens again. In the meantime I'm back to doing partial scrapes using [this site](https://rechneronline.de/number-list/) to generate intervals of accounts to scrape so as not to do the 500 I have. Less risk of errors or timeouts this way tbh

**Comment by DIGITALCRIMINAL** [comment]
How many threads does your PC have?

I've got 32 with 80GB RAM and OnlyFans limits files to 3GB, so the script would have to download 27 3 GB files at the same time for me to run out of RAM which would be hard to do.

**Comment by jp1151419** [comment]
That VM runs 6 cores/threads and currently has 24GB allocated since it had crashed with 16GB.

**Comment by americanseeder1865** [comment]
Memory allocation is done when the Python Interpreter allocates it. The program is more complex. I will look into it. I have wondered why RAM usage has been higher.
