### ISSUE TITLE
File Download Resume.

### ISSUE THREAD

**Issue by clem16** [DIGITALCRIMINAL/OnlyFans#1459]
Quick question, is there any kind of stalled download resume function? Or partial download handling? Or file checksum of any kind?
I'm finding sometimes my downloads are hanging - partly due to flaky internet, and I've noticed a few videos that start downloading don't actually complete - the ends get cut off where the download crashed.

**Comment by DIGITALCRIMINAL** [comment]
Are you using a proxy

**Comment by clem16** [comment]
> Are you using a proxy

No, I am not using any kind of proxy, tunnel, or VPN, should I be? I could.

I have tried from multiple different computers, on multiple different networks. On different operating systems. Windows 10, and FreeBSD. Same results.

**Comment by clem16** [comment]
Seems to be working now strangely. Interesting. I'll open this if it acts up again.
