### ISSUE TITLE
text_length - Not Working ?

### ISSUE THREAD

**Issue by GreyBeardy** [DIGITALCRIMINAL/OnlyFans#146]
Hi.

I have my config as below. I end up with many many overlong filenames and they cause so many problems.
Any idea why the text / title is not limited at 50 ?

Would it be possible, in the future, to add a feature to filter / remove chars like "#! etc.?

"file_name_format": "{date} - {text}.{ext}",
 "text_length": "50",

I still end up with something like this
`2017-04-11-When a friend told me she had a cousin coming to town I volunteered to play tour guide.   When your a hot young guy the proper LA experience is a double BJ!  He didn't last long nor did he hold the camera steady regardless WELCOM.mp4`

**Comment by DIGITALCRIMINAL** [comment]
Are you using the most recent version?

**Comment by GreyBeardy** [comment]
I used 3.7.1 just now.

It didnt work for a while now so thought i would ask. I will upgrade to the 3.7.2 and see what happens.

**Comment by DIGITALCRIMINAL** [comment]
I disabled it a couple of versions ago due to it only causing problems. I'll see what I can do now with it...

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit. Just noticed my script says if you have long paths enabled, it will always max out the filename. I'll change this soon.

**Comment by GreyBeardy** [comment]
just tried 3.7.2 but it still gives me some very long filenames when using text.

I also tried limiting the max length to 140 chars instead of 240 but that dont help.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, if you have long paths enabled, the script doesn't input the text length. I need to fix it.

**Comment by DIGITALCRIMINAL** [comment]
Nice the latest commit, not the release

**Comment by GreyBeardy** [comment]
python not at all my strong side.

i am struggling finding out how to use the latest commit. I normally just download the release.

**Comment by DIGITALCRIMINAL** [comment]
> python not at all my strong side.
> 
> i am struggling finding out how to use the latest commit. I normally just download the release.

![image](https://user-images.githubusercontent.com/21285176/74595832-7c30f880-503e-11ea-85c0-e82f2ea4b09c.png)

**Comment by GreyBeardy** [comment]
```
I run into this error now. Is that at my end? .. wasnt there before.

Type: Posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "D:\sites\OnlyFans-master\StartDatascraper.py", line 147, in <module>
    result = x.start_datascraper(
  File "D:\sites\OnlyFans-master\modules\onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "D:\sites\OnlyFans-master\modules\onlyfans.py", line 305, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\sites\OnlyFans-master\modules\onlyfans.py", line 249, in scrape_array
    file_path = reformat(directory[0][1], file_name,
  File "D:\sites\OnlyFans-master\modules\helpers.py", line 41, in reformat
    text = BeautifulSoup(text, 'lxml').get_text().replace(
  File "C:\Program Files\Python38\lib\site-packages\bs4\__init__.py", line 213, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by DIGITALCRIMINAL** [comment]
enter in cmd

> pip install lxml

**Comment by GreyBeardy** [comment]
works .. and text is now limited to config.json setting .. :)

filenames now have _ in all spaces and i think most chars and smilies etc are gone.

**Comment by GreyBeardy** [comment]
I have noticed other scripts must be out there. I often see this kind of filename ..

The number after the date seems random but not sure and the resolution is at the end somehow also.

Text is the only way to get a decent title for the content as the filenames are just gibberish.
```
8-10-13 2202517 Took a shower went outside and a huge thunderstorms roaring!! First rain in(..) 720x1280.mp4 
-- | --
18-10-13 2205075 Good morning, need coffee asap! Still raining here so think Ill take advan(..) 720x1280.mp4
18-10-13 2205625 Groceries and coffee run and now Im ready to snuggle up to watch a movie.(..) 720x1280.mp4 
```
