### ISSUE TITLE
Sorting content by post

### ISSUE THREAD

**Issue by Addest3** [DIGITALCRIMINAL/OnlyFans#148]
I would like to suggest the ability to sort the content by post either by automatic folder creation or automatic renaming such as Post1(01).png etc. Additionally, it seems like a lot of the time the pictures are out of chronological order which makes it even more difficult to sort by post. The reason for this being that a lot of models release pictures in sets that are meant to go together.

**Comment by DIGITALCRIMINAL** [comment]
Right now it's sorted by date creation

**Comment by Addest3** [comment]
Date creation meaning the date the photo/video was taken IE: Metadata or meaning the post date on Onlyfans/4chan etc.

**Comment by DIGITALCRIMINAL** [comment]
Post date (Date uploaded to site)

**Comment by Addest3** [comment]
I see, so maybe this is a bug report then because three times now I have downloaded content and it is out of post date order. Ill do another and look at the exact behavior.

**Comment by DIGITALCRIMINAL** [comment]
What's your OS?

**Comment by Addest3** [comment]
10 Home Build 17763

I just scraped two more pages from Onlyfans and the behavior wasn't repeated. Additionally the older folders of files now resort properly. Not too sure why that was. I would still like to keep the suggestion intact though as it could be helpful.

Also I did just notice that it isn't able to scrape slideshow content on Onlyfans, I'll make a separate issue for that.
