### ISSUE TITLE
Unable to retrieve slideshow/story content from OF.

### ISSUE THREAD

**Issue by Addest3** [DIGITALCRIMINAL/OnlyFans#149]
Onlyfans slideshow/story content isn't being detected by the program as far as I can tell. 

Using v. 3.7.2

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/72

Linking the old similar issue I found here for convenience.

**Comment by DIGITALCRIMINAL** [comment]
Story or their archived stories?

**Comment by Addest3** [comment]
Im not sure. The story in question is from June 2019 so I assume archived..

**Comment by DIGITALCRIMINAL** [comment]
Oh yeah, I've only done timeline stories so far. I forgot to do archived stories.

What's the username you're trying to rip?

**Comment by Addest3** [comment]
I will pm it to you.

**Comment by Addest3** [comment]
Lets go with https://onlyfans.com/lilithrosexxx/

**Comment by DIGITALCRIMINAL** [comment]
Kk thanks, you can delete it if you want.

**Comment by Addest3** [comment]
She has one currently as far as I can tell. 8 images total.

**Comment by DIGITALCRIMINAL** [comment]
Added.
