### ISSUE TITLE
auth not working anymore

### ISSUE THREAD

**Issue by DursyArts** [DIGITALCRIMINAL/OnlyFans#1499]
Auth with the cookie doesnt work anymore, it just logs you out on site and gives Access Denied message.

**Comment by DIGITALCRIMINAL** [comment]
Then you're doing something wrong

**Comment by yenoromm** [comment]
I wouldn't discount this just yet. I have been using this for more than a year, been through many revisions. Using on Linux and Mac across several accounts. Firefox 90.0 seems to have caused me issues with the latest revisions, spinning up 89.0 resolved this or swapping to Chrome to generate the credentials resolved this one. Previously "Access Denied" was the only symptom, this error also logs me out like OP.

**Comment by DursyArts** [comment]
Exactly what I tried to say, I found that when you use the cookie in combination with the account details you're logged in with it works again. So just fill email and password too, and it should work
