### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#15]
Do you think you will write a script to pull media from justfor.fans accounts?

**Comment by DIGITALCRIMINAL** [comment]
If you're able to provide an account, that I can to pull paid content off. Sure I can do all the scripts you want me too haha

**Comment by DIGITALCRIMINAL** [comment]
This is my email @avekifes 
If you have any sensitive information on your account remove it before sending me the credentials.
rarecoder@protonmail.com

**Comment by dilemmax** [comment]
hey @avekifes which site are you giving? Justfor.fans?
