### ISSUE TITLE
Silly question but does the metadata folder contain my personal information at all?

### ISSUE THREAD

**Issue by left1000** [DIGITALCRIMINAL/OnlyFans#1502]
Silly question but does the metadata folder contain my personal information at all? Like if I send someone my rip folder, will they be able to steal my onlyfans account?

specifically like 
this file 
user_data.db

in the Metadata folder?

**Comment by DIGITALCRIMINAL** [comment]
The only way someone can hijack your account is if you expose your auth.json file.

user_data contains identifiable information about your account so it's generally best to keep hidden.
