### ISSUE TITLE
Nothing happens after running?

### ISSUE THREAD

**Issue by Chayni** [DIGITALCRIMINAL/OnlyFans#1513]
so yea after running start_ofd nothing happens?
![ea7b40bfda98b58faf781376e6f607cb](https://user-images.githubusercontent.com/22572495/127311602-22ee11b8-57ff-4565-8586-8d72bf03b85f.png)

**Comment by LunarPenguin** [comment]
please provide some more information:
- Which python version are you running and do you have one or multiple python installation installed
- Which version of the script are you running
- what happens if you input `0` in the window shown above and hit <kbd>Enter</kbd>

**Comment by Chayni** [comment]
> please provide some more information:
> 
> * Which python version are you running and do you have one or multiple python installation installed
> * Which version of the script are you running
> * what happens if you input `0` in the window shown above and hit Enter

How do I check both versions?
And regarding inputting 0, this is what happens:
![10ec9e49f663c2c34572c6af3cab00f9](https://user-images.githubusercontent.com/22572495/127321696-a2decfd2-aa8c-4ef5-8f5b-5940bb417805.png)

**Comment by LunarPenguin** [comment]
> How do I check both versions?

For python you could check your installed programs under the control panel or you could try running `py -0` in a cmd or powershell window

for the version of the script, when did you download the script and how did you download it?

> And regarding inputting 0, this is what happens:

check if your auth.json file is valid json by using [this](https://jsonlint.com/) website

**Comment by whiteprivilege** [comment]
I'm having similar issue. 
Downloaded to zip.
Extracted 
cd'd into dir
Python 3.9
`python3.9 start_ofd.py` to start script
`auth.json` is filled out properly.
Installed all requirements from requirements.txt
similar outcome as above.
![0M5D4x2p](https://user-images.githubusercontent.com/85398870/127463784-79befbab-4b11-4fd1-baf0-1ae90742962b.png)

**Comment by LunarPenguin** [comment]
> I'm having similar issue.

It seems its having problems upgrading the legacy cookie format.

Could you provide a redacted example of the cookies in your `auth.json` file?

**Comment by whiteprivilege** [comment]
`{
  "auth": {
    "username": "default",
    "cookie": "auth_id=NOPE; sess=NOPE; auth_hash=; auth_uniq_122194429=; auth_uid_122194429=;",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
    "email": "",
    "password": "",
    "hashed": false,
    "support_2fa": true,
    "active": true
  }
}`

**Comment by whiteprivilege** [comment]
Also
on the init req
my cookie looks like the following
`sess=************; auth_id=*****; expires=Sun, 08-Aug-2021 09:21:40 GMT; Max-Age=864000; path=/; domain=.onlyfans.com; secure; HttpOnly`
But  I do not have any of the other required items such as `auth_hash=; auth_uniq_122194429=; auth_uid_122194429=;`

**Comment by whiteprivilege** [comment]
SOLVED.
I just logged in again got a new session and it seems to be working now. I guess the sess was just expired. Thanks anyways @LunarPenguin

**Comment by LunarPenguin** [comment]
> Thanks anyways

No problem. please close the issue if your done.

**Comment by Chayni** [comment]
> > Thanks anyways
> 
> No problem. please close the issue if your done.

dude literally took over my issue thread lmao
anyway, regarding your first reply, python version is 3.9
about the json file, I ran it in the website (auth.json) and it seems theres a problem with my user agent row? which is weird since I just copy pasted mine from the website

**Comment by LunarPenguin** [comment]
> dude literally took over my issue thread lmao

My sincere apologies, i was answering this issue in between other work and totally forgot he was not the OP.

But i am glad your problem is fixed as well

**Comment by Chayni** [comment]
> > dude literally took over my issue thread lmao
> 
> My sincere apologies, i was answering this issue in between other work and totally forgot he was not the OP.
> 
> But i am glad your problem is fixed as well

Thanks for helping :)
