### ISSUE TITLE
change download directory so Plex can see files

### ISSUE THREAD

**Issue by J4k-The-Reaper** [DIGITALCRIMINAL/OnlyFans#1522]
i know this might sound confusing....so i use the github app... and PLEX. but plex is not able to see the .sites folder. is there a way to change the download folder to sites, basically remove the period? i tried it but github makes it seem like i made changes to the repository. as long as i keep the period, nothing is changed.

**Comment by LunarPenguin** [comment]
You can specify which folder the script should store the media and metadata files in using the `dowload_directories` and the `metadata_directories` settings. i have mine configured as follows: 
```json
"download_directories": [
	"R://httrack//OF"
],
"file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
"filename_format": "{filename}.{ext}",
"metadata_directories": [
	"R://httrack//OF"
],
"metadata_directory_format": "{site_name}\\{model_username}\\Metadata"
```

**Comment by J4k-The-Reaper** [comment]
> You can specify which folder the script should store the media and metadata files in using the `dowload_directories` and the `metadata_directories` settings. i have mine configured as follows: 
> ```json
> "download_directories": [
> 	"R://httrack//OF"
> ],
> "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
> "filename_format": "{filename}.{ext}",
> "metadata_directories": [
> 	"R://httrack//OF"
> ],
> "metadata_directory_format": "{site_name}\\{model_username}\\Metadata"
> ```

I did that. Had to use the back slashes tho. Plus it runs extra slow now. Wonder why.

**Comment by LunarPenguin** [comment]
> Had to use the back slashes tho. Plus it runs extra slow now. Wonder why.

I guess the use of slashes differs for the OS you're running.

I have not noticed any significant slow down using an external folder. Maybe something to do with read/write throughput?

Where do you notice the script being slower and how much slower do you notice it being? If it is something wrong with the script maybe @DIGITALCRIMINAL can see if he can fix it.

**Comment by J4k-The-Reaper** [comment]
> > Had to use the back slashes tho. Plus it runs extra slow now. Wonder why.
> 
> I guess the use of slashes differs for the OS you're running.
> 
> I have not noticed any significant slow down using an external folder. Maybe something to do with read/write throughput?
> 
> Where do you notice the script being slower and how much slower do you notice it being? If it is something wrong with the script maybe @DIGITALCRIMINAL can see if he can fix it.

Nevermind I was fibbing. Lol. I think it needed to do it a couple times to register new location. Works great now. Now plex will be able to stream.

**Comment by LunarPenguin** [comment]
> Nevermind I was fibbing. Lol. I think it needed to do it a couple times to register new location. Works great now. Now plex will be able to stream.

That's nice to hear, please close the issue if you're done.
