### ISSUE TITLE
list indices must be integers or slices, not str ( Access Denied error)

### ISSUE THREAD

**Issue by bonmat22** [DIGITALCRIMINAL/OnlyFans#1523]
![Error](https://user-images.githubusercontent.com/88319034/127844172-f972b07d-dbbc-4195-adec-4cb5fce43ce8.png)

I kept getting this error those im pretty sure i filled out the Auth file correctly, I filled our sess, id and things like that but i am still getting the same error, i tried switch browser and using new sess but it doesnt work either, I tried filling the email and pass but still doesnt work, this is probably because i used twitter to login. Is there any suggestio to fix this? Thank you

**Comment by bonmat22** [comment]
So after a few tries, it kinda worked with MS Edge then i saw it started the scraping process but somehow i got another type of error like in this screenshot. Can anybody explain this?
![error2](https://user-images.githubusercontent.com/88319034/127847652-2d96fbe6-bc38-4385-bacc-3c226de7f479.png)

**Comment by FeelsBadMan1** [comment]
how you get this to work in the first place? somehow it detect usernames on your side. for me it act dumb and only give out access denied even tho i enterd the correct cookies, username & useragent:
![grafik](https://user-images.githubusercontent.com/40109798/127872042-94b8cbd7-e369-4ce5-aca9-8361980826e8.png)

**Comment by FeelsBadMan1** [comment]
used google to login

**Comment by DIGITALCRIMINAL** [comment]
>  used google to login - using email to login makes no difference
> 

Have you tried using the ligma method to auth?

**Comment by LunarPenguin** [comment]
> Can anybody explain this?

Your error references the `tqdm` progress bar library.

The `tqdm` library recently updated and changed the way a command worked (see:#1521) i would suggest upgrading your installation of `tqdm` to the new version in the `requirements.txt` file and upgrade the script to the latest version / commit

**Comment by FeelsBadMan1** [comment]
> 
> 
> > used google to login - using email to login makes no difference
> 
> Have you tried using the ligma method to auth?

what do you mean by "ligma method"? i tried cookies, username, useragent, email & pass
