### ISSUE TITLE
TypeError: gather(), DataScraper Tries to DL Free account I'm no longer subbed to

### ISSUE THREAD

**Issue by ChristopherHoef** [DIGITALCRIMINAL/OnlyFans#1527]
I keep coming across this same error message whenever I try running the Datascraper using my account:
![image](https://user-images.githubusercontent.com/68175712/128069636-fbc1c473-9af8-451f-a6bc-423144e17ae8.png)

This always comes up after getting the "Scraping Paid Content" output and then having it go through all of the models I'm subscribed to, both paid and free. The weird thing about this is that I always get this error message immediately after the program attempts to scrape data from a Free account that I used to be subscribed to and bought some pay-to-view content from but am not subbed to anymore. Another strange thing is that the program attempts to scrape data from this account whether I enter "paid" or "free" under the "ignore_type" designation on the config file or if I leave this field blank between the quotes. 

Any ideas on how to fix this? In any case, it's an issue I ran into that I wanted to bring up.

Thank you

**Comment by LunarPenguin** [comment]
- Regarding the error in the screenshot: update the script to the latest version and update to the new version of `tqdm` specified in the `requirements.txt` file
- regarding the downloading of paid content: paid content is always available regardless of subscription status. by default the script will try to download paid content first and then switch over to regular scraping. this can be disabled by setting the `scrape_paid_content` setting to `false` under the `jobs` header in the `config.json` file
- As far as i know and the `readme.md` seems to agree with me the `ignore_type` only works with regular model scraping and not paid content scraping.

**Comment by ChristopherHoef** [comment]
LunarPenguin
Thank you! This appears to have fixed the issue. You can close this thread!
