### ISSUE TITLE
Import not resolve

### ISSUE THREAD

**Issue by mhbosch** [DIGITALCRIMINAL/OnlyFans#1549]
Hello,

i use Python 3.9.6 and have a problem.
 The importlink in the main_test are not working.
I become from the compiler (and VC) the error:

```
Traceback (most recent call last):
  File "C:\Users\posts\Documents\OnlyFans-master\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Users\posts\Documents\OnlyFans-master\tests\main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "C:\Users\posts\Documents\OnlyFans-master\helpers\main_helper.py", line 805, in get_config
    json_config = ujson.load(open(config_path))
ValueError: Expected object or value
```

VC:
```
Import "helpers.main_helper" could not be resolved
Import "helpers.main_helper" could not be resolved
Import "apis.onlyfans.onlyfans" could not be resolved

```

i have tried a
import ..helpers from 
but it dosnt work.

I dont know the solution to import.

**Comment by LunarPenguin** [comment]
This seems to be a problem on your side. please make sure the `config.json` is valid json and you have filled in the options correctly. we can not help you with import errors on your side.

Maybe you can provide us with a full log of what is happening, at the moment the error occurs.

**Comment by mhbosch** [comment]
Thanks for you reply. i have solve it.
It was a problem with the PIP. I uninstall und reinstall all modules and after them, the script will start.

**Comment by LunarPenguin** [comment]
> Thanks for you reply. i have solve it.

That's nice to hear, please close the issue when your done
