### ISSUE TITLE
Auth Loop Plz Help

### ISSUE THREAD

**Issue by ReffyVFX** [DIGITALCRIMINAL/OnlyFans#155]
Everything is updated and my config is filled out including the user agent. I also deleted the cookies to see if that worked but nothing.. plz help
![Capture  3](https://user-images.githubusercontent.com/58599736/75122718-3986a600-5666-11ea-92ff-e376098ead92.JPG)

**Comment by DIGITALCRIMINAL** [comment]
Do you have 2Auth on?

**Comment by ReffyVFX** [comment]
no

**Comment by Telandriq** [comment]
@ReffyVFX hey, ran into the same issue went and checked my config file and onlyfans and my auth_hash and sess both changed. Once I went ahead and updated them it found the accounts.

**Comment by jimcrapo** [comment]
I'm having the same issue - this was working a few days ago. Updated my auth_hash & sess to no avail. I've also restored a backed up original config and entered my settings there - no good. Perhaps Onlyfans has changed something?

**Comment by DIGITALCRIMINAL** [comment]
There's nothing wrong with the auth. You just have to sometimes refresh your auth tokens.
