### ISSUE TITLE
Does not download

### ISSUE THREAD

**Issue by Razormadcat** [DIGITALCRIMINAL/OnlyFans#156]
I have now finally managed to set everything up correctly however I get this message when running it but nothing gets downloaded.

`Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Welcome "my username"
You're not subscribed to any users.
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan`

**Comment by fungastorba** [comment]
So it says that you are not subscribed to any users on Onlyfans. What exactly do you expect to get downloaded?

**Comment by Telandriq** [comment]
@Razormadcat hey, ran into the same issue went and checked my config file and onlyfans and my auth_hash and sess both changed. Once I went ahead and updated them it found the accounts.
