### ISSUE TITLE
Can't authenticate with the cookie anymore, was OK a couple of days ago

### ISSUE THREAD

**Issue by zivshek** [DIGITALCRIMINAL/OnlyFans#1562]
It looks like we are expecting the following keys from the cookie in extras.py->cookie_parser:
auth_id, sess, auth_hash, auth_uniq_, auth_uid_

but the cookie now looks like this:
'csrf=OhtADn\*\*\*\*\*\*\*\*\*bb9e1e\*\*\*\*\*\*\*\*\*0ef495014e041; __stripe_mid=\*\*\*\*\*\*\*\*\*e-f8f4-43be-856c-\*\*\*\*\*\*\*\*\*9a277d7710; cookiesAccepted=true; fp=6e7c6999\*\*\*\*\*\*\*\*\*8445f76efa\*\*\*\*\*\*\*\*\*; __stripe_sid=\*\*\*\*\*\*\*\*\*-c0be-41d2-a6a8-\*\*\*\*\*\*\*\*\*96f9\*\*\*\*\*\*\*\*\*; ref_src=; auth_id=\*\*\*\*\*\*\*\*\*; st=20c8c\*\*\*\*\*\*\*\*\*47eb1a118953a4e36ae\*\*\*\*\*\*\*\*\*72811ad3f84bab00401e2f; sess=1k1vf0h\*\*\*\*\*\*\*\*\*3il2qml4i'

Did they change their auth again?

**Comment by h0-69** [comment]
Having auth issues as well. Doesn't even show profile names when choosing profile, just all or default regardless of what the profile is named. It makes 10 attempts, gets denied, then prompts geckodriver install. Tried that, doesn't fix the auth issue.

After re-entering cookie details in auth.json, I get: ValueError: not enough values to unpack (expected 2, got 1)

Not sure how to proceed. Like you state, was not having this issue last week.

**Comment by LunarPenguin** [comment]
Is this error still occurring? my auth still works

**Comment by zivshek** [comment]
> Is this error still occurring? my auth still works

Yup, still happens to me, did you try logging out and re-login from your browser?

**Comment by EightDee** [comment]
Getting the same issue. Started this morning. I update my  Auth.json with my current session. The script fails to log in. My browser session gets logged out.

**Comment by zivshek** [comment]
> Duh, Fixed my issue. I forgot to update the User Agent

Hi, could you post your cookie here? You can delete the values, I really want to compare the keys. Thanks!

**Comment by zivshek** [comment]
Actually I can authenticate now. Interesting, changed from Chrome to Firefox browser.
