### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by eddycoolgo** [DIGITALCRIMINAL/OnlyFans#157]
Hi,

When I run _python StartDatascraper.py_, I get this error :

`Traceback (most recent call last):
  File "StartDatascraper.py", line 1, in <module>
    from modules.helpers import update_config
ImportError: No module named modules.helpers`

Can you please help?
Thanks!
Eddy

**Comment by DIGITALCRIMINAL** [comment]
is there anything in the modules folder?

**Comment by eddycoolgo** [comment]
Hey!

Thanks for your answer :-)

Yes, in the modules folder there is :
- bbwchan.py
- four_chan.py
- helpers.py
- justforfans.py
- modules.helpers.py
- onlyfans.py

If it's useful to know, I'm on the last version of macOS.

Thank you,
Eddy

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit

**Comment by eddycoolgo** [comment]
Hi,
Thank you, but I still get the same error.

**Comment by eddycoolgo** [comment]
But when I try on Windows (on the same computer), I don't have any problem.

**Comment by DIGITALCRIMINAL** [comment]
I have no idea because I don't have mac
