### ISSUE TITLE
Cant find credentials to login

### ISSUE THREAD

**Issue by mhbosch** [DIGITALCRIMINAL/OnlyFans#1572]
Hello,

 i have done my frirst run and want do login.
But i dont have all the credentials.

First, this is my cookie
![image](https://user-images.githubusercontent.com/16690726/129157102-19b164ef-3e54-4763-98a7-a4e28d81f2a8.png)

The user-agent i cant find. There is no cookie with this. and no Infromation in the init
![image](https://user-images.githubusercontent.com/16690726/129157290-6212ed6b-6dc0-49ba-af1d-a1b64a36ea4e.png)

Can somebody help me, to inspect for the credentials?

**Comment by americanseeder1865** [comment]
Go to the request headers tab instead of the preview tab. Then scroll all of the way down.

**Comment by mhbosch** [comment]
Sorry, do yoh have a screenshot? i think my tabs are not the same like yours.

**Comment by mhbosch** [comment]
I have find it. Thanks for the support.
