### ISSUE TITLE
Traceback Error & KeyError: 'author' while "scraping paid content"

### ISSUE THREAD

**Issue by BiggD0gg** [DIGITALCRIMINAL/OnlyFans#1573]
![Screenshot 2021-08-12 134804](https://user-images.githubusercontent.com/54581986/129163688-565cff04-a231-4766-997e-fe89998805be.png)

I am getting this error while scraping paid content of some models.
and it is working charm for some tho!

**Comment by americanseeder1865** [comment]
This is a known issue that it being worked on. Please us this link for a quick fix. https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231

**Comment by BiggD0gg** [comment]
thanks man...it worked!
