### ISSUE TITLE
cannot import name 'declarative_base' (am i just dumb)

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINAL/OnlyFans#1580]
when the extractor wasnt working today i decided to update. i did this by extracting the zip to the same directory i had the old version in, simply replacing all relevant duplicate files. I probably did this wrong and here is the resulting error.

```
Traceback (most recent call last):
  File "B:\OnlyFans-6.4.3\OF-Extract\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "B:\OnlyFans-6.4.3\OF-Extract\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "B:\OnlyFans-6.4.3\OF-Extract\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "B:\OnlyFans-6.4.3\OF-Extract\database\databases\user_data\models\api_table.py", line 7, in <module>
    from sqlalchemy.orm import declarative_base  # type: ignore
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (C:\Users\games\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sqlalchemy\orm\__init__.py)
```

**Comment by J4k-The-Reaper** [comment]
Why not use the Github Desktop App? It updates the script automatically and makes it easier to manage. You can place all the repositories you use with it.

**Comment by DarkDownloader** [comment]
You need to re-run the pip install command.

**Comment by Luke-L** [comment]
> 
> 
> Why not use the Github Desktop App? It updates the script automatically and makes it easier to manage. You can place all the repositories you use with it.

even with cloning the repo in the desktop app, i still get the same isue i listed above.

**Comment by LunarPenguin** [comment]
did you update to the latest version? your folder name says `6.4.3`

Have you rerun the `pip install -U -r requirements.txt` command to update the required libraries to their required versions?

**Comment by americanseeder1865** [comment]
Protip: Use Docker, it seriously makes your life easier.

**Comment by americanseeder1865** [comment]
but if you are still having issues, let me know. I will guide you through
