### ISSUE TITLE
KeyError: 'author'

### ISSUE THREAD

**Issue by rouzbehzarei** [DIGITALCRIMINAL/OnlyFans#1588]
Error given while downloading...
![Untitled](https://user-images.githubusercontent.com/55883200/129827950-4c62b42e-1a6c-40e5-b093-9a76239d5b8e.jpg)

**Comment by Macmasteri** [comment]
I also receive error now and then:

Same error as you.

**Comment by LunarPenguin** [comment]
See: #1419

**Comment by Throwaway115** [comment]
think im getting the same but only on 1 creator, everyone else works fine :/
![image](https://user-images.githubusercontent.com/77456400/129964678-10488ba7-038a-4ab7-9af1-96ec0c84ef13.png)

**Comment by vacuran** [comment]
The work around posted [here](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231) worked for me. 

In the api_helper.py file, on line 395 change:
`media_set = list(chain(*media_set))`
to:
`media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]`

Credit to Charmoq for coming up with that fix.

**Comment by rouzbehzarei** [comment]
> The work around posted [here](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231) worked for me.
> 
> In the api_helper.py file, on line 395 change:
> `media_set = list(chain(*media_set))`
> to:
> `media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]`
> 
> Credit to @Charmoq for coming up with that fix.

This is the error I get when I did what you posted.
![Uploading Untitled-1.jpg…]()

**Comment by Macmasteri** [comment]
> The work around posted [here](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231) worked for me.
> 
> In the api_helper.py file, on line 395 change:
> `media_set = list(chain(*media_set))`
> to:
> `media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]`
> 
> Credit to @Charmoq for coming up with that fix.

Thanks for this. Worked for this specific model. Creds too @Charmoq! :)

**Comment by vacuran** [comment]
> > The work around posted [here](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231) worked for me.
> > In the api_helper.py file, on line 395 change:
> > `media_set = list(chain(*media_set))`
> > to:
> > `media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]`
> > Credit to @Charmoq for coming up with that fix.
> 
> This is the error I get when I did what you posted.
> ![Untitled-1](https://user-images.githubusercontent.com/55883200/129987788-d2e7afbd-cffe-48b9-ae4e-3661e7a3ab2b.jpg)

From the error message it sounds like you have an issue with your indentation. Python cares a lot about spacing within your code. Can you post your code?

**Comment by rouzbehzarei** [comment]
> > > The work around posted [here](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231) worked for me.
> > > In the api_helper.py file, on line 395 change:
> > > `media_set = list(chain(*media_set))`
> > > to:
> > > `media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]`
> > > Credit to @Charmoq for coming up with that fix.
> > 
> > 
> > This is the error I get when I did what you posted.
> > ![Untitled-1](https://user-images.githubusercontent.com/55883200/129987788-d2e7afbd-cffe-48b9-ae4e-3661e7a3ab2b.jpg)
> 
> From the error message it sounds like you have an issue with your indentation. Python cares a lot about spacing within your code.
> I went ahead and uploaded my fixed file. You'll need to rename it from api_helper.txt to api_helper.py (maybe make a copy of your original first just in case something goes wrong) because apparently I cannot attach .py files in posts..
> [api_helper.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/7015824/api_helper.txt)

For some reason your file worked. (and I'm not a noob in copy pasting a line of code!). Thank you very much.
