### ISSUE TITLE
Onlyfans Banning XXX

### ISSUE THREAD

**Issue by GreyBeardy** [DIGITALCRIMINAL/OnlyFans#1594]
From October OF is gonna Bar porn content - nudes still ok but sex no longer allowed.

I hope a new script will follow to whatever platform the performers will move to.

Source - bloomberg.com news

**Comment by DIGITALCRIMINAL** [comment]
Sigh, I wish I could close issues via email.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by GreyBeardy** [comment]
sjeez ill close it for ya np.

**Comment by DIGITALCRIMINAL** [comment]
Make a new discussion instead lmao, this isn't an issue.

Sent from ProtonMail mobile

-------- Original Message --------
