### ISSUE TITLE
Scraping Taking forever? 

### ISSUE THREAD

**Issue by MrRawrrino89** [DIGITALCRIMINAL/OnlyFans#1595]
Would anybody know why that is? even takes a while to load up the start script, unsure why as it never used to be slow.

**Comment by americanseeder1865** [comment]
What platform are you using? Windows, Linux or Docker?

**Comment by MrRawrrino89** [comment]
> What platform are you using? Windows, Linux or Docker?

Windows currently!

**Comment by americanseeder1865** [comment]
Are you on the latest commit? The latest commit is broken, but I will guide you on how to get things fixed.

**Comment by americanseeder1865** [comment]
With the news today, these are not likely to be fixed, but I do know what to change to get it working.

**Comment by MrRawrrino89** [comment]
Yeah I believe I am!

**Comment by MrRawrrino89** [comment]
I ain’t really python savvy so if possible whatever the easiest and I guess dumbed down way possible I’d appreciate very much.

**Comment by americanseeder1865** [comment]
Alright, lets do some IT 101. Make sure your content (.sites) is NOT NOT NOT in the folder where the code is. If it is, move the contenct out of that folder. I would also save your .settings older and your .profiles folder to make things easier. Then, once your content (.sites), settings (.settings) and profiles (.profiles) folders are moved out of the folder where your code is,  run this command. 

we will need to uninstall requirements.txt so run this command while in the directory where the code is at.

> pip freeze > requirements.txt && pip uninstall -r requirements.txt -y

delete the code folder. Then let's re-download the code, and then put the content (.sites) settings(.settings) and profiles (.profiles) folder back in. 

do not run the code or install the pip requirements yet. Let me know when that is done.

**Comment by MrRawrrino89** [comment]
> Alright, lets do some IT 101.
> 
> READ THE ENTIRE DIRECTONS FIRST.
> 
> Make sure your content (.sites) is NOT NOT NOT in the folder where the code is. If it is, move the contenct out of that folder. I would also save your .settings older and your .profiles folder to make things easier. Then, once your content (.sites), settings (.settings) and profiles (.profiles) folders are moved out of the folder where your code is.
> 
> we will need to uninstall requirements.txt so run this command while in the directory (folder for windows people) where the code is at.
> 
> > pip freeze > requirements.txt && pip uninstall -r requirements.txt -y
> 
> delete the code folder. Then let's re-download the code, and then put the content (.sites) settings(.settings) and profiles (.profiles) folder back in.
> 
> do not run the code or install the pip requirements yet. Let me know when that is done.

Okay one question, what is the .sites folder called? 
![image](https://user-images.githubusercontent.com/86880907/130195621-ac678d30-b2ba-4a05-9001-3e7bd68fdbd3.png)

**Comment by americanseeder1865** [comment]
lets go ahead and move .Dowloads and .metadata out. I am using right now so my stuff is .sites and i don't have .metadata . just to be sure, make sure that your content is indeed safe and out of the folder we are about to delete.

**Comment by MrRawrrino89** [comment]
done.

**Comment by MrRawrrino89** [comment]
> lets go ahead and move .Dowloads and .metadata out. I am using right now so my stuff is .sites and i don't have .metadata . just to be sure, make sure that your content is indeed safe and out of the folder we are about to delete.

Done.

**Comment by americanseeder1865** [comment]
alright did you move .downloads and .metadata along with the other folders back in?

**Comment by MrRawrrino89** [comment]
> alright did you move .downloads and .metadata along with the other folders back in?

correct back in

**Comment by americanseeder1865** [comment]
alright. Go into your reqirements.txt file and make sure it looks like this. This is fixing a known bug.

> requests
beautifulsoup4
urllib3
win32-setctime
python-socks[asyncio]
psutil
python-dateutil
lxml
mergedeep
jsonpickle
ujson
sqlalchemy==1.4.20
alembic
tqdm>=4.62.0
selenium
selenium-wire==2.1.2
user_agent
aiohttp
aiohttp_socks

**Comment by MrRawrrino89** [comment]
> alright. Go into your reqirements.txt file and make sure it looks like this. This is fixing a known bug.
> 
> > requests
> > beautifulsoup4
> > urllib3
> > win32-setctime
> > python-socks[asyncio]
> > psutil
> > python-dateutil
> > lxml
> > mergedeep
> > jsonpickle
> > ujson
> > sqlalchemy==1.4.20
> > alembic
> > tqdm>=4.62.0
> > selenium
> > selenium-wire==2.1.2
> > user_agent
> > aiohttp
> > aiohttp_socks

Done.

**Comment by americanseeder1865** [comment]
Alright. The next thing we will do is edit one part of the actual code. Do you have an app like Notepad++ ?

**Comment by MrRawrrino89** [comment]
> Alright. The next thing we will do is edit one part of the actual code. Do you have an app like Notepad++ ?

Yep i have notepad++ :)

**Comment by americanseeder1865** [comment]
awesome. I am a docker/linux user but I am thinking you can open up python files using notepad++ .

In the code folder, go into the apis folder and open up, with notepad++ , the file called api_helper.py . Let me know when you are done with this.

**Comment by MrRawrrino89** [comment]
> awesome. I am a docker/linux user but I am thinking you can open up python files using notepad++ .
> 
> In the code folder, go into the apis folder and open up, with notepad++ , the file called api_helper.py . Let me know when you are done with this.

Im in it :)

**Comment by americanseeder1865** [comment]
awesome. Scroll down to line 395. the line should be `media_set = list(chain(*media_set))`

**Comment by MrRawrrino89** [comment]
> awesome. Scroll down to line 395. the line should be `media_set = list(chain(*media_set))`

yep see it

**Comment by americanseeder1865** [comment]
perfect! I need the part where it says `list(chain(*media_set))` to be changed to  `media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]` 

be extremly careful to not change anything else, even the indentation.

**Comment by MrRawrrino89** [comment]
> media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]

so can i delete the line thats on 395 and replace it with 

media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]

**Comment by americanseeder1865** [comment]
yes but python relies on indentation, so do not change where that line is exactly. I needs to be exactly the same indentation.

**Comment by MrRawrrino89** [comment]
> perfect! I need the part where it says `list(chain(*media_set))` to be changed to `media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]`
> 
> be extremly careful to not change anything else, even the indentation.

does this look okay? 
![image](https://user-images.githubusercontent.com/86880907/130198646-f1199d79-86f7-416e-b999-82fd731b2748.png)

**Comment by americanseeder1865** [comment]
looks perfect! alright. Lets go ahead and go into CLI (cmd/powershell for windows users) again. 

run `pip install --upgrade --user -r requirements.txt`

then start the scraper.

**Comment by americanseeder1865** [comment]
make sure that you are in the folder when running pip

**Comment by americanseeder1865** [comment]
the main code folder (so not in the apis folder)

**Comment by americanseeder1865** [comment]
Let me know if it worked, or we have errors.

**Comment by MrRawrrino89** [comment]
> Let me know if it worked, or we have errors.

okay i believe it has sped it up! :) a huge thank you for taking ya time out to help me!, im not really good with stuff like python so its all still a learning curve! but your help made me understood it a little easier! thank you!

**Comment by americanseeder1865** [comment]
Awesome! happy to help. Mind marking this issue as closed?

**Comment by americanseeder1865** [comment]
Keeping this closed, but you should donate some litecoin to the creator. He really knows his stuff. https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1596
