### ISSUE TITLE
Can this be used as an archival tool for content creators to download content from their vault?

### ISSUE THREAD

**Issue by levihb** [DIGITALCRIMINAL/OnlyFans#1599]
Can content creators use this to archive their own content from their vault? I have a penchant for data archival and preservation. With the rumours of them disallowing adult content, many people want to backup their content they don't have local copies of.

Can this download content from the creators vault, of course when signed in on their account?

If not can it download content that is in the "Saved for later" section or "Archive" section?

**Comment by DIGITALCRIMINAL** [comment]
Yes and it should be able to download the "Archived" section.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by americanseeder1865** [comment]
@levihb would you mind closing this?

**Comment by levihb** [comment]
> > > Yes and it should be able to download the "Archived" section. Sent from ProtonMail mobile
> > 
> > 
> > Thanks for the reply. I actually found [another solution](https://onlywishlist.com/extension) though. The other solution is much easier to use, and designed explicitly for creator's to backup their own vault. So I'd likely recommend that one to anyone in need of getting their own data back.
> > > @levihb would you mind closing this?
> > 
> > 
> > Pretty weird request? If you're part of the project you should get privileges to close them. If you're not, leaving messages like that is rather weird.
> > No I can't close it.
> 
> While I contribute, I am not the owner or have any privlages to do anything. I can only submit pull requests (as can you) so I have no admin privlages.

Sorry was unaware of how to close it.
