### ISSUE TITLE
Error in scrapping videos

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#16]
Scrape: a = Everything | b = Images | c = Videos
Optional Arguments: -l = Only scrape links -()- Example: "a -l"
c -l
Traceback (most recent call last):
  File "onlyfans.py", line 170, in <module>
    scrape_choice()
  File "onlyfans.py", line 91, in scrape_choice
    media_scraper(video_api, location, j_directory, only_links)
  File "onlyfans.py", line 117, in media_scraper
    for media in media_api["media"]:
TypeError: string indices must be integers

**Comment by dilemmax** [comment]
No problem scrapping images.

**Comment by DIGITALCRIMINAL** [comment]
Hmm, it seems to be working on my end.
How many videos does the user have?

**Comment by dilemmax** [comment]
Over 1000+ videos

**Comment by dilemmax** [comment]
I used a -l but it’s only scrapping images

**Comment by DIGITALCRIMINAL** [comment]
Ooof, that's a lot. 
I created a new branch called debug #1
https://github.com/DIGITALCRIMINAL/OnlyFans/tree/OF-Debug-%231
Everything is the same except for the Onlyfans.py. Download the project just how you do normally.

I have added try and except blocks to catch the error. Run the script as you normally would with the 
c -l command
`            try:
                for media in media_api["media"]:
                    if "source" in media:
                        file = media["source"]["source"]
                        if "ca2.convert" in file:
                            file = media["preview"]
                        media_set[media_count] = {}
                        media_set[media_count]["link"] = file
                        dt = datetime.fromisoformat(media_api["postedAt"]).replace(tzinfo=None).strftime('%d-%m-%Y')
                        media_set[media_count]["text"] = media_api["text"]
                        media_set[media_count]["postedAt"] = dt
                        media_count += 1
            except Exception as e:
                logger.error(e)
                logger.error(y)
                exit()`
If an error is caught the script will automatically close and produce an errors.log in the same folder as the script. Copy and paste the contents of the errors.log here so I can debug them.

**WARNING**: the errors.log contains your IP address, and for your security, I would suggest removing them all, a text editor like Visual Studio code will allow you to remove all matching strings of your choice, so you don't have to do it 1 by 1.

**Comment by dilemmax** [comment]
Maybe yesterday was an off day but the debug script is working with no error. I tried the master script and it scrapped the videos with no problem, Not sure what's going on??

**Comment by DIGITALCRIMINAL** [comment]
Does the normal script work though?
