### ISSUE TITLE
Downloading live streams

### ISSUE THREAD

**Issue by somedude74** [DIGITALCRIMINAL/OnlyFans#160]
Would it be possible to implement a function that downloads live streams? I know it can download previous ones if the model leaves them up, but most don't.

**Comment by DIGITALCRIMINAL** [comment]
I won't add this in; there's lots of programs that can download live streams

**Comment by somedude74** [comment]
Which one would you recommend

**Comment by FilthyLiquid** [comment]
> 
> 
> I won't add this in; there's lots of programs that can download live streams

I've tried a lot of them and none of them detect that any stream is playing. The lives seem to be pretty well protected. If you could recommend something that would be great, otherwise this would a nice feature to have.

**Comment by DIGITALCRIMINAL** [comment]
I would have to see when someone live streams on their account .-.
