### ISSUE TITLE
Can't see auth_uniq_=; auth_uid_=;

### ISSUE THREAD

**Issue by JJSeventies** [DIGITALCRIMINAL/OnlyFans#1606]
auth_uniq_=; auth_uid_=; dont seem to appear in my debugger screen...  I see CSRF FP ST  SESS AUTH_ID  but not the others?  Am I looking in the wrong place?

**Comment by JJSeventies** [comment]
Oh dear god.  I'm dumb.

It's ok, I "Figured" it out... :-(

**Comment by JJSeventies** [comment]
I am dumb

**Comment by slickgslickg** [comment]
Hey - I am also being dumb - could you kindly enlighten me on this one? :)
