### ISSUE TITLE
unable to get auth_hash and auth_uniq

### ISSUE THREAD

**Issue by LCS1337** [DIGITALCRIMINAL/OnlyFans#1607]
Can't get auth hash and auth uniq, when i search for "?app" it gives no result, and when i search for "api" it shows me everything execpt the auth_hash, auth_uniq and auth_uid

**Comment by vacuran** [comment]
In my file auth_hash=; is left as is, auth_uniq you'll need to add the _<auth_id>, same with auth_uid.

So if your `auth_id = 12345`
Then you would fill out the others like this:
```
auth_uniq_12345=;
auth_uid_12345=;
auth_hash=;
```

**Comment by paperboy11** [comment]
i just fill all three up with the same ID and it works

**Comment by americanseeder1865** [comment]
Awesome! Can you close this issue?
