### ISSUE TITLE
Is there a way to rip the text from a post in addition to the video? (onlyfans)

### ISSUE THREAD

**Issue by left1000** [DIGITALCRIMINAL/OnlyFans#1613]
Is there a way to rip the text from a post in addition to the video? On onlyfans this is.

I found a model that gives clear titles to all her videos in the text of her video posts, and I was wondering if there was anyway to save this text (in manner that makes it clear which snippet of text relates to which video)? It would make the rip more well organized... am I missing something? this might already be a feature I just don't know how to enable?

**Comment by taggedme** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans#path_formatting

You're looking for the "text" variable. Do heed the warning at the bottom though.

**Comment by left1000** [comment]
Oh I see. "Don't use the text variable. If you do, enjoy emojis in your filepaths and errors lmao."

What I had been hoping for ideally was not to use the text as a filename, I know that just won't work at all for me. Sometimes the girl writes a paragraph. On windows the filename will count as too long and break. I had hoped that the text could just be dumped into some sort of textfile. Either one giant text file. Or a unique text file per each post.

Although I wonder if there's a way to re-run the rip using this dangerously malfunctional {text} option but somehow end up with nothing but 0 kilobyte files. Which I could then cross reference (dump back into) my normal rip.

I guess you 100% answered my question, but haven't actually solved the problem of how to keep a record of a model's text accompanying her content drops. (The main reason I care about this is that I fear in 6 weeks many onlyfans accounts simply won't exist, so it will be too late to archive the descriptions of videos written by the model. ever again.)

Feel free to close the issue though if you feel it is closed.

**Comment by nunga** [comment]
You can download DB Browser for SQL Lite and view the user_data.db metadata file.
https://sqlitebrowser.org/

You can then run a query to extract the data you want - which includes the original directory and filename you saved your file to.

In DB Browser, you can paste the query below onto the _Execute SQL_ tab to grab the info then copy/paste it wherever you want. 

```
SELECT 'Post' AS post_type, p.text, m.directory, m.filename, m.size, p.created_at
FROM medias m INNER JOIN posts p ON m.post_id = p.post_id
UNION SELECT 'Stories' AS post_type, p.text, m.directory, m.filename, m.size, p.created_at
FROM medias m INNER JOIN stories p ON m.post_id = p.post_id
UNION SELECT 'Messages' AS post_type, p.text, m.directory, m.filename, m.size, p.created_at
FROM medias m INNER JOIN messages p ON m.post_id = p.post_id
```


As a next step, you could paste the results into Excel and use the HYPERLINK function to point to the file. Then if you see a description that takes your fancy, you can open the file directly.
