### ISSUE TITLE
Receiving errors during scrape process starting today

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#162]
OF change their site?

![image](https://user-images.githubusercontent.com/20603861/76039925-db867800-5f1b-11ea-8af9-49a100c3eb00.png)
![image](https://user-images.githubusercontent.com/20603861/76039946-ec36ee00-5f1b-11ea-9b9e-33e11d933c6a.png)

Edit: Just realized theres a big message saying theyre upgrading servers on the site. Will try again after

**Comment by DIGITALCRIMINAL** [comment]
Yeah, they upgraded their stuff.
