### ISSUE TITLE
systematically crashes while ripping: notyourtypicalbarbiedoll 

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#1647]
`(Background on this error at: http://sqlalche.me/e/14/e3q8)
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5493253cc03c, content
(sqlite3.OperationalError) table medias already exists
[SQL:
CREATE TABLE medias (
        id INTEGER NOT NULL,
        media_id INTEGER,
        post_id INTEGER NOT NULL,
        link VARCHAR,
        directory VARCHAR,
        filename VARCHAR,
        size INTEGER,
        api_type VARCHAR,
        media_type VARCHAR,
        preview INTEGER,
        linked VARCHAR,
        downloaded INTEGER,
        created_at TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE (media_id)
)

]
(Background on this error at: http://sqlalche.me/e/14/e3q8)`

**Comment by ChangeUsername** [comment]
Are you using an older config file? This might fix it.
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1472#issuecomment-890164146

**Comment by jp1151419** [comment]
> Are you using an older config file? This might fix it.
> [#1472 (comment)](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1472#issuecomment-890164146)
> 
> Also maybe delete (rename) that profiles metadata might help

Thanks but I found no helpful info there as I'm already using both "0" and "{filename}.{ext}"

I'll try with a new metadata folder  but it's a brand new account for me to rip so I have zero downloads as of now.

**Comment by jingofett** [comment]
i am also getting this error on any of the models i try (new and existing). i've tried updating everything, i've tried deleting my config.json file, still gives me this error in a loop
