### ISSUE TITLE
Access denied "You're not subscribed to any users"

### ISSUE THREAD

**Issue by P0rr** [DIGITALCRIMINAL/OnlyFans#165]
did fix this problem now. i have new one and dont know if onlyfans try stop this app. they change sess & auth_hash & app-toke several times for me in very short time 

C:\temp\OnlyFans DataScraper v3.7.5>StartDatascraper.py
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Auth (V2) Attempt 1/10
Access denied.
Auth (V2) Attempt 2/10
Access denied.
Auth (V2) Attempt 3/10
Access denied.
Auth (V2) Attempt 4/10
Access denied.
Auth (V2) Attempt 5/10
Access denied.
Auth (V2) Attempt 6/10
Access denied.
Auth (V2) Attempt 7/10
Access denied.
Auth (V2) Attempt 8/10
Access denied.
Auth (V2) Attempt 9/10
Access denied.
Auth (V2) Attempt 10/10
Access denied.
You're not subscribed to any users.

did work fine last morning. now its like this.. It new update on way?

**Comment by timothychare** [comment]
I am having the exact same experience. Looking forward to an update. Thanks for your hard work!

**Comment by JohnnyTowns94** [comment]
Update your auth_hash

**Comment by NyanyanKat** [comment]
It seems to be an issue with the new version. I tried 3.7.2 and it works like normal

**Comment by P0rr** [comment]
Did get this problem on v3.7.5

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit
