### ISSUE TITLE
Please refresh the page

### ISSUE THREAD

**Issue by fg4jerem** [DIGITALCRIMINAL/OnlyFans#1666]
This morning it stopped working for me, I cannot authenticate after updating the cookie and user_agent in my authorization file. I get the following output:

```
U:\Private\Scraping\OnlyFans\tool>python start_ofd.py
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Please refresh the page
Archive Completed in 0.06 Minutes
Pausing scraper for 0 seconds.
Choose Profile
Names: Username = username  | 0 = All | 1 = default
```

**Comment by freakish804** [comment]
same

**Comment by OFfriend** [comment]
https://github.com/DATAHOARDERS/dynamic-rules was invalid for a few minutes. OF changed something. It's working again. Please try again.

**Comment by fg4jerem** [comment]
> https://github.com/DATAHOARDERS/dynamic-rules was invalid for a few minutes. OF changed something. It's working again. Please try again.

@OFfriend  Yes, it's working again. Thank you!
