### ISSUE TITLE
Run script only once (2)

### ISSUE THREAD

**Issue by mwald84** [DIGITALCRIMINAL/OnlyFans#168]
Sorry to reopen this but you closed the old one before I could reply.

I've read the readme before posting that but the infinite loop didn't work in the case I described since I have to press a key to leave the script at the end.
As I said there, I'm trying to run it from another script and if I have to press a key at the end it will never return to the calling script. That's why I asked.

Sorry to repost this.

**Comment by mwald84** [comment]
but, again, it's not a complain or requiest. I was just wondering if that was possible currently.

**Comment by ecchiecchi0** [comment]
You can try modifying StartDataScraper.py
from: 
```
        if not infinite_loop:
            print("Input anything to continue")
            input()
```
to:

```
        if not infinite_loop:
            print("Now exiting.")
            exit(0)
```

**Comment by mwald84** [comment]
I know, but then I need to do this again on every commit I download.

It's not a big problem tho. I was just wondering if it was possible.

Thanks!

**Comment by ecchiecchi0** [comment]
I just submitted a PR to add this as a exit on completion as a configuration option as well as the ability to pause the infinite loop in between runs.

**Comment by mwald84** [comment]
thanks!

**Comment by DIGITALCRIMINAL** [comment]
@ecchiecchi0 thanks for it; I will merge it in a few hours with a few minor changes; I just have to finish my new commit first.

**Comment by DIGITALCRIMINAL** [comment]
Merged; thanks.
