### ISSUE TITLE
Scrapper download nothing

### ISSUE THREAD

**Issue by DandeMC** [DIGITALCRIMINAL/OnlyFans#1688]
Hello,
cam't find the problem... 

Site: 0 = onlyfans |
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
(Account name)
Archive Completed in 0.08 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |

It downloads nothing. Where is my mistake?

**Comment by kavinklain** [comment]
Are you subscribed to a model? if yes, then did you input your account info correctly into the scraper?

**Comment by DandeMC** [comment]
I think so. I checked it many times. But I don't know what I must put in at the auth conf in the row "username"?
