### ISSUE TITLE
Getting the error when I start the python file (Site: 0 = onlyfans |)

### ISSUE THREAD

**Issue by raymandoo** [DIGITALCRIMINAL/OnlyFans#1691]
Site: 0 = onlyfans |

Traceback (most recent call last):
  File "C:\Users\Raymond\Downloads\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Raymond\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Raymond\Downloads\OnlyFans-master\start_ofd.py", line 41, in main
    site_choice = int(site_choice)
ValueError: invalid literal for int() with base 10: ''

Getting this error when I try starting the python file. (These are images on what my .json file looks like and my python error)
https://drive.google.com/file/d/1vGu9ZymVOSTHgbJradk6fQzV7kWpLckk/view?usp=sharing
https://drive.google.com/file/d/1MYN86hwDLV_Z07j0Kf1BsHXcdBG-fZCH/view?usp=sharing

I have put in the correct cookie and network debug details in to the auth.json file. I also put in my username in the username area. But after I open the python file I get the error code above if I press enter. If I do not press enter, I only get the code 
(Site: 0 = onlyfans |) and nothing happens. How do I progress from here?

**Comment by Cyberace1985** [comment]
im also having this issue

**Comment by LunarPenguin** [comment]
Do you immediately press <kbd>enter</kbd> or do you press <kbd>0</kbd> first and then press <kbd>enter</kbd>? if not then try that.

**Comment by raymandoo** [comment]
Yeah I did that, and i got this message

Choose Profile
Names: Username = username  | 0 = All | 1 = default
 
Sorry, Im very new to python. Surprised I even got this far.

**Comment by Cyberace1985** [comment]
i tried typing in a user name and then doing both 0 and 1 and got failed attempts

**Comment by LunarPenguin** [comment]
> Choose Profile

This is to select a profile in the `.profiles` folder.

by default `default` is the only profile available so type <kbd>1</kbd> and the hit <kbd>enter</kbd>

> i tried typing in a user name and then doing both 0 and 1 and got failed attempts

Does it give any error?

**Comment by Cyberace1985** [comment]
https://imgur.com/Q7pK0um

**Comment by Cyberace1985** [comment]
also running this through Docker using WSL/ubuntu

**Comment by LunarPenguin** [comment]
>https://imgur.com/Q7pK0um

it seems their is a problem with your `auth` settings

**Comment by raymandoo** [comment]
Thank you! Worked for me. Do you guys want to continue this troubleshoot on another dedicated topic so I can close this issue.
Just tell me when ur finished or opened another issue so I can close this one

**Comment by LunarPenguin** [comment]
> Just tell me when ur finished or opened another issue so I can close this one

I would prefer @Cyberace1985 open their own issue and you close this one.

They can then reference this issue in their own issue

**Comment by raymandoo** [comment]
Yeah solid. I'll close in 24hrs, hopefully by then cyber can see the messages and open another issue. 

Thank you again!
