### ISSUE TITLE
You're not subscribed to any users.

### ISSUE THREAD

**Issue by emalov98ffm** [DIGITALCRIMINAL/OnlyFans#170]
Hello,
I was tried to start this app on mac os system and on windows 10 system I was getting the same error it says:

Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Auth (V2) Attempt 1/10
Auth (V2) Attempt 2/10
Auth (V2) Attempt 3/10
Auth (V2) Attempt 4/10
Auth (V2) Attempt 5/10
Auth (V2) Attempt 6/10
Auth (V2) Attempt 7/10
Auth (V2) Attempt 8/10
Auth (V2) Attempt 9/10
Auth (V2) Attempt 10/10
You're not subscribed to any users.

When this error will be fixed?

**Comment by DIGITALCRIMINAL** [comment]
Are you using the latest commit?

**Comment by emalov98ffm** [comment]
Yes

**Comment by DIGITALCRIMINAL** [comment]
Just to be clear; you're using the latest commit that was released 16 hours ago right?

**Comment by emalov98ffm** [comment]
Yes, I have 2FA on :/ that's why this not working?

**Comment by DIGITALCRIMINAL** [comment]
Yeah, that's why. I can make it work for 2FA in the future; I'm just busy atm, but for now, turn it off.

**Comment by emalov98ffm** [comment]
It should be working now, right? I'm getting this error now:

blabla-iMac:OnlyFans blabla$ python3 StartDatascraper.py

Traceback (most recent call last):
  File "StartDatascraper.py", line 1, in <module>
    import modules.onlyfans as onlyfans
  File "/Users/blabla/Desktop/OnlyFans/modules/onlyfans.py", line 2, in <module>
    from modules.helpers import get_directory, json_request, reformat, format_directory, format_media_set, export_archive, format_image, check_for_dupe_file
  File "/Users/blabla/Desktop/OnlyFans/modules/helpers.py", line 15, in <module>
    json_config = json.load(open(path))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 19 column 145 (char 610)

**Comment by emalov98ffm** [comment]
I tried on VM ubuntu and it working :)

**Comment by emalov98ffm** [comment]
Working on Python 3.7.5

**Comment by DIGITALCRIMINAL** [comment]
I'm releasing 3.8 within 2 hrs

**Comment by DIGITALCRIMINAL** [comment]
Released; lemme know if it's working on your mac

**Comment by emalov98ffm** [comment]
Same error as before :

Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Auth (V2) Attempt 1/10
Access denied.
Auth (V2) Attempt 2/10
Access denied.
Auth (V2) Attempt 3/10
Access denied.
Auth (V2) Attempt 4/10
Access denied.
Auth (V2) Attempt 5/10
Access denied.
Auth (V2) Attempt 6/10
Access denied.
Auth (V2) Attempt 7/10
Access denied.
Auth (V2) Attempt 8/10
Access denied.
Auth (V2) Attempt 9/10
Access denied.
Auth (V2) Attempt 10/10
Access denied.
You're not subscribed to any users.
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan

**Comment by DIGITALCRIMINAL** [comment]
@emalov98ffm then it's your cookies; make sure 2fa is off.

**Comment by emalov98ffm** [comment]
it is off

**Comment by DIGITALCRIMINAL** [comment]
I don't have a mac; I've only got Windows and Ubuntu and it works there

**Comment by taggedme** [comment]
Having the same issue. On windows 10, no 2fa enabled.

**Comment by DIGITALCRIMINAL** [comment]
@taggedme is your account a "model" account?

**Comment by taggedme** [comment]
I don't believe so but not sure how I'd check. I was able to use an older version of this though.

**Comment by taggedme** [comment]
Resolved my issue. Extracted the release into the same folder as the old version and didn't realize the config.json file had moved. 

Using the right config file fixed the "issue".

**Comment by DIGITALCRIMINAL** [comment]
@emalov98ffm did you fix it?
