### ISSUE TITLE
400 Client Error: Unauthorized for Url

### ISSUE THREAD

**Issue by Timmyy23** [DIGITALCRIMINAL/OnlyFans#1709]
![Screenshot (1)](https://user-images.githubusercontent.com/91290122/134717107-2e29665b-0312-406a-891c-7e6f87661fcc.png)

**Comment by LunarPenguin** [comment]
I'm afraid you ended up in the wrong repo, it seems you wanted to go here: [https://github.com/Amenly/onlyfans-scraper](https://github.com/Amenly/onlyfans-scraper)

Please close the issue if that is the case
