### ISSUE TITLE
Is there a way to omit certain profiles from being scraped and downloaded?

### ISSUE THREAD

**Issue by e7111** [DIGITALCRIMINAL/OnlyFans#175]
Is there a way to not download content from specific users?

**Comment by DIGITALCRIMINAL** [comment]
I'm guessing you still want to scrape all but want to filter out profiles?

**Comment by incogrito** [comment]
I'd definitely use something like what you're saying @DIGITALCRIMINAL. Exclude particular profiles from "scrape all"

**Comment by DIGITALCRIMINAL** [comment]
> I'd definitely use something like what you're saying @DIGITALCRIMINAL. Exclude particular profiles from "scrape all"

Added.
https://github.com/DIGITALCRIMINAL/OnlyFans#blacklist_name
