### ISSUE TITLE
New Issue Geckodriver

### ISSUE THREAD

**Issue by HoneyBadger116** [DIGITALCRIMINAL/OnlyFans#1757]
Program has worked with no issue till about last week. I downloaded the file and placed it in the correct folder but still same error pops up.

...
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Download geckodriver from https://github.com/mozilla/geckodriver/releases/tag/v0.27.0 and paste it in D:\OF Rip\OnlyFans\extras\OFLogin

**Comment by KevinxFinnerty** [comment]
I'm getting the same error.  Were you able to resolve this?

**Comment by docholllidae** [comment]
the author lost access to his account, or this repo?
anyway, he moved his repo to and maintains it here https://github.com/DIGITALCRIMINALS/OnlyFans  (notice the S added to the end of his name)

**Comment by HoneyBadger116** [comment]
Thank you!
