### ISSUE TITLE
Support for archived posts

### ISSUE THREAD

**Issue by amenly** [DIGITALCRIMINAL/OnlyFans#176]
I wasn't sure of this earlier but now I'm positive that the scraper does not include posts that the creator archives. Is there any chance you could add support for archived posts?

**Comment by DIGITALCRIMINAL** [comment]
Do you have a model that has an archived post?

**Comment by amenly** [comment]
Yes, you can use [Regina's OnlyFans](https://onlyfans.com/reginaluv/) as an example. If you run the scraper on her profile, you'll notice that the pictures and the video(s) in the Archived tab will not be included by the scraper. 

For example, the video she posted December 11th, 2019, in the Archived tab and the three pictures available in her post on February 9th (also in the Archived tab) don't get caught by the program, I can confirm that with 100% certainty (on my end, at the very least). 

You might thinking that it's because those pictures and videos belong to pay-per-view posts but if you go to her main feed (the Posts tab), the scraper catches the picture in the second pinned post on November 3rd, 2019. My theory is that the scraper isn't catching the archived pictures/videos because those are not included in the Pictures/Videos tabs. 

She also wasn't the person I was having trouble with when I wrote the OP. The creator I was referring to had two posts but had all of her photos and videos in the Archived tab (around 70 items in total). Every time I ran the scraper, it would finish a millisecond later because the scraper wasn't detecting the items in the Archived tab, only her two posts which were only text posts. As of now though, her page no longer has her pictures and videos archived so I can't give her as an example anymore. 

Thank you for your help!

**Comment by DIGITALCRIMINAL** [comment]
> Yes, you can use [Regina's OnlyFans](https://onlyfans.com/reginaluv/) as an example. If you run the scraper on her profile, you'll notice that the pictures and the video(s) in the Archived tab will not be included by the scraper.
> 
> For example, the video she posted December 11th, 2019, in the Archived tab and the three pictures available in her post on February 9th (also in the Archived tab) don't get caught by the program, I can confirm that with 100% certainty (on my end, at the very least).
> 
> You might thinking that it's because those pictures and videos belong to pay-per-view posts but if you go to her main feed (the Posts tab), the scraper catches the picture in the second pinned post on November 3rd, 2019. My theory is that the scraper isn't catching the archived pictures/videos because those are not included in the Pictures/Videos tabs.
> 
> She also wasn't the person I was having trouble with when I wrote the OP. The creator I was referring to had two posts but had all of her photos and videos in the Archived tab (around 70 items in total). Every time I ran the scraper, it would finish a millisecond later because the scraper wasn't detecting the items in the Archived tab, only her two posts which were only text posts. As of now though, her page no longer has her pictures and videos archived so I can't give her as an example anymore.
> 
> Thank you for your help!

Sorry I couldn't do it in time :(

I've added support for Archived posts now in the newest release.
https://github.com/DIGITALCRIMINAL/OnlyFans/releases/latest
