### ISSUE TITLE
No file called .profiles/default/auth.json to edit??

### ISSUE THREAD

**Issue by benshandd** [DIGITALCRIMINAL/OnlyFans#1767]

**Comment by alexey-romero** [comment]
Did you run the file "start_ofd.py"? It's created once you do.

**Comment by eternitycomplex** [comment]
> Did you run the file "start_ofd.py"? It's created once you do.

Not the OP, but running that file just closes the window (when running from a double click) or just drops me back to the command prompt (when running start_ofd.py in the console).
