### ISSUE TITLE
Error Scraping

### ISSUE THREAD

**Issue by mizuoppai** [DIGITALCRIMINAL/OnlyFans#18]
I am getting the error below when scraping. Seems like it verified but cant get the details of the media? Same error which ever options is chosen everything,image, video and even with -l

```
Scrape: a = Everything | b = Images | c = Videos
Optional Arguments: -l = Only scrape links -()- Example: "a -l"
c
Traceback (most recent call last):
  File "OnlyFans.py", line 170, in <module>
    scrape_choice()
  File "OnlyFans.py", line 91, in scrape_choice
    media_scraper(video_api, location, j_directory, only_links)
  File "OnlyFans.py", line 124, in media_scraper
    dt = datetime.fromisoformat(media_api["postedAt"]).replace(tzinfo=None).strftime('%d-%m-%Y')
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by mizuoppai** [comment]
It seems to be working fine if I use your early versions without the file formatting update.

Dont know how to refer to the specific one but it has the commit id fa94513af0907c0910e1a9f08045b9e534430396

**Comment by bpo5r5** [comment]
What Python version are you using? I had a similar error on 3.6.6 but upgrading to 3.7 fixed it.

**Comment by mizuoppai** [comment]
> What Python version are you using? I had a similar error on 3.6.6 but upgrading to 3.7 fixed it.

I am using 3.6.8. I am using this on Ubuntu 18.04 and it is telling me I have the latest.

**Comment by mizuoppai** [comment]
Also as an FYI for those wondering how to use the filenaming format options, it looks like there arecurrently 4 variables "{username}","{date}", "{file_name}","{ext}" that I saw and are self-explanatory. You replace the default "{file_name}.{ext}" in the json to set the format of it.
I have tested {username}{date}.{ext} which works as expected ie it becomes "model01-09-2019.mp4"

Use at your own risk given that is me deducing those options and it seems to work in my specific case

**Comment by dilemmax** [comment]
> Also as an FYI for those wondering how to use the filenaming format options, it looks like there arecurrently 4 variables "{username}","{date}", "{file_name}","{ext}" that I saw and are self-explanatory. You replace the default "{file_name}.{ext}" in the json to set the format of it.
> I have tested {username}{date}.{ext} which works as expected ie it becomes "model01-09-2019.mp4"
> 
> Use at your own risk given that is me deducing those options and it seems to work in my specific case

Thank you so much for this. It's really helpful!

**Comment by DIGITALCRIMINAL** [comment]
Ohh yeah, I'm building this script with Python 3.7 in mind

**Comment by DIGITALCRIMINAL** [comment]
I updated the script c:
Scroll down and you'll see the possible formats
https://github.com/DIGITALCRIMINAL/OnlyFans
