### ISSUE TITLE
error sqlalchemy missing but it isnt

### ISSUE THREAD

**Issue by masterdjboner** [DIGITALCRIMINAL/OnlyFans#1814]
please help im getting below saying it cant find sqlalchemy

Traceback (most recent call last):
  File "Z:\OnlyFans-master\start_ofd.py", line 26, in <module>
    main_test.check_config()
  File "Z:\OnlyFans-master\tests\main_test.py", line 20, in check_config
    import helpers.main_helper as main_helper
  File "Z:\OnlyFans-master\helpers\main_helper.py", line 2, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "Z:\OnlyFans-master\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

but i have it installed and when i do a pip list it shows
PS Z:\OnlyFans-master> pip list
Package            Version
------------------ ---------
aiohttp            3.8.1
aiohttp-socks      0.7.1
aiosignal          1.2.0
alembic            1.7.5
async-generator    1.10
async-timeout      4.0.2
attrs              21.2.0
beautifulsoup4     4.10.0
certifi            2021.5.30
cffi               1.15.0
chardet            4.0.0
charset-normalizer 2.0.9
colorama           0.4.4
commonmark         0.9.1
cryptography       36.0.1
frozenlist         1.2.0
gallery-dl         1.19.3
greenlet           1.1.0
h11                0.12.0
idna               2.10
jsonpickle         2.0.0
lxml               4.7.1
Mako               1.1.4
MarkupSafe         2.0.1
mergedeep          1.3.4
multidict          5.1.0
outcome            1.1.0
pip                21.3.1
psutil             5.8.0
pycparser          2.21
Pygments           2.10.0
pyOpenSSL          21.0.0
PySocks            1.7.1
python-dateutil    2.8.2
python-editor      1.0.4
python-socks       2.0.1
requests           2.26.0
rich               10.16.1
selenium           4.1.0
selenium-wire      2.1.2
setuptools         58.1.0
six                1.16.0
sniffio            1.2.0
sortedcontainers   2.4.0
soupsieve          2.2.1
SQLAlchemy         1.4.20
tqdm               4.62.3
trio               0.19.0
trio-websocket     0.9.2
typing-extensions  3.10.0.0
ujson              5.1.0
urllib3            1.26.6
user-agent         0.1.10
wheel              0.36.2
win32-setctime     1.0.4
wsproto            1.0.0
yarl               1.6.3

**Comment by NoCaffeine985** [comment]
yeah im having the same issue

**Comment by TheSinfulKing** [comment]
I'm also having this issue - is the script broken now?
