### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by RAR98** [DIGITALCRIMINAL/OnlyFans#1822]
I've entered my coockie and user agent in the file like asked, but everytime i get an access denied or sometimes i get an error and i get disconnected from my account on my browser. So it's trying to connect into my account

**Comment by OFRIPP** [comment]
Same error for me too.

**Comment by KayleeBarbosa** [comment]
As of the other day I'm having the same issue.  I update the cookie and then i get logged out of OF after the scraper gets access denied!

**Comment by vvglyy** [comment]
same here

**Comment by LucioSaldivar** [comment]
Why on earth would you close this issue without it being fixed??

**Comment by vvglyy** [comment]
was surprised too..
