### ISSUE TITLE
Access Denied 

### ISSUE THREAD

**Issue by LucioSaldivar** [DIGITALCRIMINAL/OnlyFans#1830]
So after installing and setting up exactly as one should do per instructions, I still end up getting access denied as well as get logged off from browser. Anyone know why this voice be happening?

**Comment by madara19** [comment]
Got the same issue here 
any solutions please ?

**Comment by god43** [comment]
yeah same issue access denied

**Comment by LucioSaldivar** [comment]
> yeah same issue access denied edit, i went through and updated my values and ts working again, make sure to include the hash after the = for the auth id from the cookie. and update your browser string.

What fiiles did you edit? and for which auth id are you talking about? as it has a few.

**Comment by LucioSaldivar** [comment]
Ok, so here's something that is not in any docs. YOU HAVE TO USE CHROME. Currently my browser is Brave after so many attempts I decided to use a different browser i.e chrome and to no surprise it worked.
