### ISSUE TITLE
Unable to open 'start_ofd.py'

### ISSUE THREAD

**Issue by jorelastin** [DIGITALCRIMINAL/OnlyFans#1847]
THis appears when I try to run it. I'm on python 3.10.

`PS C:\Users\jorel\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1> py .\start_ofd.py
Traceback (most recent call last):
  File "C:\Users\jorel\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1\start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'
PS C:\Users\jorel\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1>`

**Comment by Sesiroslanuseht** [comment]
the program is too difficult for a person who is not a coder .hahahah

**Comment by JohnwicK7382** [comment]
can you help me

**Comment by aizenn1** [comment]
> THis appears when I try to run it. I'm on python 3.10.
> 
> `PS C:\Users\jorel\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1> py .\start_ofd.py Traceback (most recent call last): File "C:\Users\jorel\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1\start_ofd.py", line 7, in <module> from rich import panel ModuleNotFoundError: No module named 'rich' PS C:\Users\jorel\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1>`

run this command: pip install rich
