### ISSUE TITLE
ValueError: Invalid isoformat string

### ISSUE THREAD

**Issue by mileyvirus** [DIGITALCRIMINAL/OnlyFans#19]
Hey @DIGITALCRIMINAL, great job with the filename wildcards! There's an issue that on my end happened only when downloading videos: it downloads photos just fine but when going to videos the script throws this error:

```
Photos Finished
Traceback (most recent call last):
  File "/OnlyFans-master/OnlyFans.py", line 172, in <module>
    scrape_choice()
  File "/OnlyFans-master/OnlyFans.py", line 83, in scrape_choice
    media_scraper(video_api, location, j_directory, only_links)
  File "/OnlyFans-master/OnlyFans.py", line 126, in media_scraper
    dt = datetime.fromisoformat(media_api["postedAt"]).replace(tzinfo=None).strftime('%d-%m-%Y')
ValueError: Invalid isoformat string: '-001-11-30T00:00:00+00:00'
```

I managed to make it shut up and download the precious porn by nulling `dt`:
`dt = "prettydolphins"`

but I'd love to have the real date if it's possible!

**Comment by DIGITALCRIMINAL** [comment]
An issue was open yesterday that they fixed this by updating to Python 3.7 (It's also the version I'm working with)

**Comment by mileyvirus** [comment]
I saw that but I'm on macOS and I also have Python 3.7 🤔
```
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
```

(I manually added #!/usr/bin/env python3 on top of the script)

**Comment by DIGITALCRIMINAL** [comment]
I see what's wrong with it.
It says this 
> -001-11-30
But it's supposed to be similar to this 01-11-30. I need to see a full dump. So I will create a new fork and message back when it's up for you to download

**Comment by DIGITALCRIMINAL** [comment]
There's no real way to solve that error since it's an invalid format on OnlyFans end. I will catch the error and transform the date into "00-00-0000"

**Comment by mileyvirus** [comment]
Dude almost the same error… ☹
How can I help?

```
Photos Completed
Traceback (most recent call last):
  File "/OnlyFans.py", line 143, in media_scraper
    dt = datetime.fromisoformat(media_api["postedAt"]).replace(tzinfo=None).strftime('%d-%m-%Y')
ValueError: Invalid isoformat string: '-001-11-30T00:00:00+00:00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/OnlyFans.py", line 223, in <module>
    scrape_choice()
  File "/OnlyFans.py", line 92, in scrape_choice
    media_scraper(video_api, location, j_directory, only_links)
  File "/OnlyFans.py", line 149, in media_scraper
    dt = datetime.strptime(found.replace("_", "-"), '%Y-%m-%d').strftime('%d-%m-%Y')
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2' does not match format '%Y-%m-%d'
```

**Comment by DIGITALCRIMINAL** [comment]
Did you update to the latest comit because I'm supposed to be catching this error

**Comment by mileyvirus** [comment]
Yes, I did! I'm using commit bd73222 on the master branch.

**Comment by DIGITALCRIMINAL** [comment]
Ah, it seems that the fallback method of getting the date doesn't work. I forgot to catch that datetime error as well. I'm not at home yet so I can't fix the code. If I were to get the real date I would need to see a dump of the json there too

**Comment by mileyvirus** [comment]
I sent you the resulting json response from 
`https://onlyfans.com/api2/v2/users/{redacted}/posts/videos?limit=10&offset=110&order=publish_date_desc&app-token={redacted}` via email at rarecoder@protonmail.com.

You'll see that the first video has that garbage `postedAt` date:
`postedAt: "-001-11-30T00:00:00+00:00"`

it's rare but I saw that at least 7 videos had that date.

**Comment by mileyvirus** [comment]
EDIT

I found the post with the same ID of one who had the `-001-11-30T00:00:00+00:00` date and it doesn't show a date on OnlyFans so it's probably a placeholder that means that no date was specified on upload or something. Usually the media URLs have the date inside but these faulty ones don't.

**Comment by DIGITALCRIMINAL** [comment]
Ahh okay, nice. I will just filter that out and hopefully, it will be fixed c:

**Comment by DIGITALCRIMINAL** [comment]
Updated the script

**Comment by mileyvirus** [comment]
Thank you, latest commits successfully caught the error and now my dump is complete!
You're on fire with this repo bruh 🔥

**Comment by DIGITALCRIMINAL** [comment]
I also forgot to mention that if the date matches the template date, the script will either use the last grabbed date OR use the 00-00-0000 date.
I forgot to add this feature in. 
```
else:
      dt = datetime.fromisoformat(media_api["postedAt"]).replace(tzinfo=None).strftime(date_format)
      master_date = dt
```

I updated onlyfans.py

**Comment by mileyvirus** [comment]
Hmm 🤔, I don't get it. Right now I see I have some 00-00-0000 files so I don't understand what you're mentioning.

Do you think I should redump my profile?

**Comment by DIGITALCRIMINAL** [comment]
Oh yeah, you'll need to rescrape the profile to see the change. You should see one template date or none at all. They should all have dates.
