### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINAL/OnlyFans#1926]
Hi,

I'm having this issue, and I can't access, it says: "Access denied":

![image](https://user-images.githubusercontent.com/81478245/190668078-fb79c7bd-8765-4fdd-be7a-b5cc35157b2c.png)

Please, help me.

Thanks.

**Comment by hafiz-muhammad** [comment]
You have to edit your **`.profiles/default/auth.json`** first as it shows in the tutorial. That's why it's returning **_Access denied._**

**Comment by djmarioka** [comment]
I've tried to changing the password, but I'm always disconnected, I don't know if I've been flagged for something, or what, the error now is: "Something went wrong. [BB91C8D6]", and I'm always unlogged when I execute the script start_ofd.py:

![image](https://user-images.githubusercontent.com/81478245/190831587-529cd260-8686-4fd4-b7c1-8216905ab5bf.png)


Please, help me.

Thanks.

**Comment by djmarioka** [comment]
Hi, I cleared all the cookies in Chrome, and with these 2 commands, it worked well:

pip install poetry
poetry install --no-dev

And then, to run the script:

poetry run python ./start_ofd.py

Specially, I think the command that worked well was this one: **poetry install --no-dev**

Thanks.
