### ISSUE TITLE
BUG: User Not Found

### ISSUE THREAD

**Issue by cooperpellaton** [DIGITALCRIMINAL/OnlyFans#2]
`settings.json` has been properly populated. After installing requirements and running `python OnlyFans.py` and then inputting a username, the return is `User Not Found`. I've tried running with username, profile link, userid from `https://onlyfans.com/api2/v2/users/` and the preceding link with the `userid`. All return the same.

**Comment by DIGITALCRIMINAL** [comment]
Gonna look into this now

**Comment by Lambrusko** [comment]
same problem for me

**Comment by Lambrusko** [comment]
but this is what i answered this has to be subscribed to worked .

**Comment by cooperpellaton** [comment]
> Gonna look into this now. Which username are you trying to find? You're also subscribed to the username right

Yes, I am subscribed. The example username is `sweetpeachxo`.

**Comment by DIGITALCRIMINAL** [comment]
@cooperpellaton I debugged it and I am getting results for sweetpeachxo. 
I did update the error handling for `Users Not Found` on the script as of writing this. Let me know what it says.

If it doesn't work, and you're certain you copied and pasted the right sess cookie, it could be that you're using the wrong user-agent. You must also be still logged in on the browser for it to work. I'm using Chrome Browser by the way and I found results for sweetpeachxo.

**Comment by cooperpellaton** [comment]
Odd. Works now. I'm certain that the params were right before though. Thanks for the patch.

**Comment by MikeDoesStuff** [comment]
Suddenly also getting this error, working fine yesterday but suddenly not today. Any ideas on how to fix it or is it just a wait it out and it'll come back to life situation?

**Comment by DIGITALCRIMINAL** [comment]
whats the username you're trying to find?

**Comment by MikeDoesStuff** [comment]
> whats the username you're trying to find?

Tried on the user "saavyy", its worked before for that profile so not sure whats happening

**Comment by DIGITALCRIMINAL** [comment]
> saavyy

Weird lol. OnlyFans is still updating its API every other week, so it's probably just that.
