### ISSUE TITLE
Tree builder

### ISSUE THREAD

**Issue by VeryStrangeUsername** [DIGITALCRIMINAL/OnlyFans#200]
I'm getting
`raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?` 

Even though that I have all requirements installed.
`Requirement already satisfied: requests in ./rippingenv/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: beautifulsoup4 in ./rippingenv/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (4.9.0)
Requirement already satisfied: urllib3 in ./rippingenv/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (1.25.8)
Requirement already satisfied: win32-setctime in ./rippingenv/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: lxml in ./rippingenv/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (4.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./rippingenv/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in ./rippingenv/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in ./rippingenv/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: soupsieve>1.2 in ./rippingenv/lib/python3.6/site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.0)`

**Comment by 180ml** [comment]
You're using Python 3.6. Upgrade to Python 3.8.
