### ISSUE TITLE
Please Refresh Page 2023

### ISSUE THREAD

**Issue by patchcad** [DIGITALCRIMINAL/OnlyFans#2002]
Has it just stopped working for anyone else? Getting the "Please Refresh Page" error again.

**Comment by DonaldTPP** [comment]
Did the error continue for you or did it stop and that's why you closed it?

**Comment by patchcad** [comment]
It stopped eventually. There's another thread about this here:

https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/1024

**Comment by DonaldTPP** [comment]
> It stopped eventually. There's another thread about this here:
> 
> [DIGITALCRIMINALS/UltimaScraper#1024](https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/1024)

I just tested it myself after fixing it and it's telling me to install GeckoDriver.
