### ISSUE TITLE
Disable download / Scrape json file only

### ISSUE THREAD

**Issue by Odin21100** [DIGITALCRIMINAL/OnlyFans#201]
I wondering if there is a way to mod the script to disable the auto download and have the scrapper just scrape the sources and save them as a json file?

**Comment by 180ml** [comment]
This feature already exists. See the `README`. Just use the `-l` option when calling the file from the command line:

`python StartDataScraper.py -l`

**Comment by Odin21100** [comment]
Much appreciated, still new to the whole coding and understanding of commands.

**Comment by DIGITALCRIMINAL** [comment]
> This feature already exists. See the `README`. Just use the `-l` option when calling the file from the command line:
> 
> `python StartDataScraper.py -l`

https://github.com/DIGITALCRIMINAL/OnlyFans#OPTIONAL_ARGUMENTS
Oof, just fixed this setting. I've changed it to "StartDatascraper -m"
