### ISSUE TITLE
ImportError: No module named modules.onlyfans

### ISSUE THREAD

**Issue by brianmccarthy000** [DIGITALCRIMINAL/OnlyFans#204]
When I try to run the StartDatascraper.py, in Terminal (MacOS), I get the following error

`Traceback (most recent call last):
  File "/file/path/StartDatascraper.py", line 2, in <module>
    import modules.onlyfans as onlyfans
ImportError: No module named modules.onlyfans
`
Not sure how to diagnose. I understand this was written on Windows in Powershell but any help would be appreciated

**Comment by DIGITALCRIMINAL** [comment]
It was coded in Python on a Windows machine. Try clicking the StartDatascraper.py instead.

**Comment by brianmccarthy000** [comment]
I did that. It did not work
