### ISSUE TITLE
Noob

### ISSUE THREAD

**Issue by tmrod25** [DIGITALCRIMINAL/OnlyFans#205]
This is my first time doing this and Im very confused. I was able to get the information (auth id, auth hash, etc.) I also downloaded python as 3.8 (32-bit). I dont understand where to began from here.

**Comment by tmrod25** [comment]
Ive also tried to the put in the pip command into the cmd and get this:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by DIGITALCRIMINAL** [comment]
open cmd within the script folder

**Comment by tmrod25** [comment]
The script folder would be the "settings" one correct? How would I open cmd using the the folder, do i just open the folder then wind+r or is there another way?

**Comment by tmrod25** [comment]
I finally installed the requirements. Now it says to open the config.json  file. What do I open it with?Every time I try to open it with python 3.8.2 (32-bit), it always opens a new window that says Modify setup with 3 choices saying, Modify, Repair, and Uninstall.

**Comment by DIGITALCRIMINAL** [comment]
open config.json with notepad

**Comment by tmrod25** [comment]
I filled in the required areas and some of the optional ones too. Now how do I use 
"python StartDatascraper.py" and what are the inputs required by the console?

**Comment by DIGITALCRIMINAL** [comment]
Open CMD inside the folder where StartDatascraper.py is and enter in that command

**Comment by tmrod25** [comment]
I entered it and that a bunch of script starting popping up fast and the CMD just closed. Does that mean I did it right?

**Comment by DIGITALCRIMINAL** [comment]
Open StartDatascrper.py with the Python 3.8 IDLE and run the script from there to catch errors.

**Comment by tmrod25** [comment]
So I when I try to open the StartDatascraper with python it opens and closes right away. So I just copied the script from this website and paste it in python. However I get a bunch of syntax errors, indentation errors, module not found errors, and name errors.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, it doesn't work like that. You can't just copy and paste stuff over.

**Comment by DIGITALCRIMINAL** [comment]
Open StartDatascraper.py with the Python IDLE instead of opening it normally.

**Comment by DIGITALCRIMINAL** [comment]
If you want we can do a screen share session or something

**Comment by tmrod25** [comment]
I found the Idle python lol. But i think im getting the same issue as #204 it says ModuleNotFoundError: No module named 'modules'

**Comment by DIGITALCRIMINAL** [comment]
Copy and paste the error here pls

**Comment by tmrod25** [comment]
Traceback (most recent call last):
  File "C:\Users\tmrod\Downloads\StartDatascraper.py", line 2, in <module>
    import modules.onlyfans as onlyfans
ModuleNotFoundError: No module named 'modules'

**Comment by DIGITALCRIMINAL** [comment]
what does the folder that contains StartDatascraper.py

**Comment by tmrod25** [comment]
![folder pic](https://user-images.githubusercontent.com/63677423/79519259-9a03e500-8010-11ea-8379-990f00d1a612.PNG)

But I opened and ran it using python idle

**Comment by tmrod25** [comment]
![idle](https://user-images.githubusercontent.com/63677423/79519552-683f4e00-8011-11ea-8727-ca721b2f9da1.PNG)

**Comment by tmrod25** [comment]
Well I barely figured out how to enter the " python StartDatascraper.py " command in cmd. It then gives me this, " Site: 0 = onlyfans | 1 = stars_avn | 2 = 4chan | 3 = bbwchan ". And if I press enter key it says  2020-04-17 03:04:56,337 ERROR errors invalid literal for int() with base 10: ''
                  Traceback (most recent call last):
                  File "StartDatascraper.py", line 58, in <module>
                  x = int(input())
                  ValueError: invalid literal for int() with base 10: ''
Not sure what to do from there :(

**Comment by tmrod25** [comment]
Okay nvm again I read that you have to type in 0 smh. However now im getting the problem where it says access denied, youre not subscribed

**Comment by tmrod25** [comment]
I think I got it. How do you access the photos. It showed a free account that I unfollowed. But im trying to scrape a specific account.

**Comment by tmrod25** [comment]
Wait do I have to be subscribed to the specific  account?

**Comment by DIGITALCRIMINAL** [comment]
Yes you have to be subscribed to download content

**Comment by tmrod25** [comment]
GG  I genuinely thought doing all this was to access accounts content without having to subscribe. I mean if that is possible let me know. Anyways thank you for guiding me through and in the end it was so easy, I literally over complicated it.   ily

**Comment by DIGITALCRIMINAL** [comment]
It actually used to be possible but OF patched the public way of getting free content :/
