### ISSUE TITLE
AttributeError - Windows 10

### ISSUE THREAD

**Issue by xD3CrypTionz** [DIGITALCRIMINAL/OnlyFans#208]
Running this command from a command window inside the script folder ```python StartDatascraper.py``` and receive this error
```
Traceback (most recent call last):
  File "StartDatascraper.py", line 20, in <module>
    log_error = helpers.setup_logger('errors', 'errors.log')
AttributeError: module 'modules.helpers' has no attribute 'setup_logger'
``

**Comment by DIGITALCRIMINAL** [comment]
Ffs

**Comment by DIGITALCRIMINAL** [comment]
Please download the latest commit.

@aboredpervert

**Comment by xD3CrypTionz** [comment]
Why the frustration. I followed your instructions in the guide you wrote. I think you need to be more clear on what you did to get it to run because I keep having issues trying to get the damn thing to work.

```pip install -r requirements.txt``` works fine but brings up an error ``` Failed building wheel for lxml```

I had to manually create the folders in modules folder and put the ``.py`` files into their respective folders

Then I opened up the cmd from the script folder and wrote ``python StartDatascraper.py``  which brings up the error message i initially posted before.

**Comment by DIGITALCRIMINAL** [comment]
??? 
The instructions are clear and thousands of people have downloaded this and never have I heard of manually creating folders. This isn't because of me.



> Why the frustration. I followed your instructions in the guide you wrote. I think you need to be more clear on what you did to get it to run because I keep having issues trying to get the damn thing to work.
> 
> `pip install -r requirements.txt` works fine but brings up an error
> 
> ```
> Failed to build lxml
> Installing collected packages: lxml
>   Running setup.py install for lxml
>     Complete output from command c:\users\xD3CrypTionz\appdata\local\programs\python\python38-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\xD3CrypTionz\\AppData\\Local\\Temp\\pip-build-13gvkriv\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\xD3CrypTionz\AppData\Local\Temp\pip-2km3hzt6-record\install-record.txt --single-version-externally-managed --compile:
>     Building lxml version 4.5.0.
>     Building without Cython.
>     ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
>     ** make sure the development packages of libxml2 and libxslt are installed **
> 
>     Using build configuration of libxslt
>     running install
>     running build
>     running build_py
>     running build_ext
>     building 'lxml.etree' extension
>     error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
> 
>     ----------------------------------------
> Command "c:\users\xD3CrypTionz\appdata\local\programs\python\python38-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\xD3CrypTionz\\AppData\\Local\\Temp\\pip-build-13gvkriv\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\xD3CrypTionz\AppData\Local\Temp\pip-2km3hzt6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\xD3CrypTionz\AppData\Local\Temp\pip-build-13gvkriv\lxml
> ```
> 
> I had to manually create the folders in modules folder and put the `.py` files into their respective folders
> 
> Then I opened up the cmd from the script folder and wrote `python StartDatascraper.py` which brings up the error message i initially posted before.

The fix for this is literally where it says "error".

**Comment by xD3CrypTionz** [comment]
> ???
> The instructions are clear and thousands of people have downloaded this and never have I heard of manually creating folders. This isn't because of me.



> 
> 
> ???
> The instructions are clear and thousands of people have downloaded this and never have I heard of manually creating folders. This isn't because of me.
> 
> > Why the frustration. I followed your instructions in the guide you wrote. I think you need to be more clear on what you did to get it to run because I keep having issues trying to get the damn thing to work.
> > `pip install -r requirements.txt` works fine but brings up an error
> > ```
> > Failed to build lxml
> > Installing collected packages: lxml
> >   Running setup.py install for lxml
> >     Complete output from command c:\users\xD3CrypTionz\appdata\local\programs\python\python38-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\xD3CrypTionz\\AppData\\Local\\Temp\\pip-build-13gvkriv\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\xD3CrypTionz\AppData\Local\Temp\pip-2km3hzt6-record\install-record.txt --single-version-externally-managed --compile:
> >     Building lxml version 4.5.0.
> >     Building without Cython.
> >     ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
> >     ** make sure the development packages of libxml2 and libxslt are installed **
> > 
> >     Using build configuration of libxslt
> >     running install
> >     running build
> >     running build_py
> >     running build_ext
> >     building 'lxml.etree' extension
> >     error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
> > 
> >     ----------------------------------------
> > Command "c:\users\xD3CrypTionz\appdata\local\programs\python\python38-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\xD3CrypTionz\\AppData\\Local\\Temp\\pip-build-13gvkriv\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\xD3CrypTionz\AppData\Local\Temp\pip-2km3hzt6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\xD3CrypTionz\AppData\Local\Temp\pip-build-13gvkriv\lxml
> > ```
> > 
> > 
> > I had to manually create the folders in modules folder and put the `.py` files into their respective folders
> > Then I opened up the cmd from the script folder and wrote `python StartDatascraper.py` which brings up the error message i initially posted before.
> 
> The fix for this is literally where it says "error".

I'll try download the Microsoft Visual C++ 14.0 tool set and report back. Might be worth mentioning it as part of the build as I didn't know you had to have this installed for some things to work.

**Comment by DIGITALCRIMINAL** [comment]
> > ???
> > The instructions are clear and thousands of people have downloaded this and never have I heard of manually creating folders. This isn't because of me.
> 
> > The fix for this is literally where it says "error".
> 
> I'll try download the Microsoft Visual C++ 14.0 tool set and report back. Might be worth mentioning it as part of the build as I didn't know you had to have this installed for some things to work.

It already shows an error message and tells you what to do to fix it? What more do you want from that?
If I was to handhold and include error messages like that in the script, you'd be downloading a 1GB+ Readme.

**Comment by xD3CrypTionz** [comment]
Okay so I installed the Microsoft Visual C++ Studio and its toolset.

Now I'm getting this error when running the ``StartDatascraper.py`` command

```
2020-04-16 20:28:04,290 ERROR errors Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
Traceback (most recent call last):
  File "StartDatascraper.py", line 170, in <module>
    result = x.start_datascraper(
  File "E:\OnlyFans\modules\onlyfans.py", line 87, in start_datascraper
    results = media_scraper(
  File "E:\OnlyFans\modules\onlyfans.py", line 428, in media_scraper
    x = pool.starmap(scrape_array, product(
  File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Zach\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "E:\OnlyFans\modules\onlyfans.py", line 310, in scrape_array
    file_path = reformat(directory[0][1], media_id, file_name,
  File "E:\OnlyFans\modules\helpers.py", line 42, in reformat
    text = BeautifulSoup(text, 'lxml').get_text().replace(
  File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bs4\__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```
Funny thing is I installed lxml from: https://pypi.org/project/lxml/3.4.1/

**Comment by DIGITALCRIMINAL** [comment]
> Okay so I installed the Microsoft Visual C++ Studio and its toolset.
> 
> Now I'm getting this error when running the `StartDatascraper.py` command
> 
> ```
> 2020-04-16 20:28:04,290 ERROR errors Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
> Traceback (most recent call last):
>   File "StartDatascraper.py", line 170, in <module>
>     result = x.start_datascraper(
>   File "E:\OnlyFans\modules\onlyfans.py", line 87, in start_datascraper
>     results = media_scraper(
>   File "E:\OnlyFans\modules\onlyfans.py", line 428, in media_scraper
>     x = pool.starmap(scrape_array, product(
>   File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 372, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 768, in get
>     raise self._value
>   File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "E:\OnlyFans\modules\onlyfans.py", line 310, in scrape_array
>     file_path = reformat(directory[0][1], media_id, file_name,
>   File "E:\OnlyFans\modules\helpers.py", line 42, in reformat
>     text = BeautifulSoup(text, 'lxml').get_text().replace(
>   File "C:\Users\xD3CrypTionz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bs4\__init__.py", line 225, in __init__
>     raise FeatureNotFound(
> bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
> ```
> 
> Funny thing is I installed lxml from: https://pypi.org/project/lxml/3.4.1/

Wrong LXML.
![image](https://user-images.githubusercontent.com/21285176/79446505-352b9900-7fd6-11ea-9895-400bd01fa459.png)

**Comment by xD3CrypTionz** [comment]
I'm sorry, I know I'm probably driving you mad right now. But I cant seem to get this right, this is such a nightmare for someone who is only just starting out their coding journey

```
C:\Windows\system32>pip install lxml
Collecting lxml
  Using cached https://files.pythonhosted.org/packages/39/2b/0a66d5436f237aff76b91e68b4d8c041d145ad0a2cdeefe2c42f76ba2857/lxml-4.5.0.tar.gz
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml
  Complete output from command c:\users\zach\appdata\local\programs\python\python38-32\python.exe -c "import setuptools;__file__='C:\\Users\\Zach\\AppData\\Local\\Temp\\pip-build-5ncd6g_m\\lxml\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\Zach\AppData\Local\Temp\tmpn5vt565fpip-wheel-:
  Building lxml version 4.5.0.
  Building without Cython.
  ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
  ** make sure the development packages of libxml2 and libxslt are installed **

  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  creating build\lib.win32-3.8\lxml
  copying src\lxml\builder.py -> build\lib.win32-3.8\lxml
  copying src\lxml\cssselect.py -> build\lib.win32-3.8\lxml
  copying src\lxml\doctestcompare.py -> build\lib.win32-3.8\lxml
  copying src\lxml\ElementInclude.py -> build\lib.win32-3.8\lxml
  copying src\lxml\pyclasslookup.py -> build\lib.win32-3.8\lxml
  copying src\lxml\sax.py -> build\lib.win32-3.8\lxml
  copying src\lxml\usedoctest.py -> build\lib.win32-3.8\lxml
  copying src\lxml\_elementpath.py -> build\lib.win32-3.8\lxml
  copying src\lxml\__init__.py -> build\lib.win32-3.8\lxml
  creating build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\__init__.py -> build\lib.win32-3.8\lxml\includes
  creating build\lib.win32-3.8\lxml\html
  copying src\lxml\html\builder.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\clean.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\defs.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\diff.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\ElementSoup.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\formfill.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\html5parser.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\soupparser.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\usedoctest.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\_diffcommand.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\_html5builder.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\_setmixin.py -> build\lib.win32-3.8\lxml\html
  copying src\lxml\html\__init__.py -> build\lib.win32-3.8\lxml\html
  creating build\lib.win32-3.8\lxml\isoschematron
  copying src\lxml\isoschematron\__init__.py -> build\lib.win32-3.8\lxml\isoschematron
  copying src\lxml\etree.h -> build\lib.win32-3.8\lxml
  copying src\lxml\etree_api.h -> build\lib.win32-3.8\lxml
  copying src\lxml\lxml.etree.h -> build\lib.win32-3.8\lxml
  copying src\lxml\lxml.etree_api.h -> build\lib.win32-3.8\lxml
  copying src\lxml\includes\c14n.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\config.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\dtdvalid.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\etreepublic.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\htmlparser.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\relaxng.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\schematron.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\tree.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\uri.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\xinclude.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\xmlerror.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\xmlparser.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\xmlschema.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\xpath.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\xslt.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\__init__.pxd -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\etree_defs.h -> build\lib.win32-3.8\lxml\includes
  copying src\lxml\includes\lxml-version.h -> build\lib.win32-3.8\lxml\includes
  creating build\lib.win32-3.8\lxml\isoschematron\resources
  creating build\lib.win32-3.8\lxml\isoschematron\resources\rng
  copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win32-3.8\lxml\isoschematron\resources\rng
  creating build\lib.win32-3.8\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win32-3.8\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win32-3.8\lxml\isoschematron\resources\xsl
  creating build\lib.win32-3.8\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win32-3.8\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win32-3.8\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win32-3.8\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win32-3.8\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win32-3.8\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win32-3.8\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build\temp.win32-3.8
  creating build\temp.win32-3.8\Release
  creating build\temp.win32-3.8\Release\src
  creating build\temp.win32-3.8\Release\src\lxml
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc\lxml\includes -Ic:\users\zach\appdata\local\programs\python\python38-32\include -Ic:\users\zach\appdata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc\lxml\etree.c /Fobuild\temp.win32-3.8\Release\src\lxml\etree.obj -w
  cl : Command line warning D9025 : overriding '/W3' with '/w'
  etree.c
  C:\Users\Zach\AppData\Local\Temp\pip-build-5ncd6g_m\lxml\src\lxml\includes/etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
  Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  creating Users
  creating Users\Zach
  creating Users\Zach\AppData
  creating Users\Zach\AppData\Local
  creating Users\Zach\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /TcC:\Users\Zach\AppData\Local\Temp\xmlXPathInitxq70gqb7.c /FoUsers\Zach\AppData\Local\Temp\xmlXPathInitxq70gqb7.obj
  xmlXPathInitxq70gqb7.c
  C:\Users\Zach\AppData\Local\Temp\xmlXPathInitxq70gqb7.c(1): fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************

  ----------------------------------------
  Failed building wheel for lxml
Failed to build lxml
Installing collected packages: lxml
  Running setup.py install for lxml
    Complete output from command c:\users\zach\appdata\local\programs\python\python38-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Zach\\AppData\\Local\\Temp\\pip-build-5ncd6g_m\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Zach\AppData\Local\Temp\pip-a4ncmel1-record\install-record.txt --single-version-externally-managed --compile:
    Building lxml version 4.5.0.
    Building without Cython.
    ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    running install
    running build
    running build_py
    running build_ext
    building 'lxml.etree' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc\lxml\includes -Ic:\users\zach\appdata\local\programs\python\python38-32\include -Ic:\users\zach\appdata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc\lxml\etree.c /Fobuild\temp.win32-3.8\Release\src\lxml\etree.obj -w
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    etree.c
    C:\Users\Zach\AppData\Local\Temp\pip-build-5ncd6g_m\lxml\src\lxml\includes/etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
    Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /TcC:\Users\Zach\AppData\Local\Temp\xmlXPathInit5b7rl466.c /FoUsers\Zach\AppData\Local\Temp\xmlXPathInit5b7rl466.obj
    xmlXPathInit5b7rl466.c
    C:\Users\Zach\AppData\Local\Temp\xmlXPathInit5b7rl466.c(1): fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************

    ----------------------------------------
Command "c:\users\zach\appdata\local\programs\python\python38-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Zach\\AppData\\Local\\Temp\\pip-build-5ncd6g_m\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Zach\AppData\Local\Temp\pip-a4ncmel1-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Zach\AppData\Local\Temp\pip-build-5ncd6g_m\lxml
```

**Comment by DIGITALCRIMINAL** [comment]
Search on google for your errors with the package

**Comment by xD3CrypTionz** [comment]
Yeah I give up on trying to get ``lxml`` to install.. None of the new ``lxml 4.5.0`` packages for ``python 3.8`` seem to work. Even bloody linux/ubuntu has the same issue with ``python3.8``

Really don't know how people are managing to get this to work -.-
