### ISSUE TITLE
Auth Error

### ISSUE THREAD

**Issue by elwoodflame** [DIGITALCRIMINAL/OnlyFans#21]
Not sure if I have editted the json file correct or not but I keep getting this error any help would be appreciated.
Traceback (most recent call last):
  File "onlyfans.py", line 14, in <module>
    j_directory = json_data['directory']+"/Users/"
KeyError: 'directory'

**Comment by DIGITALCRIMINAL** [comment]
I'm assuming you actually edited "directory".
When you edit the directory value, it's supposed to **go from this:**
`"directory":""`
 **To this:**
`"directory":"some/folder"`

**Comment by DIGITALCRIMINAL** [comment]
Also, I'm updating the script in 5 minutes, so you might as well wait :p

**Comment by elwoodflame** [comment]
> I'm assuming you actually edited "directory".
> When you edit the directory value, it's supposed to **go from this:**
> `"directory":""`
> **To this:**
> `"directory":"some/folder"`
> Also, I'm updating the script in 10 minutes, so you might as well wait :p

this is my file i eddited I left out my unique info.
{"":"","luciloser_sgh":"{file_name}.{ext}","my number":"","sess number":"","Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36":""}

**Comment by DIGITALCRIMINAL** [comment]
@elwoodflame I just updated the script.

If you want to change the directory, it has to be like this
`{"directory":"some/folder","luciloser_sgh":"{file_name}.{ext}","my number":"","sess number":"","Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36":""}`

**Comment by elwoodflame** [comment]
Figured out from your previous post what I was doing wrong Now i get this error.
Access denied.
First time? Did you forget to edit your settings.json file?
Input a username or profile link

**Comment by DIGITALCRIMINAL** [comment]
Have you downloaded the new script?

**Comment by elwoodflame** [comment]
doing so now

**Comment by DIGITALCRIMINAL** [comment]
It should work if you follow the same rule as
`"directory":"some/folder"`
`"sess":"sess_number"`

and so on

**Comment by elwoodflame** [comment]
what do I put for auto choice

**Comment by DIGITALCRIMINAL** [comment]
> what do I put for auto choice

auto_choice can be blank

**Comment by elwoodflame** [comment]
I get this error now
You're not subscribed to the user
First time? Did you forget to edit your settings.json file?
Input a username or profile link

I am a subscribed user

**Comment by DIGITALCRIMINAL** [comment]
What does your settings.json look like? (Remove the sensitive information again)

**Comment by elwoodflame** [comment]
{"directory":"luciloser","file_name_format":"{file_name}.{ext}","auto_choice": "", "overwrite_files": true,"app-token":"33***********","sess":"********","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"}

**Comment by elwoodflame** [comment]
![settings](https://user-images.githubusercontent.com/7619774/64151815-0adaf180-cde0-11e9-994e-03a828855579.jpg)

**Comment by DIGITALCRIMINAL** [comment]
Are you running the script on the same computer as the one you logged into?

**Comment by elwoodflame** [comment]
yes 

also Input a username or profile link this refers to what?  https://onlyfans.com/luciloser_sgh

**Comment by DIGITALCRIMINAL** [comment]
This
`https://onlyfans.com/luciloser_sgh`
or
`luciloser_sgh`

By the way, a folder called "luciloser_sgh" will be automatically created. You can remove it from the directory c:

**Comment by elwoodflame** [comment]
I still get You're not subscribed to the user not sure why I can go to only fans and view everything.

**Comment by DIGITALCRIMINAL** [comment]
Go here
https://onlyfans.com/my/subscribes/active
And screenshot what it looks like

**Comment by elwoodflame** [comment]
![active](https://user-images.githubusercontent.com/7619774/64152802-3232be00-cde2-11e9-981e-d59519daa9bc.jpg)

**Comment by DIGITALCRIMINAL** [comment]
Ohh did you just sub today?

**Comment by elwoodflame** [comment]
yes

**Comment by DIGITALCRIMINAL** [comment]
Go here
https://onlyfans.com/api2/v2/users/luciloser_sgh?app-token=APP_TOKEN

Replace APP_TOKEN with your app token.
Copy and paste the json here. There should be no sensitive information but you can double-check.

**Comment by DIGITALCRIMINAL** [comment]
I edited my text

**Comment by elwoodflame** [comment]
{"id":9901711,"name":"LuciLoser","username":"luciloser_sgh","avatar":"https:\/\/cdn.onlyfans.com\/Protected\/\/e5d18e2b315890bd04eba72ef63b22bbfbba1b90fc040212f5c188446a6303e8\/files\/i\/it\/iti\/itigtweyx3wgtqyb34sjgxajuym98zku1563741787\/IMG_20190720_131331_181.jpg","avatarThumbs":{"w50":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/b1bbc00f1c2aaf27e46d520b7db2eb3fc1ab57bb628dddb6123a5f84e2571ca0\/files\/thumbs\/w50\/i\/it\/iti\/itigtweyx3wgtqyb34sjgxajuym98zku1563741787\/IMG_20190720_131331_181.jpg","w67":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/5d720598b46e856a23c7b5d38e932d9c5485a95117a81be180df582f6ed98c5e\/files\/thumbs\/w67\/i\/it\/iti\/itigtweyx3wgtqyb34sjgxajuym98zku1563741787\/IMG_20190720_131331_181.jpg","w150":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/5d83c8078e0e0cde23779ce7e39d0a2b1ce5b104a3c7874a439844ba45c60516\/files\/thumbs\/w150\/i\/it\/iti\/itigtweyx3wgtqyb34sjgxajuym98zku1563741787\/IMG_20190720_131331_181.jpg","w480":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/1bada8d0c3909b311b278bc1eb0eee0fd1ba52ddd4d1b36cd27a4f824a785076\/files\/thumbs\/w480\/i\/it\/iti\/itigtweyx3wgtqyb34sjgxajuym98zku1563741787\/IMG_20190720_131331_181.jpg","w760":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/6af3e71259d5b9bf36d5de54fed1c7537829ed84b72a3fa186353d124f5ff3fc\/files\/thumbs\/w760\/i\/it\/iti\/itigtweyx3wgtqyb34sjgxajuym98zku1563741787\/IMG_20190720_131331_181.jpg"},"header":"https:\/\/cdn.onlyfans.com\/Protected\/\/58adef22c977c3e4df24b0f8960c92bedb72d8d84e8287d569f83edc26db5bef\/files\/v\/vu\/vuk\/vukz7wzl54peyu7ewre3yphtnxvavng31563741787\/IMG_20190625_193135_567.jpg","headerSize":{"width":1600,"height":1066},"headerThumbs":{"w50":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/7de43c4e23d17e5595b0a7fd250d2c43b41d19c4e0daf9514f8da1b19b24e222\/files\/thumbs\/w50\/v\/vu\/vuk\/vukz7wzl54peyu7ewre3yphtnxvavng31563741787\/IMG_20190625_193135_567.jpg","w67":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;\/0a220e8faaa5fbb0a134d75c590935f012d67c14fe82d145293a4b7f60b8453c\/files\/thumbs\/w67\/v\/vu\/vuk\/vukz7wzl54peyu7ewre3yphtnxvavng31563741787\/IMG_20190625_193135_567.jpg","w150":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/c1449a2a3b180e31455e8cb5143caa5b30d04959daba223df6050f6a58c2b59d\/files\/thumbs\/w150\/v\/vu\/vuk\/vukz7wzl54peyu7ewre3yphtnxvavng31563741787\/IMG_20190625_193135_567.jpg","w480":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/bc5e304238a6740baabd65064d5b258c0a45783afe4812d2f22debd0e3a44446\/files\/thumbs\/w480\/v\/vu\/vuk\/vukz7wzl54peyu7ewre3yphtnxvavng31563741787\/IMG_20190625_193135_567.jpg","w760":"https:\/\/cdn.onlyfans.com\/Protected\/expiretime=1567555200;ip=\/944ea44af127338307751ea7a3121ddc29feb7d70cb7bfe99fcac5c4801f5e23\/files\/thumbs\/w760\/v\/vu\/vuk\/vukz7wzl54peyu7ewre3yphtnxvavng31563741787\/IMG_20190625_193135_567.jpg"},"defaultAvatar":"https:\/\/onlyfans.com\/theme\/onlyfans\/images\/default_avatar.png?rev=16920","defaultHeader":"https:\/\/onlyfans.com\/theme\/onlyfans\/images\/default_header_image.jpg?rev=16920","hasStream":false,"payerRating":null,"isDeleted":false,"isVerified":true,"tipsEnabled":true,"canEarn":true,"canAddSubscriber":true,"subscribePrice":7.99,"gender":0,"twitterUsername":"luciloser","subscribedByExpire":false,"subscribedByExpireDate":"2019-10-03T03:31:44+00:00","subscribedByDate":"2019-09-03T03:31:44+00:00","subscribedByAutoprolong":true,"subscribedBy":true,"currentSubscribePrice":"7.99","subscribedIsExpiredNow":false,"subscribedOnExpire":null,"subscribedOnExpireDate":null,"subscribedOnDate":null,"subscribedOnAutoprolong":null,"subscribedOn":false,"subscribedOnExpiredNow":null,"isMuted":false,"joinDate":"2019-07-01T00:00:00+00:00","isPrivate":false,"isPrivateRestriction":false,"isSpotifyConnected":false,"isReferrerAllowed":true,"about":"Official Only Fans for SuicideGirls Hopeful Luciloser. <span class=\"emoji-outer emoji-sizer\"><span class=\"emoji-inner emoji1f49b\"><\/span><\/span> Subscribe for my LuciLewds!<br \/>\n<br \/>\nAbout my OnlyFans: I upload daily. YES DAILY. You can expect explicit content! <br \/>\n<br \/>\nA rapidly growing collection of Videos and Photos with lots already available the moment you subscribe.<br \/>\n<br \/>\nAll content is exclusive to my Only Fans. You won't see this anywhere else! I can do special requests for $ tips $ on a case by case basis just send me a DM with your proposal!","rawAbout":"Official Only Fans for SuicideGirls Hopeful Luciloser. \ud83d\udc9b Subscribe for my LuciLewds!<br \/>\n<br \/>\nAbout my OnlyFans: I upload daily. YES DAILY. You can expect explicit content! <br \/>\n<br \/>\nA rapidly growing collection of Videos and Photos with lots already available the moment you subscribe.<br \/>\n<br \/>\nAll content is exclusive to my Only Fans. You won't see this anywhere else! I can do special requests for $ tips $ on a case by case basis just send me a DM with your proposal!","website":"https:\/\/www.suicidegirls.com\/members\/luciloser\/?aid=1052127","location":"Pacific North West","postsCount":101,"photosCount":299,"videosCount":22,"audiosCount":0,"lastSeen":"2019-09-03T07:34:25+00:00","favoritesCount":188,"favoritedCount":482,"showPostsInFeed":true,"canReceiveChatMessage":true,"canCreatePromotion":true,"isPerformer":true,"isWantComments":true,"showSubscribersCount":false,"subscribersCount":null,"isXXXContent":true,"isFriend":false,"isBlocked":false,"friends":[],"minPayoutSumm":"100.00","canTrialSend":false}

**Comment by DIGITALCRIMINAL** [comment]
Found what I was looking for
`"subscribedBy":true`

If this is set to true, the script should work .-.
Since you recently subscribed, OnlyFans might have delayed updating that, so it might work now? If it doesn't, I will set up a special fork for you.

**Comment by elwoodflame** [comment]
still says You're not subscribed to the user.

**Comment by elwoodflame** [comment]
do I need to refresh anything?

**Comment by DIGITALCRIMINAL** [comment]
Try signing out and signing in. You will have to update your sess, app-token and maybe your user-agent again

**Comment by elwoodflame** [comment]
doesn't user agent stay the same

**Comment by DIGITALCRIMINAL** [comment]
Yeah it does unless your browser has an update and you close it

**Comment by elwoodflame** [comment]
Whats the best way to get your user agent I want to make sure that Im using the correct one.

**Comment by elwoodflame** [comment]
its working now It was the agent code

**Comment by DIGITALCRIMINAL** [comment]
Ahh, nice. Glad you fixed it.

**Comment by elwoodflame** [comment]
thanks for your help
