### ISSUE TITLE
Access denied. You're not subscribed to any users.

### ISSUE THREAD

**Issue by hetman2** [DIGITALCRIMINAL/OnlyFans#210]
I constantly get authentication failures, using the latest commit and Python 3.7 or 3.8. No syntax errors, just failed authentication attempts.

I have already looked over my config.json file and everything there looks good.

**Comment by DIGITALCRIMINAL** [comment]
Do you have 2FA on?

**Comment by hetman2** [comment]
Nope, no 2FA.

**Comment by DIGITALCRIMINAL** [comment]
Sign out then sign in and update the config

**Comment by hetman2** [comment]
Signed out, signed in, updated the config, and still the same error.

**Comment by DIGITALCRIMINAL** [comment]
Honestly, when someone says something's wrong with the auth, it always comes down to their incorrect config or it's on OF's side because it's working for me and my other accounts.
