### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by m0rJD** [DIGITALCRIMINAL/OnlyFans#211]
Can proxy support be added?

**Comment by DIGITALCRIMINAL** [comment]
Yeah; what's your proxy format?

**Comment by m0rJD** [comment]
Socks5

**Comment by FMGAlex** [comment]
Is there a specific reason this was closed?
Just curious as I would also like to have SOCKS5 proxy support as well.

**Comment by DIGITALCRIMINAL** [comment]
I added socks5 support; lmk if it works.

**Comment by FMGAlex** [comment]
I saw the changes in `master` this morning and tried it, but I had to manually install `pysocks` (on Windows 10, with Python version 3.8.2).

Maybe that should be added to `requirements.txt`?

**Comment by DIGITALCRIMINAL** [comment]
Ahh yes you're right. I've put in the requirements but forgot to push it. Glad it's working :)
