### ISSUE TITLE
Changing "text_length" has no effect

### ISSUE THREAD

**Issue by NotMyMainOne** [DIGITALCRIMINAL/OnlyFans#212]
Latest build, 

I'm trying to shorten the text_length so that there's room for the file names as I noticed its not downloading multiple files when there's a multiphoto post with a long text description. It only scrapes the first photo in those posts since it can't differentiate. I tried to set it to 225 and 200, saved, backed out of the program, and then re-entered it. It still does the full 240 and downloads only the first file.

I see now that someone else had this same issue back in February due to long paths being enabled but it was fixed. Is this now an issue again or do I need to do something different?

**Comment by DIGITALCRIMINAL** [comment]
What file name format

**Comment by NotMyMainOne** [comment]
`{date} - {text} - {file_name}.{ext}`

**Comment by DIGITALCRIMINAL** [comment]
Do you have long paths enabled on Windows?

**Comment by NotMyMainOne** [comment]
Assuming I have the right location (under group policies) it says not configured.

**Comment by NotMyMainOne** [comment]
Just disabled it and it threw traceback errors (errno 22) for some files and downloaded others. Oddly though instead of limiting text_length to 225 as it is in my config file, it limited the ones it did download to 150.

**Comment by DIGITALCRIMINAL** [comment]
So you had long paths on when the text_length had no effect?

**Comment by NotMyMainOne** [comment]
Well it wasn't configured and I'm thinking it's on by default so yeah.

**Comment by DIGITALCRIMINAL** [comment]
Alright, what happens when you turn it on?

**Comment by NotMyMainOne** [comment]
It goes right back to where we started. That's why I said I figure it acts as on by default because it has no the parameter change has no effect.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit
