### ISSUE TITLE
Missing subscriptions with latest change

### ISSUE THREAD

**Issue by aboredpervert** [DIGITALCRIMINAL/OnlyFans#214]
Hi,

With your latest change https://github.com/DIGITALCRIMINAL/OnlyFans/commit/096e0f30030e568b319776b6a7d10a9fbda28dc7 the tool only shows me 10 out of my 27 subscriptions.

I have `ignore_unfollowed_accounts` set to `all`, but all of those that should show up are currently active subscriptions.

There is no logic as to which accounts show up still, and which disappear.

Thanks.

**Comment by P0rr** [comment]
Same problem for me

**Comment by DIGITALCRIMINAL** [comment]
Ye, I changed something; I'll revert it and use a different method.

**Comment by DIGITALCRIMINAL** [comment]
Latest commits should fix it

**Comment by aboredpervert** [comment]
This indeed fixes it. Thanks.
