### ISSUE TITLE
Possible to scrape only Messages?

### ISSUE THREAD

**Issue by milktruckk** [DIGITALCRIMINAL/OnlyFans#215]
Hi I was wondering if it's possible to only scrape data from my messages. For example media that I paid for. Like If I'm not subscribed to someone anymore but still want to scrape the media that I have from that person from a message.

**Comment by DIGITALCRIMINAL** [comment]
You'll have to be subscribed to them

**Comment by GreyBeardy** [comment]
Hi.

Is it possible to scrape ONLY messages?

I have so many free subscriptions where videos are sent in msgs but I can only scrape a=everything b=images c=videos d=audios - no option to only scrape Messages

Some of them have hundreds of 1-2 second videos on their Videos page but I really want to skip them.

**Comment by DIGITALCRIMINAL** [comment]
> Hi.
> 
> Is it possible to scrape ONLY messages?
> 
> I have so many free subscriptions where videos are sent in msgs but I can only scrape a=everything b=images c=videos d=audios - no option to only scrape Messages
> 
> Some of them have hundreds of 1-2 second videos on their Videos page but I really want to skip them.

Set auto_scrape_apis to false
