### ISSUE TITLE
Unable to download Chrome Extension

### ISSUE THREAD

**Issue by aidenpi3rce** [DIGITALCRIMINAL/OnlyFans#216]
I restarted my computer and the extension was disabled. Upon trying to renable it, I had to repair it and it was removed from Chrome. Upon trying to redownload your extension, I get the following error message. Can you help?

An error has occurred
Package is invalid. Details: 'Could not load background script 'background.js'.'.

**Comment by DIGITALCRIMINAL** [comment]
I don't have any chrome extensions.
