### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by m0rJD** [DIGITALCRIMINAL/OnlyFans#217]
I have provided all the correct auth info in the config but am still getting access denied on OnlyFans.

**Comment by ElusiveZatchmo** [comment]
I would like to add that I'm getting the same thing. I checked my auth settings in config three times over and it's all correct, but I'm just getting "Access Denied" as well.

**Comment by BlatantWombat** [comment]
Same here. This happened before and I forgot how I fixed it. I reinstalled, did a ctrl+shift+r and I got in, but nothing is working.

It also doesn't try 10 times anymore, just once, and gives me an error. But that might be because of the new version

**Comment by BlatantWombat** [comment]
This is the error I get:

Auth (V1) Attempt 1/10
Access denied.
Welcome <user>
Traceback (most recent call last):
  File "D:\OnlyFans-master\StartDatascraper.py", line 94, in <module>
    if not session[0]:
KeyError: 0

**Comment by sintaxx** [comment]
Did onlyfans change something on their end ? I too just randomly started getting this error as of today.. i did a scape last night and today, access denied so i checked my settings multiple times, tried killing all login sessions from onlyfans and refreshing my info, access denied still.

**Comment by DIGITALCRIMINAL** [comment]
Are you all using the latest commit?

**Comment by sintaxx** [comment]
my apologies, i must have messed something up during an update, i deleted my release folder and got a new copy and it seems to work fine now!

**Comment by BlatantWombat** [comment]
Deleting the files and starting new with the latest download seemed to have worked. Thank you :]

**Comment by ElusiveZatchmo** [comment]
I'm still getting Access Denied after deleting and starting with the latest commit :/

**Comment by hetman2** [comment]
Same here. I keep getting access denied. And I did use this script successfully several months ago.

Is there some way to validate config.json? In the latest downloads, you don't provide a sample config.json.

**Comment by DIGITALCRIMINAL** [comment]
Yes I do, it's in the .settings folder.

I changed the folder "settings" to ".settings"

**Comment by hetman2** [comment]
Ahhh, thanks. Not sure how I missed this. Previously this script used a config.json in the root of the directory, and I just assumed it was still reading from this file.

Working for me as well. Thanks

**Comment by edmundackah** [comment]
Also getting Acess Denied at random intervals

**Comment by FIocker** [comment]
This is just the nature of this beast isn't it? What a shit program.
