### ISSUE TITLE
4.0: No module named modules

### ISSUE THREAD

**Issue by Racheron** [DIGITALCRIMINAL/OnlyFans#221]
I have not run this since 3.8, and downloaded/extracted the new release to a separate folder. 

When attempting to run StartDatascraper.py either through doubleclick, running in powershell with .\StartDatascraper.py, or py StartDatascraper.py I receive the following error: 

![image](https://user-images.githubusercontent.com/64324256/80285742-3b132f80-86e4-11ea-8971-aa6f964d11f5.png)

this is running W10 Pro and python 3.8. Python is correctly in path. using the 3.8 install works but will not authenticate.

**Comment by DIGITALCRIMINAL** [comment]
Hmm try the latest commit

**Comment by deleteforever** [comment]
just tried the last commit, it still closes after setting up the config and trying to execute it

**Comment by Racheron** [comment]
Similar error after cloning the updated repo and running start_ofd.py:

![image](https://user-images.githubusercontent.com/64324256/80315132-edb1c380-87b2-11ea-90b6-452a6577e3c2.png)

**Comment by Racheron** [comment]
Apologies, my solution here proved to be to reinstall python and fix the missing path variables *and* copy the pip installer to the python install directory, and then manually install the items in requirements.txt

I don't have a ton of python knowledge but what I have has been on *nix, which did not have these woes with Path. I appreciate your help but this seems like it was specific to my system.

**Comment by DIGITALCRIMINAL** [comment]
@deleteforever then you haven't downloaded the packages required to run the script.
You must be using python 3.8

**Comment by deleteforever** [comment]
@DIGITALCRIMINAL i was using 3.8.1. just updated to 3.8.2 and it still doesnt work, i've tried pip install -r requirements.txt again but everything is installed

**Comment by DIGITALCRIMINAL** [comment]
@deleteforever are you on Windows?

**Comment by deleteforever** [comment]
@DIGITALCRIMINAL yes, win10

**Comment by DIGITALCRIMINAL** [comment]
@deleteforever what are you using to open it? CMD?

**Comment by deleteforever** [comment]
@DIGITALCRIMINAL i've tried opening it via the CMD and executing it directly, same thing happens

**Comment by DIGITALCRIMINAL** [comment]
Run it with the Python IDLE and it will tell you the error

**Comment by deleteforever** [comment]
it worked in IDLE. tried to scrap and it was sucessful
![image](https://user-images.githubusercontent.com/63137803/80787270-78504500-8b5c-11ea-9df7-034460bada4e.png)
![image](https://user-images.githubusercontent.com/63137803/80787282-7e462600-8b5c-11ea-8425-3f83645e2c17.png)

**Comment by HeyPapito** [comment]
> Hmm try the latest commit and let me know

Also having this issue on macOS

**Comment by DIGITALCRIMINAL** [comment]
@deleteforever seems like you've probably got another version of Python installed

**Comment by DIGITALCRIMINAL** [comment]
> > Hmm try the latest commit and let me know
> 
> Also having this issue on macOS

Which error?
