### ISSUE TITLE
OnlyFans PST not UTC

### ISSUE THREAD

**Issue by aholmes97** [DIGITALCRIMINAL/OnlyFans#225]
The OnlyFans module (section for get_subscriptions) looks at the current UTC time to determine whether a subscription has expired or not. However, OnlyFans subscription expirations are based on PST time (giving an additional 6 hours or so). By changing the times being retrieved in the OnlyFans module, you’d be able to scrape content that is close to expiring!

**Comment by DIGITALCRIMINAL** [comment]
How do you know it's based on PST and I've already made the script have the ability to scrape users on/after it has expired on the front view
