### ISSUE TITLE
[OF] Add post title to file name format 

### ISSUE THREAD

**Issue by bpo5r5** [DIGITALCRIMINAL/OnlyFans#227]
Hi,

It would be great to have the option to use the original posts description as the file name.

Looking at the `posts` api, there is a `rawText: "blah blah"` key which has the post title. 

And for those that don't have any raw text, to use the media file name as usual. 

Thanks for the project :)

**Comment by DIGITALCRIMINAL** [comment]
You can already do this but you'll get a lot of errors.
