### ISSUE TITLE
Confused about Metadata Scraping

### ISSUE THREAD

**Issue by IRlyLikeBac0n** [DIGITALCRIMINAL/OnlyFans#228]
Hey I'm a bit unsure how to set up the new metadata scraping option. I have the the .json files for images and videos in the Metadata folder, but I don't know what to do with it exactly.

**Comment by IRlyLikeBac0n** [comment]
Also, would this be able to work even after the OF subscription expires?

**Comment by DIGITALCRIMINAL** [comment]
Metadata scraping is just there so you have more control over what you'd want to do after downloading the files or would like to use an external downloader. It doesn't work after the OF sub expiries.
