### ISSUE TITLE
Any way to run a script after each download like w/ youtube-dl?

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINAL/OnlyFans#229]
I'm just curious if there may be any future possibility to run a script after each download in a similiar way as youtube-dl does. I'm running this on my seedbox and having a script to upload to my storage drive after each download would help ensure that I'm not using too much space in a grab. Again, mostly curious because it would be super useful to not max out of my seedbox space. Thanks!

**Comment by DIGITALCRIMINAL** [comment]
When you say each download, do mean after a folder completes?

**Comment by ElusiveZatchmo** [comment]
Apologies for not getting back sooner, after each folder would work. In youtube-dl, it happens after each individual video, but with here, each folder might be the more viable option.

**Comment by DIGITALCRIMINAL** [comment]
Yee I can do that. Executing a script in a new window right?

**Comment by ElusiveZatchmo** [comment]
I guess in a new window. My goal, essentially, is to try and maintain a small footprint on the VPS I'm currently using.
