### ISSUE TITLE
[OF] Incomplete Image Set Downloading

### ISSUE THREAD

**Issue by ethanndev** [DIGITALCRIMINAL/OnlyFans#230]
Whenever using the picture scraping functionality, it seems like it only downloads 1 image of each set (if a model/person uploads a post with 5 pictures in the same post, only 1 is downloaded). I've tried turning **overwrite files** on and off with no success in downloading them properly.

Further info: I'm attempting to scrape a model's page that has ~1,000 pictures and ~115 videos. The 115 videos are downloaded fine but I'm only getting 180 (iirc) pictures.

**Comment by DIGITALCRIMINAL** [comment]
Are you using the default filename format?

**Comment by ethanndev** [comment]
That was it, I had removed filename so without modifying code to add on chars to beginning or end for repeated filenames it wouldn't download more than 1 per set; sorry for wasting your time.
