### ISSUE TITLE
Auth Loop with correct cookies

### ISSUE THREAD

**Issue by ubehalohalo** [DIGITALCRIMINAL/OnlyFans#232]
Hi! I've been experiencing this problem even tho all my cookies and user-agent are correct. Also, I am subscribed to accounts. How can I resolve this? Thanks!

<img width="255" alt="Screen Shot 2020-05-05 at 11 39 17 PM" src="https://user-images.githubusercontent.com/64794584/81085270-9685be80-8f29-11ea-8e9c-34f69da3a9c9.png">

**Comment by DIGITALCRIMINAL** [comment]
Have you got 2FA auth on your OF account?

**Comment by ubehalohalo** [comment]
Nope. But I enabled it earlier and tried the code again, it didn’t work.

**Comment by DIGITALCRIMINAL** [comment]
Ye 2FA has to be off for it to work right now

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit
