### ISSUE TITLE
issue with latest build 

### ISSUE THREAD

**Issue by jimcrapo** [DIGITALCRIMINAL/OnlyFans#237]
Python 3.8.3rc1 64 bit on Win10. 

When running via cmd, it'll auth then hang up. When pressing enter on the window, the following error comes up:

2020-05-08 11:03:42,810 ERROR errors invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "F:\rip\datascraper\main_datascraper.py", line 150, in start_datascraper
    value = int(input().strip())
ValueError: invalid literal for int() with base 10: ''

Script then ends.

Running in the IDLE:
#!/usr/bin/env python
import tests.main_test as main_test

main_test.version_check()

if __name__ == "__main__":
    import datascraper.main_datascraper as main_datascraper
    main_datascraper.start_datascraper()

**Comment by DIGITALCRIMINAL** [comment]
You need to input an integer on who you'd like to scrape.

**Comment by jimcrapo** [comment]
auto_choice is set to "a" - shouldn't have to select an account, correct?

I had to set "auto_scrape_names" to "true" for it start working again as it did previously, before the update.

**Comment by DIGITALCRIMINAL** [comment]
Ah yes; so it works now right?
