### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by ItsN3rdy** [DIGITALCRIMINAL/OnlyFans#24]
Anyway to change the date format to Y/M/D?

**Comment by mileyvirus** [comment]
Yes, on line 141 change `%d-%m-%Y` to `%Y-%m-%d` so
`dt = datetime.fromisoformat(media_api["postedAt"]).replace(tzinfo=None).strftime('%d-%m-%Y')`
to
`dt = datetime.fromisoformat(media_api["postedAt"]).replace(tzinfo=None).strftime('%Y-%m-%d')`

**Comment by dilemmax** [comment]
What if I want the format to be YYYY-MM-DD?

**Comment by mileyvirus** [comment]
Same as `%Y-%m-%d` means `2019-09-04`.

**Comment by dilemmax** [comment]
Okay. Thanks for the info!

**Comment by DIGITALCRIMINAL** [comment]
Added the ability to chose a custom date format in settings.json
