### ISSUE TITLE
Purchased request

### ISSUE THREAD

**Issue by Code4Win** [DIGITALCRIMINAL/OnlyFans#240]
Is there a way to please scrape and download the login user's 'Purchased' tab?

That way all purchases made by the login user's account can be downloaded even if not currently following or subscribed to the content user.

**Comment by DIGITALCRIMINAL** [comment]
Can you link me the purchased tab?

**Comment by DIGITALCRIMINAL** [comment]
Nvm finally found it. I'll add it soon.

**Comment by Code4Win** [comment]
Thank you so much. I really appreciate it!

**Comment by GreyBeardy** [comment]
was this added yet ?

Is there a way to scrape "purchased" content ?

As I understand you cant scrape the content the account purchased if they are no longer subscribed to that user - i.e the subscription ran out but the account still has acccess to any videos bought in messages.

**Comment by bollerdominik** [comment]
Hope this feature is added soon as it would be very usable

**Comment by yolopolo8** [comment]
how to scrape purchased tab?

**Comment by DIGITALCRIMINAL** [comment]
Lol... it's been added finally.

**Comment by wailin247** [comment]
Purchased request label:enhancement
