### ISSUE TITLE
Replace old directories

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINAL/OnlyFans#243]
Why has the folder structures changed? I've now redownloaed content twice. How can I change this back to the previous folder setup?

**Comment by incogrito** [comment]
Per the commit, set sort_free_paid_posts to false.

**Comment by DIGITALCRIMINAL** [comment]
@incogrito ^^^^^^^

**Comment by DIGITALCRIMINAL** [comment]
Added a commit where the files will automatically convert to the new filepath.
