### ISSUE TITLE
[Bug] Pressing 0 for onlyfans auto selects "everything" if you have more than 5 subscriptions

### ISSUE THREAD

**Issue by MyAltGitHubAccount** [DIGITALCRIMINAL/OnlyFans#245]
Pretty much the subject. Once you're subscribed to more than 4 or 5 people and press 0 to select onlyfans, it adds another 0? to select everything.

**Comment by DIGITALCRIMINAL** [comment]
What is "auto_scrape_names" set to in the config

**Comment by MyAltGitHubAccount** [comment]
Blank

**Comment by DIGITALCRIMINAL** [comment]
Blank? Set it to False then

> "auto_scrape_names": false

**Comment by MyAltGitHubAccount** [comment]
There we go. Thanks.
