### ISSUE TITLE
[Request] Have "Everything|Images|Videos|Audios" option apply to everyone when you select "0 = All"

### ISSUE THREAD

**Issue by MyAltGitHubAccount** [DIGITALCRIMINAL/OnlyFans#247]
I don't know if this is for OnlyFans, but if I select 0 for all, and then a for everything, it would be nice if there was a way to apply that to everyone so I didn't have to keep hitting 'a'.

**Comment by DIGITALCRIMINAL** [comment]
You can.
Look at the README.

**Comment by MyAltGitHubAccount** [comment]
I'm ashamed. Sorry.

**Comment by DIGITALCRIMINAL** [comment]
It's okay lol. The script is able to be fully automated. Just look for anything that has "auto" in the name.
