### ISSUE TITLE
ignored_keywords Issue

### ISSUE THREAD

**Issue by pirate-cpu** [DIGITALCRIMINAL/OnlyFans#253]
I'm unable to skip posts that promotes other pages. I have the following keywords added `"free", "follow", "Free", "Follow", "FREE", "FOLLOW"`. My file name format is `{date}_{file_name}.{ext}`. Should I change the format to include text? Or is there a way to skip them without changing the format?

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit.
