### ISSUE TITLE
4chan is broke

### ISSUE THREAD

**Issue by Chronowolf47** [DIGITALCRIMINAL/OnlyFans#254]
First off, hell of an application btw.
The 4chan module for the application does not work. After manually adding the extra_auth settings and the missing scraping field inside the config.json I can get the 4chan module to start. I also added the boards to rip like found in the readme, and as soon as the application asks which boards to rip in the py.exe it crashes.

2020-05-18 10:29:02,855 ERROR errors 0
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 175, in start_datascraper
    session = session_array[0][0]
KeyError: 0

I hope this helps.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit.
