### ISSUE TITLE
Install requirements

### ISSUE THREAD

**Issue by lumberjack29** [DIGITALCRIMINAL/OnlyFans#255]
I open powershell in the project folder, run the install code listed and get this - 

pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DIGITALCRIMINAL** [comment]
Use CMD or search on Google how to fix it.
