### ISSUE TITLE
Implementing Token Retrieval via Splinter

### ISSUE THREAD

**Issue by XAW42069** [DIGITALCRIMINAL/OnlyFans#256]
This tool is great but has caveats for idiots.

I suggest a browser that pops up when no credentials have been supplied via Splinter or something like that. I understand this is a low (if not forgettable) thing for you but, I'd be mostly happy to add it if it's something you'd like.

There is also an issue in infinite looping that causes CPU to get to 100% after a while which also needs looking in to but that'll be it's own ticket when the time comes.

Alternatively, couldn't we just provide some basic javascript for the users to run to extract all tokens for onlyfans?

**Comment by DIGITALCRIMINAL** [comment]
I'm thinking of making a simple Chrome Extension but I'm garbage at JavaScript.
I'm most likely going to do this though.

**Comment by XAW42069** [comment]
A chrome extension is a bit far but, I do really think some simple F12 magic can rip all that's needed. Guess I can take a look.

**Comment by DIGITALCRIMINAL** [comment]
I can't add this in.

I might have fixed the 100% CPU issue, I dunno though.
