### ISSUE TITLE
question: what is the media_id?

### ISSUE THREAD

**Issue by vv211** [DIGITALCRIMINAL/OnlyFans#258]
I see there is now option for including media_id in filename format, what is that? How will it be different from the media's filename?

further, if this is a naming format i wish to change to, is it possible to auto-rename already downloaded files with new name format, instead of downloading again?
My internet is very slow and can take hours for 1 page to download with a small amount of posts

Thanks :)

**Comment by aboredpervert** [comment]
It's internal to OnlyFans, it uniquely identifies every media (picture/video/etc) uploaded.

When multiple media are put in the same post, the media IDs are in the same order as they are in the post, unlike the filenames which are random.

I use `{date}_{id}.{ext}` as my file name format. With this it ensures that the downloaded files end up being sorted in the intended order.

I don't know for the auto-renaming part though.

**Comment by DIGITALCRIMINAL** [comment]
If you've still got the metadata, I can convert old filenames to the new

**Comment by vv211** [comment]
I have configured to download metadata in js format for all downloads to date
