### ISSUE TITLE
An unusual situation where the scraper is unable to detect videos

### ISSUE THREAD

**Issue by amenly** [DIGITALCRIMINAL/OnlyFans#259]
Hello DC,

I believe I've run into an unusual situation where if an OF creator *only* has images in the 'Posts' section, the scraper will *not* scrape for any videos in the 'Archived' section. I encountered this problem with [this profile](https://onlyfans.com/thelittlesister). If you look at the top of that page, you'll see they only have 1 image and 0 videos. However, they have 37 posts in the 'Archived' section and among those 37 posts are 20 videos. For some reason though, the scraper fails to detect those videos. 

![Screen](https://user-images.githubusercontent.com/60410674/82722137-7d9b3e00-9c89-11ea-90fe-49544a08d52e.png)

I thought that maybe it was an issue with the 'Archived' section so I tried scraping [this page](https://onlyfans.com/lexypanterratwerk/) as a test but it was indeed able to scrape all the videos in the 'Archived' section of that page. This leads me to believe that if a page only has images in the 'Posts' section, then the scraper will only scrape images in the 'Archived' section. In addition to this, the opposite may also be true: if a page *only* has videos in the 'Posts' section, the scraper may only scrape videos in the 'Archived' section (but I wasn't able to test this).

I was wondering if there's any way you could fix this? I understand it may seem like a really minor problem since there's not many OF creators who only have videos or only have pictures but it would be really appreciated.

**Comment by DIGITALCRIMINAL** [comment]
I can't recreate the issue as they don't have the archive anymore :c

**Comment by amenly** [comment]
> I can't recreate the issue as they don't have the archive anymore :c

When you say "they," are you referring to that specific user that I linked to above or are you referring to creators on OnlyFans in general? I just ripped [this page](https://onlyfans.com/thiccasianbaddie) that had over 400 posts in the 'Archived' section before the redesign with your script and the script is still able to scrape items in the 'Archived' section, they're just not visible to us (this also makes me wonder if creators are able to see it on their end). 

For example, you'll see that the page I linked to only has 15 photos:

![3](https://user-images.githubusercontent.com/60410674/83316882-3a435100-a1ee-11ea-9231-0cb1752c238c.png)

However, if I run your script to rip her page, there is an 'Archived' folder that appears and there are 444 images in the 'Images' folder.

![1](https://user-images.githubusercontent.com/60410674/83316908-7b3b6580-a1ee-11ea-94e3-a12196c60bc4.png)

![2](https://user-images.githubusercontent.com/60410674/83316917-88f0eb00-a1ee-11ea-9698-2a0d13b12c2d.png)

The problem here is that I know for a fact that her page has videos in the now-hidden 'Archived' section but they're invisible to the scraper since she *only* has photos uploaded at the moment. I understand if you can't do anything about it though. I'm just hoping she uploads at least one video before my sub ends.

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed now

**Comment by amenly** [comment]
So I just noticed that when you select an account, you have several options: Everything, Images, Videos, and Audios. Previously, I was only selecting Everything and I completely forgot that there was a Videos option. I just tried the Everything option again (after redownloading your script) and it couldn't detect the videos in the Archived section. However, when I tried just the Videos option, it was able to detect them! Very unusual. So I guess the problem is resolved then? The thing to take away from this is if you're ripping a page with *only* images on it, you should try the Videos option just to be sure. And if you're ripping a page with *only* videos on it, you should try the Images option afterwards.

**Comment by DIGITALCRIMINAL** [comment]
The scraper will check for everything now

**Comment by DIGITALCRIMINAL** [comment]
> So I just noticed that when you select an account, you have several options: Everything, Images, Videos, and Audios. Previously, I was only selecting Everything and I completely forgot that there was a Videos option. I just tried the Everything option again (after redownloading your script) and it couldn't detect the videos in the Archived section. However, when I tried just the Videos option, it was able to detect them! Very unusual. So I guess the problem is resolved then? The thing to take away from this is if you're ripping a page with _only_ images on it, you should try the Videos option just to be sure. And if you're ripping a page with _only_ videos on it, you should try the Images option afterwards.

Yee the scraper isn't tied down to posts anymore. It'll try to find everything.
