### ISSUE TITLE
OSError with {text} file_name_format

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#26]
I'm running into the following error with a certain file when I use the {text} option in file_name_format:

OSError: [Errno 22] Invalid argument: 'X:\\OnlyFans/Users/boobzillaxxx/Images/2018-02-23-Waistraining. HIIT cardio Get access to my unseen and exclusive content at onlyfans.com onlyfans.com onlyfans.com onlyfans.com onlyfans.com onlyfans.com onlyfans.com onlyfans.com onlyfans.com onlyfans.com-33881666--upload-467305-1519404725819-JPEG-20180222-092806-349656419.jpg'

**Comment by DIGITALCRIMINAL** [comment]
It's because the text is too long for a file name. I'll sort it out in a few hours.

**Comment by DIGITALCRIMINAL** [comment]
I pushed a commit

**Comment by DIGITALCRIMINAL** [comment]
I pushed a commit (forgot to do it 3 hours ago), reopen the issue if there's still an error
