### ISSUE TITLE
Haven't seen this issue occur yet when trying to run 4chan or bbwchan.

### ISSUE THREAD

**Issue by kave333** [DIGITALCRIMINAL/OnlyFans#261]
2020-05-26 23:18:18,484 ERROR errors 'auto_scrape_names'
Traceback (most recent call last):
  File "F:\X\X\X\OnlyFans-master\datascraper\main_datascraper.py", line 68, in start_datascraper
    auto_scrape_names = json_site_settings["auto_scrape_names"]
KeyError: 'auto_scrape_names'

Might be something very simple - I am just not familiar with Python, sorry.

Python: 3.8.3

**Comment by DIGITALCRIMINAL** [comment]
4Chan and BBWChan broke right now but I've fixed it on my end. I'm not ready to push the commit yet though.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit.
