### ISSUE TITLE
OnlyFans requires "fp" cookie to authenticate.

### ISSUE THREAD

**Issue by ApacheTech** [DIGITALCRIMINAL/OnlyFans#263]
I've had to edit the code here to allow for a new cookie to be sent with the request. There's an "fp" cookie that needs to be sent, along with the current cookies. Without this cookie being present, I get an auth fail loop. Adding the cookie makes it authenticate first time.

I'd like to know what the "fp" stands for, if possible, and it might be worth adding it as an optional field in the config, if it is required for some. Every update, I have to re-edit the code to add it back in again before anything works.

**Comment by goodboi69** [comment]
> 
> 
> I've had to edit the code here to allow for a new cookie to be sent with the request. There's an "fp" cookie that needs to be sent, along with the current cookies. Without this cookie being present, I get an auth fail loop. Adding the cookie makes it authenticate first time.
> 
> I'd like to know what the "fp" stands for, if possible, and it might be worth adding it as an optional field in the config, if it is required for some. Every update, I have to re-edit the code to add it back in again before anything works.

Could you tell us how and what to edit until this has been updated please?

**Comment by ApacheTech** [comment]
OF has changed their policies again today, so a proper fix will likely be added soon. I wouldn't want to pre-empt the update with a jury-rigged hotfix.

**Comment by DIGITALCRIMINAL** [comment]
Added the FP cookie in
