### ISSUE TITLE
[OF] Downloading

### ISSUE THREAD

**Issue by MadamJazzy** [DIGITALCRIMINAL/OnlyFans#264]
Images are able to download extremely fast, however when it moves to videos it seems to lag. I've noticed on my bandwidth monitor that the speed of which its downloading is very slow. I have Gigabit (1000 mbps) internet but yet I see that the script is only using approx 30-40 mbps when downloading?

**Comment by DIGITALCRIMINAL** [comment]
Yee that's down to OnlyFans. their servers have an upload limit.
The script is optimized for multiple a CPU with multiple threads. The more threads you've got, the faster it'll able to download stuff.
