### ISSUE TITLE
Auth_id & auth_hash no longer present in cookies

### ISSUE THREAD

**Issue by LunarPenguin** [DIGITALCRIMINAL/OnlyFans#265]
It seems that OnlyFans have deprecated the use of the auth_id and auth_hash cookies and now only use a "fp" cookie and the sess cookie.
![of_fp](https://user-images.githubusercontent.com/35904804/83251640-2d9d0980-a1aa-11ea-8512-284cb257267a.png)

**Comment by ApacheTech** [comment]
I have 5 cookies being sent with each request: **"auth_id"**, **"auth_hash"**, **"sess"**, **"fp"**, and **"ref_src"**.

Currently, I cannot get any response from the API, other than **_"Error: Application token is required."_**, even when setting the Host Header.

**Comment by DIGITALCRIMINAL** [comment]
Huh, it's all still working for me.
They updated their site though... but the cookies are still fine to use.

The auth_id, auth_hash and sess token are still in the cookies. Am I missing something?

**Comment by ApacheTech** [comment]
I have three accounts, and two of them broke in the last 12 hours with the scraper. All the others say "Access Denied". Only the one I added last night works. When directly accessing the requests, they used to be accessible, but now just say "Application token is required".

**Comment by DIGITALCRIMINAL** [comment]
Do you have 2FA enabled?

**Comment by ApacheTech** [comment]
Nope. Not on any of the accounts.

**Comment by ApacheTech** [comment]
The "fp" cookie seems to be essential, as well. Without that, even the new account comes back with "Access Denied". See my reported issue, below.

**Comment by DIGITALCRIMINAL** [comment]
Did you update all of the cookies for the accounts?

**Comment by ApacheTech** [comment]
Ran the scraper once at 2am before going to bed. Worked fine. Ran the scraper again at midday. Auth fail loop. Nothing changed in between.

**Comment by LunarPenguin** [comment]
i tried to download last night but it failed somehow and i saw in the browser that the auth_id, auth_hash and the new fp cookie were present but i did not have time to look further. and when i looked at it today both the auth_id and auth_hash had disappeared and i only saw them appear again once when i was testing in firefox

**Comment by ApacheTech** [comment]
The "fp" cookie has been present for a few months now, and since it showed up, I have had to edit the source of the scraper to add it in.

**Comment by DIGITALCRIMINAL** [comment]
> I use Firefox. I forget that other - inferior - browsers exist. :p

:(

But yeah I've got a big commit waiting to be pushed with other features and fixes, I just gotta make sure it works. I'll add in the FP and other types of cookies to support 2FA as well.

**Comment by LunarPenguin** [comment]
a small summary of my findings. i have not seen the **"auth_id"** and **"auth_hash"** cookies again since opening the issue. only cookies i see are **"fp"**, **"sess"** and **"sess_src"** (seems to be for redirecting). it does not seem to matter what browser you use or if they're paid or free subscriptions.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit

**Comment by LunarPenguin** [comment]
The program now works as intended using the latest commits. also my thanks for implementing 2fa.
