### ISSUE TITLE
Only downloading the first image from a post containing multiple (OnlyFans)

### ISSUE THREAD

**Issue by dangscribble** [DIGITALCRIMINAL/OnlyFans#268]
Using the latest commit (~5 hours ago as of posting), ripping everything (option a) from a specific model (not all models) that hasn't been ripped previously by the tool.

Everything appears to work as intended, but only seems to be grabbing the first image from a post that has more than one image in it. I'm not sure about videos as this wasn't applicable to me. A peek in the Posts.json file appears to show entries for all the images in each post (from what I can understand of it).

The contents of the respective "..\Posts\Free\Images" folder confirms that the number of images downloaded is less than the total indicated on the model's page, and it's not hard to visually check which ones. All nine of the images missing were the second or third images in a different multiple image posts. Ripping the same model again doesn't download any of the missing files.

**Comment by DIGITALCRIMINAL** [comment]
Which model are you trying to download

**Comment by dangscribble** [comment]
qxeen-xxxclusive

**Comment by DIGITALCRIMINAL** [comment]
Thanks, you can download the latest commit
