### ISSUE TITLE
Only a user's free content is downloaded

### ISSUE THREAD

**Issue by becquerel43** [DIGITALCRIMINAL/OnlyFans#269]
Apologies in advance if this issue is down to my own stupid mistake, I checked the FAQ and looked over the config file and didn't see anything that immediately spoke to my problem.

The scraper accepted my OF authentication without issues and correctly displayed my list of subscribed profiles, but when I try to download a user's images it only gets (what I assume to be) the images they've posted for free to a folder titled 'Free'. For reference, the profile I'm trying to rip has ~3000 images posted overall, but the scraper only got around 200 of them.

Is this most likely an issue with authentication, or something else? My errors.log file is empty.

**Comment by DIGITALCRIMINAL** [comment]
If you're authed in, you're fine. It's to do with the logic of my script if it isn't working. What's the username you're trying to scrape?

**Comment by becquerel43** [comment]
It's Riley Reid's account I'm interested in, rileyreidx3. Thank you.

**Comment by DIGITALCRIMINAL** [comment]
Could you try the latest commit? I pushed it 20 minutes ago

**Comment by LP560** [comment]
I was having this same issue, seems to be fixed for me, thanks

**Comment by becquerel43** [comment]
Sorry for the slightly slow response, but I wanted to make sure it die halfway through before posting - the new commit fixed the problem perfectly and it's now downloading every picture without a problem. Thank you very much indeed!
