### ISSUE TITLE
Latest version re-downloaded/duplicated everything with new file name

### ISSUE THREAD

**Issue by artyom2035** [DIGITALCRIMINAL/OnlyFans#270]
I've been using "file_name_format": "{date}-{text}-{id}.{ext}" for the last few versions & it would create names with an underscore in place of a space in the {text} field.  Using the same file name format, this latest version has re-downloaded everything, just w/o the underscore. Long story short, have duplicates of everything with two filename variations.

Also, there's also lots of file names like this "_HAV0F~4.MP4", and others with no extension, like this "_HAV0F~4", that are duplicates of existing files with normal names. 

Usually, I wouldn't bug you & manually clean this up, but I now have .97 TB of data with 44,452 files

**Comment by DIGITALCRIMINAL** [comment]
In your filename format, it says you're using hyphens instead of underscores

**Comment by jeremfg** [comment]
I concur... It seems in previous versions the spaces in {text} were being replaced with underscores. Not anymore.

While I prefer the new scheme (it's clearner with spaces than underscore), it would force me to re-download everything.

I'd love a migration path where the old files get renamed instead of re-downloaded. I'm not too keen in re-downloading 805 GiB over my 15 Mbps connection.

**Comment by DIGITALCRIMINAL** [comment]
For onlyfans or some other module?

**Comment by jeremfg** [comment]
I can't speak for others, I only use OnlyFans.

I was gonna bite the bullet for the new "Free" and "Paid" folder by manually moving the files under each model sub-folder. But this is becoming too much now.

**Comment by DIGITALCRIMINAL** [comment]
I already told people multiple times not to use text in the filename format because stuff like this would happen. 

The script automatically moves files to the new directory format.

**Comment by jeremfg** [comment]
In this case, may I request to scrap text-only posts and/or treat the text as meta-data somehow that can be consulted independently? I'm trying to preserve the context around the pictures/videos, it's important to me. Best way to do that thus far was to include it in the filename.

**Comment by DIGITALCRIMINAL** [comment]
All the text is already in the metadata file?

**Comment by jeremfg** [comment]
Oh right, I missed that somehow.

**Comment by DIGITALCRIMINAL** [comment]
Either way, I'm working on an auto renamer.

You MUST have {id} or {filename} in your filename format for it to work.

**Comment by jeremfg** [comment]
I do have {filename} at the very beginning of my old pattern! Thank you for saving us :)

Although it's not next to the .{ext}, as per your warning:
`Warning: It's important to keep a unique identifier next to .{ext}. By default it's {file_name}.`
Will it prevent your auto-renamer from working in my case? Or you'll be matching for the unique fields in the entire path, regex-like?

My old pattern is `{file_name} - {text}.{ext}`. I'm definitely going to remove {text} now that I know the meta-data contains what I need.

**Comment by DIGITALCRIMINAL** [comment]
Oh, it's fine, it doesn't need to be next to the .ext

I'll just be doing something like
`if "filename" in "filename - hello.ext":
                rename()`

Basically what you said without regex

**Comment by jeremfg** [comment]
Cool. I was afraid this would be too much of a performance issue to test against each files first. Glad to hear!

**Comment by artyom2035** [comment]
Just following up, but you guys are already on it.  I only use it for Onlyfans and I was specifically referencing spaces/underscores within the {text} field. Like jeremfg, I used the text field to 'quickly' identify context (vs. names like 8udcepydyjv8qixsiurdairjerkkhiiu.mp4 for example). I'll explore how to do that with metadata.  Thanks for a great program btw!

**Comment by artyom2035** [comment]
Just a heads-up - not complaining btw. Onlyfans may have made a site change that screwed with 'date modified'.  The {date} field used to insert the post's date.  Now (for me at least) having {date} in the filename format downloads dups of everything in every subscription, but with 2020-06-10 as the date (even if it was posted a year ago). I'll probably stop using the date field also.

**Comment by DIGITALCRIMINAL** [comment]
Will push the commit for this within two days

**Comment by DIGITALCRIMINAL** [comment]
The commit has been pushed, but it only works for OnlyFans and StarsAVN for now.
