### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by crackmanix** [DIGITALCRIMINAL/OnlyFans#271]
Hi,

After the download of the new release i still have access denied.
The config.json looks good.

Auth (V1)
Auth Attempt 1/10
Access denied.
Auth Attempt 2/10
Access denied.
...
Auth (V2)
Auth Attempt 1/10
Access denied.
Auth Attempt 2/10

**Comment by goodboi69** [comment]
This is being worked on and will be updated as soon as it can.

**Comment by DIGITALCRIMINAL** [comment]
10/10 times there's something wrong with your cookies

**Comment by crackmanix** [comment]
I've found what's wrong.
I cleared the onlyfans cookie manually then i force chrome to disable the cache.
Strangelly, there is no "auth_hash" anymore so i put the "sess" instead and it works.
