### ISSUE TITLE
Error when scraping

### ISSUE THREAD

**Issue by aholmes97** [DIGITALCRIMINAL/OnlyFans#272]
Latest version (pulled 2 minutes ago). When running, I get the below:

/user/local/lib/python3.8/site-packages/bs4/__init__.py:393: UserWarning: “https://onlyfans.com/USERNAME” looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
Warnings.warn(

Then it continues.

**Comment by DIGITALCRIMINAL** [comment]
That's not an error

**Comment by aholmes97** [comment]
Shall I repost it with the title “Warning” then? Thought you might want to suppress it, that’s all.
