### ISSUE TITLE
Only free content is downloaded

### ISSUE THREAD

**Issue by notarealemail** [DIGITALCRIMINAL/OnlyFans#273]
This seems similar to what was resolved in #269 but I can't seem to figure it out. OnlyFans content seems to only download free posts, no premium content for subscribes creators.

**Comment by DIGITALCRIMINAL** [comment]
Did you buy any of the posts?

**Comment by notarealemail** [comment]
I'm a monthly, paid subscriber to two creators.

**Comment by DIGITALCRIMINAL** [comment]
But have you paid for a post......

**Comment by aliasedv2** [comment]
following up on this, the scraper is also not downloading time limited content that can be viewed for free

![image](https://user-images.githubusercontent.com/18623540/83670882-759ca180-a599-11ea-8929-a77493d926a5.png)

the content shows up in the posts.json but does not get scraped
`"01-06-2020 18:55:39", "paid": false, "directory": "B:/_redacted_/Posts\\Free\\Videos/", "filename": "{username} - [{date}] {file_name}.{ext}", "size": 1}], `

**Comment by DIGITALCRIMINAL** [comment]
@aliasedv2 what's the username you're trying to scrape

**Comment by aliasedv2** [comment]
> @aliasedv2 what's the username you're trying to scrape

nigella_pty

**Comment by DIGITALCRIMINAL** [comment]
@aliasedv2 do you have the post id?

**Comment by aliasedv2** [comment]
26255127

**Comment by DIGITALCRIMINAL** [comment]
I was able to download the video
![image](https://user-images.githubusercontent.com/21285176/83675859-a698c880-a5d1-11ea-94a9-a71859d56bab.png)

**Comment by aliasedv2** [comment]
Confirmed. Had to update repo first.

**Comment by notarealemail** [comment]
So, I clearly misunderstand something. Either about this script or OF. I have not paid for individual content, no. I paid a recurring monthly fee for access to a profile. Am I to understand that OF content is only scraped if it is a) Free or b) purchased on an per-item basis?

**Comment by DIGITALCRIMINAL** [comment]
If you're subscribed to the model, all their content will go into the "Free" folder and anything you pay extra for goes into the "Paid" folder.

**Comment by notarealemail** [comment]
Understood. I set the scraper up in a Linux VM and found that it missed no content. So, I'm marking this closed.
