### ISSUE TITLE
Login fails unless script is called in a specific way

### ISSUE THREAD

**Issue by chastepants** [DIGITALCRIMINAL/OnlyFans#276]
Environment: 
OS: Windows 10 1909
Shell: Powershell 5.1.18362.752
Python: Python 3.8.3

Running 
python start_ofd.py
results in authentication failures

Running 
python -i start_ofd.py
works as expected

Maybe just needs a change to the instructions to make it clearer how to run this

**Comment by DIGITALCRIMINAL** [comment]
Running without the I flag doesn't affect me, so I wouldn't have known.
