### ISSUE TITLE
Unable to auth to Onlyfans

### ISSUE THREAD

**Issue by cyberkoala** [DIGITALCRIMINAL/OnlyFans#278]
I would buy this might still be user error, but I actually previously had this setup and working. Last time i ran it successfully was 6/2. On trying to run it since, it fails to authenticate. signed out and back in, and noticed that the chrome debug tool still gives the same session id etc... but also, trying to run the script forces signout on browser session, so there is def some communication happening. 

Tried using firefox in privacy mode and got a different session id/app-token, but still seem to have the same behavior.

Can anyone confirm that the script still works as is, and that this isn't any changes made on the OF end breaking authentication?

**Comment by DIGITALCRIMINAL** [comment]
It's working for me

Try this guy's solution and let me know if it works
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/276#issue-633410692

**Comment by dilemmax** [comment]
Same her and I tried the solution but still not working

**Comment by DIGITALCRIMINAL** [comment]
@dilemmax do you have 2FA on your account?

**Comment by DIGITALCRIMINAL** [comment]
@cyberkoala there was a bug like that, but I fixed it. It happened when I was using a proxy/vpn.

**Comment by dilemmax** [comment]
I don't have 2FA turned on for my account. It was working for me a few days ago. I did have to update the auto-hash when I tried to use it just then.

**Comment by dilemmax** [comment]
That's so weird. It's working for me now.

**Comment by cyberkoala** [comment]
Well. Full restart, clear cache clear cookies, and tried again. One thing i did catch: user agent changed, now running a more advanced version of chrome, so updated that as well as the sess. (app token appears to be the same, just new sess and auth hash).. and now it works. 

Not sure, maybe user error or maybe all that clearing stuff out fixed it. Maybe they are actually checking against the agent version and saw two different IDs? it IS weird.
