### ISSUE TITLE
[macOS] win32_setctime: This function is only available for the Windows platform.

### ISSUE THREAD

**Issue by mileyvirus** [DIGITALCRIMINAL/OnlyFans#28]
Hey dude! Great work on the last commits, the scraper's performance has become amazing.
Your new dependency `win32_setctime` obviously works only on Windows, on macOS it halts the script.

```
  File "/usr/local/lib/python3.7/site-packages/win32_setctime.py", line 44, in setctime
    raise OSError("This function is only available for the Windows platform.")
OSError: This function is only available for the Windows platform.
```

I commented line 206 to make it work.
```
        # setctime(directory, timestamp)
```

**Comment by DIGITALCRIMINAL** [comment]
Thanks for spotting, I thought it would work on Mac because it works on Linux. In the meantime, I'll add a commit in an hour or so, that will check the os type before running that function

**Comment by DIGITALCRIMINAL** [comment]
In the latest release if your OS is MacOS it will skip the setctime function
