### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by ElegantPercentage** [DIGITALCRIMINAL/OnlyFans#284]
Hi, I'm getting access denied. Was working fine just yesterday. Verified config.json multiple times.

**Comment by crackmanix** [comment]
Hi same problem for me nothing change and suddenly today access denied.
Config.json seems good and unchanged.

**Comment by ctrlcmdshft** [comment]
redo the auth_id and auth_hash if you logged out of site or cookies got deleted it could cause that

**Comment by crackmanix** [comment]
i logged out delete the cookie and re write the info on the config.json still the same

**Comment by ctrlcmdshft** [comment]
No idea then mine is still working, are you using a newer version?  I was on 4.0 earlier this week and it worked fine and im now using 5.0 and its working fine.

**Comment by crackmanix** [comment]
To be sure, i've downloaded the latext version and restart from scratch.
Same problem, access denied. when you look at the network trace on devtools a PHPSESSID as appeared.
Maybe something to dig.

**Comment by Jarsky** [comment]
Same issue. It stopped working, I pulled the latest version today from github, re-did my cookie details in the config.json and same issue

**Comment by crackmanix** [comment]
does it solved the problem?

**Comment by chnge** [comment]
make sure you fill in the "sess" and the "fp" section I skipped them cuz the tutorial said optional but mine didnt work until I filled those in with the info in the "cookies" tab in chrome browser network debugger

**Comment by crackmanix** [comment]
I tried to fill the sess and the fp.
I deleted the cookie to be sure to have a brand new situation.
But still the same result, not working

**Comment by Jarsky** [comment]
> I tried to fill the sess and the fp.
> I deleted the cookie to be sure to have a brand new situation.
> But still the same result, not working

If you're using the older config.json, then try and set "support_2fa" to true, also set all the "text_length" values to 255

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit, if you're using 2fa, add in the auth_unique cookie to the cookie

**Comment by dilemmax** [comment]
I'm still getting access denied with the new commit. I cleared the cookie and notice this after activating 2fa.

auth_uniq_*myuserid*=7ddb929af1da63a20c2dce2b2e78db7d

**Comment by DIGITALCRIMINAL** [comment]
@dilemmax ye, did you add it to the cookie file?

**Comment by dilemmax** [comment]
Cookie file?
