### ISSUE TITLE
compare metadata?

### ISSUE THREAD

**Issue by tomhans18** [DIGITALCRIMINAL/OnlyFans#285]
Hello DIGITALCRIMINAL,

it would be greate if it would be possible to move my downloaded content to an external drive and the downloader still only downloads the new content.

I tought about as possibility to compare the new metadata with the last one and only download the diff.

Thanks for the great work.
tomhans18

**Comment by Balgden** [comment]
youtube-dl has a `--download-archive` feature that might server as a template for this.

**Comment by aschettler** [comment]
You can do this. I have moved all content between drives and subfolders without problem. Just move the folder and set the download folder in the config.json file. If you are concerned about the Metadata being incorrect, you can run a search in the download folder for ".json" and delete all the files. Your other option would be to run the script in metadata-only mode (./start_ofdl.py -m) before running it in download mode. All metadata should be replaced after running the script.

**Comment by aschettler** [comment]
After re-reading your comment, I do agree that it would be awesome if the script could detect existing files and metadata and add the difference.

**Comment by DIGITALCRIMINAL** [comment]
I don't have enough confidence to do that tbh. 
What I can do is allow additional file paths to be searched by the script for model folders.
