### ISSUE TITLE
Ignore free profiles

### ISSUE THREAD

**Issue by bollerdominik** [DIGITALCRIMINAL/OnlyFans#289]
I would like to request a feature to disable scraping of free profiles (subscribePrice = 0).
I know there is the blacklist feature but a flag to ignore free profiles would be preferred as I do not need to keep updating the blacklist.

Thanks for creating this tool.

**Comment by DIGITALCRIMINAL** [comment]
Done, download the latest commit

https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/README.md#ignore_type
