### ISSUE TITLE
Why did the folder structure change?

### ISSUE THREAD

**Issue by dkwtfigo** [DIGITALCRIMINAL/OnlyFans#291]
I'm a tech-retard, just tryna bust a nut, so bear with me if my question is dumb.
Anyway, I just downloaded the latest 5.0 release after I wasn't able to auth any longer with 4.9.
But now the settings and sites folder have a dot in front of them, making them invisible on MacOS.
Not that much of an issue, but the whole structure inside the folder seems to have changed as well?
Used to be "model/Posts/Videos" (or Images)
Now it's "model/Posts/Free/Videos" (or Images)
And the path of the Metadata is also different so it downloaded everything I already had again.
Just wondering if that is the way it's supposed to be or if I messed something up.

**Comment by DIGITALCRIMINAL** [comment]
The script is supposed to move everything (or as much as it can) to the new structure automatically
