### ISSUE TITLE
Cannot run it on mac with python 3.x installed.

### ISSUE THREAD

**Issue by championofdeath** [DIGITALCRIMINAL/OnlyFans#292]
![Screenshot 2020-06-20 at 12 10 25](https://user-images.githubusercontent.com/44276783/85199416-e6082a00-b2de-11ea-8a61-d5105d1d5e81.png)

This is what I'm getting.

**Comment by DIGITALCRIMINAL** [comment]
Follow the tutorial
https://github.com/DIGITALCRIMINAL/OnlyFans

**Comment by championofdeath** [comment]
I did it. Those exact files work on Windows10 machine but do not on MacOS.
I have pythjon 3.7. I ran pip3 install -r requirements.txt
Here's a screenshot of me upgrading python, installing requirements and running the script again. 
Might be something caused by the python versions? OS says I have 3.7.7 however in the requirements install the python directories are called 3.8... 
Anyways thanks for the fast answer. Looking forward the solution :(
![Screenshot 2020-06-20 at 19 15 36](https://user-images.githubusercontent.com/44276783/85207669-f12c7b80-b319-11ea-81e9-6ab811bb0cc1.png)

**Comment by DIGITALCRIMINAL** [comment]
Oh, you need to install and use Python 3.8 and above

It says here that you're installing the modules into the Python 3.8 folder (which is correct), but you're running the script with Python 3.7 modules. You need to run the script with Python 3.8.

Try ``` Python 3.8 start_ofd.py```

**Comment by championofdeath** [comment]
Apparently python is not working properly. I installed 3.8 and I need to make it default with this command echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> ~/.zshrc

but it keeps saying access denied idk why. Anyways looks like its not a script problem but my computer's. Thanks anyway I will stick with my Windows 10 machine to run it apparently

**Comment by championofdeath** [comment]
nvm it worked!! installed python 3.8 as app and deleted everything I had with brew. Then reinstalled dependencies and it works!

Thanks for your time and help.

**Comment by DIGITALCRIMINAL** [comment]
Nice, enjoy the script :)
