### ISSUE TITLE
Where to find auth_uniq_?

### ISSUE THREAD

**Issue by Dnto160** [DIGITALCRIMINAL/OnlyFans#294]
In the "cookie" section i can't find it and the voice is not included in your original sample, where do i find it?

**Comment by DIGITALCRIMINAL** [comment]
What voice

**Comment by fuomag9** [comment]
Same issue here, I haven't got any auth_uniq_ cookie

**Comment by DIGITALCRIMINAL** [comment]
Are you using 5.1?

**Comment by cannonball1911** [comment]
@Dnto160 

Do you use 2FA on Onylfans? If not, you probably won't get `auth_uniq_`. I don't have 2FA activated and I also don't get `auth_uniq_`. Just leave it blank in the `config.json` file. Just downloaded some stuff with 5.1 and it works fine for me.

**Comment by DIGITALCRIMINAL** [comment]
@cannonball1911 is right, if you're not using 2FA you don't need the cookie. I've updated the README to make it clearer.
