### ISSUE TITLE
Wrong documentation for application token

### ISSUE THREAD

**Issue by fuomag9** [DIGITALCRIMINAL/OnlyFans#295]
In the documentation the Application token is considered optional, while during the application execution the Application token is considered mandatory 

```
Auth (V2)
Auth Attempt 1/10
Application token is required.
```

**Comment by DIGITALCRIMINAL** [comment]
It's an optional change. By default, it'll already be entered for you. Did you delete it?

**Comment by fuomag9** [comment]
> 
> 
> It's an optional change. By default, it'll already be entered for you. Did you delete it?

You're right, I deleted it wrongfully. Thank you
