### ISSUE TITLE
NOT FOUND: C:\

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#298]
did just get 5.1 and get this error

NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images
FOUND: C:\temp\OnlyFans DataScraper v5.1\.sites\OnlyFans\sannarough\Posts\Free\Images
NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images
FOUND: C:\temp\OnlyFans DataScraper v5.1\.sites\OnlyFans\sannarough\Posts\Free\Images
NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images
FOUND: C:\temp\OnlyFans DataScraper v5.1\.sites\OnlyFans\sannarough\Posts\Free\Images
NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images
FOUND: C:\temp\OnlyFans DataScraper v5.1\.sites\OnlyFans\sannarough\Posts\Free\Images
NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images
FOUND: C:\temp\OnlyFans DataScraper v5.1\.sites\OnlyFans\sannarough\Posts\Free\Images
NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images
FOUND: C:\temp\OnlyFans DataScraper v5.1\.sites\OnlyFans\sannarough\Posts\Free\Images
NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images
FOUND: C:\temp\OnlyFans DataScraper v5.1\.sites\OnlyFans\sannarough\Posts\Free\Images
NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images
FOUND: C:\temp\OnlyFans DataScraper v5.1\.sites\OnlyFans\sannarough\Posts\Free\Images
NOT FOUND: C:\temp\OnlyFans DataScraper v5.0\.sites\OnlyFans\sannarough\Posts\Free\Images

It dont find the model name in .sites 

what have i done wrong?

**Comment by DIGITALCRIMINAL** [comment]
Just ignore it? It's not an error.
