### ISSUE TITLE
Long loading posts

### ISSUE THREAD

**Issue by Jar4ek** [DIGITALCRIMINAL/OnlyFans#299]
Hello, after the last update I noticed that my profiles on OnlyFans load for a long time. I don't know if it only occurs with me or it really is. The best part is that when I enter the website through the browser, all the profiles are loading, but they don't download the latest posts.

https://imgur.com/leQQJqH

And such loading even takes several hours and there is no reaction.

**Comment by DIGITALCRIMINAL** [comment]
OnlyFans is fucked atm

**Comment by Telandriq** [comment]
Seeing similar issue, hope @DIGITALCRIMINAL can shed some light on the increased load time/ downloads being hung up.

**Comment by DIGITALCRIMINAL** [comment]
Post the usernames you're having troubles in this thread
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/302
