### ISSUE TITLE
can't open file 'start': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#30]
Hi there,

I'm getting this error.

C:\OLF\modules>py start datascraper.py

C:\Users\User Name\AppData\Local\Programs\Python\Python37-32\python.exe: can't open file 'start': [Errno 2] No such file or directory

**Comment by dilemmax** [comment]
Fixed it by removing the space from start datascrapper.py

Just out of interested, how do I run it in cmd if I didn't change the file name?

**Comment by dilemmax** [comment]
I also got this error

ModuleNotFoundError: No module named 'win32_setctime'

and I fixed by installing the below.

pip install win32-setctime

Maybe this should be added to readme?

**Comment by bpo5r5** [comment]
It already is written in the readme https://github.com/DIGITALCRIMINAL/OnlyFans#mandatory

`pip install -r requirements.txt`

**Comment by dilemmax** [comment]
Of course! I should've read it. Thank you!

Do you know how to run a python script if there is a space in the file name?

**Comment by DIGITALCRIMINAL** [comment]
Start Datascraper.py should not be in the module folder

**Comment by dilemmax** [comment]
Not sure why it was in there. I moved it to the correct folder and I'm still getting "can't open file 'start': [Errno 2] No such file or directory".

Anyway I worked it out. I typed py "start datascraper.py" in cmd and it worked.
