### ISSUE TITLE
Directory issue

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#301]
I just downloaded 5.1, but there seems to be a weird directory issue. Previously, I had the directory (now "download_path" in the config file) set to X:\\OnlyFans, but the ripper would download everything into a sub-folder instead (X:\\OnlyFans\onlyfans).

With 5.1, the ripper downloads everything into X:\\OnlyFans, without a sub-folder, which is fine and good - but if I move all of my previous content/folders from X:\\OnlyFans\onlyfans into X:\\OnlyFans, the ripper runs into an error. It tries to read from the original directory, with the sub-folder, even though it should simply update the folders in X:\\OnlyFans.

Is there something I'm doing wrong, or is this by design?

**Comment by avekifes** [comment]
For now, I simply set "download_path" in the config to "X:\\OnlyFans\\onlyfans" and left my content/folders where they were, but what if I wanted to move them into another directory in the future?

**Comment by herefromrdt** [comment]
I ran into this problem when I moved where I kept my local repo clone. The issue is the metadata JSON files in the directories with the content use absolute paths. So even though you moved it, the JSON still has the old folder path in it. I opened up the content folder in VS Code and did a find and replace on all references to the old path in any file, and replaced it with the new path. That fixed the issue for me.

Ideally, though, I think the paths in the JSON files should be relative to the download directory instead of absolute.

**Comment by DIGITALCRIMINAL** [comment]
> Ideally, though, I think the paths in the JSON files should be relative to the download directory instead of absolute.

I agree I'll see what I can do

**Comment by DIGITALCRIMINAL** [comment]
@avekifes what is your file_path_format?

**Comment by avekifes** [comment]
"settings": {
        "auto_choice": "a",
        "auto_scrape_names": false,
        "auto_scrape_apis": true,
        "download_path": "X:\\OnlyFans\\onlyfans",
        "file_name_format": "[{date}] {file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": false,
        "blacklist_name": "Blacklist"

**Comment by DIGITALCRIMINAL** [comment]
> "settings": {
>         "auto_choice": "a",
>         "auto_scrape_names": false,
>         "auto_scrape_apis": true,
>         "download_path": "X:\\OnlyFans\\onlyfans",
>         "file_name_format": "[{date}] {file_name}.{ext}",
>         "text_length": "255",
>         "overwrite_files": false,
>         "date_format": "%Y-%m-%d",
>         "ignored_keywords": [],
>         "ignore_type": "",
>         "export_metadata": true,
>         "delete_legacy_metadata": false,
>         "sort_free_paid_posts": false,
>         "blacklist_name": "Blacklist"

Replace "onlyfans" with "{site_name}"
