### ISSUE TITLE
Ripper hanging on folders with a large amount of files?

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#302]
So, I'm not sure if size is the actual issue, but the ripper hangs on one of my accounts, which happens to contain nearly 10,000 photo/videos. It just says "download processing," but even after waiting over an hour, nothing seems to be happening.

I checked the logs folder but don't see anything. How can I troubleshoot this?

**Comment by DIGITALCRIMINAL** [comment]
which username are you trying to download

**Comment by avekifes** [comment]
busty_von_tease

**Comment by bollerdominik** [comment]
I have noticed something similar lately. On certain (large) profiles the script just gets stuck half way and does not continue. I have aborted it after waiting over an hour and then started scraping the same name again and it got stuck again. Other profiles work fine

**Comment by DIGITALCRIMINAL** [comment]
@bollerdominik what username are you trying to scrape

**Comment by bollerdominik** [comment]
shes6ft4 for example

**Comment by Telandriq** [comment]
briana_lee_xo hangs up for me.

**Comment by DIGITALCRIMINAL** [comment]
They updated their API and changed how they do pagination

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit.
I've downloaded all of nataliaxstarr content as well as some other accounts that hung for me
