### ISSUE TITLE
blacklist_name not working for more than one

### ISSUE THREAD

**Issue by WellSomething** [DIGITALCRIMINAL/OnlyFans#303]
Hi,

Wanted to try this feature to ignore scrapping for two usernames. First I added 1 user to the list, it worked. Then I added another user to the list, and it only worked for one of the usernames.

Second I tried doing two lists, with one username each... so I made 2 entries of blacklist_name in the config file, but same issue occurred, it ignored one of the usernames (or maybe it ignored one of the lists)... assuming that in order to include multiple lists I needed to do multiple "blacklist_name": "XXXX" entries (as opposed to 1 variable with multiple values, which I tried but if I did so both list would be ignored).

Haven't tried with more than two

So assuming I'm doing things correctly, it doesn't seem to be working with multiple usernames (or at least with 2 it isn't)... or I'm not doing this correctly.

Thanks.

**Comment by DIGITALCRIMINAL** [comment]
There should only be one list which consists of multiple users

**Comment by WellSomething** [comment]
Then that being the case, it was only working for me if I only had one user in it. When I added a second one, then it only blacklisted one of the users. The one that got blacklisted when the two were on the list (only tried with 2 specific users), was the lower one in alphabetical order and at the same time it was the latest user that your program listed (for example if no blacklisting occurred and these users were 25 - n and 26 - e, then 26 - e got blacklisted but 25 - n got scrapped).

**Comment by DIGITALCRIMINAL** [comment]
Thanks for this. Use the latest commit.
