### ISSUE TITLE
Value error on the main_datascraper.py file 

### ISSUE THREAD

**Issue by MRLshark** [DIGITALCRIMINAL/OnlyFans#307]
Hello, after I've been logged to my account through the CMD, I have this error :  line 163, in start_datascraper
    value = int(input().strip())
ValueError: invalid literal for int() with base 10: ''

You can see the error message that the CMD shows me here : https://prnt.sc/t9hvrj

Can someone help me please ? Thanks you

**Comment by DIGITALCRIMINAL** [comment]
Press 0?

**Comment by MRLshark** [comment]
Thanks you so much
