### ISSUE TITLE
Error possibly with config file?

### ISSUE THREAD

**Issue by pmd006** [DIGITALCRIMINAL/OnlyFans#308]
Updated on 6/29, ran start_ofd.py and updated the new config file in the .settings folder with my information. Getting the following when running the python script:

C:\Users\user\Downloads\OnlyFans-master>.\start_ofd.py
Traceback (most recent call last):
  File "C:\Users\user\Downloads\OnlyFans-master\start_ofd.py", line 5, in <module>
    main_test.check_config()
  File "C:\Users\user\Downloads\OnlyFans-master\tests\main_test.py", line 18, in check_config
    json_config = json.load(open(path))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 29 column 36 (char 902)

I double checked that I have the requirements installed:
C:\Users\user\Downloads\OnlyFans-master>py -m pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: beautifulsoup4 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 2)) (4.8.2)
Requirement already satisfied: urllib3 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 3)) (1.25.8)
Requirement already satisfied: win32-setctime in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: lxml in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 5)) (4.5.0)
Requirement already satisfied: pysocks in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 6)) (1.7.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from requests->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: soupsieve>=1.2 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (1.9.5)

Also verified my current python version:

C:\Users\user\Downloads\OnlyFans-master>py --version
Python 3.8.1

**Comment by DIGITALCRIMINAL** [comment]
What does your download_path look like?

**Comment by pmd006** [comment]
That was it. I was using "\" instead of "/". Thanks for the response.
