### ISSUE TITLE
Cannot auth in to Onlyfans today

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#311]
Having issues authing in, getting access denied. Nothing changed in my settings.

Updated auth_hash_sess_user_agent to latest with no luck

**Comment by docholllidae** [comment]
Are you on version 5.1?
I was getting that earlier when I was on an older version but updated and it worked.
If you haven't updated yet, when you first do the `config.json` isn't included anymore, but is auto-generated when you first run the script

Also make sure you get `fp` value; and `auth_uniq` if you're using 2FA

Doing all this fixed it for me

**Comment by bobsage123** [comment]
> Are you on version 5.1?
> I was getting that earlier when I was on an older version but updated and it worked.
> If you haven't updated yet, when you first do the `config.json` isn't included anymore, but is auto-generated when you first run the script
> 
> Also make sure you get `fp` value; and `auth_uniq` if you're using 2FA
> 
> Doing all this fixed it for me

Yeah did all that and am on 5.1. Not using 2FA so left those blank.

**Comment by bobsage123** [comment]
Closing. After second time logging in and re-adding all settings to settings its working.
