### ISSUE TITLE
Full Scrape Went from 10 Minutes to 3 Hours After Updating to 5.1

### ISSUE THREAD

**Issue by NotMyMainOne** [DIGITALCRIMINAL/OnlyFans#314]
Hello again,

For some reason the new version takes forever to run. I noticed it goes through every single file one by one during the initial scrape and says:
`FOUND: \full\file\path\ `
It doesn't say what the file is but it gives the file path for every item. It does eventually complete successfully but I'm curious as to what in the update causes this behavior.

"settings": {
        "auto_choice": "a",
        "auto_scrape_names": false,
        "auto_scrape_apis": true,
        "download_path": "{site_name}",
        "file_name_format": "{date} - {media_id}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "b",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": false,
        "blacklist_name": "Skip"

**Comment by WellSomething** [comment]
Was that the first time you ran it? Make sure you didn't redownload everything, it happened to me because there was a change in the directory structure. If that's not the case, hopefully you'll get help.

**Comment by DIGITALCRIMINAL** [comment]
The script goes through every file and converts them to the correct file_name_format.

**Comment by NotMyMainOne** [comment]
I'd understand if it was only the first go through but it does it and takes just as long on every single run without changing the file_name_format.

**Comment by DIGITALCRIMINAL** [comment]
Have you tried the latest commit

**Comment by NotMyMainOne** [comment]
Running it right now and it's going slow still. Is there a way to skip the OFRenamer process once we have all file names in the current format?

**Comment by DIGITALCRIMINAL** [comment]
How do you know it's running slow though? Does it say "FOUND" and waits a minute or is it something else?

**Comment by NotMyMainOne** [comment]
It's doing the Found message and taking a few seconds for every photo. So for accounts with thousands of photos it takes an extremely long time compared to before. Can that process be skipped?

**Comment by DIGITALCRIMINAL** [comment]
What's the username you're scraping

**Comment by NotMyMainOne** [comment]
sophiestonem (it's a free account). 

It was doing it with different accounts as well. Although funnily enough when I scraped another different user it went quick through the posts but then slow through the messages.

**Comment by DIGITALCRIMINAL** [comment]
> sophiestonem (it's a free account).
> 
> It was doing it with different accounts as well. Although funnily enough when I scraped another different user it went quick through the posts but then slow through the messages.

Yeah, I have to get messages a different way compared to getting posts since the API doesn't tell you total messages sent.

If you let the script go through the posts, you shouldn't see the "Found" message again.

**Comment by NotMyMainOne** [comment]
Unfortunately I'm still getting it and it goes through just as slowly the second time. Takes 90 minutes for that one account with no new content added.
