### ISSUE TITLE
Access Denied Logging

### ISSUE THREAD

**Issue by rustjunky** [DIGITALCRIMINAL/OnlyFans#319]
I have been using the 985 release until recently when it stopped working (Access Denied). I'm trying to execute the latest release but I'm getting Access Denied there as well. Is there any way to increase the output verbosity to help diagnose that? Aside from checking config.json for errors, is there any dependencies or conflicts with modules that I should be checking? I have installed the dependencies in requirements.txt.

Most of issues with the scraper are around login issues and I'm looking for solid troubleshooting steps.

**Comment by emhorstmann** [comment]
I think this has to do with them implementing re-captcha

**Comment by DIGITALCRIMINAL** [comment]
It always comes down to your cookies. Just log out and readd them
