### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by azureboss** [DIGITALCRIMINAL/OnlyFans#320]
I haven't been using the scraper for about a week now, I come back to try to use it and all of the auth attempts fail. However, the onlyfans account that I've been provided does not seem to be affected in any way

What do I do?

(here's what happens after I try to initiate the scrape)
**_Auth Attempt 1/10
Access denied.
Auth Attempt 2/10
Access denied.
Auth Attempt 3/10
Access denied.
Auth Attempt 4/10
Access denied.
Auth Attempt 5/10
Access denied.
Auth Attempt 6/10
Access denied.
Auth Attempt 7/10
Access denied.
Auth Attempt 8/10
Access denied.
Auth Attempt 9/10
Access denied.
Auth Attempt 10/10
Access denied.
Auth (V2)
Auth Attempt 1/10
Access denied.
Auth Attempt 2/10
Access denied.
Auth Attempt 3/10
Access denied.
Auth Attempt 4/10
Access denied.
Auth Attempt 5/10
Access denied.
Auth Attempt 6/10
Access denied.
Auth Attempt 7/10
Access denied.
Auth Attempt 8/10
Access denied.
Auth Attempt 9/10
Access denied.
Auth Attempt 10/10
Access denied.
There's nothing to scrape.
Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan_**

**Comment by jumbled37** [comment]
your login details have expired, you need to update the settings again
