### ISSUE TITLE
[Request] Separate Metadata Folder from Content.

### ISSUE THREAD

**Issue by ApacheTech** [DIGITALCRIMINAL/OnlyFans#321]
Currently, the Metadata folder is located at "**~\\.sites\\{site-name}\\{username}\\Metadata\\...**". This means that in order to keep a clean content directory, you have to delete the Metadata folder, and it renews itself with each update.

My proposal is that the Metadata folder would be taken out of the content folders entirely, and move to "**~\\.metadata**", with the folder structure: "**~\\.metadata\\{site-name}\\{username}\\...**".

This way, the content folders are not bloated with metadata, and much easier to manage.

Optionally, the scraper would move these folders automatically to the new location, if it finds them at the old location; to make it backwards compatible.

**Comment by DIGITALCRIMINAL** [comment]
I can't do that. Just turn #export_metadata to False.

**Comment by ApacheTech** [comment]
You definitely can do that. I've patched it to work almost exactly like that on my local copy. Although, I use a slightly different folder structure. There's no reason for the metadata to bloat the contents folders.

**Comment by DIGITALCRIMINAL** [comment]
I know, but I'm not doing it. Too much work. I already have to add backwards compatibility for other metadata locations.
