### ISSUE TITLE
access denied 

### ISSUE THREAD

**Issue by revcletis** [DIGITALCRIMINAL/OnlyFans#323]
I have download and configured the latest OF scraper as of the writing of this incident and I am getting this 
Auth (V1)
Auth Attempt 1/10
Access denied.
Auth Attempt 2/10
.
.
.Auth (V2).
..
.
Auth Attempt 9/10
Access denied.
Auth Attempt 10/10
Access denied.
There's nothing to scrape.

I have a working account, and entered all values corrrectly .. Please advise

**Comment by docholllidae2** [comment]
in your browser, try logging out and then deleting all OnlyFans cookies. refresh the page and log back in (make sure to select remember for 30 days if using 2fa) and then put the new values into the config. This has worked for me

**Comment by DIGITALCRIMINAL** [comment]
> in your browser, try logging out and then deleting all OnlyFans cookies. refresh the page and log back in (make sure to select remember for 30 days if using 2fa) and then put the new values into the config. This has worked for me
