### ISSUE TITLE
Change Length of File Name

### ISSUE THREAD

**Issue by RickyBubbles** [DIGITALCRIMINAL/OnlyFans#330]
If I have been limiting my file names to 50 characters, but would like to increase that to 100 because descriptions are being truncated, is there a way to do that without re-scraping everything?

I would even be okay with not changing what is already there, I just want to change the filename format going forward and not have the scraper re-download everything due to a filename mismatch.

**Comment by DIGITALCRIMINAL** [comment]
I think the script already handles that
