### ISSUE TITLE
OFRenamer Not Working As Standalone

### ISSUE THREAD

**Issue by NotMyMainOne** [DIGITALCRIMINAL/OnlyFans#334]
Hi,

I'm trying to run the Renamer on its own to rename the files of models I no longer follow but still have all their folders saved as is with metadata still there. I double clicked it and saw it said to place the path to the main config in the Renamer config but upon double clicking it to start it just shows up and shuts back down right away without making any changes. The model I'm trying to rename the files for is located in the main .sites/onlyfans folder. Is there another step or something that I'm missing?

**Comment by DIGITALCRIMINAL** [comment]
Have you filled in the config in ofrenamer
