### ISSUE TITLE
Not downloading all images

### ISSUE THREAD

**Issue by xathian** [DIGITALCRIMINAL/OnlyFans#337]
I've had this issue with all accounts I've tried to scrape. I get their videos just fine but I always get a fraction of their images.

Account A has 21 images, I can see all of them in the browser. It only scrapes 6
Account B has 131 images, I can see all of them in the browser. It only scrapes 89
Account C has 344 images, I can see all of them in the browser. It only scrapes 216

Also, is the scraper supposed to stick all the posts it grabs into a folder called 'Free' even if it's paid content? I know it's not only scraping free posts because I am getting videos and images from accounts with no free content on them.

**Comment by docholllidae2** [comment]
I think that in this context, "free" simply means you didn't pay extra for it (ptv posts)
I could be wrong though

**Comment by DIGITALCRIMINAL** [comment]
@xathian what are the account username that you're having trouble with.
