### ISSUE TITLE
[Feature Request] Scrape Profile images on OnlyFans

### ISSUE THREAD

**Issue by qazsedcftgbhujmkol** [DIGITALCRIMINAL/OnlyFans#339]
Request:
add the ability to scrape profile pictures (the rounded profile picture and the rectangular profile header picture).
e.g. for the https://onlyfans.com/nosex page:

the avatar picture is:
<img src="https://public.onlyfans.com/files/thumbs/c144/4/4l/4la/4laoxklxzopnpvdwhrvrhauzzdqn3uez1580455684/-479KrZb_normal.jpg" alt="sfw">
and the header picture is:
<img src="https://public.onlyfans.com/files/thumbs/w760/2/2p/2pi/2pi32jgt2qv6c5lp52smqmcfwre7p3zf1580455684/header.jpg" alt="sfw">

It's not a huge change, but I think it might be a nice thing to eventually have the two pictures dumped in .sites/{name}/Profile/ as header.{ext} and avatar.{ext} (afaik these are the file names that onlyfans assigns the files, so no extra work renaming the file once it has been downloaded).

**Comment by aboredpervert** [comment]
I notice that a _full-size_ profile image URL is actually returned in the JSON.

The one shown on the page, that you can right-click and View Image, is only the thumbnail version.

**Comment by avekifes** [comment]
Sshhh...some of these thots think they've cropped their faces out of their avatars, ha ha...

**Comment by DIGITALCRIMINAL** [comment]
the folder structure will be

username/profile/avatars/image
username/profile/headers/image

**Comment by DIGITALCRIMINAL** [comment]
Done
