### ISSUE TITLE
Not downloading all content 

### ISSUE THREAD

**Issue by MadamJazzy** [DIGITALCRIMINAL/OnlyFans#347]
One of the people i follow has 60 photos and 118 videos. When i run this however it only downloads 6 videos? It does however get all of the photos.

**Comment by DIGITALCRIMINAL** [comment]
which model is it?

**Comment by MadamJazzy** [comment]
@the-entertainer

**Comment by frontclip** [comment]
Having the same issue, not downloading all images or videos. Trying from "foshposh" which have 253 photos and 89 videos. Scrapes and downloads 167 images and 17 videos.

**Comment by mellow0324** [comment]
Be sure that you have unlocked or are not counting the locked content. The counts on the page includes posts on the feed that you have to pay to unlock. So it may not be downloading "everything" on the profile but it is downloading the posts you have access to.

**Comment by MadamJazzy** [comment]
Site shows i have access to 118 videos. Although i'll admit i thought you might be right. However i went through and counted on the video page 112 vids (so like 6 don't show for me) but still a far off number from 6 to 112

**Comment by frontclip** [comment]
> Be sure that you have unlocked or are not counting the locked content. The counts on the page includes posts on the feed that you have to pay to unlock. So it may not be downloading "everything" on the profile but it is downloading the posts you have access to.

100% sure that's not the issue. I manually downloaded the videos with a browser extension and that number matched the available videos.

**Comment by TronVonDoom** [comment]
I initially thought this was an issue as well. The model was showing 319 videos, but only 88 or so were downloading. I contacted the model, and they said that they had 88 available, and the rest were locked. @mellow0324 would be correct.

**Comment by DIGITALCRIMINAL** [comment]
@MadamJazzy I finished downloading the-entertainer's content and I was able to download all 118 videos and 60 images. I recently pushed a commit, maybe it fixed the problem.

**Comment by mortimerhobbs** [comment]
Having the same issue. Profile says there are 47 photos and 159 videos. I spot checked and none of them are locked. I can view them on the site. Scraper places everything into >posts > free where there are only 25 images and 41 videos. 
Just set up using the onlyfans-master.zip

**Comment by DIGITALCRIMINAL** [comment]
Nvm... I also got the bug, I'll fix it later.

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by thorwart** [comment]
having this issue with the latest code. i have access to 47 photos and 68 videos for an account but when i run the script it finds only 6 images and 11 videos and puts them in the Free folder. however after running several times, one of the times it found 47 images and put them in the Free folder, but it doesn't seem to find them again. the videos it never found

**Comment by DIGITALCRIMINAL** [comment]
What's the username

**Comment by thorwart** [comment]
@DIGITALCRIMINAL brattytatty

**Comment by BoxFit3** [comment]
Yup, still the same issue for me as well

**Comment by hirezz** [comment]
Update: Used the newest commit and the scrape worked successfully grabbing every file. However, it only works for me if I add {file_name} somewhere in the "file_name_format" config line. 
My config line is "{post_id} - {file_name}.{ext}" so files are listed in sequential order. Will look into a simple way to regex out the {file_name} portion of the file name which is non-descriptive.

**Comment by DIGITALCRIMINAL** [comment]
> Update: Used the newest commit and the scrape worked successfully grabbing every file. However, it only works for me if I add {file_name} somewhere in the "file_name_format" config line.
> My config line is "{post_id} - {file_name}.{ext}" so files are listed in sequential order. Will look into a simple way to regex out the {file_name} portion of the file name which is non-descriptive.

Why are you using only using post_id? It's not a unique identifier. It should be media_id.

**Comment by BoxFit3** [comment]
Was this issue supposed to be patched in the latest commit? Still seems to be missing files for me

**Comment by DIGITALCRIMINAL** [comment]
The 2nd last commit was supposed to somewhat fix it...

What's the account you're trying to scrape?

**Comment by BoxFit3** [comment]
@DIGITALCRIMINAL Tried it on a couple actually: sophiebrielle8 scrapes 35/130 images and 40/96 videos; @yummy_yum-yum scrapes 391/705 images and 44/59 videos; ashleyaoki scrapes 98/1483 images and 10/105 videos

**Comment by DIGITALCRIMINAL** [comment]
I see what the problem is now... Basically I have fixed the situation with skipped posts, but my script only counts "sets" meaning it doesn't individually count the media in the media set (5 images in 1 post, etc)

You should have the correct amount of content in the folder right?

**Comment by BoxFit3** [comment]
Understood what you meant in the first part

>You should have the correct amount of content in the folder right?

No to that part

**Comment by DIGITALCRIMINAL** [comment]
> Understood what you meant in the first part
> 
> > You should have the correct amount of content in the folder right?
> 
> No to that part

I successfully downloaded 1483 images from her .-.

**Comment by BoxFit3** [comment]
@DIGITALCRIMINAL w/Latest commit

![Screenshot_3](https://user-images.githubusercontent.com/68820625/88839314-e7175b80-d1a8-11ea-8c94-50b7a7894c54.png)

**Comment by DIGITALCRIMINAL** [comment]
What's the filename format

**Comment by BoxFit3** [comment]
> What's the filename format

{date} {file_name}.{ext}

**Comment by frontclip** [comment]
Just wanted to comment that for me it scrapes all content now. Although it shows the wrong amount in the script, the correct amount gets downloaded.

**Comment by BoxFit3** [comment]
Hmmmm...wonder what's wrong on my end

**Comment by hirezz** [comment]
> 
> 
> > What's the filename format
> 
> {date} {file_name}.{ext}

Using date as the first part of the string doesn't work for me. Have to use something like "{media_id} - {date}.{ext}" if you want to maintain the date information.

**Comment by BoxFit3** [comment]
Well I managed to get it working after creating an entirely new windows profile. Guessing something is up with my last one, anyway thanks for the help everyone. Cheers as always @DIGITALCRIMINAL

**Comment by BoxFit3** [comment]
Well managed to get it working by creating an entirely new windows profile, still seems a bit buggy seeing that I had to run the script twice to complete a scrape. Guessing something was up with my other profile, thanks for the help everyone. Cheers as always @DIGITALCRIMINAL

**Comment by TheMonDon** [comment]
I'm still having this issue with every person I tried, I even tried the new windows profile thing but couldn't get that to work either.

**Comment by DIGITALCRIMINAL** [comment]
> I'm still having this issue with every person I tried, I even tried the new windows profile thing but couldn't get that to work either.

You shouldn't have to create a new windows profile.

What is your auto_choice set to in the config?

**Comment by TheMonDon** [comment]
> You shouldn't have to create a new windows profile.
> 
> What is your auto_choice set to in the config?

I have auto choice set to a normally, but for troubleshooting, I set it to c.

**Comment by BoxFit3** [comment]
Yup, still having the same issue :/

Thought the new profile thing worked but I guess I got lucky with one sub that wasn't working before, the rest is the same. Tried redownloading the latest commit and only inputting the data that was mandatory without changing any other configs but still skipping

**Comment by DIGITALCRIMINAL** [comment]
> > You shouldn't have to create a new windows profile.
> > What is your auto_choice set to in the config?
> 
> I have auto choice set to a normally, but for troubleshooting, I set it to c.

When set to a, does it not download all the content?

**Comment by thorwart** [comment]
i'm still having the same issue after pulling the latest code. i also reset my config and the only things i changed were `username`, `auth_id`, `sess` and `user_agent`. i then tried with `fp` changed too. still only finding 6 images and 11 videos

**Comment by BoxFit3** [comment]
Damn they really cracked down on us this time

**Comment by thorwart** [comment]
might it be paging related? it seems to find only the oldest 11 videos in the list of videos i can see

**Comment by Przew87** [comment]
Same here, out of the 10 creators I am subscribed to, only 2 got fully scraped - one is the model which has started her OF the most recently and another is a free account of another model I follow (also fairly recent account). Another relatively recent account got all the posts scraped, but none of the content she sent via DM. For all the rest, I only get the oldest content up to a certain point, but that point is different for each creator - for some it was a week after they started posting, for others several months and in one case a bit over a year (but it's also not the same calendar date, checked that). One account that posted over 1600 pics and 100 vids, no feed content got scraped at all, just some of the DM content. I can compile an overview of accounts and how much did and did not get scraped if needed.

**Comment by otisrush** [comment]
Same here, out of the 10 creators I am subscribed to, only 2 got fully scraped - one is the model which has started her OF the most recently and another is a free account of another model I follow (also fairly recent account). Another relatively recent account got all the posts scraped, but none of the content she sent via DM. For all the rest, I only get the oldest content up to a certain point, but that point is different for each creator - for some it was a week after they started posting, for others several months and in one case a bit over a year (but it's also not the same calendar date, checked that). One account that posted over 1600 pics and 100 vids, no feed content got scraped at all, just some of the DM content. I can compile an overview of accounts and how much did and did not get scraped if needed.

**Comment by thorwart** [comment]
today i run it and surprisingly it found 43 images and 67 videos! it still dumped them in the `free` folder but thats ok

**Comment by otisrush** [comment]
the issue apparently fixed itself, after running the script this morning (no changes from my last attempt whatsoever, did not use the latest commit - I'm still running the version from Wednesday), every single piece of content from all accounts got scraped, it even managed to find more pics and vids than OF is showing in some cases (e.g. 230 pics downloaded vs 229 indicated on OF etc.)

**Comment by TheMonDon** [comment]
I agree it seems to have fixed itself, its downloading everything now.

**Comment by July211** [comment]
what are the steps i have to take in order to find a models content

**Comment by vinsh3nt** [comment]
I am still having this issue even on the latest commit, scrapes about half the pics.

**Comment by johnwig** [comment]
Hi. I am having the same issue. I never really paid attention, but just now I decided to check them out.

I tried on `@noisettebaby` which have 69 videos. I counted manually and stopped at 30. This script only downloaded 22 videos.
