### ISSUE TITLE
Anyone else have thier OF account suspended recently?

### ISSUE THREAD

**Issue by lidem39228** [DIGITALCRIMINAL/OnlyFans#350]
Sorry i know this is not the right place because its not exactly an issue with this repo but wanted to get an idea if there they are cracking down on accounts using the tool or if i just have bad luck.

So let me start at the beginning of this week. After the new signing requirement was implemented i had to fussed around with different browsers and finally got the program to work again. Because of this i ended up with two sets of valid cookies from different user agents. both worked when i got the signing hash correct.

Two days ago i noticed the program stopped working again and i went to again into ino my account to investigate abut i could not login. it said password or username incorrect. I thought maybe i was hacked and someone got in my account and changed the password so submitted a password reset. I waited and waited but it never came. I filled out another  and waitied again but nothing. I checked my emails spam folder. Nothing. 

Now today when i try to sign in or request a password reset i get the message that the account is suspended. No reason specified, no email confirming or stating this. just suspended.

to probably answer you initial question,  no i never shared any of the content that i downloaded. i only run the program from my computer at home and save it to an external hard drive. No cloud storage.
I also had my account for 8 months and used this program multiple times. My guess is that with the changes this week i must have triggered something.

Any one else see something similar?

**Comment by DIGITALCRIMINAL** [comment]
Really? Have you installed any Chrome Extensions recently?

**Comment by lidem39228** [comment]
No i have never used any browser extension designed for Onlyfans. You just made me remember that i did recently reinstall an extension but i have used it before with no issue. [Tamper Chrome](https://chrome.google.com/webstore/detail/tamper-chrome-extension/hifhgpdkfodlpnlmlnmhchnkepplebkb). I was using it earlier this week to watch the requests and step through them. I do not think i doofed up something since i was just watching but i am not sure now. 

If no one else has a suspension issue then i would say i have an unrelated problem going on here.

**Comment by DIGITALCRIMINAL** [comment]
Hmm, it's best if you email them
support@onlyfans.com or contact them on twitter

https://twitter.com/onlyfanssupport
