### ISSUE TITLE
Will scraper "pick up where it left off"?

### ISSUE THREAD

**Issue by BobbyBadass** [DIGITALCRIMINAL/OnlyFans#353]
Scraper worked great but was using all my bandwidth. I live with other people so had to stop the process after it had downloaded around 30GB of videos.

My question is, if I start the scraper again with the same setup, will it pick up where it left off -- i.e. will it ignore completed downloads, finish partially completed downloads, and download new/missing videos it didn't start yet?

Or will it simply start from the beginning and overwrite the existing downloads?

Thanks! BTW, happy to "buy you a coffee" -- where do I do that?

**Comment by DIGITALCRIMINAL** [comment]
Hello, glad you liked the scraper, and yes the script automatically checks the files you've downloaded and skips them.

I just signed up to this sign if you'd like to donate, thanks.
https://www.buymeacoffee.com/datahoarders

**Comment by BobbyBadass** [comment]
Done! :)

**Comment by DIGITALCRIMINAL** [comment]
> Done! :)

Thank you c:

**Comment by DIGITALCRIMINAL** [comment]
But yes, the script skips files you've completely downloaded. If you quit the script midway through a download, it'll know that it's corrupted and will download the file again. So you're free to quit the scraper at any time.
