### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by A4th** [DIGITALCRIMINAL/OnlyFans#356]
I mean sorry noob question but I installed all the modules using pip but when I type "start_ofd.py" at the command terminal, it says no module named 'requests'

**Comment by artyom2035** [comment]
Which version of Python? You may need to install the modules using pip3. Check versions using these commands

python -V
python3 -V
pip -V
pip3 -V

**Comment by DIGITALCRIMINAL** [comment]
Then you didn't install it properly. Make sure it's installed for Python 3.8
