### ISSUE TITLE
Scrapping is not picking up all videos

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#36]
I'm data scrapping videos from a particular account with 140 videos but it's only picking up 100 videos.

**Comment by DIGITALCRIMINAL** [comment]
What account?
The account probably has pay per view videos.

**Comment by dilemmax** [comment]
https://onlyfans.com/jaxxxyboy

I was able to pull the remaining videos using a Chrome extension.

**Comment by dilemmax** [comment]
Not sure if this helps, it's not pulling videos before 30/05/2017

**Comment by DIGITALCRIMINAL** [comment]
Hmm, is that for all accounts for is this just for one?

**Comment by DIGITALCRIMINAL** [comment]
I got the bug as well. I think it's because I had to update my auth_hash since it was outdated.

**Comment by dilemmax** [comment]
just this one only but I haven't encountered any accounts that has posts that was dated so far back.

**Comment by DIGITALCRIMINAL** [comment]
Hmm, I think it's just an OnlyFans API issue. Hopefully, a one-off because when I got the error, I just kept retrying to scrape and it did eventually work. Reopen this if it occurs again.

**Comment by dilemmax** [comment]
Hey there, I just found another account with posts older than 2017 and it's not scrapping all of them.
