### ISSUE TITLE
Unable to create session (2nd issue created, 1st got closed before I could say that the fix didn't work)

### ISSUE THREAD

**Issue by qazsedcftgbhujmkol** [DIGITALCRIMINAL/OnlyFans#365]
I git cloned the repo a few minutes ago.
I installed requirements via pip.
I ran start_ofd.py
I filled in the auth_id, sess, user-agent and auth_uniq_ values.
I pressed enter (to proceed and have the script load the config)
I still get:
```
T:\#OnlyFans>py start_ofd.py
Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan | x = Exit
0
Unable to create session
There's nothing to scrape.
Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan | x = Exit
```

I ran the script using an IDE.
modules/onlyfans.py line 613
`for proxy2 in proxy:` , my proxy variable is an empty list, so the function returns null up to `session = x.create_session()` at datascraper.py line 107 .

I hope that helps.

If you want someone to run the script in debug to help confirm that the fix works on a blank install, I'm happy to help, just ask.

**Comment by DIGITALCRIMINAL** [comment]
I made a commit just before you made this issue. I did a commit a few hours earlier but I accidentally overwrote it with an old commit. Anyways, if you download the latest commit, it'll fix it.

**Comment by qazsedcftgbhujmkol** [comment]
Thank you for all your time and effort.
It works perfectly!

I wish I understood python enought to be some actual help with this project.

Thank you.
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/361
