### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by TommyA89** [DIGITALCRIMINAL/OnlyFans#366]
Could you update the README file describing how to use and set the proxies?

I'm getting Access denied error on authenticating on OnlyFans even changing the authentication properties. 
Every time I try to run the script my web session on OnlyFans ends and I have to login again.

I think that these things are correlated but any other suggestion is appreciated.

**Comment by DIGITALCRIMINAL** [comment]
There's lots of different proxy format, I can't just add them all in.

My format is:
username:password@hostname:port
