### ISSUE TITLE
Read Timeout

### ISSUE THREAD

**Issue by vinsh3nt** [DIGITALCRIMINAL/OnlyFans#369]
Getting this error when scraping creator nebraskawut

HTTPSConnectionPool(host='onlyfans.com', port=443): Read timed out. (read timeout=10)
followed by a number of other exceptions.

Scrapes a majority of the posts but not all.

**Comment by BatmanAndWilly** [comment]
I am getting this as well. I don't think it matters which `Name` page you are trying to scrape. For me, it sometimes downloads a few files before throwing this error, and other times it happens immediately.

Doesn't seem to matter whether I am scraping `0 = All` or any other specific individual page:

`Scrape Processing
Name: XXXXXXX
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
2020-08-05 16:00:30,641 ERROR errors HTTPSConnectionPool(host='onlyfans.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "D:\Virtual\Python\OnlyFans\venv\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Virtual\Python\OnlyFans\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "c:\users\XXXXX\appdata\local\programs\python\python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "c:\users\XXXXX\appdata\local\programs\python\python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "c:\users\XXXXX\appdata\local\programs\python\python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\XXXXX\appdata\local\programs\python\python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\XXXXX\appdata\local\programs\python\python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\XXXXX\appdata\local\programs\python\python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out`

This was happening for the last few days. I left it alone for a few days, figuring it was a new bug, but after pulling the latest commit this is still happening.

**Comment by vinsh3nt** [comment]
Yeah it seems you're right, I just tried it with another creator, I still get the error.

**Comment by BatmanAndWilly** [comment]
I tried setting `multithreading` to `false`, as well as the `auto_` settings, but I still get this error.

I am not much of a software developer, and I don't know enough Python to dig into the code to see what's happening, but I am a sysadmin and this looks to me like some kind of anti-scraping measure put in place on their webserver(s). Like maybe it looks for a certain pattern of connection requests hitting the server that is indicative of a scraper. I am totally speculating, though...

So, my thinking was to change the config file to allow me to download one file at a time for testing purposes. But even with all of the above settings changed to `false` it still craps out.

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by vinsh3nt** [comment]
Scraper seems to hang after making a selection on latest commit

**Comment by BatmanAndWilly** [comment]
> Try latest commit

It is now working for me. Thank you!

Was this error simply a result of the scraper timing out when OF is slower than usual? I looked at your commit and it looks like you just had to remove the timeouts.

**Comment by BatmanAndWilly** [comment]
> Scraper seems to hang after making a selection on latest commit

I would bet that you are simply not waiting long enough. As I am typing this, I am running the scraper, and it is taking a long time to begin downloading. I am inclined to believe that the slowness is coming from the OF server side.

Just be patient and let it run. It is working 100% for me despite just being a bit slower.

**Comment by vinsh3nt** [comment]
I have let it run, it hangs, says the scraping is complete, doesn't scrape anything.

**Comment by DIGITALCRIMINAL** [comment]
The reason why it's a bit slower is because there's a delay between 2-5 of each request to ensure the request succeeds

**Comment by vinsh3nt** [comment]
Re-entered my cookies, seems to be working fine now
