### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#37]
Just updated to the latest version and updated config.json. I'm getting this:

Site: 0 = onlyfans | 1 = justforfans
0
Access denied.

**Comment by DIGITALCRIMINAL** [comment]
Only happens when you've got the wrong user-agent, auth_token or auth_hash

**Comment by dilemmax** [comment]
I worked it out. I didn't realised you moved the user-agent further up. It's working now!
