### ISSUE TITLE
Is config.json template supposed to be missing from the .settings folder in 5.2?

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#370]

**Comment by DIGITALCRIMINAL** [comment]
No

**Comment by DIGITALCRIMINAL** [comment]
It gets created when you run the script for the first time without the config.json in the settings folder
![image](https://user-images.githubusercontent.com/21285176/89605621-e7c58700-d865-11ea-89ca-1b78df24a4ca.png)

**Comment by bobsage123** [comment]
Sorry please close, I will paste my config.jason from the previous version of nothing has changed in the lines in 5.2.

**Comment by DIGITALCRIMINAL** [comment]
The config gets updated automatically to the new version

**Comment by bobsage123** [comment]
Gotcha, should I go through the new automatic process or pasting my config from 5.1 is ok?

**Comment by DIGITALCRIMINAL** [comment]
yee that's fine
