### ISSUE TITLE
[Feature Request] Type creator name instead of number

### ISSUE THREAD

**Issue by AlexDucks** [DIGITALCRIMINAL/OnlyFans#372]
I follow an unhealthy amount of creators on OnlyFans (50+), so this is probably not something others would find all that useful, but I would.
Sometimes I just want to scrape one of the profiles to update with their most recent posts and it can be hard to find the right number to type in.

Therefore I propose a feature that would allow you to type in their "username" instead.
This would also indirectly fix a bug where typing in anything other than an `int` would practically crash the software.

Cheers :)

**Comment by DIGITALCRIMINAL** [comment]
I added this to the latest commit. Thanks.

**Comment by AlexDucks** [comment]
Appreciate the quick implementation, but it seems that typing `0` (for "All") now gives me "User not found".

Should I create another issue for that?

**Comment by DIGITALCRIMINAL** [comment]
I'll fix it

**Comment by DIGITALCRIMINAL** [comment]
fixed
