### ISSUE TITLE
Only Free content is downloaded

### ISSUE THREAD

**Issue by dxeel1** [DIGITALCRIMINAL/OnlyFans#373]
Content that i have bought wont download. Only the free folder is created. And if i get a message with a slideshow only the first item gets downloaded and saved.

**Comment by DIGITALCRIMINAL** [comment]
Which user are you talking about

**Comment by dxeel1** [comment]
There is multiple user i have bought from that doesnt get downlaoded, but as far i can tell is it only content sent in messages that wont download.

**Comment by DIGITALCRIMINAL** [comment]
You still haven't told me which user is incorrectly being scraped, and what is your filename format.

**Comment by dxeel1** [comment]
It seems its all users, but for an example [https://onlyfans.com/thelatexteacher](url)

**Comment by DIGITALCRIMINAL** [comment]
Just use {file_name}.{ext} as the filename format.

**Comment by dxeel1** [comment]
Yeah that fixed it. Thanks.
