### ISSUE TITLE
Changes to config file

### ISSUE THREAD

**Issue by RickyBubbles** [DIGITALCRIMINAL/OnlyFans#375]
Could you version the config file so that we can tell if we need to re-build it between script updates?

E.g. stick a readme in the .config directory that says “Config file v1.0”

For the most part it seems to stay the same between updates, but if a new version if the script requires a new file format. it would be cool to know if we can’t just re-use the old file.

**Comment by DIGITALCRIMINAL** [comment]
You can always reuse the same config file. Just drop it in the new version.
