### ISSUE TITLE
Auth attempt 

### ISSUE THREAD

**Issue by Exdner** [DIGITALCRIMINAL/OnlyFans#378]
I've been triyng for 2-3 hours now but still the same stuff.
Auth Attempt 10/10
Access denied.
There's nothing to scrape.

Also i cannot find auth_hash in the cookies and what do i put in the username in the extra_auth.json and config.json?

I'm really triyng my best here but i cannot get it to work. I would really appreciate some help.

**Comment by DIGITALCRIMINAL** [comment]
Ignore extra auth. As already explained on in the readme, if you don't have auth_hash then you don't need to add it in. There's nothing much I can say except to recheck your config.
