### ISSUE TITLE
syntax error trying to run program

### ISSUE THREAD

**Issue by mistamistaa** [DIGITALCRIMINAL/OnlyFans#383]
everything worked perfectly fine, then i updated my OS. now i get this error when trying to start

Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/Users/****/OnlyFans-5.2/tests/main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "/Users/****/OnlyFans-5.2/helpers/main_helper.py", line 128
    writer.writerow({**{media_type: "valid"}, **item})
                      ^
SyntaxError: invalid syntax

**Comment by DIGITALCRIMINAL** [comment]
Download from Master
https://github.com/DIGITALCRIMINAL/OnlyFans/archive/master.zip

**Comment by mistamistaa** [comment]
i can't even run the program in the first place to get there. thats the error i get when trying to start ofd.py

**Comment by DIGITALCRIMINAL** [comment]
Are you running the latest commit?

**Comment by choadrocker** [comment]
try python3 
on a mac after the lastest update python resolves to python 2.7

**Comment by mistamistaa** [comment]
> Are you running the latest commit?

by that do you mean launching "start_ofd.py" from the latest 5.3 folder? if so then yes. 
and when i run it with python3 i get this error

File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/Users/***/OnlyFans-master/tests/main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "/Users/***/OnlyFans-master/helpers/main_helper.py", line 18, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

but bs4 is already installed satisfied and says so when i try re-installing all requirements

**Comment by herefromrdt** [comment]
if it's using python 2 by default, you might have bs4 installed on the python 2 installation, but not the python 3 one. You need to make sure you install the requirements with the version of pip that's with your python 3 installation. I'm not that familiar with mac commands, so I can't really be much more helpful than that. Sorry.

**Comment by mistamistaa** [comment]
> if it's using python 2 by default, you might have bs4 installed on the python 2 installation, but not the python 3 one. You need to make sure you install the requirements with the version of pip that's with your python 3 installation. I'm not that familiar with mac commands, so I can't really be much more helpful than that. Sorry.

thank you herefromrdt, the issue was downloading bs4/requirements with matching version of pip. ~cheers
