### ISSUE TITLE
Files get saved outside the "Images/Videos" folders

### ISSUE THREAD

**Issue by n4m1e** [DIGITALCRIMINAL/OnlyFans#384]
With the latest release, rather than placing the files in the "Images" and "Videos" folders, they get placed in the "Free" folder.
The files themselves get the prefixes "Images/Videos".
[https://i.imgur.com/7vTESmx.jpg](https://i.imgur.com/7vTESmx.jpg)

File name format I use: "[{username}] {date} - {post_id}_{media_id}.{ext}"

Is there a backspace missing somewhere in my settings?

**Comment by jumbled37** [comment]
Exact same thing happening to me

**Comment by AlexDucks** [comment]
Yep. Looks like there's missing a `/` after `Videos` / `Images` and before the actual filename.

**Comment by DIGITALCRIMINAL** [comment]
I'm a clown. I'll create a separate script to fix this.

**Comment by DIGITALCRIMINAL** [comment]
I pushed a commit that fixed this 3 hours ago if you want my custom script to rename the files properly, let me know.

**Comment by n4m1e** [comment]
Updated to the latest version and works like a charm again. Thanks for all the hard work!
