### ISSUE TITLE
Files not downloading

### ISSUE THREAD

**Issue by Dolladole** [DIGITALCRIMINAL/OnlyFans#388]
After installing and running I get messages like this.

Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
FOUND: C:\Users\xyz\Documents\OnlyFans\.sites\OnlyFans\chyburd\Posts\Free\Images
FOUND: C:\Users\xyz\Documents\OnlyFans\.sites\OnlyFans\chyburd\Posts\Free\Images
FOUND: C:\Users\xyz\Documents\OnlyFans\.sites\OnlyFans\chyburd\Posts\Free\Images

But there is nothing found in these folders. When reviewing the metadata I am able to use the links there to view the content in browser and then download it manually.
It looks something like this, and does show the video.
https://cdn2.onlyfans.com/files/3/33/33084202cf1e8910bfd0de3b303f2c30/5f1ca36ae387b90bac3a2_source.mp4?Tag=1&Policy=redacted&Signature=redacted&Key-Pair-Id=redacted

**Comment by DIGITALCRIMINAL** [comment]
What is your filename format

**Comment by Dolladole** [comment]
"file_name_format": "{file_name}.{ext}",

Yes, it's a fresh repo clone of 5.3. I didn't make any changes to the default filename format. Using Windows 10.

**Comment by DIGITALCRIMINAL** [comment]
What user are you trying to scrape

**Comment by DIGITALCRIMINAL** [comment]
What is your download path format

**Comment by Dolladole** [comment]
"download_path": "{site_name}",
This is the default here as well. It creates a folder called .sites inside the Onlyfans folder created as a the repo and the folder structure inside there is correct.

trying to scrape several accounts but the example I pulled is from chyburd

**Comment by Dolladole** [comment]
I changed the download path to "Test" and the path it generated was 
 C:\Users\xyz\Documents\OnlyFans\.sites\Test\chyburd\Posts\Free\Images

**Comment by Dolladole** [comment]
Another interesting thing I just noticed is that the Avatars and Profile photos are downloading correctly. But again the folders are created for the correct content and it shows up in the metadata files.

**Comment by DIGITALCRIMINAL** [comment]
Are you able to view hidden folders?

**Comment by Dolladole** [comment]
Yes, hidden files and folders are enabled.

**Comment by Dolladole** [comment]
I think it has to be some issue with the default path. I'm not able to find where in the files it's adding the .sites to the path.

**Comment by DIGITALCRIMINAL** [comment]
@Dolladole in main_helper.py under ofrenamer, there is a function called get_directory which handles the .sites

**Comment by mnlg3456** [comment]
Using c8956d8
On the initial run,it didnt download everything,way less then 50%.And then if there are, for example, 30 new images and 10 new videos, it may only download 5-10 images and dosent touch the videos.Running it a second time it still does not see everything. 3+ tries later it may download the videos but its fully random. It seems to be blind to the new files or just dosent want to download.
I have not changed any config options other then the cookies settings.
