### ISSUE TITLE
StarsAVN errors 

### ISSUE THREAD

**Issue by ctrlcmdshft** [DIGITALCRIMINAL/OnlyFans#389]
Errors on downloads for StarsAVN

`2020-08-17 14:05:52,024 ERROR errors [Errno 22] Invalid argument: 'F:\\OnlyFans-5.3\\.sites\\StarsAVN\\leilanilei\\Highlights\\ImagesF:\\OnlyFans-5.3\\.sites\\StarsAVN\\leilanilei\\Highlights\\Images\\048eb35ff2f12c5cbfb9688274f50f74954368.jpeg'
 Tries: 0
Traceback (most recent call last):
  File "F:\OnlyFans-5.3\modules\starsavn.py", line 470, in download
    with open(download_path, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'F:\\OnlyFans-5.3\\.sites\\StarsAVN\\leilanilei\\Highlights\\ImagesF:\\OnlyFans-5.3\\.sites\\StarsAVN\\leilanilei\\Highlights\\Images\\048eb35ff2f12c5cbfb9688274f50f74954368.jpeg'
2020-08-17 14:05:52,026 ERROR errors`

**Comment by SteveJSzabo** [comment]
I had essentially the same error, but I was able to fix it myself.

To fix it, go to the modules\starsavn.py file and change line 459 from:
download_path = media["directory"]+media["filename"]

to:
download_path = media["filename"]

Then this will work.

**Comment by ctrlcmdshft** [comment]
Thanks that worked great!

**Comment by DIGITALCRIMINAL** [comment]
Fixed with latest commit
