### ISSUE TITLE
After editing the Config.json and getting to "enter username" script crashes

### ISSUE THREAD

**Issue by kave333** [DIGITALCRIMINAL/OnlyFans#39]
After editing config.json and running the .py and selecting which site, and then entering username. Script crashes and force closes itself. Nothing in the error log but briefly flashes up some information in the script window before closing.
![W1 (2)](https://user-images.githubusercontent.com/56347533/66478203-be936900-ea91-11e9-9c1e-d1a94f5b3a30.png)

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.7
