### ISSUE TITLE
Only Free videos Downloading

### ISSUE THREAD

**Issue by john4driver** [DIGITALCRIMINAL/OnlyFans#390]
I found that this was an issue posted earlier but the solution for the past one did not work for me. The name of the user Im trying to scrape is sammi-starfish. I am subbed to her content however it will not download her paid content and only downloads free content.

**Comment by DIGITALCRIMINAL** [comment]
Have you actually paid for the paid content.

**Comment by john4driver** [comment]
Yes I have payed for the content. I have access to the paid content through the actual website.

**Comment by DIGITALCRIMINAL** [comment]
What type of content is it? A post, or message?

**Comment by john4driver** [comment]
Wasn't working properly yesterday... suddenly started working today
