### ISSUE TITLE
Auto selecting only fans user when auto scrape names is set to true

### ISSUE THREAD

**Issue by john4driver** [DIGITALCRIMINAL/OnlyFans#391]
"auto_scrape_names": true

then selecting only fans

Will cause the program to auto select a name (for me it defaults to 1) not allowing you to select the name you want.

**Comment by DIGITALCRIMINAL** [comment]
Then set it to False? That's the point of the setting.

**Comment by john4driver** [comment]
My mistake. I had though the point of the setting was for filenames or something of that nature
