### ISSUE TITLE
Complete idiot here?

### ISSUE THREAD

**Issue by blackkami333** [DIGITALCRIMINAL/OnlyFans#396]
I'm already failing at the first goal. First time using python. How do I open a terminal in the folder?
Clicking start_ofd makes it isntantly dissapears.

I can open python just normally. But then I just don't know what to do next. Using "pip" there, says I'm using a wrong command.

**Comment by Code4Win** [comment]
Download python 3.8 

https://www.python.org/downloads/mac-osx/

Open terminal

https://support.apple.com/guide/terminal/execute-commands-and-run-tools-apdb66b5242-0d18-49fc-9c47-a2498b7c91d5/mac

CD <path to script>
Python3 start_ofd.py

**Comment by blackkami333** [comment]
This didn't help me at all. I'm on windows.
