### ISSUE TITLE
Choose whet ever videos I wanna download?

### ISSUE THREAD

**Issue by 999Jw** [DIGITALCRIMINAL/OnlyFans#397]
I’m just wondering how can I choose which videos I want to download ?
Can I get some help 
Thanks.

**Comment by DIGITALCRIMINAL** [comment]
Nope, you gotta download all or just use another program. There's an extension on Firefox called "Downloader for OnlyFans" or something like that.

**Comment by 999Jw** [comment]
Ok thanks for the response
