### ISSUE TITLE
win32-setctime not found and No module named bs4

### ISSUE THREAD

**Issue by realrEDGUY** [DIGITALCRIMINAL/OnlyFans#398]
EDIT: I'm using Linux ubuntu

This was during `pip install -r requirements.txt`
```
Collecting win32-setctime (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement win32-setctime (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for win32-setctime (from -r requirements.txt (line 4))
```

This was during `python3.8 start_ofd.py`
```
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/home/of_scraper/tests/main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "/home/of_scraper/helpers/main_helper.py", line 18, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

**Comment by SnappierCactus** [comment]
Hey, I just had this issue and solved it. 

First, make sure you install the requirements. The way I was able to do it was opening powershell on Windows then navigate to the folder and paste this command 

pip install -r requirements.txt --user

The first time I did it, I didn't have the --user at the end and it didn't install fully. After that try starting the start_pyd.py again

**Comment by realrEDGUY** [comment]
> Hey, I just had this issue and solved it.
> 
> First, make sure you install the requirements. The way I was able to do it was opening powershell on Windows then navigate to the folder and paste this command
> 
> pip install -r requirements.txt --user
> 
> The first time I did it, I didn't have the --user at the end and it didn't install fully. After that try starting the start_pyd.py again

Hey, just tried with the --user as you said and I still got the error. I'm guessing I need something else because this says win32-sectime
```
root@user:/home/of_scraper# pip install -r requirements.txt --user
Collecting win32-setctime (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement win32-setctime (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for win32-setctime (from -r requirements.txt (line 4))
```

**Comment by SnappierCactus** [comment]
After trying to look that error up, the only way I'm seeing people fix their issue is their Python version wasn't the right one so maybe try checking to see if you have at least version 3.8 or newer. Good luck!

**Comment by realrEDGUY** [comment]
> After trying to look that error up, the only way I'm seeing people fix their issue is their Python version wasn't the right one so maybe try checking to see if you have at least version 3.8 or newer. Good luck!

Yea I'm using the correct one, I even wrote `python3.8` in the start file to get it right.
```
root@user:/home/of_scraper/.settings# python3.8 --version
Python 3.8.5
root@user:/home/of_scraper/.settings# python3.6 --version
Python 3.6.9

```

 I saw someone with MacOS having the same issue but that didn't fix my issue

**Comment by DIGITALCRIMINAL** [comment]
If win32-setctime doesn't install, then the rest of the modules won't install when trying to install all.

**Comment by realrEDGUY** [comment]
> If win32-setctime doesn't install, then the rest of the modules won't install when trying to install all.

I know so I removed that one and installed the rest, but it won't work as it needs it

**Comment by artyom2035** [comment]
Try 'pip3 install -r requirements.txt'

I had this problem a while back.  I believe I solved it by installing the requirements using pip3.  On my system pip is linked to python2.7 which is the default version thats installed but pip3 is linked to python3.7 & 3.8.

**Comment by realrEDGUY** [comment]
> Try 'pip3 install -r requirements.txt'
> 
> I had this problem a while back. I believe I solved it by installing the requirements using pip3. On my system pip is linked to python2.7 which is the default version that's installed but pip3 is linked to python3.7 & 3.8.

yes that worked, thank you

now I'm just getting a different error so I'm on the right track :)

**Comment by DIGITALCRIMINAL** [comment]
@realrEDGUY you probably changed the folder structure, download it again

**Comment by realrEDGUY** [comment]
> @realrEDGUY you probably changed the folder structure, download it again

Redownloaded the files and tried `pip3 install -r requirements.txt` and they were working but im still unable to start it, here is what i get when running `python3 start_ofd.py`

```
/home/of_scraper/OnlyFans# python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/home/of_scraper/OnlyFans/tests/main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "/home/of_scraper/OnlyFans/helpers/main_helper.py", line 137
    writer.writerow({**{media_type: "valid"}, **item})
                      ^                                                 SyntaxError: invalid syntax
```

**Comment by DIGITALCRIMINAL** [comment]
@realrEDGUY use JSON instead of CSV

**Comment by artyom2035** [comment]
Okay, I already had bs4 installed for something else.  I'm not sure which of these got it working for me and I don't wanna break it in order to test it fixing it, lol.  Give these a try:

1.  Run 'apt list python-beautifulsoup python3-bs4'.  They both come back as installed for me, see below:
          Listing... Done
          python-beautifulsoup/stable,now 3.2.1-1 all [installed]
          python3-bs4/stable,now 4.7.1-1 all [installed]

2. If it doesn't say installed on your system run 'sudo apt-get install python-beautifulsoup python3-bs4'. 
          Try 'python3.8 start_ofd.py' again

3. If step 2 doesn't fix it, try running 'sudo python3 -m pip install bs4'. (This may be what you need)
          Try 'python3.8 start_ofd.py' again

Hope one of these helps.  Let us know how it goes....
