### ISSUE TITLE
New Cookie :  "auth_uniq_xxxx"

### ISSUE THREAD

**Issue by bollerdominik** [DIGITALCRIMINAL/OnlyFans#399]
OF seems to be changing their authentication. Since yesterday some accounts require a new cookie "auth_uniq_xxxx" (xxxx being your OF account id). Without this cookie value no API calls work and you get a HTTP 400 response.

I think they will soon roll this out for more accounts and this python script needs to be updated to support the value.

**Comment by DIGITALCRIMINAL** [comment]
Do you have 2FA on

**Comment by bollerdominik** [comment]
yes. after removing it it works

**Comment by DIGITALCRIMINAL** [comment]
The script has been handling the auth_unique cookie for a couple of months now. I'm not using 2FA, so I'll turn it on and debug it.

**Comment by DIGITALCRIMINAL** [comment]
If you turn on 2FA, it should work. There's even an option for you to fill in the auth_unique cookie on the config if you've got it.
