### ISSUE TITLE
not scraping all StarsAVN content

### ISSUE THREAD

**Issue by mhill1658** [DIGITALCRIMINAL/OnlyFans#401]
Hi, the profile (payveronica) has 573 images and 65 videos but only 4 videos and 63 images are being downloaded. No error messages or anything.

**Comment by DIGITALCRIMINAL** [comment]
I can't fix it because I'm not subscribed to any accounts on there

**Comment by DIGITALCRIMINAL** [comment]
Same thread

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/367
