### ISSUE TITLE
start_ofd.py opens and close without errors

### ISSUE THREAD

**Issue by ffedev** [DIGITALCRIMINAL/OnlyFans#402]
Hi, 

when double clicking start_ofd.py the window closes instantly, when I tried opening it in IDLE I get this error:

> Traceback (most recent call last):
>   File "C:\...\Onlyfans DW\start_ofd.py", line 9, in <module>
>     main_datascraper.start_datascraper()
>   File "C:\...\\Onlyfans DW\datascraper\main_datascraper.py", line 34, in start_datascraper
>     json_config, json_config2 = main_helper.get_config(config_path)
>   File "C:\...\Onlyfans DW\helpers\main_helper.py", line 301, in get_config
>     json_config2 = json.loads(json.dumps(make_config.start(
>   File "C:\...\Onlyfans DW\classes\make_config.py", line 226, in __init__
>     self.settings = Settings(**settings)
> TypeError: __init__() got an unexpected keyword argument 'global_user-agent'

The older version (last month) worked, but the loging didn't (Auth failed) so before updating the config file I updated with this latest version, and now it does not even launch.

I re-installed requirements and updated python from .3 to .5 

I'm probably missing something obvious here but I can't seem to find the problem

**Comment by DIGITALCRIMINAL** [comment]
Are you copy and pasting the config to the new version?

**Comment by ffedev** [comment]
> Are you copy and pasting the config to the new version?

FFFFF....

yeah, there was a typo, sorry.. it works now 💯
