### ISSUE TITLE
Not downloading all images and videos in OnlyFans

### ISSUE THREAD

**Issue by z-hyrule** [DIGITALCRIMINAL/OnlyFans#404]
The script doesn't download all the available content, for example @belledelphine suppose to have ~1400 photos and ~200 videos and just download ~400 and 69 videos.

The images and videos are the first she uploaded I don't know if it have something to do with that.

Is currently some kind of limitation on the amount of files to download or pages to run scrapper?

PD: Thanks for your amazing job.

**Comment by DIGITALCRIMINAL** [comment]
What is your file name format

**Comment by mnlg3456** [comment]
Having the same issue with the same creator. But i had previously scraped the account but now it will no longer add new pics/vids from what has updated since the scrape.
Have not changed any settings but cookie settings.

> "file_name_format": "{file_name}.{ext}"

**Comment by z-hyrule** [comment]
> What is your file name format

`"file_name_format": "{date}_{file_name}.{ext}"`

**Comment by DIGITALCRIMINAL** [comment]
@z-hyrule are you using any Chrome Extensions?

**Comment by DIGITALCRIMINAL** [comment]
> > What is your file name format
> 
> `"file_name_format": "{date}_{file_name}.{ext}"`

Are you using any proxies?

**Comment by z-hyrule** [comment]
> > > What is your file name format
> > 
> > 
> > `"file_name_format": "{date}_{file_name}.{ext}"`
> 
> Are you using any proxies?

Nope :(

**Comment by DIGITALCRIMINAL** [comment]
Eh try the latest commit, it should be better at getting posts now.

**Comment by z-hyrule** [comment]
I run it using the last commit. 
Now I get 522/1572 (~33%) pictures and 198/229 (~86%) videos.
It gets post's images since 16/06 until 06/07 and videos since 21/06 until 04/09.

**Comment by DIGITALCRIMINAL** [comment]
You're correct, for some reason, it's only getting the last 100 pages

**Comment by z-hyrule** [comment]
Is there a way for me to change something in the code to jump the first 100 pages and get the next ones? (or something like this to get the other content?)

**Comment by DIGITALCRIMINAL** [comment]
I know how to fix it, it's to do with certain timings. You can do this now by going to helpers/main_helper.py and search  json_requests and change the timeout=10 to timeout=20

**Comment by DIGITALCRIMINAL** [comment]
I pushed a new commit

**Comment by z-hyrule** [comment]
It's works perfectly thanks :)
