### ISSUE TITLE
'Messages' metadata not downloading 'text' field

### ISSUE THREAD

**Issue by clydachpugsley** [DIGITALCRIMINAL/OnlyFans#410]
Scraper is no longer grabbing the 'text' field in the 'Messages.json' metadata.
'Posts.json' is properly grabbing the 'text' field per the post.
Confirming on the website that the Messages do contain text.

**Comment by DIGITALCRIMINAL** [comment]
Thanks, fixed in the latest commit. They removed the RawText key I was using to get text.
