### ISSUE TITLE
auto_choice and auto_scrape_names causing issues

### ISSUE THREAD

**Issue by theravinglunatic** [DIGITALCRIMINAL/OnlyFans#413]
Whenever I have either auto_choice or auto_scrape_names enabled, nothing downloads but the profile and header.
I looked thru other issues, everything is default other than what needed to be filled out, not using proxies.
I am new to Python I pretty much only learned what was necessary to use this.
I also updated pip to the most recent version, and am using the most recent commit you uploaded about 40 minutes ago as of the time of posting.

**Comment by theravinglunatic** [comment]
Correction: I was using a VPN at the time

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit

**Comment by theravinglunatic** [comment]
> Use the latest commit

Issue still persists

**Comment by DIGITALCRIMINAL** [comment]
> > Use the latest commit
> 
> Issue still persists

Take a screenshot of the console that makes you think its broken....

**Comment by theravinglunatic** [comment]
> > > Use the latest commit
> > 
> > 
> > Issue still persists
> 
> Take a screenshot of the console that makes you think its broken....

Not at my pc right now but in the console it prints the metadata when downloading, when I use those two functions listed above, it doesn't print the metadata and doesn't download anything other than the profile and header.
If that info doesn't work I can get you a screenshot later.

**Comment by DIGITALCRIMINAL** [comment]
> > > > Use the latest commit
> > > 
> > > 
> > > Issue still persists
> > 
> > Take a screenshot of the console that makes you think its broken....
> 
> Not at my pc right now but in the console it prints the metadata when downloading, when I use those two functions listed above, it doesn't print the metadata and doesn't download anything other than the profile and header.
> If that info doesn't work I can get you a screenshot later.

You need to let the script complete it's whole job

**Comment by theravinglunatic** [comment]
> > > > > Use the latest commit
> > > > 
> > > > 
> > > > Issue still persists
> > > 
> > > 
> > > Take a screenshot of the console that makes you think its broken....
> > 
> > 
> > Not at my pc right now but in the console it prints the metadata when downloading, when I use those two functions listed above, it doesn't print the metadata and doesn't download anything other than the profile and header.
> > If that info doesn't work I can get you a screenshot later.
> 
> You need to let the script complete it's whole job

So does it create the folders first and then downloads?

**Comment by theravinglunatic** [comment]
It does create all of the folders first. Thanks, didn't know that.
