### ISSUE TITLE
Scraping but not downloading anything

### ISSUE THREAD

**Issue by dkwtfigo** [DIGITALCRIMINAL/OnlyFans#414]
I can auth just fine but the scraping doesn't download anything afterwards.
Script used to work without issues. Also takes quite long to finish scraping now, used to be faster.

It's just like:
>[...all the other download messages go here...]
Download Processing
Name: adestoex | Type: Archived | Directory: /Users/XY/Downloads/OnlyFans-5.3/.sites/OnlyFans
Downloading 1 Images
Task Completed in 6.033333333333333 Minutes
Pausing scraper for 0 seconds.

No Error message or anything.
Already checked other issue posts but wasn't able to find this one. Any idea what it could be?

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit and not 5.3

**Comment by taggedme** [comment]
I'm having a similar issue. Have tried using both v5.4 and the latest commit.

The difference with mine is that the script hangs and never gets to Task Completed.
