### ISSUE TITLE
Some odd error start geting on 5.3 and 5.4

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#418]
i have start get this error from 5.3 and 5.4
Python\Python38\lib\site-packages\bs4\__init__.py:385: UserWarning: "x'x'x'x'x'x'x'x'x'x'x'x'x'x'x'x'x'x'x'x'" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  warnings.warn(

**Comment by DIGITALCRIMINAL** [comment]
Ignore this.
