### ISSUE TITLE
"Missing 800 posts" displays over and over in 5.4 for one girl despite clearing all metadata

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#419]
I can provide her name if need be

![image](https://user-images.githubusercontent.com/20603861/93164438-74762700-f6e7-11ea-87c7-5ed736314631.png)

**Comment by DIGITALCRIMINAL** [comment]
Has nothing to do with the metadata. Are you using a proxy?

**Comment by bobsage123** [comment]
I'm not. It's possible this girl has taken down a large number of things though. Is there anyway for this message to only come up once?

**Comment by DIGITALCRIMINAL** [comment]
> I'm not. It's possible this girl has taken down a large number of things though. Is there anyway for this message to only come up once?

Go into onlyfans.py and change 100 to 50

![image](https://user-images.githubusercontent.com/21285176/93278647-31868300-f7bd-11ea-8d3b-4b6d0217cf06.png)

**Comment by bobsage123** [comment]
Updated that. Now it gets stuck on the message scraping part.

![image](https://user-images.githubusercontent.com/20603861/93280469-bb235a00-f797-11ea-9180-b845d38098af.png)

**Comment by bobsage123** [comment]
Okay so after updating pip and changing back to 100, looks to be working. Thanks.

**Comment by otisrush** [comment]
Same issue here, "Missing 100 posts" error in a loop. Pip updated, tried both with 100 and 50. Happens only for one model.
