### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by EvilKain** [DIGITALCRIMINAL/OnlyFans#42]
Hi now I got Phyton running but when I choose 0 for onlyfans it always says that the Access is denied. Checked Hash and all other parameters but its all right. Any Suggestions?
Thank you.

**Comment by DIGITALCRIMINAL** [comment]
Hmm, it only happens when your auth_id, auth_hash or your user-agent is incorrect

**Comment by DIGITALCRIMINAL** [comment]
Should look similar to this
```
"onlyfans": {
      "auth": {
        "app-token": "zCrrmx0nOcgormj7ZS7saz6q7iNvKs95",
        "auth_id": "696969",
        "auth_hash": "6677aca62435f836a861c15ccf65353c"
      }
    }
```

**Comment by EvilKain** [comment]
Hmm thats strange because it looks like your example. 
Could it be that this happens because of a other Python version. Iam using the newest.

**Comment by DIGITALCRIMINAL** [comment]
Try using it with Python 3.7

**Comment by EvilKain** [comment]
Iam using 3.7.4

**Comment by DIGITALCRIMINAL** [comment]
Message me the config at
datahoarders@protonmail.com
It's so I can verify it's the right format

**Comment by DIGITALCRIMINAL** [comment]
On my side, it's telling me you have the wrong application token

**Comment by dilemmax** [comment]
I had the same issue. The new version has moved to the user agent further up in the config.json so you need to populate the information to remove the access denied error.

**Comment by EvilKain** [comment]
Thanks dilemmax for your answer maybe you can tell me where I have to set the user agent. I tried it but now I get syntax errors and many more.

**Comment by DIGITALCRIMINAL** [comment]
The format you sent me was correct. Try logging out and logging back in and updating the information again.

**Comment by dilemmax** [comment]
I used this website to find my user agent. Just copy what's inside the blue box.

https://www.whatismybrowser.com/detect/what-is-my-user-agent

**Comment by EvilKain** [comment]
Okay somehow it works now. How I have to give in the profile name that I want to download from?

**Comment by EvilKain** [comment]
Everytime I gave in a name then it says Route not found.
Thanks for your help.

**Comment by DIGITALCRIMINAL** [comment]
Go here and choose a username from this list
https://onlyfans.com/my/subscribes/active

**Comment by EvilKain** [comment]
Okay but when I give in the username it says no route found

**Comment by EvilKain** [comment]
Do I have to put this in the json.config too?

**Comment by DIGITALCRIMINAL** [comment]
what exact username are you inputting

**Comment by EvilKain** [comment]
![A](https://user-images.githubusercontent.com/56481785/66712986-13422700-eda5-11e9-8288-5971110eff13.png)

**Comment by EvilKain** [comment]
This is what I tried so far.

**Comment by DIGITALCRIMINAL** [comment]
sophiedeelive
That's the username

**Comment by DIGITALCRIMINAL** [comment]
I accidentally closed this. I reopened it.

**Comment by EvilKain** [comment]
Okay thanks now it works.
