### ISSUE TITLE
program sometimes only downloads about half the videos

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINAL/OnlyFans#420]
[observe](https://i.imgur.com/LGye2Gn.png)

this user has 520 videos https://onlyfans.com/iamjasonluv/videos

the issue is intermittent with some accounts working fine

**Comment by DIGITALCRIMINAL** [comment]
Try scraping all

**Comment by DIGITALCRIMINAL** [comment]
Also, what is the filename format

**Comment by alectprasad** [comment]
nvm the issue is if filename format is only text, it doesn't download anything that doesn't have a text
