### ISSUE TITLE
How to upgrade the script ?

### ISSUE THREAD

**Issue by UncleVladd** [DIGITALCRIMINAL/OnlyFans#421]
Not really sure how to use github.
Downloaded the latest tarball 
Running Ubuntu 20.x LTS

What's the proper way to keep it updated ?

PS... amazing work btw.

**Comment by DIGITALCRIMINAL** [comment]
Download from the master

**Comment by UncleVladd** [comment]
is this something I should do with a github client ? or do I just re-download over the old files and then just replace the config.jason ?

**Comment by DIGITALCRIMINAL** [comment]
Yes, just overwrite everything
