### ISSUE TITLE
Scrape expired subscription messages

### ISSUE THREAD

**Issue by RickyBubbles** [DIGITALCRIMINAL/OnlyFans#423]
Is it possible to scrape messages from subscriptions that are no longer active?
Is it also possible to scrape the “Purchased” tab (if there’s purchased content from an account that no longer has an active subscription, those purchases won’t get scraped)?

**Comment by DIGITALCRIMINAL** [comment]
You cannot access messages without subscribing to them.
You cannot scrape past purchases with this script yet
