### ISSUE TITLE
Cookie change?

### ISSUE THREAD

**Issue by melwim** [DIGITALCRIMINAL/OnlyFans#425]
Auth_Hash is missing from the cookie and has been replaced with sc_is_visitor_unique? sess & auth_id are still there.

**Comment by DIGITALCRIMINAL** [comment]
No.

**Comment by melwim** [comment]
I may have elaborated more.

![image](https://user-images.githubusercontent.com/71847805/94237395-17604980-ff0f-11ea-9b66-d2787550dc4a.png)

Tried Chrome, Edge, Twitter login and user/pass login. As per very recently auth_hash is not in cookie anymore.
