### ISSUE TITLE
Auth failed

### ISSUE THREAD

**Issue by kotori2** [DIGITALCRIMINAL/OnlyFans#427]
Seems like they added a header `auth_uid_{uid}`, with values follows pattern `[A-Za-z0-9]`. 
Without this cookie I will get HTTP 400 and a OTP request, but by manually hardcoded this cookie [here](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/302d87f1d8af6719140c87603943caa8ce2656cf/modules/onlyfans.py#L736) it works fine. 
Might related to 2FA.

**Comment by DIGITALCRIMINAL** [comment]
Are you sure? Because on my end it does absolutely nothing. The only thing I had to do was update my user-agent, that's all.

**Comment by kotori2** [comment]
Yes i am sure. Also when it promotes for 2FA code, even if I entered the correct code, it won't work.

**Comment by DIGITALCRIMINAL** [comment]
What 2FA do you use? Authenticator?

**Comment by kotori2** [comment]
yes.

CRIMINAL <notifications@github.com> 于 2020年9月26日周六 05:35写道：

**Comment by DIGITALCRIMINAL** [comment]
Okay, I made a commit.
