### ISSUE TITLE
Issues with renaming

### ISSUE THREAD

**Issue by mattlines** [DIGITALCRIMINAL/OnlyFans#428]
In the read me, you mention using {text} could cause issues, but I've been in contact with several people who don't experience any while using it. My issue is that when I use {text}, it excludes many images from the scraping results. When I set it back to default, it grabs everything. Could it be because of special characters in the posts of the images? I'm basically just trying to rename each file to the proper name. Any assistance would be greatly appreciated!

**Comment by DIGITALCRIMINAL** [comment]
What is your filename format

**Comment by mattlines** [comment]
`"{date} - {text}#{file_name}.{ext}"`

I'm noticing errors. For example:

`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*****\\Downloads\\OnlyFans-master\\OnlyFans-master\\.sites\\OnlyFans\\sharkbittens\\Posts\\Free\\Images\\01-03-2020 - a series lemme know what u think oiling up vid coming next love this white bra#3840x3840_04dc681fdba44e2f9ee94037161502222382505e0e8a84cd234.jpg'`

I get this with any format if I include `"{text}"`

**Comment by mattlines** [comment]
Just tested something else. It could be because the text used in the posts are too long. If I set text_length higher than 100, it won't download certain posts that exceed that limit.

**Comment by DIGITALCRIMINAL** [comment]
You can try with the latest commit

**Comment by mattlines** [comment]
Still not working. I have to keep shortening the text length to get all of the images.
