### ISSUE TITLE
auth_hash

### ISSUE THREAD

**Issue by Kev2FreshYo** [DIGITALCRIMINAL/OnlyFans#429]
unable to locate the auth_hash anywhere??

**Comment by DIGITALCRIMINAL** [comment]
then don't add it in??????????????????????????????????????????????????????????????????????????????????????????????????????????
read the readme jfc.

**Comment by Kev2FreshYo** [comment]
@DIGITALCRIMINAL i had readd the readme, i overlooked that section, until right after i wrote issue. my apologies????????????????????????????????????????????????????????????? jfc
