### ISSUE TITLE
New space check causing issues on Linux

### ISSUE THREAD

**Issue by chibbardpm** [DIGITALCRIMINAL/OnlyFans#431]
Hello,
While trying to solve another issue I came across this new one. It seems some sort of disk-space check has been included, and I think it's causing an issue on linux.
 `/OnlyFans-master/helpers/main_helper.py", line 244, in check_space
    obj_Disk = psutil.disk_usage(drive)
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2015, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/lib/python3.8/site-packages/psutil/_psposix.py", line 169, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: ''
`

**Comment by DIGITALCRIMINAL** [comment]
yee it is, gonna push a commit rn

**Comment by DIGITALCRIMINAL** [comment]
it's been pushed

#430 430
