### ISSUE TITLE
can't find .settings/config/json

### ISSUE THREAD

**Issue by alb-ctrl** [DIGITALCRIMINAL/OnlyFans#432]
after downloading the zip file 
there's not dir .settings nor a config.json file

**Comment by DIGITALCRIMINAL** [comment]
Read the readme

**Comment by alb-ctrl** [comment]
I have. and I even watched the YouTube video 
also im getting this error 
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/Users/andresarauz/Documents/P2/OnlyFans-master/tests/main_test.py", line 55
    f"The .settings\\{file_name} file has been updated. Fill in whatever you need to fill in and then press enter when done.\n")
                                                                                                                              ^
SyntaxError: invalid syntax
I presume is because I don't have a .settings/config/json

**Comment by DIGITALCRIMINAL** [comment]
... so you've read the FAQ then

**Comment by alb-ctrl** [comment]
yes

**Comment by DIGITALCRIMINAL** [comment]
Are you using Windows

**Comment by alb-ctrl** [comment]
Mac
but I fixed it 
I was missing some libraries 
thank you btw
