### ISSUE TITLE
Closing instantly after running start_ofd and not creating .settings folder

### ISSUE THREAD

**Issue by RinuxLee** [DIGITALCRIMINAL/OnlyFans#433]
Python Version is 3.8.2

OS: Windows 10

Never had an issue with the tool, however downloaded new version today and as soon as I click on "start_ofd" the terminal pops up and instantly closes. Nothing is created within the folder structure. Normally .settings is created but this time it instantly closes and does nothing.

Am I doing something wrong?

**Comment by DIGITALCRIMINAL** [comment]
Run the requirements again

**Comment by RinuxLee** [comment]
All requirements are met and have been double checked. Still got the issue.

**Comment by RinuxLee** [comment]
Update:

Fixed my issue. Apparently kaspersky kept interfering for some reason. Works fine now.
