### ISSUE TITLE
content-length error on one particular user

### ISSUE THREAD

**Issue by ProjektPremium** [DIGITALCRIMINAL/OnlyFans#434]
Just got hit with this multiple times on the one user, not sure how to get around this.

2020-10-02 20:28:51,014 ERROR errors 'content-length'
Traceback (most recent call last):
  File "\datascraper\main_datascraper.py", line 248, in start_datascraper
    x.download_media(*arg)
  File "\modules\onlyfans.py", line 684, in download_media
    pool.starmap(download, product(
  File "C:\Python\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Python\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "\modules\onlyfans.py", line 626, in download
    result = choose_link(session, links)
  File "\modules\onlyfans.py", line 622, in choose_link
    content_length = int(header["content-length"])
  File "C:\Python\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

**Comment by DIGITALCRIMINAL** [comment]
What's the account?

**Comment by ProjektPremium** [comment]
adulteressamber

**Comment by thatoneguy206** [comment]
seeing the same thing with kwgirlx

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by ProjektPremium** [comment]
Just tried the latest commit and got this.

Scrape Processing
Name: adulteressamber
Type: Profile
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
No Highlights Found.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
Found: Posts
C:\Python\lib\site-packages\bs4\__init__.py:332: MarkupResemblesLocatorWarning: "." looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
FOUND: \.sites\OnlyFans\adulteressamber\Posts\Free\Videos

FOUND: \.sites\OnlyFans\adulteressamber\Posts\Free\Videos

FOUND: \.sites\OnlyFans\adulteressamber\Posts\Free\Videos

FOUND: \.sites\OnlyFans\adulteressamber\Posts\Free\Videos

FOUND: \.sites\OnlyFans\adulteressamber\Posts\Free\Videos

Type: Archived
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scrape Attempt: 1/100
No Archived Found.
FOUND: \.sites\OnlyFans\adulteressamber\Archived\Free\Videos
FOUND: \.sites\OnlyFans\adulteressamber\Archived\Free\Videos

FOUND: D:\DigitalCriminal\.sites\OnlyFans\adulteressamber\Archived\Free\Videos
FOUND: D:\DigitalCriminal\.sites\OnlyFans\adulteressamber\Archived\Free\Videos



Type: Messages
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scrape Attempt: 1/100
No Messages Found.
Scrape Completed

2020-10-03 11:51:20,257 ERROR errors 'start' object is not subscriptable
Traceback (most recent call last):
  File "\datascraper\main_datascraper.py", line 247, in start_datascraper
    if not result["subbed"]:
TypeError: 'start' object is not subscriptable

**Comment by thatoneguy206** [comment]
Works fine for me now!  Thanks.
