### ISSUE TITLE
#Question - Redownload content with new file naming format and delete old file

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#440]
So, I have a bunch of content in the type named in the format `[{date}] ({file_name}).{ext}` Example:  `[2017-03-16] (33394635--upload-215753-AF888A4C-4C2F-4373-A127-7D30C49FD84B).jpg`

I'd like to redownload some of these girls but use the description they give in the file name (or however much fits) so that I am able to search through the content more easily. Also, if possible, when re-downloading in the new naming format, if it could delete the old naming format version. I know using the description was iffy a while back but I'm not sure if that has been resolved.

Is this possible in this current version?

Thanks

**Comment by DIGITALCRIMINAL** [comment]
Ye it should delete the old format automatically

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bobsage123** [comment]
I know there were issues with using the description in filename in the past. Ie. if there is a set with 5 pictures and they all have the same description, then it would only download the first of the set. Has this been resolved?

And just want to confirm this looks good for the new format.
`[{date}] ({text}).{ext}`

Thanks

**Comment by DIGITALCRIMINAL** [comment]
As long as you have a unique identifier like media id, you'll be fine.

**Comment by bobsage123** [comment]
Hmm, only unique id I know of is the file name which is sometimes long and won't leave much room for the description. Is there any shorter ones you know that can be used?

**Comment by bobsage123** [comment]
So I ended up using this and limiting text to 200 so that the unique identifier of the file name had room `{date}-{text}-{file_name}.{ext}` But it did not rename files I had already downloaded into the new format. It re-downloaded everything in the new format and left the old format files. Maybe I have a setting off and that is why it's not overwriting old files correctly?
