### ISSUE TITLE
Adjust-able thread count

### ISSUE THREAD

**Issue by kotori2** [DIGITALCRIMINAL/OnlyFans#441]
It seems the default settings (`multiprocessing.cpu_count()`) is too high if you owns a high-end CPU but not top level network.
Imagine downloading videos with 16 threads. It is likely causing corrupted videos which was caused by connection closed.

**Comment by DIGITALCRIMINAL** [comment]
I download content with 32 threads over a proxy that keeps on disconnecting.

The script automatically redownloads content if the connection drops

**Comment by kotori2** [comment]
also it seems it won't check status code. 
sometimes it will download tons of invalid videos if the URL expires
```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access denied</Message></Error>
```

**Comment by DIGITALCRIMINAL** [comment]
It does check status code.

**Comment by kotori2** [comment]
then how can I get tons of files with `AccessDenied`? it seems like error from Amazon S3

**Comment by kotori2** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/blob/46ff045007ef16a032ebb6a3fef74c41c8e7a975/helpers/main_helper.py#L342-L387
> It does check status code.

seems no

**Comment by DIGITALCRIMINAL** [comment]
You cannot use the links on a different IP address

**Comment by kotori2** [comment]
Yea it make sense. Anyway I think there is room for enhancement, like checking `r.status_code == 200`

**Comment by DIGITALCRIMINAL** [comment]
Yeah, you're right, I'll add it, thanks.

**Comment by DIGITALCRIMINAL** [comment]
Added it to the latest commit, I will also allow users to add a thread limit in the settings later on.

**Comment by kotori2** [comment]
~~Wow that was super fast~~

**Comment by DIGITALCRIMINAL** [comment]
It's in the latest commit
