### ISSUE TITLE
Recurring crash while scraping

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#442]
![crash](https://user-images.githubusercontent.com/58760178/95656037-7f02c100-0ad9-11eb-9409-5ad67ddd37b9.png)

Hi I've been having this same error appear sporadically but now it's systematic if I try to scrape all the accounts I'm subbed to (~120 accounts total) I don't have that error when scraping a single account and I don't think it's always the same account where it crashes.

I tried looking into it but my level in Python is "I wish I could do something with that" and my internet searches haven't helped much.

**Comment by jp1151419** [comment]
![newcrash](https://user-images.githubusercontent.com/58760178/95656921-65fd0e80-0adf-11eb-8954-08ed2702edf5.png)
I realized after my previous post that I didn't have the most up-to-date version. Now I do but I still have the same issue

**Comment by DIGITALCRIMINAL** [comment]
Use JSON instead of CSV

**Comment by jp1151419** [comment]
> 
> 
> Use JSON instead of CSV

That seems to have fixed it thanks! Would you mind giving a quick explanation as why exporting to CSV caused an error?

**Comment by jp1151419** [comment]
![json crash](https://user-images.githubusercontent.com/58760178/95661425-4d9bec80-0afd-11eb-927b-3e79a11e89ff.png)
Spoke too soon. I just had this error pop up

**Comment by jp1151419** [comment]
![json crash](https://user-images.githubusercontent.com/58760178/95661450-7328f600-0afd-11eb-9e2a-bcafddfa7bab.png)
I spoke too soon, I just had this error pop up while it was downloading videos.

**Comment by AlexDucks** [comment]
Landed here after getting the same issue as the one @jp1151419 just posted with `model_directory = os.path.join()...`

From what I can tell it only happens when I try to scrape all creators. For me it seems that scraping individual creators work fine and that error does not occur.  
With that said, I haven't tried scraping every creator individually to see if the error occurs with one specific one, due to having 60 to go through...

**Comment by jp1151419** [comment]
I'm having that issue on the current master, as downloaded 4 hours ago.

**Comment by AlexDucks** [comment]
Okay, I think I actually found my issue pretty quickly after posting my comment, but it took a while to go through all the creators and verify.

First of all, the latest commit (https://github.com/DIGITALCRIMINAL/OnlyFans/commit/1aab6e49c528918cb218da2ae41f649ea21b0c45) is broken. I keep getting `Missing 100 posts... Retrying...` for creators that worked previously. Reverting to the previous commit that I was using earlier (https://github.com/DIGITALCRIMINAL/OnlyFans/commit/321c33e0fc8bb91c54a6c366465031831c4eee60) works fine without that issue.

The original issue with the `model_directory = os.path.join()` error occurred to me with one specific creator after some testing: https://onlyfans.com/lizzielouise  
It may be because that creator hasn't posted anything yet and thus has 0 posts/archived/messages etc, but I'm not sure.  
Adding that creator to the "blacklist" for the scraper seemed to temporarily fix that issue at least.

**Comment by DIGITALCRIMINAL** [comment]
Thanks, should be working in the latest commit now

**Comment by jp1151419** [comment]
> 
> 
> Thanks, should be working in the latest commit now

I started a new run with 0=all, I'll let you know the result when it's done.

**Comment by jp1151419** [comment]
![Screenshot 2020-10-10 164931](https://user-images.githubusercontent.com/58760178/95664750-b5136580-0b18-11eb-9c02-8c81117f66ca.jpg)
It crashed the same way as my last run with the previous commit. Interestingly enough on the same creator  onlyfans.com/eva69mtl69

**Comment by DIGITALCRIMINAL** [comment]
@jp1151419 I can't reproduce the error yet, I would need to know what the variable "others" is printing

**Comment by jp1151419** [comment]
> need to know what the variable "others" is printing

@DIGITALCRIMINAL how do I check that for you?

**Comment by DIGITALCRIMINAL** [comment]
> > need to know what the variable "others" is printing
> 
> @DIGITALCRIMINAL how do I check that for you?

Add 
`
                try:
                    model_directory = os.path.join(others[0][2], others[0][3])
                except Exception as e:
                    print(e)
                    input(others)`

beneath line 250

**Comment by jp1151419** [comment]
So my file looked like this before:
![image](https://user-images.githubusercontent.com/58760178/95698135-01d96800-0c0f-11eb-9c1d-244f87dff362.png)

I edit it to replace the `model_directory = os.path.join(others[0][2], others[0][3])` line with what you provided and now start_ofd.py doesn't run at all, the window closes within a second of starting it.

**Comment by DIGITALCRIMINAL** [comment]
What does it look like now?

**Comment by jp1151419** [comment]
My bad, didn't know indentation was critical. Here it is after fixing it:
![image](https://user-images.githubusercontent.com/58760178/95701445-9c3da980-0c17-11eb-9f45-628fb42bbd46.png)

**Comment by galaxianloop** [comment]
i'm getting the same error and pasted in the code you posted above. here's what it looks like:
![image](https://user-images.githubusercontent.com/59378670/95724952-dca72280-0c2b-11eb-8668-db5c8f9cbc61.png)
i have the script running on an infinite loop scraping every name and this error always comes up when scraping this one specific account.

**Comment by DIGITALCRIMINAL** [comment]
> i'm getting the same error and pasted in the code you posted above. here's what it looks like:
> ![image](https://user-images.githubusercontent.com/59378670/95724952-dca72280-0c2b-11eb-8668-db5c8f9cbc61.png)
> i have the script running on an infinite loop scraping every name and this error always comes up when scraping this one specific account.

Thank you. I had to make sure the variable was returning empty.

I've pushed a commit that will solve this.

**Comment by CF-Gauss** [comment]
```
Type: Posts
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Found: Posts
2020-10-12 15:15:22,459 ERROR errors [Errno 2] No such file or directory: '/mnt/data/OnlyFans/mntdataOnlyFans.sitesOnlyFansthenaomi99PostsFreeImages/2232x3968_b5615a220f81d38c195a0e09d9c06527.jpg'
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 780, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/OnlyFans/.sites/OnlyFans/thenaomi99/Posts/Free/Images/2232x3968_b5615a220f81d38c195a0e09d9c06527.jpg' -> '/mnt/data/OnlyFans/mntdataOnlyFans.sitesOnlyFansthenaomi99PostsFreeImages/2232x3968_b5615a220f81d38c195a0e09d9c06527.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/OnlyFans/datascraper/main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "/mnt/data/OnlyFans/modules/onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "/mnt/data/OnlyFans/modules/onlyfans.py", line 478, in prepare_scraper
    main_helper.export_archive(
  File "/mnt/data/OnlyFans/helpers/main_helper.py", line 165, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "/mnt/data/OnlyFans/extras/OFRenamer/start.py", line 136, in start
    metadata.valid = fix_metadata(
  File "/mnt/data/OnlyFans/extras/OFRenamer/start.py", line 116, in fix_metadata
    old_folders = pool.starmap(start, product(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/mnt/data/OnlyFans/extras/OFRenamer/start.py", line 87, in start
    filepath, old_filepath = update(filepath)
  File "/mnt/data/OnlyFans/extras/OFRenamer/start.py", line 84, in update
    shutil.move(filepath, new_format)
  File "/usr/lib/python3.8/shutil.py", line 794, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/OnlyFans/mntdataOnlyFans.sitesOnlyFansthenaomi99PostsFreeImages/2232x3968_b5615a220f81d38c195a0e09d9c06527.jpg
```

There's still an error in the way the path is constructed

**Comment by jp1151419** [comment]
I tried a full run with the latest commit, fac67e2, and got this error:
![json crash](https://user-images.githubusercontent.com/58760178/95788145-f0449e80-0ca8-11eb-9c27-cb95c40d79d2.png)

**Comment by DIGITALCRIMINAL** [comment]
Open new issue and tell me your file name format in said issue

**Comment by DIGITALCRIMINAL** [comment]
> I tried a full run with the latest commit, fac67e2, and got this error:
> ![json crash](https://user-images.githubusercontent.com/58760178/95788145-f0449e80-0ca8-11eb-9c27-cb95c40d79d2.png)
> 

I'd need to know what the y variable is printing

**Comment by jp1151419** [comment]
> I'd need to know what the y variable is printing

Mind helping me out with the formatting again?

**Comment by DIGITALCRIMINAL** [comment]
try:
        model_link = f"https://onlyfans.com/{y['username']}"
    except Exception as e:
        print(e)
        input(y)

![image](https://user-images.githubusercontent.com/21285176/95791331-1124e800-0cd9-11eb-8aa6-92f8b27b8a20.png)

**Comment by jp1151419** [comment]
I did a clean install of  fac67e2 yesterday and it ran all night without an issue so I can't answer that last question of yours. I'll close this thread since that commit seems to work after all. Thanks for your time.
