### ISSUE TITLE
Linked to #273 Not able to access to premium content

### ISSUE THREAD

**Issue by bungle90** [DIGITALCRIMINAL/OnlyFans#443]
Hi, 

Probably missing something here...
Getting authed in ok, but cant download premium content. 
User is em1794

Cheers

**Comment by DIGITALCRIMINAL** [comment]
Have you paid for the content?

**Comment by bungle90** [comment]
No I haven't, I'm assuming posts behind a paywall aren't available?

**Comment by hawktank** [comment]
@bungle90 Toss them some cheddar, might be able to ask em nicely for a discount.
