### ISSUE TITLE
its not starting. no config file generated

### ISSUE THREAD

**Issue by stuffnstuffx** [DIGITALCRIMINAL/OnlyFans#444]
[perses ~/OnlyFans-master] python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/media/dmad/usr/OnlyFans-master/tests/main_test.py", line 55
    f"The .settings\\{file_name} file has been updated. Fill in whatever you need to fill in and then press enter when done.\n")
                                                                                                                              ^
SyntaxError: invalid syntax

i had a previous config file and filled it up but still get this issue

**Comment by DIGITALCRIMINAL** [comment]
You're not using Python 3.8

**Comment by stuffnstuffx** [comment]
yeah seems to be the case, somehow my python had reverted back to 2.7 but thanks anyway

**Comment by DIGITALCRIMINAL** [comment]
On Linux, you gotta use `python 3.8 start_of.py` or something like that
