### ISSUE TITLE
extra_auth no longer working

### ISSUE THREAD

**Issue by AlexDucks** [DIGITALCRIMINAL/OnlyFans#445]
Latest commit from master: https://github.com/DIGITALCRIMINAL/OnlyFans/commit/32aeb869a94c516ac1dfe93903adef6a934a772d

Getting the following error when trying to utilize `extra_auth`:
```
2020-10-11 22:40:15,914 ERROR errors 'onlyfans'
Traceback (most recent call last):
  File "E:\OnlyFans\datascraper\main_datascraper.py", line 88, in start_datascraper
    json_auth_array += extra_auth_config[site_name_lower]["extra_auth"]
KeyError: 'onlyfans'
```

It seems to be trying to use the old file layout, even though the software is automatically converting it to a new file format.

**Comment by DIGITALCRIMINAL** [comment]
Fixed, thanks
