### ISSUE TITLE
Win32-setctime & Syntax Error MacOS

### ISSUE THREAD

**Issue by notimotion** [DIGITALCRIMINAL/OnlyFans#446]
When installing the requirements I've got an error not allowing me to install win32-setctime so I skipped it and when I ran

`python start_odf.py`

I got the following:
`Traceback (most recent call last):
  File "/OnlyFans-5.4/start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/OnlyFans-5.4/tests/main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "/OnlyFans-5.4/helpers/main_helper.py", line 153
    writer.writerow({**{media_type: "valid"}, **item})
                      ^
SyntaxError: invalid syntax`

not creating the config.json file.

**Comment by DIGITALCRIMINAL** [comment]
install 5.5 and don't use csv
