### ISSUE TITLE
Option to remember saved files

### ISSUE THREAD

**Issue by supra89t** [DIGITALCRIMINAL/OnlyFans#448]
Not really an "issue" but perhaps worth adding in.

I was wondering if there is an option to have the app recall its downloaded files. The reason why I ask this is because I keep the files stored on an unraid server, and I have a small headless VM running this script. I set it to auto scan every hour, and this keeps spinning up my HDD's (sleep timer is 30 mins)

I also use youtube-dl to fetch movies/video files and they have the option to export all downloaded files into a txt document. When the app is triggered it will check for new media and reference the txt file for duplicates, that keeps my disks offline and only spins them up once new data is added.

What do you think the possibilities are for an option like this to be added? I'm free for testing as I don't know how many people have a setup like mine.

Thanks

**Comment by OnlyAFan2** [comment]
This would be a pretty great addition. The metadata is already exported with the last run through for a model so I'd imagine it wouldn't be too difficult to only scrape between the current time and the last added file. 

Some models like rileyreidx3 have tons of media and scraping all of their posts slows things down a ton

**Comment by DIGITALCRIMINAL** [comment]
With the way the script is built and how it handles the metadata and files, it's not possible at this time. I will keep it in mind though.

**Comment by DIGITALCRIMINAL** [comment]
This has been implemented but your disk will still spin up.
