### ISSUE TITLE
auth_uniq_ not in cookies despite using 2FA

### ISSUE THREAD

**Issue by xathian** [DIGITALCRIMINAL/OnlyFans#449]
As it says, there is no auth_uniq_ cookie present anywhere even though I do have 2FA enabled. There is a cookie called auth_uid_(userID), however if its value is added to the config in the auth_uniq_ section it rejects all 2FA codes so I assume that's not the right cookie under a different name.

**Comment by DIGITALCRIMINAL** [comment]
Are you able to use the script

**Comment by xathian** [comment]
Yes, I just edited the above post. The script starts up, asks for the site, etc then starts failing auth due to no 2FA code

**Comment by DIGITALCRIMINAL** [comment]
Try logging into an out of OnlyFans and see if it will appear. I can't do anything since I don't have access to your account.

**Comment by xathian** [comment]
Still nothing, also tried an a different browser, Firefox instead of Chrome and nothing there either.

**Comment by DIGITALCRIMINAL** [comment]
After you enter the code, I would need to know what r prints out
![image](https://user-images.githubusercontent.com/21285176/96086855-d5497880-0eba-11eb-9372-0a2dbf859098.png)

**Comment by xathian** [comment]
I have no idea where that is or how to see what it puts out, but I can tell you if I find out

**Comment by DIGITALCRIMINAL** [comment]
open onlyfans.py and go to line 806 and under it put 

input(r)

![image](https://user-images.githubusercontent.com/21285176/96087844-6e2cc380-0ebc-11eb-9672-2a3105606b43.png)

**Comment by xathian** [comment]
{'error': {'code': 101, 'message': 'u-------', 'payload': {'otpState': {'email': False, 'phone': False, 'phoneOtp': False, 'app': True, 'appOtp': True}}}}

Blocked out userID in case it's unsafe to show

**Comment by oOD4rkL0rdOo** [comment]
I try the last release yesterday and get the same error.
To fixed, i change the value none in line 747 in ./modules/onlyfans.py to my 'auth_uid'.

**Comment by DIGITALCRIMINAL** [comment]
@oOD4rkL0rdOo even if you had 2FA on?

**Comment by oOD4rkL0rdOo** [comment]
yes, i use 2FA

**Comment by DIGITALCRIMINAL** [comment]
@xathian you should try their solution
