### ISSUE TITLE
Dates don't work an MacOS

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINAL/OnlyFans#45]
win32-setctime doesn't run on MacOS so you have to remove it from the script, and you just end up with randomly named videos.

**Comment by bpo5r5** [comment]
Same issue #28 
Are you using the latest version?

**Comment by mep85** [comment]
Yes.

It still tries to import from win32_setctime at line 3, and the module just doesn't install on MacOS, so it throws errors at that point (the import).  The rest runs fine.

And sorry about the typo in the title.

**Comment by jeff-geoff** [comment]
Yes.

It tries to import from win32_setctime at line 3, and that module just won't install on MacOS, so it will always throw an error at line 3 if it doesn't check OS first.

When I remove that line, it runs okay.

And sorry about the typo in the title.

**Comment by DIGITALCRIMINAL** [comment]
Pushing a commit in a few hours that will fix this

**Comment by DIGITALCRIMINAL** [comment]
Fixed, pushed a commit.
