### ISSUE TITLE
Add option to put in folder or not based on image/video count.

### ISSUE THREAD

**Issue by herefromrdt** [DIGITALCRIMINAL/OnlyFans#452]
As I get more more posts/messages that contain a lot of images or videos, I've found I want to start putting those posts/messages in their own folder to keep things a bit tidier. However, that also means the more common posts that are just one or two images get put in individual folders as well, which then makes those harder to navigate.

It would be nice if I could set a threshold where if the post or message contains X or more images/videos, then that post/message will be put in its own folder, but if there are less than that, the images/videos would go in the main folder.

For example, if I set my threshold to 5, downloading a post that has 4 images, it would do the following 

* .sites/
  * example-user/
    * Posts/
      * Images/
        * image1.jpg
        * image2.jpg
        * image3.jpg
        * image4.jpg

but if there's a post with 5 or more images in it, then they would be grouped together in the folder (named with the format specified in the config)
* .sites/
  * example-user/
    * Posts/
      * Images/
        * <_file_directory_format_>/
          * image1.jpg
          * image2.jpg
          * image3.jpg
          * image4.jpg
          * image5.jpg

**Comment by DIGITALCRIMINAL** [comment]
Dunno if I will add something like this but I will keep it in mind.
