### ISSUE TITLE
I/O Error: encoder error

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#455]
encoding error : input conversion failed due to input error. bytes 0x99 0x73 0x20 0x67

happens for all media resulting in no media files being saved

**Comment by DIGITALCRIMINAL** [comment]
I dunno what this is or where the error occurs.

**Comment by James-MF-Thomas** [comment]
This has happened with every model with the exception of 1 out of 100:
![Screen Shot 2020-10-18 at 8 08 19 PM](https://user-images.githubusercontent.com/47627618/96391253-b62e3d80-117d-11eb-994c-06f4c6bd19f1.png)


![Screen Shot 2020-10-18 at 8 05 41 PM](https://user-images.githubusercontent.com/47627618/96391157-723b3880-117d-11eb-89f0-eee3d31d8676.png)

**Comment by James-MF-Thomas** [comment]
the links to all the media are avail in the metadata which can be copy/pasted into jdownloader... but a little too tedious

**Comment by DIGITALCRIMINAL** [comment]
What's your file name format

**Comment by James-MF-Thomas** [comment]
happened with default naming initially, now its' {username}-{media_id}.ext

**Comment by James-MF-Thomas** [comment]
![Screen Shot 2020-10-18 at 8 12 22 PM](https://user-images.githubusercontent.com/47627618/96391453-4f5d5400-117e-11eb-852f-88c6f2b7ce34.png)

**Comment by James-MF-Thomas** [comment]
another forum had the error referenced to beautifulsoup4... i tried tracing it but i got lost

**Comment by DIGITALCRIMINAL** [comment]
It's most likely because I switched from lxml to html

**Comment by DIGITALCRIMINAL** [comment]
Finally LXML works for Python 3.9 so I'm adding it back in.

**Comment by James-MF-Thomas** [comment]
👍🏼 thank you sir.  (I was able get the script to work(download), just had to let it run a second loop, took a while)

**Comment by adamwinn** [comment]
I saw this when I used `"filename_format": "{date}-{media_id}-{text}.{ext}",` and the text had an emoji in it
