### ISSUE TITLE
Onlyfans scrapper enhancement

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#460]
I usually purchase more than one subscription at a time and was wondering if there was an option to stay in the particular scrapper (OF for this example) instead of having to select which scrapper to use once you are done scrapping a subscription?

Also, is it possible to show the expiry date for each subscription when pulling up the menu for scrapping? I usually scrap a subscription on the first and last day of a subscription and I don't always get the email notification from OF to say the subscription is expiring the next day.

**Comment by gitporn873** [comment]
Do you only scrape OF? If so you can edit `.settings/config.json` to automatically use OF as a scrape target and then you can pick which model to scrape

**Comment by DIGITALCRIMINAL** [comment]
Read the readme...
