### ISSUE TITLE
Renaming Files Question

### ISSUE THREAD

**Issue by gitporn873** [DIGITALCRIMINAL/OnlyFans#463]
Readme didn't really cover this and figured best way to find out before redownloading a whole model is to ask.

So I wanna change the date format cause I'm an american and use the wrong format :P 

I could easily do a bulk rename on my end and update the config.json file but I'm wondering how that works with the Metadata currently stored. I have overwrite turned off and I'm wondering if content I've already archived would attempt to be downloaded and break the script due to the conflict between the Metadata and the filenames.

What's the best plan of attack here?

**Comment by DIGITALCRIMINAL** [comment]
Just change the date format and the script will automatically update the file names and metadata without downloading anything

**Comment by gitporn873** [comment]
Cool thanks
