### ISSUE TITLE
 Running setup.py install for psutil ... error (feat.pip install -r requirements.txt)

### ISSUE THREAD

**Issue by Chansaris** [DIGITALCRIMINAL/OnlyFans#464]
I'm korean so i'm not good at English

I tried many hour but :( crycry 

I install 3.9.0 and good very good

but when i write' pip install -r requirements.txt '
error :((
Installing collected packages: psutil
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\chans\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chans\\AppData\\Local\\Temp\\pip-install-116dsh6d\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\chans\\AppData\\Local\\Temp\\pip-install-116dsh6d\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\chans\AppData\Local\Temp\pip-record-jtfj3cb5\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\chans\appdata\local\programs\python\python39\Include\psutil'
         cwd: C:\Users\chans\AppData\Local\Temp\pip-install-116dsh6d\psutil\
    Complete output (39 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.9\psutil
    creating build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.9\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    VisualStudio is not installed; get it from http://www.visualstudio.com/en-au/news/vs2015-preview-vs
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\chans\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chans\\AppData\\Local\\Temp\\pip-install-116dsh6d\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\chans\\AppData\\Local\\Temp\\pip-install-116dsh6d\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\chans\AppData\Local\Temp\pip-record-jtfj3cb5\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\chans\appdata\local\programs\python\python39\Include\psutil' Check the logs for full command output.

so i install
  VisualStudio C++ 14.0 but it start again ㅠㅠㅠㅠㅠ crycrycry windows and install new vision okay

**Comment by DIGITALCRIMINAL** [comment]
You need to install VS Studio build tools, look on youtube.

**Comment by Chansaris** [comment]
i love you thx i install vs studio this link but error again again :( but use your answer , error is gone ahahahahhahahahhahahahahahhaa ilove you thxthxthxthxthxthxthxthxthxthx
