### ISSUE TITLE
Running setup.py install for psutil ... error

### ISSUE THREAD

**Issue by dawforpc** [DIGITALCRIMINAL/OnlyFans#467]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\xbot\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xbot\\AppData\\Local\\Temp\\pip-install-t8vyjeav\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\xbot\\AppData\\Local\\Temp\\pip-install-t8vyjeav\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xbot\AppData\Local\Temp\pip-record-ljvkpydo\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\xbot\appdata\local\programs\python\python39\Include\psutil'
         cwd: C:\Users\xbot\AppData\Local\Temp\pip-install-t8vyjeav\psutil\
    Complete output (47 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.9\psutil
    creating build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.9\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\psutil
    creating build\temp.win-amd64-3.9\Release\psutil\arch
    creating build\temp.win-amd64-3.9\Release\psutil\arch\windows
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=573 -DPSUTIL_WINDOWS=1 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -Ic:\users\xbot\appdata\local\programs\python\python39\include -Ic:\users\xbot\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\include\um /Tcpsutil/_psutil_common.c /Fobuild\temp.win-amd64-3.9\Release\psutil/_psutil_common.obj
    _psutil_common.c
    c:\users\xbot\appdata\local\programs\python\python39\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    VisualStudio is not installed; get it from http://www.visualstudio.com/en-au/news/vs2015-preview-vs
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\xbot\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xbot\\AppData\\Local\\Temp\\pip-install-t8vyjeav\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\xbot\\AppData\\Local\\Temp\\pip-install-t8vyjeav\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xbot\AppData\Local\Temp\pip-record-ljvkpydo\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\xbot\appdata\local\programs\python\python39\Include\psutil' Check the logs for full command output.

WHY GETTING THIS ERROR INSTALL VS 2019 ALSO VS TOOLS STILL

**Comment by DIGITALCRIMINAL** [comment]
I dunno, but it's a VS problem... You need to install VS Build Tools.

**Comment by dawforpc** [comment]
Everything was already installed before giving cmd

**Comment by reyaz006** [comment]
Same here.
Went through the link and installed the "Visual Studio Build Tools 2022", still same error. Now installing the 7 GB package consisting of Windows 10 SDK and another set of "build tools".

**Comment by dawforpc** [comment]
> Same here. Went through the link and installed the "Visual Studio Build Tools 2022", still same error. Now installing the 7 GB package consisting of Windows 10 SDK and another set of "build tools".

I understand that Just for the trick I tried to install another onlyfans-scraper after that this problem seems a goner but there is new issue now!  Something went wrong. [BB91C8D6]
