### ISSUE TITLE
Having a issue while scraping OnlyFans 

### ISSUE THREAD

**Issue by Iamknownasfesal** [DIGITALCRIMINAL/OnlyFans#468]
Having issue while logging to account
![accessdenied](https://user-images.githubusercontent.com/39006465/97120467-31689400-1728-11eb-8c27-863bb26f9bfa.png)

Idk what i did wrong but tried your guys **https://github.com/M-rcus/OnlyFans-Cookie-Helper** too, but didnt work.

Did i do something wrong or what? xd

**Comment by DIGITALCRIMINAL** [comment]
I dunno, you'd have to tell me your credentials lol

**Comment by HrnyG4ndalf** [comment]
had the same issue. had to delete a pesky "/t"

**Comment by JayReatard** [comment]
Had the same problem too, couldn't find any "/t" like the other guy said. I got it working again by editing the config file. I only changed my username, and sess and fp tokens, not sure which was the problem.
