### ISSUE TITLE
OFRenamer doesn't work with .csv metadata

### ISSUE THREAD

**Issue by RickyBubbles** [DIGITALCRIMINAL/OnlyFans#469]
OFRenamer doesn't work if metadata has been exported as csv
(I think? Or maybe I'm just stupid...)

Either way OFRenamer breaks:

> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

which I assume means it can't decode the files in the metadata folder because they are .csv

**Comment by DIGITALCRIMINAL** [comment]
CSV is broken, I'm removing it in the next update

**Comment by RickyBubbles** [comment]
I tried changing the config to export json instead of csv, and the script hung.
So could I request some sort of conversion path?

(I'm not sure if I can just delete the metadata folders and let them regenerate, or if doing so will cause problems)

**Comment by bobsage123** [comment]
I can't get renaming to work with JSON metadata either. I'm going from a filename with `[{date}] ({file_name}).{ext}` to `[{date}] {text} [{media_id}].{ext}` and it always redownloads the file instead of renaming.

**Comment by RickyBubbles** [comment]
Will deleting all the metadata and running the script again cause anything to break?

Or will it just regenerate the information it needs and rename things accordingly? (I'm trying to increase the number of characters in the filename)

**Comment by DIGITALCRIMINAL** [comment]
It won't break anything

**Comment by bobsage123** [comment]
With 3.9 is it now safe to scrape text to use in the filename?

**Comment by RickyBubbles** [comment]
Were we not supposed to be using that?

**Comment by bobsage123** [comment]
> Were we not supposed to be using that?

Digitalcriminal has been saying that it is broken and you should not use it. I tested it out for the hell of it and certain videos did not download at all. I assume because it has issues parsing certain characters.

**Comment by DIGITALCRIMINAL** [comment]
The warning not to use text is in the readme for a reason.

@bobsage123 which user were you trying to download with text?

**Comment by RickyBubbles** [comment]
I've had it in place for several versions, with no issues...

For whatever that's worth.

**Comment by bobsage123** [comment]
> The warning not to use text is in the readme for a reason.
> 
> @bobsage123 which user were you trying to download with text?

A bunch of them. I would test downloading a girl with text and without it. Then see if the file size and file amount matched up. On several occasions the folder with text was missing several files it didn't download. One example I can remember is Gianna dior i had bought a few videos from her via messages from a few months back and those were not scraped.
