### ISSUE TITLE
Script Isn't Accessing My OnlyFans Account

### ISSUE THREAD

**Issue by sldr23876** [DIGITALCRIMINAL/OnlyFans#47]
When loading up the script, the program refers to me by a different username than my own and I can't download anything from the accounts I'm subscribed to. I've double checked my config file and my app-token, auth_id, and auth_hash match the values shown in my browser.

<img width="161" alt="wrong username" src="https://user-images.githubusercontent.com/16935594/67234628-4a928280-f3fa-11e9-872e-0c4b3553cd34.png">
{DamnSon is not my username, it's an existing account that belongs to someone else}

**Comment by sldr23876** [comment]
The problem seems to have resolved itself, I'm really not sure what happened. I haven't restarted my computer or cleared my browser cache or altered the config file at all since opening this issue, but the script is working properly now. Feel free to close it if you think it isn't worth looking into!

**Comment by DIGITALCRIMINAL** [comment]
I'm looking into this. It's a rare thing for me so I'll have to catch it when I can :/

**Comment by DIGITALCRIMINAL** [comment]
See: https://github.com/DIGITALCRIMINAL/OnlyFans/issues/52
