### ISSUE TITLE
Archive completed 0.0 seconds / pausing scraper for 0 seconds 

### ISSUE THREAD

**Issue by HelloMotolol** [DIGITALCRIMINAL/OnlyFans#471]
Version 5.5. Google Chrome. Config file is default except for required, correct cookies. Python 3.9 via MS store. Requirements installed successfully no errors. Scraper not detecting any usernames. 

![12](https://user-images.githubusercontent.com/73501363/97230789-cce51d80-1797-11eb-8442-46de2e699608.png)

**Comment by DIGITALCRIMINAL** [comment]
Are you subscribed to anyone?

**Comment by HelloMotolol** [comment]
> Are you subscribed to anyone?

No, they are locked behind a pay wall. Is there a way to target an account?

**Comment by DIGITALCRIMINAL** [comment]
No.
