### ISSUE TITLE
Blacklist isnt always read

### ISSUE THREAD

**Issue by yokonjuan** [DIGITALCRIMINAL/OnlyFans#474]
On previous versions I had an issue where I had to change blacklist names and sometimes having to create numerous lists, or delete lists to update the blacklist. On the newest version it almost never blacklists.

I also have the suggestion when selecting models having the option to choose multiple, but not all.
So maybe an input of | 4,6,8 | would choose 3 models out of say 10.

**Comment by DIGITALCRIMINAL** [comment]
Ye I fixed the blacklist in another commit and I'm adding in multiple choices also.
