### ISSUE TITLE
Running on Colab

### ISSUE THREAD

**Issue by indodatabase45** [DIGITALCRIMINAL/OnlyFans#475]
Hi, I trying to run this AWESOME project on Colab and got this error
What should I do?

![Annotation 2020-10-28 192246](https://user-images.githubusercontent.com/73208025/97423861-3c533c80-1953-11eb-8ae8-813d9d4e9247.jpg)

**Comment by DIGITALCRIMINAL** [comment]
It won't work on Google Colab
