### ISSUE TITLE
Custom naming ignores some files

### ISSUE THREAD

**Issue by dockyflash** [DIGITALCRIMINAL/OnlyFans#480]
Hi, first sorry if this was posted somewhere else already.

When scraping from OF everything works great when using the {file_name} key on the settings but when I tried adding a {date} or {post_id} it just ignored most of the other files.

I'm guessing that's a limitation from those "swipe right to see more" posts then.

But again, it works fine when using the default {file_name}.{ext}

Thanks for the tool

**Comment by DIGITALCRIMINAL** [comment]
which file format isn't working

**Comment by dockyflash** [comment]
The videos, in mp4

**Comment by DIGITALCRIMINAL** [comment]
What is the file name format.....

**Comment by dockyflash** [comment]
i don't get it. maybe it's something on my end
