### ISSUE TITLE
did work fine last night now i get this error "ModuleNotFoundError: No module named 'psutil'" how do i fix that?

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#482]
Did work fine last night 

-----
And now i get this error
-----

C:\temp\OnlyFans DataScraper v5.5>start_ofd.py
Traceback (most recent call last):
  File "C:\temp\OnlyFans DataScraper v5.5\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "C:\temp\OnlyFans DataScraper v5.5\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\temp\OnlyFans DataScraper v5.5\helpers\main_helper.py", line 19, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by sjfer** [comment]
`pip3 install psutil` or `pip3 install -r requirements.txt` when in the OnlyFans directory. Yo umay be able to use `pip` instead of `pip3`

**Comment by whateverman91** [comment]
Run `pip3 install -r requirements.txt` again

**Comment by Dalla-maker** [comment]
not working fix the problem that way. is there other way fix the problem?
