### ISSUE TITLE
Re-construct HTML pages from metadata and media

### ISSUE THREAD

**Issue by whateverman91** [DIGITALCRIMINAL/OnlyFans#485]
Are there any plans to have a way to "re-construct" HTML pages from scraped data? So you can read the posts and see the images/videos together (keeping order and context)

**Comment by DIGITALCRIMINAL** [comment]
No

**Comment by whateverman91** [comment]
Would you accept PRs?

**Comment by DIGITALCRIMINAL** [comment]
Sure but the script is only for scraping and downloading content and not reconstructing html.

**Comment by whateverman91** [comment]
That's what I'm saying... If I wrote another script that re-built HTML would you accept it? As a second script

**Comment by DIGITALCRIMINAL** [comment]
I don't want to add that to the repo since it would just be bloat
