### ISSUE TITLE
What version of microsoft visual studio for psutil?

### ISSUE THREAD

**Issue by RuneDemomn** [DIGITALCRIMINAL/OnlyFans#489]
With this new update psutil is one of the new requirements to operate the python program. However psutil requires Visual Studio 14.0+ as stated at the end of the error code when trying to install it.

I've downloaded 16.7.7 from the Microsoft website but there are hundreds of options to install inside it and the program isnt clear on what to actually install within visual studios, except "Get it with "Build Tools for Visual Studio.""

**Comment by RuneDemomn** [comment]
`
C:\Users\Adam\Desktop\DIGITALCRIMINAL>pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: beautifulsoup4 in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (4.9.3)
Requirement already satisfied: urllib3 in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 3)) (1.25.11)
Requirement already satisfied: win32-setctime in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 4)) (1.0.3)
Requirement already satisfied: pysocks in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 5)) (1.7.1)
Collecting psutil
  Using cached psutil-5.7.3.tar.gz (465 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting lxml
  Using cached lxml-4.6.1-cp39-cp39-win_amd64.whl (3.5 MB)
Collecting mergedeep
  Using cached mergedeep-1.3.0-py3-none-any.whl (6.3 kB)
Collecting jsonpickle
  Using cached jsonpickle-1.4.1-py2.py3-none-any.whl (36 kB)
Collecting deepdiff[murmur]
  Using cached deepdiff-5.0.2-py3-none-any.whl (60 kB)
Collecting numpy==1.19.3
  Using cached numpy-1.19.3-cp39-cp39-win_amd64.whl (13.3 MB)
Requirement already satisfied: idna<3,>=2.5 in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from requests->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in c:\users\adam\appdata\local\programs\python\python39\lib\site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.0.1)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting ordered-set>=4.0.1
  Using cached ordered-set-4.0.2.tar.gz (10 kB)
Collecting mmh3; extra == "murmur"
  Using cached mmh3-2.5.1.tar.gz (9.8 kB)
Collecting zipp>=0.5
  Using cached zipp-3.4.0-py3-none-any.whl (5.2 kB)
Using legacy 'setup.py install' for psutil, since package 'wheel' is not installed.
Using legacy 'setup.py install' for ordered-set, since package 'wheel' is not installed.
Using legacy 'setup.py install' for mmh3, since package 'wheel' is not installed.
Installing collected packages: psutil, six, python-dateutil, lxml, mergedeep, zipp, importlib-metadata, jsonpickle, ordered-set, mmh3, deepdiff, numpy
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\adam\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-lr24yoy_\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-lr24yoy_\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Adam\AppData\Local\Temp\pip-record-hupwqbaj\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\adam\appdata\local\programs\python\python39\Include\psutil'
         cwd: C:\Users\Adam\AppData\Local\Temp\pip-install-lr24yoy_\psutil\
    Complete output (39 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.9\psutil
    creating build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.9\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    VisualStudio is not installed; get it from http://www.visualstudio.com/en-au/news/vs2015-preview-vs
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\adam\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-lr24yoy_\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-lr24yoy_\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Adam\AppData\Local\Temp\pip-record-hupwqbaj\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\adam\appdata\local\programs\python\python39\Include\psutil' Check the logs for full command output.`

**Comment by RuneDemomn** [comment]
Looking through my installed programs, it appears I already have Microsoft Visual C++ 14.25 which should have been the requirement for psutil since it wants 14.0+

If you could clarify in the readme what to actually download with the new 2019 visual studio that would be great.

**Comment by DIGITALCRIMINAL** [comment]
It's literally the same link

![image](https://user-images.githubusercontent.com/21285176/98457011-1f9cdd00-217b-11eb-9f6c-2232974c55bc.png)
