### ISSUE TITLE
Add ability to resume downloads

### ISSUE THREAD

**Issue by helopy** [DIGITALCRIMINAL/OnlyFans#49]
Could you please add the ability to resume downloads?

**Comment by DIGITALCRIMINAL** [comment]
You can set overwrite to False and it won't redownload files that already downloaded

**Comment by dilemmax** [comment]
You could always use a download manager that supports batch downloading from clipboard. I use Internet Download Manager and I can pause and resume my downloads at any time.

**Comment by helopy** [comment]
By resume I mean an ability similar to youtube-dl where you send a range of bytes like [this ](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/downloader/http.py#L80) or 
[this ](https://stackoverflow.com/questions/21775860/python-how-to-download-file-using-range-of-bytes/21776292#21776292). What do you think @DIGITALCRIMINAL?

**Comment by DIGITALCRIMINAL** [comment]
I don't think I'm going to do that anytime soon since OnlyFans has messed with the upload rate of some files.
