### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by willhesee** [DIGITALCRIMINAL/OnlyFans#491]
Have a config option to choose how the content folders are setup, so instead of having {username}/Posts/Free/Images/{file} and {Username}/Posts/Videos/{file} and {username}/Messages/Free/Images/{file} etc. just have {username}/{file} and maybe have the apis as a variable for the file/folder name.

**Comment by DIGITALCRIMINAL** [comment]
With the way, the script is set up; I can't do this right now.

**Comment by DIGITALCRIMINAL** [comment]
Btw I added this with v5.7.
