### ISSUE TITLE
Getting a traceback that ends in a modulenotfounderror when starting

### ISSUE THREAD

**Issue by Marroque** [DIGITALCRIMINAL/OnlyFans#494]
Starting it from the command prompt, the .py file won't open anymore for me, i get this:

D:\OFDL>python start_ofd.py
Traceback (most recent call last):
  File "D:\OFDL\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "D:\OFDL\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "D:\OFDL\helpers\main_helper.py", line 19, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by DIGITALCRIMINAL** [comment]
Run the requirements :)))))))))))))))))))))))))))))))))))))))))))))))))))))))

**Comment by Marroque** [comment]
After running it again looks like i missed the part where it tells me to install visualstudio. After doing that and running the requirements again it worked. My bad, thanks.
