### ISSUE TITLE
traceback: too many files open....

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#496]
So this happens:

![Screen Shot 2020-11-09 at 12 31 39 PM](https://user-images.githubusercontent.com/47627618/98582408-8cea6400-2288-11eb-828a-918becf3dc42.png)

and this happens:
![Screen Shot 2020-11-09 at 12 32 36 PM](https://user-images.githubusercontent.com/47627618/98582464-9f649d80-2288-11eb-846f-ddbd37d6069e.png)

**Comment by DIGITALCRIMINAL** [comment]
You can ignore this error, increase the number of files you can open, or use a diff operating system

**Comment by James-MF-Thomas** [comment]
wheres the issue in this file path? 
![Screen Shot 2020-11-10 at 4 58 12 AM](https://user-images.githubusercontent.com/47627618/98665495-5d336e80-2311-11eb-9024-7d282924b03e.png)

It keeps creating this path inside .sites directory.. 

(this is the same path I was using with 5.5, where it was downloading to a secondary SSD)

**Comment by ProjektPremium** [comment]
> 
> 
> wheres the issue in this file path?
> ![Screen Shot 2020-11-10 at 4 58 12 AM](https://user-images.githubusercontent.com/47627618/98665495-5d336e80-2311-11eb-9024-7d282924b03e.png)
> 
> It keeps creating this path inside .sites directory..
> 
> (this is the same path I was using with 5.5, where it was downloading to a secondary SSD)

Can you do me a favor? Email me imdonaldtramp@protonmail.com

**Comment by James-MF-Thomas** [comment]
just emailed you

**Comment by Code4Win** [comment]
You can run this command in terminal 

`ulimit -S -n 2048`

Then run `start_ofd.py` 

That resolved the issue for me. 

This command will only apply to the current shell session. 

You can add it to your shell configuration file (.bashrc, .zshrc, etc) if you want it to run every time you open a shell.

**Comment by James-MF-Thomas** [comment]
Yeah I ended up running;

`sudo launchctl limit maxfiles 10000 2147483647 `

2147483647 Is equivalent to “unlimited” which is the system install hard limit. apparently if you change the soft limit it automatically and forever removes the unlimited setting(option) 

Obviously unlimited is theoretical, where as 2147483647 is the actual ceiling.

The real difference was changing the soft limit from 256 to 10000

**Comment by Code4Win** [comment]
Changing from the default 256 to 2048 fixed it for me.
