### ISSUE TITLE
Only Onlyfans showing

### ISSUE THREAD

**Issue by neil-ui** [DIGITALCRIMINAL/OnlyFans#499]
Hi,
I love this piece of code, thanks so much for creating it!
I've just upgraded from 5.2 to the latest version and the only options I get when running the scraper are 
Site: 0 = onlyfans | x = Exit

Has support for AVN stars been removed?
If it hasn't, I'd be grateful if someone could point me to where the "sess" is found in the "Inspect" thing, I can find it fine in OnlyFans but not AVN Stars.

**Comment by DIGITALCRIMINAL** [comment]
It's gone
