### ISSUE TITLE
Only grabbing URLs, without downloading the files

### ISSUE THREAD

**Issue by Jacklossa** [DIGITALCRIMINAL/OnlyFans#5]
Hi, is it possible to grab direct URLs for images and videos without actually downloading them?

**Comment by DIGITALCRIMINAL** [comment]
@Jacklossa would you want to export the links into a .json file?

**Comment by DIGITALCRIMINAL** [comment]
An update has been made.
Links are now exported by default when downloading.
I also added arguments to the scrape choice.
`a -l` will now only scrape links without having to download them.
