### ISSUE TITLE
File by year

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#501]
Would is be possible to add an option to file by year and then even month?
Keep the existing folder structure but then break free images for example into multiple directories based on year This could be useful for accounts where they've been posting for a few years and have thousands of images etc.

**Comment by DIGITALCRIMINAL** [comment]
I don't understand this

**Comment by ChillyP** [comment]
Sorry would it be possible to have an option to add a year directory to each media folder. An example folder structure would then be \Onlyfans\User\Posts\Free\Images\2020\files from 2020, then the same for 2019, 2018 etc etc.

**Comment by DIGITALCRIMINAL** [comment]
Can't. You'd have to sort them yourself...

**Comment by ChillyP** [comment]
Ok will give it a go.
