### ISSUE TITLE
Everything worked, but script only downloaded the FREE Content

### ISSUE THREAD

**Issue by quandorondoboy** [DIGITALCRIMINAL/OnlyFans#502]
Is there a way to download the content behind the paywall? Everytime I select a model that I follow and press 0 to donwload everything it downloads only the FREE Content, which is a bummer.
Also, can you download pics of models you can't follow because they are behind a paywall?

**Comment by jp1151419** [comment]
You can't scrape content your account doesn't have access to through the website, it's as simple as that.

**Comment by hawktank** [comment]
Confusing FAQ:

![image](https://user-images.githubusercontent.com/54247989/102899976-50865800-4431-11eb-94e8-6593112b5a47.png)

But upon clicking that tutorial... 

![image](https://user-images.githubusercontent.com/54247989/102900062-698f0900-4431-11eb-9078-5cfc8b9e4211.png)
