### ISSUE TITLE
KeyError: 'hasMore'

### ISSUE THREAD

**Issue by Code4Win** [DIGITALCRIMINAL/OnlyFans#503]
Environment: 
OnlyFans DataScraper v5.6.1
macOS 10.15.7 (19H2)
Python 3.9
Script run from command line

Issue:  
While scrapping 'Type: Messages' error raised, "KeyError: 'hasMore'".
<img width="1373" alt="hasmore_error" src="https://user-images.githubusercontent.com/65194430/99003536-d72b4980-2503-11eb-9068-a0c2d061dc93.png">

**Comment by Code4Win** [comment]
Additional Info:  
Script run from command line again resulted in successful completion without the error.

**Comment by DIGITALCRIMINAL** [comment]
Ahh yes, it's because I haven't handled empty results yet. If you run it again it should work. I'll make a commit later on. Usually happens if you're on a proxy.

**Comment by DIGITALCRIMINAL** [comment]
Added it in the latest commit. It will retry if the result is empty. Hoping this doesn't introduce an infinite loop.
