### ISSUE TITLE
No module names "psutil"

### ISSUE THREAD

**Issue by ClassicKooz** [DIGITALCRIMINAL/OnlyFans#504]
Just downloaded the new version since I kept getting authentication errors on the old one. running `pip install -r requirements.txt` comes up with an error that psutil was not stalled correctly. running the "python start_ofd.py" gives ModuleNotFoundError: No module names 'psutil'. start_ofd.py wont run either, just crashes on startup. I am using python 3.9.

**Comment by DIGITALCRIMINAL** [comment]
Run the requirements again

**Comment by ClassicKooz** [comment]
D:\OnlyFans-5.6.1>pip install -r requirements.txt
Using legacy 'setup.py install' for psutil, since package 'wheel' is not installed.
Using legacy 'setup.py install' for ordered-set, since package 'wheel' is not installed.
Using legacy 'setup.py install' for mmh3, since package 'wheel' is not installed.
Installing collected packages: psutil, six, python-dateutil, lxml, mergedeep, zipp, importlib-metadata, jsonpickle, ordered-set, mmh3, deepdiff, numpy
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-install-msvvefzd\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-install-msvvefzd\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\\AppData\Local\Temp\pip-record-00mb5jlo\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\\appdata\local\programs\python\python39\Include\psutil'
         cwd: C:\Users\\AppData\Local\Temp\pip-install-msvvefzd\psutil\
    Complete output (39 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.9\psutil
    creating build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.9\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    VisualStudio is not installed; get it from http://www.visualstudio.com/en-au/news/vs2015-preview-vs
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

D:\OnlyFans-5.6.1>python start_ofd.py
Traceback (most recent call last):
  File "D:\OnlyFans-5.6.1\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "D:\OnlyFans-5.6.1\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "D:\OnlyFans-5.6.1\helpers\main_helper.py", line 19, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

I downloaded Visual Studio as well as Visual C++ and restarted. Running requirements again also hasnt worked.

**Comment by DIGITALCRIMINAL** [comment]
Run python -v in cmd and tell me the version

**Comment by James-MF-Thomas** [comment]
3.9

**Comment by secretiveolwagner** [comment]
I had the same problem, run `pip3.9 install psutil`
