### ISSUE TITLE
file path wont leave .sites folder

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#507]
So the following path: line 37:

![Screen Shot 2020-11-11 at 1 17 11 PM](https://user-images.githubusercontent.com/47627618/99069742-93245d00-2574-11eb-8a33-bcbb6bbce092.png)

returns this path:

![Screen Shot 2020-11-11 at 1 23 35 PM](https://user-images.githubusercontent.com/47627618/99069806-adf6d180-2574-11eb-8bad-ff8e76aac86a.png)

instead of the intended path:

![Screen Shot 2020-11-11 at 1 29 53 PM](https://user-images.githubusercontent.com/47627618/99069821-b3541c00-2574-11eb-9e0a-5dcd24c05502.png)

the file path had worked as intended before the  3.6 update.... what changed?

**Comment by DIGITALCRIMINAL** [comment]
Have you tried removing the brackets?

**Comment by James-MF-Thomas** [comment]
I’ve tried every combination possible. Even new config and changing it scraperhelper.Jason

**Comment by DIGITALCRIMINAL** [comment]
what is scraperhelper.Jason?

**Comment by James-MF-Thomas** [comment]
Main_helper.py.  phone auto corrected .json . But I misspoke either way

**Comment by DIGITALCRIMINAL** [comment]
Why did you change main_helper.py? What code did you put in?

**Comment by James-MF-Thomas** [comment]
Tried switching out the def path for .sites, but it didn’t work. Still put everything in .sites

**Comment by DIGITALCRIMINAL** [comment]
If you use {/Volume}, it won't recognize it as a path so it will just create a folder in the .sites directory

**Comment by DIGITALCRIMINAL** [comment]
Remove the brackets and the first forward slash

**Comment by James-MF-Thomas** [comment]
Right on. Ill give it a shot.. 5.5 recognized “/volume"

**Comment by James-MF-Thomas** [comment]
This path





Returned this:

**Comment by DIGITALCRIMINAL** [comment]
I don't see anything in your comment

**Comment by James-MF-Thomas** [comment]
This path
![Screen Shot 2020-11-13 at 8 44 26 AM](https://user-images.githubusercontent.com/47627618/99084790-03d77380-258d-11eb-9d31-1a4be46f7dca.png)


Returned this:

![Screen Shot 2020-11-13 at 8 44 10 AM](https://user-images.githubusercontent.com/47627618/99084821-0df97200-258d-11eb-8d03-a44cf4d5b9e8.png)

**Comment by James-MF-Thomas** [comment]
![Screen Shot 2020-11-13 at 8 50 46 AM](https://user-images.githubusercontent.com/47627618/99085050-5a44b200-258d-11eb-8bfc-894bad3c22ff.png)
![Screen Shot 2020-11-13 at 8 50 21 AM](https://user-images.githubusercontent.com/47627618/99085065-5dd83900-258d-11eb-8abc-3611e1645a45.png)

**Comment by DIGITALCRIMINAL** [comment]
That's on your end, you need to make it read and write

**Comment by James-MF-Thomas** [comment]
no permissions have changed.  same drive, dame path worked with previous version
![Screen Shot 2020-11-13 at 8 58 08 AM](https://user-images.githubusercontent.com/47627618/99085957-79900f00-258e-11eb-906e-145bb190985e.png)

**Comment by DIGITALCRIMINAL** [comment]
Have you tried running it in sudo?

**Comment by James-MF-Thomas** [comment]
Same result

**Comment by DIGITALCRIMINAL** [comment]
What's your OS?

**Comment by James-MF-Thomas** [comment]
macOS 
catalina

**Comment by DIGITALCRIMINAL** [comment]
Yeah, I don't have a mac. From what you've shown T2000 is only read-only and you'd have to use Sudo to write to it.

The only thing that's changed in my script is that it only recognizes full paths. If the path doesn't exist it will try to create it or place it in the sites folder

**Comment by DIGITALCRIMINAL** [comment]
Remove the forward-slash from T2000

**Comment by James-MF-Thomas** [comment]
I'll try a different drive.

 just strange - nothing has changed with drive and all permissions say its read/write

**Comment by James-MF-Thomas** [comment]
just tried sending it secondary internal drive..  claims that is read only too--- not possible

**Comment by DIGITALCRIMINAL** [comment]
What was the file path you used

**Comment by James-MF-Thomas** [comment]
"Spartan/onlyfans/"


![Screen Shot 2020-11-13 at 9 33 03 AM](https://user-images.githubusercontent.com/47627618/99089716-4734e080-2593-11eb-8005-9d0b61bf9d1f.png)

**Comment by James-MF-Thomas** [comment]
tried with "/" and with out "/" prefix

**Comment by DIGITALCRIMINAL** [comment]
ah okay I will fix this

**Comment by James-MF-Thomas** [comment]
w/o the /  it goes straight to .sites

**Comment by DIGITALCRIMINAL** [comment]
Open helpers/main_helper.py

Add the input(directory) line

![image](https://user-images.githubusercontent.com/21285176/99090014-f4c0e780-25c5-11eb-9405-d74e438dbc6a.png)

**Comment by James-MF-Thomas** [comment]
mine is on line 275 - issue or non-issue?

![Screen Shot 2020-11-13 at 9 42 44 AM](https://user-images.githubusercontent.com/47627618/99091382-6c2a5300-2595-11eb-9e0a-61081951b690.png)


then I get this traceback:
![Screen Shot 2020-11-13 at 9 48 33 AM](https://user-images.githubusercontent.com/47627618/99091447-882df480-2595-11eb-84dd-7ee267572910.png)

**Comment by DIGITALCRIMINAL** [comment]
It's not formatted correct

**Comment by James-MF-Thomas** [comment]
after entering that line of code: it wants to me to confirm destination path:

![Screen Shot 2020-11-13 at 5 01 42 PM](https://user-images.githubusercontent.com/47627618/99129120-4ff8d700-25d2-11eb-9b54-66c57d5e4119.png)

but still kickbacks: read only

![Screen Shot 2020-11-13 at 5 01 53 PM](https://user-images.githubusercontent.com/47627618/99129140-6737c480-25d2-11eb-9049-4fae39f7816f.png)

**Comment by James-MF-Thomas** [comment]
![Screen Shot 2020-11-14 at 3 14 01 AM](https://user-images.githubusercontent.com/47627618/99143968-af350680-2627-11eb-9b8c-4e94b9ff0a93.png)
