### ISSUE TITLE
Download Processing Loop

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#508]
Having an issue, where the script seems to be stuck in a loop.

I start the script and it begins scrapping “account 1”, the script finds already downloaded media for “account 1”, and then displays the “download processing” for “account 1” images, video and audio. It then repeats again and again and has been doing so for a couple of hours.
I’ve stopped it and started again and it the same thing happens?

The script does seem to start scraping other accounts but always then repeats the scrape for “account 1”. It appears to be stuck scraping paid for media.

**Comment by DIGITALCRIMINAL** [comment]
It's not an issue. It's working as intended.

You can stop downloading paid content in the config.

**Comment by DIGITALCRIMINAL** [comment]
Also, I suggest leaving it to run, because once you download all paid content, it won't do it again.
