### ISSUE TITLE
UnboundLocalError after login on OF

### ISSUE THREAD

**Issue by ma-jay** [DIGITALCRIMINAL/OnlyFans#509]
I am getting the following error after the login to OF

> Auth (V1) Attempt 1/10
> Welcome ---
> Scraping [photo]. Should take less than a minute.
> Scraping [video | stream | gif]. Should take less than a minute.
> Scraping [audio]. Should take less than a minute.
> Scraping [text]. Should take less than a minute.
> 2020-11-13 23:15:12,487 ERROR errors local variable 'metadata_set2' referenced before assignment
> Traceback (most recent call last):
>   File "G:\onlyfans\OnlyFans\datascraper\main_datascraper.py", line 116, in start_datascraper
>     paid_content = module.paid_content_scraper(api)
>   File "G:\onlyfans\OnlyFans\modules\onlyfans.py", line 309, in paid_content_scraper
>     a = export_archive(metadata_set2, metadata_path, json_settings)
> UnboundLocalError: local variable 'metadata_set2' referenced before assignment

I am using the currently most recent revision (0469d14ee544dceaa8081770eb28345c9ffb7143)

**Comment by DIGITALCRIMINAL** [comment]
Thanks, download the latest commit
