### ISSUE TITLE
"No module named'psutil'"

### ISSUE THREAD

**Issue by nerdytech83** [DIGITALCRIMINAL/OnlyFans#510]
Python won't launch because of this error. Also, when I try to launch start_ofd directly with python, it immediately closes.
![Capture](https://user-images.githubusercontent.com/74445601/99141310-2bbfe900-2618-11eb-9dd8-f8fe722b0c40.PNG)

**Comment by DIGITALCRIMINAL** [comment]
Run the requirements, also use the latest commit

**Comment by nerdytech83** [comment]
> Run the requirements, also use the latest commit

This is an error I get when I input "pip install -r requirements.txt"
Is there something I need to install?
What is the "latest commit"?
Also, there is no settings folder in my file.
![error](https://user-images.githubusercontent.com/74445601/99153529-162ddc00-2677-11eb-82d9-9846b52d1613.PNG)
![folder](https://user-images.githubusercontent.com/74445601/99153531-17f79f80-2677-11eb-9030-42a66df1318e.PNG)

**Comment by Aer3x** [comment]
> 
> 
> > Run the requirements, also use the latest commit
> 
> This is an error I get when I input "pip install -r requirements.txt"
> Is there something I need to install?
> What is the "latest commit"?
> Also, there is no settings folder in my file.

it exactly says what you need to install:

 error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

get it here: https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

**Comment by DIGITALCRIMINAL** [comment]
And read the readme for the answer for the settings folder.
