### ISSUE TITLE
Update readme with new auto-scrape paid behaviour

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#512]
I did a bit of digging in the closed issues because I couldn't understand what the script was doing. I read #495 and #498 and I think I understand now but could the ReadMe be updated?

If I got this right;  **"scrape_paid_content": true** means the paid content in _messages_ is scraped automatically for everyone and then we get the list of all active subscriptions. The scraper then scrapes all the _Posts_ paid/free of whoever is selected.

**"scrape_paid_content": false** means the paid content is just scraped along with the rest of the content, one subscription after the other as it used to be?

Is it really just an question of priority then?

edit:  #508 seems to also be because of this confusion

**Comment by DIGITALCRIMINAL** [comment]
It's already in the readme.

**Comment by jp1151419** [comment]
Having read the readme I don't see where the logic is explained for the **Jobs** fields. 

At **""scrape_names" - This will scrape your standard content"**  does **your standard content** mean everything including the paid content?

**Comment by DIGITALCRIMINAL** [comment]
It means that it will scrape posts, messages, paid content, etc of users you're subscribed to.
