### ISSUE TITLE
Keep getting Error: Could not open requirements file

### ISSUE THREAD

**Issue by caseytanx** [DIGITALCRIMINAL/OnlyFans#514]
Newbie here! Forgive me, but I cannot seem to get past the first step. After I run the pip install cmd, while in the right directory, it says Error: Could not open requirements file: {Errno 2} No such file or directory: 'requirements.txt'

**Comment by DIGITALCRIMINAL** [comment]
Have you watched the youtube tutorial

**Comment by caseytanx** [comment]
yes
