### ISSUE TITLE
getting this error more and more often

### ISSUE THREAD

**Issue by Muruxror** [DIGITALCRIMINAL/OnlyFans#517]

**Comment by Muruxror** [comment]
Hey there, i get this error an a few atists now, it seems not to download anything on these artists then. 


the code is: `urllib3.connectionpool Connection pool is full, discarding connection`

**Comment by Muruxror** [comment]
Im also getting this error from time to time : ```
C:\Users\Murux\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\__init__.py:332: MarkupResemblesLocatorWarning: "....." looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
```

**Comment by charizardtheron** [comment]
Getting the exact same issue out of nowhere on every creator that i try to use. Not sure why, not doing anything different than I have, Includes everything that's in the instructions. It would very helpful if this was fixed quickly, my subscriptions expire soon.

**Comment by DIGITALCRIMINAL** [comment]
Set max threads to 1 I guess.

**Comment by Muruxror** [comment]
worked so far but i get still this error:
```
...\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\__init__.py:332: MarkupResemblesLocatorWarning: "....." looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
```
after it looped this about 30 times or so:
```
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.

```

but thanks so far, still any ideas?

**Comment by DIGITALCRIMINAL** [comment]
Just let the scraper run until it's done.

**Comment by DIGITALCRIMINAL** [comment]
These are all just warning, you can just ignore them all.

**Comment by Muruxror** [comment]
then you can close the issue
thank you for the fast reply

**Comment by DIGITALCRIMINAL** [comment]
I suggest putting max threads back to normal though

**Comment by Muruxror** [comment]
ok, thats -1 right?

**Comment by DIGITALCRIMINAL** [comment]
yee
