### ISSUE TITLE
Script doesn't seem to be working anymore

### ISSUE THREAD

**Issue by hmmark1984** [DIGITALCRIMINAL/OnlyFans#52]
I used the script without any issues a few days ago, i went to use it again today and despite rechecking that my app token, auth id and hash are all still correct anytime i try to select a user to scrape i get the message

`You're not subscribed to the user
First time? Did you forget to edit your config.json file?
Task Completed in 0.0 Minutes`

Nothing's changed my end from when it was working but now no matter which user i choose it tells me i'm not subscribed to them?

**Comment by DIGITALCRIMINAL** [comment]
I get this error sometimes, it happens when I take to long to select a user

**Comment by hmmark1984** [comment]
i don't think that was the cause for me as i was typing the username i wanted to scrape within 15 seconds of it prompting me to input one. However it does seem to have fixed itself now, i open and closed the terminal/the script a few times and the first few i was still told i wasn't subbed to the users i tried, then when the script ran it had a different username to mine, then after closing the terminal and running the script again the first time it said i wasn't subbed, the second time it showed me two "access denied" messages but then on the third time of the same user it started scraping the images.

**Comment by DIGITALCRIMINAL** [comment]
Hmm, I'll have to look into this because https://github.com/DIGITALCRIMINAL/OnlyFans/issues/47 has the same problem

**Comment by hmmark1984** [comment]
ok, thanks. I know other people who've written scripts for OF that apparently they're known for fiddling with how their site works for seemingly no reason etc... so maybe they were doing something that caused the script to act funny for a while, as i mentioned it does seem to be ok now but would appreciate you checking it out

**Comment by DIGITALCRIMINAL** [comment]
Yeah, they change a lot of stuff haha. I'm going to add a second auth option incase the first auth fails.
1st Auth would be auth_id and auth_hash
2nd Auth would be the sess (session) token
The downside to the 2nd auth is that you'll only be able to use the script on the computer OnlyFans is logged into.

**Comment by dilemmax** [comment]
I'm having the same issue too and noticed it's not displaying my username. Maybe that would explain why it's displaying the "you're not subscribed to the user." error message.

**Comment by dilemmax** [comment]
I don't actually know my username but I know it starts with u-something.

Now it's displaying the below:

Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan
0
Welcome Grimmjr
Input a onlyfans username or profile link

**Comment by dilemmax** [comment]
Okay, it's back to normal for me now.

**Comment by DIGITALCRIMINAL** [comment]
@hmmark1984 OnlyFans put me into YOUR account but it's back to normal for me now .-.

**Comment by DIGITALCRIMINAL** [comment]
Retrying the auth works.
![image](https://user-images.githubusercontent.com/21285176/67637311-2559b480-f8d1-11e9-841a-bfccea79ec98.png)

**Comment by hmmark1984** [comment]
yeah i think last night it logged me into someone else's account a few times in a row, but closing the console and reopening seemed to solve it for me.

One thing i have noticed is that the script does seem to get "hung up" occasionally with it just sitting seemingly not doing anything for hours at a time, meaning you need to close the console, reopen and start the script again

**Comment by DIGITALCRIMINAL** [comment]
@hmmark1984 is it when it's downloading? OnlyFans' changed something and now some files download very slowly. I'm on a 350Mb connection and I see files downloading at 100Kb. It's best if you export the links into jdownloader or idm and have it download there so you can see the progress. Also, I'm adding something where if you do auth into someone's account, you'll still get to scrape their content.

**Comment by hmmark1984** [comment]
yeah it does seem to be during download, i thought it was freezing up but maybe it is just downloading super slow as i know a couple of people i sub to have 1,2 or even 3GB vids. I've also noticed a fair few corrupted files getting downloaded but i'm 99.9% sure that's an OF's thing and nothing to do with the script.

To do the link export thing do i just add -1 to the end? so for me i'd type `python OF.py-1` ?

Being able to potentially grab other random content would be good, one question though, how would i know who they were subbed to so that i could put in the right names when the script asks?

**Comment by DIGITALCRIMINAL** [comment]
@hmmark1984 go into the config and change "auto_choice" to "a -l" That's a lowercase L, not an I.
![image](https://user-images.githubusercontent.com/21285176/67640307-bfc9f000-f8f1-11e9-8c26-7f421ca7860a.png)


Also regarding your last paragraph, it will be handled like this
![image](https://user-images.githubusercontent.com/21285176/67640294-a628a880-f8f1-11e9-96fb-34b670cc20c0.png)

**Comment by DIGITALCRIMINAL** [comment]
@hmmark1984 Go into the config and change auto_choice to "a -l". That's a lowercase L.
![image](https://user-images.githubusercontent.com/21285176/67640340-f142bb80-f8f1-11e9-9428-1dad0d2c74bf.png)

Regarding the last paragraph, it will be handled like this
![image](https://user-images.githubusercontent.com/21285176/67640369-36ff8400-f8f2-11e9-95f2-db71c424eb81.png)

**Comment by hmmark1984** [comment]
ok cool, cheers for that, i'll give that option a try and see if things work a bit faster.

That looks cool, hopefully you can get that working soon

**Comment by DIGITALCRIMINAL** [comment]
@hmmark1984 If you're on could you run the script and check if you've got access to an account right now?

**Comment by hmmark1984** [comment]
will do

**Comment by hmmark1984** [comment]
indeed i do

`\OnlyFans-master>python OF.py
Welcome u6972054
Input a onlyfans username or profile link`

**Comment by DIGITALCRIMINAL** [comment]
I've got access to the same account.
They're only subscribed to jesseflanagan

**Comment by hmmark1984** [comment]
i had to google who that was, and i'm getting a rather over weight guy in his 30's who was apparently in  The Big Lebowski lol, i'm guessing it's someone else?

**Comment by DIGITALCRIMINAL** [comment]
Lmao
https://t.co/NGRb8frYug?amp=1

**Comment by hmmark1984** [comment]
ah ok, yeah she makes slightly more sense to be on OF lol

**Comment by hmmark1984** [comment]
i'm guessing you did some trickery with the script to see who they were subbed to?

**Comment by DIGITALCRIMINAL** [comment]
@hmmark1984 No trickery, just an API request
![image](https://user-images.githubusercontent.com/21285176/67643727-6faf5580-f912-11e9-947d-b00416b5e331.png)

**Comment by hmmark1984** [comment]
yeah that falls into "trickery" in my books lol, i'd have never figured out how to do that

**Comment by hmmark1984** [comment]
one thing i will say, downloading pics from that account seems to go infinitely faster than it was when i was actually logged in as myself.

(also can i just add what you've posted in there and that'll mean whenever i log in it'll show me the current subs of whoever i log in as? i'm guessing it goes into the actual script at some position?)

**Comment by DIGITALCRIMINAL** [comment]
The order should be like this (This is outdated by the way)

```
session = create_session(user_agent, auth_id, auth_hash, app_token)
names = get_subscriptions(session, app_token)
for name in names:
      start_datascraper(session, app_token, name)
```

**Comment by hmmark1984** [comment]
yep, you've lost me lol. I'm not seeing anything like 

> session = create_session(user_agent, auth_id, auth_hash, app_token)
names = get_subscriptions(session, app_token)
for name in names:
      start_datascraper(session, app_token, name)

anywhere in what was the start_datascraper.py file

for refrence this is what i see when i open that file 

`import os
import modules.onlyfans as onlyfans
import modules.justforfans as justforfans
import modules.four_chan as four_chan
import timeit
import json
import modules.helpers as helpers
# Open config.json and fill in MANDATORY information for the script to work
json_config = json.load(open('config.json'))
json_sites = json_config["supported"]
json_settings = json_config["settings"]
user_agent = json_settings['user-agent']
domain = json_settings["auto_site_choice"]

string = ""
site_names = []
if not domain:
    site_count = len(json_sites)
    count = 0
    for x in json_sites:
        string += str(count)+" = "+x
        site_names.append(x)
        if count+1 != site_count:
            string += " | "

        count += 1

while True:

    if domain:
        site_name = domain
    else:
        print("Site: "+string)
        x = int(input())
        site_name = site_names[x]
    json_auth = json_sites[site_name]["auth"]
    session = ""
    x = ""
    app_token = ""
    if site_name == "onlyfans":
        app_token = json_auth['app-token']
        auth_id = json_auth['auth_id']
        auth_hash = json_auth['auth_hash']
        x = onlyfans
        session = x.create_session(user_agent, auth_id, auth_hash, app_token)
    elif site_name == "justforfans":
        auth_id = json_auth['phpsessid']
        auth_hash = json_auth['user_hash2']
        x = justforfans
        session = x.create_session(user_agent, auth_id, auth_hash)
    elif site_name == "4chan":
        x = four_chan
        session = x.create_session()

    if not session:
        continue
    print('Input a '+site_name+' '+session[1])
    input_link = input().strip()
    username = helpers.parse_links(site_name, input_link)
    start_time = timeit.default_timer()
    session = session[0]
    result = x.start_datascraper(session, username, site_name, app_token)
    stop_time = str(int(timeit.default_timer() - start_time) / 60)
    print('Task Completed in ' + stop_time + ' Minutes')
`

although i've renamed start_datascraper to OF so i only have to type OF.py each time, i'm assuming that's the correct way of doing things?

**Comment by hmmark1984** [comment]
oh wait, i'm guessing you're talking about the onlyfans.py file in the modules folder, although i still can't see where i would put in that code you wrote out for the API request

**Comment by DIGITALCRIMINAL** [comment]
I'll push my update in 10 minutes

**Comment by hmmark1984** [comment]
ah ok lol. I think my head might have exploded if i'd tried to figure things out any further lol, i know they say python is an easy language but it's still way beyond me as someone who's never learnt anything about coding, it's why i'm thankful for guys like you being around!

**Comment by hmmark1984** [comment]
I'm now getting logged in as "Datahoarder" but unfortunately i've no idea who they're subbed to

**Comment by DIGITALCRIMINAL** [comment]
@hmmark1984 Do you still have access to the account?

**Comment by hmmark1984** [comment]
nope, now back to mine it seems

**Comment by DIGITALCRIMINAL** [comment]
OnlyFans is really shitting the bed right now lmao. I also released a commit. It contains the update.

**Comment by hmmark1984** [comment]
yeah, i noticed it seems to be just a handful of accounts it swaps between as i know i've seen that datahoarder one before. Not surprised to hear that about them though, i know from the guy who wrote the last script i used that he had to update the script four or five times in one month because it stopped working due to them changing pointless things

**Comment by hmmark1984** [comment]
definitely nice not having to type in the accounts and who knows maybe i'll win the lottery and get logged in as someone who's subbed to an account i'm actually interested in lol

Only thing is i appear to be having an issue, the first time i ran it, it looked to work, getting to the "scraping images" message and then a few different files scrolling up, it then chucked up 

`Traceback (most recent call last):
  File "of.py", line 91, in <module>
    session[0], username, site_name, app_token)
  File "C:\Users\\Downloads\OnlyFans-master\modules\onlyfans.py", line 68, in start_datascraper
    media_set["valid"], [session], [directory], [username]))
  File "C:\Python37\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python37\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\\Downloads\OnlyFans-master\modules\onlyfans.py", line 241, in download_media
    with open(directory, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\\\Downloads\\OnlyFans-master/sites//onlyfans/siswet19/Images/`

(i've removed my name from that, now when i run it i immediately get

`Downloading 581 Images
Traceback (most recent call last):
  File "of.py", line 91, in <module>
    session[0], username, site_name, app_token)
  File "C:\Users\\Downloads\OnlyFans-master\modules\onlyfans.py", line 68, in start_datascraper
    media_set["valid"], [session], [directory], [username]))
  File "C:\Python37\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python37\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\\Downloads\OnlyFans-master\modules\onlyfans.py", line 241, in download_media
    with open(directory, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\\\Downloads\\OnlyFans-master/sites//onlyfans/siswet19/Images/`

**Comment by DIGITALCRIMINAL** [comment]
Hmm try creating the /sites/ folder

**Comment by hmmark1984** [comment]
it seems to be working now, i think it just wasn't playing well with the pre existing downloads as i tried deleting one of the folders for someone who doesn't have many video's/pics and it's now seemingly happily downloading the videos and has already got all the pics

**Comment by hmmark1984** [comment]
I do also like how it shows you how many pics/vids it's going to get as well

**Comment by hmmark1984** [comment]
well i was wrong, it worked fine for that one persons, but now i'm trying another sub of mine and getting the same message about traceback after it downloads a few pics and the script ends putting me back at

`2019-10-28 02:56:08,668 INFO modules.onlyfans Path: C:\Users\\Downloads\OnlyFans-master/sites//onlyfans/goddesscandika/Images/2018-07-12#Worn #converse for sale #shoefetish #sneakerworship #conversefetish38213157-IMG-20180712-171345.jpg
Traceback (most recent call last):
  File "StartDatascraper.py", line 91, in <module>
    session[0], username, site_name, app_token)
  File "C:\Users\\Downloads\OnlyFans-master\modules\onlyfans.py", line 68, in start_datascraper
    media_set["valid"], [session], [directory], [username]))
  File "C:\Python37\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python37\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\\Downloads\OnlyFans-master\modules\onlyfans.py", line 241, in download_media
    with open(directory, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\\\Downloads\\OnlyFans-master/sites//onlyfans/goddesscandika/Images/'

C:\Users\\Downloads\OnlyFans-master>`

**Comment by DIGITALCRIMINAL** [comment]
Hmmmm does /sites/onlyfans/gc/images/ folder get created?

**Comment by hmmark1984** [comment]
yep and it actually downloaded 102 out of her 104 images, then it popped up that message above and now when i try to run it and select her i get

`Scraping Images. Should take less than a minute.
DIRECTORY - C:\Users\\Downloads\OnlyFans-master/sites//onlyfans/goddesscandika/Images/
Downloading 104 Images
Traceback (most recent call last):
  File "StartDatascraper.py", line 91, in <module>
    session[0], username, site_name, app_token)
  File "C:\Users\\Downloads\OnlyFans-master\modules\onlyfans.py", line 68, in start_datascraper
    media_set["valid"], [session], [directory], [username]))
  File "C:\Python37\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python37\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\\Downloads\OnlyFans-master\modules\onlyfans.py", line 241, in download_media
    with open(directory, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\\\Downloads\\OnlyFans-master/sites//onlyfans/goddesscandika/Images/'

C:\Users\\Downloads\OnlyFans-master>`

**Comment by DIGITALCRIMINAL** [comment]
Hmm, I am using Python 3.8 now. I don't know if it's because of that

**Comment by hmmark1984** [comment]
does that mean i need to update python? i re ran the requirements.txt and updated the thing it said to update

`WARNING: You are using pip version 19.3; however, version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

so i updated that as well, is there another command i can do to update python?

**Comment by DIGITALCRIMINAL** [comment]
Oh that's pip, you don't need to update pip tbh. I don't know if there is another command to update Python. I just use this link:
https://www.python.org/downloads/

**Comment by hmmark1984** [comment]
i'm updating it currently so i'll try the script again when done and see how it goes

**Comment by hmmark1984** [comment]
no luck i'm afraid, i finally managed to get 3.8 installed and it's still doing the same thing, downloading 102 of her pics and then throwing up the message above and kicking me out of the script

**Comment by hmmark1984** [comment]
oh except the messages now say "python38" instead of "37"

**Comment by hmmark1984** [comment]
i've gotta go get some sleep as it's nearly 4am here, so i'll leave it in your capable hands mate, hopefully it either sorts itself or you know what's wrong

**Comment by DIGITALCRIMINAL** [comment]
@hmmark1984 I would have to look at the exported Images.json to see if there is a valid filename

**Comment by hmmark1984** [comment]
just looked and i'm not entirely sure what i'm looking for but it starts off 

`{"valid": [{"post_id": 7966095, "link": "https://cdn.onlyfans.com/Protected/expiretime=1572307200;ip=176.27.240.90/a987487e3af59302c42cb1a3a0027bbc919443802b1b4e2f10823b84d017852f/files/6/64/64055186f4550d8724d29d2c5cab3102/3840x2560_89474d939cc282be77b64e1d26b829353890985dad2c8d30971.jpg", "text": "#GoddessWorship #HighHeels #LegFetish  ", "postedAt": "27-10-2019 10:57:00", "directory": "C:\\Users\\`

and carries on and looks ok to me

**Comment by hmmark1984** [comment]
ok, so the last one reads `invalid": [{"post_id": 1724578, "link": "https://cdn.onlyfans.com/Protected/expiretime=1572307200;ip=176.27.240.90/6f1a7e28c7b551fc2ed611a64d5614b08b528a4c5793aa3714c6b044c25d903e/files/a/ad/adc/adcg9jsbx1xk5mfoefjyxxyrbiliuuj61531405583/82674524-IMG-20180712-171345.jpg", "text": "I have some worn flip flops and trainers for sale - email me pay<a href = \"/goddesscandika\">@goddesscandika</a>.com to purchase  ", "postedAt": "12-07-2018 14:25:50", "directory": "C:\\Users\\\\Downloads\\OnlyFans-master/sites//onlyfans/goddesscandika/Images/", "filename": "2018-07-12I have some worn flip flops and trainers for sale - email me pay@goddesscandika.com to purchase82674524-IMG-20180712-171345.jpg"}]}`

So i'm guessing that's the issue? but it just stops everything and kicks me out of the script, it doesn't even try to download videos and i know before the update i used the "old" version of the script to download all her vids and pics ok

**Comment by DIGITALCRIMINAL** [comment]
Hmm, it shouldn't be the issue since that's the invalid one.
Try searching for the following:
"filename": ""

**Comment by hmmark1984** [comment]
found it, was the one before the invalid one

`{"post_id": 6437, "link": "https://cdn.onlyfans.com/Protected/expiretime=1572307200;ip=176.27.240.90/14ae6e1ed5c015adddbffb7154642b0efa40ff658704a73577171bf67d65657d/files/5/51/51c/51cc26aae1fe4689d74650c26fac9a29/34687995-IMG-3912.JPG", "text": "So a while ago I cut all my hair off.  If you didn't notice, nevermind.  I quite like it short, especially in the tropical climates.  I've also been messing about with snapchat. Filters are a fun way to pass the time whilst watching the tributes roll in.  Carry on!   ", "postedAt": "15-09-2016 06:17:13", "directory": "C:\\Users\\\\Downloads\\OnlyFans-master/sites//onlyfans/goddesscandika/Images/", "filename": ""}`

I'm still in the dark as to what's going on but hopefully it helps you figure it out lol

**Comment by DIGITALCRIMINAL** [comment]
Basically in the script, it will add directory+filename, but filename is empty for some reason.

Are you adding text to the filename?

**Comment by hmmark1984** [comment]
i've got it in the config.json as 

`"settings": {
        "auto_choice": "a",
        "directory": "",
        "file_name_format": "{date}{text}{file_name}.{ext}",
        "text_length": "",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": []`

which is the same file name format as i had on the old version

**Comment by DIGITALCRIMINAL** [comment]
Ah yeah, I suggest putting text_length to "text_length" : "50"
It should then work.

**Comment by hmmark1984** [comment]
does it have to be 50 or can i go a bit longer? ideally i'd like to get a good amount of the "titles" as tha's why i like the script so much, i get readable filenames and not just random letters and numbers

**Comment by DIGITALCRIMINAL** [comment]
The total file_path has to be under 260 characters. The text alone is 261 characters .-.
You can do as much as you want as long as you don't get the error. You can try 100 I guess.

**Comment by hmmark1984** [comment]
ah ok, cheers for all the help and explaining things so a dummy like me can understand it

**Comment by DIGITALCRIMINAL** [comment]
No problem c:

**Comment by hmmark1984** [comment]
i had to go down to 50, as you suggested, but it has now moved onto video's. TBH in an ideal world i'd like the files to be date text for their name, but a lot of the people who upload upload multiple files with the same name so if i leave it as just date text then it stops/doesn't download lots of them so i have to have file_name last to make them all different.

**Comment by dilemmax** [comment]
Hey @DigitalCriminal. How do you run the API?

**Comment by hmmark1984** [comment]
> Hey @DIGITALCRIMINAL. How do you run the API?

if you're talking about the one posted to let you pick from all subscribed accounts, you no longer need to run it as an API, as @DIGITALCRIMINAL has updated the script to include it as default

**Comment by dilemmax** [comment]
Okay cool. Just out of interest, how do you run it? I'm interested in this one.

start_datascraper(session, app_token, username)

This function will scrape the username/link you pass.
The function will return true if scrape finished and false if something went wrong.

**Comment by DIGITALCRIMINAL** [comment]
@dilemmax you have to pass the auth session, app_token and username you want to scrape
