### ISSUE TITLE
Download contents from certain time/year/date

### ISSUE THREAD

**Issue by secretiveolwagner** [DIGITALCRIMINAL/OnlyFans#522]
Is it possible to add a feature that you can download contents from certain year/date/time (whichever is easier to develop).

The reason I'm asking this is because there are some contents which are not worth downloading (whatever reason it might be). For example, a female model A started her career in 2018, she only did solo scenes back then, and she started filming boy/girl scenes this year, and I want to only download her contents from this year instead of the contents from day 1.

Edit 1: Re-elaborated my point a little.

**Comment by adamwinn** [comment]
This would also be good so you can pick up where you last left off and only download the new content that's been posted

**Comment by DIGITALCRIMINAL** [comment]
Eh maybe, doubt it though.
