### ISSUE TITLE
Listing suggestion for future releases

### ISSUE THREAD

**Issue by ProjektPremium** [DIGITALCRIMINAL/OnlyFans#523]
Instead of listing models in order like this; 
1 - name | 2 - name | 3 - name etc

Do you think it would be easy to reprogram to list them like this;
1 - name
2 - name
3 - name

Still in the same order of subscription expiration of course.

Just a suggestion.

**Comment by rjy7wb** [comment]
also you should have the ability to just download everything, and sync new posts that aren't currently archived

**Comment by adamwinn** [comment]
+1 for a sync/merge feature

**Comment by DIGITALCRIMINAL** [comment]
@rjy7wb the script already does that
