### ISSUE TITLE
config.json edit have right info.. v5.7 give me Auth (V1) Attempt 1/10 Access denied. "go back 5.5 all works fine no error Access denied"

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#525]
config.json edit have right info.. v5.7 give me Auth (V1) Attempt 1/10 Access denied. "go back 5.5 all works fine no error Access denied"

---
5.7
--
give me this error... and it i go back use 5.5 it work fine..

Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
There's nothing to scrape.
Archive Completed in 0.03 Minutes
Pausing scraper for 0 seconds.
--

what have missed i the last update..

**Comment by DIGITALCRIMINAL** [comment]
In the past, were you using the fp cookie?

**Comment by Dalla-maker** [comment]
From what I understand, I have never used fp cookie

**Comment by DIGITALCRIMINAL** [comment]
Hmm OnlyFans was down today though

**Comment by Dalla-maker** [comment]
been on onlyfans page all day, works fine no down for me. only thing that down is that i cant use v5.7

**Comment by Dalla-maker** [comment]
is new fix for 5.7 on the way? or do i go back and use 5.5?

**Comment by Dalla-maker** [comment]
If I used fp cookie earlier versions. What changes do I need to make to avoid Auth (V1) Attempt 1/10
Access denied.

**Comment by devsdocs** [comment]
going to open an similar issue, we can't login, endless auth failed even after adding "fp" cookie

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit...

**Comment by DIGITALCRIMINAL** [comment]
There's only one auth version. I can't really do anything since I don't have your account credentials. I suggest just signing in and out multiple times.

**Comment by devsdocs** [comment]
just test it, works now, thank you
