### ISSUE TITLE
ERROR errors 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#529]
Anyone know what this is about?

Scrape Processing
Name: mindimink
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
2020-11-21 03:01:36,824 ERROR errors 'str' object has no attribute 'get'
Traceback (most recent call last):
File "C:\Users\user\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 120, in start_datascraper
x = main_helper.process_names(
File "C:\Users\user\Desktop\OnlyFans-master\helpers\main_helper.py", line 511, in process_names
result = module.start_datascraper(
File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 130, in start_datascraper
results = prepare_scraper(
File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 554, in prepare_scraper
old_metadata = metadata_fixer(archive_directory)
File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 617, in metadata_fixer
media["media_id"] = media.get("media_id", None)
AttributeError: 'str' object has no attribute 'get'

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit, I replaced metadata_fixer with something else.

**Comment by avekifes** [comment]
Thanks, but I'm getting this on first run with the latest commit. The .config should be created automatically, shouldn't it?

C:\Users\user\Desktop\OnlyFans-master>start_ofd.py
Traceback (most recent call last):
  File "C:\Users\user\Desktop\OnlyFans-master\start_ofd.py", line 5, in <module>
    main_test.check_config()
  File "C:\Users\user\Desktop\OnlyFans-master\tests\main_test.py", line 22, in check_config
    json_config, json_config2 = main_helper.get_config(path)
  File "C:\Users\user\Desktop\OnlyFans-master\helpers\main_helper.py", line 372, in get_config
    json_config = json.load(open(config_path))
FileNotFoundError: [Errno 2] No such file or directory: '.settings\\config.json'

**Comment by DIGITALCRIMINAL** [comment]
Yeah but you can copy the script over your old script and it will upgrade the config automatically. I'll fix this though.

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed now

**Comment by paulomanrique** [comment]
I'm getting this error, and after that, the script is changing my auth.json "active" attribute to false.
