### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by hawktank** [DIGITALCRIMINAL/OnlyFans#530]
I'm getting this TypeError when attempting to login and see what's available to scape.  It's worked before and the config credentials / cookie is up to date.  Latest python and ran `pip install -r requirements.txt` to be sure packages are good.  I've been seeing this since a few versions back.  Will try an older version around 5.5 or so. Tried in an elevated PowerShell and CMD - same deal.

![asddsadsds](https://user-images.githubusercontent.com/54247989/99883261-db362600-2beb-11eb-81b7-23c132bb92df.JPG)

**Comment by DSczyrba** [comment]
You need to use latest Python 3.9 to solve this issue.

**Comment by hawktank** [comment]
Oh hah awesome, thanks @DSczyrba !  Yes, just saw OnlyFans v5.5 works fine with Python 3.7x!  Will give the latest release and Python 3.9 a go!

**Comment by DSczyrba** [comment]
No cause @hawktank 
I had the same problem a few minutes ago and was able to solve it that way.

**Comment by DIGITALCRIMINAL** [comment]
Download from the latest commit, instead of the latest release, please. It's better.

**Comment by hawktank** [comment]
Working great now
