### ISSUE TITLE
Auth access denied on all versions

### ISSUE THREAD

**Issue by Requaxy** [DIGITALCRIMINAL/OnlyFans#532]
I've been getting "Auth (V1) Attempt x/10 Access Denied" perpetually on 5.5, 5.7 and the latest commits. It was working on 5.5, now it's stopped on all seemingly. My config.json has been updated over 3 times and none of it works. Why would this be? Because of captcha or something?

**Comment by Telandriq** [comment]
You verified already that your info is updated? Also 5.7 does require python 3.9 to just rule that out once you solve the access denied error.

**Comment by DIGITALCRIMINAL** [comment]
Same issue as https://github.com/DIGITALCRIMINAL/OnlyFans/issues/525

And I dunno why it wouldn't work.
