### ISSUE TITLE
pydevconsole.py: error: unrecognized arguments:

### ISSUE THREAD

**Issue by dev-staecker** [DIGITALCRIMINAL/OnlyFans#534]
After running start_ofd.py for the first time I was able to set the settings in the json file. Now when I rerun the code I get this message:

```
Execute the script with Python 3.9 
Press enter to continue? 
```

When I then press enter I get this error message:

```
usage: pydevconsole.py [-h] [-m]
pydevconsole.py: error: unrecognized arguments: --mode=client --port=52245
```

How do I solve this? Thanks.

**Comment by DIGITALCRIMINAL** [comment]
I don't know what this means. It seems like you did something wrong on your end.
