### ISSUE TITLE
unsupported operand type(s) for -: 'str' and 'int' in 

### ISSUE THREAD

**Issue by JAusD** [DIGITALCRIMINAL/OnlyFans#535]
On some OF-sites, script crashes with above exception in module _main_helper.py_, _line 272_.

In some cases, variable maximum_length contains string value  **'255'** instead of int-value **255**. 
Changing _line 238_ from  
`maximum_length = prepared_format.maximum_length`
to
`maximum_length = int(prepared_format.maximum_length)`
prevents crashing the script but does not fix the root-cause for sure.

Will add further details after investigation.

**Comment by DIGITALCRIMINAL** [comment]
I forgot to convert the str to an int whilst updating the config. It will now handle it automatically. Thanks.
