### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by wangebcjd** [DIGITALCRIMINAL/OnlyFans#538]
Hello，Thanks your code.I can login sucessfully. But when I input "Enter",  it say "TypeError: unsupported operand type(s) for |: 'dict' and 'dict'" . Excuse me ,how can I solve it?
![Snipaste_2020-11-23_17-29-18](https://user-images.githubusercontent.com/38966246/99947771-71687880-2db3-11eb-9825-023999757c46.png)

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.8
