### ISSUE TITLE
[Question] Put paid content in individual folders?

### ISSUE THREAD

**Issue by goodboi69** [DIGITALCRIMINAL/OnlyFans#539]
I would like to keep all my paid content in the default directory but I would like each individual paid post to be in its' own folder. Is that possible and how do I do that?
* Onlyfans
  * Messages
    * Paid
      * Paidcontent1
      * Paidcontent2

**Comment by DIGITALCRIMINAL** [comment]
Read paid formats in the readme.

**Comment by goodboi69** [comment]
> Read paths formats in the readme.

I did. It don't see how I can only specify paid only content to be in separate folders and the rest as the default.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, you can't do that, you'd have to organize on your end.
