### ISSUE TITLE
No module named 'win32_setctime'

### ISSUE THREAD

**Issue by Excentricitet** [DIGITALCRIMINAL/OnlyFans#54]
Windows 10
![image](https://user-images.githubusercontent.com/43474772/67907562-5401b480-fb89-11e9-82f7-f641712c1055.png)
Traceback:
![image](https://user-images.githubusercontent.com/43474772/67907686-d4c0b080-fb89-11e9-8741-473b3f761b30.png)
How can fix it?

**Comment by Excentricitet** [comment]
Programm started and downloaded 16 Images, but then I got that Error

**Comment by DIGITALCRIMINAL** [comment]
Was about to say run requirements but you already got it. You're using Python 3.8 right?

**Comment by Excentricitet** [comment]
python 3.7.0

**Comment by DIGITALCRIMINAL** [comment]
Try with Python 3.8. Python 3.7.4 might work because that's what the script was last built with but now it's being built with Python 3.8 in mind.
