### ISSUE TITLE
NEW LINK DETECTED,

### ISSUE THREAD

**Issue by DarkDownloader** [DIGITALCRIMINAL/OnlyFans#541]
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
NEW LINK DETECTED, PLEASE OPEN AN ISSUE ON GITHUB AND PASTE THE NEW LINK THERE SO I CAN HANDLE THE LINK, THANKS.
LINK: https://ca.convert.onlyfans.com/upload/a38a1ebdd725acec2b16247c499b98d9839448.jpeg

**Comment by DIGITALCRIMINAL** [comment]
Thank youuu

**Comment by DIGITALCRIMINAL** [comment]
Btw the commit is up.
