### ISSUE TITLE
ModuleNotFoundError: No module named 'deepdiff'

### ISSUE THREAD

**Issue by cyclone463** [DIGITALCRIMINAL/OnlyFans#543]
Windows 10 - 2004
Python version 3.9.0
Visual Studio Build Tools 2019 - 16.8.2

got the same error when extracting/running files from C:\OF
also tried deleting/redownloading

C:\OnlyFans-5.8>python start_ofd.py
Traceback (most recent call last):
  File "C:\OnlyFans-5.8\start_ofd.py", line 2, in <module>
    import tests.main_test.py
  File "C:\OnlyFans-5.8\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\OnlyFans-5.8\helpers\main_helper.py", line 4, in <module>
    from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'

-------------------------------------------------------------------------------------

If I delete the line of code in question, I get another module not found error.

C:\OnlyFans>python start_ofd.py
Traceback (most recent call last):
  File "C:\OnlyFans\start_ofd.py", line 2, in <module>
    import tests.main_test.py
  File "C:\OnlyFans\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\OnlyFans\helpers\main_helper.py", line 5, in <module>
    from classes.prepare_metadata import format_variables, prepare_metadata, prepare_reformat
  File "C:\OnlyFans\classes\prepare_metadata.py", line 5, in <module>
    from requests.api import get
ModuleNotFoundError: No module named 'requests'

**Comment by globalgossamer** [comment]
The requirements.txt has new stuff in it, try `pip install -r requirements.txt`

**Comment by srw91** [comment]
Been troubleshooting this all night. 
I had this issue but pip install deepdiff fixed it. eventually got stuck on psutil not being found despite it being installed.
I eventually uninstalled pip, _apt-get install python**3.9**-dev_, reinstall pip with python3.9 get-pip.py. Redid the requirements and suddenly it works.

**Comment by DIGITALCRIMINAL** [comment]
I dunno... just try reinstalling python and doing what the answers above did .-.

**Comment by cyclone463** [comment]
Hmm... did `pip install deepdiff` but it didn't fix the issue for me. Still got the same error.

Just did a complete reinstall and now I'm getting an error I used to get when on python 3.8.

![image](https://user-images.githubusercontent.com/74943387/100148369-85fb4e00-2e51-11eb-821c-cafc00ee5196.png)

I just spun up a fresh VM and tried using python 3.10.0a1 as well. got an error when doing  `pip install -r requirements.txt` because wheels couldn't be built for it. I tried running `start_ofd` anyways and ended up with the second error in the original post `ModuleNotFoundError: No module named 'requests'`

**Comment by DIGITALCRIMINAL** [comment]
Try not renaming the folder and putting it in the downloads folder,

**Comment by cyclone463** [comment]
lol that was it. Leaving the folder named "OnlyFans-5.8" and leaving it in the Downloads folder resolved the issue.

**Comment by DIGITALCRIMINAL** [comment]
You should be able to put it anywhere, just don't make "OnlyFans" the first folder in the path.
