### ISSUE TITLE
Site: 0 = onlyfans | x = Exit 0 Auth (V1) Attempt 1/10 Access denied. Auth (V1) Attempt 2/10 Access denied. Auth (V1) Attempt 3/10 Access denied. Auth (V1) Attempt 4/10 Access denied. Auth (V1) Attempt 5/10 Access denied.

### ISSUE THREAD

**Issue by AshSha1** [DIGITALCRIMINAL/OnlyFans#546]
It is not working , also it cause issue on browser ,
Eg I have chrome and using the useragent for chrome in this .
I will get this error and also it will logout from chrom .

I tried to run this many times and same behaviour .
also i changed browser now to mozila and once it worked and then it also show same behaviour and on mozila also it was logout automatically

**Comment by AshSha1** [comment]
It's like they have made some changes in there session been accessed by other tool !!

**Comment by zeldatp151** [comment]
This happens if part of your auth in the config is wrong, and it will log you out on the session because onlyfans detects it as auth failures on an existing session. Each time you access onlyfans, it can change your auth settings, so you need to update the config.json each time.

**Comment by ModernAesthetics** [comment]
I am getting the same issue

**Comment by AshSha1** [comment]
Auth_id  is  filled with id 
other are not

So should i remove "auth_id" also ?



"auth_id": "xxxx",
"auth_hash": "",
"auth_uniq_": "",

**Comment by DIGITALCRIMINAL** [comment]
> It's like they have made some changes in there session and able to detect that it is been accessed by other tool !!

Wrong...

> This happens if part of your auth in the config is wrong, and it will log you out on the session because onlyfans detects it as auth failures on an existing session. Each time you access onlyfans, it can change your auth settings, so you need to update the config.json each time.
> 
> also make sure you don't have auth fields filled out in your config.json if they aren't actually shown in your cookies.

Yep that's what happens @zeldatp151 

@AshSha1 literally just add whenever cookies you see from the browser that matches the config.

**Comment by AshSha1** [comment]
okay 

So i added the 
username
auth_id
sess
and user_agent

and denied again 

H:\NN\NN\OnlyFans-5.7\OnlyFans-5.7>python start_ofd.py
Site: 0 = onlyfans | x = Exit
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10

**Comment by AshSha1** [comment]
still confused about auth field 

 "auth_id": "",
        "auth_hash": "",
        "auth_uniq_": "",

all of them it has to be empty 
right ?

**Comment by zeldatp151** [comment]
> still confused about auth field
> 
> "auth_id": "",
> "auth_hash": "",
> "auth_uniq_": "",
> 
> all of them it has to be empty
> right ?

for mine, I have 
username
auth_id
sess
app_token
user_agent
all filled out.

auth_hash
auth_uniq 
are both empty

**Comment by AshSha1** [comment]
exact same thing i have and facing problems 
and in previous version the fp was also there now it is not ,is fp cauing issue ?


 "username": "xxxxxxxx",
        "auth_id": "xxxxxxxxxx",
        "auth_hash": "",
        "auth_uniq_": "",
        "sess": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "app_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "user_agent": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "support_2fa": true

**Comment by AshSha1** [comment]
at last it worked 
not sure how , but created new config file and then it worked
