### ISSUE TITLE
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

### ISSUE THREAD

**Issue by pocoai** [DIGITALCRIMINAL/OnlyFans#547]
On the latest commit, scraping fails for me after reaching this point:

Scraping - d*****
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - f*****
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - l*****
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - None
2020-11-24 15:50:57,174 ERROR errors join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
Traceback (most recent call last):
  File "/Users/xxxx/OnlyFans-master/datascraper/main_datascraper.py", line 121, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "/Users/xxxx/OnlyFans-master/modules/onlyfans.py", line 324, in paid_content_scraper
    formatted_directories = format_directories(
  File "/Users/xxxx/OnlyFans-master/modules/onlyfans.py", line 523, in format_directories
    legacy_model_directory = x["legacy_model_directory"] = os.path.join(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Is that ”scraping - none” line to be expected? Up to this point, a username is shown where ”none” is. Also, I don’t follow the user whose handle appears after ”scraping” in the last apparently successful scrape before ”none.” I’m not sure if this is related to the error but figured it might be worth mentioning.

**Comment by DIGITALCRIMINAL** [comment]
Ahhh I forgot about paid content scraping. I'll fix it; thanks.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit

**Comment by pocoai** [comment]
Hmm, I’m still seeing the same error. Do I need to change something on my end?

**Comment by DIGITALCRIMINAL** [comment]
Nah it's not you, it's me. I know what the bug is.

**Comment by DIGITALCRIMINAL** [comment]
@pocoai do you have scrape_names set to false?

**Comment by pocoai** [comment]
it was set to true. I just tried changing it to false, though, and it didn’t fix the issue. it's possible I'm just doing something wrong, though. I tried changing a few variables and nothing seems to have an effect on how the app runs

**Comment by DIGITALCRIMINAL** [comment]
I believe I've fixed it in the latest commit. The script was grabbing all your subscribers and looping through all of them, sometimes it would be invalid. It should be fixed and should run faster now.

**Comment by pocoai** [comment]
great, the latest commit seems to be an improvement. no more ”typeerror.” unfortunately, now it's misbehaving in a new way. it scrapes everything almost instantly but then only sends a small subset of handles to the ”download processing” phase and then loops the whole process, always bringing the same few accounts to the actual download stage

**Comment by DIGITALCRIMINAL** [comment]
It's not an issue. Read #jobs in the read me.

**Comment by pocoai** [comment]
I just tried again with a fresh download and it seems to be working normally, thanks!
