### ISSUE TITLE
Flag to download the latest N days only

### ISSUE THREAD

**Issue by whateverman91** [DIGITALCRIMINAL/OnlyFans#548]
Could you please consider adding a flag to download the last N days only? Some creators have HUGE libraries (I have seen one of 600GB) and it would help to split them in multiple parts

**Comment by DIGITALCRIMINAL** [comment]
Maybe in the future, I'm still rebuilding my script.
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/522
