### ISSUE TITLE
5.8.1 issue 

### ISSUE THREAD

**Issue by iknewit2** [DIGITALCRIMINAL/OnlyFans#550]
getting this issue i didnt have with 5.4 & 5.5 at all. 

Q:\xD\OnlyFans-5.8.1>python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "Q:\xD\OnlyFans-5.8.1\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "Q:\xD\OnlyFans-5.8.1\helpers\main_helper.py", line 5, in <module>
    from classes.prepare_metadata import format_variables, prepare_metadata, prepare_reformat
  File "Q:\xD\OnlyFans-5.8.1\classes\prepare_metadata.py", line 217, in <module>
    class prepare_reformat(object):
  File "Q:\xD\OnlyFans-5.8.1\classes\prepare_metadata.py", line 251, in prepare_reformat
    def reformat(self, unformatted_list) -> list[str]:
TypeError: 'type' object is not subscriptable

**Comment by DIGITALCRIMINAL** [comment]
Who are you trying to scrape?

**Comment by iknewit2** [comment]
Onlyfans

**Comment by iknewit2** [comment]
I’ve been using 5.5 the last like 2-3 weeks no issue, then that stopped
working last night, ghen I downloaded your new release and I can’t work it
at all,

**Comment by DIGITALCRIMINAL** [comment]
I was talking about the username

**Comment by DIGITALCRIMINAL** [comment]
I've added a bunch of fixes after I release 5.8.1 so you can try downloading the latest commit

**Comment by iknewit2** [comment]
i can't get past "python start_ofd.py" on the command prompt, so it won't create that settings folder to edit the config.

**Comment by DIGITALCRIMINAL** [comment]
Are you on Windows

**Comment by iknewit2** [comment]
yep.

**Comment by DIGITALCRIMINAL** [comment]
Python 3.9?

**Comment by iknewit2** [comment]
3.8.5

**Comment by DIGITALCRIMINAL** [comment]
... use Python 3.9. Literally says that on the FAQ.
