### ISSUE TITLE
deepdiff error

### ISSUE THREAD

**Issue by NathanIfinity** [DIGITALCRIMINAL/OnlyFans#551]
When ever i launch the start_ofd.py after running the requirements, I get and error message 

Traceback (most recent call last):
  File "H:\Girlz\Scraper\Digital_OF\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "H:\Girlz\Scraper\Digital_OF\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "H:\Girlz\Scraper\Digital_OF\helpers\main_helper.py", line 4, in <module>
    from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'

but after running the requirement text it clearly says it's installed all requirements, even tried uninstalling and reinstalling.. worked fine last week.. 

H:\Girlz\Scraper\Digital_OF>pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\jomor\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: beautifulsoup4 in c:\users\jomor\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 2)) (4.8.2)
Requirement already satisfied: urllib3 in c:\users\jomor\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 3)) (1.25.7)
Requirement already satisfied: win32-setctime in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: pysocks in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: psutil in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 6)) (5.7.3)
Requirement already satisfied: python-dateutil in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 7)) (2.8.1)
Requirement already satisfied: lxml in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 8)) (4.5.2)
Requirement already satisfied: mergedeep in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 9)) (1.3.0)
Requirement already satisfied: jsonpickle in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 10)) (1.4.1)
Requirement already satisfied: deepdiff[murmur] in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 11)) (5.0.2)
Requirement already satisfied: numpy==1.19.3 in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 12)) (1.19.3)
Requirement already satisfied: ujson in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 13)) (4.0.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\jomor\appdata\roaming\python\python38\site-packages (from requests->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jomor\appdata\roaming\python\python38\site-packages (from requests->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: soupsieve>=1.2 in c:\users\jomor\appdata\roaming\python\python38\site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (1.9.5)
Requirement already satisfied: six>=1.5 in c:\users\jomor\appdata\roaming\python\python38\site-packages (from python-dateutil->-r requirements.txt (line 7)) (1.13.0)
Requirement already satisfied: importlib-metadata in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from jsonpickle->-r requirements.txt (line 10)) (3.1.0)
Requirement already satisfied: ordered-set>=4.0.1 in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from deepdiff[murmur]->-r requirements.txt (line 11)) (4.0.2)
Requirement already satisfied: mmh3; extra == "murmur" in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from deepdiff[murmur]->-r requirements.txt (line 11)) (2.5.1)
Requirement already satisfied: zipp>=0.5 in c:\users\jomor\appdata\local\programs\python\python38-32\lib\site-packages (from importlib-metadata->jsonpickle->-r requirements.txt (line 10)) (3.4.0)

tried with latest commit ans same error

thanks

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.9.
