### ISSUE TITLE
Issue when ripping all

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#552]
Hi, 

currently using the latest commit, 2ea6dac. I get this error when the rip-all reaches onlyfans.com/ciieraa
![screenshot](https://user-images.githubusercontent.com/58760178/100404634-d6300700-302f-11eb-80b2-01b97762b7ae.png)

edit: Just tried scraping that account individually and I get the same error.

edit2: the blacklist option doesn't seem to work to skip that account when ripping all.

**Comment by DIGITALCRIMINAL** [comment]
Try to delete or fix the metadata file that is broken.
