### ISSUE TITLE
[bug] Stuck on Scraping

### ISSUE THREAD

**Issue by Telandriq** [DIGITALCRIMINAL/OnlyFans#553]
On the latest master commit from a few hours back, been stuck on user elletwerk for over an hour at just 
Scraping - elletwerk | 19 / 34
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.

When it starts it hangs on paid content of casadyarobertson 

Scraping - casadyarobertson | 2 / 34
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.

for a few minutes.

Haven't progressed past this. Have deleted metadata of both, not sure what is causing it.

**Comment by ChillyP** [comment]
I experience this as well, however deleting what seems like bloated metadata files does resolve the issue for me.

I’ve deleted metadata files that are almost 100mb in size, which are then only 4/5mb once the script completes.

**Comment by DIGITALCRIMINAL** [comment]
There was a problem between 5.7 and 5.8.1 with duplicate metadata files; I did fix it though.

**Comment by ChillyP** [comment]
Ok awesome, I've deleted all metadata, downloaded the latest commits and will re-run the script so anything that's legacy duplication should now be gone .

Cheers as always!! 👍

**Comment by DIGITALCRIMINAL** [comment]
Legacy stays unfortunately... I need to add it to the folder cleanup function soon.
