### ISSUE TITLE
[FR] HTTP proxy support

### ISSUE THREAD

**Issue by kotori2** [DIGITALCRIMINAL/OnlyFans#556]
It seems you hard-coded socks proxy here. 
https://github.com/DIGITALCRIMINAL/OnlyFans/blob/945f1148bb19456a245745e4f4f2099cdc589ba3/apis/api_helper.py#L129-L130
It will be great if you add custom configs for HTTP proxies.

**Comment by DIGITALCRIMINAL** [comment]
In the future, I will.
