### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by NullTie** [DIGITALCRIMINAL/OnlyFans#557]
Hello, 

I'm using this for the first time and I am having an issue when it comes to starting stard_ofd.py

![image](https://user-images.githubusercontent.com/8681408/100524563-0bdb0a00-316e-11eb-9f5c-0e06f2b003f8.png)

I am on python 3.9 and this error appears both on 5.8.1 and 5.8. I have not tried anything earlier.

**Comment by tbturbo** [comment]
I also get the same

**Comment by Anonymeowse** [comment]
I had the same issue and it was because I wasn't using python 3.9. I know you said you have it installed but are you sure you're using that version? `python --version`

**Comment by DIGITALCRIMINAL** [comment]
You only get this error if you're not on 3.9
