### ISSUE TITLE
ERROR: Trailing data

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#558]
![Screen Shot 2020-11-29 at 7 15 27 AM](https://user-images.githubusercontent.com/47627618/100544702-1b655c00-321d-11eb-9b0a-3643cc22dd8f.png)

**Comment by Code4Win** [comment]
Looks like you're missing ujson. 

From the project folder open Terminal and run the command below:

pip install -r requirements.txt

**Comment by James-MF-Thomas** [comment]
No I have all requirements. It only tb’s on certain models

**Comment by Code4Win** [comment]
Have you tried deleting the metadata for the user with the error and then running the script again?

**Comment by DIGITALCRIMINAL** [comment]
Delete the metadata or fix it
