### ISSUE TITLE
requirements mmh3, failed to build

### ISSUE THREAD

**Issue by dethorpe** [DIGITALCRIMINAL/OnlyFans#559]
Hey! 
Trying to download the requirements fails to build mmh3. I think these are the pertinent lines. 

```
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for mmh3
```

Any thoughts on how I can address this issue? I have run the Google-fu gauntlet with no luck.

By the way although it has been a minute since I've tried to run your script. When it works, it works! I appreciate all the hard work you've done and I am impressed you continue to patch this up. Thanks a million.

**Comment by DIGITALCRIMINAL** [comment]
I dunno, all I can say is you need to use Python 3.9, and install MS Build tools

**Comment by dethorpe** [comment]
Hmm... I am trying reinstalling Python and Visual Studio incase the Build Tools is corrupted. MS Build tools used to be a discreate part of the MSVS Installer choices but it looks to less simplified now. Or am I looking at this wrong now?

**Comment by DIGITALCRIMINAL** [comment]
That's the link
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16
