### ISSUE TITLE
CONTACT

### ISSUE THREAD

**Issue by zedzed-wq** [DIGITALCRIMINAL/OnlyFans#561]
I want to ask if a specific script can be made for OnlyFans (Private and not regarding downloading content)

Where can I contact you

**Comment by DIGITALCRIMINAL** [comment]
I hope it's not a braindead question like "Can you make OnlyFans Hack" or something.
datahoarders@protonmail.com

**Comment by DIGITALCRIMINAL** [comment]
Removed my contact because no reply.
