### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by febo01** [DIGITALCRIMINAL/OnlyFans#562]
module/onlyfans.py line 1027

if item["usersCount"]) > 2:

changed for 

if int(item["usersCount"]) > 2000:

and working now.

Good day!

BTW, nice app!! 10000/10!

**Comment by artyom2035** [comment]
@febo01 If your using a blacklist looks like it's broken now. They've been having 'issues' recently so it's probably some site update that broke it. Found two workarounds that worked for me - remove blacklist name from config file or comment lines 1027-1029 from onlyfans.py:

     if item["usersCount"] > 2:
                list_id = str(item["id"])
                list_users = api.get_lists_users(list_id)

**Comment by DIGITALCRIMINAL** [comment]
Huh, strange; it's working for me. If I ever get this error, I'll know what to do. Thanks.

**Comment by DIGITALCRIMINAL** [comment]
I added the fix to the latest commit.
