### ISSUE TITLE
build tools

### ISSUE THREAD

**Issue by 999Jw** [DIGITALCRIMINAL/OnlyFans#563]
![Annotation 2020-12-01 214306](https://user-images.githubusercontent.com/70190014/100817368-67332380-341e-11eb-9536-840965b0210b.png)
which tools i have to download please ?

**Comment by DIGITALCRIMINAL** [comment]
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16
