### ISSUE TITLE
Issue with date in file name

### ISSUE THREAD

**Issue by JLH972** [DIGITALCRIMINAL/OnlyFans#566]
Hi, I am facing an issue when using {date} in filename. As you can see in attachment, for some file, the date display in the filename is different than the explorer Date. I have check on the model page and the correct time is always the one display in the explorer "Date" column .

I face this issue with all scraper version for at least 1 month. I have many duplicated files created because of this issue. Some previous files were well named but have now a duplicated file with wrong date.

here is my config.json :
        "download_directories": [
          "C:/users/***/Folder/Truc//"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{username}-{date}_{text}-{filename}.{ext}",

![Date Issue](https://user-images.githubusercontent.com/63334693/100971587-9d030580-350d-11eb-9d9a-40b572e48d8a.png)

**Comment by DIGITALCRIMINAL** [comment]
I need an example of duplicate files

**Comment by JLH972** [comment]
Here an example. 
![Date Issue 2](https://user-images.githubusercontent.com/63334693/101182355-57852c00-3624-11eb-88a7-3677764fdc1c.png)

As you can see i'm syncing this file in a cloud. The ones with the cloud icon are the ones that were downloaded with an older version of the script. Comparing with the model's profile, the correct publication dates are those of the old files.

**Comment by zetaomegagon** [comment]
@JLH972 do you have `"overwrite_files": false,` in your config.json?

**Comment by DIGITALCRIMINAL** [comment]
I don't have any of those files so I won't be able to do anything unless you have more examples .-.
