### ISSUE TITLE
Error while executing start_ofd.py 

### ISSUE THREAD

**Issue by guiinow** [DIGITALCRIMINAL/OnlyFans#567]
I'm using python 3.9 in Ubuntu. I've installed the requirements, but I keep getting this error: 
![image](https://user-images.githubusercontent.com/38408385/101065456-f30a9400-3573-11eb-82b1-1920da946033.png)

**Comment by DIGITALCRIMINAL** [comment]
Then you haven't installed the requirements properly

**Comment by jinseobhong** [comment]
If you installed python 3.9, You need to resolve package dependencies. Support for backwards compatibility deprecated in Python 3.9 can be resolved with the Python3.9-dev package
