### ISSUE TITLE
Fails to start with new update

### ISSUE THREAD

**Issue by MadamJazzy** [DIGITALCRIMINAL/OnlyFans#568]
Before updating to current branch everything was working as expected. However after updating to the current branch gets the below error. I've made sure that the creds are correct and installed all requirements. And yes, i am on the current version 5.9.1 released yesterday. 

```C:\Users\jleeh>H:\OnlyFans_Git\start_ofd.py
Traceback (most recent call last):
  File "H:\OnlyFans_Git\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "H:\OnlyFans_Git\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "H:\OnlyFans_Git\helpers\main_helper.py", line 5, in <module>
    from classes.prepare_metadata import format_variables, prepare_metadata, prepare_reformat
  File "H:\OnlyFans_Git\classes\prepare_metadata.py", line 217, in <module>
    class prepare_reformat(object):
  File "H:\OnlyFans_Git\classes\prepare_metadata.py", line 251, in prepare_reformat
    def reformat(self, unformatted_list) -> list[str]:
TypeError: 'type' object is not subscriptable```

**Comment by JordyUSA** [comment]
I have the same problem

**Comment by hugeband** [comment]
> Before updating to current branch everything was working as expected. However after updating to the current branch gets the below error. I've made sure that the creds are correct and installed all requirements. And yes, i am on the current version 5.9.1 released yesterday.
> 
> ```python
> Traceback (most recent call last):
>   File "H:\OnlyFans_Git\start_ofd.py", line 2, in <module>
>     import tests.main_test as main_test
>   File "H:\OnlyFans_Git\tests\main_test.py", line 4, in <module>
>     import helpers.main_helper as main_helper
>   File "H:\OnlyFans_Git\helpers\main_helper.py", line 5, in <module>
>     from classes.prepare_metadata import format_variables, prepare_metadata, prepare_reformat
>   File "H:\OnlyFans_Git\classes\prepare_metadata.py", line 217, in <module>
>     class prepare_reformat(object):
>   File "H:\OnlyFans_Git\classes\prepare_metadata.py", line 251, in prepare_reformat
>     def reformat(self, unformatted_list) -> list[str]:
> TypeError: 'type' object is not subscriptable```
> ```

You need to use python 3.9

**Comment by DIGITALCRIMINAL** [comment]
> > Before updating to current branch everything was working as expected. However after updating to the current branch gets the below error. I've made sure that the creds are correct and installed all requirements. And yes, i am on the current version 5.9.1 released yesterday.
> > ```python
> > Traceback (most recent call last):
> >   File "H:\OnlyFans_Git\start_ofd.py", line 2, in <module>
> >     import tests.main_test as main_test
> >   File "H:\OnlyFans_Git\tests\main_test.py", line 4, in <module>
> >     import helpers.main_helper as main_helper
> >   File "H:\OnlyFans_Git\helpers\main_helper.py", line 5, in <module>
> >     from classes.prepare_metadata import format_variables, prepare_metadata, prepare_reformat
> >   File "H:\OnlyFans_Git\classes\prepare_metadata.py", line 217, in <module>
> >     class prepare_reformat(object):
> >   File "H:\OnlyFans_Git\classes\prepare_metadata.py", line 251, in prepare_reformat
> >     def reformat(self, unformatted_list) -> list[str]:
> > TypeError: 'type' object is not subscriptable```
> > ```
> 
> You need to use python 3.9

And use the latest commit.
