### ISSUE TITLE
Getting "Access Denied" errors

### ISSUE THREAD

**Issue by boulara** [DIGITALCRIMINAL/OnlyFans#57]
Tried multiple accounts and got the auth creds but still getting Access Denied, wonder if something changed in the login process.

**Comment by boulara** [comment]
looks like the site has re-captcha now ;(

**Comment by DIGITALCRIMINAL** [comment]
@boulara We bypass the ReCaptcha already. It still works on my end. You have to make sure that your user-agent is correct.
