### ISSUE TITLE
Messages Metadata

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#571]
Hey, running the latest commit

I think there maybe an issue with duplication but specific to messages, metadata files are really large. If I remove all metadata files and run the script and it completes, a users messages metadata file maybe 2/3mb after a couple more runs the same users message metadata file is maybe 200mb?

**Comment by DIGITALCRIMINAL** [comment]
which user are you scraping

**Comment by ChillyP** [comment]
calymorgan

**Comment by DIGITALCRIMINAL** [comment]
What's your file path format

**Comment by ChillyP** [comment]
Just what is default in the config file, only change on that side is the directory location is on my D drive.

**Comment by DIGITALCRIMINAL** [comment]
Check the metadata for duplicate media_id values

**Comment by ChillyP** [comment]
No duplicate media IDs but lots of duplicate post IDs

**Comment by DIGITALCRIMINAL** [comment]
If there are no duplicate media ids, then it's working as intended

**Comment by ChillyP** [comment]
Could removing duplicate post ids be added as a feature?

**Comment by DIGITALCRIMINAL** [comment]
I can't. It's tied to how the script works. You will end up downloading duplicate content instead.

**Comment by DIGITALCRIMINAL** [comment]
If you want to send me the metadata so I can take a look at it properly to see if there's actually anything wrong with it, other than that there's nothing else to do since it's working as intended.
