### ISSUE TITLE
Nothing to scrape (not sure why)

### ISSUE THREAD

**Issue by zetaomegagon** [DIGITALCRIMINAL/OnlyFans#572]
I keep getting this message since updating to current Master:

```
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Now exiting.
```
- I don't currently have any data in my `.sites` directory.
- Additionally, after a run, I'm logged out of my account in my web browser.
- I've tried several config options disableing auto choices (such as ` "auto_choice": "a"` v. ` "auto_choice": ""`) and have even blown out my `config.json` to use config defaults.
- Tried `"overwrite_files": true` and `"overwrite_files": false`, with no change.

Does anyone have any suggestions I can try?

Here's my current config for OF:

```
{
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "webhooks": [],
    "exit_on_completion": true,
    "infinite_loop": false,
    "loop_timeout": "0",
    "socks5_proxy": [],
    "cert": "",
    "random_string": "54d7babc2df111ebae6bf0189849c53e",
    "global_user_agent": ""
  },
  "supported": {
    "onlyfans": {
      "auth": {
        "username": "redacted",
        "auth_id": "redacted",
        "auth_hash": "",
        "auth_uniq_": "",
        "sess": "redacted",
        "app_token": "redacted",
        "user_agent": "redacted",
        "support_2fa": true
      },
      "settings": {
        "auto_choice": "a",
        "auto_scrape_names": true,
        "auto_scrape_apis": true,
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{username}/{api_type}/{value}/{date}/{post_id}/{media_type}",
        "filename_format": "{date}_{post_id}_{media_id}_{filename}_{username}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{username}/Metadata",
        "text_length": 255,
        "overwrite_files": true,
        "date_format": "%m-%d-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "blacklist_name": "",
        "webhook": true
      },
      "extra_auth_settings": {
        "extra_auth": false,
        "choose_auth": false,
        "merge_auth": false
      }
    },
```

**Comment by DIGITALCRIMINAL** [comment]
Are you subscribed to anyone?

**Comment by zetaomegagon** [comment]
Yeah: `velvetvalerina` and `velvetvalie`

Adding on...
```

**Comment by zetaomegagon** [comment]
So I:

1. Unsubbed and re-subbed

2. Used the OnlyFans-Cookie-Helper

Which seemed to do the trick, though not sure if it was the combo or not. My `auth:{}` object looked like it had the same info as what the cookie helper provided, but I didn't verify strictly (just by eye).

Anyway: 🤷‍♀️

Thanks for responding. Closing.

**Comment by buttseckskarms** [comment]
I have the same issue.

Version 6.0
Python 3.9.1
Default config.json

I can use an old version of the software (when auth was still in settings) and rip everything fine. Using the same auth block in 6.0,  authenticate with no issues, and get the nothing to scrape response.

**Comment by zetaomegagon** [comment]
@buttseckskarms yeah, I had it happen to me again too. Sorry, forgot to compare my cookie data from the cookie helper to my config.

IIRC, my session string changed 🤷 

I'll do better next time.

**Comment by zetaomegagon** [comment]
Just found that I was logged out of my OF account in browser-- so I ran the scraper, and got the message again.

I'm p-sure that some ablock extension I've got is clearing my session deets.

**Comment by DIGITALCRIMINAL** [comment]
What extension are you using

**Comment by zetaomegagon** [comment]
Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 10.15.7 (Build 19H114)

- uBlock Origin
- uMatrix

Both allow you to clear cookies at custom intervals. Dunno yet if I have that setup.

**Comment by zetaomegagon** [comment]
Working now, so likely can't check till 6PM ET

**Comment by DIGITALCRIMINAL** [comment]
Oh nvm, I thought it was an OnlyFans extension. Most likely uMatrix because I use uBlock and I don't get booted out.

**Comment by zetaomegagon** [comment]
Word. I mostly posted back here for @buttseckskarms.

**Comment by zetaomegagon** [comment]
For posterity, here is the setting that I think was causing my session to reset...1440 minutes (7 days) feels about right.

<img width="569" alt="Screen Shot 2020-12-17 at 8 42 25 PM" src="https://user-images.githubusercontent.com/24728279/102564221-f5f3a180-40a8-11eb-946b-c0872bef1835.png">

**Comment by zetaomegagon** [comment]
Just an update. It happened again w/o uMatrix enabled. That said, I'm still not certain if it _wasn't_ uMatrix.

I wasn't logged out this time, the scraper just ran and did nothing.

I remembered to compare my cookie info this time:

```
OG
"sess": "vv5####################a5e"

New
"sess": "le4####################m5r",
```

I'm going to continue to monitor with all adblock disabled to see if it happens again, and if not, I'll set a shorter timer on uMatrix and test with it enabled.

Hope to remember to update :/
