### ISSUE TITLE
4chan not enabled

### ISSUE THREAD

**Issue by Jrjy3** [DIGITALCRIMINAL/OnlyFans#574]
After filling out which boards I would like to scrape and running the script, the 4chan option is not available. It seems like it might need an auth to detect 4chan, but no auth is needed to access the content.

![image](https://user-images.githubusercontent.com/1194768/101273336-fbbcbf00-3759-11eb-9739-2f412ccd177a.png)

**Comment by DIGITALCRIMINAL** [comment]
I disabled all modules except OF
