### ISSUE TITLE
REQUEST admireme.vip and www.manyvids.com and snapchat and onlyfans downloader

### ISSUE THREAD

**Issue by markte22** [DIGITALCRIMINAL/OnlyFans#575]
hi can anyone here make me a tool/software to download from theses sites
admireme.vip and www.manyvids.com and snapchat and onlyfans.com
this is what i need

a software/ a tool that will download all contents from this site admireme.vip a software that will download all contents from any person that is on that site

a software/ a tool that will download all contents from www.manyvids.com of any person that is on it

a software/ a tool that will download all contents from snapchat that will download all snapchat contents from a username of a person like puting in the persons username and the software downloads all there contents

and can anyone make me a software/ tool  that will download all onlyfans content of any person and also downloads the paid stuff in the messages
a software were you copy the persons onlyfans username and the software downloads all the persons contents everything the person has uploaded even the paid stuff in the messages

if anyone can make me a tool/ software to do this then i can buy someone a xbox or amazon giftcard
as payment and send it to a person when i get the software/tool i will also send the recipet first as proof that it is a real giftcard bought of amazon site then a person sends ,e the software/tools then i would send the person a amazon or xbox giftcard i can buy someone a $25 dollars amazon or xbox giftcard if anyone can help me with this then just reply to it

also DIGITALCRIMINAL if you can do this and can you make a private tool/ private software portable so i dont have to install it
i also want it were it bypasses the payment on theses sites so a tool/software to download from theses sites above and is portable aswell so i dont have to install it i also dont want to use the python software so if it can be done so it does not need python software were the software/tool  just pops up 

i want to download all contents from theses sites above and need you to make me a hack tool if you can do that for me i would pay you with a $25 dollars amazon or xbox giftcard or if you have a ps3 or ps4 or xbox 360 console i could upload some of my games that i have for you and give you the link to download my games or you could accept the giftcard 

i really want you to make this software/ tool for me if you can please do that would be great

**Comment by markte22** [comment]
also DIGITALCRIMINAL if you can do this and can you make a private tool/ private software portable to download all contents from theses sites above i would pay you with a $25 dollars amazon or xbox giftcard or if you have a ps3 or ps4 or xbox 360 console i could upload some of my games that i have for you and give you the link to download my games or you could accept the giftcard i really want you to make this software/ tool for me if you can please that would be great

**Comment by DIGITALCRIMINAL** [comment]
Lmao, you already posted this on HackForums... stop...

No clown would bypass a company's payment system that's worth millions of $ for a PS3 game or even $25. You have to be braindead to even ask that.
