### ISSUE TITLE
After 9.1 update get stuck for very long time on WARNING urllib3.connectionpool alerts

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#577]
I know you tell people to ignore this error, but I never got these before and now I get these for many accounts and it takes a very long time to go through some of the accounts. 

This is from kathleeneggleton but it happens to others, I think ones with many files.

Edit: So running her individually, this did not come up. Only when dling all accounts at once.

![image](https://user-images.githubusercontent.com/20603861/101413400-32a5e880-38b2-11eb-8264-2d1297e8624d.png)

**Comment by DIGITALCRIMINAL** [comment]
It's OF's side. Just ignore it and let the script do it's job.
