### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by masterisk** [DIGITALCRIMINAL/OnlyFans#580]
```
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "C:\OnlyFans-5.9.1\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\OnlyFans-5.9.1\helpers\main_helper.py", line 5, in <module>
    from classes.prepare_metadata import format_variables, prepare_metadata, prepare_reformat
  File "C:\OnlyFans-5.9.1\classes\prepare_metadata.py", line 217, in <module>
    class prepare_reformat(object):
  File "C:\OnlyFans-5.9.1\classes\prepare_metadata.py", line 251, in prepare_reformat
    def reformat(self, unformatted_list) -> list[str]:
TypeError: 'type' object is not subscriptable
```

This error occurs even with a clean fresh copy, on run of the latest version.

**Comment by paper9oll** [comment]
Same issue here, just downloaded and unzipped. Follow the instructions but got the same error when running `python start_ofd.py`

**Comment by paper9oll** [comment]
> 
> 
> ```
> Traceback (most recent call last):
>   File "start_ofd.py", line 2, in <module>
>     import tests.main_test as main_test
>   File "C:\OnlyFans-5.9.1\tests\main_test.py", line 4, in <module>
>     import helpers.main_helper as main_helper
>   File "C:\OnlyFans-5.9.1\helpers\main_helper.py", line 5, in <module>
>     from classes.prepare_metadata import format_variables, prepare_metadata, prepare_reformat
>   File "C:\OnlyFans-5.9.1\classes\prepare_metadata.py", line 217, in <module>
>     class prepare_reformat(object):
>   File "C:\OnlyFans-5.9.1\classes\prepare_metadata.py", line 251, in prepare_reformat
>     def reformat(self, unformatted_list) -> list[str]:
> TypeError: 'type' object is not subscriptable
> ```
> 
> This error occurs even with a clean fresh copy, on run of the latest version.

Update to Python 3.9, solved the issues
