### ISSUE TITLE
script is extremely slow / seems to hang

### ISSUE THREAD

**Issue by LunarPenguin** [DIGITALCRIMINAL/OnlyFans#581]
Over the last couple of updates the script seems extremely slow, and it gives the impression that the script is "stuck" or "hanging"

Due to some debugging on my own i have managed to narrow down the problem and its seems to have something to do with the reading / comparing / preparing of the metadata.

The same thing happens when the script is checking the paid content and the only thing to make it work again is deleting the metadata but then in a couple of days the same problem arises.

I have included some log files which show were the program "hangs" or how long it takes the program to complete execution.

For me execution time has gone from an average of around 5 - 10 minutes to around 20 - 60 minutes and sometimes even longer.

[debug_log.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5658868/debug_log.txt)
[debug_log2.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5658870/debug_log2.txt)
[debug_log3.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5658871/debug_log3.txt)
[debug_log4.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5658872/debug_log4.txt)
[debug_log5.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5658873/debug_log5.txt)
[debug_log6.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5658874/debug_log6.txt)
[debug_log7.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5658875/debug_log7.txt)

**Comment by DIGITALCRIMINAL** [comment]
What is your filename

**Comment by LunarPenguin** [comment]
My ```file_directory_format``` and ```filename_format``` are the following:
```
"file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
"filename_format": "{filename}.{ext}",
```

**Comment by DIGITALCRIMINAL** [comment]
Okay.

It's not a good idea to delete metadata since the script will now have to redownload every file.

I've made a new commit that will help you accurately identify if the script hangs on processing metadata or not and let me know if it does...

**Comment by jp1151419** [comment]
> the script will now have to redownload every file.

Does that mean that by deleted my metadata in an attempt to fix downloading errors I have brought the scraper to duplicate everything?

**Comment by DIGITALCRIMINAL** [comment]
> > the script will now have to redownload every file.
> 
> Does that mean that by deleted my metadata in an attempt to fix downloading errors I have brought the scraper to duplicate everything?

If you have overwrite set to True then it would; yes

**Comment by jp1151419** [comment]
> If you have overwrite set to True then it would; yes

I do not, thanks. Wasn't sure if the script was able to recognize files it had already downloaded if the associated Metadata folder is deleted. Thanks!

**Comment by LunarPenguin** [comment]
> I've made a new commit that will help you accurately identify if the script hangs on processing metadata or not and let me know if it does...

It seems it indeed "hangs" during the metadata processing.
I've got a hunch that it has something to do with the loading of the metadata files as those are quiet big.

my biggest metadata file is a ```posts.json``` file which is 327MB big and 9483496 lines long

Other metadata files range from 2kb to around 30MB.

The ```posts.json``` seems to have a lot of duplicate items with different post_ids. i read in another issue that this is normal behavior which is ok but seems to lead to massive metadata files

[debug_log.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667913/debug_log.txt)
[debug_log2.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667910/debug_log2.txt)
[debug_log3.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667911/debug_log3.txt)
[debug_log4.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667912/debug_log4.txt)

**Comment by DIGITALCRIMINAL** [comment]
> > If you have overwrite set to True then it would; yes
> 
> I do not, thanks. Wasn't sure if the script was able to recognize files it had already downloaded if the associated Metadata folder is deleted. Thanks!

If overwrite is set to True, it will search files that have the same filename and size and skip them, but if the size parameter doesn't match up, it will overwrite the file, and if the file has a different filename it will download the same file which would lead to duplicates

If overwrite is set to False, it will check the metadata if the file has already been downloaded, and will skip them reguardless if it exists or not.

**Comment by DIGITALCRIMINAL** [comment]
> > I've made a new commit that will help you accurately identify if the script hangs on processing metadata or not and let me know if it does...
> 
> It seems it indeed "hangs" during the metadata processing.
> I've got a hunch that it has something to do with the loading of the metadata files as those are quiet big.
> 
> my biggest metadata file is a `posts.json` file which is 327MB big and 9483496 lines long
> 
> Other metadata files range from 2kb to around 30MB.
> 
> The `posts.json` seems to have a lot of duplicate items with different post_ids. i read in another issue that this is normal behavior which is ok but seems to lead to massive metadata files
> 
> [debug_log.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667913/debug_log.txt)
> [debug_log2.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667910/debug_log2.txt)
> [debug_log3.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667911/debug_log3.txt)
> [debug_log4.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667912/debug_log4.txt)

Ahh okay, I'm changing the metadata format, it will backwards compatable with all formats. It will be easier to read and have less chance of duplicate posts. Should be a bit faster at processing the metadata as well since I'm going to multithread it.

**Comment by DarkDownloader** [comment]
> > > I've made a new commit that will help you accurately identify if the script hangs on processing metadata or not and let me know if it does...
> > 
> > 
> > It seems it indeed "hangs" during the metadata processing.
> > I've got a hunch that it has something to do with the loading of the metadata files as those are quiet big.
> > my biggest metadata file is a `posts.json` file which is 327MB big and 9483496 lines long
> > Other metadata files range from 2kb to around 30MB.
> > The `posts.json` seems to have a lot of duplicate items with different post_ids. i read in another issue that this is normal behavior which is ok but seems to lead to massive metadata files
> > [debug_log.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667913/debug_log.txt)
> > [debug_log2.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667910/debug_log2.txt)
> > [debug_log3.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667911/debug_log3.txt)
> > [debug_log4.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5667912/debug_log4.txt)
> 
> Ahh okay, I'm changing the metadata format, it will backwards compatable with all formats. It will be easier to read and have less chance of duplicate posts. Should be a bit faster at processing the metadata as well since I'm going to multithread it.

This is really good to hear, as I am having the same issues as above.

**Comment by DIGITALCRIMINAL** [comment]
Turns out the text key was being duplicated because I didn't check for it.

I will be releasing a commit within this hour.

**Comment by DIGITALCRIMINAL** [comment]
Done

**Comment by LunarPenguin** [comment]
> Done

Unfortunately i am now getting the following error when it tries to scrape the paid content. 

```Auth (V1) Attempt 1/10
Welcome LunarPenguin
Scraping Paid Content
Scraping - raeriley | 0 / 6
Scraping [photo]. Should take less than a minute.
2020-12-11 18:03:20,462 ERROR errors tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "C:\Users\username\Documents\Development\[Map] Other\Scraping\OF\OnlyFans\datascraper\main_datascraper.py", line 122, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "C:\Users\username\Documents\Development\[Map] Other\Scraping\OF\OnlyFans\modules\onlyfans.py", line 332, in paid_content_scraper
    new_metadata = media_scraper(paid_content, api,
  File "C:\Users\username\Documents\Development\[Map] Other\Scraping\OF\OnlyFans\modules\onlyfans.py", line 837, in media_scraper
    date = media_api["postedAt"] if "postedAt" in media_api else media_api["createdAt"]
TypeError: tuple indices must be integers or slices, not str````

**Comment by DIGITALCRIMINAL** [comment]
It's fixed now.

**Comment by LunarPenguin** [comment]
> It's fixed now.

Everything now indeed works perfectly again. Thanks!

fyi. the ```posts.json``` metadata file i talked about earlier has gone from 327MB to a bit less than 2MB. That's Nice!
