### ISSUE TITLE
script hangs on 'missing X posts'

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#585]
I'm creating this as a new issue, it doesn't seem related to the other active issues posted.

This has been happening with the last 2-3 versions and it doesn't seem to happen systematically with the same "content creators" ![image](https://user-images.githubusercontent.com/58760178/101534007-8f61db80-3964-11eb-8306-4a95bc8effe5.png)

I thought deleted all my metadata might help but clearly it hasn't. 

Any ideas? It seems to always stall around scrape attempt # 16-18

**Comment by James-MF-Thomas** [comment]
Having the same issue

**Comment by DIGITALCRIMINAL** [comment]
It's on OF's side, but the missing x amount of posts seems to be increasing which it should not.

**Comment by jp1151419** [comment]
is there a way to implement a "skip missing posts if more than X?" I haven't been able to rip 0=all in a couple days because of this. It stalls on multiple models

**Comment by DIGITALCRIMINAL** [comment]
> is there a way to implement a "skip missing posts if more than X?" I haven't been able to rip 0=all in a couple days because of this. It stalls on multiple models

I already implemented that, it's out of 100. It's on OF's side that's causing the stutter.
