### ISSUE TITLE
Script can't instal visual studio basic when installing pip install command

### ISSUE THREAD

**Issue by Zoroxoroz** [DIGITALCRIMINAL/OnlyFans#586]
when i type in the command pip install -r requirements.txt i get the error that visual studio didn't install. I installed it manually and still can't get the script to work.

Using the latest version with py9.

**Comment by jp1151419** [comment]
did you install the c+/c++ modules?

**Comment by Zoroxoroz** [comment]
thanks for the suggestion, i installed it and the VSB error is gone. But now when i enter start_ofd.py VSB pops out instead of creating the .settings folder
