### ISSUE TITLE
Filled out everything perfectly according to the video but when i go to scrape, it tells me there is nothing to scrape.

### ISSUE THREAD

**Issue by Shodow8196** [DIGITALCRIMINAL/OnlyFans#587]

**Comment by DIGITALCRIMINAL** [comment]
Okay, are you subscribed to anyone?

**Comment by NathanIfinity** [comment]
same error : 

Session IP: xxxxxxxxxx

Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.

and I have about 51 subs?? 
worked fine yesterday morning during my daily scrape

thnks

**Comment by LunarPenguin** [comment]
Make sure you have your credentials filled in correctly. as i can see from the log it tries to authenticate but fails to do so and that results in there being no models to scrape

**Comment by NathanIfinity** [comment]
Yeah that's what I thought too even though it worked yesterday, so I went to validate, and I saw my (sess) had changed (not sure why) but all other info were still the same,  so i made the modification, but it's still giving me the same error.

**Comment by LunarPenguin** [comment]
i found from my experience that it sometimes is very finicky to get it working but once it starts working again it usually keeps working until my browser updates and i have to change the User-Agent.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, I wouldn't know how to fix this unless I have your login details
