### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by user15503** [DIGITALCRIMINAL/OnlyFans#59]
![Bildschirmfoto 2019-11-03 um 16 39 18](https://user-images.githubusercontent.com/57323674/68087718-8b59b500-fe58-11e9-8371-4d8f764018b9.png)

No files were scrapped. Running Python 3.7.

**Comment by DIGITALCRIMINAL** [comment]
It says you're using Python 3.6.
