### ISSUE TITLE
Exception in paid content scraper - TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by herefromrdt** [DIGITALCRIMINAL/OnlyFans#590]
Stack Trace:
Traceback (most recent call last):
  File "G:\OnlyFans\datascraper\main_datascraper.py", line 122, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "G:\OnlyFans\modules\onlyfans.py", line 332, in paid_content_scraper
    new_metadata = media_scraper(paid_content, api,
  File "G:\OnlyFans\modules\onlyfans.py", line 837, in media_scraper
    date = media_api["postedAt"] if "postedAt" in media_api else media_api["createdAt"]
TypeError: tuple indices must be integers or slices, not str

I ran it again with a try-catch block around that line, and printed the value of media_api. When the error is thrown, it is the following tuple, instead of a dictionary
('Posts', [])

**Comment by DarkDownloader** [comment]
I have the same issue after updating to the latest version.

**NOTE: I did not allow it to use a new settings file, I used my old one from last release.**

**Comment by stolli83** [comment]
Same here after a fresh cloneing of the repo.

**Comment by andreymukha** [comment]
I have this problem too

**Comment by wanyek43** [comment]
Same here. Just pulled the latest commit and instantly had this error. I also used the config file from the last commit I pulled of 5.9.1 instead of the new one it generated.

**Comment by DIGITALCRIMINAL** [comment]
If you wanna use the program now, just disable paid content in the jobs, in the config; I'll fix it

**Comment by andreymukha** [comment]
> 
> 
> If you wanna use the program now, just disable paid content in the jobs, in the config; I'll fix it

So the paid content won't download?

**Comment by DIGITALCRIMINAL** [comment]
@andreymukha There are 2 jobs, download paid content and download models. When downloading models, the script will still download paid content.

**Comment by wanyek43** [comment]
> @andreymukha There are 2 jobs, download paid content and download models. When downloading models, the script will still download paid content, for now, we can just bypass downloading paid content exclusively.

So does that mean if you have both options set to true, it will process paid content twice? If so, is it okay to have the paid job set to false going forward? The description of those options doesn't include that bit of info.

**Comment by DIGITALCRIMINAL** [comment]
> @DIGITALCRIMINAL
> 
> > @andreymukha There are 2 jobs, download paid content and download models. When downloading models, the script will still download paid content, for now, we can just bypass downloading paid content exclusively.
> 
> So does that mean if you have both options set to true, it will process paid content twice? If so, is it okay to have the paid job set to false going forward? The description of those options doesn't include that bit of info.

No. You still access paid content even if you're not subscribed to the user. The script will check if you've already downloaded the media anyway, so there will be no dupes.

**Comment by DIGITALCRIMINAL** [comment]
I made a commit, it should be fixed.

**Comment by stolli83** [comment]
> I made a commit, it should be fixed.

Thank you man, it works perfect!
