### ISSUE TITLE
Filter by date?

### ISSUE THREAD

**Issue by flamingghost** [DIGITALCRIMINAL/OnlyFans#594]
(I believe this is a feature request, as I can't see a switch for it, but if not apologies!)

Could you implement a 'download posts newer than 10/12/20' etc option?

I'm basically looking to archive off a load of content, as my drives hitting 4TB, but the script will currently re-download the archived-off data.

If this isn't possible, could anyone suggest a work around? Looking to shift things up to some encrypted cloud storage with rclone.

**Comment by LunarPenguin** [comment]
I believe if you set ```overwrite_files``` to ```false``` it should use the metadata to determine if it has already downloaded the data and not download it again. allowing for archiving of the data

**Comment by zetaomegagon** [comment]
☝️ what @LunarPenguin said. This is how I have my config.jason setup.

```
"onlyfans": {
      "auth": {
        "username": "redacted",
        "auth_id": "redacted",
        "auth_hash": "",
        "auth_uniq_": "",
        "sess": "redacted",
        "app_token": "redacted",
        "user_agent": "redacted",
        "support_2fa": true
      },
      "settings": {
        "auto_choice": "a",
        "auto_scrape_names": true,
        "auto_scrape_apis": true,
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{username}/{api_type}/{value}/{media_type}/{date}/{post_id}",
        "filename_format": "{date}_{username}_{post_id}_{media_id}_{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{username}/Metadata",
        "text_length": 255,
        "overwrite_files": false,   <------------------- [ Here's what you are looking for ]
        "date_format": "%m-%d-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "blacklist_name": "",
        "webhook": true
      },
      "extra_auth_settings": {
        "extra_auth": false,
        "choose_auth": false,
        "merge_auth": false
      }
    }
```

**Comment by zetaomegagon** [comment]
Too add on here-- I know this method to work for media, but it seems that there is an API limitation (?) when it comes to message metadata, so there will be duplicate messages. ([ref](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/571))

**Comment by DIGITALCRIMINAL** [comment]
I'm adding support to separate metadata and content in the near future.
