### ISSUE TITLE
Not grabbing all OF posts

### ISSUE THREAD

**Issue by yeenoghu** [DIGITALCRIMINAL/OnlyFans#6]
Hi, thanks for this script! I ran it earlier but it looks like it isn't scraping all the content for a given user. The profile shows 585 photos and 157 videos, but the script only downloaded 133 photos and 100 videos. Any idea what the issue could be?

**Comment by DIGITALCRIMINAL** [comment]
Which account are you trying to grab?

**Comment by yeenoghu** [comment]
The account is maryelizabethmcq

**Comment by DIGITALCRIMINAL** [comment]
> maryelizabethmcq

She deleted her account bruh

**Comment by yeenoghu** [comment]
Ah she just changed her account name to missmarymcq in the last day or so.

**Comment by DIGITALCRIMINAL** [comment]
> Ah she just changed her account name to missmarymcq in the last day or so.

Ah okay, found the problem. They've limited posts by 100. The limit used to be 500+ from the api and I currently don't have a system to grab the next 100 posts, so I'll update the script by tomorrow. It'll porbably be in a few hours though.

**Comment by DIGITALCRIMINAL** [comment]
> Ah she just changed her account name to missmarymcq in the last day or so.

Updated OnlyFans.py
