### ISSUE TITLE
im new to this sorry if this is a noob question. I installed python 3.8 but running the install command says pip is not recognised.

### ISSUE THREAD

**Issue by deashtx** [DIGITALCRIMINAL/OnlyFans#60]
![Annotation 2019-11-06 055104](https://user-images.githubusercontent.com/57429768/68271820-c4ad4300-0059-11ea-95a5-639aeaf2b3e7.png)
![Annotation 2019-11-06 0551042](https://user-images.githubusercontent.com/57429768/68271823-c8d96080-0059-11ea-8f2b-bd7faf86d323.png)

**Comment by dilemmax** [comment]
You need to install PIP before you can run it in cmd.

Go here to find out how to install PIP

https://phoenixnap.com/kb/install-pip-windows

**Comment by DIGITALCRIMINAL** [comment]
`python get-pip.py`

Run that command in CMD

**Comment by deashtx** [comment]
ended up moving the folder to C drive and it worked... I wonder why?

**Comment by DIGITALCRIMINAL** [comment]
@deashtx did you run the command I suggested?
