### ISSUE TITLE
Text Files

### ISSUE THREAD

**Issue by Astrofluke** [DIGITALCRIMINAL/OnlyFans#600]
These aren't showing in my text file; 

{"auth_id":"your_auth_id"}
{"sess":"your_sess_token"}
{"user-agent":"your_user-agent"}

**Comment by DIGITALCRIMINAL** [comment]
It's here.
`.profiles/default/auth.json`

**Comment by Astrofluke** [comment]
I'm following the tutorial step by step, but this is what my text file looks like. I don't have the "username", "auth_ID", "sess". Do I have to manually add this to the text file?

  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "",
        "auto_scrape_names": false,
        "auto_choice": "",
        "auto_scrape_apis": true,
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "text_length": 255,
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "blacklist_name": "",
        "webhook": true
