### ISSUE TITLE
All accounts downloaded

### ISSUE THREAD

**Issue by 22none** [DIGITALCRIMINAL/OnlyFans#604]
After selecting which account I wanted to download content from and choosing all content 'a' the software proceeded to download all the content from every account. I can look through the code but I was wondering if this was a known issue.

**Comment by 22none** [comment]
Actually this might be fine it downloaded only the messages of all the accounts but only the posts of the account I selected. Which is manageable I assumed I would need to download every account when I followed a new account but it seems it might just be the messages it will run through again.

**Comment by DIGITALCRIMINAL** [comment]
Your config is working as intended
