### ISSUE TITLE
auth.json doesn't exist (using docker)

### ISSUE THREAD

**Issue by jo45** [DIGITALCRIMINAL/OnlyFans#606]
Everything worked fine a few days ago.
Now it doesn't, so I decided to update.
But no .profiles directory is generated, so I don't know where to put auth.json or what to write inside.
Tried different location/content but none seems to work and the only message I get is: user_agent required for: default
. Any help ?
Used latest release as of 12/17 15h GMT+1.

**Comment by jo45** [comment]
I'm a total noob to docker so I guess I forget to add "-v ${PWD}/.profiles:/usr/src/app/.profiles" to the docker command.
I tried but it still doesn't change anything.
BTW I'm on debian 10, and used docker because installing concurrent python3.9 on debian 10 is a pain.

**Comment by jo45** [comment]
So, after starting the docker instance with the right parameters, .profiles/OnlyFans/default/auth.json appeared.
Sorry for being that noob.
If I can contribute from that, you could add the "-v ${PWD}/.profiles:/usr/src/app/.profiles" parameter to the docker section of the README.
Sorry for the disturbance.

**Comment by DIGITALCRIMINAL** [comment]
Have you tried adding ".profile" to the docker ignore file?

https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/.dockerignore

**Comment by DIGITALCRIMINAL** [comment]
Done; thanks.
