### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#607]
Running latest commit and I'm seeing this issue

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 153, in start_datascraper
    x = main_helper.process_names(
  File "C:\Users\user\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 451, in process_names
    names = choose_option(
  File "C:\Users\user\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 435, in choose_option
    values = auto_scrape_names.split(",")
AttributeError: 'bool' object has no attribute 'split'

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit.

**Comment by ChillyP** [comment]
It’s partly working. It scrapes paid content ok. When the script gets to the scrape subscriptions part it says there is nothing new to scrape?

**Comment by DIGITALCRIMINAL** [comment]
I don't know how to fix that since I don't have your account credentials

**Comment by ChillyP** [comment]
I've had to revert back to a previous commit and its working again now.

**Comment by DoublePipe** [comment]
I'm seeing this too. Authentication is successful with the latest commit and it is able to print the full list of profiles I'm subscribed to, but the scraping-stage finishes instantly without detecting any content. This is a redacted version of the output:

```
Names: Username = username  |  0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome Foobar | u12345678
Scraping Paid Content
Scraping - profileA | 0 / 3
Scraping - profileB | 1 / 3
Scraping - profileC | 2 / 3
Scraping Subscriptions
Names: Username = username  |  0 = All | 1 = profileA | 2 = profileB | 3 = profileC
There's nothing to scrape.
Archive Completed in 0.16 Minutes
Now exiting.
```

Let me know if there are other details I can provide that would be helpful for debugging.

**Comment by DIGITALCRIMINAL** [comment]
If you want a quick fix, set auto_scrape_names to False

**Comment by DIGITALCRIMINAL** [comment]
Thanks, use the latest commit
