### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#609]
![Screen Shot 2020-12-18 at 12 12 55 AM](https://user-images.githubusercontent.com/47627618/102581427-2b5ab800-40c6-11eb-8d0c-e0332c60abc3.png)
![Screen Shot 2020-12-18 at 12 14 26 AM](https://user-images.githubusercontent.com/47627618/102581429-2c8be500-40c6-11eb-8431-4b1e086453f9.png)

**Comment by DIGITALCRIMINAL** [comment]
Fix the metadata that's broken or delete it
