### ISSUE TITLE
File name format adds information/characters I don't want

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#61]
config.json: "file_name_format": "[{date}] {file_name}.{ext}",

Yet my file names look like this:

[2019-09-23] 3840x2880_7496eff286d4159abb92a248054c4257802759

**Comment by DIGITALCRIMINAL** [comment]
{file_name} is equal to 3840x2880_7496eff286d4159abb92a248054c4257802759

**Comment by avekifes** [comment]
The image dimensions aren't supposed to be part of the file name, though. Or did OnlyFans change that?

**Comment by DIGITALCRIMINAL** [comment]
Onlyfans put it in there

**Comment by avekifes** [comment]
You're right. I thought I'd have to re-download everything again, but luckily, the new file name structure has only been applied to newer uploads.
