### ISSUE TITLE
Renaming files operation slow

### ISSUE THREAD

**Issue by arlateedaina** [DIGITALCRIMINAL/OnlyFans#610]
I upgraded to v6.0 and I'm seeing `Renaming files.` being printed and it just takes a while to progress to the next operation. 

    Found: Posts
    Scraping [photo]. Should take less than a minute.
    Scraping [photo]. Should take less than a minute.
    Scraping [photo]. Should take less than a minute.
    Scraping [photo]. Should take less than a minute.
    Scraping [video | stream | gif]. Should take less than a minute.
    Scraping [audio]. Should take less than a minute.
    Scraping [text]. Should take less than a minute.
    Scraping [photo]. Should take less than a minute.
    Scraping [video | stream | gif]. Should take less than a minute.
    Scraping [audio]. Should take less than a minute.
    Scraping [text]. Should take less than a minute.
    Scraping [video | stream | gif]. Should take less than a minute.
    Scraping [video | stream | gif]. Should take less than a minute.
    Scraping [video | stream | gif]. Should take less than a minute.
    Scraping [audio]. Should take less than a minute.
    Scraping [text]. Should take less than a minute.
    Scraping [audio]. Should take less than a minute.
    Scraping [audio]. Should take less than a minute.
    Scraping [text]. Should take less than a minute.
    Scraping [text]. Should take less than a minute.
    Processing metadata.
    Merging new metadata with legacy metadata.
    Merging new metadata with old metadata.
    Renaming files.

I also do see the 'Merging' operations above and I'm not sure why this would happen on every run. I'm assuming something changed including naming scheme and that's why this is happening, but I'm not sure why it would happen on each run.

Is there something that can be done? Not sure where to start digging into this one.

**Comment by DIGITALCRIMINAL** [comment]
It's working as intended.
