### ISSUE TITLE
onlyfans question

### ISSUE THREAD

**Issue by markte22** [DIGITALCRIMINAL/OnlyFans#613]
hi  DIGITALCRIMINAL could you make this software for windows cos making it for python i dont have this software could you make this 
 DIGITALCRIMINAL /OnlyFans for windows aswell and could you make a broswer tool for google chrome and firefox it is just some ideas for you cos i dont have python software so could you make this for windows where it does not need python software installed
and could you please do this for google chrome and firefox broswer and make a onlyfans add on tool that you put on your broswer and it downloads onlyfans contents could you please do that cos the python software with this tool it is shit as hell it never works friends of mine have tried it this with python installed and it never works for my friends i have never tried this with python it is just too messy and probelms if a windows one was made that would be a lot better for everyone i think also you could make a broswer tool which you add to your browser like google chrome and firefox broswer and it downloads onlyfans contents

**Comment by DIGITALCRIMINAL** [comment]
I have no plans to make a C# scraper.
Python is fine and it's working.
There's already plenty of web extensions out there that will download the content.

**Comment by ProjektPremium** [comment]
https://github.com/Hashirama/OFDL

Then use this one.
