### ISSUE TITLE
Keep stuck downloading

### ISSUE THREAD

**Issue by of-endless** [DIGITALCRIMINAL/OnlyFans#614]
Hi, big fan of your work :)
When i select download 'x' it starts downloading pay files from 'y' and get stuck after 1 or 2 files. If I set pay = false, it still gets stuck after downloaded 3 or 4 files. I dont change nothing more than pay = false, ans start the scrap from scratch.

Ty

**Comment by markte22** [comment]
HI of-endless does it download the onlyfans contents for free you said it downloads the pay files do you have to pay for the contents what i am after is a way to bypass the payment method or trick the website to thinking it has a card added there might be a way to trick it on the site if you click f12 on the keybord on windows it brings up the developer tools there might be a way to do that or something that might work or if someone was able to get the girls onlyfans logins that would be even better for everyone cos then you would be able to download all the contents main page and paywall contents in the messages the lot of any girl then

**Comment by DIGITALCRIMINAL** [comment]
@of-endless how long does it get stuck for

**Comment by of-endless** [comment]
the most time I waited is 10 minutes.

**Comment by DIGITALCRIMINAL** [comment]
Just let the script run

**Comment by of-endless** [comment]
Ok, I gonna give a try, say u what happens tomorrow

**Comment by of-endless** [comment]
I wait 1 hour, and nothing. The script its not downloading, the space used in the hdd keep constant.

**Comment by DIGITALCRIMINAL** [comment]
What is your filename format?

**Comment by of-endless** [comment]
I think by default. I didn't change anything

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit

**Comment by of-endless** [comment]
I still have problems :/, downloaded 4 pics and stop

**Comment by DIGITALCRIMINAL** [comment]
> I still have problems :/, downloaded 4 pics and stop

I can't do anything unless I have access to your account, sorry.

**Comment by DIGITALCRIMINAL** [comment]
@of-endless are you a creator on OnlyFans?

**Comment by of-endless** [comment]
Sorry for the delay. No, im not a creator :/
