### ISSUE TITLE
APIs Displaying Incorrectly

### ISSUE THREAD

**Issue by artyom2035** [DIGITALCRIMINAL/OnlyFans#615]
Using commit https://github.com/DIGITALCRIMINAL/OnlyFans/commit/099d5f915480b68926e7c001dfb431f997fc3c9b. With "auto_scrape_names": false & "auto_scrape_apis": false to scrape individual, accounts I see the following:

![image](https://user-images.githubusercontent.com/29996283/102725771-d9d94580-42de-11eb-9c0a-2e674dc312f2.png)

Edit: It also appears that the "autocomplete" username feature no longer works here either.  Although, typing the full name or using the number does work.

**Comment by artyom2035** [comment]
Has to do with this from modules/onlyfans.py:

```
        if "apis" == choice_type:
                if isinstance(api, SimpleNamespace):
                    name = getattr(api, "username", None)
                else:
                    if isinstance(api, start) or isinstance(api, create_subscription):
                        continue
                    name = api.get("api_type")
                string += f"{count} = name"
```

Displays correctly if I revert it to this from the previous commit:

```
        if "apis" == choice_type:
            names = f_list
            for api in f_list:
                  if hasattr(api, "username"):
                       name = api.username
                else:
                      name = api["api_type"]
                string += str(count)+" = "+name
```
![image](https://user-images.githubusercontent.com/29996283/102728182-db5f3980-42ef-11eb-8cce-1e94d2e15ed5.png)

**Comment by DIGITALCRIMINAL** [comment]
Lmao, forgot to add {name}. Thanks.
