### ISSUE TITLE
Enable storing configs outside of the codebase

### ISSUE THREAD

**Issue by dc824** [DIGITALCRIMINAL/OnlyFans#618]
Enable people to store configs outside of the codebase which is generally good practise.

Ideally you'd do a few things things.

1. Stop chdir during code run (enables storing config in pwd)
2. Have a hierarchy of config positions first one found wins
    - PWD (looking for .settings)
    - Homedir (probably looking for ~.of_setings so it's unique to the app)
    - Codebase (looking for .settings)

**Comment by DIGITALCRIMINAL** [comment]
Ehh maybe, but I really don't see the point tbh.
