### ISSUE TITLE
Where do I find the docker image?

### ISSUE THREAD

**Issue by alexander-paterson** [DIGITALCRIMINAL/OnlyFans#622]

**Comment by Blcksoda** [comment]
Hey ,
Heres a step by step guide for windows:

1. You download the Project 
2. You unzip the project
3. You open Powershell and cd into the project
4. You run the command
docker build -t only-fans . 
5.after that finished you run

docker run -it --rm --name onlyfans -v ${PWD}/.settings:/usr/src/app/.settings -v ${PWD}/.profiles:/usr/src/app/.profiles -v ${PWD}/.sites:/usr/src/app/.sites only-fans
6.You enjoy your dockerized OF downloader

and btw to create multiple instances of the downloader you just run 

docker run -it --rm --name onlyfans-<add a number here eg.1>-v ${PWD}/.settings:/usr/src/app/.settings -v ${PWD}/.profiles:/usr/src/app/.profiles -v ${PWD}/.sites:/usr/src/app/.sites only-fans


Excuse if the formatting is complete shit I'm on mobile

**Comment by DIGITALCRIMINAL** [comment]
@Blcksoda should have posted it in the discussions lol
