### ISSUE TITLE
when i type python start_ofd.py

### ISSUE THREAD

**Issue by kalesha666** [DIGITALCRIMINAL/OnlyFans#623]
when i type python start_ofd.py this  comand give to me a issues

traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
     import test.main_test as main_test
  File "/home/user/Desktop/OnlyFans-6.1.1/test/main_test.py", line 10
     python_version = f"{version_info.major}.{version_info.minor}"
SyntaxError: invalid syntax.

What should i do?

**Comment by DIGITALCRIMINAL** [comment]
Python 3.9
