### ISSUE TITLE
.profiles/OnlyFans and .profiles/onlyfans

### ISSUE THREAD

**Issue by whateverman91** [DIGITALCRIMINAL/OnlyFans#626]
When updating from 5.x to 6.x, it created both folders. My data by default was put in .profiles/onlyfans, but I got an error unless I updated .profiles/OnlyFans too

I assume you're developing on Windows which is case-insensitive, while I'm running this on Linux where the FS is case-sensitive.

**Comment by DIGITALCRIMINAL** [comment]
What was the error

**Comment by whateverman91** [comment]
```sh
root@6d91bb503553:~/OnlyFans# python3 start_ofd.py
Session IP: xxx.xxx.xxx.xxx

user_agent required for: default
```

**Comment by whateverman91** [comment]
The `auth.json` file was created in both folders. In the lowercased one, everything was there but the user agent, which I immediately filled (before the error above). The one in the OnlyFans folder (with uppercase) had just the skeleton.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, the lowercase one is the old folder and the uppercased one is what you're supposed to be using.

**Comment by DIGITALCRIMINAL** [comment]
Thanks, I'll keep in mind that Linux is case sensitive. I made a new commit that will tell people that auth.json has been created and it will show the exact filepath.
