### ISSUE TITLE
NameError: name 'scrape_all' is not defined

### ISSUE THREAD

**Issue by nkycldn** [DIGITALCRIMINAL/OnlyFans#63]
`Traceback (most recent call last):
  File "fans.py", line 83, in <module>
    if not scrape_all:
NameError: name 'scrape_all' is not defined`

Anyone else getting this error or have a fix?

**Comment by nkycldn** [comment]
Solved the issue by correct my user agent...now I have an access denied auth loop...

**Comment by DIGITALCRIMINAL** [comment]
Did you update your config?

**Comment by DIGITALCRIMINAL** [comment]
I don't know what fans.py is

**Comment by DIGITALCRIMINAL** [comment]
I'm putting out a new release
