### ISSUE TITLE
overwrite_file: false not working, script still deletes and re-downloads

### ISSUE THREAD

**Issue by ph6sor** [DIGITALCRIMINAL/OnlyFans#630]
Running commit 2077af7

I have my config.json set to `"overwrite_files": false` in every section, but on my last run of the script it still deleted all the previously downloaded posts and re-downloaded them. Am I misunderstanding this option?

```{
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "webhooks": [],
    "exit_on_completion": true,
    "infinite_loop": true,
    "loop_timeout": "0",
    "proxies": [],
    "cert": "",
    "random_string": "d9b9d340427e11eb9b7d406c8f2f7c9c"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "",
        "auto_scrape_names": true,
        "auto_choice": "a",
        "auto_scrape_apis": true,
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{username}/Metadata",
        "text_length": 255,
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "blacklist_name": "",
        "webhook": true
      }

**Comment by DIGITALCRIMINAL** [comment]
It's working as intended. Just let the script do its job.

**Comment by ph6sor** [comment]
?? can you explain what the expected behavior would be if I had overwrite_files set to true, then? You just merged my PR updating your documentation to explain that if overwrite_files is set true, the script is going to re-download content that already exists in the download location. Implying that if it's set false, the content **won't** be re-downloaded (which is what the original documentation said in the first place). From my perspective, this isn't behaving as expected which is why I asked if I was misunderstanding the option.

With overwrite_files set to false, I'd expect that re-running the script on the same set of subscriptions would do a delta and just download new or changed content, not clear the directory and redownload 10s of GBs of unchanged content that I already had.

**Comment by DIGITALCRIMINAL** [comment]
The only time overwrite = false doesn't matter is when you delete the metadata files.
