### ISSUE TITLE
Adding metadata to jpeg's exif?

### ISSUE THREAD

**Issue by Penacillin** [DIGITALCRIMINAL/OnlyFans#635]
Currently the `format_image` sets the file's modification date to the picture's date. Adding it to the jpeg metadata would be quite useful. Could make a PR for you if you'd like

**Comment by DIGITALCRIMINAL** [comment]
What's the difference or what would it achieve?

**Comment by Penacillin** [comment]
Most other software pick up image metadata from jpeg metadata, not file metadata. Media hosting sites like https://github.com/photoprism/photoprism or https://github.com/Piwigo/Piwigo are the main ones I'm looking at right now. 
Also file modification dates are a lot less stable, if you copy the file or move between filesystems its much easier to lose the timestamp than if it were in the jpeg data.

**Comment by hammerheaddf** [comment]
I haven't gone through the EXIF in images I downloaded, but I did notice something curious. Some images seem to keep the location info. When I uploaded them to Jottacloud, it automatically created location-based albums with several photos. So, I guess OF keeps some original metadata on the uploaded files.

**Comment by Penacillin** [comment]
Interesting, I haven't seen that in the exif I think.... But I've written a simple addition using piexif in my fork that I'm using. Can open a PR if you'd like.
