### ISSUE TITLE
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly (Failed UJSON)

### ISSUE THREAD

**Issue by Addest3** [DIGITALCRIMINAL/OnlyFans#638]
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly 

This error is coming up when trying to install the latest release. Any ideas? Updated all dependencies.

**Comment by DIGITALCRIMINAL** [comment]
I dunno, search the internet or just open the issue on the actual ujson repo.
