### ISSUE TITLE
It's a me thing, not a you thing

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#639]
I don't know I can't get any content to download, unless I go one by one for each model. "auto_scrape_names" and "0" (select all) selection return the same results:
![Screen Shot 2020-12-28 at 10 22 03 PM](https://user-images.githubusercontent.com/47627618/103259819-a93d7f80-4960-11eb-8ab4-9d04222e2afb.png)
 
current settings: 
![Screen Shot 2020-12-28 at 10 53 03 PM](https://user-images.githubusercontent.com/47627618/103259864-cd995c00-4960-11eb-80f8-e7826d2cf03b.png)
(I have tried deleting legacy metadata)

**Comment by DIGITALCRIMINAL** [comment]
Try auto_scrape_names = True

**Comment by James-MF-Thomas** [comment]
I have, it was set to false so I could grab content.

**Comment by James-MF-Thomas** [comment]
So, It finally started pulling media. 

I guess it cycles through the entire model list to update/merge all the metadata before pulling media. And this happens every time at the beginning of running start_ofd.py (Given I'm scraping close 400 contributors, that can take a while. ) 

If that is the case, could having the metadata merge at the begging of each contributor be practical?

**Comment by exsambo** [comment]
DIGITALCRIMINAL, I write you an eMail about an equal problem. I don't want to start a new issue because 2 of them were recently closed.

Regards,
exsambo

**Comment by Nostang3** [comment]
I can't get it to pull any names from onlyfans or download any content. It hasn't pulled anything since yesterday. Tried reverting to the previous version but the outcome is still the same. Tried letting it recreate the settings file. Tried auto_scrape with true or false. Here is the CLI output.  

```
Choose Profile
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit
```

I thought this might be the same issue but if it's not I can create a new issue for you. Let me know.

**Comment by DIGITALCRIMINAL** [comment]
I can't do anything unless I have access to the account, sorry.

**Comment by DIGITALCRIMINAL** [comment]
> I can't get it to pull any names from onlyfans or download any content. It hasn't pulled anything since yesterday. Tried reverting to the previous version but the outcome is still the same. Tried letting it recreate the settings file. Tried auto_scrape with true or false. Here is the CLI output.
> 
> ```
> Choose Profile
> Scraping Paid Content
> Scraping Subscriptions
> There's nothing to scrape.
> Archive Completed in 0.0 Minutes
> Pausing scraper for 0 seconds.
> Site: 0 = onlyfans | x = Exit
> ```
> 
> I thought this might be the same issue but if it's not I can create a new issue for you. Let me know.

I can't do anything unless I have access to the account's auth_details, sorry.

**Comment by Nostang3** [comment]
> I can't do anything unless I have access to the account's auth_details, sorry.
Are you saying that you are downloading things just fine from OF and that it might be an account specific thing with me and that's why you would need my specific account details to troubleshoot?

**Comment by DIGITALCRIMINAL** [comment]
> > I can't do anything unless I have access to the account's auth_details, sorry.
> 
> Are you saying that you are downloading things just fine from OF and that it might be an account specific thing with me and that's why you would need my specific account details to troubleshoot?

Unfortunately yes, but OF has been going down randomly. Sometimes the only API we get posts from goes and, but the API we get messages from stays up. It's should be on their side.

Clear your log in sessions, logout then login again, and update your cookies.

**Comment by Nostang3** [comment]
> Unfortunately yes, but OF has been going down randomly. Sometimes the only API we get posts from goes and, but the API we get messages from stays up. It's should be on their side.
> 
> Clear your log in sessions, logout then login again, and update your cookies.

Alright, just checking. I logged out of OF, cleared browser cache & cookies, logged back in, then updated the auth.json file with the new info, checked the user_agent, no errors in log. Is there anything I need to clear/delete for the script?

Since this stopped grabbing right when OF glitched out yesterday, and guess I'm in a wait and see situation. Could I be

**Comment by DIGITALCRIMINAL** [comment]
> > Unfortunately yes, but OF has been going down randomly. Sometimes the only API we get posts from goes and, but the API we get messages from stays up. It's should be on their side.
> > Clear your log in sessions, logout then login again, and update your cookies.
> 
> Alright, just checking. I logged out of OF, cleared browser cache & cookies, logged back in, then updated the auth.json file with the new info, checked the user_agent, no errors in log. Is there anything I need to clear/delete for the script?
> 
> Since this stopped grabbing right when OF glitched out yesterday, and guess I'm in a wait and see situation. Could I be

Make sure it's active in auth

**Comment by Nostang3** [comment]
Interesting. That worked. It was set to false. Is it coded to go inactive when OF glitched?

**Comment by DIGITALCRIMINAL** [comment]
> Interesting. That worked. It was set to false. Is it coded to go inactive when OF glitched?

Yes
