### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#64]
What's this about?

> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 425, in _error_catcher
>     yield
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 507, in read
>     data = self._fp.read(amt) if not fp_closed else b""
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 454, in read
>     n = self.readinto(b)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 498, in readinto
>     n = self.fp.readinto(b)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
>     return self._sock.recv_into(b)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
>     return self.read(nbytes, buffer)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
>     return self._sslobj.read(len, buffer)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 750, in generate
>     for chunk in self.raw.stream(chunk_size, decode_content=True):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 564, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 529, in read
>     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
>     raise ProtocolError("Connection broken: %r" % e, e)
> urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\OnlyFans-master\StartDatascraper.py", line 102, in 
>     x.download_media(*arg)
>   File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 257, in download_media
>     pool.starmap(download, product(media_set, [session], [directory], [username]))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
>     raise self._value
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 242, in download
>     for chunk in r.iter_content(chunk_size=1024):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 753, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
> 
> C:\Users\user\Desktop\OnlyFans-masterpause
> Press any key to continue . . .

**Comment by DIGITALCRIMINAL** [comment]
Were you doing an infinite loop with the script? If so you might get that error because of too many requests

**Comment by avekifes** [comment]
Infinite loop? I don't think so; I'm not even sure how to do that. I got the error while downloading a single account.

Do you think the ripper should include an option to reduce requests?

**Comment by DIGITALCRIMINAL** [comment]
Did you fill in auto_site_choice, auto_choice, and auto_scrape_all?

**Comment by avekifes** [comment]
Yes, all three.

"auto_site_choice": "onlyfans",
"auto_choice": "a",
"auto_scrape_all": false,

**Comment by DIGITALCRIMINAL** [comment]
Do you still get the error?

**Comment by doodlie** [comment]
@DIGITALCRIMINAL Hey, what does the PSA warning about video CDN being ass mean? Does that have anything to do with video quality or what? thanks :)

**Comment by DIGITALCRIMINAL** [comment]
@doodlie Video quality is the same (Highest quality). It's just that the download speed might be slow due to Onlyfan's servers being slow. Although it's been quite fast for me this week so I think they might have fixed it.

**Comment by doodlie** [comment]
Oh that's not too bad. Thanks for letting me know!
