### ISSUE TITLE
Changing the date format for the new version

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#65]
I tried to use the previous instruction to change the date format but I believe you have change the coding?

**Comment by DIGITALCRIMINAL** [comment]
Date format as in 01/11/2019 to 11/01/2019 or something like that?

**Comment by dilemmax** [comment]
Oh no, I mean like change to YYYY-MM-DD. Makes it hard to sort videos in the proper order if in the original format.

1/11/2019
11/11/2019
2/11/2019
3/11/2019
30/11/2019
04/11/2019

**Comment by dilemmax** [comment]
okay sorry. I forgot to edit the config.json file.
