### ISSUE TITLE
Duplicate downloads OnlyFans MediaID changed

### ISSUE THREAD

**Issue by mikeymatrix70** [DIGITALCRIMINAL/OnlyFans#650]
Has anyone else noticed that MediaID's have changed on OnlyFans resulting in duplicate downloads? I use the media_id and date to ensure all filenames are unique and it's worked pretty good until this mornings run. 

filename_format": "{media_id}-{date}.{ext}"

**Comment by artyom2035** [comment]
@mikeymatrix70 Yes, I noticed when I manually downloaded an individual model's posts today. I just shrugged it off & deleted the older versions.  

Now that you mention it, I took a look at my setup that's set to loop, it normally finishes in 120ish minutes, but it's been running for 20 hours redownloading dups of everything with different with different media ids (90 creators - most free trial stuff). Sucks because I switched from using date & text a couple of months ago.

Trying to think of a easy way to clean it up. Might just have to delete everything that was free...

"filename_format": "{date}-{filename}-{media_id}.{ext}"

**Comment by flamingghost** [comment]
Seeing the same issue with filename, I use "{username}-{date}-{filename}.{ext}"

**Comment by mikeymatrix70** [comment]
Well I would call this a program bug. I don't think there is a way for program to know when the site changes a key value. I'm using a  dupe cleaner running against model folders one by one after downloading to a parallel location. Time consuming but it ran me out of disk space FAST. One other thing I noticed which is a bug is running with the -m option still downloads files instead of only downloading metadata.

**Comment by avekifes** [comment]
I don't know if this is related, but mine keeps updating the file dates with every run.

**Comment by artyom2035** [comment]
Definitely a site change, not a bug. Fortunately, I think I stopped mine before it scraped everything & I'm working on cleaning dups.

Just thinking out loud...

Curious if stripping the media_id from the filename can be automated. Then remove it from filename_format in the config file that way it matches on the next run & doesn't redownload.  Might also guard against future media_id changes.  Although, removing it might cause a filename conflict in those "slideshow" style posts.  I've got a bulk file renamer that can remove X number of characters but media_id seems to vary in length, so it's no good in this situation unfortunately.

**Comment by mikeymatrix70** [comment]
> Definitely a site change, not a bug. Fortunately, I think I stopped mine before it scraped everything & I'm working on cleaning dups.
> 
> Just thinking out loud...
> 
> Curious if stripping the media_id from the filename can be automated. Then remove it from filename_format in the config file that way it matches on the next run & doesn't redownload. Might also guard against future media_id changes. Although, removing it might cause a filename conflict in those "slideshow" style posts. I've got a bulk file renamer that can remove X number of characters but media_id seems to vary in length, so it's no good in this situation unfortunately.

I was looking at a way to do that by just downloading metadata and scripting a proper rename but the -m switch for metadata only doesn't appear to be working. Definitely a bummer as it's truly the only unique part of the posts.

**Comment by DIGITALCRIMINAL** [comment]
Made a new commit that takes care of the media_id duplication.
