### ISSUE TITLE
.settings folder is not there

### ISSUE THREAD

**Issue by jat9n** [DIGITALCRIMINAL/OnlyFans#651]
i can see hidden folders but .setting folder is not there

**Comment by RonnieBlaze** [comment]
He just going to tell you to read the FAQ then close your thread like he did to me..  BUT i did finally get the settings and profile folder to show up.. and i till tell you what i did to help you out...

take the newest code and put in a BRAND new folder and then run it with out changing anything.. it will say then say the profile folder was made and to hit enter to continue and then it will make the settings folder after that..

it was a pain in the ass to get it to make them for me.. i hope this works for you.. idk why the folders are just not included in the files like they were originally.

**Comment by jat9n** [comment]
it worked but extra_auth file was not created and code in config file is totally different.

**Comment by RonnieBlaze** [comment]
the video is wrong, it even says that next to the link.. all the settings that you have to fill in are the same from the old way.  lookin the .profiles\OnlyFans\default for a file called auth.json this is where you fill in your account info .  .settings/config.json is all the settings.

**Comment by Hnd42** [comment]
maybe this code just support for python 3.9 (python 3.9 only run on window 8.1 and 10), so settings folder is not there.
