### ISSUE TITLE
Not working with Python 3.9 on Ubuntu 20.10

### ISSUE THREAD

**Issue by reahari** [DIGITALCRIMINAL/OnlyFans#652]
I'm trying to use commit #00f3f3d on Ubuntu 20.10. I have Python 3.9 installed but when I run start_ofd.py I get this error
```
python3.9 start_ofd.py 
Traceback (most recent call last):
  File "/OnlyFans/start_ofd.py", line 8, in <module>
	main_test.check_config()
  File "/OnlyFans/tests/main_test.py", line 20, in check_config
	import helpers.main_helper as main_helper
  File "/OnlyFans/helpers/main_helper.py", line 5, in <module>
	from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'
```
I checked and I already have deepdiff 5.2.1 installed (released on 1st January 2021).

Is the script not finding deepdiff?

**Comment by zerodayz1** [comment]
I have the same issue on **`20.04`** & `Master Branch`

Checking requirements...

**`sudo pip install -r requirements.txt`** 

`Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (4.9.3)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.25.8)
Requirement already satisfied: win32-setctime in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (1.0.3)
Requirement already satisfied: pysocks in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (5.5.1)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.7.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 8)) (4.6.2)
Requirement already satisfied: mergedeep in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 9)) (1.3.0)
Requirement already satisfied: jsonpickle in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 10)) (1.4.2)
Requirement already satisfied: deepdiff[murmur] in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 11)) (5.2.1)`
  
This line might be an issue though...

**`WARNING: deepdiff 5.2.1 does not provide the extra 'murmur'`**

Continues...

`Requirement already satisfied: numpy==1.19.3 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 12)) (1.19.3)
Requirement already satisfied: ujson in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 13)) (4.0.1)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 14)) (1.3.22)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in /usr/local/lib/python3.8/dist-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.1)
Requirement already satisfied: ordered-set==4.0.2 in /usr/local/lib/python3.8/dist-packages (from deepdiff[murmur]->-r requirements.txt (line 11)) (4.0.2)`

Check version...

`python --version`
 **`Python 3.9.1`**

Running...

`python start_ofd.py                 
Traceback (most recent call last):
  File "/opt/OnlyFans/start_ofd.py", line 8, in <module>
    main_test.check_config()
  File "/opt/OnlyFans/tests/main_test.py", line 20, in check_config
    import helpers.main_helper as main_helper
  File "/opt/OnlyFans/helpers/main_helper.py", line 5, in <module>
    from deepdiff.deephash import DeepHash
**ModuleNotFoundError: No module named 'deepdiff'`**

**Comment by zerodayz1** [comment]
This seems to be the python3.9 problem with the installed modules looking at the 3.8 version, as above. 

I've tried to install the modules individually using:

`python3.9 -m pip install <module>`

Which does move things forward. But now failing on `psutil`

**Comment by DIGITALCRIMINAL** [comment]
I dunno, it's a Ubuntu problem lul

**Comment by reahari** [comment]
@zerodayz1 if I run `python3.9 -m pip install -r requirements.txt` it seems the script now starts working
