### ISSUE TITLE
Cant download from all users

### ISSUE THREAD

**Issue by gsoxreptile** [DIGITALCRIMINAL/OnlyFans#653]
Whenever I try to download from all the pages I have subscribed to, it brings up each of the users one by one and every time asks me what I want to download from each user, but if I keep saying everything from every user, nothing is downloaded, it works if i download from each of the users one by one...

**Comment by artyom2035** [comment]
How does your config look? When you pick 'everything' are you waiting for the script to complete? Because it processes folders & metadata first, then media? Mine downloads everything with these settings.

```
        "auto_scrape_names": true,
        "auto_choice": "a",
        "auto_scrape_apis": true,
```

**Comment by James-MF-Thomas** [comment]
I'm pretty sure you're not waiting for the script to cycle through at least 1 whole rotation. once the script loops 1x some time 2x (at least it feels twice) you will stat to see media being downloaded.

**Comment by James-MF-Thomas** [comment]
If you have a large  number (##) of models depending on your system it can hours. if you have an extremely  nigh number (####) it can a day before it starts to pick up media. 

If that is the case try partitioning your models "lists" then using the "black/whitelist" feature to get it so you don't have to start the process over from scratch if you need to stop the script.

**Comment by gsoxreptile** [comment]
Yep you were correct.. it all works now
