### ISSUE TITLE
Followed read.me and video tutorial multiple times... the media will simply not rip even tho the folders do

### ISSUE THREAD

**Issue by swipershit** [DIGITALCRIMINAL/OnlyFans#658]
I am using the latest version of onlyfans.py. every single time i complete the process in CMD prompt, the media does not get scrapped and nothing is saved at alll... EXCEPT the folders. so frustrating

**Comment by artyom2035** [comment]
Are you waiting until the script finishes?  It downloads all directories and metadata first, then it starts downloading media.

**Comment by swipershit** [comment]
Maybe not... I am waiting now so we will see. I didnt realise that

**Comment by swipershit** [comment]
@artyom2035 Still not working. Maybe this is why? my config.json has no 'auth' when i go to edit it?
![Untitled](https://user-images.githubusercontent.com/76914511/103522626-c2997b00-4ece-11eb-8271-1c41b7aea58d.jpg)

**Comment by GreyBeardy** [comment]
auth.json must be editet also

for me its here: \OnlyFans-6.1.2\.profiles\OnlyFans\default

**Comment by artyom2035** [comment]
@swipershit auth was moved out of config.json.  
Looks like yours should be here:  J:\(redacted)\Onlyfans-Master\.profiles\OnlyFans\default\auth.json

**Comment by swipershit** [comment]
The .profiles file doesnt exist? These are the ones that appear after 'pip install...' and 'python start_ofd.py'.
![Untitled1](https://user-images.githubusercontent.com/76914511/103600256-1651a600-4f5b-11eb-89d1-0cb594547b7c.jpg)
![Untitled](https://user-images.githubusercontent.com/76914511/103600260-181b6980-4f5b-11eb-918c-6bdc0d2d1e26.jpg)

**Comment by GreyBeardy** [comment]
did you press enter as the script says in the last line of your screen - after filling out the config.json

that will give another line saying auth.json was created in the .profiles path.

**Comment by swipershit** [comment]
Omg im such an idiot.... THANK YOU! @GreyBeardy @artyom2035

**Comment by DIGITALCRIMINAL** [comment]
wow...
