### ISSUE TITLE
Is it normal that the script is updating creation and modification date for the same files every time I run the script?

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#659]
Version 6.1.2
Seems to be updating this for the same files over and over every time I run the script.

```
Updated Creation Time I:\OnlyFans-6.1.2\.sites\OnlyFans\candyw\Messages\Videos\[2020-12-10] (0glj5o3azt1qrj1ibz17s_source).mp4
Updated Modification Time I:\OnlyFans-6.1.2\.sites\OnlyFans\candyw\Messages\Videos\[2020-12-10] (0glj5o3azt1qrj1ibz17s_source).mp4
Updated Creation Time I:\OnlyFans-6.1.2\.sites\OnlyFans\candyw\Messages\Videos\[2020-12-09] (0glhdxzeaxjfi4mrahs1z_source).mp4
Updated Modification Time I:\OnlyFans-6.1.2\.sites\OnlyFans\candyw\Messages\Videos\[2020-12-09] (0glhdxzeaxjfi4mrahs1z_source).mp4
Updated Creation Time I:\OnlyFans-6.1.2\.sites\OnlyFans\candyw\Messages\Videos\[2020-12-08] (5fcffe4a0d9afdeea5e93_source).mp4
Updated Modification Time I:\OnlyFans-6.1.2\.sites\OnlyFans\candyw\Messages\Videos\[2020-12-08] (5fcffe4a0d9afdeea5e93_source).mp4
Updated Creation Time I:\OnlyFans-6.1.2\.sites\OnlyFans\candyw\Messages\Videos\[2020-12-10] (0glj5o598wwu9lyzaoomj_source).mp4
```

**Comment by DIGITALCRIMINAL** [comment]
No, there's something wrong with media_id

**Comment by anonCoder123** [comment]
i've having this same issue after upgrading from 6.0 to master. This updating metadata time has slowed the script down from 5-10 minutes to now taking 80-100 minutes.

**Comment by whateverman91** [comment]
I am having the same issue with 6.x 
Every time I run the script, it updates the modification time for every media already downloaded, and it takes much longer now.

Running on Linux and the file system is ext4.

**Comment by avekifes** [comment]
...so the issue is that OnlyFans keep randomizing its media_id for content?

**Comment by mikeymatrix70** [comment]
I don''t believe the media_id is being randomized. it seems to have changed once since Sunday but has been constant as i redownloaded all of my active subscriptions as well as paid content and have been running the scraper and it's working normally. it appears that it is setting the file create and modify date to match what's on the server. not getting any abnormal run times although it does state it's modifiying date and time.

**Comment by bobsage123** [comment]
> I don''t believe the media_id is being randomized. it seems to have changed once since Sunday but has been constant as i redownloaded all of my active subscriptions as well as paid content and have been running the scraper and it's working normally. it appears that it is setting the file create and modify date to match what's on the server. not getting any abnormal run times although it does state it's modifiying date and time.

Same here. The media_id has not changed. It is possible that something weird is happening on the OF servers though and they are changing the dates of the files.

**Comment by whateverman91** [comment]
> not getting any abnormal run times although it does state it's modifiying date and time.

Well that depends on your disk. My data is stored on a HDD (magnetic) so each mtime/ctime commands do take time. Some creators have thousands of files...

**Comment by mikeymatrix70** [comment]
Yeah I usually have about 56 active subscriptions and after media id changed I redownloaded close to 1TB over 250,000 files easy. Now that redownloaded with proper media, cleared out files with old media id, and moved to original location when I run a job it's taking about 20 mins.  If anyone is interested here is my setup.
1. Under my scraper folder "C:\OnlyFans-6.1.2\.sites" I use a symbolic link to my Onlyfans folder
2. I deleted my original symbolic link and pointed to a new one on a drive with sufficient drive space to download all active subscriptions and paid content
3. Ran multiple scraper jobs until all files were downloaded.
4. The PAINFUL part. I used "Digital Volcano Dupilcate Cleaner Pro" and ran comparisons on model folders in new and old locations removing duplicates found in the old folder location only. 
5. Once complete I move all downloaded folders from new to the old location. (I did it this way so story files that expired were still there I did choose to overwrite existing metadata as it had only the current file names)
6. Deleted the symbolic link for the newly downloaded folder and replaced with the original
7. Ran scraper job as normal. Initially job took about an hour then subsequent runs about 20 mins

**Comment by avekifes** [comment]
...yeah, I'm not doing that. There's got to be a bug in the script, since it didn't have this problem until recent versions. Why wouldn't it just skip preexisting files?

**Comment by avekifes** [comment]
I applied the latest updates but am now running into a media_id error.

> Traceback (most recent call last):
> File "C:\Users\user\Desktop\OnlyFans-master\start_ofd.py", line 40, in
> main_datascraper.start_datascraper(json_config, site_name_lower)
> File "C:\Users\user\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 85, in start_datascraper
> x = main_helper.process_names(
> File "C:\Users\user\Desktop\OnlyFans-master\helpers\main_helper.py", line 521, in process_names
> result = module.start_datascraper(
> File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 148, in start_datascraper
> results = prepare_scraper(
> File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 681, in prepare_scraper
> w = process_metadata(metadata_path, new_metadata,
> File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 556, in process_metadata
> Session, api_type, folder = main_helper.make_metadata(
> File "C:\Users\user\Desktop\OnlyFans-master\helpers\main_helper.py", line 167, in make_metadata
> media_id = media["media_id"]
> KeyError: 'media_id'

**Comment by whateverman91** [comment]
@DIGITALCRIMINAL even after the fix, I'm still getting the same error, all modification times are updated. I am using the master branch.

**Comment by whateverman91** [comment]
Actually, nvm. Running the script twice, the second time it worked fine. Now executions went back down to 10-15 mins as opposed to 80 they were before.
