### ISSUE TITLE
Chose multiple profiles to download.

### ISSUE THREAD

**Issue by GreyBeardy** [DIGITALCRIMINAL/OnlyFans#660]
Hi.

Would it be possible to add the option to chose multiple profiles to get at the first prompt?

I believe as it is now you can chose 0 = all or pick a number.

If I have 40 profiles and only want to download 7 It would be nice to "queue" those 7 and be able to leave the pc.

**Comment by DIGITALCRIMINAL** [comment]
I haven't added it in the readme, but yes you can.

Seperate the usernames or numbers by commas.
