### ISSUE TITLE
[OnlyFans] downloading content not selected

### ISSUE THREAD

**Issue by sintaxx** [DIGITALCRIMINAL/OnlyFans#664]
i'm using the latest script on linux with python 3.9 and everytime i go to scrape an individual model somehow it ends up scraping random files from other seemingly random profiles i have subscriptions to. Am I the only one having this issue?

**Comment by gsoxreptile** [comment]
it sounds like its profiles you have subscribed to in the past, so it scrapes all the images and videos that was sent in the chat
