### ISSUE TITLE
[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#665]
Running latest commit

The script seems to be stuck in a loop with the following error. I can confirm the files and directory are present. It does get past the first user who has no archived so it seems to be an issue with archived posts??

[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Videos\\File_1.mp4'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Images\\File_2.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Images\\File_3.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Images\\File_4.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Images\\File_5.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Images\\File_6.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Videos\\File_7mp4'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Images\\File_8.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Videos\\File_9.mp4'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\user\\Archived\\Free\\Videos\\File_1.mp4'
etc etc

**Comment by DIGITALCRIMINAL** [comment]
Are you using the latest commit?

**Comment by DIGITALCRIMINAL** [comment]
What's their username?

**Comment by DIGITALCRIMINAL** [comment]
What was your filename

**Comment by ChillyP** [comment]
"file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
"filename_format": "{date}_{filename}.{ext}",

**Comment by DIGITALCRIMINAL** [comment]
I need to know the filenames that are broken

**Comment by ChillyP** [comment]
[Errno 2] No such file or directory: 'D:\\OnlyFans\\emmag\\Archived\\Free\\Images\\15-05-2020_2191x3088_1d3ba8d4760f22338a5641ab79368c1b.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\emmag\\Archived\\Free\\Videos\\07-12-2017_400PHsfEyLvtw2A7mObOdQUnjoDQejL8.mp4'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\emmag\\Archived\\Free\\Images\\07-05-2020_2316x3088_5955866e24f34e1d8d219d56c8aed83c.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\emmag\\Archived\\Free\\Images\\14-08-2019_1082x667_366ee8bd879056968bea0be6cac6becc827344.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\emmag\\Archived\\Free\\Videos\\15-01-2020_5e1f93cf5208c7b455e58.mp4'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\emmag\\Archived\\Free\\Images\\08-05-2020_2316x3088_2fde61b59aa7d9dfab14b9c47b6d30e4.jpg'
[Errno 2] No such file or directory: 'D:\\OnlyFans\\emmag\\Archived\\Free\\Videos\\05-12-2017_xpH9XBaoD20oAvAUhBqBv1Yg1sb6vR5y.mp4'

**Comment by DIGITALCRIMINAL** [comment]
Thanks, I also added a new commit that may give more information on the error

**Comment by ChillyP** [comment]
Cool, here is the new error based on latest commits.

"During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\OnlyFans\extras\OFRenamer\start.py", line 76, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 820, in move
    copy_function(src, real_dst)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OnlyFans\\emmag\\Archived\\Free\\Images\\07-05-2020_2316x3088_5955866e24f34e1d8d219d56c8aed83c.jpg'

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\OnlyFans\\emmag\\Archived\\Posts\\Free\\Images\\14-08-2019_1082x667_366ee8bd879056968bea0be6cac6becc827344.jpg' -> 'D:\\OnlyFans\\emmag\\Archived\\Free\\Images\\14-08-2019_1082x667_366ee8bd879056968bea0be6cac6becc827344.jpg'"

**Comment by DIGITALCRIMINAL** [comment]
Ahh okay, so Posts\Free\Images doesn't exist right but Free\Images does right?

**Comment by ChillyP** [comment]
No its actually the other way around, the directory tree Archived\Posts\Free\Images does exist in the file system and Archived\Free\Images does not exist

**Comment by DIGITALCRIMINAL** [comment]
Try latest, it should work

**Comment by headphonia** [comment]
I'm also getting this error on the latest commit.

`Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/shutil.py", line 803, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/OF Scrapper/.sites/OnlyFans/filipinaxo/Archived/Posts/Free/Images/1240x1654_ab343e8fe8a6198bc4710b6e02522259.jpg' -> '/OF Scrapper/.sites/OnlyFans/filipinaxo/Posts/Paid/Images/1240x1654_ab343e8fe8a6198bc4710b6e02522259.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/OF Scrapper/extras/OFRenamer/start.py", line 81, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/OF Scrapper/.sites/OnlyFans/filipinaxo/Posts/Paid/Images/1240x1654_ab343e8fe8a6198bc4710b6e02522259.jpg'`
