### ISSUE TITLE
Question: Update Modification and Creation Time

### ISSUE THREAD

**Issue by Kurosaki22** [DIGITALCRIMINAL/OnlyFans#667]
Not an issue but more a question.
Most of the time when I run the script it always updates Modification and Creation Time.
and because of that the script takes ages.

![image](https://user-images.githubusercontent.com/69061840/103803491-edabd800-5050-11eb-8b80-bb03c440fba1.png)

Is it possible to disable this or is it mandatory?

**Comment by DIGITALCRIMINAL** [comment]
Are you running the latest commit?, because I've fixed this.

**Comment by Kurosaki22** [comment]
Yes this was on the latest master.
I will re-run it quickly to verify.

**Comment by DIGITALCRIMINAL** [comment]
Let it complete its job

**Comment by Kurosaki22** [comment]
Ah ok. 
Saw it on the first run when everything was fixed and now its gone.
Was just curious because in the past I saw it during every run.

Thanks :)
