### ISSUE TITLE
[Feature Request] Scraping lists associated to accounts

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#669]
I use lists as tags and filters to manage the *multiple* subscriptions I have. It would be great if those could be downloaded along with the rest of the metadata. I don't have a suggestion as far as the final format as long as it is possible to reference it, ideally through a file search.

Thanks!

edit: in the best world that would allow to look at the content of all the content of the accounts that are part of list X

**Comment by DIGITALCRIMINAL** [comment]
I don't really want to increase the metadata file by adding stuff like that...

**Comment by jp1151419** [comment]
> 
> 
> I don't really want to increase the metadata file by adding stuff like that...

Does the metadata file size affect the process speed? Because it could just be optional.

**Comment by DIGITALCRIMINAL** [comment]
> > I don't really want to increase the metadata file by adding stuff like that...
> 
> Does the metadata file size affect the process speed? Because it could just be optional.

Theoretically, yes...

**Comment by James-MF-Thomas** [comment]
damn thing sends more time on metadata than anything else, lol
