### ISSUE TITLE
not getting latest commit to work

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#671]
I've read the readme as well as a couple recent issues posts but can't figure this one out. I have an instance of 8da3cd7 still running fine but there seems to be a lot of improvements since.

![image](https://user-images.githubusercontent.com/58760178/103817187-2db09200-5034-11eb-822e-afab8527be66.png)

I also had the same "no content" message as others when I tried using my old authenticating values. This is with new values.

**Comment by thats-whack** [comment]
I have this same exact error with the new release. I thought it would just be me. I've done everything according to readme

**Comment by jp1151419** [comment]
wasn't filling in my new cookie informations properly it seems. I also discovered I had to rename the folder inside .profiles\OnlyFans to my username, along with replacing "default" in auth.json by my username once again (script kept changing it back to "default")
