### ISSUE TITLE
Paid content not downloading

### ISSUE THREAD

**Issue by sonicshake** [DIGITALCRIMINAL/OnlyFans#679]
The script picks up paid posts but apparently ignores them instead of downloading them. `scrape_paid_content` is set to true.

Example extract of output:

> Download Processing
> Name: courtneytaylorxxx | Type: Messages | Count: 0 Images | Directory: /share2/CACHEDEV1_DATA/Download/OF2
> 
> Download Processing
> Name: courtneytaylorxxx | Type: Messages | Count: 1 Videos | Directory: /share2/CACHEDEV1_DATA/Download/OF2
> 
> Download Processing
> Name: courtneytaylorxxx | Type: Messages | Count: 0 Audios | Directory: /share2/CACHEDEV1_DATA/Download/OF2

When the script has finished the model directory only contains the Metadata folder and Messages.db (or Posts.db in other cases). The db files contain all the correct info but nothing actually gets downloaded as per the example above.

Using a fresh install of commit (775df64) in a new python venv with an empty target directory, so there are no pre-existing downloads or db files.

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit
