### ISSUE TITLE
new functionality idea ?

### ISSUE THREAD

**Issue by Zerero** [DIGITALCRIMINAL/OnlyFans#68]
I'm pretty sure this is not the way to bring a new functionality so I want to apologize for that. 
I'm wondering if there is a possibility to add an optional feature that would allow to scrap media inside messages ? 
Thanks for this very useful library. I'm no beginner in web scraping but I would gladly help if you have the patience to explain me the basics.

**Comment by DIGITALCRIMINAL** [comment]
I almost forgot about scraping messages. This will be implemented by or during next week c:

**Comment by DIGITALCRIMINAL** [comment]
Messages are in already btw. You can download the master or wait for a release.
