### ISSUE TITLE
sqlalchemy .... ?

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#681]
First things I kept getting a traceback yesterday asking for .DS_store file. Thats weird cuz it shouldn't even know about .DS_store. That's macOS metadata.  It broke tying to:

![Screen Shot 2021-01-07 at 7 42 36 PM](https://user-images.githubusercontent.com/47627618/103964240-95440b80-5120-11eb-940e-17c1f12ba227.png)

The 2nd weird thing is that I'm not using the directory it's looking for, at least not in my .config:

![Screen Shot 2021-01-07 at 7 45 39 PM](https://user-images.githubusercontent.com/47627618/103964389-f53ab200-5120-11eb-8566-dd5d3ea8ab30.png)

so I ran git remote and git fetch upstream, and now I get this:

![Screen Shot 2021-01-07 at 7 34 43 PM](https://user-images.githubusercontent.com/47627618/103964565-5a8ea300-5121-11eb-892e-b7e2abda2bb1.png)

![Screen Shot 2021-01-07 at 7 49 38 PM](https://user-images.githubusercontent.com/47627618/103964626-81e57000-5121-11eb-9977-c894d8213ac6.png)

**Comment by ctrlcmdshft** [comment]
try runing `pip install -r requirements.txt` from within the main folder of this project which in your case looks like its OnlyFans folder

**Comment by James-MF-Thomas** [comment]
that added the extra package but it doesn't help pre-commit. For some reason it's treating .DS_store as a directory/folder when its a hidden metadata file.

**Comment by James-MF-Thomas** [comment]
I don't know how .ds_store3 got added to the auth.json path name. I searched for it int he code but couldn't find it

**Comment by DIGITALCRIMINAL** [comment]
I don't have MacOS so I wouldn't know

**Comment by ctrlcmdshft** [comment]
best bet is to delete everything in onlyfans directory except .sites so you dont lose any existing downloads and then download latest commit zip and then drag and drop all files in the zip to onlyfans folder and try again

**Comment by James-MF-Thomas** [comment]
Already did that

**Comment by James-MF-Thomas** [comment]
im sending anything to .sites. I started a new clone of DCs master to a different path and broke just the same

**Comment by ctrlcmdshft** [comment]
try it manually without using git/clone

**Comment by James-MF-Thomas** [comment]
👍🏼👍🏼 fkn lame
