### ISSUE TITLE
Position in post naming

### ISSUE THREAD

**Issue by KristofferKvamme** [DIGITALCRIMINAL/OnlyFans#682]
Would it be possible to get a position in post tag for naming. 
After OnlyFans changed all media ids, a lot posts with multiple images get all out of order. Would be nice to have the position in the name, so i can get the images back in order.

**Comment by DIGITALCRIMINAL** [comment]
You can already do this

**Comment by KristofferKvamme** [comment]
I cant find it in the readme.
I can see I can have post_id, but I want to have the naming sceme: {date]_{post_id}_{POSITION_IN_POST_ALBUM}_{filename}.

**Comment by DIGITALCRIMINAL** [comment]
It's literally the media_id.

**Comment by KristofferKvamme** [comment]
But after onlyfans changed media_id they will not be sorted in the right order.

**Comment by DIGITALCRIMINAL** [comment]
Then there's no way

**Comment by KristofferKvamme** [comment]
The images are in correct order in the "medias" array in the json file. Would it be possible to get their position in that array in their name ?
