### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Kabla19** [DIGITALCRIMINAL/OnlyFans#684]
Hi, I'm sorry for bothering you, I've istalled Python 3.9 andI see the file named .settings, but I can't find the file named .profiles. I've watched the tutorial on YouTube, but unfortunately I don't have any of lines betwen the 13th line and 24th line. I don't see any file where I can type a name and an ID. There isn't anything similar to the exaple you've given. Could you help me out with it?

**Comment by artyom2035** [comment]
The youtube tutorial is for an older commit. Those lines have been relocated to '.profiles/OnlyFans/default/auth.json'

When you initially launch the script it will inform you that "The '.settings/config.json' file has been updated.  Fill in whatever you need to fill in then press enter when done".  Have you done this? I think '.profiles' is created after this is done.
