### ISSUE TITLE
user_agent required for: default 

### ISSUE THREAD

**Issue by moviemaker989** [DIGITALCRIMINAL/OnlyFans#686]
I run the pip install then get to the python start then 0 for only fans then get this message
user_agent required for: default 
I can not erase default and when I just add my user agent to the back of default it does not work and when I press enter while it is on default it does not work

**Comment by artyom2035** [comment]
@moviemaker989 put your `auth_id`, `session`, and  `user_agent` in `.profiles/OnlyFans/default/auth.json`
