### ISSUE TITLE
cmd line fail

### ISSUE THREAD

**Issue by moviemaker989** [DIGITALCRIMINAL/OnlyFans#688]
even after i added my user agent when I after I hit 0 for onlyfans it keeps saying user agent required for : default it would let me erase default and whether I hit return or add the exact user agent it still just resets and starts me from the beginning. Somebody please help I dont mind buying cups of coffee.

**Comment by artyom2035** [comment]
Where are you adding the user agent? auth.json or in the command line? Did you see the comment on issue #686?

**Comment by moviemaker989** [comment]
yes I put it in .profile and it still says user agent required for : default on the command line when I try and execute everything perfectly fine until I get to that part

**Comment by moviemaker989** [comment]
![photo_2021-01-09_01-11-00](https://user-images.githubusercontent.com/77181089/104084727-ab80c300-5217-11eb-9878-66629de7e6a9.jpg)

**Comment by moviemaker989** [comment]
My apologies for I am an idiot I got it just let me know where to send the cup of coffee
