### ISSUE TITLE
missing auth section 

### ISSUE THREAD

**Issue by theking1473** [DIGITALCRIMINAL/OnlyFans#689]
The lines are only this

"supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "",
        "auto_scrape_names": false,
        "auto_choice": "",
        "auto_scrape_apis": true,
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },

**Comment by skylar01** [comment]
It was stated on the "Video Tutorial" Section
(Authentication is no longer inside config.json)

AFAIK it should be on ".profiles/default/auth.json"

Running on docker looks for settings in .settings\config.json though.

**Comment by theking1473** [comment]
yea was reading the comment section. only issue is that i have no profile folder.

**Comment by theking1473** [comment]
nevermind used master version instead

**Comment by theking1473** [comment]
nevermind used master version
