### ISSUE TITLE
I applied show hidden files still not showing

### ISSUE THREAD

**Issue by moviemaker989** [DIGITALCRIMINAL/OnlyFans#693]
I followed the windows instructions and checked the show hidden files and drives and applied it but the .profiles and the .settings still does not show up for me to add my auth credentials. I have windows 10 and followed the 3 instructions that they listed but still not working

**Comment by DIGITALCRIMINAL** [comment]
Did you start the program

**Comment by moviemaker989** [comment]
Ok I started the program I forgot that I restarted the computer so I see settings now but still no profiles the last code I uploaded had profiles and settings in different folders I only see settings which takes me to config but there is nowhere to add the auth unless I am supposed to make space and put it somewhere in the config file which is different then last time I did it when it was working

**Comment by DIGITALCRIMINAL** [comment]
I dunno, it's best you use another script then
