### ISSUE TITLE
issue not finding tables

### ISSUE THREAD

**Issue by Fernando-Martinez** [DIGITALCRIMINAL/OnlyFans#694]
After pulling latest changesets, started to get errors about tables not being found in database.

Like this:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: posts
[SQL: SELECT posts.id AS posts_id, posts.text AS posts_text, posts.price AS posts_price, posts.paid AS posts_paid, posts.created_at AS posts_created_at
FROM posts]

and this:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: messages
[SQL: SELECT messages.id AS messages_id, messages.text AS messages_text, messages.price AS messages_price, messages.paid AS messages_paid, messages.created_at AS messages_created_at
FROM messages]

Renaming the .db files /database/ fixes the issue.

renamed test_messages.db to messages.db, and test_posts.db to posts.db and test_stories.db to stories.db

I did the change locally and i was able to scrape and download correctly after that

**Comment by avekifes** [comment]
I just got this.

`sqlite3.OperationalError: no such table: messages`

Related issue?

**Comment by DIGITALCRIMINAL** [comment]
@avekifes is there a 0kb messages.db file in your metadata folder

**Comment by Fernando-Martinez** [comment]
> I just got this.
> 
> `sqlite3.OperationalError: no such table: messages`
> 
> Related issue?

Yea, looks exactly the same.

**Comment by avekifes** [comment]
> 
> 
> @avekifes is there a 0kb messages.db file in your metadata folder

Yes.

**Comment by DIGITALCRIMINAL** [comment]
> > @avekifes is there a 0kb messages.db file in your metadata folder
> 
> Yes.

Thanks, if you delete that 0kb file; it will work.

**Comment by avekifes** [comment]
> 
> 
> > > @avekifes is there a 0kb messages.db file in your metadata folder
> > 
> > 
> > Yes.
> 
> Thanks, if you delete that 0kb file; it will work.

Is this something that will be fixed in an upcoming commit, or should I just manually clear out all 0-kb messages.db files?

**Comment by Fernando-Martinez** [comment]
Its a problem migrating the metadatas, so you can just delete yours and rebuild those from scratch which works just fine

**Comment by DIGITALCRIMINAL** [comment]
> > > > @avekifes is there a 0kb messages.db file in your metadata folder
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Thanks, if you delete that 0kb file; it will work.
> 
> Is this something that will be fixed in an upcoming commit, or should I just manually clear out all 0-kb messages.db files?

Basically the commit that first introduced databases wasn't correctly done. You may have gotten a media_id error which caused the script to not write any data.

Latest version of the script, converts the old database to a new format and then merges everything.

**Comment by avekifes** [comment]
...now I'm getting this error even on accounts with Messages.db files that aren't 0 kb. Running the script results in a Pre_Alembic_Posts.db file, but it errors after that.

Should I just delete all of my Metadata folders and have the scraper do everything from scratch? That's actually what I did a day or two ago to fix my previous issues.

**Comment by DIGITALCRIMINAL** [comment]
Don't do that unless you don't care about support for changing filenames. I'll fix it.

**Comment by DIGITALCRIMINAL** [comment]
You can use the latest commit.
Any existing 0kb files will need to be deleted manually.

**Comment by DIGITALCRIMINAL** [comment]
Latest commit will resolve the errors automatically, thanks for the legacy databases,etc
