### ISSUE TITLE
Media ID Missing In Filenames

### ISSUE THREAD

**Issue by dunkethee** [DIGITALCRIMINAL/OnlyFans#698]
With the new SQLite DBs - It appears the filenames aren't quite built properly. 

In the Posts DB - "medias" table, I'm seeing filenames that are missing the media ID. Current format is {date}\_{media_id}.{ext} - but resulting filename looks like {date}\_.{ext}. I tried temporarily moving the output folder to see if a new DB created from scratch would have this issue and it did

**Comment by DIGITALCRIMINAL** [comment]
In earlier versions of the script, I did not include the media_id in json metadatas which is why you'll see NULL media_ids

**Comment by dunkethee** [comment]
In the database, the media_id field is not null. The problem is the filenames. I'm seeing this even with no legacy metadata from older versions of the script on a completely clean install/config.json.

**Comment by DIGITALCRIMINAL** [comment]
Alright, try the latest commit please

**Comment by dunkethee** [comment]
No fix there. The following tweak solves the issue - Around line 973 of onlyfans.py (within media_scraper) - add the following:
`                option["media_id"] = media["id"]`

I'm not certain that this is the proper way to set this in all cases, but I believe the issue is that despite media_id existing, it is not included in the options when filepath is set on line 979 call to main_helper.reformat

**Comment by DIGITALCRIMINAL** [comment]
Thank you, that's the correct answer, the latest commit has that change 👍

**Comment by James-MF-Thomas** [comment]
still getting it 

![Screen Shot 2021-01-10 at 12 10 18 AM](https://user-images.githubusercontent.com/47627618/104124984-94c29500-5319-11eb-9d7b-4b0dc3bc66db.png)

**Comment by dunkethee** [comment]
> Thank you, that's the correct answer, the latest commit has that change 👍

Thanks for all the hard work! Cheers!

**Comment by James-MF-Thomas** [comment]
I have the latest commit, just did a clean install still from the zip with ti,, that's why I posted when I did

**Comment by James-MF-Thomas** [comment]
![Screen Shot 2021-01-10 at 8 15 26 AM](https://user-images.githubusercontent.com/47627618/104125401-13203680-531c-11eb-8f36-77be30c4455e.png)
![Screen Shot 2021-01-10 at 8 15 06 AM](https://user-images.githubusercontent.com/47627618/104125405-187d8100-531c-11eb-9825-692b81c7a8e8.png)
![Screen Shot 2021-01-10 at 12 10 18 AM](https://user-images.githubusercontent.com/47627618/104125411-20d5bc00-531c-11eb-8ac0-d7def88af31a.png)
