### ISSUE TITLE
KeyError: 'auth'

### ISSUE THREAD

**Issue by iDerp** [DIGITALCRIMINAL/OnlyFans#699]
Fresh install, getting this error after selecting a profile:
```
Traceback (most recent call last):
  File "/root/OnlyFans/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/root/OnlyFans/datascraper/main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "/root/OnlyFans/helpers/main_helper.py", line 544, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'
```
I'd assume a recent update broke it so it might be a good idea to bring it to your attention.

**Comment by James-MF-Thomas** [comment]
I second this

**Comment by James-MF-Thomas** [comment]
![Screen Shot 2021-01-10 at 12 10 18 AM](https://user-images.githubusercontent.com/47627618/104115758-4b9e2100-52d8-11eb-8ecd-4cf91bc1680e.png)

**Comment by DIGITALCRIMINAL** [comment]
Delete the auth.json or format it like this

https://github.com/DIGITALCRIMINAL/OnlyFans/raw/master/examples/2.png

**Comment by Aer3x** [comment]
Removed auth,
Filled in again on the new auth file (looks the same as the old one)
 still the same error

**Comment by DIGITALCRIMINAL** [comment]
@Aer3x Use latest commit.

**Comment by DIGITALCRIMINAL** [comment]
Latest commit has fixed this completely
