### ISSUE TITLE
Findrow/Buttrcup Support

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#70]
Would you be willing to add support for Findrow and Buttrcup if I sent you crypto to buy accounts? (I emailed you at rarecoder@protonmail.com about this but never heard back.)

**Comment by DIGITALCRIMINAL** [comment]
My new email is datahoarders@protonmail.com @avekifes

**Comment by mikejones498** [comment]
I have sent an email with an accoount

**Comment by DIGITALCRIMINAL** [comment]
I see, thanks. Bit of a short notice, but I'll try to make it.

**Comment by mikejones498** [comment]
It's alright if you aren't able to, I've already ripped all the videos I can, just habing trouble with the albums.

**Comment by avekifes** [comment]
Just curious if Findrow and/or Buttrcup support is still coming.

**Comment by DIGITALCRIMINAL** [comment]
Maybe
