### ISSUE TITLE
6.2.1 doesn't create logs

### ISSUE THREAD

**Issue by mikeymatrix70** [DIGITALCRIMINAL/OnlyFans#701]
New version doesn't create logs. I use these extensively for tracking downloads. Also when merging the JSON data it actually deleted to old JSON even though the config.json is set to preserve. So currently the scraper just makes blind runs. It is faster but please bring re-enable the logging.

**Comment by DIGITALCRIMINAL** [comment]
You can track what has been downloaded in the database? The logs were creating 1GB files for certain runs so I took it out.

Script no longer uses JSON, so any metadata that's stored in JSON gets converted to sqlite.
