### ISSUE TITLE
Webhook trigger when auth is deactivated by script

### ISSUE THREAD

**Issue by fl4shback** [DIGITALCRIMINAL/OnlyFans#708]
Hi!
First, thanks for your hard work on this projet.

Saw this comment on an issue you closed recently https://github.com/DIGITALCRIMINAL/OnlyFans/issues/703#issuecomment-757927002

Do you think it would be possible to trigger a webhook when auth gets deactivated following a session change or when user-agent is not valid anymore ?

Would be really useful for automated script runs as right now with log files not being a thing anymore, there's no simple way to know when the script isn't running correctly.

Thanks!

**Comment by DIGITALCRIMINAL** [comment]
I had to remove logging for the time being but it will get added back soon.

I can definitely add-in webhook triggers for other stages as well

**Comment by sintaxx** [comment]
sorry to hijack but not sure where to ask since this isn't exactly an issue but can i get an example of how to use the webhook in the config file ? i just see webhook: true and am not sure if i just replace true with "discord_webhook_URL" or what

**Comment by DIGITALCRIMINAL** [comment]
> sorry to hijack but not sure where to ask since this isn't exactly an issue but can i get an example of how to use the webhook in the config file ? i just see webhook: true and am not sure if i just replace true with "discord_webhook_URL" or what

You put the webhook, in the webhook key in the config.

**Comment by sintaxx** [comment]
> 
> 
> > sorry to hijack but not sure where to ask since this isn't exactly an issue but can i get an example of how to use the webhook in the config file ? i just see webhook: true and am not sure if i just replace true with "discord_webhook_URL" or what
> 
> You put the webhook, in the webhook key in the config.

my apologies, i found it, thank you !

**Comment by DIGITALCRIMINAL** [comment]
Latest commit.
