### ISSUE TITLE
Noob here - apologies

### ISSUE THREAD

**Issue by alexcreep** [DIGITALCRIMINAL/OnlyFans#71]
I followed all the instructions up until filling out the app-token, auth_id, auth_hash and user-agent - then what do I do? I double-clicked StartDatascraper and it opens and closes a command window and nothing happens. Is there something I'm missing?

**Comment by DIGITALCRIMINAL** [comment]
@alexcreep Are you using the latest release which is 3.4?

**Comment by alexcreep** [comment]
Hi! Yes, just downloaded from here just now.

**Comment by DIGITALCRIMINAL** [comment]
Did you installed the requirements?
