### ISSUE TITLE
my config.jason looks nothing like the video or text instructions. 

### ISSUE THREAD

**Issue by stevesdown** [DIGITALCRIMINAL/OnlyFans#715]
VIDEO TUTORIAL: as you can see from my config.jason, there is no place to enter "username", "fp", "sess" or "auth_id", "user_agent"

TEXT INSTRUCTIONS 
Fill in the Following
{"auth_id":"your_auth_id"}
{"sess":"your_sess_token"}
{"user-agent":"your_user-agent"}

*Here's the example of what's in my config.Jason file.*

"supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "",
        "auto_scrape_names": false,
        "auto_choice": "",
        "auto_scrape_apis": true,
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "text_length": 255,
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "blacklist_name": "",
        "webhook": true

**Comment by gsoxreptile** [comment]
The video is a bit old for how the program works now
How to do it now:
Open cmd from folder location and type "Pip install -r requirements.txt"
press enter
type "python start_ofd.py
press enter 
and now it says it has created the config file but press enter once more then it will create a profiles folder which is the new location you want to put in: your @ username, session id, AUTH id and your user agent, now save the file and go back to the program and it should work

**Comment by DIGITALCRIMINAL** [comment]
You didn't even read the readme. Sad!
