### ISSUE TITLE
458 videos, but only 453 downloaded

### ISSUE THREAD

**Issue by chenks** [DIGITALCRIMINAL/OnlyFans#718]
not sure if this is an issue or maybe something else.
but i used the script today to rip all videos from 1 profile, the profile has 458 videos, but the script only pulled down 453.

is there a way to know which 5 videos it didn't pull down?

**Comment by DIGITALCRIMINAL** [comment]
You have to figure out which videos it didn't download, it's probably paid or locked.

**Comment by chenks** [comment]
are there any logs that would show which ones failed?
all 458 videos are in the free section, and i can't see any that might be locked.

**Comment by DIGITALCRIMINAL** [comment]
Yes, in the metadata database you'll see a table called "medias". You can check which files are not downloaded by checking if the download column is set to 0 (0 = False, 1 = True)

**Comment by chenks** [comment]
hmm.. strange
every item in the media table has that column set to 1

**Comment by DIGITALCRIMINAL** [comment]
> hmm.. strange
> every item in the media table has that column set to 1

If you check in the other table, does the post row count equal to the posts count on site?

**Comment by chenks** [comment]
yes
3176 posts on the profile page
3176 rows in the posts table

**Comment by DIGITALCRIMINAL** [comment]
Try setting overwrite to True, it will force everything to download again except for files that have the same name and size

**Comment by chenks** [comment]
i'll give it a go.
with overwrite set to false, if i was to tell it to download all videos for a particular profile would it only download any new ones or re-download everything again?

**Comment by DIGITALCRIMINAL** [comment]
If overwrite is set to False, it won't download anything in the table that has downloaded set to True.
