### ISSUE TITLE
New OnlyFans feature: "Stories"

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#72]
OnlyFans seems to have a new feature that rips off Snapchat and Instagram's "Stories." Can the scraper be updated to download this content? AFAIK, the current version isn't picking them up.

**Comment by DIGITALCRIMINAL** [comment]
What does the "Stories" feature look like?

**Comment by DIGITALCRIMINAL** [comment]
Actually nevermind. I see the API. I'd have to wait for my account that I follow to put up a story unless you can provide me with a JSON sample.

https://onlyfans.com/api2/v2/users/USER_ID_HERE/stories?app-token=33d57ade8c02dbc5a333db99ff9ae26a

**Comment by avekifes** [comment]
How do I provide a JSON sample?

**Comment by DIGITALCRIMINAL** [comment]
Replace user_id_here in the link with the account's id number. Go to the link and copy the contents. Don't forget to remove your IP address.

**Comment by avekifes** [comment]
How do you get a user's ID?

**Comment by DIGITALCRIMINAL** [comment]
Actually, just go to their profile, open the Network Dev Tool and search for "stories?" and open that in the new tab

**Comment by avekifes** [comment]
I'm sending the JSON file to you via e-mail. It looks like a mess here.

**Comment by DIGITALCRIMINAL** [comment]
Done.

**Comment by Addest3** [comment]
Onlyfans slideshow/story content isn't being detected by the program as far as I can tell. 
Using v. 3.7.2
