### ISSUE TITLE
Downloads all of the subs...

### ISSUE THREAD

**Issue by mcangeli** [DIGITALCRIMINAL/OnlyFans#724]
Once I launch the script and select a subscription to download from, it appears that after it finishes downloading from that one it continues on downloading in the list (in no rhyme or reason).

IE: if I launch the script and select a username out of the list to scrape, it appears to scrape and download it but instead of going back to the menu and allowing me to pick another, it continues downloading from other usernames.

**Comment by mcangeli** [comment]
Though in looking at it, maybe what I am seeing is the new process to go through and re "scrape" the sites to see what has changed?

**Comment by DIGITALCRIMINAL** [comment]
It's doing what it's supposed to do.
