### ISSUE TITLE
Never had Auth issues until 6.2.3

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#725]
I logged in once with 6.2.3 yesterday and it went fine.

But now today I get this. I updated my sesh and user agent with no luck.

![image](https://user-images.githubusercontent.com/20603861/104791847-23943f00-576a-11eb-9706-1d2607800c91.png)

**Comment by andradre** [comment]
i also have this problem, how to work around this issue?

**Comment by bobsage123** [comment]
I had to delete my profile and settings folders and recreate from scratch.
