### ISSUE TITLE
'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by hiimdad** [DIGITALCRIMINAL/OnlyFans#729]
I just finished the tutorial up to double click start_ofd.py and this what I get:

Site: 0 = onlyfans | x = Exit
0
Session IP: xxx.xxx.xx.xxx (I edited this out idk if someone can use it)

Choose Profile
Names: Username = username  |  0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Traceback (most recent call last):
  File "E:\Program Files (x86)\OF Scraper\OnlyFans-6.2.3\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "E:\Program Files (x86)\OF Scraper\OnlyFans-6.2.3\datascraper\main_datascraper.py", line 85, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "E:\Program Files (x86)\OF Scraper\OnlyFans-6.2.3\modules\onlyfans.py", line 304, in paid_content_scraper
    author = paid_content.get("author")
AttributeError: 'str' object has no attribute 'get'

**Comment by mistuhryan** [comment]
I had the same problem. I changed my public IP, redownloaded the master ZIP. re-entered the auth settings and it connected for me right away

**Comment by DIGITALCRIMINAL** [comment]
Fixed
