### ISSUE TITLE
infinite retrying loop

### ISSUE THREAD

**Issue by reashetyrr** [DIGITALCRIMINAL/OnlyFans#736]
Hi,

i noticed that while trying to make a backup of all subscriptions the downloader would end up in an infinite: "Missing 100 posts... retrying..." loop.

can we make it so it tried that just an x amount of times before it just skips that profile?

**Comment by DIGITALCRIMINAL** [comment]
It's not infinite. It does it out of 100 times.

**Comment by reashetyrr** [comment]
I had it run for over 3hours....
