### ISSUE TITLE
All Content Showing As Free

### ISSUE THREAD

**Issue by kirsed** [DIGITALCRIMINAL/OnlyFans#737]
All content I download is showing as free and being placed in free folders. When I check the posts.db it's all showing as free as well. All content that requires a subscription is considered paid correct? If so all the content that I have scrapped should be considered paid. The profiles I've subscribed to only have paid feeds. 
If I've made the incorrect assumption and that the paid value is only assigned to things you have to individually purchase than never mind close this issue and I'm dumb.

**Comment by DIGITALCRIMINAL** [comment]
I guess you didn't read the readme.
