### ISSUE TITLE
No module named "PIL"

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINAL/OnlyFans#74]
In trying to run OnlyFans downloader on my Linux box, I just keep getting the same error message:

`python StartDatascraper.py
Traceback (most recent call last):
  File "StartDatascraper.py", line 9, in <module>
    import modules.helpers as helpers
  File "/media/sdw1/holonet81/OnlyFans/modules/helpers.py", line 8, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'`

Not sure what I'm missing or doing wrong. I already ran install requirements and everything is accounted for there. Any help here would be greatly appreciated. Thanks

**Comment by DIGITALCRIMINAL** [comment]
Are you using the latest release? 3.4?

**Comment by DIGITALCRIMINAL** [comment]
Also
pip install Pillow

**Comment by ElusiveZatchmo** [comment]
Thanks!

**Comment by DIGITALCRIMINAL** [comment]
Also thanks. I have added it to the requirements c:
