### ISSUE TITLE
FileExistsError

### ISSUE THREAD

**Issue by shotgun469** [DIGITALCRIMINAL/OnlyFans#745]
Based on what I've read, this is an awesome program. I also read that you wish to remain anon so there is no Paypal o anything to donate. Thanks a lot for building this program.

Here is what the console tells me. I can't seem to fix this to make it work. 

I filled the auth_id, sess, app_token and user_agent after the it instructs me to do so before pressing 'enter to continue'.

I modified the paths from the trace and my ip but I hope you get the problem and could throw in any hints/help to make it work.

Thanks again!

/.profiles/OnlyFans/default/auth.json has been created. Fill in the relevant details and then press enter to continue.
Site: 0 = onlyfans | x = Exit
0
Session IP: xx.xxx.xxxx.xxx

Traceback (most recent call last):
  File "/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/datascraper/main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "/helpers/main_helper.py", line 560, in process_profiles
    export_data(
  File "/helpers/main_helper.py", line 616, in export_data
    os.makedirs(directory, exist_ok=True)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/.profiles/OnlyFans/.DS_Store'

**Comment by shotgun469** [comment]
Hi people!

Any help on what am I doing wrong to make the program run?

**Comment by burner4898r932** [comment]
Tell me why I made a burner GitHub account for this. 

cd into your project directory and recursively delete the system .DS_Store files with this command

`find . -name ".DS_Store" -delete`

**Comment by DIGITALCRIMINAL** [comment]
Fixed in the latest commit.

**Comment by shotgun469** [comment]
Thanks!

I did the "find delete" command and went through.

Thanks DigitalCriminal for fixing the issue.
