### ISSUE TITLE
I keep getting nothing to scrape

### ISSUE THREAD

**Issue by Bigchaor** [DIGITALCRIMINAL/OnlyFans#746]
I keep looping withthis error:

Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit

**Comment by Backaache** [comment]
Try cloning the master branch.

**Comment by kingtiger20** [comment]
Also having this issue with the master branch

**Comment by chidi9901** [comment]
Your "active" is set to "true"?

**Comment by bluebower** [comment]
Thanks @chidi9901, setting `"active": true` in auth.json worked for me.

**Comment by Idesmi** [comment]
Why did you close it? The issue is not solved.

**Comment by bluebower** [comment]
I had the same error as OP, and a solution was posted.

**Comment by DIGITALCRIMINAL** [comment]
> Why did you close it? The issue is not solved.
> 
> auth.json keeps getting rewritten with "default" as user

This has been talked about 1000000000000000000 times. Just use the search function.
