### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory when downloading content

### ISSUE THREAD

**Issue by th3resident** [DIGITALCRIMINAL/OnlyFans#75]
While downloading content from OF the downloads will fail after a while. I've set overwrite_files to true and false, I tried only downloading videos or downloading all content. If I do all content it usually fails on Images, if I do videos only it will fail part way through downloading videos

> Traceback (most recent call last):
>   File "./StartDatascraper.py", line 109, in <module>
>     x.download_media(*arg)
>   File "/home/th3resident/OnlyFans/modules/onlyfans.py", line 276, in download_media
>     pool.starmap(download, product(
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
>     raise self._value
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "/home/th3resident/OnlyFans/modules/onlyfans.py", line 261, in download
>     with open(directory, 'wb') as f:
> IsADirectoryError: [Errno 21] Is a directory: '/mnt/captured//onlyfans/[REDACTED]/Videos/'

**Comment by DIGITALCRIMINAL** [comment]
@th3resident are you using the latest release?

**Comment by th3resident** [comment]
running latest version from master

**Comment by DIGITALCRIMINAL** [comment]
Use this
https://github.com/DIGITALCRIMINAL/OnlyFans/releases/tag/v3.4

**Comment by th3resident** [comment]
Same issue with 3.4

> Traceback (most recent call last):
>   File "./StartDatascraper.py", line 102, in <module>
>     x.download_media(*arg)
>   File "/home/th3resident/OnlyFans-3.4/modules/onlyfans.py", line 257, in download_media
>     pool.starmap(download, product(media_set, [session], [directory], [username]))
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
>     raise self._value
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "/home/th3resident/OnlyFans-3.4/modules/onlyfans.py", line 241, in download
>     with open(directory, 'wb') as f:
> IsADirectoryError: [Errno 21] Is a directory: '/mnt/captured//onlyfans/[REDACTED/Images/'

**Comment by DIGITALCRIMINAL** [comment]
Will hopefully be fixed in the next commit @th3resident
