### ISSUE TITLE
Scraper stopping on one model only

### ISSUE THREAD

**Issue by ProjektPremium** [DIGITALCRIMINAL/OnlyFans#754]
What would make the scraper stop at the exact same point/file every time? After deleting the scraped data that it didn't complete after leaving for many hours, what could be the problem out of curiosity? Her subscription is going to expire shortly and I can't get the complete scrape.

heathercarolin is the model name. Is it because there is so much content?

**Comment by DIGITALCRIMINAL** [comment]
> What would make the scraper stop at the exact same point/file every time? After deleting the scraped data that it didn't complete after leaving for many hours, what could be the problem out of curiosity? Her subscription is going to expire shortly and I can't get the complete scrape.
> 
> heathercarolin is the model name. Is it because there is so much content?

Are you using a proxy?

**Comment by James-MF-Thomas** [comment]
Have you tried doing individual api's one at a time?

**Comment by ProjektPremium** [comment]
> 
> 
> > What would make the scraper stop at the exact same point/file every time? After deleting the scraped data that it didn't complete after leaving for many hours, what could be the problem out of curiosity? Her subscription is going to expire shortly and I can't get the complete scrape.
> > heathercarolin is the model name. Is it because there is so much content?
> 
> Are you using a proxy?

No to proxies.

> 
> 
> Have you tried doing individual api's one at a time?

Yes, it hits a certain number of files and a particular file name and then just stops dead in it's tracks. Even deleting the data and doing a clean scrape stops at the same point.

**Comment by ProjektPremium** [comment]
This is in the latest commit, version 6.2.4

Thought I would drop down a couple of versions and tried different ones, still same thing. Problems with scraping her.

**Comment by James-MF-Thomas** [comment]
What process is it executing? Downloading, renaming, metadata?

**Comment by ProjektPremium** [comment]
Problems on all fronts. It's when it's doing the pictures API. I can download videos fine, once it gets to images it hits the wall.

**Comment by DIGITALCRIMINAL** [comment]
What is your filename format

**Comment by ProjektPremium** [comment]
"filename_format": "{filename}.{ext}",

**Comment by ProjektPremium** [comment]
This is the results of the video scrape;
INFO downloads Path: <directory>\.sites\OnlyFans\heathercarolin\Posts\Free\Videos\0gmmtrig6jxh6n6pivjq9_source.mp4
Archive Completed in 2.3 Minutes
Pausing scraper for 0 seconds.

This is where it hangs on the images
FOUND: <directory>\.sites\OnlyFans\heathercarolin\Posts\Free\Images

FOUND: <directory>\.sites\OnlyFans\heathercarolin\Posts\Free\Images

Type: Archived
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Found: Archived
Type: Messages
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Found: Messages
Scrape Completed

Download Processing
Name: heathercarolin | Type: Posts | Directory: <directory>\.sites\OnlyFans
Downloading 1145 Images

**Comment by DIGITALCRIMINAL** [comment]
How many hours did you leave the scraper running

**Comment by ProjektPremium** [comment]
Can't be too sure but at least 90 minutes to 2 hours.

I'm going to delete the data and do a fresh scrape and just leave it and see if it does it over the course of however long it's left open.

I can also see from my network monitor that it's not using any bandwidth.

**Comment by DIGITALCRIMINAL** [comment]
Just let the scraper run...

**Comment by ProjektPremium** [comment]
I let the scraper run and it took a total of 12 hours. So now I've just blacklisted her.
