### ISSUE TITLE
Error with synology related attribute files

### ISSUE THREAD

**Issue by E0911CD45B19686** [DIGITALCRIMINAL/OnlyFans#755]
I'm running this tool on a Synology NAS using docker. I also access the files on a Mac via NFS. This gives me the pleasure of polluting my filesystem with not only `.DS_Store` files but also `@eaDir` directories!

I'm hitting this error with the latest 6.2.4 release:

> user_agent required for: @eaDirTraceback (most recent call last):
>   File "/usr/src/app/./start_ofd.py", line 40, in <module>
>     main_datascraper.start_datascraper(json_config, site_name_lower)
>   File "/usr/src/app/datascraper/main_datascraper.py", line 48, in start_datascraper
>     apis = main_helper.process_profiles(
>   File "/usr/src/app/helpers/main_helper.py", line 573, in process_profiles
>     api.set_auth_details(
>   File "/usr/src/app/apis/onlyfans/onlyfans.py", line 507, in set_auth_details
>     input(
> EOFError: EOF when reading a line
> 
> Traceback (most recent call last):
>   File "/usr/src/app/./start_ofd.py", line 40, in <module>
>     main_datascraper.start_datascraper(json_config, site_name_lower)
>   File "/usr/src/app/datascraper/main_datascraper.py", line 48, in start_datascraper
>     apis = main_helper.process_profiles(
>   File "/usr/src/app/helpers/main_helper.py", line 573, in process_profiles
>     api.set_auth_details(
>   File "/usr/src/app/apis/onlyfans/onlyfans.py", line 507, in set_auth_details
>     input(
> EOFError: EOF when reading a line
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/app/./start_ofd.py", line 52, in <module>
>     input()
> EOFError: EOF when reading a line

**Comment by DIGITALCRIMINAL** [comment]
I've merged your PR 👍

**Comment by James-MF-Thomas** [comment]
"  defaults write com.apple.desktopservices DSDontWriteNetworkStores false  "

To stop creating .DS_Store files
