### ISSUE TITLE
Can this script download paid things for free?

### ISSUE THREAD

**Issue by GBBranco** [DIGITALCRIMINAL/OnlyFans#758]
I signed up for a profile, she has a photo that costs 3 dollars, I didn't pay, can I download this photo with the script or do I need to pay for the photo to download?

sorry for the english i'm using google translator.
![ofans](https://user-images.githubusercontent.com/77861015/106069891-356ad000-60e2-11eb-8a4e-02d5a5fca99d.png)

**Comment by DIGITALCRIMINAL** [comment]
Pay.

**Comment by GBBranco** [comment]
I thank you for your understanding, I am Brazilian and do not understand much of English, any content from onlyfans costs 5 times more for us Brazilians.

**Comment by James-MF-Thomas** [comment]
Your translator works like a pair of tits.

(Or whatever you call female breast in Portuguese or Brazil)
