### ISSUE TITLE
Scraper not detecting

### ISSUE THREAD

**Issue by g0dzcsgo** [DIGITALCRIMINAL/OnlyFans#759]
Basically i have like 10 subscriptions, but whenever i try to scrape it just auth's 10 times then says there's nothing to scrape??

**Comment by g0dzcsgo** [comment]
And sometimes when i swap auth details, it just says theres no content to scrape when theres like 10+??????

**Comment by g0dzcsgo** [comment]
Yep still getting this issue.

**Comment by chidi9901** [comment]
Check every line carefully in your auth.json! "user-agent" could get updated. "sess" could get updated. I can still say that the tool works as of now.

**Comment by g0dzcsgo** [comment]
Everything is fine, i've tried it like 5 times

**Comment by g0dzcsgo** [comment]
Auth.json is correct.... but it just auths 10 times and then says there is "NOTHING TO SCRAPE"
