### ISSUE TITLE
Still getting 10 auths then nothing

### ISSUE THREAD

**Issue by g0dzcsgo** [DIGITALCRIMINAL/OnlyFans#761]
Already tried 5 different of my VPS'es, the auth.json is correct i've triple quadraple checked it.... but it still auth's 10 times wtf is this?

Like sometimes it works smooth, now it doesn't? And i really need for this to work.... holy fuck

**Comment by scgreenhalgh** [comment]
Check your "user_agent" string as if your browser recently upgraded and there is a mismatch between the logged-in browser and the python scraper it will not auth.

**Comment by g0dzcsgo** [comment]
Should i just copy it straight from chrome?

**Comment by scgreenhalgh** [comment]
Yup, same place you’d find your session cookie (or a couple of lines down). Please let us know if that worked for you when you do it!

**Comment by DIGITALCRIMINAL** [comment]
Use the discussions instead.
