### ISSUE TITLE
AttributeError : Stories

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#763]
![image](https://user-images.githubusercontent.com/58760178/106358844-ad9ce580-62dc-11eb-934a-65e8e04c5ad8.png)

Currently using 675749e, I'm having this error pop up at some point

**Comment by DIGITALCRIMINAL** [comment]
Which model

**Comment by jp1151419** [comment]
It happened on a couple, I started another run and will let you know an example.

**Comment by jp1151419** [comment]
> 
> 
> Which model

It happened with https://onlyfans.com/mercyfeetish

**Comment by DIGITALCRIMINAL** [comment]
I was able to download it with no errors

**Comment by jp1151419** [comment]
Yeah the run I started an hour ago is still running well. Maybe it was a bug on the OF side yesterday.
