### ISSUE TITLE
Limit on shown subscriptions?

### ISSUE THREAD

**Issue by g0dzcsgo** [DIGITALCRIMINAL/OnlyFans#767]
Basically, i got more than 40 subscriptions but its only showing 38 of them? Is this a limitation with the scraper?

Regards.

**Comment by DIGITALCRIMINAL** [comment]
Shouldn't be any limitation, maybe you changed something in the config related to subscriptions

**Comment by g0dzcsgo** [comment]
Not that i know of, its all default but it seems no more subscriptions are showing up :/

**Comment by ProjektPremium** [comment]
Use this
`https://onlyfans.com/my/subscriptions/active`

Check if the same amount of accounts are active as the amount you are subscribed to. Sometimes people deactivate their accounts and you don't notice it.
