### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by NathanIfinity** [DIGITALCRIMINAL/OnlyFans#769]
Ever since the update i keep getting auth error everytime I launch: start_ofd.py

Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.

tried multiple time starting from scratch everytime and get the same result.

**Comment by DIGITALCRIMINAL** [comment]
I can't do anything unless you email your auth details.

**Comment by NathanIfinity** [comment]
where can I email? and i send the auth.json?

**Comment by DIGITALCRIMINAL** [comment]
> where can I email? and i send the auth.json?

I don't need the auth.json, I'd need the email and password to try it myself.
