### ISSUE TITLE
Image previews for Pay-To-Unlock content gets put in the PAID folder.

### ISSUE THREAD

**Issue by goodboi69** [DIGITALCRIMINAL/OnlyFans#772]
When scraping content from messages, content previews attached to un-paid posts gets downloaded into the 'Paid' folder. Would it be possible to have that content download into the 'Free' folder instead? This would be nicer to keep the content separated.

![Screenshot_2021-02-01 OnlyFans](https://user-images.githubusercontent.com/43517545/106500334-aff37100-648f-11eb-8f5a-e02fce9ae09f.png)

**Comment by DIGITALCRIMINAL** [comment]
Thanks, and done, the script will move it to the "Free" folder automatically.
