### ISSUE TITLE
"There's nothing to scrape"

### ISSUE THREAD

**Issue by Joakimgreenday** [DIGITALCRIMINAL/OnlyFans#773]
Worked like a charm just like 2 hours ago. Did they update something?
![image](https://user-images.githubusercontent.com/23558072/106540046-6e9aaa00-64ff-11eb-98bc-605b0ef19e51.png)

I recently figured out that onlyfans changed so their session is being updated every 5-10 seconds, which also leads to your account being logged out. Really annoying. I don't know if it was like this before, but it's not working right now. Worked 2 hours ago as said. Hope there's a fix for this!

**Comment by ProjektPremium** [comment]
Check to see if your version of your browser is up to date.
