### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by j-ktz** [DIGITALCRIMINAL/OnlyFans#777]
I've got it installed and the auth filled out in profiles. When I run start_ofd.py, I press 0 for OF and then get this error. Any ideas?
<img width="807" alt="screenshot 2021-02-02 at 6 27 17 PM" src="https://user-images.githubusercontent.com/59346628/106677937-b5cc7d80-6587-11eb-8ff3-3607ff1e75f0.png">

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit.

**Comment by j-ktz** [comment]
I'm not sure what that means? Sorry.

On February 3, 2021, GitHub <notifications@github.com> wrote:
> Use the latest commit.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DIGITALCRIMINAL/OnlyFans/issues/777#issuecomment-
773005057>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5RHLDHBZO7XSHOYSZ2TS5IJURANCNFSM4W726GLA>.

**Comment by DIGITALCRIMINAL** [comment]
> I'm not sure what that means? Sorry.
> On February 3, 2021, GitHub ***@***.***> wrote: Use the latest commit.
> — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <[#777 (comment)](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/777#issuecomment)- 773005057>, or unsubscribe <https://github.com/notifications/unsubscribe- auth/AOEY5RHLDHBZO7XSHOYSZ2TS5IJURANCNFSM4W726GLA>.

Download from master

**Comment by j-ktz** [comment]
I did download the master. 

On February 4, 2021, GitHub <notifications@github.com> wrote:
> > I'm not sure what that means? Sorry.
> >  On February 3, 2021, GitHub @.***> wrote: Use the latest commit.
> >  — You are receiving this because you authored the thread. Reply to
> > this email directly, view it on GitHub <#777 (comment)
> > <https://github.com/DIGITALCRIMINAL/OnlyFans/issues/777#issuecomment>-
> > 773005057>, or unsubscribe
> > <<https://github.com/notifications/unsubscribe->
> > auth/AOEY5RHLDHBZO7XSHOYSZ2TS5IJURANCNFSM4W726GLA>.
> >
>
> Download from master
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DIGITALCRIMINAL/OnlyFans/issues/777#issuecomment-
773360286>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5RGV6A5RIZX6NQYBROTS5KW4BANCNFSM4W726GLA>.
