### ISSUE TITLE
question about onlyfans

### ISSUE THREAD

**Issue by markte22** [DIGITALCRIMINAL/OnlyFans#778]
HI DIGITAL CRIMINAL i have got a question for you about this software is it possible to extract a bank card what is added to a onlyfans account and extract it to a text document file can that be done if so how i want to extract a bank card from a onlyfans account to a text document file can that be done with your software or can it be done through the onlyfans site with maybe a other software

**Comment by DIGITALCRIMINAL** [comment]
You're asking me to help you commit BANK FRAUD? Stop.
