### ISSUE TITLE
FileNotFound Error

### ISSUE THREAD

**Issue by valdearg** [DIGITALCRIMINAL/OnlyFans#784]
Updated to the latest commit today, spammed with thousands of errors like the below:

```
Traceback (most recent call last):
  File "C:\Python\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Archived\\Posts\\Videos\\22966993 (11-05-2020)\\5eb8a51f03f2f558973f7_source.mp4' -> 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Posts\\Videos\\22966993 (11-05-2020)\\5eb8a51f03f2f558973f7_source.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "C:\Python\Python39\lib\shutil.py", line 820, in move
    copy_function(src, real_dst)
  File "C:\Python\Python39\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Posts\\Videos\\22966993 (11-05-2020)\\5eb8a51f03f2f558973f7_source.mp4'
Traceback (most recent call last):
  File "C:\Python\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Archived\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg' -> 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "C:\Python\Python39\lib\shutil.py", line 820, in move
    copy_function(src, real_dst)
  File "C:\Python\Python39\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg'
```

Ran the scraper yesterday and no errors.

**Comment by headphonia** [comment]
I'm getting the same error.

**Comment by RonnieBlaze** [comment]
I am getting a similar error also with the current comment.

valdearg, what file_directory_format are you using? i like how you have the date in the folder names

**Comment by valdearg** [comment]
```       "file_directory_format": "OnlyFans-new2\\{username}\\{api_type}\\{media_type}\\{post_id} ({date})", ```

**Comment by RonnieBlaze** [comment]
thanks!, not sure if i should change mine since so many files will not be sorted

**Comment by mikeymatrix70** [comment]
This was disastrous

**Comment by SteveJSzabo** [comment]
I'm also experiencing this bug

**Comment by DIGITALCRIMINAL** [comment]
Does this happen for paid messages

**Comment by Kurosaki22** [comment]
For me the files do not exist at the new place. (deleted the old files in the old location in hope to fix the issue)
So normally it should create new ones right?

For me the error appears when it is scraping an account with paid content

**Comment by DIGITALCRIMINAL** [comment]
No... don't delete the files. I've fixed it on my end, but I need to do a couple of things.

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed now

**Comment by headphonia** [comment]
I'm getting this with the latest commit.

`Traceback (most recent call last):
  File "/Volumes/OF Scrapper/start_ofd.py", line 40, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Volumes/OF Scrapper/datascraper/main_datascraper.py", line 113, in start_datascraper
    paid_content = module.paid_content_scraper(apis, identifiers)
  File "/Volumes/OF Scrapper/modules/onlyfans.py", line 360, in paid_content_scraper
    new_metadata = main_helper.format_media_set(unrefined_set)
  File "/Volumes/OF Scrapper/helpers/main_helper.py", line 102, in format_media_set
    os.makedirs(directory, exist_ok=True)
  File "/Users/username/.pyenv/versions/3.9.0/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/username/.pyenv/versions/3.9.0/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/username/.pyenv/versions/3.9.0/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/username/.pyenv/versions/3.9.0/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/model'


`

**Comment by Nostang3** [comment]
I'm also still getting this with latest commits

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' -> 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
```

**Comment by DIGITALCRIMINAL** [comment]
> I'm also getting this with latest commits
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
>     os.rename(src, real_dst)
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' -> 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "G:\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
>     moved = shutil.move(old_filepath, new_filepath)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
>     copy_function(src, real_dst)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
>     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> ```

Does the file exist

**Comment by Nostang3** [comment]
> > I'm also getting this with latest commits
> > ```
> > Traceback (most recent call last):
> >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
> >     os.rename(src, real_dst)
> > FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' -> 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "G:\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
> >     moved = shutil.move(old_filepath, new_filepath)
> >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
> >     copy_function(src, real_dst)
> >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
> >     copyfile(src, dst, follow_symlinks=follow_symlinks)
> >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
> >     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > FileNotFoundError: [Errno 2] No such file or directory: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > ```
> 
> Does the file exist
No. There is no videos directory. Is it having trouble creating the directory? That's not something that I have to do right?

**Comment by DIGITALCRIMINAL** [comment]
> > > I'm also getting this with latest commits
> > > ```
> > > Traceback (most recent call last):
> > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
> > >     os.rename(src, real_dst)
> > > FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' -> 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "G:\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
> > >     moved = shutil.move(old_filepath, new_filepath)
> > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
> > >     copy_function(src, real_dst)
> > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
> > >     copyfile(src, dst, follow_symlinks=follow_symlinks)
> > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
> > >     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > > FileNotFoundError: [Errno 2] No such file or directory: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > ```
> > 
> > 
> > Does the file exist
> > No. There is no videos directory. Is it having trouble creating the directory? That's not something that I have to do right?

Did you delete the folder before?

**Comment by iamspecial** [comment]
Also getting the same errors. Everything worked flawlessly a few builds ago. And i haven't changed anything. I've followed the "missing" files myself, and they're exactly where the console is saying they aren't.

```
Traceback (most recent call last):
  File "C:\Users\username\scoop\apps\python39\current\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\Media\\NSFW\\Temp\\OnlyFans\\.sites\\OnlyFans\\tanamongeau\\Posts\\Free\\Videos\\2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4' -> 'F:\\Media\\NSFW\\Temp\\OnlyFans\\.sites\\OnlyFans\\tanamongeau\\Posts\\Paid\\Videos\\2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Media\NSFW\Temp\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "C:\Users\username\scoop\apps\python39\current\lib\shutil.py", line 820, in move
    copy_function(src, real_dst)
  File "C:\Users\username\scoop\apps\python39\current\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\username\scoop\apps\python39\current\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Media\\NSFW\\Temp\\OnlyFans\\.sites\\OnlyFans\\tanamongeau\\Posts\\Paid\\Videos\\2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4'
```

**Comment by DIGITALCRIMINAL** [comment]
> Also getting the same errors. Everything worked flawlessly a few builds ago. And i haven't changed anything. I've followed the "missing" files myself, and they're exactly where the console is saying they aren't.
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\username\scoop\apps\python39\current\lib\shutil.py", line 806, in move
>     os.rename(src, real_dst)
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\Media\\NSFW\\Temp\\OnlyFans\\.sites\\OnlyFans\\tanamongeau\\Posts\\Free\\Videos\\2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4' -> 'F:\\Media\\NSFW\\Temp\\OnlyFans\\.sites\\OnlyFans\\tanamongeau\\Posts\\Paid\\Videos\\2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "F:\Media\NSFW\Temp\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
>     moved = shutil.move(old_filepath, new_filepath)
>   File "C:\Users\username\scoop\apps\python39\current\lib\shutil.py", line 820, in move
>     copy_function(src, real_dst)
>   File "C:\Users\username\scoop\apps\python39\current\lib\shutil.py", line 435, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "C:\Users\username\scoop\apps\python39\current\lib\shutil.py", line 264, in copyfile
>     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Media\\NSFW\\Temp\\OnlyFans\\.sites\\OnlyFans\\tanamongeau\\Posts\\Paid\\Videos\\2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4'
> ```

But are they in the model's folder?

**Comment by iamspecial** [comment]
Sorry, I'm not following. The file that says isn't found 

`F:\Media\NSFW\Temp\OnlyFans\.sites\OnlyFans\tanamongeau\Posts\Free\Videos\2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4`

exists exactly there. 

and my config is this for of

```
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{date}_{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
```

Is there something I've messed up or not configured properly in the latest commit?

**Comment by DIGITALCRIMINAL** [comment]
> Sorry, I'm not following. The file that says isn't found
> 
> `F:\Media\NSFW\Temp\OnlyFans\.sites\OnlyFans\tanamongeau\Posts\Free\Videos\2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4`
> 
> exists exactly there.
> 
> and my config is this for of
> 
> ```
>         "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
>         "filename_format": "{date}_{filename}.{ext}",
>         "metadata_directories": [
>           ".sites"
>         ],
>         "metadata_directory_format": "{site_name}\\{username}\\Metadata",
>         "delete_legacy_metadata": false,
>         "text_length": 255,
>         "video_quality": "source",
>         "overwrite_files": false,
>         "date_format": "%Y-%m-%d",
>         "ignored_keywords": [],
>         "ignore_type": "",
>         "blacklist_name": "",
>         "webhook": true
>       }
> ```
> 
> Is there something I've messed up or not configured properly in the latest commit?

That's fine.

A couple of days ago I updated the script to separate preview content that appears in paid content.

Do you know if this is actually preview content? `2021-01-21_ocr8dQRqj7YKSMwKeLGbxLwHyLXQ8yCd.mp4`

**Comment by omnicentrist** [comment]
Just looked, the post is now *locked* on her page, behind a paywall. Not sure how I have it. Also, the file only exists in the Free folder, so the first path is invalid.

**Comment by DIGITALCRIMINAL** [comment]
> Just looked, the post is now _locked_ on her page, behind a paywall. Not sure how I have it. Also, the file only exists in the Free folder, so the first path is invalid.

Ah okay but is there a free preview on that paid post?

**Comment by omnicentrist** [comment]
Nope, no preview

**Comment by Nostang3** [comment]
> > > > I'm also getting this with latest commits
> > > > ```
> > > > Traceback (most recent call last):
> > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
> > > >     os.rename(src, real_dst)
> > > > FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' -> 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > > 
> > > > During handling of the above exception, another exception occurred:
> > > > 
> > > > Traceback (most recent call last):
> > > >   File "G:\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
> > > >     moved = shutil.move(old_filepath, new_filepath)
> > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
> > > >     copy_function(src, real_dst)
> > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
> > > >     copyfile(src, dst, follow_symlinks=follow_symlinks)
> > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
> > > >     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > > > FileNotFoundError: [Errno 2] No such file or directory: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > > ```
> > > 
> > > 
> > > Does the file exist
> > > No. There is no videos directory. Is it having trouble creating the directory? That's not something that I have to do right?
> 
> Did you delete the folder before?

No. I never touch the folders. I leave all that up to the script.

**Comment by Nostang3** [comment]
> 
> 
> > > > I'm also getting this with latest commits
> > > > ```
> > > > Traceback (most recent call last):
> > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
> > > >     os.rename(src, real_dst)
> > > > FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' -> 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > > 
> > > > During handling of the above exception, another exception occurred:
> > > > 
> > > > Traceback (most recent call last):
> > > >   File "G:\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
> > > >     moved = shutil.move(old_filepath, new_filepath)
> > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
> > > >     copy_function(src, real_dst)
> > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
> > > >     copyfile(src, dst, follow_symlinks=follow_symlinks)
> > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
> > > >     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > > > FileNotFoundError: [Errno 2] No such file or directory: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > > ```
> > > 
> > > 
> > > Does the file exist
> > > No. There is no videos directory. Is it having trouble creating the directory? That's not something that I have to do right?
> 
> Did you delete the folder before?
Update: So I manually created the 'Videos' folder and the scripted worked...for awhile. The script then DELETED the 'Videos' folder and threw up the same error.

**Comment by DIGITALCRIMINAL** [comment]
> > > > > I'm also getting this with latest commits
> > > > > ```
> > > > > Traceback (most recent call last):
> > > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
> > > > >     os.rename(src, real_dst)
> > > > > FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' -> 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > > > 
> > > > > During handling of the above exception, another exception occurred:
> > > > > 
> > > > > Traceback (most recent call last):
> > > > >   File "G:\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
> > > > >     moved = shutil.move(old_filepath, new_filepath)
> > > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
> > > > >     copy_function(src, real_dst)
> > > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
> > > > >     copyfile(src, dst, follow_symlinks=follow_symlinks)
> > > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
> > > > >     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > > > > FileNotFoundError: [Errno 2] No such file or directory: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > > > ```
> > > > 
> > > > 
> > > > Does the file exist
> > > > No. There is no videos directory. Is it having trouble creating the directory? That's not something that I have to do right?
> > 
> > 
> > Did you delete the folder before?
> 
> Update: So I manually created the 'Videos' folder and the scripted worked...for awhile. The script then DELETED the 'Videos' folder and threw up the same error.

The videos folder was empty?

**Comment by Nostang3** [comment]
> 
> 
> > > > > > I'm also getting this with latest commits
> > > > > > ```
> > > > > > Traceback (most recent call last):
> > > > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
> > > > > >     os.rename(src, real_dst)
> > > > > > FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' -> 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > > > > 
> > > > > > During handling of the above exception, another exception occurred:
> > > > > > 
> > > > > > Traceback (most recent call last):
> > > > > >   File "G:\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_directories
> > > > > >     moved = shutil.move(old_filepath, new_filepath)
> > > > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
> > > > > >     copy_function(src, real_dst)
> > > > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
> > > > > >     copyfile(src, dst, follow_symlinks=follow_symlinks)
> > > > > >   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
> > > > > >     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > > > > > FileNotFoundError: [Errno 2] No such file or directory: 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4'
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Does the file exist
> > > > > No. There is no videos directory. Is it having trouble creating the directory? That's not something that I have to do right?
> > > 
> > > 
> > > Did you delete the folder before?
> > 
> > 
> > Update: So I manually created the 'Videos' folder and the scripted worked...for awhile. The script then DELETED the 'Videos' folder and threw up the same error.
> 
> The videos folder was empty?

It deleted the folder AND file completely. When I do manually create the folder it will download the file in the error I posted but then in a subsequent run will delete the folder and it's contents.

**Comment by DIGITALCRIMINAL** [comment]
You can try the latest commit

**Comment by valdearg** [comment]
Same error unfortunately

```
Traceback (most recent call last):
  File "C:\Python\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Archived\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg' -> 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 90, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "C:\Python\Python39\lib\shutil.py", line 820, in move
    copy_function(src, real_dst)
  File "C:\Python\Python39\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg'

Traceback (most recent call last):
  File "C:\Python\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Archived\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg' -> 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg'
```

'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Archived\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg' - Exists

'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\mikomihokina\\Posts\\Images\\51744068 (23-09-2020)\\1080x1440_fc4762ef6c62c461ce2734cb205dcc91.jpg' - folder does not exist

**Comment by Kurosaki22** [comment]
He recommended above not to delete the metadata files.
But it was already too late for me back then.

But I hadnt any single issue since then. the script created new metadata files in the new location and updated the creationtime.
No issue since then for me

**Comment by Nostang3** [comment]
Same for me as before. I'll create the Videos folder, it will run once, delete the folder including file(s), then error out on a subsequent run with the same error.

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by Nostang3** [comment]
The program runs without error( 3 consecutive runs). Before it was trying to download 'G:\\OnlyFans\\.sites\\OnlyFans\\omgcosplay\\Archived\\Posts\\Free\\Videos\\0glrkj1lf9pe1oy58jbsu_source.mp4' but now it no longer tries to download that file. So my question is, was the file it was trying to download and put in that folder a mistake? I looked in her Posts/Free/Videos and that video is present there.

**Comment by DIGITALCRIMINAL** [comment]
> The program runs without error( 3 consecutive runs). Before it was trying to download 'G:\OnlyFans\.sites\OnlyFans\omgcosplay\Archived\Posts\Free\Videos\0glrkj1lf9pe1oy58jbsu_source.mp4' but now it no longer tries to download that file. So my question is, was the file it was trying to download and put in that folder a mistake? I looked in her Posts/Free/Videos and that video is present there.

Depend... If the post is archived then it should actually be in Archived/Posts and not /Posts

**Comment by Nostang3** [comment]
> Depend... If the post is archived then it should actually be in Archived/Posts and not /Posts

I don't see any archived videos for her. So not sure why it was trying to put it in Archived/Posts in stead of /Posts. 

Also it's ran a few more times without issues. I have it on a 720 sec pause.

**Comment by DIGITALCRIMINAL** [comment]
> > Depend... If the post is archived then it should actually be in Archived/Posts and not /Posts
> 
> I don't see any archived videos for her. So not sure why it was trying to put it in Archived/Posts in stead of /Posts.
> 
> Also it's ran a few more times without issues. I have it on a 720 sec pause.

This the post you were trying to download, it's archived. Was this a paid post?
https://onlyfans.com/51744068/mikomihokina

**Comment by Nostang3** [comment]
> This the post you were trying to download, it's archived. Was this a paid post?
> https://onlyfans.com/51744068/mikomihokina
Think you replied to the wrong comment. I don't follow her.

**Comment by valdearg** [comment]
Seems to have completed without errors now, cheers! There were a few empty folders but may just have been from the previous attempts and I've removed those, not the end of the world.
