### ISSUE TITLE
How to download new content without scraping everything again?

### ISSUE THREAD

**Issue by deashtx** [DIGITALCRIMINAL/OnlyFans#79]
is there an option to scrape a defined number of videos without scrapping everything? for example the newest content?

**Comment by DIGITALCRIMINAL** [comment]
In the config, set overwrite_files to false

**Comment by monkjew** [comment]
If you set it to false it won't download any duplicates?

**Comment by DIGITALCRIMINAL** [comment]
If it's set to false, it won't download the same files again. @monkjew

**Comment by monkjew** [comment]
Very cool thank you
