### ISSUE TITLE
Is it possible to add Hutt.co to the datascraper?

### ISSUE THREAD

**Issue by SafadezaSemLimites** [DIGITALCRIMINAL/OnlyFans#798]
First of all, DIGITALCRIMINAL is the boss! Thanks for doing God's work, my man!

Anyway, I'm a newbie when it comes to anything related to coding, but I wonder if it's possible to also add Hutt.co to the datascraper. They both seem very similar.

Thanks for the attention.

**Comment by DIGITALCRIMINAL** [comment]
If it has an API, then yeah.
