### ISSUE TITLE
There's nothing to scrape.

### ISSUE THREAD

**Issue by beepboop01** [DIGITALCRIMINAL/OnlyFans#799]
Everything was working fine until last night when I started receiving "There's nothing to scrape." over and over.
I definitely have things to scrape and it was all working perfectly until this morning. I tried on two different browsers and changed the profile file on each.

It repeats this:

Session IP: I removed my IP

Choose Profile
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.

**Comment by James-MF-Thomas** [comment]
That’s in reference to to that specific model.. you have either already downloaded their content (it may have been moved or in a different location, or the model is not an active subscription)

**Comment by beepboop01** [comment]
This is on the initial start up before it even shows me the list of models that I get the issue, that is the weird part. It also isn't prompting me to choose a profile, it's almost like it is failing before that.

**Comment by SteveJSzabo** [comment]
In your auth string for that site, you need to add "Active":true for it to use that profile.

**Comment by beepboop01** [comment]
Thanks, that seemed to work! It's weird how it was working fine for a long time.
