### ISSUE TITLE
Filename suggestion

### ISSUE THREAD

**Issue by mileyvirus** [DIGITALCRIMINAL/OnlyFans#8]
We all know what media downloaded from OnlyFans looks like and it's not pretty… It would be great to add some templating like in `youtube-dl` in `settings.json` or even hardcoded, for example:

```
Users/{username}/{date} - {text} - {carousel-index}.{ext}

Which will become
Users/miamalkova/2019-08-08 - Pink hair... don't care!.mp4
```

I see in the API requests we have those:
```
postedAt: "2019-08-08T12:54:09+00:00",
text: "Pink hair... don't care!"
```

I think having the date in the filename would work wonder for consuming the downloaded media as it mirrors the profile order. The text could even not be in the filename but in a separate .json/.xml file for archival purposes.

**Comment by DIGITALCRIMINAL** [comment]
Good idea. I'm on holiday right now, but I get back on Saturday. I'm also planning to get rid of useless code. I'll add in your suggestion of having the option to use your filename format and also adding the text to the links.json for archival reasons c:

**Comment by mileyvirus** [comment]
Great, enjoy your holiday!

**Comment by DIGITALCRIMINAL** [comment]
Text is now scraped and I added in file_name formatting.
Couldn't add {text} to file formatting because OnlyFans allows emojis in their posts which means there would be invalid characters that would cause the script to crash. {username} and {date} works though.

**Comment by dilemmax** [comment]
Hi there, I was really looking forward to this enhancement because the account I'm using has over 1000+ videos, most of which the user promotes other accounts so I need this enhancement to weed out the "promo videos".

I'm just scrapping to links so I can use a download manager to download the videos. What do I need to do to get those videos renamed with the scrapped texts?

**Comment by DIGITALCRIMINAL** [comment]
How come you're using a download manager? Is the inbuilt downloader too slow?
If the promoted posts contain text like "go follow, go add, promote, etc" I can add a filter that removes them from the links.json

**Comment by DIGITALCRIMINAL** [comment]
I updated the format, you can now use {text}. Some files won't contain text, so it will just be blank.
