### ISSUE TITLE
TypeError:  'NoneType'

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#800]
<img width="998" alt="Screen Shot 2021-02-09 at 3 18 05 AM" src="https://user-images.githubusercontent.com/47627618/107342157-7a4d1a00-6a85-11eb-87ce-17998f0939e5.png">
<img width="768" alt="Screen Shot 2021-02-09 at 3 16 12 AM" src="https://user-images.githubusercontent.com/47627618/107342186-81742800-6a85-11eb-85fc-3664f5a7fa2b.png">

**Comment by DIGITALCRIMINAL** [comment]
Which model

**Comment by James-MF-Thomas** [comment]
its mine creator profile

**Comment by James-MF-Thomas** [comment]
it always puts my profile at #1
