### ISSUE TITLE
Not able to get authorized, shows nothing to scrape. What am I doing wrong?

### ISSUE THREAD

**Issue by omruuu21** [DIGITALCRIMINAL/OnlyFans#806]
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 1.16 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit

Have purchased some content on my feed. Just got two accounts. Still shows nothing to scrape. Don't have 2FA but the auth json has 2FA true

**Comment by olivechicago** [comment]
I'm not sure of the cause, but this has been a constant issue for the past month or two.  It started for me around the time site configs were given their own json files.

Verify your session cookie.

For some reason OnlyFans logs me out/expires my session cookie.  After reauthenticating a new session cookie is generated and you have to update that in the .profile config file.

**Comment by omruuu21** [comment]
> I'm not sure of the cause, but this has been a constant issue for the past month or two. It started for me around the time site configs were given their own json files.
> 
> Verify your session cookie.
> 
> For some reason OnlyFans logs me out/expires my session cookie. After reauthenticating a new session cookie is generated and you have to update that in the .profile config file.

How do I reauthenticate? Log out and log into OF again?

**Comment by olivechicago** [comment]
yeap
