### ISSUE TITLE
changing download directory after some content has already downloaded

### ISSUE THREAD

**Issue by chenks** [DIGITALCRIMINAL/OnlyFans#807]
if i want to change the download location after some content has already been downloaded, is it simply the case of updating the config.json file and the moving the existing content to the new location and it'll continue on as normal (ie it won't look to re-download everything again, it'll just download any new content)?

just want to confirm before i go ahead and move the content.

**Comment by clem16** [comment]
I Just did this. Seems to work for me.

**Comment by DIGITALCRIMINAL** [comment]
The ideal setup is to keep metadata separate from the model folder so you can move the model folder anywhere you want whilst keeping track of whatever has been downloaded.

**Comment by olivechicago** [comment]
Different dilemma in the same vein.

Before downloading the commit for fixing the locked db issue, I could move or delete content, and as expected, that content was never downloaded again.

This is no longer true.  Successful initial scrape,  Move/delete some files.  Scraped again and those files are re-downloaded.

**Comment by DIGITALCRIMINAL** [comment]
> Different dilemma in the same vein.
> 
> Before downloading the commit for fixing the locked db issue, I could move or delete content, and as expected, that content was never downloaded again.
> 
> This is no longer true. Successful initial scrape, Move/delete some files. Scraped again and those files are re-downloaded.

Do you have overwrite files set to True?

**Comment by olivechicago** [comment]
Nope.  I checked that the first time I noticed this.

  D:\ExePrograms\onlyfans\.settings\config.json (2 hits)
	Line 41:         "overwrite_files": false,
	Line 71:         "overwrite_files": false,

**Comment by chenks** [comment]
to update this.
i changed the location on config.json (both download and metadata), moved the content.
it worked as expected, it only downloaded new content.

**Comment by olivechicago** [comment]
Are you using the current release or the most recent commit?
