### ISSUE TITLE
Interrupted Downloads.

### ISSUE THREAD

**Issue by clem16** [DIGITALCRIMINAL/OnlyFans#808]
Quick Question - How does this handle interrupted downloads?

Request:
Is there anyways we could get an individual file download rates displayed? 
Like how fast the download is going, and how much is left?

**Comment by DIGITALCRIMINAL** [comment]
> Quick Question - How does this handle interrupted downloads?
> 

The script retries the download 10 times.

> Request:
> Is there anyways we could get an individual file download rates displayed?
> Like how fast the download is going, and how much is left?

Not anytime soon.
