### ISSUE TITLE
Will not go past the 1st account via auto_scrape_names or "0"

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#809]
I do not get this error scraping individually via any account

<img width="1065" alt="Screen Shot 2021-02-11 at 12 14 01 AM" src="https://user-images.githubusercontent.com/47627618/107607202-2ca7ed00-6bfe-11eb-9733-d63811ca3647.png">

**Comment by ProjektPremium** [comment]
Could this be happening because it's your own account?

**Comment by James-MF-Thomas** [comment]
that's my guess

**Comment by ProjektPremium** [comment]
I've seen the list you have to endure scraping. You know how to contact me, I'll give you some advice.

**Comment by DIGITALCRIMINAL** [comment]
> I do not get this error scraping individually via any account
> 
> <img alt="Screen Shot 2021-02-11 at 12 14 01 AM" width="1065" src="https://user-images.githubusercontent.com/47627618/107607202-2ca7ed00-6bfe-11eb-9733-d63811ca3647.png">

I can't fix this unless I have access to the account

**Comment by James-MF-Thomas** [comment]
Just emailed your proton address

**Comment by James-MF-Thomas** [comment]
<img width="1205" alt="Screen Shot 2021-02-13 at 3 15 37 AM" src="https://user-images.githubusercontent.com/47627618/107846497-c9f35480-6da9-11eb-958b-cf2e72de2f63.png">

**Comment by James-MF-Thomas** [comment]
got the correct string combination this time.. accounts got crossed earlier. should be in your proton

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed in the latest commit

**Comment by James-MF-Thomas** [comment]
<img width="580" alt="Screen Shot 2021-02-14 at 4 46 48 AM" src="https://user-images.githubusercontent.com/47627618/107874492-aac6f680-6e7f-11eb-8f88-1e501746f842.png">

**Comment by James-MF-Thomas** [comment]
<img width="580" alt="Screen Shot 2021-02-14 at 4 46 48 AM" src="https://user-images.githubusercontent.com/47627618/107874528-e19d0c80-6e7f-11eb-9558-05fd7b4c3da4.png">
