### ISSUE TITLE
Scraper no longer launches

### ISSUE THREAD

**Issue by onesimpleclik** [DIGITALCRIMINAL/OnlyFans#811]
Running start_ofd.py no longer launches scraper.
Shell window opens & immediately closes.
Reinstall of python & requirements for scraper does not give results.

Unsure of problem, scraper was working up until today.

**Comment by jp1151419** [comment]
Did you try to just download a fresh copy? That fixed it for me a couple times

**Comment by onesimpleclik** [comment]
> 
> 
> Did you try to just download a fresh copy? That fixed it for me a couple times

Yeah still not working. Unsure what has changed to stop it working :/

**Comment by DIGITALCRIMINAL** [comment]
You'll have to debug it yourself and find out why it's closing. Open it with the Python IDE.

**Comment by onesimpleclik** [comment]
> 
> 
> You'll have to debug it yourself and find out why it's closing. Open it with the Python IDLE.

I'm not sure how to do that.. but I just reset my PC & started fresh, and still having the same issue. Is there anything I need to have installed, other than Python & the C++ Build Tools? I might be missing something.
