### ISSUE TITLE
No content being found

### ISSUE THREAD

**Issue by MadamJazzy** [DIGITALCRIMINAL/OnlyFans#812]
Scrapper no longer working. Scraper launches but finds no content. I've updated to latest version, even deleted auth and config files and let it generate new ones to fill out. Still does not find any content. 
`Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit
`
Disabled the autos and it shows onlyfans but doesn't show any names to scrape. 
And i've ensured that there is new content on the subscribers. Even subscribed to a new person just to test it.

**Comment by onesimpleclik** [comment]
Getting the same error as well. Maybe something got changed on OF's end?

[https://i.imgur.com/sDHzE21.jpg](url)

**Comment by MadamJazzy** [comment]
mine isn't even showing all that. It literally just shows 
![Capture1](https://user-images.githubusercontent.com/22993774/107840452-d57e5580-6d80-11eb-9585-c1b9e3de295e.PNG)
No choice for what usernames or anything. And i don't get the attempts. It logs in, but says there is nothing to scrape

**Comment by DIGITALCRIMINAL** [comment]
@MadamJazzy Does this still happen?

**Comment by ChrisKyle698** [comment]
I am having the exact same problem: Scraping Paid Content Scraping Subscriptions There's nothing to scrape. Archive Completed in 0.0 Minutes Pausing scraper for 0 seconds. Site: 0 = onlyfans | x = Exit

**Comment by MadamJazzy** [comment]
@DIGITALCRIMINAL yes, after pulling fresh update its still showing the same as the screen above.

**Comment by ChrisKyle698** [comment]
what can we do to fix it? it always shows theres nothing to scrape and then the auth.json file changes automatically the username to default after i put in a onlyfans username

**Comment by arenatemp** [comment]
poking around i think i have gathered:
if you get the 10 auth attempts, thats the scraper silently failing to auth, then because getting your subscriptions etc is part of the login, it will scrape nothing.

the username part of auth.json is ignored, only the folder name auth.json is in matters (so rename it from default to your username).

**Comment by onesimpleclik** [comment]
i've somehow managed to get mine running. 

steps:
- delete extracted folder & re-extract the scraper
- requirements should already be installed, but do that if need be. pip may need to be updated.
- run the scraper & open/edit the auth.json file **&** save, but leave the the file open as you go. keep hitting enter until the scraper is set up.

for some reason this worked & it's back up again for me.

**Comment by MadamJazzy** [comment]
This has resolved somehow (not sure how) Everything same as it was before. Today it just works when it wouldn't yesterday.
