### ISSUE TITLE
Redownloading content when it's not supposed to

### ISSUE THREAD

**Issue by olivechicago** [DIGITALCRIMINAL/OnlyFans#813]
As mentioned here (https://github.com/DIGITALCRIMINAL/OnlyFans/issues/807) after installing the latest release, previously downloaded content that had either been moved or deleted is being downloaded again.  

I tried the latest build, hoping that the "Fixed metadata filepath" note may resolve the issue.  No luck.  My config is attached. 
[config.json-copy.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5976283/config.json-copy.txt)

Also, I have it set to exit after completion.  Before the latest release, exiting was almost instant.  Now it takes a very long time... 10, 15 minutes maybe.  Not a complaint, just an observation.  Maybe has something to do with this.

**Comment by DIGITALCRIMINAL** [comment]
Fixed 👍

**Comment by olivechicago** [comment]
Yes it has been.  Thank you!
