### ISSUE TITLE
No 'tqdm module'

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#819]
<img width="1579" alt="Screen Shot 2021-02-14 at 5 54 53 PM" src="https://user-images.githubusercontent.com/47627618/107892946-eef0e000-6eed-11eb-9fce-352107906f40.png">

**Comment by Donkeykong307** [comment]
Until the requirements file gets updated, you can manually install tqdm with the following command.

python3.9 -m pip install tqdm

**Comment by James-MF-Thomas** [comment]
Right on. Thanks

**Comment by DIGITALCRIMINAL** [comment]
> Until the requirements file gets updated, you can manually install tqdm with the following command.
> 
> python3.9 -m pip install tqdm

I forgot to actually push the commit.
