### ISSUE TITLE
Authentication loop

### ISSUE THREAD

**Issue by Pl0xs** [DIGITALCRIMINAL/OnlyFans#83]
Hi,

I ran the program after I added the app-token, auth_id, auth_hash and user_agent. But it keeps printing:
```
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
```

I also see there is a sess atribute, where do I find that one?

Kind regards.

**Comment by DIGITALCRIMINAL** [comment]
The sess token is in the same place where you find the auth_hash

**Comment by Pl0xs** [comment]
It was the user-agent, it works now. Thank you!
