### ISSUE TITLE
Redownloading content if db existed before fix for #813

### ISSUE THREAD

**Issue by olivechicago** [DIGITALCRIMINAL/OnlyFans#833]
Content is redownloaded if the subscription has an existing db file.

When testing the fix for #813 , I had completely deleted a smaller subscriptions directory, and it worked fine.

Letting the script run over night I found all previously moved/deleted content has been downloaded again.

I deleted the db files from a few more subscription directories, ran the script and all content was downloaded again, obviously.  Moved the content out, ran the script, and as desired, there was nothing new to download.

**Comment by DIGITALCRIMINAL** [comment]
I don't understand this
