### ISSUE TITLE
Update about auth issues

### ISSUE THREAD

**Issue by oferchen** [DIGITALCRIMINAL/OnlyFans#836]
Hi,
I used to receive the auth issue,
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10

The reason behind it seems to be that a session is tied to the user agent used to create it
the default auth contains some cancellation characters (\) if you remove it and make sure the user agent is identical to the browser used to initiate the session then the issue is gone.

**Comment by DIGITALCRIMINAL** [comment]
What cancelation characters

**Comment by oferchen** [comment]
I think it's the escape characters that were present in the "user_agent" value, once I removed it and used the same user agent from firefox the issue stopped.

**Comment by DIGITALCRIMINAL** [comment]
The script automatically resolves the escape characters

**Comment by oferchen** [comment]
I understand but that is what it work for me. I think that locking a session to a certain user agent is a clever and cheap way of removing additional clients on to that session.

**Comment by DIGITALCRIMINAL** [comment]
> I understand but that is what works for me. I think that locking a session to a certain user agent is a clever and cheap way of removing additional clients on to that session.

True, I was thinking of creating a script where users can input their username and password and it will return all relative credentials with a custom but static user-agent.

**Comment by oferchen** [comment]
> > I understand but that is what works for me. I think that locking a session to a certain user agent is a clever and cheap way of removing additional clients on to that session.
> 
> True, I was thinking of creating a script where users can input their username and password and it will return all relative credentials with a custom but static user-agent that a user can choose.

That sounds like a good idea to simplify the login process.
