### ISSUE TITLE
Purchased content from unsubscribed profiles

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINAL/OnlyFans#837]
Will this scrape purchased content from profiles without a current active subscription?

(i.e. content on the "purchased" tab of the main page)

**Comment by olivechicago** [comment]
If it was paid for, I believe it does.  That's been my experience

**Comment by ProjektPremium** [comment]
Yes it does. It gets it from the "onlyfans.com/purchased" page. All purchases stay there regardless of active subscription or not, and it does scrape it. I believe you just have to set it to "true" in the settings for paid content.
