### ISSUE TITLE
Looping issue onlyfans

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#84]
It seems that the script is looping for me after it finishes over and over. I have it set to auto-choose choice a, to auto scrape all and to not overwrite files if they exist.

When I start it it scrapes all the users like it normally should, then dls if it needs. But then after this, it loops back to the scrape user part again. And just keeps doing this unless I manually close the script.

**Comment by DIGITALCRIMINAL** [comment]
Set auto scrape all to false if you don't want it to loop again

**Comment by bobsage123** [comment]
But I do want it to scrape all users without having to explicitly input that. Is there a way so I can automatically scrape all users without the loop?

**Comment by DIGITALCRIMINAL** [comment]
Yeah, I'll add that feature in. I gotta fix a couple of things.

**Comment by DIGITALCRIMINAL** [comment]
Added. Set infinite_loop to false so it only runs once before asking you to continue.

**Comment by bobsage123** [comment]
Thanks!
