### ISSUE TITLE
Useragent changes in auth.json, causing auth attempts to fail

### ISSUE THREAD

**Issue by CoderJoedk** [DIGITALCRIMINAL/OnlyFans#840]
Hello,

Running on Windows using 6.4.1 I have noticed I had a lot of failed auth attempts. What I noticed was, that in "auth.json" the user agent between runs is escaped, which makes auth fail.

```
{
  "auth": {
    "username": "default",
    "auth_id": "123445566",
    "auth_hash": "",
    "auth_uniq_": "",
    "sess": "v6r86gg0cro3vmao5vb3vjpqea",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    **"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182** Safari/537.36",
    "support_2fa": true,
    "active": true
  }
}
```

After a run it seems like useragent is escaped, adding "\\", which then makes the auth fail. 
```
{
  "auth": {
    "username": "default",
    "auth_id": "123445566",
    "auth_hash": "",
    "auth_uniq_": "",
    "sess": "v6r86gg0cro3vmao5vb3vjpqea",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/88.0.4324.182 Safari\/537.36",
    "support_2fa": true,
    "active": true
  }
}
```

**Comment by mikeholly** [comment]
Ive been getting this output: Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.03 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit


and i also noticed the same thing in my auth.json file. Ive had no luck

**Comment by wobbleninja** [comment]
Just downloaded the newest version yesterday and I noticed that now too. Basically it would login normally but was getting errors after "Scraping Paid Content".

In the end it gives a KeyError: 'Medias'

And yeah, same problem with the "\" for me in auth.json

**Comment by olivechicago** [comment]
Thanks to this, I finally figured out why they only way I could fix the failed auth attempt loop after my session cookie expired was to do a clean install of the script.

Onlyfans certainly does not like the \ / in the user_agent line.  I never bothered to look at this line because it never changed.

**Comment by wobbleninja** [comment]
> Thanks to this, I finally figured out why they only way I could fix the failed auth attempt loop after my session cookie expired was to do a clean install of the script.
> 
> Onlyfans certainly does not like the \ / in the user_agent line. I never bothered to look at this line because it never changed.

I tried a clean install but nothing changed for me. Even if I put the agent again it would automatically changed. The only fix for me so far is to set "scrape_paid_content": false" in settings folder's text.

**Comment by olivechicago** [comment]
> > Thanks to this, I finally figured out why they only way I could fix the failed auth attempt loop after my session cookie expired was to do a clean install of the script.
> > Onlyfans certainly does not like the \ / in the user_agent line. I never bothered to look at this line because it never changed.
> 
> I tried a clean install but nothing changed for me. Even if I put the agent again it would automatically changed. The only fix for me so far is to set "scrape_paid_content": false" in settings folder's text.

The medias error is something different.

**Comment by scgreenhalgh** [comment]
'medias' error is completely different and fixed in the latest git commit. The error is described in issue #823 .

**Comment by James-MF-Thomas** [comment]
The / is how macOS deals with spaces in file-paths. Those should return no error

**Comment by j-ktz** [comment]
Anyone figured out how to fix? Randomly started happening to me.

**Comment by threepwood-guy** [comment]
FYI, I fixed this by switching from Chrome to Firefox (and updating the cookie/user agent strings in the config to the ones generated while loading the page in Firefox)
