### ISSUE TITLE
Can't get working on Mac OS

### ISSUE THREAD

**Issue by j-ktz** [DIGITALCRIMINAL/OnlyFans#842]
I'm running Python 3.9.2
- Downloaded the .zip and unzipped
- Opened terminal window in the unzipped folder and run "pip install -r requirements.txt" and get the following error.
- I've verified I do have Python3 installed. Do I need to modify the code above to use Python3 instead of Python 2.7?
<img width="1030" alt="screenshot 2021-02-20 at 3 58 24 PM" src="https://user-images.githubusercontent.com/59346628/108608388-965d8f00-7394-11eb-9c0c-2cc6070a10d1.png">

**Comment by headphonia** [comment]
How did you install python? Looks like Terminal is still set to Python 2 which is built into macOS. Follow this guide to install Python 3.

https://opensource.com/article/19/5/python-3-default-mac#what-to-do

**Comment by j-ktz** [comment]
I installed Python3 off their website, downloaded zip and ran installer. If I run the version command for Python3 it’s there. But using the instructions from the YouTube video seem to default to Python 2 on Mac

**Comment by headphonia** [comment]
If you take a few minutes to follow the guide you'll be able to get it working. The way the Python website installs it does make it the default Python version Terminal will use.

**Comment by j-ktz** [comment]
@headphonia Thanks for the tip! I was following the YouTube guide on the Code page to install Python, however, when I try with the article you sent. I still run into errors. If I'm being honest, no idea what this all means. Keep running into hurdles with Python. Any ideas? 
<img width="865" alt="screenshot 2021-02-20 at 5 03 31 PM" src="https://user-images.githubusercontent.com/59346628/108609717-c8272380-739d-11eb-8af9-4fdfa6ca9505.png">

**Comment by headphonia** [comment]
I'm not that well-versed in this stuff either. But I think the latest version of Python is 3.9, looks like you're installing 3.7, maybe that's the culprit?

**Comment by j-ktz** [comment]
Yup. Tried that too. Same error. :(

**Comment by kervala** [comment]
It looks like Xcode command-line tools are not installed :(

**Comment by j-ktz** [comment]
@kervala Thanks for the tip. I installed the Xcode Command Line Tools and tried the terminal line to install Python again and get this error. 
<img width="479" alt="screenshot 2021-02-21 at 8 14 33 AM" src="https://user-images.githubusercontent.com/59346628/108626324-9190ed80-741d-11eb-98b6-571c8ceb1f3e.png">

**Comment by kervala** [comment]
Apparently, this is not the same issue :)

The link https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz seems to work for me :)

**Comment by j-ktz** [comment]
Yeah... I'm stuck. Can't get it to work. :(

**Comment by nappyapp** [comment]
Try `pip3` instead of `pip`, and `python3` instead of `python`

**Comment by j-ktz** [comment]
@nappyapp That was it! You solved it. THANK YOU!!!!

**Comment by kingkarl2** [comment]
instead of "pip" enter "pip3" and it should work
