### ISSUE TITLE
ModuleNotFoundError: No module named 'deepdiff'

### ISSUE THREAD

**Issue by quarz12** [DIGITALCRIMINAL/OnlyFans#848]
I have installed C++ Buildtools but i keep getting this error when trying to start.

**Comment by James-MF-Thomas** [comment]
pip install deepdiff

**Comment by quarz12** [comment]
yeah I tried that one already, didnt work

**Comment by James-MF-Thomas** [comment]
did it fail or did it say requirements already met?

**Comment by quarz12** [comment]
requirements already met

**Comment by James-MF-Thomas** [comment]
Can you show me the actual error or trace back

**Comment by James-MF-Thomas** [comment]
try upgrading python to 39

**Comment by quarz12** [comment]
that is what i am running it with, python3 is just the path name

**Comment by quarz12** [comment]
dont need it anymore
