### ISSUE TITLE
There's nothing to scrape.

### ISSUE THREAD

**Issue by anon-ion** [DIGITALCRIMINAL/OnlyFans#855]
**Issue:**

The script keeps exiting with the following output:
```
Choose Profile
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
```

I haven't had problems until recently. So I just did a hard reset from the latest commit on master in case something changed with the OF API. Still no good. 

**Debugging:**

I've been working my way through the code, and I'm pretty sure the main issue is that the profile isn't being set. 

On `datascraper/main_datascraper.py:69`, a "Choose Profile" is printed out, and it does not accept any user input.

Here is my output from the following line that I inserted on `datascraper/main_datascraper.py:71`:
```
print('subscription_list: ', subscription_list, 'auto_profile_choice: ', auto_profile_choice)
=> subscription_list:  [[], ''] auto_profile_choice:  
```

So when trying to retrieve a value for `apis` on the next line, it's passing in blank data that I believe I was supposed to set.

I remember using this script before and I was prompted to choose a profile. But now I'm not. I've double checked to make sure  `.profiles/OnlyFans/default/auth.json` has the proper data filled in.

**Next:**

I'll continue to work my way through this to see if I can pinpoint the issue, but just wanted to document my problems in case someone else has run into it before and already has it solved.

Thanks again for this library, and for actively maintaining it. I'd like to help in any way that I can. Although I probably have collectively 10-20 hours of experience with python :)

**Comment by James-MF-Thomas** [comment]
your .auth file located in .profiles should like this:
![Screen Shot 2021-02-23 at 7 14 49 AM](https://user-images.githubusercontent.com/47627618/108848714-f0ce3980-75a6-11eb-8c15-e8c1d9aa2c27.png)

Line 21 in .config should choose the default profile
![Screen Shot 2021-02-23 at 7 14 21 AM](https://user-images.githubusercontent.com/47627618/108848651-dbf1a600-75a6-11eb-993d-16d779970052.png)

**Comment by anon-andon** [comment]
> your .auth file located in .profiles should like this:
> ![Screen Shot 2021-02-23 at 7 14 21 AM](https://user-images.githubusercontent.com/47627618/108848651-dbf1a600-75a6-11eb-993d-16d779970052.png)
> 
> Line 21 in .config should choose the default profile
> ![Screen Shot 2021-02-23 at 7 14 49 AM](https://user-images.githubusercontent.com/47627618/108848714-f0ce3980-75a6-11eb-8c15-e8c1d9aa2c27.png)

I've changed that line in .config, and `auto_profile_choice` is now printing out 1. So progress. But still getting the same output for the rest of it. Here is my .config: 
```
{
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "webhooks": [],
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "proxies": [],
    "cert": "",
    "random_string": "6039390e48a311ebaa906030d46a3ea4"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "1",
        "auto_scrape_names": false,
        "auto_choice": "a",
        "auto_scrape_apis": true,
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": "",
        "auto_scrape_names": false,
        "auto_choice": "",
        "auto_scrape_apis": true,
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    }
  }
}
```
Not sharing my .auth for obvious reasons, but everything in mine is the same as yours, minus auth_id, sess, and auth_token, of course.

**Comment by j-ktz** [comment]
I'm running into this too. Typically I would see my username when I ran the script, now it just says **username = username**, when I lick at auth.js, it says username is default, I changed to my actual username and save but when I run again, it reverts back to default. Any idea?

**Comment by lEtranger1942** [comment]
Check your sess token. I ran into the same problem. I run it as a cron job and at some point started failing. Checked my sess token on the website and saw that it expired. After placing the correct sess token started working again

**Comment by j-ktz** [comment]
That seemed to fix it. Thank you so much!!!


On February 27, 2021, GitHub <notifications@github.com> wrote:
> Check your sess token. I ran into the same problem. I run it as a cron

> job and at some point started failing. Checked my sess token on the
> website and saw that it expired. After placing the correct sess token

> started working again
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/DIGITALCRIMINAL/OnlyFans/issues/855#issuecomment-
787417629>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5RHCDLJPFTBG3FMLS5DTBH6WHANCNFSM4YCBHVTQ>.

**Comment by clem16** [comment]
Oh, also check see if your user agent is still the same.

Browsers have a habit of auto updating themselves, then when you login again... Your user agent has changed from what may be in the config file.

**Comment by j-ktz** [comment]
Thank you!


On March 1, 2021, GitHub <notifications@github.com> wrote:
> Oh, also check see if your user agent is still the same.
>
> Browsers have a habit of auto updating themselves, then when you login

> again... Your user agent has changed from what may be in the config
> file.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/DIGITALCRIMINAL/OnlyFans/issues/855#issuecomment-
788038587>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5REO4CNT4ODTC4HW653TBOXSHANCNFSM4YCBHVTQ>.

**Comment by anon-ion** [comment]
Just commenting to note that I'm still running into the same issues. I tried updating the sess token and user agent. I haven't had time to dig in recently, but I'll try to this week.

**Comment by AplhaSlayer1964** [comment]
> Just commenting to note that I'm still running into the same issues. I tried updating the sess token and user agent. I haven't had time to dig in recently, but I'll try to this week.
> 
> I also tried completely removing the project and recloning. Same problems. I'm positive I'm using the right auth creds.

Quadruple check because I was having the same issue and changed the sess and user_agent and that fixed my problem. My user agent looked almost the same but was apparently different. Hope you are able to get it working too.

**Comment by Glaukon777** [comment]
I was having the same issue, followed the same steps and still had the issue. Turns out my sess token was changing frequently, it was just a matter of inputting it again and again until it worked. Hope you get it running!

**Comment by massivroom** [comment]
I had this problem, which I didn't have before and I realized, that if I search for session ID in mozilla firefox, it signs me out as soon as I run the scrapper which comes up empty. 
I looked for session ID in Chrome, and it immediately worked using the ID I got from Chrome.

**Comment by lazy2203** [comment]
I have this issue and any of the solutions seems to work for me.
Every help will be appreciate.

**Comment by dimer191996** [comment]
Choose Profile
Names: Username = username  |  0 = All | 1 = default
theonlyhydro_vids
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.16 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit
.............
I have this issue and none of the solutions seems to work for me.
Every help will be appreciate.

**Comment by DIGITALCRIMINAL** [comment]
Nothing I can do unless you give me your email and password.

**Comment by KptnKMan** [comment]
Hi, I referenced this issue in a new ticket on an issue I'm experiencing that seems to shed light on this issue also.
Seems related, but I don't know if @DIGITALCRIMINAL has any thoughts on it?
I'm running this in an auto-build docker container so can replicate.
Any advice?

**Comment by anon-ion** [comment]
I deleted the repo and recloned again, and it is working. I'm not sure what's different, but I suspect it was an auth issue. I'm closing this issue, but my advice if anyone runs into this again is to just start over with a fresh setup. Be sure to move all your data to a different directory and move it back into the recloned repo if you don't want to lose everything.

**Comment by KptnKMan** [comment]
Hi @anon-ion would you be able to post more details on your configuration files (`auth.json` / `config.json`) and setup?
Please, of course, I mean with any personal details/credentials anonymised. I'm concerned most about the formatting of a working configuration.
I'm using a dockerised deployment, build directly of this codebase for repeatable testing.

I'm also trying to get this to work, and raised an issue #993 trying to get to the bottom of it, where I also encountered the error and use case you documented in this issue.

If I can compare our configurations, I might be able to investigate further, and it might be able to determine where in the code what is causing issues.
