### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by ReffyVFX** [DIGITALCRIMINAL/OnlyFans#86]
Hi, Im new to this and im confused about the first step. It says “From the project folder run this command in your terminal pip install -r requirements.txt”. this is what happens... 

![Capture](https://user-images.githubusercontent.com/58599736/70336186-51d8e880-180e-11ea-8942-2d6d17823757.JPG)

**Comment by DIGITALCRIMINAL** [comment]
@ReffyVFX Do you have Python 3.8 installed?

**Comment by ReffyVFX** [comment]
Thanks for the help, I installed everything and filled out the config. what do I do next?

**Comment by ReffyVFX** [comment]
Nvm, I figured it out thanks again!

**Comment by usergip** [comment]
I have the same issue but i have 3.8 installed. I'm a newbie to this btw
