### ISSUE TITLE
Script will scrape a few models, then get stuck on "medias" and can't find "filename"

### ISSUE THREAD

**Issue by anonCoder123** [DIGITALCRIMINAL/OnlyFans#868]
I am running master

```
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Traceback (most recent call last):
  File "Z:\github-folders\OnlyFans\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "Z:\github-folders\OnlyFans\datascraper\main_datascraper.py", line 95, in start_datascraper
    paid_content = module.paid_content_scraper(apis, identifiers)
  File "Z:\github-folders\OnlyFans\modules\onlyfans.py", line 353, in paid_content_scraper
    unrefined_set = media_scraper(paid_content, api, subscription,
  File "Z:\github-folders\OnlyFans\modules\onlyfans.py", line 1075, in media_scraper
    found_medias = [x for x in medias
  File "Z:\github-folders\OnlyFans\modules\onlyfans.py", line 1076, in <listcomp>
    if x["filename"] == new_media["filename"]]
KeyError: 'filename'
```

**Comment by DIGITALCRIMINAL** [comment]
model name

**Comment by anonCoder123** [comment]
`bronzed_aurora` its a free account

**Comment by badchoices** [comment]
Try using the branch from #867 it fixed my issue.

**Comment by lEtranger1942** [comment]
Branch #867 fixed it for me too

**Comment by jeff-geoff** [comment]
Still broken in latest commit.

**Comment by bobsage123** [comment]
The https://github.com/DIGITALCRIMINAL/OnlyFans/pull/867 commit works for me too. @DIGITALCRIMINAL will you merge this\apply similar fix?

**Comment by Jar4ek** [comment]
I have the same problem. 
nickname `cherielady` and `lindseypelas`

**Comment by sintaxx** [comment]
> 
> 
> I have the same problem.
> nickname `cherielady` and `lindseypelas`
> 
> ```
> Traceback (most recent call last):
>   File "start_ofd.py", line 43, in <module>
>     apis = main_datascraper.start_datascraper(json_config, site_name_lower)
>   File "datascraper\main_datascraper.py", line 98, in start_datascraper
>     names = main_helper.process_names(
>   File "helpers\main_helper.py", line 631, in process_names
>     result = module.start_datascraper(
>   File "modules\onlyfans.py", line 147, in start_datascraper
>     results = prepare_scraper(
>   File "modules\onlyfans.py", line 700, in prepare_scraper
>     unrefined_result = pool.starmap(media_scraper, product(
>   File "Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "Python\Python39\lib\multiprocessing\pool.py", line 771, in get
>     raise self._value
>   File "Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "\modules\onlyfans.py", line 1075, in media_scraper
>     found_medias = [x for x in medias
>   File "\modules\onlyfans.py", line 1076, in <listcomp>
>     if x["filename"] == new_media["filename"]]
> KeyError: 'filename'
> ```
> 
> I have a question if it is possible to add one command where I do not have to wait for the profile to load. I mean 0-All and a = everything. With 20 observed profiles, it is a pain. I mean that if I enter `0` and `a` that these profiles will be automatically treated. So every generation profile flies with such settings.

You can edit the config and have all of that automated, I believe he has that mentioned on the readme on the main page.
