### ISSUE TITLE
Run into a "IsADirectoryError" when archiving after most recent update

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINAL/OnlyFans#87]
I just recently updated and after it downloads from one account, when it moves to the next, I get the following error after it archives all the images:

`Traceback (most recent call last):`
`  File "StartDatascraper.py", line 112, in <module>`
`    x.download_media(*arg)`
`  File "~/OnlyFans/modules/onlyfans.py", line 334, in download_media`
`    pool.starmap(download, product(`
`  File "~/python3/lib/python3.8/multiprocessing/pool.py", line 372, in starmap`
`    return self._map_async(func, iterable, starmapstar, chunksize).get()`
`  File "~/python3/lib/python3.8/multiprocessing/pool.py", line 768, in get`
`    raise self._value`
`  File "~/python3/lib/python3.8/multiprocessing/pool.py", line 125, in worker`
`    result = (True, func(*args, **kwds))`
`  File "~/python3/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar`
`    return list(itertools.starmap(args[0], args[1]))`
`  File "~/OnlyFans/modules/onlyfans.py", line 319, in download`
`    with open(download_path, 'wb') as f:`
`IsADirectoryError: [Errno 21] Is a directory: '/directory/'`

I'm not sure what happened or what I need to change/edit. Any thoughts/help would be greatly appreciated. Thanks!

**Comment by DIGITALCRIMINAL** [comment]
What path are you downloading to?

**Comment by ElusiveZatchmo** [comment]
~/onlyfans

**Comment by DIGITALCRIMINAL** [comment]
Did you fill in "directory" in the config?

**Comment by ElusiveZatchmo** [comment]
I did

**Comment by ElusiveZatchmo** [comment]
apologies here's the full directory in error:
IsADirectoryError: [Errno 21] Is a directory: '~/Plex/Porn//onlyfans/{username}/Posts/Images/'

**Comment by ElusiveZatchmo** [comment]
I'm finding I only run into this error when I enable the auto options in the config file, if I run:
`(echo -e "0"; echo -e "c"; echo -e "c") | python3 StartDatascraper.py`
I don't get that error at all

**Comment by DIGITALCRIMINAL** [comment]
@ElusiveZatchmo what's the directory config

**Comment by ElusiveZatchmo** [comment]
`"directory": "/media/sdw1/holonet81/Plex/Porn"`
Okay, so here's some other info. I'm currently following 2 accounts on OnlyFans and am trying to scrape everything from both. Whenever I try to grab everything from both it grabs everything from the first profile, but throws that error that I've been getting after completing the images of the second profile.

**Comment by DIGITALCRIMINAL** [comment]
@ElusiveZatchmo Try using `\\` instead of `/`

`\\media\\sdw1\\holonet81\\Plex\\Porn`

**Comment by ElusiveZatchmo** [comment]
`IsADirectoryError: [Errno 21] Is a directory:`
`\\media\\sdw1\\holonet81\\Plex\\Porn//onlyfans/{username}/Posts/Images/'`

And on top of that, I have no idea where those downloaded to, because Linux is telling me that doesn't exist

**Comment by DIGITALCRIMINAL** [comment]
Hmm seems that UNIX uses forward slashes instead of backslashes then. In the script, I'm probably telling it somewhere to use a backslash so I'll look into it.
One thing I noticed is this
`/Plex/Porn//onlyfans/{username}/Posts/Images/`
`Porn//onlyfans`
There are two forward slashes. Could be the reason why.

**Comment by ElusiveZatchmo** [comment]
maybe. I noticed it added three there if I ended the directory list in config with a trailing '/'

**Comment by DIGITALCRIMINAL** [comment]
@ElusiveZatchmo gonna push the update within 5 minutes

**Comment by ElusiveZatchmo** [comment]
I'm still getting the same error :/

`IsADirectoryError: [Errno 21] Is a directory: '/media/sdw1/holonet81/Plex/Porn/onlyfans/{username}/Posts/Images/'`

**Comment by DIGITALCRIMINAL** [comment]
@ElusiveZatchmo what is your filename format in the config

**Comment by ElusiveZatchmo** [comment]
`"file_name_format": "{username} {date} - {text} ({file_name}).{ext}"`

**Comment by DIGITALCRIMINAL** [comment]
Just use {file_name}.{ext}
Should work I think

**Comment by ElusiveZatchmo** [comment]
It doesn't have that issue though when I try to scrape just images or just videos though. I'll give it a try and report back

**Comment by ElusiveZatchmo** [comment]
So that worked, it just becomes an organizational nightmare, lol. What in my "file_name_format" is breaking this?

**Comment by ElusiveZatchmo** [comment]
yeah something is happening in {text}. I set the length to '50' and it stopped having this particular problem

**Comment by tenaka18** [comment]
i had the same problem and i did what you said "set the length to '50'" and it worked like a charm .
thank you .

**Comment by ethan961** [comment]
I'm getting this issue regardless of filename format and on 3.5.4. Have had no success scraping anything. If I don't define a folder it appears to attempt to create a folder under root, which it naturally does not have permissions for. Defining a folder has this result.

**Comment by DIGITALCRIMINAL** [comment]
@ethan961 are you using Linux?

**Comment by ethan961** [comment]
Yes I am.

**Comment by DIGITALCRIMINAL** [comment]
@ethan961 What folder path did you define?

**Comment by ethan961** [comment]
I tried "sites" (which created the folder in the project directory like it used to by default), "~/sites", and "/home/username/sites" which all exhibited the error.

**Comment by Morticioner87** [comment]
Im using linux aswell and i get the same problem as @ethan961
However im leaving the folder path empty aka default. It does create all folders sites/onlyfans/"username"/Posts/Videos etc but this error message comes as soon as it starts the Download Processing.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest release and tell me if it's working, please.

**Comment by Morticioner87** [comment]
@DIGITALCRIMINAL Working perfectly for me at least on Linux. Thank you! Amazing work!

**Comment by ElusiveZatchmo** [comment]
I just started getting this error again despite the adjustments I've made to the config file as mentioned above. I hadn't changed anything since it was working again and now the error has returned. :/
