### ISSUE TITLE
"Missing 900 Posts" error, OF model has 825 posts...

### ISSUE THREAD

**Issue by zLpZZxRc** [DIGITALCRIMINAL/OnlyFans#870]
Hi, I'm attempting to scrape videos by this model: mistressjaa

Login via successful - the terminal display my subscriptions, then when starting to parse:

> Scrape Processing
> Name: mistressjaa
> Type: Profile
> 0.00B [00:00, ?B/s]
> Type: Stories
> No Stories Found.
> Type: Posts
> Scrape Attempt: 1/100
> Missing 900 Posts... Retrying...
> Scrape Attempt: 2/100

DIGITALCRIMINAL, I sent you my OF credentials, hopefully you can take a look?
I've read past bugs but nothing seemed similar to this issue.
I know there are bugs about "missing 100 posts" but I read your explanation about it, and this is not the case here..

**Comment by zLpZZxRc** [comment]
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0

**Comment by DIGITALCRIMINAL** [comment]
Hello, this is just on OF's side. Their site runs slow sometimes which leads to these requests.
