### ISSUE TITLE
KeyError: 'filename'

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#874]
![image](https://user-images.githubusercontent.com/58760178/109392644-4a0dd400-78eb-11eb-8b1c-ddea0f720649.png)

Just tried the latest commit, 4df1eaf, after 63f63e6 started giving me the "nothing to scrape" error

**Comment by DIGITALCRIMINAL** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/840
