### ISSUE TITLE
Double Click On start_ofd.py in v6.4.1, nothing happens

### ISSUE THREAD

**Issue by mwill39014** [DIGITALCRIMINAL/OnlyFans#875]
Was using v6.2.5, downloaded v6.4.1, now when I double click on start_ofd.py the window opens & immediately closes. v6.2.5 still works though.

**Comment by ProjektPremium** [comment]
run it through command prompt and it should tell you what the problem is if there is one.

**Comment by hirezz** [comment]
Having the same issue. 

OnlyFans-6.4.1>python start_ofd.py
Traceback (most recent call last):
  File "H:\OnlyFans-6.4.1\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "H:\OnlyFans-6.4.1\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "H:\OnlyFans-6.4.1\helpers\main_helper.py", line 4, in <module>
    from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'

**Comment by lEtranger1942** [comment]
pip3 install deepdiff
