### ISSUE TITLE
OF changed calls to get session info

### ISSUE THREAD

**Issue by TheTrueColonel** [DIGITALCRIMINAL/OnlyFans#876]
![image](https://user-images.githubusercontent.com/19292389/109429407-316fed80-79c1-11eb-9276-85d6c87dc934.png)

Using the method stated on the README file no longer works as it seems OF updated authentication calls.

![image](https://user-images.githubusercontent.com/19292389/109429485-8b70b300-79c1-11eb-966b-696e32249876.png)

They seemed to have removed the `?app` calls

**Comment by DIGITALCRIMINAL** [comment]
Thanks, they finally stopped with the app-token nonsense.

**Comment by ProjektPremium** [comment]
> 
> 
> Thanks, they finally stopped with the app-token nonsense.

So what does that mean when it comes to the scraper out of curiosity?
