### ISSUE TITLE
Used to work but I am getting new issues

### ISSUE THREAD

**Issue by Shimoli** [DIGITALCRIMINAL/OnlyFans#878]
Used to work but I am getting new issues it cant scrape content anymore
![onlyfans](https://user-images.githubusercontent.com/6807663/109539318-0693a100-7a76-11eb-85ae-05dc2ecd2fbf.JPG)

**Comment by lEtranger1942** [comment]
Check your session token and user agent. Had the same issue. There are other issues opened with this problem

**Comment by ProjektPremium** [comment]
Sometimes OF goes really slow, even the site itself accessing it manually is quite slow at times. Just try and leave it for a few hours.

**Comment by ProjektPremium** [comment]
I just checked and it's still having issues. In the latest version and an older one I test with. 

Updated my session token and user agent, still times out on both.

**Comment by dcex** [comment]
The site is down. When this happens just go to twitter and search for 'onlyfans down' and you'll see a lot of complaints.

They may be changing something, but right now I think the safe option is to say that it is not working because the site is also not working.

**Comment by ProjektPremium** [comment]
All is working now.
