### ISSUE TITLE
Possible to scrape messages/conversations?

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINAL/OnlyFans#88]
Is it possible to have the script also scrape paid media in messages?
This doesn't seem to be working currently.

Also would be interested in being able to scrape conversations from non-active subscriptions (but which contain paid media)...

**Comment by DIGITALCRIMINAL** [comment]
I haven't paid for any media messages so I wouldn't know how to do it. I would need a JSON sample from you if you've paid for one.
