### ISSUE TITLE
Not pulling sources/models with 6.4.1

### ISSUE THREAD

**Issue by sintaxx** [DIGITALCRIMINAL/OnlyFans#880]
just updated to 6.4.1 and setup my auth.json as usual and it authenticates fine, says Welcome "USER | USER_ID" as normal but it just sits there... can someone verify this version works ? i've tried this on two different machines at 2 separate physical locations so basically 2 different WAN IPs as well as 2 different VPN IPs. I also saw that OF eXtractor browser plugin has disappeared and stopped working a few days ago as well so I wasn't sure if OF changed something that would have broken scraping

"""Seems to be working now all of the sudden, it must have been OF, even though i didn't see any maintenance notifications from them on twitter""""""

**Comment by ProjektPremium** [comment]
OnlyFans was probably upgrading their site, under attack or part of it crashed.

**Comment by bobsage123** [comment]
Yes, site is very slow right now.
