### ISSUE TITLE
Bug: when scraping multiple accounts, only ones models get scraped

### ISSUE THREAD

**Issue by bigbluedeer** [DIGITALCRIMINAL/OnlyFans#887]
I have a setup of two seperate accounts and everything works normally. When scraping and choosing to use both accounts to detect models, it detects all models that should be detected and i choose to scrape all of them. But then, it only scrapes models from the second account, never from the first. Only when i choose to just use the first account will it scrape the models there at all.

**Comment by artyom2035** [comment]
@bigbluedeer have you found a work-around or are you having any luck with newer releases? Just curious because I automate the script with docker & I currently use separate containers(similar to virtual machines) for each profile.  If there's a work-around or once the issue is closed I'll be able to use a single container.

**Comment by DIGITALCRIMINAL** [comment]
> @bigbluedeer have you found a work-around or are you having any luck with newer releases? Just curious because I automate the script with docker & I currently use separate containers(similar to virtual machines) for each profile. If there's a work-around or once the issue is closed I'll be able to use a single container.

Yikes, I'll fix it

**Comment by bigbluedeer** [comment]
@artyom2035 nope, issue still persists, only workaround is loading them seperately. could be cool to be able to predefine all inputs before starting a run (in a list or something), a bit like the auto choice keys in the settings config. this would resolve any issues and also give users a way to easily circumvent any future issues like these

**Comment by DIGITALCRIMINAL** [comment]
I promise I'm fixing it now lol
