### ISSUE TITLE
No .profile generated

### ISSUE THREAD

**Issue by Frivolousmud** [DIGITALCRIMINAL/OnlyFans#891]
I've installed all requirements without failure and ran the script. Get prompted to press enter to execute. By pressing enter it quickly exits. No error message displayed. No .profile generated. Can see other hidden files.

WIndows 10, python 3.9.

Tried latest build, 6.2.5 and 6.4

**Comment by Gamma-Velorum** [comment]
Did you install Visual Studio Build tools?

**Comment by Aikidou** [comment]
Same issue. Everything is set up properly (in a conda environment), the VS dependencies are installed too.

**Comment by vser** [comment]
Most Windows issues are trivial from what I can find. Have you attempted to run as admin?
Start > CMD > Run As Administrator.

After that just use the commands pointing to the dir. of OFD. For example:
```
pip install -r "D:\OFD\requirements.txt"
python "D:\OFD\start_ofd.py"
```

**Comment by intaemin** [comment]
Thanks, the administrator solution worked! For some reason, I had to run "pip install -r requirements.txt" multiple times (in cmd then python then back to cmd) until .profile was generated.

**Comment by tdup93** [comment]
I'm also having this issue and running in admin didn't help.
@intaemin can you explain a bit more what you mean by running the requirements install multiple times please?

**Comment by intaemin** [comment]
@tdup93 I'm not sure if this particular order matters but this is how it happened: 
1. I started off with opening the buildtools app then clicking launch for "Visual Studio Build Tools 2019." It basically opened up its own version of CMD, so I input the "pip install -r requirements.txt" thing. It downloaded some things but it said that it "failed to build the JSON." 
2. So, I tried to install the requirements thing in regular CMD but it still just generated error-type things. 

3. Afterwards, I double-clicked "start_ofd," which is inside the OnlyFans-v.6.6.4 folder, and decided to run "pip install -r requirements.txt" there (python). It generated the ".settings" folder. 
4. Next, I opened regular CMD as administrator then ran "pip install -r requirements.txt" and it finally generated the ".profiles" folder.

**Comment by tdup93** [comment]
When I double click "start_ofd" in the folder it just gives me the below:

![image](https://user-images.githubusercontent.com/82218872/114208374-4d1dca80-9955-11eb-8566-ae808700dfe9.png)

When I hit enter it just closes the window so I've no way to run "pip install -r requirements.txt" there. 
Any ideas or was yours different when running that?

**Comment by tdup93** [comment]
ok I figured it out. I hadn't actually upgraded my verion of python from 3.8 to 3.9. After I did that everything seems to working now.
@intaemin Thanks for getting back to me!

**Comment by intaemin** [comment]
@tdup93 Nice! Glad to hear that.

**Comment by LunarPenguin** [comment]
@Frivolousmud did you solve your problem? if so please close the issue
