### ISSUE TITLE
correct script upgrade process?

### ISSUE THREAD

**Issue by chenks** [DIGITALCRIMINAL/OnlyFans#894]
can't see it mentioned in FAQ or readme, but what's the correct process for upgrading the script version?
i've downloaded the most recent update, but is it simply pasting all the files into the existing installation location and overwriting everything?

**Comment by Gamma-Velorum** [comment]
Yes

**Comment by chenks** [comment]
including the database folder?

**Comment by DIGITALCRIMINAL** [comment]
> including the database folder?

Overwrite everything
