### ISSUE TITLE
chrome not providing app-token / sess_token

### ISSUE THREAD

**Issue by chenks** [DIGITALCRIMINAL/OnlyFans#895]
i think chrome has changed the network debugger on a recent update (89.0.4389.72 )
what previously worked fine to get the app-token etc now no longer displays any data

![Screenshot 2021-03-04 143626](https://user-images.githubusercontent.com/11945919/109979697-12da6100-7cf7-11eb-8f7d-039407416279.jpg)

**Comment by chenks** [comment]
ok that's fine, but how do you we get the other info required for auth.json?
the instructions say to use the chrome network debugger, but it's not matching the screenshot in the instructions any more.

never had a problem with it until recently.

**Comment by bigbluedeer** [comment]
dont know where it is on chrome, but you will need to find where the cookies are stored. everything else you need is there

**Comment by bigbluedeer** [comment]
and the user agent can be retrieved from any request header that was sent to onlyfans, just pick one

**Comment by chenks** [comment]
the installation instructions need to be updated then, as it says to do that.

**Comment by chenks** [comment]
> and the user agent can be retrieved from any request header that was sent to onlyfans, just pick one

is that true?
every time my chrome updates i have to edit the auth.json to match the new user_agent otherwise the script fails.

**Comment by bigbluedeer** [comment]
> > and the user agent can be retrieved from any request header that was sent to onlyfans, just pick one
> 
> is that true?
> every time my chrome updates i have to edit the auth.json to match the new user_agent otherwise the script fails.

well, if the chrome version changes, the user agent does too. its just a string representation of what you are using the web with and it changes with each version you install.

**Comment by chenks** [comment]
> > > and the user agent can be retrieved from any request header that was sent to onlyfans, just pick one
> > 
> > 
> > is that true?
> > every time my chrome updates i have to edit the auth.json to match the new user_agent otherwise the script fails.
> 
> well, if the chrome version changes, the user agent does too. its just a string representation of what you are using the web with and it changes with each version you install.

yes i know, so you saying "just pick one" makes no sense.
it has to match, not "just pick one" out of the air.

regardless, if chrome no longer provides this info via the network debugger then the installation/config instructions need updated to reflect this. agree yes?

**Comment by bigbluedeer** [comment]
> > > > and the user agent can be retrieved from any request header that was sent to onlyfans, just pick one
> > > 
> > > 
> > > is that true?
> > > every time my chrome updates i have to edit the auth.json to match the new user_agent otherwise the script fails.
> > 
> > 
> > well, if the chrome version changes, the user agent does too. its just a string representation of what you are using the web with and it changes with each version you install.
> 
> yes i know, so you saying "just pick one" makes no sense.
> it has to match, not "just pick one" out of the air.
> 
> regardless, if chrome no longer provides this info via the network debugger then the installation/config instructions need updated to reflect this. agree yes?

yes, instructions need an update. what i mean with "just pick one" is: go to the network tab, pick one of the request that were performed when you opened the tab/window, pick the user agent from the header. your chrome always uses the up-to-date user agent for all new requests

**Comment by chenks** [comment]
> yes, instructions need an update. what i mean with "just pick one" is: go to the network tab, pick one of the request that were performed when you opened the tab/window, pick the user agent from the header. your chrome always uses the up-to-date user agent for all new requests

that's the thing, the network tab is showing nothing at all - as per the screenshot i posted.

**Comment by bigbluedeer** [comment]
> > yes, instructions need an update. what i mean with "just pick one" is: go to the network tab, pick one of the request that were performed when you opened the tab/window, pick the user agent from the header. your chrome always uses the up-to-date user agent for all new requests
> 
> that's the thing, the network tab is showing nothing at all - as per the screenshot i posted.

not while searching for something. ?app is a search, nothing matches because it has been removed. dont search, then you will see all the requests. pick one, copy the user agent, finished

**Comment by chenks** [comment]
ok sorted.
my sess id had changed as well, so both updated and it's now logging in OK again.

**Comment by DIGITALCRIMINAL** [comment]
They changed it to api2
