### ISSUE TITLE
Enhancement: Add mentionedUsers or linkedUsers to path_formatting options

### ISSUE THREAD

**Issue by koalahntr** [DIGITALCRIMINAL/OnlyFans#896]
Cross promotions are seriously getting out of hand with a lot of models and really cluttering up our archives. It would be great if we could use mentionedUsers and/or linkedUsers (not sure how OF differentiates) in the path formatting. There may have to be some magic to convert from ID's to usernames, as well as concatenate in some way when there are a two or more

The idea then is you could have subfolders for the cross-promotions within a given model's directory.

**Comment by ProjektPremium** [comment]
If you are using windows, I suggest this; In the content folder you are in, right click and select "Sort By" and then select "More". Push the "D" key 7 times or manually click "Date created". Right click in the folder and select "Sort by Date Created" then select "Ascending".

Most of the cluttered crap will be down towards the bottom, making it easier to filter through the files but doesn't make it as time consuming as if you were to sort them in order of name.

**Comment by bobsage123** [comment]
I see something related to linked was added as it's adding "linked_" to the front of some files. But it's screwing up my sorting which I sort by date. Not sure if there's a way to move where "linked" is put in the filename.

linked_[2021-02-14] (0gnnkga64ox29gpnyzgqp_source).mp4

**Comment by aboredpervert** [comment]
In my observation, the quickest way to skip all promoted content is to never scrape timed posts.
The change is simple, if post has an `expiredAt` value, skip it.
Like this: https://github.com/aboredpervert/OnlyFans/commit/c0de0d4431be1f481245630a25f833f0f5928eb2
Warning: you lose the stories too, doing that.

**Comment by bobsage123** [comment]
I suspect "linked" files are supposed to be files located at a different channel but are linked from the channel you're subbed to. The problem is, some of the files that are from the channels I subbed to, are getting re-downloaded as a dupe with the word "linked_" in the filename. Still no idea why this is happening.

**Comment by DIGITALCRIMINAL** [comment]
They added this

![image](https://user-images.githubusercontent.com/21285176/119213136-edb6ec80-bab4-11eb-9fae-544b9f4e3d41.png)
