### ISSUE TITLE
infinite loop at the end of a succesfull scraping

### ISSUE THREAD

**Issue by tenaka18** [DIGITALCRIMINAL/OnlyFans#90]
hi 
i used your scraper with success.
one thing i noticed is:
the script doesn't end when finished but it get stuck in an infinite loop.

my python version and operative system:
- Python 3.7.3
- Linux version 4.19.0-6-amd64 # 1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux 

my config.json

`
{
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "multithreading": true,
    "user-agent": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  "supported": {
    "onlyfans": {
      "auth": {
        "app-token": "XXXXXXXXXXXXXXXXXXXXXXXX",
        "auth_id": "XXXXXXXXXXXXX",
        "auth_hash": "XXXXXXXXXXXXXXXXXXX"
      },
      "settings": {
        "auto_choice": "a",
        "auto_scrape_all": true,
        "directory": "/home/myuser/",
        "file_name_format": "{username}/{date}/{text}-{file_name}.{ext}",
        "text_length": "50",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": []
      }
    },
    "justforfans": {
      "auth": {
        "phpsessid": "",
        "user_hash2": ""
      },
      "settings": {
        "auto_choice": "",
        "auto_scrape_all": false,
        "directory": "",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "",
        "overwrite_files": true,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": []
      }
    },
    "4chan": {
      "auth": {},
      "settings": {
        "auto_choice": "",
        "auto_scrape_all": false,
        "directory": "",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "boards": [],
        "ignored_keywords": []
      }
    },
    "bbwchan": {
      "auth": {},
      "settings": {
        "auto_choice": "",
        "auto_scrape_all": false,
        "directory": "",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "boards": [],
        "ignored_keywords": []
      }
    }

  }
}

`

**Comment by DIGITALCRIMINAL** [comment]
Download:
https://github.com/DIGITALCRIMINAL/OnlyFans/releases/tag/3.5.2
