### ISSUE TITLE
feature request: make text unique by appending an index at the end

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINAL/OnlyFans#901]
I want to preserve as much of the title as possible and since file names are limited to 255 characters filename and media_id cut into that. so I propose checking if a file with the same title already exists and if it does numbering the new file to make it unique.

**Comment by DIGITALCRIMINAL** [comment]
I don't want to do that... All the text is stored in the database anyway, so you're free to modify the content after it's been downloaded.
