### ISSUE TITLE
Downloads keep failing

### ISSUE THREAD

**Issue by j-ktz** [DIGITALCRIMINAL/OnlyFans#902]
Any idea why this keeps happening? 
<img width="966" alt="screenshot 2021-03-06 at 5 09 30 PM" src="https://user-images.githubusercontent.com/59346628/110222245-d34e7900-7e9e-11eb-8702-c5f8e6cdf506.png">

**Comment by ProjektPremium** [comment]
Model name?

**Comment by j-ktz** [comment]
@ProjektPremium daltonrileyxxx

**Comment by ProjektPremium** [comment]
Yeah I just had a look at their content count, usually it fails when they have content counts in the thousands. No idea then.

**Comment by j-ktz** [comment]
Hmm, yeah I only chose to scrape videos, and he's only got 83. Strange.

**Comment by DIGITALCRIMINAL** [comment]
Are you using a proxy?

**Comment by j-ktz** [comment]
@DIGITALCRIMINAL I use a VPN, but always do and never run into this error.

**Comment by DIGITALCRIMINAL** [comment]
Usually doing multiple runs makes the content download
