### ISSUE TITLE
Failure in start_datascraper

### ISSUE THREAD

**Issue by pyrometheous** [DIGITALCRIMINAL/OnlyFans#903]
![Error Screenshot](https://imgur.com/DTUZy35.jpg)
<br>
Everything has been working fine until a few days ago, then I started getting this with a couple of models, and I just recently subscribed to a new model, and her download is failing right out of the gate.
<br>
It also seems to be inconsistent, like it'll do some models fine, then error part way through a download. Or fail almost immediately.

**Comment by headphonia** [comment]
try the latest [commit](https://github.com/DIGITALCRIMINAL/OnlyFans/archive/master.zip).

**Comment by pyrometheous** [comment]
Looks like that's doing it so far. Thanks for the quick fix :-)
