### ISSUE TITLE
Expired Models still appearing? Fix here.

### ISSUE THREAD

**Issue by ProjektPremium** [DIGITALCRIMINAL/OnlyFans#906]
Didn't come across this problem until OF's latest outage. At the top of my scrape list, I have maybe 9 models who appear on the list, but their subscription has expired. I go to their profile and I cannot see the content but they aren't in my expired or subscribed list on the site.

The only way around this is to block them, so to all that may have encountered this problem, blocking them is the only way the name gets removed from your scraping list. Once you unblock them again, they reappear but cannot be scraped.

**Comment by JohnnyTowns94** [comment]
Or add them to your blacklist.

**Comment by Kurosaki22** [comment]
Adding to blacklist doesnt work for me.
Will try the block feature

**Comment by ProjektPremium** [comment]
> 
> 
> Or add them to your blacklist.

That is also true but I find it easier just blocking them.

**Comment by ProjektPremium** [comment]
This problem doesn't occur anymore, closing.
