### ISSUE TITLE
Auth loop after starting the python Script

### ISSUE THREAD

**Issue by kevkov202** [DIGITALCRIMINAL/OnlyFans#91]
Hey,

I am running into an authentification loop after starting the script. I triple checked the cookie data, it's definitely correct. Also deactivated 2FA in my account. Is there any way to locate the error more precisely or get an error log what exactly went wrong? My python knowlege is really limited to the basics :-) 

```
xxx@debian:~/OnlyFans$ python3.8 StartDatascraper.py
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10

```
Python version installed is 3.8.1

Kind regards,

kev

**Comment by DIGITALCRIMINAL** [comment]
Did you fill in the session token?

**Comment by kevkov202** [comment]
Yep. All from the Chrome Network Analyzer. I filled in "app-token", "auth_id", "auth_hash" and "sess" just like shown in the screenshot. 

What I noticed is that the "sess" token changes every time I log in in chrome. I hope that’s normal.

**Comment by DIGITALCRIMINAL** [comment]
@kevkov202 try it without the sess token.
It's normal for it to change if you log in again.

**Comment by kevkov202** [comment]
Same bevahiour without sess token. I also set up a completely new machine in docker and installed it from scratch, still the same auth loop.

**Comment by DIGITALCRIMINAL** [comment]
Are you using the script on the same computer as the one you're logged into on OnlyFans?

**Comment by kevkov202** [comment]
I was running it on a debian remote machine. Is it mandatory to run in on the same machine where you run the browser to login?

Have tried it on my local ubuntu now - sadly no change. Still the auth loop. No matter if I insert the sess token or leave it empty.

**Comment by DIGITALCRIMINAL** [comment]
@kevkov202 

If you're using only auth_id and auth_hash you can log in from any IP without the correct User-Agent (sometimes)
If you're using auth_id, auth_hash, and sess, it has to be from the same IP address as the one you're logged into.

Preferably all cookies must be filled in .-.
I also forgot to ask what Python version are you using?

**Comment by kevkov202** [comment]
Ah, now I'm getting it. But the IP should have been the same on all machines as I'm connected to it via vpn while surfing.

I tried it on my windows machine now. Still the same. Tried it with and withoug vpn.  I did nothing but installing python, installing pip, install requirements via pip and then edit the config and run "python StartDatascraper.py" in cmd. I attached a screenshot of my config below. I only changed the 4 auth variables, auto_site_choice and auto_choice for onlyfans.

![config](https://user-images.githubusercontent.com/59096236/71365847-7d92f700-25a0-11ea-917b-fd8119a56e53.PNG)

I really have no idea what I could possibly be doing wrong.

**Comment by DIGITALCRIMINAL** [comment]
@kevkov202 Hmm just to be 100% sure you did try with the correct User-Agent right?

**Comment by kevkov202** [comment]
Shame on me. I've gone through the Readme like 10 times and never saw that point ._. Works like a charm now. On my windows machine as well as on my linux machine. Just feeling a little stupid right now.

Thanks for your support and your amazing script! :-)

**Comment by DIGITALCRIMINAL** [comment]
My bad, honestly I should have called it out first since it was a common fix. I'm also going to add it to the FAQ at the bottom of the readme. Thanks and glad it's working.

**Comment by DIGITALCRIMINAL** [comment]
By the way, OnlyFans just updated the API so I have just pushed a new release to fix the script.
