### ISSUE TITLE
Can't download specific model.

### ISSUE THREAD

**Issue by Joakimgreenday** [DIGITALCRIMINAL/OnlyFans#911]
Whenever I run it as I usually do from 
CMD
Python39 start_ofd.py

I get this specific model that gets the constant "retrying" / "missing posts".
`

> Type: Profile
> 0.00B [00:00, ?B/s]
> Type: Stories
> No Stories Found.
> Type: Posts
> Scrape Attempt: 1/100
> Missing 200 Posts... Retrying...
> Scrape Attempt: 2/100
> Missing 200 Posts... Retrying...
> Scrape Attempt: 3/100
> Missing 400 Posts... Retrying...
> Scrape Attempt: 4/100
> Missing 533 Posts... Retrying...
> Scrape Attempt: 5/100
> Missing 800 Posts... Retrying...
> Scrape Attempt: 6/100
> Missing 1280 Posts... Retrying...
> Scrape Attempt: 7/100
> Missing 1066 Posts... Retrying...
> Scrape Attempt: 8/100
> Missing 914 Posts... Retrying...
> Scrape Attempt: 9/100
> Missing 800 Posts... Retrying...
> Scrape Attempt: 10/100
> Missing 711 Posts... Retrying...
> Scrape Attempt: 11/100
> Missing 640 Posts... Retrying...
> Scrape Attempt: 12/100
> Missing 581 Posts... Retrying...
> Scrape Attempt: 13/100
> Missing 533 Posts... Retrying...
> Scrape Attempt: 14/100
> Missing 492 Posts... Retrying...
> Scrape Attempt: 15/100
> Missing 457 Posts... Retrying...
> Scrape Attempt: 16/100
> Missing 426 Posts... Retrying...
> Scrape Attempt: 17/100
> Missing 400 Posts... Retrying...
> Scrape Attempt: 18/100
> Missing 376 Posts... Retrying...
> Scrape Attempt: 19/100
> Missing 355 Posts... Retrying...
> Scrape Attempt: 20/100
> Missing 336 Posts... Retrying...
> Scrape Attempt: 21/100
> Missing 320 Posts... Retrying...
> Scrape Attempt: 22/100
> Missing 304 Posts... Retrying...
> Scrape Attempt: 23/100
> Missing 290 Posts... Retrying...
> Scrape Attempt: 24/100
> Missing 278 Posts... Retrying...
> Scrape Attempt: 25/100
> Missing 266 Posts... Retrying...
> Scrape Attempt: 26/100
> Missing 256 Posts... Retrying...
> Scrape Attempt: 27/100
> Missing 246 Posts... Retrying...
> Scrape Attempt: 28/100
> Missing 237 Posts... Retrying...
> Scrape Attempt: 29/100
> Missing 228 Posts... Retrying...
> Scrape Attempt: 30/100
> Missing 220 Posts... Retrying...
> Scrape Attempt: 31/100
> Missing 213 Posts... Retrying...
> Scrape Attempt: 32/100
> Missing 206 Posts... Retrying...
> Scrape Attempt: 33/100
> Missing 200 Posts... Retrying...
> Scrape Attempt: 34/100
> Missing 193 Posts... Retrying...
> Scrape Attempt: 35/100
> Missing 188 Posts... Retrying...
> Scrape Attempt: 36/100
> Missing 182 Posts... Retrying...
> Scrape Attempt: 37/100
> Missing 177 Posts... Retrying...
> Scrape Attempt: 38/100
> Missing 172 Posts... Retrying...
> Scrape Attempt: 39/100
> Missing 168 Posts... Retrying...
> Scrape Attempt: 40/100
> Missing 164 Posts... Retrying...
> Scrape Attempt: 41/100
> Missing 160 Posts... Retrying...
> Scrape Attempt: 42/100
> Missing 156 Posts... Retrying...
> Scrape Attempt: 43/100
> Missing 152 Posts... Retrying...
> Scrape Attempt: 44/100
> Missing 148 Posts... Retrying...
> Scrape Attempt: 45/100
> Missing 145 Posts... Retrying...
> Scrape Attempt: 46/100
> Missing 142 Posts... Retrying...
> Scrape Attempt: 47/100
> Missing 139 Posts... Retrying...
> Scrape Attempt: 48/100
> Missing 136 Posts... Retrying...
> Scrape Attempt: 49/100
> Missing 133 Posts... Retrying...
> Scrape Attempt: 50/100
> Missing 130 Posts... Retrying...
> Scrape Attempt: 51/100
> Missing 128 Posts... Retrying...
> Scrape Attempt: 52/100
> Missing 125 Posts... Retrying...
> Scrape Attempt: 53/100
> Missing 123 Posts... Retrying...
> Scrape Attempt: 54/100
> Missing 120 Posts... Retrying...
> Scrape Attempt: 55/100
> Missing 118 Posts... Retrying...
> Scrape Attempt: 56/100
> Missing 116 Posts... Retrying...
> Scrape Attempt: 57/100
> Missing 114 Posts... Retrying...
> Scrape Attempt: 58/100
> Missing 112 Posts... Retrying...
> Scrape Attempt: 59/100
> Missing 110 Posts... Retrying...
> Scrape Attempt: 60/100
> Missing 108 Posts... Retrying...
> Scrape Attempt: 61/100
> Missing 106 Posts... Retrying...
> Scrape Attempt: 62/100
> Missing 104 Posts... Retrying...
> Scrape Attempt: 63/100
> Missing 103 Posts... Retrying...
> Scrape Attempt: 64/100
> Missing 101 Posts... Retrying...
> Scrape Attempt: 65/100
> Missing 100 Posts... Retrying...
> Scrape Attempt: 66/100
> Missing 98 Posts... Retrying...
> Scrape Attempt: 67/100
> Missing 96 Posts... Retrying...
> Scrape Attempt: 68/100
> Missing 95 Posts... Retrying...
> Scrape Attempt: 69/100
> Missing 94 Posts... Retrying...
> Scrape Attempt: 70/100
> Missing 92 Posts... Retrying...
> Scrape Attempt: 71/100
> Missing 91 Posts... Retrying...
> Scrape Attempt: 72/100
> Missing 90 Posts... Retrying...
> Scrape Attempt: 73/100
> Missing 88 Posts... Retrying...
> Scrape Attempt: 74/100
> Missing 87 Posts... Retrying...
> Scrape Attempt: 75/100
> Missing 86 Posts... Retrying...
> Scrape Attempt: 76/100
> Missing 85 Posts... Retrying...
> Scrape Attempt: 77/100
> Missing 84 Posts... Retrying...
> Scrape Attempt: 78/100
> Missing 83 Posts... Retrying...
> Scrape Attempt: 79/100
> Missing 82 Posts... Retrying...
> Scrape Attempt: 80/100
> Missing 81 Posts... Retrying...
> Scrape Attempt: 81/100
> Missing 80 Posts... Retrying...
> Scrape Attempt: 82/100
> Missing 79 Posts... Retrying...
> Scrape Attempt: 83/100
> Missing 78 Posts... Retrying...
> Scrape Attempt: 84/100
> Missing 77 Posts... Retrying...
> Scrape Attempt: 85/100
> Missing 76 Posts... Retrying...
> Scrape Attempt: 86/100
> Missing 75 Posts... Retrying...
> Scrape Attempt: 87/100
> Missing 74 Posts... Retrying...
> Scrape Attempt: 88/100
> Missing 73 Posts... Retrying...
> Scrape Attempt: 89/100
> Missing 72 Posts... Retrying...
> Scrape Attempt: 90/100
> Missing 71 Posts... Retrying...
> Scrape Attempt: 91/100
> Missing 71 Posts... Retrying...
> Scrape Attempt: 92/100
> Missing 70 Posts... Retrying...
> Scrape Attempt: 93/100
> Missing 69 Posts... Retrying...
> Scrape Attempt: 94/100
> Missing 68 Posts... Retrying...
> Scrape Attempt: 95/100
> Missing 68 Posts... Retrying...
> Scrape Attempt: 96/100
> Missing 67 Posts... Retrying...
> Scrape Attempt: 97/100
> Missing 66 Posts... Retrying...
> Scrape Attempt: 98/100
> Missing 65 Posts... Retrying...
> Scrape Attempt: 99/100
> Missing 65 Posts... Retrying...
> Scrape Attempt: 100/100
> Missing 64 Posts... Retrying...
> Processing metadata.
> Finished processing metadata.

`

For privacy and legal reasons I will not openly write the name, but send you it in encrypted basic "base-sixty-four".
`Inl1a2tpX2FtZXkiIA0K`

Good luck! If there are any questions about more information I'm willing to respond.

**Comment by Joakimgreenday** [comment]
I also get this when after it skips
Traceback (most recent call last):

>   File "F:\Onlyfans\Onlyfans 6.4.2\start_ofd.py", line 40, in <module>
>     x = int(x)
> ValueError: invalid literal for int() with base 10: 'a' 

then it just stops.

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit

**Comment by Joakimgreenday** [comment]
> Use the latest commit

I am using the latest version, If that's what you mean :)

**Comment by DIGITALCRIMINAL** [comment]
> > Use the latest commit
> 
> I am using the latest version, If that's what you mean :)

What is the latest version

**Comment by SeaOrb** [comment]
I'm pretty sure this is due to subscription expiry. Check if you still have access to the model's content. Try blacklististing or wait untill OF updates the access.
