### ISSUE TITLE
ValueError: Key name of object must be 'string' when decoding 'object' error

### ISSUE THREAD

**Issue by poubelle34** [DIGITALCRIMINAL/OnlyFans#913]
Hello,
I got this error when I star the script.
I follow the tutorial, so I'm not sure if it's an an auth error or a bug.
app version :  6.4.2, python version:  3.9.2
Does someone have a clue ? thanks

![image](https://user-images.githubusercontent.com/80391946/110614207-6551cc80-8192-11eb-8758-8c8d4db10d53.png)

**Comment by DIGITALCRIMINAL** [comment]
You messed up your auth.json. You need to fix it.
