### ISSUE TITLE
Feature suggestion and metadata only download

### ISSUE THREAD

**Issue by SeaOrb** [DIGITALCRIMINAL/OnlyFans#916]
Hello, first I'd like to thank you. Thank you.
So currently we can download one or all usernames but it would be great if the program accepted multiple names at once like "user1 user2 user3" and downloaded only those automatically, or maybe a "whitelist"? that you can only download from that — like the current blacklist works

also will 'metadata only' download come back?

Have a great week :-)

**Comment by jp1151419** [comment]
You can list multiple users by separating them with a comma.

I do agree that a whitelist would be awesome though, I've been looking forward to that since it was first suggested

**Comment by SeaOrb** [comment]
> 
> 
> You can list multiple users by separating them with a comma.

OH MY I didn't knew that 🤦‍♀️ Thank you very much!

**Comment by DIGITALCRIMINAL** [comment]
> also will 'metadata only' download come back?

Not anytime soon.
