### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by hammerheaddf** [DIGITALCRIMINAL/OnlyFans#919]
Running current commit `c197e77` on Raspbian gives me this:
`Traceback (most recent call last):
  File "/home/myuser/OnlyFans/start_ofd.py", line 14, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "/home/myuser/OnlyFans/datascraper/main_datascraper.py", line 11, in <module>
    import modules.onlyfans as m_onlyfans
  File "/home/myuser/OnlyFans/modules/onlyfans.py", line 1092
    if found_medias:
IndentationError: expected an indented block`

**Comment by headphonia** [comment]
I'm also getting this error.

**Comment by nappyapp** [comment]
after the `else` on line 1089 of modules/onlyfans.py, add a `pass` on the next line. so it looks like this:

```else:
    pass
```

**Comment by DIGITALCRIMINAL** [comment]
Fixed in the latest commit. I accidentally removed that line.
