### ISSUE TITLE
ModuleNotFoundError: No module named 'user_agent'

### ISSUE THREAD

**Issue by secretiveolwagner** [DIGITALCRIMINAL/OnlyFans#920]
I just updated with the latest commit and it's showing this error
![7342309472394293042](https://user-images.githubusercontent.com/69245900/111031077-daa2f300-8459-11eb-92a3-df1df0ead075.PNG)
This is only occurred after I applied the latest commit. but when I used the initial release of version 6.4.2 and it worked just fine.
I also tried to re-download the script using `git clone` because I suspected I screwed up some settings without realising it unfortunately I still ran into the same error.

**Comment by hammerheaddf** [comment]
Getting the same error on release `ff9f021`

**Comment by valdearg** [comment]
```pip install user_agent``` 

Will do it for now.

**Comment by DIGITALCRIMINAL** [comment]
> `pip install user_agent`
> 
> Will do it for now.

yes
