### ISSUE TITLE
ModuleNotFoundError: No module named 'user_agent'

### ISSUE THREAD

**Issue by NorskGod** [DIGITALCRIMINAL/OnlyFans#922]
recieving this error when i try to run program

**Comment by DIGITALCRIMINAL** [comment]
run requirements lul

**Comment by NorskGod** [comment]
> run requirements lul

![Screenshot 2021-03-13 180743](https://user-images.githubusercontent.com/80601343/111052217-238d8400-8427-11eb-92e5-0a0dab65739a.png)
