### ISSUE TITLE
Maintain 6.3.x until 6.4.x is stable

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINAL/OnlyFans#924]
I have yet to encounter a working version of the 6.4 branch.

Can you provide periodic updates to 6.3.x to keep it working? I don’t need progress bars or sqlite metadata, I just need f*ing content and 6.4 is like alpha software.

**Comment by DIGITALCRIMINAL** [comment]
The script is mainly made for me and my needs. I don't have time to maintain different versions. 
There are multiple other scripts out there that will fulfill your needs.

I haven't seen any issues opened by you since 6.4 released, I've only seen you comment on issues that were reported as fixed.
