### ISSUE TITLE
Auth problem

### ISSUE THREAD

**Issue by GuglPlay** [DIGITALCRIMINAL/OnlyFans#927]
Im tryin to log in from new master version (03/14/2021), im download geckodriver and put it to \extras\OFLogin but I got this:

_Choose Profile
Names: Username = username  |  0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "E:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "E:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "E:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 117, in account_setup
    cookies = oflogin.login(api, domain, proxy)
  File "E:\OnlyFans-master\OnlyFans-master\extras\OFLogin\start_ofl.py", line 75, in login
    web_browser = launch_browser(
  File "E:\OnlyFans-master\OnlyFans-master\extras\OFLogin\start_ofl.py", line 27, in launch_browser
    opts = webdriver.FirefoxOptions()
AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'_

**Comment by DIGITALCRIMINAL** [comment]
Run requirements

**Comment by malonecries** [comment]
I've encountered the same problem even after running the requirements. 

gecko is installed in the extras and I have firefox and chrome installed.

**Comment by malonecries** [comment]
> I've encountered the same problem even after running the requirements.
> 
> gecko is installed in the extras and I have firefox and chrome installed.

I've just reopened the auth.json my username is being written as 'default' I change it back to what my username should be, then run the script and it gets changed back to 'default'

**Comment by malonecries** [comment]
> Im tryin to log in from new master version (03/14/2021), im download geckodriver and put it to \extras\OFLogin but I got this:
> 
> _Choose Profile Names: Username = username | 0 = All | 1 = default 1 Auth (V1) Attempt 1/10 Access denied. Auth (V1) Attempt 2/10 Access denied. Auth (V1) Attempt 3/10 Access denied. Auth (V1) Attempt 4/10 Access denied. Auth (V1) Attempt 5/10 Access denied. Auth (V1) Attempt 6/10 Access denied. Auth (V1) Attempt 7/10 Access denied. Auth (V1) Attempt 8/10 Access denied. Auth (V1) Attempt 9/10 Access denied. Auth (V1) Attempt 10/10 Access denied. Opening Browser Traceback (most recent call last): File "E:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 43, in apis = main_datascraper.start_datascraper(json_config, site_name_lower) File "E:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 78, in start_datascraper setup, subscriptions = module.account_setup( File "E:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 117, in account_setup cookies = oflogin.login(api, domain, proxy) File "E:\OnlyFans-master\OnlyFans-master\extras\OFLogin\start_ofl.py", line 75, in login web_browser = launch_browser( File "E:\OnlyFans-master\OnlyFans-master\extras\OFLogin\start_ofl.py", line 27, in launch_browser opts = webdriver.FirefoxOptions() AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'_

I have poked at this for a while now;

Using the latest commit I did the following:
- deleted the install
- set up 2fa on my account
- that seems to have provided me with a new cookie
- disabled 2fa on my account
- set "support_2fa" to false leaving email password empty 
- pasted the new "sess" into the auth.json and it's now working

now to get to my original task of trying to get the infinite loop working aha

**Comment by jaxsonm75** [comment]
> > Im tryin to log in from new master version (03/14/2021), im download geckodriver and put it to \extras\OFLogin but I got this:
> > _Choose Profile Names: Username = username | 0 = All | 1 = default 1 Auth (V1) Attempt 1/10 Access denied. Auth (V1) Attempt 2/10 Access denied. Auth (V1) Attempt 3/10 Access denied. Auth (V1) Attempt 4/10 Access denied. Auth (V1) Attempt 5/10 Access denied. Auth (V1) Attempt 6/10 Access denied. Auth (V1) Attempt 7/10 Access denied. Auth (V1) Attempt 8/10 Access denied. Auth (V1) Attempt 9/10 Access denied. Auth (V1) Attempt 10/10 Access denied. Opening Browser Traceback (most recent call last): File "E:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 43, in apis = main_datascraper.start_datascraper(json_config, site_name_lower) File "E:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 78, in start_datascraper setup, subscriptions = module.account_setup( File "E:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 117, in account_setup cookies = oflogin.login(api, domain, proxy) File "E:\OnlyFans-master\OnlyFans-master\extras\OFLogin\start_ofl.py", line 75, in login web_browser = launch_browser( File "E:\OnlyFans-master\OnlyFans-master\extras\OFLogin\start_ofl.py", line 27, in launch_browser opts = webdriver.FirefoxOptions() AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'_
> 
> I have poked at this for a while now;
> 
> Using the latest commit I did the following:
> 
> * deleted the install
> * set up 2fa on my account
> * that seems to have provided me with a new cookie
> * disabled 2fa on my account
> * set "support_2fa" to false leaving email password empty
> * pasted the new "sess" into the auth.json and it's now working
> 
> now to get to my original task of trying to get the infinite loop working aha

I tried going this but i wasnt able to get it to work, do you have anymore insight? Thanks
