### ISSUE TITLE
Lacking .settings

### ISSUE THREAD

**Issue by Synchrololled69** [DIGITALCRIMINAL/OnlyFans#932]
So i've tried running the program which returns the following:

![image](https://user-images.githubusercontent.com/22560492/111211357-984ef280-85ce-11eb-8de7-d22a0c6aead0.png)

And I cannot find the .settings folder either with hidden folders enabled

![image](https://user-images.githubusercontent.com/22560492/111211164-60e04600-85ce-11eb-8795-136d4045913c.png)
I know it's in my own language but making hidden folders visable checked.

**Comment by secretiveolwagner** [comment]
How hard is it to follow [this](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/README.md#running-the-app-locally)?

**Comment by Synchrololled69** [comment]
I have pip installed, I have visual studio installed? 

![image](https://user-images.githubusercontent.com/22560492/111225410-11a31100-85e0-11eb-872c-ac7e7607e0c3.png)

**Comment by secretiveolwagner** [comment]
I don't know, you tell me

I have a better solution for you, [use this instead](https://chrome.google.com/webstore/detail/downloader-for-onlyfansco/pdbbabjcnanbkimdgcdfbnghhmchomnh)

**Comment by mikebatnz** [comment]
The latest version (1.4) of sqlalchemy isn't compatible.

You can install the previous version (1.3.23) with this command:
`pip install sqlalchemy==1.3.23`

**Comment by Synchrololled69** [comment]
> The latest version (1.4) of sqlalchemy isn't compatible (see also #933 )
> 
> You can install the previous version (1.3.23) with this command:
> `pip install sqlalchemy==1.3.23`

Looks like that works awesome!

**Comment by Synchrololled69** [comment]
> I don't know, you tell me
> 
> I have a better solution for you, [use this instead](https://chrome.google.com/webstore/detail/downloader-for-onlyfansco/pdbbabjcnanbkimdgcdfbnghhmchomnh)

Then why act so agressive right away? 

It was an issue with the requirements grabbing a newer version of a dependency which didn't work. and a quick install of an older version resolved it and now it works perfectly. So thanks for that Mike 👍 


 I'd rather tick in some commands than click 100000 buttons.

**Comment by secrets69** [comment]
Hey @mikebatnz and @Synchrololled69, thanks for the tip. I've made a pull request to add those changes so people know!

Also, just have to say, @secretiveolwagner is the absolute worst lol

**Comment by DIGITALCRIMINAL** [comment]
@secrets69 there was no pull request
