### ISSUE TITLE
SQLAlchemy 1.4 not supported

### ISSUE THREAD

**Issue by blade2005** [DIGITALCRIMINAL/OnlyFans#933]
https://github.com/DIGITALCRIMINAL/OnlyFans/blob/879193bcd07551f481c4f0a8b968dd1adc9b7aa6/requirements.txt#L14

Looks like they changed how things are laid out in 1.4. sqlaclhemy.ext.declarative.api isn't valide any more.

**Comment by DIGITALCRIMINAL** [comment]
Ahh, ye, I was gonna upgrade to the beta a week ago but that would be redoing all of that.

**Comment by DIGITALCRIMINAL** [comment]
Ahh, ye, I was gonna upgrade to the beta a week ago but that would be redoing all of that.
