### ISSUE TITLE
Onlyfans Menu Including Free Accounts That Were Previously Unfollowed

### ISSUE THREAD

**Issue by NotMyMainAccount** [DIGITALCRIMINAL/OnlyFans#94]
Hi, the new update has everything working again however there's a slightly annoying issue and that is that previously followed free accounts on Onlyfans are showing up in the list of accounts followed. These accounts have all been unfollowed for a bit of time now. This is an issue because I want to select scrape all and there's currently 8 accounts I follow so I'd prefer not to have to select each one at a time in order to avoid the extra accounts I don't want to scrape. This wasn't an issue with the previous version and my config file hasn't changed.

Any help would be appreciated.

**Comment by DIGITALCRIMINAL** [comment]
Yeah it's something I personally changed. Just to know you've unfollowed the accounts for a month now?

Should I add a setting that ignores unfollowed free accounts or ignores unfollowed accounts?

**Comment by NotMyMainAccount** [comment]
If you could add a setting to ignore the unfollowed free accounts I think would be best. Reason being, if you follow and then unfollow a free account, odds are it's because there's no content worth seeing. If you want the content still then you could always stay subbed until you get what you want. Of course others might see it differently but I think the option would be a good one to have.

Also just want to say thanks for the tool. It's exactly what I was looking for and works great with all the options you have in it.

**Comment by DIGITALCRIMINAL** [comment]
@NotMyMainAccount added the option for both. 
Added "ignore_unfollowed_accounts" to the new config and readme.
