### ISSUE TITLE
kindly help with this issue

### ISSUE THREAD

**Issue by freakish804** [DIGITALCRIMINAL/OnlyFans#945]
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\datascraper\main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\modules\onlyfans.py", line 117, in account_setup
    cookies = oflogin.login(api, domain, proxy)
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\extras\OFLogin\start_ofl.py", line 27, in launch_browser
    opts = webdriver.FirefoxOptions()
AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'

Everytime its showing this error. kindly please someone guide me

**Comment by jaxsonm75** [comment]
I'm also having this issue. I have firefox installed and ran the requirements.

**Comment by secretiveolwagner** [comment]
If you guys just want to run the script normally, you just need to enter `sess` accordingly and that should "fix" the problem.

However if you want to run it with Selenium (as the commit suggested, fill in email and password (only)), it's a little bit tricky. I got curious and spent few hours yesterday try to make it work with Selenium. With my limited knowledge of Selenium (as well as Python) I don't think the script launches the browser properly or I'm too dumb to understand Selenium and not how to configure it properly (correct me if I'm wrong @DIGITALCRIMINAL).

Like you mentioned I followed the instruction and simply put my email, password and user-agent and the rest empty (I assume you did the same as well) in `auth.json`. I got the same error without Firefox being launched by the script.

In my opinion and my basic understanding (from reading `start_ofl.py`) this is what @DIGITALCRIMINAL wants;

1. Auth failed (with 2FA disabled, even the Selenium documentation suggested so), the scripts launches Firefox (or Chrome) via Selenium
2. Grabs email and password from `auth.json` and auto-fill it (?)
3. Log in successfully and the script grabs `sess`, `auth-id` and `user-agent` from the website
4. Pass them on to `auth.json` (?)
5. The main script is now logged in
6. Scrap OF contents as usual

**Comment by DIGITALCRIMINAL** [comment]
You either have the old version of gecko or an old version of Selenium from what I'm reading

**Comment by secretiveolwagner** [comment]
I just confirmed I have the latest version of both Selenium (3.141.0) and geckodriver (v0.29) and still got the same error

**Comment by DIGITALCRIMINAL** [comment]
My geckodriver is 0.27.0

**Comment by secretiveolwagner** [comment]
This is what I did, I re-downloaded the 6.4.3.zip, put the geckodriver v27 accordingly, ran `pip install -r requirements.txt`, made sure VS Build Tools 2019 is installed, filled only `user-agent`, `email` and `password` in `auth.json`. Still got the same error.

I also try both 32 bit and 64 bit geckodriver. Didn't help

**Comment by dballs6666** [comment]
well it works for me, but ignore the email and password, just enter auth_id , sess and user_agent

**Comment by jaxsonm75** [comment]
I'm still not able to get it to work I've tried many different things. Anyone able to provide assistance?

**Comment by freakish804** [comment]
with only user id, sess and user agent its showing 'there is nothing to scrape'

**Comment by secretiveolwagner** [comment]
Start from scratch.

Reset you script by redownloading the latest zip, [**follow this**](https://github.com/DIGITALCRIMINAL/OnlyFans#mandatory-tutorial). Procced from there.

**Comment by freakish804** [comment]
Already tried twice but still the same result. it wasnt like this before. all this happening after onlyfans drastically updated their site

**Comment by jaxsonm75** [comment]
Feels like I've tried everything just not sure what I'm not getting. I'll pay one of you for help at this point!

**Comment by icemouton** [comment]
I've been having the same issue @jaxsonm75 I tried on a different machine (I used to run it on linux, tried windows) I tried using docker, I don't think it's us, I think something changed on OF side, and maybe it doesn't affect all users just yet...

**Comment by DIGITALCRIMINAL** [comment]
Download from master and reinstall the requirements.
