### ISSUE TITLE
geckodriver linux

### ISSUE THREAD

**Issue by sintaxx** [DIGITALCRIMINAL/OnlyFans#946]
Does the browser auth work with linux? I downloaded geckodriver but i see you mentioned exe support only ? if not, do you plan on adding linux support ?

**Comment by DIGITALCRIMINAL** [comment]
> Does the browser auth work with linux? I downloaded geckodriver but i see you mentioned exe support only ? if not, do you plan on adding linux support ?

Yee I can add it in, is there an extension for for it? I've got geckodriver.exe but for linux is there an extension?

**Comment by secretiveolwagner** [comment]
There is...
![0849032483902489302](https://user-images.githubusercontent.com/69245900/111783882-d02ba200-890e-11eb-8fd7-594492055a15.PNG)

**Comment by DIGITALCRIMINAL** [comment]
I dunno which one to run

**Comment by sintaxx** [comment]
> I dunno which one to run

Amd64 is for Linux and it doesn't have an extension, most Linux binaries don't use them

**Comment by DIGITALCRIMINAL** [comment]
If you use the latest commit, the script searches for geckodriver. Make sure you place it in extras/OFLogin

![image](https://user-images.githubusercontent.com/21285176/111835139-7ca85c80-88ec-11eb-908a-403a93a389a6.png)

**Comment by icemouton** [comment]
Having problems using geckodriver under linux as well.

I added the linux geckodriver binary to the folder and now I'm getting
`
Traceback (most recent call last):
  File "/OnlyFans/start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/OnlyFans/datascraper/main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "/OnlyFans/modules/onlyfans.py", line 117, in account_setup
    cookies = oflogin.login(api, domain, proxy)
  File "/OnlyFans/extras/OFLogin/start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "/OnlyFans/extras/OFLogin/start_ofl.py", line 27, in launch_browser
    opts = webdriver.FirefoxOptions()
AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'
`
I tried deleting all files and redoing setup from scratch, selenium and gecko are the latest versions 
all requirements were installed
using python3.9 as expected


sidenote:

everything was working fine 3 days ago, I changed nothing and it stopped working, auth started failling and logging me out of my OF account on my browser.
Checking out the issues on here I saw there was a new option with geckodriver and email/password, so I decided to try using geckodriver to make the script to work

but nothing is working

**Comment by secretiveolwagner** [comment]
@icemouton #945

Make sure the OF cookies is up-to-date

1. Clear OF cookies all that
2. Log in again
3. Paste your new `sess`
4. Evaluate from there
5.  set `auth` to `false` in your `config.json`, line 26 (this step is optional if you pasted the working info, since auth via browser is secondary method)

If you insist to use Selenium I would contact dev in private (see [the bottom of Mandatory Tutorial](https://github.com/DIGITALCRIMINAL/OnlyFans#mandatory-tutorial))

**Comment by icemouton** [comment]
I did all that,
Still, I run the script, get 10 denied attempts then my browser is logged out
get the `sess` token again, edit auth.json, retry, same results
I really don't insist on using Selenium I was super happy with how things worked 3 days ago...

**Comment by secretiveolwagner** [comment]
Mine looks like that as well

If you haven't already, use [OnlyFans Cookie Helper](https://github.com/M-rcus/OnlyFans-Cookie-Helper)

Have you tried using previous version?
Have you tried  another account?
Have you tried on different browser?
Have you tried different OS?

DIGITALCRIMINAL clearly stated any auth related problems will be ignored. Needless to say the script was developed on Windows. You are on your own unfortunately

**Comment by icemouton** [comment]
Alright so for the sake of argument I tried all versions from 6.2.1 on linux

Then gave up and did a new install on my windows machine, and configured that, added geckdriver when instructed to do so
and I get the same 
```
AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'
```
error... so it doesn't seem to be a linux specific issue

**Comment by secretiveolwagner** [comment]
Well, clearly you haven't tried everything I've suggested from above for instance step 5 from below

> @icemouton #945
> 
> Make sure the OF cookies is up-to-date
> 
> 1. Clear OF cookies all that
> 2. Log in again
> 3. Paste your new `sess`
> 4. Evaluate from there
> 5. set `auth` to `false` in your `config.json`, line 26 (this step is optional if you pasted the working info, since auth via browser is secondary method)
> 
> If you insist to use Selenium I would contact dev in private (see [the bottom of Mandatory Tutorial](https://github.com/DIGITALCRIMINAL/OnlyFans#mandatory-tutorial))

Because if you did set `auth` to `false`, you wouldn't get AttributeError in the first place

The reason why you get that error is because `sess`, `auth-id` or `user-agent` in `auth.json` is invalid/outdated, and the script attempts the second method (Selenium) to get the necessary information from OF website after you **successfully** logged in

**Comment by icemouton** [comment]
I did try with auth set to false, but it didn't help (except that it didn't try browser auth)
I used the cookie helper and double checked using the inspector from both chrome and firefox on 2 separate computers after each logout/logback in and updated the values in auth.json accordingly each time.

It runs, fails, then I'm logged out of that browser. I even tried with a different set of OF credentials a friend gave me to test it out, and it did the same thing.

I understand web browser (gecko/selenium) is supposed to be a last resort, but that's pretty much where I'm at so I'm trying to get it working on either linux or windows (even tried docker with the same resutls)

**Comment by secretiveolwagner** [comment]
[Read here](https://github.com/DIGITALCRIMINAL/OnlyFans/commit/191c9447e42b3f24eced04f55c8008415543dd25#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

**Comment by secretiveolwagner** [comment]
I can tell you the script is working just fine
![Screenshot from 2021-03-23 20-47-59](https://user-images.githubusercontent.com/69245900/112127263-5c90da00-8c19-11eb-99ec-3161f413a04e.png)

**Comment by icemouton** [comment]
I want to thank you for trying to help me even if you didn't have to.
This morning I got inspired and tried edge for the 1st time (never used it before lol), logged in, litterally just changed the sess token and user agent in the auth.json and now it works... 

So I have no idea why the tokens from chrome AND firefox didn't work.. but it's working **thank you** for pushing me to keep trying @secretiveolwagner
