### ISSUE TITLE
Error with SQLAlchemy

### ISSUE THREAD

**Issue by g0dzcsgo** [DIGITALCRIMINAL/OnlyFans#949]
Everytime i try to run the script on a new VPS after installing all the pip3 requirements i get:

Traceback (most recent call last):
  File "/root/of/start_ofd.py", line 9, in <module>
    main_test.check_config()
  File "/root/of/tests/main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "/root/of/helpers/main_helper.py", line 5, in <module>
    from sqlalchemy.ext.declarative import api
ImportError: cannot import name 'api' from 'sqlalchemy.ext.declarative' (/usr/local/lib/python3.9/dist-packages/sqlalchemy/ext/declarative/__init__.py)

I tried some known solutions, which included uninstalling it, and reinstalling it but still the same issue.

Hope someone on here has had the same issue, and maybe can provide a fix.

Regards.

**Comment by g0dzcsgo** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/discussions/937 (This does not solve it for me)

I got latest release and tried, but still not working.

**Comment by DIGITALCRIMINAL** [comment]
Use latest and run requirements
