### ISSUE TITLE
Support different run modes

### ISSUE THREAD

**Issue by E0911CD45B19686** [DIGITALCRIMINAL/OnlyFans#950]
Occasionally my scheduled task will time out, and this results in no downloads because the script first scrapes everything and then downloads everything (and if the site is slow scraping can take a long time). This isn't that big a deal, I can just increase the timeout or re-run on failure.

But I thought I'd ask if you'd be open to some architecture changes (by me/community) to support running in different modes. My current ideas are:

- Treat each creator as their own process to scrape and download. You could still parallelize by doing multiple creators at once (tee-hee 🤭)
- Move (or allow) some settings to be passed by CLI flags (e.g., the name of a creator(s). Use case here is more easily spreading the load over a full day by scraping a couple creators every couple of hours instead of all of them at once)
- Refactor some code to work more like a library then the above (or anything else) could be done by anyone and not have to be supported officially

**Comment by E0911CD45B19686** [comment]
Another one: New mode to only scrape stories, combined with CLi agruments to run the script hourly and not miss story content.

**Comment by DIGITALCRIMINAL** [comment]
You can run the script like a library, but I haven't documented it at all.

It would run something like this

`
        session_manager = api_helper.session_manager()
        api = OnlyFans.start(session_manager)
        api.set_auth_details(
            json_auth)
        apis = [api]
        valid = main_datascraper.start_datascraper(
            json_config, site_name_lower, apis=apis)`
