### ISSUE TITLE
Suggestion for webhooks

### ISSUE THREAD

**Issue by icemouton** [DIGITALCRIMINAL/OnlyFans#953]
I think it would be nice to add a notification via the webhook when the script fails (for auth failure or other reasons).

Since I have the script running in a cron, it can take me a while to notice it's broken if it does break.

So a nice message on my discord channel could be a great help.

It could be toggled by a boolean in the config json file too so it doesn't change the current behavior for all users.

Thank you,

**Comment by DIGITALCRIMINAL** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/708
