### ISSUE TITLE
I dont have another file extra_auth.json, when i open config i dont have in cofing supported sess username and fp.

### ISSUE THREAD

**Issue by milandzuris** [DIGITALCRIMINAL/OnlyFans#957]
![image](https://user-images.githubusercontent.com/42905545/112361368-94f4ee80-8cd3-11eb-89b2-6e85d5504a1d.png)
![image](https://user-images.githubusercontent.com/42905545/112361400-a1794700-8cd3-11eb-817f-d02687544c75.png)

I dont have another file extra_auth.json, when i open config i dont have in cofing supported sess username and fp.

**Comment by secretiveolwagner** [comment]
[What does Mandatory Tutorial mean in your language?](https://github.com/DIGITALCRIMINAL/OnlyFans#mandatory-tutorial), use search function or [go to Discussions](https://github.com/DIGITALCRIMINAL/OnlyFans/discussions)
Please translate into your own language when necessary

@DIGITALCRIMINAL close this thread thanks
