### ISSUE TITLE
Have start get this error on several models on onlyfans

### ISSUE THREAD

**Issue by P0rr** [DIGITALCRIMINAL/OnlyFans#959]
Download Failed: https://cdn2.onlyfans.com/files/4/4d/4d3a8783f3a10fddb440366d3445f016/1176x2208_a5ef7644bd628ed4e6df0e42284a76e9.jpg?Tag=2&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjIub25seWZhbnMuY29tXC9maWxlc1wvNFwvNGRcLzRkM2E4NzgzZjNhMTBmZGRiNDQwMzY2ZDM0NDVmMDE2XC8xMTc2eDIyMDhfYTVlZjc2NDRiZDYyOGVkNGU2ZGYwZTQyMjg0YTc2ZTkuanBnP1RhZz0yIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjE2NzExNDM0fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjE4NS44Ni4xMDYuMTc1XC8zMiJ9fX1dfQ__&Signature=BPwMPF-~V83od0plVqRLIHX3PD7g3EkzxG12caFdGGlG4GxRgDtwAteDpUc1FEw~99PzY5EscM7FnnmRpqYa0Ym7Z5MkZFfc8gQoNaAr1O1XYgwqJH4-ZpO4e2apnqbLAUKHb3TzCPtTafmIe9WXEgYYfV-sIbG-i~UeQhrEbCIGF311zBtUrtiBTqWBcXVYckp~PXZjJue9O6YtudGgI2nnMyPXZgSZVgAModUa7MTWa0p7jylGfhQ06-Ig-Qva-iKg55y-OaGi8NzA0DUAuUmQ6rx1xbws1hlHY6viZILJzlaHKigXVj-WMPJFlZ2nLI7wVDBp9A9HH~75bsq28Q__&Key-Pair-Id=APKAJZU4IULC2OKULHGA

-----

And its not downloade

have i done some thing wrong?

**Comment by DIGITALCRIMINAL** [comment]
Do you see the image on her profile?

**Comment by P0rr** [comment]
yes i see the pics on the webpage.. its get like 15 pics and they have like 2000+ pics / image same problem video

**Comment by freakish804** [comment]
im also getting exactly same kind of error on several models.

**Comment by Neuro-NX** [comment]
Can confirm the same issue is occuring after every scrape session, when getting videos. After awhile the progress bar shows red and states `Download failed:` and moves to the next file but same thing happens. The file output is not saved. When clicking the URI the video plays in the browser, so it is not due to locked/paid content.

**Comment by P0rr** [comment]
I still have this problem and have drive space. How do i get this error fixed?

**Comment by DIGITALCRIMINAL** [comment]
> I still have this problem and have drive space. How do i get this error fixed?

Are you able to click the failed download link and see the content?

**Comment by P0rr** [comment]
> > I still have this problem and have drive space. How do i get this error fixed?
> 
> Are you able to click the failed download link and see the content?

yes i can see the photo or video that i get this error on. And i have not been download too my hard drive

**Comment by freakish804** [comment]
> 
> 
> > I still have this problem and have drive space. How do i get this error fixed?
> 
> Are you able to click the failed download link and see the content?

yeah. i can see the photos/videos if i click the link. tried several times but every time its gets failed on those specific photos/videos.

**Comment by DIGITALCRIMINAL** [comment]
I'd need the post link to check what is wrong
