### ISSUE TITLE
User Agent Issue?

### ISSUE THREAD

**Issue by sonygoup** [DIGITALCRIMINAL/OnlyFans#96]
Trying to run the script but getting  this:
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan

I'm unsure if this the correct agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

Everything seems correct, I subbed yesterday

**Comment by DIGITALCRIMINAL** [comment]
Looks like a correct user agent

**Comment by nocilek** [comment]
Same error on my end. Might be due to a change site side? DownThemAll isn't working at the moment either.

**Comment by sonygoup** [comment]
Hmm idk what else it could be then. Did I need to choose a specific ?app or anyone. Because my results was a bit different than the pics (less)

**Comment by andonandon** [comment]
The site has updated with a session token which is distinct from the user agent. You can grab the session token from the same location as the auth_id and auth_hash. Repo owner should update the README at some point to reflect this.

**Comment by DIGITALCRIMINAL** [comment]
@sonygoup Sometimes the user has locked pictures that you have to pay for so it won't download.
@sonygoup @nocilek 
If you're using 2FA add in the sess cookie or turn it off.

@andonandon It's already in the readme. The sess token is optional. It still works on my end without the sess. I'm just using the auth_id and auth_hash and the correct user-agent.

**Comment by nocilek** [comment]
@DIGITALCRIMINAL Got mine working. Well, mostly. It connects and I can navigate the menu.

I fixed my issue by replacing my user_agent with the one @sonygroup listed.

Was running in PowerShell and it didn't like the Windows directory format when downloading, so going to try again in Ubuntu later.

**Comment by DIGITALCRIMINAL** [comment]
@nocilek tried with cmd?

**Comment by sonygoup** [comment]
@DIGITALCRIMINAL so it seems my user agent is correct but still nothing. Any idea on how to troubleshoot

**Comment by DIGITALCRIMINAL** [comment]
@sonygoup Honestly, the only way for me to really troubleshoot is to email me the cookies you're using.

**Comment by DIGITALCRIMINAL** [comment]
@sonygoup should look like this
Not real btw.
![image](https://user-images.githubusercontent.com/21285176/71552061-010f7680-29ed-11ea-8f4d-63702ae5ae7c.png)

**Comment by dilemmax** [comment]
Use this to find your user agent. Copy everything inside the box

https://www.whatismybrowser.com/detect/what-is-my-user-agent

**Comment by dilemmax** [comment]
> @DIGITALCRIMINAL Got mine working. Well, mostly. It connects and I can navigate the menu.
> 
> I fixed my issue by replacing my user_agent with the one @sonygroup listed.
> 
> Was running in PowerShell and it didn't like the Windows directory format when downloading, so going to try again in Ubuntu later.

I can run it from windows explorer. Just double-click on StartDatascraper.py to run it.

**Comment by dilemmax** [comment]
> @sonygoup should look like this
> Not real btw.
> ![image](https://user-images.githubusercontent.com/21285176/71552061-010f7680-29ed-11ea-8f4d-63702ae5ae7c.png)

hahaha. I like how you had to put a disclaimer in case people try to use it.

**Comment by sonygoup** [comment]
@DIGITALCRIMINAL Iegit just reordered them to the same way you had it and it worked instantly, no changes to nothing

Thanks
