### ISSUE TITLE
There's nothing to scrape.

### ISSUE THREAD

**Issue by dimer191996** [DIGITALCRIMINAL/OnlyFans#966]
Auth (V1) Attempt 1/10
Welcome Harry Potter | u130510738
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.23 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit

**Comment by Daironman78** [comment]
I am having the same issues and have even removed my version of Python and the scraper and downloaded the latest versions and it seemed to make things worse.  I have subs ending today and need to figure this out fast!!

**Comment by dimer191996** [comment]
this guy is fkn racist , he answer only white people . now he just close my issue

**Comment by DIGITALCRIMINAL** [comment]
> this guy is fkn racist , he answer only white people . now he just close my issue

LMAO IF I SHOWED YOU MY FUCKING SKIN COLOR, EVERYONE WOULD BE SURPRISED.

USE THE FUCKING SEARCH BUTTON. I DON'T CARE ABOUT ISSUES LIKE THIS ANYMORE, USE ANOTHER SCRAPER.
