### ISSUE TITLE
Python not recognized?

### ISSUE THREAD

**Issue by Daironman78** [DIGITALCRIMINAL/OnlyFans#967]
So I have been getting this issue now when I attempt to scrape data. A few days ago I was on and tried to scrape and I noticed some of the subs weren't showing so I figured, ahhh something must just be up with OF tonight so I didnt worry about it. Next day I did it and I was getting that AUTH message and none of my subs were pulling up. After looking around and trying things out I decided to remove the version of the scraper I had and put the latest version of Python on. Nothing was working so I went back to the 5.4 version and now I am getting this message. Can someone PLEASE help me out. I have a ton of subs and dont wanna lose all of them before i get a chance to do my thing. What do I need to do to get it back to how I was able to scrape before? 

C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4>python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\helpers\main_helper.py", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Aer3x** [comment]
try
`pip install requests`
or
`pip3 install requests`
