### ISSUE TITLE
Authentication loop

### ISSUE THREAD

**Issue by usergip** [DIGITALCRIMINAL/OnlyFans#97]
I keep getting an authentication loop even after putting in all the information. I have tried removing sess token and keeping sess token, keeping and removing user_agent, and the combination of both of them. Not quite sure what else to do at this point. I've checked past issues with authentication loop and tried the same solutions but nothing changed.
![auth](https://user-images.githubusercontent.com/59217905/71539184-0befdb80-2907-11ea-9c42-40fa781300b0.png)

**Comment by andonandon** [comment]
The site has updated with a session token which is distinct from the user agent. You can grab the session token from the same location as the auth_id and auth_hash. Repo owner should update the README at some point to reflect this.

**Comment by DIGITALCRIMINAL** [comment]
@usergip user-agent looks a bit short.
Should look something like this mayb?
`"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"`

**Comment by BiscuitDK** [comment]
I got the same error, have check my all my settings in user the Login IDs but note andonandon comment and found the "sess=tokenid" in the same location as auth_id, auth_hash when I pass that in to the config.json it worked.
![image](https://user-images.githubusercontent.com/59343463/71561933-88a4c600-2a7d-11ea-9052-e64ade36d63c.png)

**Comment by DIGITALCRIMINAL** [comment]
Didn't know the readme told people to put the user agent in the sess token...

I copied and pasted that line and forgot to change it
