### ISSUE TITLE
Unable to create session

### ISSUE THREAD

**Issue by Uberschall2519** [DIGITALCRIMINAL/OnlyFans#973]
I've checked my config and auth files against examples, they appear to be correct.

Getting error:
Proxy Not Set: socks5h://

Unable to create session
Now exiting.

I don't have a proxy set in Windows at all. Per another suggestion in another issue here, I did check that I can access checkip.amazonaws.com because I am running a Pihole on my network.

Auth File:
{
  "auth": {
    "username": "2790REDACTED",
    "auth_id": "2790REDACTED",
    "auth_hash": "",
    "auth_uniq_": "",
    "sess": "emncREDACTED",
    "app_token": "33d57REDACTED",
    "user_agent": "Mozilla\/5.0(Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/89.0.4389.90 Safari\/537.36",
    "email": "REDACTED@live.com",
    "password": "REDACTED",
    "support_2fa": false,
    "active": true
  }
}

Config File:

{
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": true,
    "infinite_loop": false,
    "loop_timeout": "0",
    "proxies": [
      "socks5h://"
    ],
    "cert": "",
    "random_string": "08745a70213611eb9ff5c025e91ef381"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "1",
        "auto_scrape_names": true,
        "auto_choice": "a",
        "auto_scrape_apis": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          "{site_name}"
        ],
        "file_directory_format": "{username}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": "",
        "auto_scrape_names": false,
        "auto_choice": "",
        "auto_scrape_apis": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          "{site_name}"
        ],
        "file_directory_format": "{username}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    }
  }
}

**Comment by DIGITALCRIMINAL** [comment]
Remove ""socks5h://" from proxies
