### ISSUE TITLE
Auth/Access Denied

### ISSUE THREAD

**Issue by Joakimgreenday** [DIGITALCRIMINAL/OnlyFans#974]
All it gives me is "Access Denied"
Might be because I use google login for Onlyfans, is there any bypass for this?

**Comment by ProjektPremium** [comment]
You aren't doing something correctly, that's the only time it gives off this error.

**Comment by sgaurav510** [comment]
same with me 
1
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Download geckodriver from https://github.com/mozilla/geckodriver/releases/tag/v0.27.0 and paste it in C:\Users\sgaur\Downloads\OnlyFans-master\OnlyFans-master\extras\OFLogin
DRIVER NOT FOUND

**Comment by ElusiveZatchmo** [comment]
I am also getting this and I also use Google for my login to OF

**Comment by Joakimgreenday** [comment]
> same with me
> 1
> Auth (V1) Attempt 1/10
> Access denied.
> Auth (V1) Attempt 2/10
> Access denied.
> Auth (V1) Attempt 3/10
> Access denied.
> Auth (V1) Attempt 4/10
> Access denied.
> Auth (V1) Attempt 5/10
> Access denied.
> Auth (V1) Attempt 6/10
> Access denied.
> Auth (V1) Attempt 7/10
> Access denied.
> Auth (V1) Attempt 8/10
> Access denied.
> Auth (V1) Attempt 9/10
> Access denied.
> Auth (V1) Attempt 10/10
> Access denied.
> Opening Browser
> Download geckodriver from https://github.com/mozilla/geckodriver/releases/tag/v0.27.0 and paste it in C:\Users\sgaur\Downloads\OnlyFans-master\OnlyFans-master\extras\OFLogin
> DRIVER NOT FOUND

I also did download the driver and put it there but it seems like the automated website tries to paste my login credentials in the OF login field, not attempt using Google login. And if I do it myself through google it says the browser isn’t safe. So it doesn’t matter if you have the gecko driver I believe.

**Comment by sgaurav510** [comment]
did it worked worked you? you got access granted?

**Comment by jdkjdji** [comment]
Hi there! I am relatively new here. But I just had that problem. LOL

I run the script on mac, and I use chrome as a browser. For some reason, the developer selects firefox as the main browser.

So when setting up, it asked me to download "geckodriver" from a URL. I downloaded it and put it in the folder indicated by the setup.

**What I did to solve this problem was to install the geckodriver through "brew install geckodriver" and download and install the latest version of firefox.**

I accessed OF and copied the "user_agent" from firefox.

And, I went back to running the Script. Tried to access, the failure: _"Auth (V1), Attempt 1/10, Access denied ... blah"_

I guess the fault is because it asks to resolve the captcha. Well, the browser was opened in its version -Geckodriver- and, I solved the captchas, it closed, and the download began.

**### I Guess IT'S CAPTCHA.**

**Comment by lucky1luc** [comment]
Does anyone actually read the instructions? What do you think user_agent means? It is the browser! You get that from the debugger in your browser and fill it out in the auth.json.

**Comment by goodboi69boi** [comment]
I am also having this issue. I have re-filled out all my information but it still fails and repeats failing.

Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.16 Minutes
Pausing scraper for 0 seconds.

**Comment by lucky1luc** [comment]
1. log off OF and close the browser, clear cookies if you want.
2. log on to OF and go to chats. Press F12, press the reload link in the debugger and start looking for the correct api2 calls with cookies etc
3. fill data in auth.json
4. possible change config.json to your own preferences...
5. try again

**Comment by Daironman78** [comment]
Anyone with a solution aside from copying the same info from the network debugger. I have all of the info copied correctly and am still getting that auth error.  Am I missing something? And it seems like my session changed the last 3 times I logged in and had to change it but still no results other than  Auth Attempt.....User not found.  Then Username = Username 

{
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "multithreading": true,
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "socks5_proxy": [],
    "cert": "",
    "global_user_agent": ""
  },
  "supported": {
    "onlyfans": {
      "auth": { 
        "username": "u13xxxxx",
        "auth_id": "13xxxxx",
        "auth_hash": "",
        "auth_uniq_": "",
        "sess": "8ohuskbm20nxxxxxxxxxxxxxrf",
        "fp": "8ed4e6b39cxxxxxxxxxxxxxeeddbaa51",
        "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0",
        "support_2fa": true
      },
      "settings": {
        "auto_choice": "",
        "auto_scrape_names": true,
        "auto_scrape_apis": true,
        "download_path": "{site_name}",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": ""

**Comment by salamihawk** [comment]
I'm also having the same issue as Daironman78. I cannot seem to find my app_token though. I've updated all the other information (username, auth_id, auth_hash, sess, etc..).

I've noticed that the information isn't visible when one follows the tutorial on the start page. Filtering for ?app finds nothing in the network debugger. I'm wondering if OF changed the way the HTTP calls work?

**Comment by leightonstarwalt** [comment]
Same issue here. Repeatedly getting the same message, despite all information in the config being correct.

**Comment by AlfredoP92** [comment]
I'm running version 4.0 (old, but has been working up till now). Getting the following message even after making sure my settings file is correct and current.

> Site: 0 = onlyfans | 1 = stars_avn | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
User not found
User not found
User not found
User not found
User not found
User not found
User not found
User not found
User not found
User not found
Auth (V2) Attempt 1/10
User not found
User not found
User not found
User not found
User not found
User not found
User not found
User not found
User not found
User not found
You're not subscribed to any users.
Site: 0 = onlyfans | 1 = stars_avn | 2 = 4chan | 3 = bbwchan

**Comment by vdmx-byte** [comment]
I solved this issue by updating to the latest release [v6.4.4](https://github.com/DIGITALCRIMINAL/OnlyFans/releases/tag/v.6.4.4). Was previously using v5.x which stopped working a few days ago. I would get the "User not found" response during authentication.

I am running Ubuntu 16.04 and my browser (i.e. user-agent) is Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0. I was previously using python 3.7 but installed/used python 3.9 as is required by v6.4.4. 

**To update to v6.4.4 without needing to re-download any content:**
For reference, `<OFDIR>` is your current OnlyFans DataScraper folder (folder that contains start_ofd.py).
1. Within `<OFDIR>` remove all files/folders **except** ".sites".
2. Download + extract the latest datascraper zip / tar release (v6.4.4) contents and move them to `<OFDIR>`.
3. Run the start_ofd.py script.

(This is not the only way to avoid re-downloading / copying the current ".sites" files. These were simply the steps I used.)

**Comment by AlfredoP92** [comment]
I tried updating to the latest release (v6.4.4), updated to python 3.9.4, installed C++ Build Tools, ran the `pip install -r requirements.txt` command in CMD, then tried launching the data scraper using both the `python start_ofd.py` command in CMD and double clicking "start_ofd.py" in the folder, but it hasn't resolved the issue. This is what appears when I started the v6.4.4 data scraper:

> H:\Applications\OnlyFans-v.6.4.4>python start_ofd.py
Traceback (most recent call last):
  File "H:\Applications\OnlyFans-v.6.4.4\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "H:\Applications\OnlyFans-v.6.4.4\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "H:\Applications\OnlyFans-v.6.4.4\helpers\main_helper.py", line 7, in <module>
    from classes.prepare_metadata import format_variables
  File "H:\Applications\OnlyFans-v.6.4.4\classes\prepare_metadata.py", line 1, in <module>
    from apis.onlyfans.onlyfans import media_types
  File "H:\Applications\OnlyFans-v.6.4.4\apis\onlyfans\onlyfans.py", line 10, in <module>
    from .. import api_helper
  File "H:\Applications\OnlyFans-v.6.4.4\apis\api_helper.py", line 6, in <module>
    import ujson
ModuleNotFoundError: No module named 'ujson'

Also, the '.settings' (does it actually have a '.' character in front of settings?) did not generate. Hidden folders are set to show, it's just not there. Searched for solutions for this as well, but came up with nothing. Version 4.0 included the settings folder, so it was a nonissue for me when I first started using the data scraper back then. Any help would be appreciated.

**Comment by leightonstarwalt** [comment]
> I solved this issue by updating to the latest release [v6.4.4](https://github.com/DIGITALCRIMINAL/OnlyFans/releases/tag/v.6.4.4). Was previously using v5.x which stopped working a few days ago. I would get the "User not found" response during authentication.
> 
> I am running Ubuntu 16.04 and my browser (i.e. user-agent) is Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0. I was previously using python 3.7 but installed/used python 3.9 as is required by v6.4.4.
> 
> **To update to v6.4.4 without needing to re-download any content:**
> For reference, `<OFDIR>` is your current OnlyFans DataScraper folder (folder that contains start_ofd.py).
> 
> 1. Within `<OFDIR>` remove all files/folders **except** ".sites".
> 2. Download + extract the latest datascraper zip / tar release (v6.4.4) contents and move them to `<OFDIR>`.
> 3. Run the start_ofd.py script.
> 
> (This is not the only way to avoid re-downloading / copying the current ".sites" files. These were simply the steps I used.)

I was able to upgrade and get it working again as well.. Didn't realize I was so many releases behind current.

**Comment by AlfredoP92** [comment]
I resolved my issue. It took several steps but I reinstalled python 3.9 (was complicated at first because I had registry issues preventing me from reinstalling), ran the `pip install -r requirements.txt` command, noticed a line saying that package "wheel" was not installed, so I ran the following command `python -m pip install --upgrade pip setuptools wheel`, reran the install requirements.txt command, then ran `start_ofc.py` and the .settings and .profiles folders generated and I was able to log into my account no problems.

**Comment by salamihawk** [comment]
I installed python 3.9, redownloaded the latest version of the scraper, moved the old stuff out and put the new stuff in, keeping the .sites directory, edited the default profile configuration file, but when I run it I get a "database is locked" error:

`Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
`
I dunno what sql has to do with any of this, but this is what I get

**Comment by Daironman78** [comment]
Well  I have been fooling with this thing for hours and did the steps that were suggested by yesterday by installing the latest version of the Scraper as well as Python and moving the stuff over to the older version's folder I had. Everything seemed to be going okay with me having to just keep install all of the requirements until I got to this point. 

C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4>python start_ofd.py
LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\.settings\config_backup.json)
Traceback (most recent call last):
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\tests\main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\helpers\main_helper.py", line 494, in get_config
    json_config, string = make_settings.fix(json_config)
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\classes\make_settings.py", line 104, in fix
    c = x.check_unique()
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\classes\prepare_metadata.py", line 321, in check_unique
    value = os.path.normpath(value)
  File "C:\Users\Tony_\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
**TypeError: expected str, bytes or os.PathLike object, not NoneType**

I have looked all through Google and cant really get any definitive answers as to what I should do. Just telling me that I have something with the script on the Json file that isnt configured right. Any suggestions. I thought I was making progress and thanks for the help so far vdmx-byte by the way.

**Comment by lucky1luc** [comment]
> 
> 
> I'm also having the same issue as Daironman78. I cannot seem to find my app_token though. I've updated all the other information (username, auth_id, auth_hash, sess, etc..).
> 
> I've noticed that the information isn't visible when one follows the tutorial on the start page. Filtering for ?app finds nothing in the network debugger. I'm wondering if OF changed the way the HTTP calls work?

App-token is (in firefox) in the debugger under column: headers, in the paragraph request-headers

**Comment by lucky1luc** [comment]
> 
> 
> I'm also having the same issue as Daironman78. I cannot seem to find my app_token though. I've updated all the other information (username, auth_id, auth_hash, sess, etc..).
> 
> I've noticed that the information isn't visible when one follows the tutorial on the start page. Filtering for ?app finds nothing in the network debugger. I'm wondering if OF changed the way the HTTP calls work?

Look for api2, no question mark, select the line with 200 GET, file me, look to the details. I have not entered my username but left it at "default", the auth_id, sess, app_token and user_agent should be enough

**Comment by LunarPenguin** [comment]
I would like to suggest that people in this issue who have not already solved their problems submit a new issue for their specific problem and include as much info as possible (`program output`, `program version`, `system` and any other potentially important info) to prevent cluttering up this issue even further.

**Comment by j-ktz** [comment]
Having this issue on the latest release. Did a fresh install and used the cookie helper and still getting auth issues.
