### ISSUE TITLE
No detecting subscriptions

### ISSUE THREAD

**Issue by edmundackah** [DIGITALCRIMINAL/OnlyFans#976]
Keep getting the following.

Choose Profile
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.

Checked auth.json all the login credentials are up to date

**Comment by DIGITALCRIMINAL** [comment]
Nothing I can do unless you give me your email and password.
