### ISSUE TITLE
Incomplete downloads 

### ISSUE THREAD

**Issue by lllllllllllllllllllI** [DIGITALCRIMINAL/OnlyFans#978]
What's your filename format

_Originally posted by @DIGITALCRIMINAL in https://github.com/DIGITALCRIMINAL/OnlyFans/issues/977#issuecomment-813492997_

"filename_format": "{filename}.{ext}",

Apolagizes for the accidental closure of the previous issue im still having this problem.

**Comment by LunarPenguin** [comment]
Could you post the output of the program? this would help us solve your problem
