### ISSUE TITLE
Unable to find auth, sess etc.

### ISSUE THREAD

**Issue by AlexBaldry** [DIGITALCRIMINAL/OnlyFans#980]
I got CTRL SHIFT I and refresh the page. Nothing anywhere.

**Comment by AlexBaldry** [comment]
![image](https://user-images.githubusercontent.com/48566683/113767597-ca0f3100-9716-11eb-9370-d8cbef44e5ce.png)

**Comment by Macmasteri** [comment]
Which browser do you use?

Click on "messages" on OF, then hit F12. In Chrome its under Network. Reload the page and then choose "chat". There you will fin what you looking for.

**Comment by nappyapp** [comment]
Just look under the "init" page it's there in your screenshot

**Comment by LunarPenguin** [comment]
I dont know which browser you use but the instructions are very similar.

1. Navigate to Onlyfans
2. Right-click on the page and select `inspect element` (or something similar)
3. in the new window that popped-up click on `network` (or something similar like `networking`)
4. press <kbd>F5</kbd> or click the `reload` page button
5. the api request should now show up like the ones in the screenshot above
6. click on the `init` request, a window to the right should open up.
7. check if your required values are present in the selected window (`Headers`)
8. if required values were not (all) in the selected window click on the `cookies` submenu, there you should find most of the required values.

I hope this helped.
