### ISSUE TITLE
Version 6.2.4 Problem

### ISSUE THREAD

**Issue by ProjektPremium** [DIGITALCRIMINAL/OnlyFans#984]
I like to use this version with my other account that I have, it was working up until maybe 20 minutes ago. I cannot log in. I can log in with later versions.

Edit; The error is this - 
Session IP: REDACTED

Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.1 Minutes
Pausing scraper for 0 seconds.

Is there a way to diagnose what the problem is? Same details are being entered in 6.2.4 as they are in 6.4.3 which I use with another account and it works for the later version but not the older version. With and without proxy/VPN works with the later version.

The other software I use also is working fine, it's just that I'm having trouble with 6.2.4

**Comment by mediaburnwayne** [comment]
looks like most older versions are broken for auth now as well. I have been using older versions due to errors in trying to get newer versions working. 
Just tried to configure 6.4.3 and getting following error after files are populated 


Traceback (most recent call last):
  File "N:\OnlyFans\start_ofd.py", line 14, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "N:\OnlyFans\datascraper\main_datascraper.py", line 11, in <module>
    import modules.onlyfans as m_onlyfans
  File "N:\OnlyFans\modules\onlyfans.py", line 31, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "N:\OnlyFans\extras\OFLogin\start_ofl.py", line 2, in <module>
    from seleniumwire import webdriver
ModuleNotFoundError: No module named 'seleniumwire'


GRRRRR

**Comment by ProjektPremium** [comment]
> 
> 
> looks like most older versions are broken for auth now as well. I have been using older versions due to errors in trying to get newer versions working.
> Just tried to configure 6.4.3 and getting following error after files are populated
> 
> Traceback (most recent call last):
> File "N:\OnlyFans\start_ofd.py", line 14, in
> import datascraper.main_datascraper as main_datascraper
> File "N:\OnlyFans\datascraper\main_datascraper.py", line 11, in
> import modules.onlyfans as m_onlyfans
> File "N:\OnlyFans\modules\onlyfans.py", line 31, in
> import extras.OFLogin.start_ofl as oflogin
> File "N:\OnlyFans\extras\OFLogin\start_ofl.py", line 2, in
> from seleniumwire import webdriver
> ModuleNotFoundError: No module named 'seleniumwire'
> 
> GRRRRR

For that you may have to run the requirements install again just to make sure, but I think you're right. The older version kicked me out mid rip of somebody. Switch over to the newer one and it works fine. Bad thing about having multiple accounts is having to use one version.

**Comment by kevinsheeks** [comment]
im a bit confused i had to update as well the new config.json confuses me it doesn't have sess,fp,auth,etc like the older versions
![onlyfans](https://user-images.githubusercontent.com/82110138/113899669-05ebda00-979b-11eb-91c4-23199620d9f1.PNG)

**Comment by Macmasteri** [comment]
> im a bit confused i had to update as well the new config.json confuses me it doesn't have sess,fp,auth,etc like the older versions
> ![onlyfans](https://user-images.githubusercontent.com/82110138/113899669-05ebda00-979b-11eb-91c4-23199620d9f1.PNG)

Exact same problem for me. I got confused.

What this geckodriver do? 
Auth via browser if email and password is filled | 60f6a5b
You must download geckodriver to auth via browser.
https://github.com/mozilla/geckodriver/releases/tag/v0.27.0

**Comment by Macmasteri** [comment]
Try to get geckordriver working. Got this message
user_agent required for: default
When clicking enter python closes. When adding the user agent it closes too.

**Comment by kevinsheeks** [comment]
lol we don't touch that actually goto .profiles folder keep clicking until you get to auth.json and fill in the stuff needed

**Comment by ProjektPremium** [comment]
Can you guys create your own issue threads? As I have stated, my issue is completely different to your issues. I have created my own software, but I still use the DC scraper on my smaller OF accounts to scrape with 6.2.4 which personally, I think is the best and fastest version in comparison to the rest.

I just want to get that working so I can run it remotely like I have been since it's release. So please, create your own issue threads.

**Comment by j-ktz** [comment]
Having the same error here.

**Comment by HoneyBadger116** [comment]
Had same issue. Seems like v6.4.4 is working. Just had to do the pip install again and copied over the .profiles' and .settings' .josn files and it worked fine.

**Comment by Macmasteri** [comment]
> lol we don't touch that actually goto .profiles folder keep clicking until you get to auth.json and fill in the stuff needed
> 
> sess,
> auth id
> user_agent

Thanks :)

**Comment by Macmasteri** [comment]
> Can you guys create your own issue threads? As I have stated, my issue is completely different to your issues. I have created my own software, but I still use the DC scraper on my smaller OF accounts to scrape with 6.2.4 which personally, I think is the best and fastest version in comparison to the rest.
> 
> I just want to get that working so I can run it remotely like I have been since it's release. So please, create your own issue threads.

Sorry mate!

**Comment by ProjektPremium** [comment]
Didn't mean to come off sounding like an asshole but yeah, just wanted to know why the older versions suddenly stopped but the newer ones are still fine.

**Comment by Themisssingport** [comment]
Im having the same issue

**Comment by DIGITALCRIMINAL** [comment]
Things break, just use the latest release.
