### ISSUE TITLE
Help with setting up

### ISSUE THREAD

**Issue by GreenMonkey1** [DIGITALCRIMINAL/OnlyFans#992]
Download new update follow the step to add account. 

added setting into .profiles/default/auth.json

but i am getting this 

`Site: 0 = onlyfans | x = Exit
0
Session IP: 8.0.0.8

Traceback (most recent call last):
  File "C:\Users\Desktop\Desktop\OnlyFans-v.6.4.4\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\Desktop\Desktop\OnlyFans-v.6.4.4\datascraper\main_datascraper.py", line 60, in start_datascraper
    apis = main_helper.process_profiles(
  File "C:\Users\Desktop\Desktop\OnlyFans-v.6.4.4\helpers\main_helper.py", line 602, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'`

**Comment by lucky1luc** [comment]
Did you execute the "pip install -r requirements.txt" command as documented. you HAVE to do that each time you download the software. It will download changed or updated packages for Python and for the software.

**Comment by GreenMonkey1** [comment]
Yea , and completed the Auth

**Comment by GreenMonkey1** [comment]
i notice that i get WARNING: deepdiff 5.2.3 does not provide the extra 'murmur'

**Comment by DIGITALCRIMINAL** [comment]
Use latest script

**Comment by GreenMonkey1** [comment]
still getting KeyError: 'auth'` even with the new copy
