### ISSUE TITLE
"sess" constantly resetting

### ISSUE THREAD

**Issue by looneycono** [DIGITALCRIMINAL/OnlyFans#994]
So not sure if this is a new security measure brought in by OnlyFans or an internal issue, but whenever I go to scrape the files, it automatically logs me out and resets the "sess" code.

Never had this problem prior to today, so assume it's a security update.

**Comment by JohnnyTowns94** [comment]
Double check your user_agent in the auth.json file.

**Comment by looneycono** [comment]
I updated the user_agent but it didn't fix the problem.

However, I did notice that the user_agent is different on Firefox (didn't work either), could the problem be rooted in there's multiple user_agents.

**Comment by looneycono** [comment]
Found the issue, the auth.json was opening with a default app so was converted. I created a proxy app to reset the default setting and got it working again.
