### ISSUE TITLE
Access Denied, don't know what issue is

### ISSUE THREAD

**Issue by williamck123** [DIGITALCRIMINAL/OnlyFans#998]
![Capture](https://user-images.githubusercontent.com/60608446/114096550-dddca380-988c-11eb-92dc-ccdc993969e4.PNG)
I am unsure if my auth info is correct or if its because I've not logged in on firefox, but it's spouting errors and I couldn't solve it myself.

**Comment by frisky-canadian** [comment]
I was having this problem too. I'm new but here's what lead to it working for me:
Logged out from browser, eventually logging in made me do a captcha.
Also, I updated the 'user agent' info in "auth", as well as 'sess'.

Managed to get it all working.

**Comment by lucky1luc** [comment]
see for self-help: https://github.com/DIGITALCRIMINAL/OnlyFans/issues/974
